### PR TITLE
Removing unnecesary SqlStore interface

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Removing unnecesary SqlStore interface

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
Great!

**Review by mgdelacroix — APPROVED** [review]

**Comment by jespino** [comment]
@lindalumitchell this is the kind of thing that affects the whole store, If the unit tests are passing, I would delegate this to the release testing, but is up to you :)

**Review by lindalumitchell — APPROVED** [review]
@jespino sounds good to me!

**Pull request merged**
