### PR TITLE
[MM-44030] Remove the read_channel permission to unfollow a thread

### PR DESCRIPTION
**Pull request by vish9812**
#### Summary

Remove the read_channel permission to allow a user to _unfollow_ a thread even if the user is no longer a member of the channel.

#### Ticket Link

JIRA - https://mattermost.atlassian.net/browse/MM-44030

#### Release Note

```release-note
Fixed a bug where mobile app crashes when unfollowing a thread of a channel that you're no longer member of.
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by ashishbhate — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @vish9812 
Tested, looks good to merge.
[E2E report](https://automation-dashboard.vercel.app/cycles/842b740d-0bce-4cad-801a-305a5171b4d3) looks good - no PR related failures

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
