### PR TITLE
MM-37721: Add prop for post preview before saving record.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Adds `previewed_post` prop _before_ saving the record so that two records aren't created for a new post.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37721

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by BenCookie95** [comment]
Is there a unit test we can write for this fix?

**Comment by mkraft** [comment]
> Is there a unit test we can write for this fix?

Yes, I've added one. Good call.

**Review by BenCookie95 — APPROVED** [review]

**Review by engineereng — APPROVED** [review]
Looks good to me!

**Comment by mkraft** [comment]
@furqanmlk I think you already tested this? The only change I made since your testing is I added a unit test.

**Review by furqanmlk — APPROVED** [review]
Working as expected 

image

image

**Pull request merged**
