### PR TITLE
MM-28835  Configure/update notices setting for TeamAdmin

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

notices urls are now config variables
team admin notification fixed

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28835

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by ogi-m — APPROVED** [review]
QA will test post-merge.

**Comment by reflog** [comment]
Manual cherry pick https://github.com/mattermost/mattermost-server/pull/15633

**Pull request merged**
