### PR TITLE
[MM-27622] Publish messages as SystemBot when a user is required

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR adds the channel restore and channel privacy endpoints to local mode using the System Bot to post the relevant messages when the endpoints are used.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24864
https://mattermost.atlassian.net/browse/MM-24600
https://mattermost.atlassian.net/browse/MM-27440

#### Release Note
```release-note
Added channel restore and channel privacy change endpoints to local mode using the system bot
```

### CODE REVIEW

**Review by wiersgallak — APPROVED** [review]
Thanks!

**Review by lindy65 — APPROVED** [review]
Thanks @mgdelacroix - this will be tested after merge 👍 

Will there be E2E tests for this?

**Review by jespino — APPROVED** [review]
LGTM

**Comment by mgdelacroix** [comment]
@lindy65 yes!! there are E2E tests already at the API layer on the server PR for the local mode actions, and more will be added on the `mmctl` side to test that both endpoints affected work properly :)

**Comment by lindy65** [comment]
Fantastic! Thanks so much @mgdelacroix :)

**Review by catalintomai — APPROVED** [review]

**Pull request merged**
