### PR TITLE
MM-36084 - Certificate Auth: Remove SAML dependency in license check

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Certificate-based authentication availability was being checked against SAML license feature flag. In the upcoming product repackaging, SAML has been moved from highest level tier (Enterprise - former E20) to mid-level (Professional) while Certificate-based authentication feature had no change and should stay in the highest sku. 

This PR changes the check to rely on the `FutureFeatures` flag and remains backward compatible for current and new skus.  

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-36084

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Comment by marianunez** [comment]
@jwilander @crspeller I am not completely familiar with this feature. I think I've covered the license checks for it based on the original implementation https://github.com/mattermost/mattermost-server/pull/8475 

Who would be a good person to test this feature with the new licenses ?

**Review by crspeller — APPROVED** [review]
Looks fine to me. Did a quick look for other license checks on this feature and didn't see any. 

@lindalumitchell Would know if any QA is done on this feature.

**Comment by jwilander** [comment]
@mkraft maybe you'd be a better set of eyes on this than me

**Comment by lindalumitchell** [comment]
@furqanmlk are you familiar with this one / able to QA-review it?

**Comment by marianunez** [comment]
@furqanmlk we can test this as part of https://github.com/mattermost/mattermost-webapp/pull/8554

**Comment by marianunez** [comment]
@furqanmlk will merge this and we can complete the testing with mattermost/mattermost-webapp#8554

**Comment by cwarnermm** [comment]
Docs updated via https://github.com/mattermost/docs/pull/5039

**Pull request merged**
