### PR TITLE
Migration of ChannelStore.GetMoreChannels to return plain error

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

Continuing with the campaing of migrating to return plain error in store layer, this time is the migration of `GetMoreChannels` in the `ChannelStore`

Fixes https://github.com/mattermost/mattermost-server/issues/14812

Jira ticket: https://mattermost.atlassian.net/browse/MM-26025

### CODE REVIEW

**Comment by rvillablanca** [comment]
Hi @agnivade plese create a ticket for this PR :)

**Comment by rvillablanca** [comment]
@agnivade is this stuck ?

**Comment by agnivade** [comment]
There's a flaky test. I restarted it.

**Comment by rvillablanca** [comment]
I suppose that is why several PRs were failing in not related test

**Pull request merged**
