### PR TITLE
MM-37691: Harden interactive dialog action

### PR DESCRIPTION
**Pull request by agnivade**
We strengthen some checks, forcing them to be changed
only via config.

https://mattermost.atlassian.net/browse/MM-37691

```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]

**Review by oh6hay — APPROVED** [review]
:+1:

**Comment by agnivade** [comment]
@oh6hay - You raised some issues previously with this. Are all of those not a concern?

**Pull request merged**
