### PR TITLE
[MM-34918] Update prepackaged version of autolink and GitHub

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Update prepackaged version of Autolink and GitHub

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34918

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by levb — APPROVED** [review]

**Comment by amyblais** [comment]
@DHaussermann Kind reminder for PR review.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Plugin version where changed as expected
- Plugins can be installed without the remote marketplace enabled
- Enabled but plugins as a precaution to confirm they are functional 

LGTM!

**Pull request merged**
