### PR TITLE
[GH-15742] Remove direct Store calls from the Api layer for the file api4/system.go

### PR DESCRIPTION
**Pull request by ataboo**
#### Summary
Moved two `Srv().Store` calls used for DB health check from `api4/system.go` to `app.go`.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15742

### CODE REVIEW

**Review by reflog — APPROVED** [review]

**Review by jespino — APPROVED** [review]
Nice work! Thanks @ataboo! :tada:

**Comment by jespino** [comment]
I going to do the QA myself, because is an API endpoint changes that is not exposed in the UI and is not easy to tests (make the database read only/stop the database...)

**Comment by jespino** [comment]
QA pass done, and working. I tried it stopping the database and making the database read only, both cases works as expected :)

**Comment by jespino** [comment]
Thanks @ataboo! everything works!

**Pull request merged**
