### PR TITLE
MM-15128 change openDialog to allow dialogs with no elements

### PR DESCRIPTION
**Pull request by andresoro**
#### Summary
This pull request is to add support for interactive dialogs with no elements (#10686). As far as I know, the small change here should be enough to add support on the server side. As for the web app, we still need to modify the InteractiveDialog component to not require elements. While my experience with react is limited, I think the change needed is to simply drop the .isRequired tag for the array of elements in that component and add proper checks/test cases. Also, as @hanzei said in #10686 we probably need an integration test as well.

If I am missing the scope of the problem, I'll gladly go back and rework the solution 👍. 

#### Ticket Link
Addresses #10686

### CODE REVIEW

**Comment by hanzei** [comment]
@jwilander Requesting your review on this, as you originally implemented this feature.

**Comment by hanzei** [comment]
@jasonblais Do you want to review this PR or is it enough for you to review the webapp one?

**Comment by jasonblais** [comment]
@hanzei I can review the webapp one only 👍

**Comment by hanzei** [comment]
Thank you for the PR @andresoro. Looking forward to the one for the webapp!

**Comment by aaronrothschild** [comment]
Updated docs to note that you can pass 0 elements in the array.  Posted to 5.14 branch https://github.com/mattermost/docs/blob/v5.14-documentation/source/developer/interactive-dialogs.rst

**Pull request merged**
