### PR TITLE
Avoid emails if user status is OOO or post is an auto response

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Fixes email issues from MM-10638:
* Email notification from `@System` is sent to the user who DMed the OOO user
* Email notifications are sent to the OOO user

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10638

### CODE REVIEW

**Comment by amyblais** [comment]
Hi @csduarte Would you be able to rebase this to 4.10 branch? We are planning to release this as part of 4.10.1 dot release.

**Comment by miguelespinoza** [comment]
@amyblais here's the change for the `release-4.10` branch: https://github.com/mattermost/mattermost-server/pull/8849

**Comment by cpanato** [comment]
I will spin up some test server just for testing lol

**Comment by cpanato** [comment]
merging this one, since we have the label

**Pull request merged**
