### PR TITLE
MM-15707 include missing localized strings

### PR DESCRIPTION
**Pull request by enahum**
#### Summary

This PR adds back some strings that were removed from en.json
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-15707

### CODE REVIEW

**Comment by jespino** [comment]
I think you need to merge master into the branch

**Comment by jespino** [comment]
This time is because there are some flaky test cases, I rerun the tests, lets see if now works.

**Comment by amyblais** [comment]
@jespino Was this cherry-picked to v5.12?

**Comment by jespino** [comment]
@amyblais It wasn't, but now it is :)

**Pull request merged**
