### PR TITLE
[MM-45561] Improve user top reactions query

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

Avoids join on Posts table to get ChannelId of a Reaction

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45561
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]
I thought we had already removed that `Posts` join... oh well. LGTM.

**Review by BenCookie95 — APPROVED** [review]

**Comment by plant99** [comment]
Hi @furqanmlk gentle reminder on this, please affirm if it's good to be merged without a QA review (or) this looks good to you.

**Review by furqanmlk — APPROVED** [review]
Thanks @plant99 
E2E passed and Smoke testing around reactions are working as expected.

**Pull request merged**
