### PR TITLE
Add german i18n for #7574

### PR DESCRIPTION
**Pull request by chclaus**
#### Summary
Add the missing german i18n key for `store.sql_command.get_by_trigger.app_error`

#### Ticket Link
[JIRA](https://mattermost.atlassian.net/browse/PLT-7218)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you @chclaus! Really appreciate your help here.

Similar to #7624, translations are actually managed in our Translation server at https://translate.mattermost.com. Would you like to help make the changes there?

You can search for the strings at https://translate.mattermost.com/de/mattermost/

image

If you're unable to find it, let me know and I can take a look.

**Comment by chclaus** [comment]
Ah ok. Thanks for this advice. Should I reproduce my changes there or is this hint just for future changes?

**Comment by jasonblais** [comment]
I would recommend making the changes at https://translate.mattermost.com/ instead.

Once a week we'll sync changes from the Translation Server to this repo, and as a result your changes will be overwritten if they're not reflected at https://translate.mattermost.com/.

I think there is an opportunity to clarify this in our contribution guidelines. I've realized we don't have a good description for how/where to make string changes.

**Comment by chclaus** [comment]
Okay, I'll give it a try ;)

**Comment by jasonblais** [comment]
Awesome! Let me know if you have any questions about it.

**Comment by lindy65** [comment]
Hi @chclaus,

Just popping in to find out how it went making the changes to the translation server?

Let us know if you need any assistance or have any questions :)

**Comment by chclaus** [comment]
Hej @lindy65 ,

I made the changes of another PR at the transalation server but can't find the key of this PR. (`store.sql_command.get_by_trigger.app_error`) :(

**Comment by jasonblais** [comment]
Hey @chclaus, here's the particular string: https://translate.mattermost.com/de/mattermost/translate/#search=Der%20Befehl%20konnte%20nicht%20abgerufen%20werden&sfields=source,target&unit=513156

Looks like you need to tick the `Location` box to find a specific key: 
image

**Comment by jasonblais** [comment]
@chclaus I'll close this PR off then, although let me know if you have any other questions about it.

PS: You're welcome to join our German localization channel if you're interested: https://pre-release.mattermost.com/core/channels/i18n-german. It's got close to 40 members already!

**Comment by chclaus** [comment]
Oh. Thanks a lot. I‘ll join the channel

**Pull request closed without merging**
