### PR TITLE
#146 Added option to mark TOS as mandatory or optional

### PR DESCRIPTION
**Pull request by harshilsharma**
#### Summary
Added option to mark TOS as mandatory or optional.

*(Edit: Implements part 2 of https://mattermost.atlassian.net/browse/MM-12411)*

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12400

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs) - https://github.com/mattermost/mattermost-api-reference/pull/403
- [x] All new/modified APIs include changes to the drivers
- [x] Has UI changes - not yet implemented
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by harshilsharma** [comment]
Do not merge this as webapp changes for this have not been implemented yet.

**Comment by jasonblais** [comment]
@harshilsharma Is this part 2 of https://mattermost.atlassian.net/browse/MM-12411?

**Comment by harshilsharma** [comment]
@jasonblais yes, that's right.

**Comment by jasonblais** [comment]
Sounds good @harshilsharma - added that as a note in the PR description as well for reviewers.

**Comment by harshilsharma** [comment]
@lieut-data this PR can be closed. Updated PR with mandatory/optional TOS removed is here - https://github.com/mattermost/mattermost-server/pull/9731

**Comment by jasonblais** [comment]
Closing in favor of https://github.com/mattermost/mattermost-server/pull/9731

**Pull request closed without merging**
