### PR TITLE
MM-42049 - license endpoint not working

### PR DESCRIPTION
**Pull request by pablovelezvidal**
#### Summary
Initial investigation for the saving license issue. Workers not starting/stopping correctly when prevLicense/nextLicense features are validated.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42049

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AGMETEOR — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Review by stevemudie — APPROVED** [review]
Passed with flying colors! Thanks for the walkthrough on this @pablovelezvidal it's all set from what I can see.

**Review by jespino — APPROVED** [review]

**Comment by marianunez** [comment]
@pablovelezvidal heads up that the changes here were reverted in master. Please reopen a PR to re-introduce these changes

**Pull request merged**
