### PR TITLE
bump mattermost/mattermost-build-server to use go 1.12.9

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
the new image `mattermost/mattermost-build-server:sep-17-2019` uses go version `1.12.9`

### CODE REVIEW

**Comment by hanzei** [comment]
Blocked by https://github.com/mattermost/mattermost-server/pull/12250

**Comment by hanzei** [comment]
It works now :tada:

**Comment by hanzei** [comment]
@cpanato Please also take a look and see if this is fine

**Comment by cpanato** [comment]
if we merge this i need to update the release cut job and the jenkinsfile for 5.16 branch

this is a note to myself

**Comment by hanzei** [comment]
@cpanato Are we good to merge this after the pipeline has passed?

**Comment by hanzei** [comment]
@cpanato Build is green now

**Pull request merged**
