### PR TITLE
upgrade DB for 5.35

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
upgrade DB for 5.35

#### Ticket Link
N/A

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by cpanato** [comment]
we might cherry pick this to release-5.35

**Review by jespino — APPROVED** [review]
LGTM

**Comment by cpanato** [comment]
besides the cherry-pick for the release branch 5.35 and the follow-up or to add the preparation for the next upgrade do we need to do anything else?

@jespino @agnivade

**Comment by agnivade** [comment]
I'd perhaps check with @streamer45 and @ethervoid for confirmation.

**Comment by cpanato** [comment]
thanks @agnivade for pointing the correct persons

**Comment by streamer45** [comment]
> besides the cherry-pick for the release branch 5.35 and the follow-up or to add the preparation for the next upgrade do we need to do anything else?
> 

I'd say no. As long as the release branch gets these changes in we should be good.

**Review by streamer45 — APPROVED** [review]

**Comment by jespino** [comment]
@cpanato I don't see any special treatment needed for this.

**Comment by cpanato** [comment]
merging and will cherry pick to release-5.35 branch

**Pull request merged**
