### PR TITLE
MM-40686: Added feature flag for group member dn lookup.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Added a new feature flag.

#### Related PRs

* https://github.com/mattermost/enterprise/pull/1125

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-40686

#### Release Note

```release-note
Added a new feature flag MM_FEATUREFLAGS_NormalizeLdapDNs.
```

### CODE REVIEW

**Comment by coltoneshaw** [comment]
@mkraft - This just becomes a config.json feature flag with this?

**Comment by spirosoik** [comment]
@mkraft sorry for abusing your PR :), but I was testing some changes in spinwicks

**Review by streamer45 — APPROVED** [review]

**Comment by mkraft** [comment]
> @mkraft - This just becomes a config.json feature flag with this?

The feature flags are not configured in config/config.json, they're managed via environment variables.

**Comment by amyblais** [comment]
> > @mkraft - This just becomes a config.json feature flag with this?
> 
> The feature flags are not configured in config/config.json, they're managed via environment variables.

cc @coltoneshaw

**Pull request merged**
