### PR TITLE
MM-24652: Bump golangci to 1.25.1

### PR DESCRIPTION
**Pull request by agnivade**
#### Ticket link

https://mattermost.atlassian.net/browse/MM-24652

### CODE REVIEW

**Comment by agnivade** [comment]
There is no burning reason to do this. Mainly to keep things up to date. Feel free to reject if you feel it's not worth it. 0/5.

**Comment by hanzei** [comment]
@agnivade The CI failed: https://app.circleci.com/pipelines/github/mattermost/mattermost-server/9440/workflows/95afc2cd-462c-4438-8eae-5493ee8f2519/jobs/44411/tests

More flaky tests?

**Comment by agnivade** [comment]
Yes .. it's on my radar: https://mattermost.atlassian.net/browse/MM-24611

**Comment by metanerd** [comment]
Would it make sense to do the same for enterprise at the same time?

**Comment by agnivade** [comment]
gentle ping @josephbaylon

**Pull request merged**
