### PR TITLE
Allow inline JSON in config.json for advanced logging config

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR allows customers to embed proper JSON as Advanced Logging Config in `config.json` without escaping the JSON.

The fields `LogSettings.AdvancedLoggingConfig`, `ExperimentalAuditSettings.AdvancedLoggingConfig`, and `NotificationLogSettings.AdvancedLoggingConfig` now support multi-line JSON, escaped JSON as a string, or a filename.

This is a non-breaking change, despite changes to a model struct. All previously valid config files are still valid.

Example:
```
...
    "LogSettings": {
        "EnableConsole": true,
        "ConsoleLevel": "DEBUG",
        "ConsoleJson": false,
        "EnableColor": true,
        "EnableFile": true,
        "FileLevel": "INFO",
        "FileJson": true,
        "FileLocation": "",
        "EnableWebhookDebugging": true,
        "EnableDiagnostics": true,
        "EnableSentry": true,
        "AdvancedLoggingConfig": {
            "file_1": {
                "Type": "file",
                "Format": "plain",
                "Levels": [
                    {"ID": 5, "Name": "debug", "Stacktrace": false},
                    {"ID": 4, "Name": "info", "Stacktrace": false},
                    {"ID": 3, "Name": "warn", "Stacktrace": false},
                    {"ID": 2, "Name": "error", "Stacktrace": true},
                    {"ID": 1, "Name": "fatal", "Stacktrace": true},
                    {"ID": 0, "Name": "panic", "Stacktrace": true}
                ],
                "Options": {
                    "Compress": true,
                    "Filename": "mattermost_logr.log",
                    "MaxAgeDays": 1,
                    "MaxBackups": 10,
                    "MaxSizeMB": 500 
                },
                "MaxQueueSize": 1000
            }
        }
    },
...
```

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43077

#### Release Note
```release-note
Advanced logging configuration now supports inline JSON and no longer needs to be escaped to a single line string.
```

### CODE REVIEW

**Review by isacikgoz — COMMENTED** [review]
Looks good, would it be possible to add an automated test for parsing both new and old configs and validate it's working?

**Comment by wiggin77** [comment]
> add an automated test for parsing both new and old configs

Test cases added for escaped JSON.

**Review by isacikgoz — APPROVED** [review]
Thanks for adding the tests cases, LGTM! Just noticed that we don't use `json.RawMessage` or `[]byte` in any config type. Although they are practically cast-able to `string`, wondering if there was a reason not using them 🤔 cc @agnivade

**Comment by agnivade** [comment]
Don't think there's a reason. Should be fine to use. :+1:

**Comment by marianunez** [comment]
Lacking some domain knowledge here so will defer the review to @agnivade

**Comment by agnivade** [comment]
Ibrahim's review is good enough for me :)

**Comment by wiggin77** [comment]
@amyblais this PR has been reverted.  There was a Release Note item included which I've removed from the PR description, but it may have already been picked up for the changelog.

**Comment by amyblais** [comment]
Thanks for letting me know!

**Pull request merged**
