### PR TITLE
Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.3

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Cherry pick  of #21493 into `release-7.3` branch.

#### Release Note

```release-note
Adds a new schema migration to ensure ParentId column is dropped from the Posts table. Depending on the table size, if the column is not dropped before; A significant spike in DB CPU usage is expected on MySQL databases. Writes to the table will be limited during the migration.  
```

### CODE REVIEW

**Comment by agnivade** [comment]
Ah I think the MPA changes has somehow affected older release branches. This might take some time to sort out. It's not super urgent to immediately backport it, so maybe just wait for a while.

**Review by agnivade — APPROVED** [review]

**Comment by isacikgoz** [comment]
@phoinixgrr @spirosoik Is there a way we can fix these builds?

**Comment by phoinixgrr** [comment]
> @phoinixgrr @spirosoik Is there a way we can fix these builds?

🤷 
I would start with troubleshooting the failing pipeline step by step. 
Starting with `check-mattermost-vet`, throwing: 

```
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
# github.com/mattermost/focalboard/mattermost-plugin/product
../focalboard/mattermost-plugin/product/api_adapter.go:127:34: a.api.permissionsService.HasPermissionTo undefined (type "github.com/mattermost/mattermost-server/v6/product".PermissionService has no field or method HasPermissionTo)
make: *** [Makefile:738: vet] Error 2

```

**Comment by isacikgoz** [comment]
@phoinixgrr I think the issue here is it's trying to build Boards with server but we shouldn't do that in version `7.3` or `7.4` right? My changes are irrelevant from that anyway. I think any cherry-pick would result in the same error.

**Comment by phoinixgrr** [comment]
> @phoinixgrr I think the issue here is it's trying to build Boards with server but we shouldn't do that in version `7.3` or `7.4` right? My changes are irrelevant from that anyway. I think any cherry-pick would result in the same error.

How did we reach that assumption? 

`release-7.3` is reported as successfully build before this cherry pick. 

https://app.circleci.com/pipelines/github/mattermost/mattermost-server/37694/workflows/ef6b2ba7-3cd7-4ce4-b3e7-ef25bdba736a

**Comment by isacikgoz** [comment]
> How did we reach that assumption?

Yeah I know, *it's interesting*.. actually that's the part I'm curious about. Because my changes are totally irrelevant with boards etc but it's still trying to build together. It's must be something with the pipeline.

**Comment by phoinixgrr** [comment]
> > How did we reach that assumption?
> 
> Yeah I know, _it's interesting_.. actually that's the part I'm curious about. Because my changes are totally irrelevant with boards etc but it's still trying to build together. It's must be something with the pipeline.

Yes. Most probably, Seems to be related to the changes introduced to support Multi Product Architecture. 
There is a new step called "configure-multirepo" in this build. 
Introduced with https://github.com/mattermost/mattermost-server/pull/20783 

I guess this is were things go south. 
Feel free and raise a ticket in our board, for us to investigate. Thanks Ibrahim

**Comment by isacikgoz** [comment]
@phoinixgrr Actually the last successful build was 20 days ago on this branch, I'd suspect some of the recent PRs, just to give you a hint 😛

**Pull request merged**
