### PR TITLE
MM-52261: Remove boards language selector, use Language in Display Settings

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
Drops Boards language selector and leverages global language selector and top-level intl infrastructure. `getMessages` has been made compatible with option keys from the main language selector in Display Settings.

Because of this, a few languages are no longer available in Boards—Catalan, Greek, Indonesian, and Occitan. Options with "alpha" labels could be added for these languages if desired.

Bulgarian and Romanian are [supported languages](https://handbook.mattermost.com/contributors/join-us/localization#translation-maintenance) but remain unavailable as they haven't been translated yet. 

| Language | Option Available in Display Settings | Source Translations Available in Boards |
|--------|--------|--------|
| Catalan (41%) | No ❌ |  Yes ✅ - `ca` |
| Green (10%) | No ❌ |  Yes ✅ - `el` |
| Indonesian (31%) | No ❌ |  Yes ✅ - `id` |
| Occitan (31%) | No ❌ |  Yes ✅ - `oc` |
| Bulgarian | Yes ✅ |  No ❌ |
| Romanian | Yes ✅ |  No ❌ |

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-52261

#### Screenshots
imageimage

#### Release Note

```release-note
Language setting in Boards removed; the main language setting under `Settings -> Display Settings` now covers Boards. Boards previously supported Catalan, Greek, Indonesian, and Occitan, but since these 4 languages were only partially translated (<40%; Boards-only), they have been removed until more areas of Mattermost are translated into these languages.
```

### CODE REVIEW

**Comment by wuwinson** [comment]
@calebroseland How does this impact users who are currently using the 4 languages impacted? How does this also change how people select languages in Boards?

**Comment by calebroseland** [comment]
@wuwinson users who are currently using any of those 4 languages will be reverted back to whichever global language setting they've chosen in Display Settings—Boards now follows this setting instead of having its own.

**Comment by wuwinson** [comment]
Thanks for clarifying @calebroseland. This makes sense to do, but hoping we can figure out some options to make the transition smoother for impacted users. Will queue up a discussion topic for tomorrow's weekly.

**Comment by calebroseland** [comment]
@wuwinson the release note here has been updated—feel free to adjust/rephrase if desired. A heads up note could perhaps go out in the release before this goes out as discussed.

**Comment by wuwinson** [comment]
> @wuwinson the release note here has been updated—feel free to adjust/rephrase if desired. A heads up note could perhaps go out in the release before this goes out as discussed.

Looks great, thanks @calebroseland! Is this change going out in the May v7.11 release or the one after that?

**Comment by calebroseland** [comment]
@wuwinson TBD, but I think given the close timing to the cutoff this should probably go in after v7.11.

**Comment by wuwinson** [comment]
> @wuwinson TBD, but I think given the close timing to the cutoff this should probably go in after v7.11.

Sounds good! I'll get the early notice out for v7.11 in that case.

**Review by sbishel — APPROVED** [review]
Awesome work! LGTM!

**Review by lindy65 — APPROVED** [review]
Thanks @calebroseland - looks good to me 👍 

Language setting has been removed from Boards.  When changing language setting from Channels > Settings > Display > Language, the language is changed in Boards.

**Comment by lindy65** [comment]
@wuwinson - leaving the spinwick up for you in case you want to take a look

**Review by wuwinson — APPROVED** [review]
Looks good! Nice work @calebroseland! :+1:

**Pull request merged**
