### PR TITLE
Change link to redirect email notifications to landing page

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
This change completes the use of the landing page to redirect directly to the native application that were done with this PR:
https://github.com/mattermost/mattermost-webapp/pull/2299

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-8255
[mattermost/desktop#628](https://github.com/mattermost/desktop/issues/628)

### CODE REVIEW

**Comment by esethna** [comment]
Adding the Awaiting PR label as we are working on the flow for the landing page and the client PRs (webapp and mobile) need to be merged first, so we don't break email notification links

**Comment by hanzei** [comment]
Hey @esethna,

Can you provide some next steps for this PR? It has been staying open for almost half a year now.

**Comment by devinbinnie** [comment]
Closing in favour of https://github.com/mattermost/mattermost-server/pull/13362

**Pull request closed without merging**
