### PR TITLE
translations PR 20180511

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1206

### CODE REVIEW

**Comment by kaakaa** [comment]
`ja` LGTM

**Comment by jasonblais** [comment]
Thanks all!

@enahum Looks like the build is failing

**Comment by enahum** [comment]
@jasonblais rebased the PR, lets see if that solves it cause the failure seems to be a random test nothing to do with the PR

**Comment by enahum** [comment]
@jasonblais not sure why this thing is failing but it does not have anything to do with the translations

**Comment by jasonblais** [comment]
@enahum will someone else need to take a look at it?

**Comment by enahum** [comment]
@jasonblais probably.

@jwilander do you have an idea of why is this build failing? I cannot seem to figure it out looking at the jenkins logs

**Comment by enahum** [comment]
I think I fixed it, a few translations had errors in the var names

**Comment by wget** [comment]
@enahum Sorry :-/ This is what happens when I don't have the time to launch my Arch Linux CI just after having translated, typos happens. Sorry.

**Comment by jasonblais** [comment]
@enahum Still fails

**Comment by jwilander** [comment]
Looking..

**Comment by jwilander** [comment]
The build server is down currently.

**Comment by enahum** [comment]
Yeah I think I’ve managed to fix the failure but with jenkins down... when jenkins is back up I’ll see if I actually fixed the issue or not

**Pull request merged**
