### PR TITLE
Adding missing Order to postList in Post().Get()

### PR DESCRIPTION
**Pull request by carmo-evan**
#### Summary
Adds postIds to the PostList.Order slice to make sure it can be sorted.
#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/11006

### CODE REVIEW

**Comment by carmo-evan** [comment]
> The problem with this, is, you are adding and arbitrary (generated by the database) order to the posts there. You are not sorting at all the SQL query, so... you are returning an arbitrary order. And actually I'm not sure how the webapp is using the result here, but it can generate problems too.

I see. What I'm aiming to fix here though is the fact that without those IDs, the list is not sortable at all. Calling [SortByCreateAt()](https://github.com/mattermost/mattermost-server/blob/master/model/post_list.go#L103-L107) fails silently because it expects those ids to be there. Currently there's just one, so the list is never sorted. I'm 3/5 there isn't any assumption of order at the point where the list is retrieved from the database.

**Comment by carmo-evan** [comment]
> The problem with this, is, you are adding and arbitrary (generated by the database) order to the posts there. You are not sorting at all the SQL query, so... you are returning an arbitrary order. And actually I'm not sure how the webapp is using the result here, but it can generate problems too.

Thinking about again, if we do want it to be ordered by default, maybe we should add `ORDER BY CreateAt DESC` to the query? That's how `getFlaggedPosts` works.

**Comment by jespino** [comment]
I have to think about it and investigate the implications in the rest of the code, mainly frontend code.

**Comment by jasonblais** [comment]
Hey @jespino, have you had a chance to review the implications?

**Comment by jespino** [comment]
@jasonblais Nope, Still trying to find the time to investigate it a bit more.

**Comment by jasonblais** [comment]
@jespino Wondering if the investigation would be worth queuing as a Jira ticket for the platform team? Let me know what you think

**Comment by teresa-novoa** [comment]
@jasonblais @jespino where are we with this PR? Thanks!

**Comment by jasonblais** [comment]
@jespino wondering if we should close this PR for now, or create a ticket to investigate the implications of the changes here?

Given this was submitted in May/2019, I'm not sure how relevant the changes still are?

**Comment by teresa-novoa** [comment]
> @jespino wondering if we should close this PR for now, or create a ticket to investigate the implications of the changes here?
> 
> Given this was submitted in May/2019, I'm not sure how relevant the changes still are?

**Comment by jespino** [comment]
Yes, I think we can discard this, Is not needed, we still can investigate it, but anyway, we can move that to a ticket if we want to investigate it.

**Comment by jasonblais** [comment]
Thanks Jesús. I'll close the PR for now as per your comment. Thanks @carmo-evan for the contribution, hope you are doing well :)

**Pull request closed without merging**
