### PR TITLE
MM-35103 Replies in a thread with an initial mention triggers notification each time

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

only process parent post mentions for threads in order to autofollow
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-35103
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@reflog Is this bug only on master, or does it also reproduce on release-5.35 branch?

**Comment by reflog** [comment]
@amyblais master only

**Review by hmhealey — APPROVED** [review]

**Review by calebroseland — COMMENTED** [review]
Unfortunately this still repros for me.

(`@sysadmin` received notifications and plain-replies appear as mentions; happened for both `@user` and `@here` root mentions)
CleanShot 2021-04-26 at 23 47 32@2x

**Comment by reflog** [comment]
Hey @calebroseland - I re-tested again and it seems to work. Let's sync up today to help me reproduce the issue

**Review by ogi-m — APPROVED** [review]
Working as expected now 👍🏻

**Pull request merged**
