### PR TITLE
Fixes indentation.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Re-opened https://github.com/mattermost/mattermost-server/pull/16892 but with the correct fix.

#### Ticket Link

n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]
LGTM !

**Review by jespino — APPROVED** [review]

**Comment by hmhealey** [comment]
Any chance of getting this in soon? The Elasticsearch container on my local instance has constant issues, so I'd like to be able to not run it.

**Pull request closed without merging**
