### PR TITLE
PLT-4752 Add update OAuthApp endpoint for APIv4

### PR DESCRIPTION
**Pull request by n1aba**
#### Summary
Implement APIv4 endpoint for editing OAuth Applications, add respective test
This PR is resubmit of https://github.com/mattermost/mattermost-server/pull/7361

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/4752

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs)
- [x] All new/modified APIs include changes to the drivers

### CODE REVIEW

**Comment by jwilander** [comment]
We can ignore the `continuous-integration/jenkins/pr-merge ` build, it's from a new build server that isn't stable yet

**Comment by jwilander** [comment]
Marking as ready to merge as this has already been reviewed at #7361

**Comment by jwilander** [comment]
@n1aba could you give this a rebase?

**Comment by n1aba** [comment]
@jwilander I have rebased, please consider my changes

**Pull request merged**
