### PR TITLE
Mm 31258 compliance monitoring csv headers

### PR DESCRIPTION
**Pull request by maxerenberg**
#### Summary
This pull request moves the UserType field in the CSV compliance report into the right column. Currently this field is at the end of the row, causing headers and data to be misaligned.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31258

#### Release Note
```release-note
Compliance report field headers are now correctly aligned.
```

#### Unit tests
https://github.com/mattermost/enterprise/pull/909

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
Just add a link to the related PR in Enterprise in the Description

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Test passed ✅ 

image

**Review by adamjclarkson — APPROVED** [review]

**Pull request merged**
