### PR TITLE
Use always strings for cache keys

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
The cache keys was using `interface{}` for the keys, which was used only for
store some hash as integers related to the opengraph and post metadata cache.
Because we can easily express that data as a string, I removed that problem and
added the concrete string type to the keys at the cache.

### CODE REVIEW

**Comment by jespino** [comment]
@lindy65 this is touching the cache which affects a lot of different places in the app, but at the same time is mainly changing the types used in the code, which means probably is almost everything captured by the compiler itself. From my perspective, we can be super picky and tests the whole cache, or we can be more pragmatic and test only the post metadata/opengraph stuff what is the part with a bit of real changes.

**Comment by lindy65** [comment]
Thanks @jespino, is there a Jira ticket for this PR?

When you say `test only the post metadata/opengraph stuff` - does that mean testing opengraph images and their metadata? Or are there other things to test around this?

**Comment by jespino** [comment]
@lindy65, no it wasn't but I created it here: https://mattermost.atlassian.net/browse/MM-21788

About testing metadata/opengraph yes, I'm talking about images and metadata from links in the posts. I'm almost sure there is nothing else around metadata/opengraph.

**Comment by agnivade** [comment]
I suggest the title to be "Always use strings for cache keys", or even "Use strings for cache keys".

**Pull request merged**
