### PR TITLE
upgrade db to 5.16

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Upgrade DB to 5.16

#### Ticket Link
n/a

### CODE REVIEW

**Comment by jespino** [comment]
Sure, they are related to the new invitation tokens, we need more space because the guest invitations can be way longer.

**Comment by jespino** [comment]
Looks good to me but we should wait until the release date is closer to allow posible database changes related to bugs

**Comment by cpanato** [comment]
@jespino @hanzei i will be merging this when green, we already cut rc1

**Pull request merged**
