### PR TITLE
MM-31054 demote user

### PR DESCRIPTION
**Pull request by anurag6713**
#### Summary
While demoting the user, remove as Team & Channel admin as well.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31054

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]
**Lgtm**

**Review by sbishel — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Added Test case [MM-T3898](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T3898)


image

**Pull request merged**
