### PR TITLE
Bump zoom plugin version to v1.3.0

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
Roll back Zoom version from 1.2.0 to 1.1.2 equivalent commit (named `v1.3.0`)

Relevant Conversation
https://community.mattermost.com/core/pl/ppjt5k8e9pr898xqiqxios3bxy

plugin | prev | new 
--- | --- | ---
zoom | `v1.2.0` | `v1.3.0`

### CODE REVIEW

**Comment by DHaussermann** [comment]
@jfrerich  or @lieut-data is there a quick alternative to verify this on a server and the cloud server won't build.

**Comment by lieut-data** [comment]
@DHaussermann, we're missing plugin signatures for this plugin -- hence the build failure. I don't think we can validate until that's resolved. (I've messaged on Mattermost re: this.)

**Comment by jfrerich** [comment]
@DHaussermann @lieut-data @levb, the Zoom Plugin `v1.3.0` has been submitted and released https://github.com/mattermost/mattermost-plugin-zoom/releases/tag/v1.3.0

**Comment by DHaussermann** [comment]
@jfrerich Any thoughts on why the cloud server build would still be failing?

**Comment by lieut-data** [comment]
Thanks, @jfrerich -- @ali-farooq0, can you work with Jason to show him the ropes on how we currently sign plugins and work towards getting 1.3.0 ready for prepackaging/marketplace?

**Comment by jfrerich** [comment]
Thanks for helping clarify what was needed in this particular "roll-back"/"bump" mess :) @ali-farooq0, hit me up in MM whenever you are ready!

**Comment by ali-farooq0** [comment]
> Thanks for helping clarify what was needed in this particular "roll-back"/"bump" mess :) @ali-farooq0, hit me up in MM whenever you are ready!

Sorry fellas, been trying to wrap up my [matterbuld pr](https://github.com/mattermost/matterbuild/pull/17). I was thinking i could fix it by running it locally, but unfortunately since i don't have access to our s3 release bucket, i won't be able to unblock this PR till my matterbuild changes are merged in. If this is super urgent i can get help from the build team to manually upload this plugin to our s3 bucket and that should resolve the issue.

Let me know @jfrerich if this can wait a day or two.

**Comment by jfrerich** [comment]
Thanks for the update, @ali-farooq0.  I'll leave the decision making up to @levb and @lieut-data.  Can this wait until Ali is finished with his PR, or do we need to expedite and get the build team involved to manually update the plugin?

**Comment by ali-farooq0** [comment]
Good news everyone! my `matterbuild` changes are merged in. I was successfully able to generate release artifacts for https://github.com/mattermost/mattermost-plugin-zoom/releases/tag/v1.3.0.

However, it looks like there is a MMCTL dependency that's failing the build now (not toolkit) related, i've poked [devops](https://community-daily.mattermost.com/core/pl/4s5m8rmh9p8pxy7qtcnorqntso) to get some insight and have them take a look. Once the issue is resolved, it will unblock this PR for testing/merging.

**Comment by ali-farooq0** [comment]
@jfrerich looks like all is well here. Tested to make sure zoom plugin was picked up. Will leave it upto you guys for testing and doing other things 👍

**Comment by jfrerich** [comment]
@ali-farooq0, Thank you sir!  @DHaussermann and @aaronrothschild, this is ready for review!

**Comment by jfrerich** [comment]
FYI @amyblais, this PR will be merged, pending @aaronrothschild's approval!

**Pull request merged**
