### PR TITLE
Prevent cancellation of CI in master

### PR DESCRIPTION
**Pull request by agnivade**
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@isacikgoz - Your first addition was itself correct. The current one is definitely wrong because the [format](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) is `refs/heads/<branch>` rather than heads/ref/<branch>.

I am not sure what was the initial problem. Did it not work even with the initial code?

**Comment by isacikgoz** [comment]
> I am not sure what was the initial problem. Did it not work even with the initial code?

Nope it didn't work, but also `heads/ref` convention is wrong I'm not sure why it was that way. But let's apply this fix, I'm curious whether `cancel-in-progress: false` ever works.

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
I did some debug logging to print out values of `github.ref` and doing a comparison with `refs/heads/master` and confirmed that it shows `true` for this PR. Given that the current state seems definitely wrong, this is one step forward. I will verify that it passes in master, and if not, continue to work on it.

**Review by M-ZubairAhmed — APPROVED** [review]
Heads up on this changes @hmhealey

**Comment by agnivade** [comment]
@isacikgoz - Seems to be working now 
cancel

The last one failed because of the OOM issue, but before that, the 2 commits weren't cancelled.

**Comment by agnivade** [comment]
What equality issue?

**Pull request merged**
