### PR TITLE
[PLT-7364] Ability to Direct Message yourself

### PR DESCRIPTION
**Pull request by cpanato**
I need some help to test and find if this is good in terms of code.
@jasonblais can help me here?

Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/186

#### Summary
 Ability to Direct Message yourself

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/PLT-7364
GitHub: https://github.com/mattermost/mattermost-server/issues/7618

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jwilander** [comment]
Looks good, but can you add/update a store unit test for this case?

**Comment by cpanato** [comment]
yes!! @jwilander it is not fully ready 😄

**Comment by jasonblais** [comment]
> I need some help to test and find if this is good in terms of code.
> @jasonblais can help me here?

Is there something specific you're looking for? We can test your work by setting up a spinmint for the webapp PR  once server and redux PRs are merged

**Comment by cpanato** [comment]
@jasonblais ah ok, then I will finish the server side, then we can do a round of testing 😄

**Comment by jwilander** [comment]
FYI the webapp PR can be tested without merging the redux PR by just pointing yarn at the correct redux branch

**Comment by cpanato** [comment]
@jwilander added a test

**Comment by jwilander** [comment]
@cpanato can you give this a rebase?

**Comment by cpanato** [comment]
@jwilander rebased

**Pull request merged**
