### PR TITLE
MM-24830: Add event constants for gossip request/response

### PR DESCRIPTION
**Pull request by agnivade**
This is an accompanying PR for the shift to entirely gossip.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-24830

### CODE REVIEW

**Comment by agnivade** [comment]
Note: this is a duplicate of https://github.com/mattermost/mattermost-server/pull/14579, which I am creating again because the branch name changed.

**Comment by agnivade** [comment]
Load tested and looks okay:

new

**Comment by agnivade** [comment]
@saturninoabril - Just checking whether you will be the one testing this and the accompanying EE PR ?

**Comment by saturninoabril** [comment]
@agnivade Yup, will do.

**Pull request merged**
