### PR TITLE
Rudder key and dataplane in Config with env vars

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Rudder key and dataplane in Config with env vars. This is reapplying the #15026
PR that was overwritten by the migration of telemetry into its own service.

#### Ticket Link
[MM-28952](https://mattermost.atlassian.net/browse/MM-28952)

### CODE REVIEW

**Review by grundleborg — APPROVED** [review]

**Comment by amyblais** [comment]
@Adovenmuehle Reminder to review this.

**Review by Adovenmuehle — APPROVED** [review]
🚢

**Comment by josephbaylon** [comment]
@jespino I tried locally to spin up the server like I usually do using `make run` (I have your PR for mattermost-server and I have latest master for mattermost-webapp, mattermost-redux, and enterprise) but unable to load localhost:8065 properly. The logs don't print anything but I noticed the following when server is spinning up (which I don't see when I try to spin up server from master -- so I'm guessing this is from the PR),

```
# github.com/mattermost/mattermost-server/v5/enterprise/cloud
enterprise/cloud/cloud.go:26:2: undefined: app.RegisterCloudInterface
enterprise/cloud/cloud.go:26:46: undefined: einterfaces.CloudInterface
enterprise/cloud/cloud.go:33:53: undefined: model.Product
enterprise/cloud/cloud.go:60:18: undefined: model.Product
enterprise/cloud/cloud.go:68:56: undefined: model.StripeSetupIntent
enterprise/cloud/cloud.go:103:14: undefined: model.StripeSetupIntent
enterprise/cloud/cloud.go:111:69: undefined: model.ConfirmPaymentMethodRequest
enterprise/cloud/cloud.go:168:25: c.App.Srv().Config().CloudSettings undefined (type *model.Config has no field or method CloudSettings)
enterprise/cloud/cloud.go:172:55: c.App.Srv().Config().CloudSettings undefined (type *model.Config has no field or method CloudSettings)
```

Should I checkout a different branch other than master locally for enterprise?

**Comment by jespino** [comment]
@josephbaylon probably we need to update to the last version of master in my branch to make it work.

**Comment by jespino** [comment]
@josephbaylon can you try it again?

**Comment by josephbaylon** [comment]
@jespino The branch update fixed the issue of loading the local server. However, I'm still not getting any events logged from my server towards https://mattermost.looker.com/dashboards/181 . I made sure `RUDDER_KEY` and `RUDDER_DATAPLANE_URL` values are correct, from this [handbook](https://docs.google.com/document/d/1CJeMFxnwUq8njKd3S3zxnfqrwUz8zNDsTmUAYqgy_uo/edit#heading=h.3g3h5oyxrijf).

Is it working for you locally - events getting logged into the looker above? If yes, I can approve the PR since the issue is only on my local. Let me know. Thanks.

**Comment by jespino** [comment]
@josephbaylon Actually it wasn't my changes were from @Adovenmuehle, I only reapplied them into our current code (we lost the changes during merges). @Adovenmuehle Do you have any ideas?

**Comment by Adovenmuehle** [comment]
Let me see if I can reproduce locally and then I'll check with Eric N to see if there's something wonky with the dashboard.

**Review by josephbaylon — APPROVED** [review]
LGTM. @jespino @Adovenmuehle I'm approving this PR. The events finally showed up on the looker dashboard. I guess it was just delayed.

**Comment by Adovenmuehle** [comment]
Ah perfect. Thanks @josephbaylon

**Comment by amyblais** [comment]
@jespino Can this be cherry picked manually?

**Comment by jespino** [comment]
@amyblais I can merge it skipping the CI errors, shouldn't be a problem, because the error looks like is not related to my changes.

**Comment by amyblais** [comment]
Ok, thanks,

**Comment by jespino** [comment]
@amyblais done!

**Pull request merged**
