### PR TITLE
MM-23281 - Continuously crashing plugin goes into infinite restart loop

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Do not remove pluginID from `Env.registeredPlugins` on `Deactivate()`. This is a bandaid fix to resolve https://mattermost.atlassian.net/browse/MM-23281, the underlying issue is how `PluginHealthCheckJob` is structured and communicates with the Plugin `Environment`. I tried to capture and provide the solution in https://mattermost.atlassian.net/browse/MM-23365 on how `PluginHealthCheckJob` should be structured to avoid bypassing public APIs to update `Environment`'s internal state.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-23281

### CODE REVIEW

**Comment by ali-farooq0** [comment]
No problem @mickmister!

I was thinking storing all that error-metadata inside `PluginHealthCheckJob`? What do you think? Since it's the only one that cares about the failures, it can hold a list of lastfailedattempts (similar to how you had it set up with registeredPlugin) and it can perform regular checks and deactivate if one of them goes past the error threshold.

**Comment by mickmister** [comment]
> I was thinking storing all that error-metadata inside PluginHealthCheckJob

Yes sounds like the right place. Seems pretty obvious, I'm not sure why I ended up storing in the `registeredPlugin`. Comparing the original PR and master, I think the code was over-complicated and has since been simplified.

**Comment by mickmister** [comment]
> How much work would it be to internalize this field into the health job and avoid touching the environment.go code (and risking regression)?

@lieut-data I was going to follow up with a PR to do this, but I think it makes sense to do the proper fix in this PR because of the potential regression.

**Comment by ali-farooq0** [comment]
> I'm worried about this line:
> https://github.com/mattermost/mattermost-server/blob/16b535314d7b942b84b128e25b03af20fbe9bd28/plugin/environment.go#L232-L235
> 
> If the plugin isn't removed from the map, we won't reinitialize all of its fields on re-activation. Does this cause any problems?
> 
> How much work would it be to internalize this field into the health job and avoid touching the environment.go code (and risking regression)?

Ahh yes I should've mentioned that this will regress https://mattermost.atlassian.net/browse/MM-20865


> @lieut-data I was going to follow up with a PR to do this, but I think it makes sense to do the proper fix in this PR because of the potential regression.

@mickmister fair point, unfortunately I won't be able to get to do the proper fix till end of this week. @mickmister if you have some bandwidth would you be willing to work on it?

**Comment by mickmister** [comment]
> @mickmister if you have some bandwidth would you be willing to work on it?

@ali-farooq0 Certainly :slightly_smiling_face: I'll get on this soon

**Comment by ali-farooq0** [comment]
Closing as @mickmister already has the other PR up
https://github.com/mattermost/mattermost-server/pull/14110.

**Comment by agnivade** [comment]
@ali-farooq0 - Feel free to delete the branch unless you think it might be needed later.

**Pull request closed without merging**
