### PR TITLE
[MM-41351] Set ThreadAutoFollow to false by default

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- `ThreadAutoFollow` is now `false` by default. Won't affect existing systems that have it set to `true`
- 
#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-41351

#### Release Note

```release-note
The default for ThreadAutoFollow has been changed to "false". This does not affect existing configurations where this value is already set to true.  
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by ashishbhate** [comment]
@Willyfrog which releases do we want to put this into? 

This will not affect existing configurations. Only new configurations starting from default.

**Comment by Willyfrog** [comment]
@amyblais this one should also go into 5.37, 6.3 and any supported version we currently have

**Comment by amyblais** [comment]
Yes, 5.37 / 6.1 / 6.2 / 6.3.

**Comment by esethna** [comment]
@cwarnermm this PR will need a PR to update the changelog page and config docs page

**Comment by cwarnermm** [comment]
@esethna - Applied the ThreadAutoFollow config setting update (setting to `false` by default) via https://github.com/mattermost/docs/pull/5390

**Comment by esethna** [comment]
@ashishbhate @Willyfrog are we good to merge this?

cc// @amyblais for patch release (along with https://github.com/mattermost/mattermost-server/pull/19411#issuecomment-1025749325) backported to v5.37 and v6.1 and later

**Comment by amyblais** [comment]
@ashishbhate This can also be cherry-picked to ``release-5.37``.

**Comment by ashishbhate** [comment]
@amyblais yep, I have a PR open for it - https://github.com/mattermost/mattermost-server/pull/19462

**Comment by ashishbhate** [comment]
@amyblais all cherry-picks done (6.3, 6.2, 6.1, 5.37)

**Pull request merged**
