### PR TITLE
upgrade db to 6.3.0

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- upgrade db to 6.3.0

#### Ticket Link
n/a

#### Release Note

```release-note
upgrade db to 6.3.0
```

### CODE REVIEW

**Comment by cpanato** [comment]
this code does not exist on the release-6.3 should we cherry pick those changes to there or just uncomment the upgrade?
https://github.com/mattermost/mattermost-server/blob/release-6.3/store/sqlstore/upgrade.go#L1808
cc @streamer45 @amyblais

**Comment by streamer45** [comment]
> this code does not exist on the release-6.3 should we cherry pick those changes to there or just uncomment the upgrade? https://github.com/mattermost/mattermost-server/blob/release-6.3/store/sqlstore/upgrade.go#L1808 cc @streamer45 @amyblais

That depends whether the features behind the changes got in or not. If they didn't then those schema changes should go in the 640 method.

**Comment by amyblais** [comment]
I'm cherry-picking some PRs to the 6.3 branch today - we can review this PR once done.

**Comment by amyblais** [comment]
This is now ready for reviews. 

I'm done with cherry-picking the other PRs.

**Review by agnivade — APPROVED** [review]
I cannot wait to get rid of this system :)

**Review by isacikgoz — APPROVED** [review]

**Pull request merged**
