### PR TITLE
Typo Fixes in Turkish Translation

### PR DESCRIPTION
**Pull request by iTechsTR**
#### Summary
Corrected some typos.

#### Checklist
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by iTechsTR** [comment]
@jasonblais If you are interested I can do the whole correct translation of the software this saturday but I would love to get something in return because it will take a long time to read all English and Turkish language files at the same time. Not to be greedy or anything but I saw you guys were used to send hoodies to contributors, according to some guy on a forum. I wonder if I can get some great swag in return so I can work more efficiently and happily? Thanks in advance.

**Comment by jasonblais** [comment]
@iTechsTR That would be great!! Wow, much appreciated.

Would you be open to joining our community server at https://community.mattermost.com and reach out to me (I'm `jason.blais` on there). Let's discuss + I can connect you to our current Turkish language maintainer as well.

**Comment by iTechsTR** [comment]
@jasonblais Done.

**Comment by jasonblais** [comment]
Thanks @iTechsTR! We can continue conversation there, I'll close this PR :)

**Pull request closed without merging**
