### PR TITLE
Prepackage Playbooks v1.16.1

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Fixed a bug preventing prepackaged Playbooks from installing

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-37928

#### Release Note

```release-note
Bug fix: Playbooks v1.16.0 could not be installed as a pre-packaged plugin
```

### CODE REVIEW

**Comment by jason-code78** [comment]
Release

**Comment by cpoile** [comment]
@lieut-data With this PR, cloud test server installs the v1.16.1 plugin, everything is good. A "control" PR (https://github.com/mattermost/mattermost-server/pull/18156) shows the v1.16.0 plugin fails to load as described in the channel.

**Review by agarciamontoro — APPROVED** [review]
:tada:

**Review by lieut-data — APPROVED** [review]

**Pull request merged**
