### PR TITLE
MM-40677: Pre-package Playbooks v1.23.0

### PR DESCRIPTION
**Pull request by lieut-data**
#### Release Note
```release-note
Pre-package Playbooks v1.23.0.
```
#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-40677

### CODE REVIEW

**Comment by lieut-data** [comment]
Let's hold on actually merging this until we confirm if we need to bump the minimum server version in the plugin.

**Comment by lieut-data** [comment]
Confirmed the minimum server version is already bumped. We should be good to go once we have confidence in the build in question.

**Review by crspeller — APPROVED** [review]

**Comment by Phrynobatrachus** [comment]
Screenshot from 2022-01-07 11-18-13

:+1:

**Review by Phrynobatrachus — APPROVED** [review]

**Pull request merged**
