### PR TITLE
Test license server

### PR DESCRIPTION
**Pull request by ethervoid**
#### Summary

Test license server

For dev check https://github.com/mattermost/mattermost-server/pull/16787

#### Release Note

```release-note
```

### CODE REVIEW

**Comment by angeloskyratzakos** [comment]
Hey all, I will remove the tag `Setup Cloud Test Server` for maintenance reasons. Feel free to re-add it when you need it. Thank you

**Comment by isacikgoz** [comment]
@AGMETEOR @marianunez do you know what is the state for this PR? Can we close it?

**Comment by marianunez** [comment]
> @AGMETEOR @marianunez do you know what is the state for this PR? Can we close it?

@isacikgoz we have this PR with the license key changed to the test license key (instead of prod) so we can test licenses generated in the test portal with the spinwick here.

**Comment by isacikgoz** [comment]
Thanks for the info @marianunez! We have a repo here https://github.com/mattermosttest/mattermost-server that has been used for a similar purpose for development of mattermod. I am not sure if it would work for you but I just wanted to bring this up. AFAIK there is no spinwick configured for that repo but maybe @cpanato can guide if you think it would make sense to use that repo for this purpose.

**Comment by marianunez** [comment]
Closing this PR and will open another one if needed later.

**Pull request closed without merging**
