### PR TITLE
MM-12369 Add Create Outgoing Webhook Command

### LINKED ISSUE #9768: [Help Wanted] [MM-12369] Create CLI command "webhook create-outgoing"
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12369)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `webhook create-outgoing` command in the CLI.

Allow creating outgoing webhooks.

Example: `webhook create-outgoing myteam --title MyOutgoinWebhook --description "My Command Description" --channel mychannel --trigger-words "word1\nword2" --triger-in first --icon http://localhost:8000/my-slash-handler-bot-icon.png --url http://localhost:8000/my-webhook-handler --content-type "application/json"`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

### PR DESCRIPTION
**Pull request by KerryAlsace**
#### Summary
Implement `webhook create-outgoing` command in the CLI

#### Ticket Link
resolves #9768 (Jira link: https://mattermost.atlassian.net/browse/MM-12369)

#### Checklist
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by KerryAlsace** [comment]
I filled out the CLA a couple hours ago and it looks like I'm listed on the approved contributors list

**Comment by KerryAlsace** [comment]
Awesome! Thanks

**Comment by jwilander** [comment]
@wiersgallak confirming this is OK to merge?

**Comment by wiersgallak** [comment]
Thank you - looks good @KerryAlsace! (and @jwilander)

**Comment by lindalumitchell** [comment]
@KerryAlsace @jwilander @grundleborg I'm just testing this ahead of the v5.6 release. Wondering if you can help with a couple questions (us QA folk are relatively new to testing CLI commands):
1. Is it expected that there is no feedback printed after success or fail for this command?
2. The example shows using `\n` to insert a newline in trigger words field and enter multiple terms. But I'm not able to get this to insert a newline. I've Googled and tried many variations of quotes, spaces, escape characters, but none of them result in a newline in that field (most of them unsurprisingly). Any ideas?
a. As listed in the example `--trigger-words "build\ntest"` > `build\ntest` appears in the Trigger Words field
b. Single quotes, no spaces `--trigger-words "build'\n'test"` > `buildntest` 
c. Double quotes, no spaces `"build"\n"test"` > `build'\n'test`
d. Double (escaped) backslash `"build\\test"` > `build\test`
e. Double quotes, spaces `"build "\n" test"` > `build n test`
f. Single quotes, spaces `"build '\n' test"` > `build '\n' test`
g. Other attempts with spaces before and/or after the `\n`, with no quotes; and still others that probably are overkill to list out one by one here :)

**Comment by grundleborg** [comment]
@jespino please can you help with Linda's questions above, as you wrote the original ticket spec for this?

**Comment by jespino** [comment]
Sure.

1. I would expect to have an error message and an error code (command return code, not visible by the user normally) on error and no message on success (and of course no error code).

2. I would refactor it to use multiple "--triger-word" params, something like `mattermost webhook create-outgoing --triger-word build --triger-word test ...`. Anyway, if not, we have to properly interpretate the `\n` string.

**Comment by lindalumitchell** [comment]
Thanks @jespino! So at this point, would we want to revert this one, then make those changes, and then get it back in for next time? Or is that a question for PM/triage?

**Comment by jespino** [comment]
Added a PR to solve some of the problems here: #9899

**Comment by lindalumitchell** [comment]
Note: I re-tested and all looks good. Closed the JIRA ticket. 👍

**Pull request merged**
