### PR TITLE
MM-15801 Migrate "Session.UpdateRoles" to Sync by default

### LINKED ISSUE #10930: Migrate "Session.UpdateRoles" to Sync by default
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15801)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `UpdateRoles` in the `Session` store.

The expected way to implement it is, go to the `Session` store implementation in the `store/sqlstore/` directory, modify the method `UpdateRoles` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

### PR DESCRIPTION
**Pull request by bolariin**
#### Summary

This pull request migrates the `UpdateRoles` in the `Session` store to use Sync by default. I followed the instructions laid out in the issue description and updated all necessary files.

#### Ticket Link

Resolves #10930

### CODE REVIEW

**Comment by mgdelacroix** [comment]
@bolariin can you please update the branch to solve the confict so it can be merged?

**Comment by hanzei** [comment]
@bolariin Looks like there is still a merge conflict. Let me know, if you need help resolving it.

**Comment by bolariin** [comment]
I think I was able to resolve the issue with the file conflict. I'm not exactly sure what the current cause of the current issue is because I tried govet locally and had no issues.

**Comment by jespino** [comment]
@bolariin you merged from `master`, maybe your local copy of the `master` branch wasn't up to date? I normally use `git fetch origin` and `git merge origin/master` to be sure. (In your machine the remote can be other instead of `origin`)

**Comment by bolariin** [comment]
I actually pulled the remote branch and tested it locally. I did what you advised and merged my local branch with the updated master branch and I didn't get the govet error.

**Comment by jespino** [comment]
@bolariin Your local govet is not able to check for enterprise changes, and because some changes made to master affects the entperprise repo, you dont have the posibility of changing it. The last merge to this branch was 5 days ago, do you mind to merge master again here?

**Comment by hanzei** [comment]
Thank you for the contribution @bolariin :rocket:

**Pull request merged**
