### PR TITLE
remove redis from the code base

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
we don't use this code and Redis for now, and it looks like there is no plan in near/mid future.
As we talked sometime ago, I'm opening this PR to remove the Redis from the codebase

### CODE REVIEW

**Comment by jwilander** [comment]
I have to say I don't remember a conversation about ripping this code out

**Comment by grundleborg** [comment]
@jespino what did we decide to do with the existing redis code in relation to the cache layer overhaul?

**Comment by jespino** [comment]
@grundleborg The code wasn't "used" and wasn't up to date, was removed with the idea of abstract the concept of cache from the cache implementation (having something like a "Cache interface" to implement later the basic operations on this cache interface for redis, and maybe others). I have that pending for a long time already (I tried to assign that to community members in the past with much success).

We can easily reintroduce it and have a real, valid and usable implementation of redis cache in matter of a couple of days of work (IMO).

**Comment by jespino** [comment]
About the PR itself, I'm ok with removing this, but I think we want to reitroduce a proper implementation of the redis cache eventually, so I don't know if it is going to be sooner o later.

**Comment by grundleborg** [comment]
@jespino so would you say it makes sense to merge this PR then to clean up the remaining traces or redis for now from the server code base?

**Comment by grundleborg** [comment]
@jespino can you see any down side to merging this PR?

**Comment by jespino** [comment]
@grundleborg The need to reintroduce this changes once we add again the redis support.

**Comment by cpanato** [comment]
@grundleborg ptal

**Pull request merged**
