### PR TITLE
[MM-13744] Enable NPS plugin if prepackaged

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
Enables NPS plugin if prepackaged.

#### Ticket Link
[MM-13744](https://mattermost.atlassian.net/browse/MM-13744) and [MM-13745](https://mattermost.atlassian.net/browse/MM-13745)

### CODE REVIEW

**Comment by hmhealey** [comment]
@cpanato I'm not sure how it would be against GDPR to enable this automatically. The plugin asks for feedback in that case, but it doesn't do anything if users don't respond to it

**Comment by cpanato** [comment]
@hmhealey I dont know i was asking to check if we need to review to see if it is not against the gdpr. maybe @jasonblais know more 😄

**Comment by jasonblais** [comment]
We're good, not against the GDPR: https://docs.google.com/document/d/1J9XweWe3roDvYI5j5kjXDH6fHgmhnCYFbz-xRQyfckw/edit#heading=h.d5n1hidb1xw2

**Comment by hmhealey** [comment]
I'm waiting to merge this until we're ready to ship the NPS plugin

**Comment by hmhealey** [comment]
I just double checked, and even if we enable it like this, the server just ignores that line if the plugin binaries aren't included yet, so we're good to merge this whenever

**Pull request merged**
