### PR TITLE
[SEC-2191] Add security headers with sensible default values.

### PR DESCRIPTION
**Pull request by oh6hay**
#### Summary

Adds missing security headers with sensible default values.

#### Ticket Link

https://mattermost.atlassian.net/browse/SEC-2191

#### Release Note

````release-note
The following new HTTP headers and values are written on all responses:
```
Permissions-Policy: 
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
```
These default values should make sense in most installations and can be overridden by a reverse proxy or ingress configuration. Note that the empty `Permissions-Policy` does not have any other effect than be present, to suggest changing it to a more restrictive value based on actual needs.
````

### CODE REVIEW

**Comment by oh6hay** [comment]
An empty `Permissions-Policy` by default is a sane default as a non-empty one may break plugins.

**Review by agnivade — COMMENTED** [review]
Possible to add a unit test?

**Comment by oh6hay** [comment]
> Possible to add a unit test?

sure, like this?

**Comment by agnivade** [comment]
Looks good Ossi. My question is - was this intended only for API responses? Because `web.Handler` only covers API responses not static assets. If we also want to cover assets, we need to modify this function as well: https://github.com/mattermost/mattermost-server/blob/087aa38afb3903401d49f838415827416810223b/web/static.go#L79

**Comment by oh6hay** [comment]
Thanks Agniva, that's a good point, I added a test for the static handler. Plugins also have their own handler, but as they may support arbitrary functionality, I didn't implement the default headers there.

**Review by agnivade — APPROVED** [review]
Nice, thanks!

**Review by noxer — APPROVED** [review]

**Pull request merged**
