### PR TITLE
MM-42268: Added more fields to Channel and Team

### PR DESCRIPTION
**Pull request by agnivade**
Also added sessions as part of the user object

https://mattermost.atlassian.net/browse/MM-42268

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@larkox - Can you pull this down locally and let me know that everything looks okay on the client side?

**Comment by agnivade** [comment]
Can you tell me the query you are using?

**Comment by larkox** [comment]
A simple query like this reproduce the issue:
```
{
  channelMembers(userId: "me") {
    channel {
      id
    }
  }
}
```

**Review by larkox — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Pull request merged**
