### PR TITLE
MM-33789: Revert fallback to master for GetAllProfilesInChannel

### PR DESCRIPTION
**Pull request by agnivade**
This fixes a regression introduced in https://github.com/mattermost/mattermost-server/pull/16911.

It was causing problems with too many invalidations and overloading the writer instance for big installations.
Reverting this does not affect correctness at all because it was done out of abundance of caution and the
idea at that point was it was to be done for all caches.

https://mattermost.atlassian.net/browse/MM-33789

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@srkgupta - Would you be able to QA this. The steps are essentially the same as https://github.com/mattermost/mattermost-server/pull/16911. But that PR is causing some performance regressions which this PR fixes. We just want to confirm that the issue is still fixed.

**Review by streamer45 — APPROVED** [review]
Thanks! Looks good :+1: 

Re-run a load-test to confirm and everything is back to normal:

image

**Review by srkgupta — CHANGES_REQUESTED** [review]
Hi @agnivade 

This code revert is now causing the issue in the ticket MM-30882 to re-appear. Can you please take a look at it and fix it.

**Review by srkgupta — APPROVED** [review]
There were some issues with the code deployed on the previous HA instance here. I redeployed the same on a cloud test HA instance and retested and the issue worked fine. Approving the PR. Thanks @agnivade

**Pull request merged**
