### PR TITLE
[WebApp][MM-52138]: Wrap all the components using compass-components with compass-components theme provider

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Wrap all the components using compass-components with compass-components theme provider.
Note: We are doing this to make way for MUI theme provider and to avoid wrappping individual components with it.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-52138

#### Screenshots
No visual changes

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
This one LGTM, thanks @AshishDhama

**Comment by hmhealey** [comment]
If I understand this correctly, we're doing this so to keep the old compass-components looking the same while we wrap the rest of the app in new theme provider that'll style the new modals and such. Is that right?

**Comment by AshishDhama** [comment]
> If I understand this correctly, we're doing this so to keep the old compass-components looking the same while we wrap the rest of the app in new theme provider that'll style the new modals and such. Is that right?

Yeah, Your understanding is correct.

**Comment by AshishDhama** [comment]
@M-ZubairAhmed @hmhealey gentle review reminder on this one.

**Review by M-ZubairAhmed — COMMENTED** [review]
So this PR has two changes 
- Removes few of the `compass-components-icons` to mattermost icons
- Adds CompassThemeProvider in bunch of components root

My question is how are we going to handle the MUI provider, will it be added in this theme provider itself? or will it be another wrapper

**Comment by AshishDhama** [comment]
> So this PR has two changes
> 
> * Removes few of the `compass-components-icons` to mattermost icons
> * Adds CompassThemeProvider in bunch of components root
> 
> My question is how are we going to handle the MUI provider, will it be added in this theme provider itself? or will it be another wrapper

We have another https://github.com/mattermost/mattermost-server/pull/23238, we are doing it in parts to keep reviewing manageable.

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Thanks, @AshishDhama 
One test is failing; that will be fixed by tomorrow
https://mattermost.atlassian.net/browse/MM-52647

**Comment by AshishDhama** [comment]
> Thanks, @AshishDhama One test is failing; that will be fixed by tomorrow https://mattermost.atlassian.net/browse/MM-52647

Thanks @furqanmlk, working on failing e2e.

**Pull request merged**
