### PR TITLE
[MM-10335] Update email notification subject line and contents for Group Messages

### PR DESCRIPTION
**Pull request by uturkdogan**
#### Summary
Update email notification subject line and contents for Group Messages

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10335
https://github.com/mattermost/mattermost-server/issues/8670

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by uturkdogan** [comment]
Sure thing, should I also add `@` on generic email messages? So they would read:
`You have a new notification from @user`

**Comment by ThiefMaster** [comment]
> `app/notification.go 100644 → 100755`

Intentional?

**Comment by esethna** [comment]
@uturkdogan awesome, thanks for the tweaks. Noticing one other bug with long GM channel names:

Notice how the group message channel name is cut off in the email subject line and the email contents.
image
image

We can line wrap the channel name in the email contents when necessary.

**Comment by uturkdogan** [comment]
@esethna Hey, good catch. Sorry didn’t test it with long name... 
I’ll fix it later today, 
also do you want me to add @ sign infront of username on generic email messages?

**Comment by esethna** [comment]
@uturkdogan thanks! And can you clarify the case you are referring to?

**Comment by uturkdogan** [comment]
@esethna When email content type "EMAIL_NOTIFICATION_CONTENTS_GENERIC", which is I believe the privacy mode, email notifications read "You have a new notification from user1" for all cases. 
Should I change it to "You have a new notification from @user1", or should I just leave it as is?

**Comment by uturkdogan** [comment]
@esethna sounds good, I will do these changes.

**Comment by uturkdogan** [comment]
@esethna Eric, I think I did all the things you've requested,
in all cases I've added @ sembol before the username.
I've removed the channel name from group message notifications on Generic mode.
I've capitalized Group Message and Direct Message.
I've also fixed the issue with long group message names. The issue was I was using channel's displayname which has a character limit. Now instead I am using constructed name..

Let me know if you need anything else :)

**Comment by esethna** [comment]
Awesome, looks great! Moving to dev review

**Pull request merged**
