### PR TITLE
[MM-50827] Detect content-type if missing in response during link metadata generation

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

This issue was a bit tricky because I wasn't able to reproduce it consistently. Also it looks like the web client is not affected at all. Even if the image metadata is missing, it will still render the image correctly while the mobile side seems to require the extra info.

The test case used was the markdown snippet provided by the reporter in https://github.com/mattermost/mattermost-mobile/issues/7158. At times it worked and the metadata was generated correctly:

```
-[ RECORD 1 ]----------------------------------------------------------------
hash      | 4204853875
url       | http://placekitten.com/200/300
timestamp | 1680814800000
type      | image
data      | {"width": 200, "format": "jpeg", "height": 300, "frame_count": 0}
```

while at times we'd end up with a mostly empty entry:

```
-[ RECORD 1 ]-----------------------------
hash      | 4204853875
url       | http://placekitten.com/200/300
timestamp | 1680814800000
type      | none
data      | null
```

After analyzing the server-side responses I figured the `Content-Type` header wasn't always returned by the server (seems to be behind Cloudflare) while the data was correctly sent. I suppose this is likely a bug on their side but still it can affect MM users since once cached in the database the "empty" metadata is stuck there and will cause such images to permanently fail to display until deleted.

```
< HTTP/1.1 200 OK
< Date: Thu, 06 Apr 2023 21:32:57 GMT
< Content-Length: 6599
< Connection: keep-alive
< Cache-Control: public, max-age=86400
< Expires: Thu, 31 Dec 2020 20:00:00 GMT
< Vary: User-Agent
< Access-Control-Allow-Origin: *
< Last-Modified: Thu, 06 Apr 2023 05:47:39 GMT
< CF-Cache-Status: HIT
< Age: 33075
< Accept-Ranges: bytes
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=YXQR4VnzQaIaueigCKB464DVwK5t2Oa7E9JffG1Z975cPrG75J0MQDC6a77ksNCiY7sZkNebpJXoHOnDH0CfJWP2L%2FZiqqFGOnnBj0U9g3xWtFcmBCevlnHZlnqisPyQ5Loq6aGsrPqslGkppvQ%3D"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 7b3d25798fb22f3a-LAX
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

To fix this I added a little probing function (copied over from the image proxy) that attempts to figure out the content of the response from the body itself if none is provided.

@enahum This is a separate issue from what we discussed in the Jira ticket which still stands. Also I cannot be 100% confident this is what the original reporter was experiencing but I hope it's a step in the right direction.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-50827

#### Release Note

```release-note
Fixed an issue with post metadata not generating correctly for images due to missing content-type in response. This would result in certain embedded images not to display on mobile clients.
```

### CODE REVIEW

**Review by agnivade — DISMISSED** [review]
Hmm .. weird indeed. Let's see how much this improves things.

**Review by cpoile — DISMISSED** [review]
Interesting!

**Comment by streamer45** [comment]
Re-asking for a quick pass since I simplified the logic a bit to avoid the extra buffer initialization for the happy path (non-empty content-type).

**Review by cpoile — APPROVED** [review]

**Review by agnivade — APPROVED** [review]

**Pull request merged**
