### PR TITLE
Upgrade db to 5.20

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Upgrade DB to 5.20

@amyblais there are some new columns, need to check with @mkraft

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@cpanato is there anything QA should test on these changes? Everything looks orderly to me. :)

**Comment by cpanato** [comment]
@lindalumitchell afaik no, but maybe @mkraft can give better details if needed deep testing

**Comment by mkraft** [comment]
@lindalumitchell The groups part of these changes were tested as part of https://github.com/mattermost/mattermost-server/pull/13361. 

The [bots part of the code change change](https://github.com/mattermost/mattermost-server/pull/13542) was likely deemed not requiring testing, but @jwilander should confirm because I don't see a history of any QA-related labels on the PR.

**Comment by jwilander** [comment]
My PR was just fixing a community member's PR that broke the DB migration. The community member's PR was tested other than that case I fixed.

Traditionally these upgrade PRs do not require testing.

**Comment by mkraft** [comment]
> My PR was just fixing a community member's PR that broke the DB migration. The community member's PR was tested other than that case I fixed.
> 
> Traditionally these upgrade PRs do not require testing.

Yes these upgrade PR's don't typically have a QA Review label but I think all feature and bug PRs now require a QA Review label as per the new policy.

**Pull request merged**
