### PR TITLE
MM-27989 Remove experimental setting for data prefetch

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Remove experimental setting added for data prefetch. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27989

#### Related PR
https://github.com/mattermost/mattermost-webapp/pull/7094

#### Release Notes
```release-note
Enabled ExperimentalDataPrefetch for all servers and removed the corresponding setting
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by ashishbhate — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @sudheerDev 
Tested, looks good to merge.
- Verified ExperimentalDataPrefetch is not present as `client?format` value.

**Comment by sudheerDev** [comment]
@amyblais Hey, Here we are removing the setting and config for the experimental feature `DataPrefetch`. With this change sys admins will not have an option in the console to turn this off. We had this in the first place as a fail safe. As there are no reports on this since we enabled it we are removing this. I made a PR to update docs https://github.com/mattermost/docs/pull/4132. Let me know if i am missing anything

**Comment by hmhealey** [comment]
@amyblais I updated the docs PR with a deprecation notice and added a release note here, so can the Awaiting PR label be removed?

**Comment by amyblais** [comment]
@hmhealey I don't have context as to why the Awaiting PR label was originally added, but I think this is ok to merge.

**Comment by hmhealey** [comment]
I think it was added because we wanted the docs PR submitted first

**Pull request merged**
