### PR TITLE
Set Advanced Text Editor feature flag default value to True

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Set Advanced Text Editor feature flag default value to True

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-44704

#### Release Note
```release-note
Set Advanced Text Editor feature flag default value to True
```

### CODE REVIEW

**Review by vish9812 — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Comment by AshishDhama** [comment]
@Willyfrog Suggestion?

**Comment by Willyfrog** [comment]
yes, it is part of the follow up ticket

**Review by Willyfrog — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @AshishDhama - looks good to merge.
I'll update the follow up ticket with the list of test cases that will need to be fixed as a result of this change.
Please fix the conflicts and merge when available. 🙂

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
