### PR TITLE
MM-10603: Ignore Redirects and Other Changes when Displaying Link Previews

### PR DESCRIPTION
**Pull request by pietroglyph**
#### Summary
This PR is a small behavior change with link previews. When a user posts a message with a URL, we get the contents of that URL and check for `<meta>` annotations that conform to the [Open Graph protocol](http://ogp.me/). If these annotations are present, we show a link preview in Mattermost (if that setting is enabled.) We also follow redirects when performing this action, which means that sometimes we follow a redirect, and our final landing page provides a `og:url` different from the URL the user put in their message. This behavior is intended, but confusing. **This PR ignores the `og:url` property, and always uses the link the user originally provided instead.** We still follow redirects for displaying other link preview information.

#### Ticket Link
Closes: Github #9008, JIRA [MM-10603](https://mattermost.atlassian.net/browse/MM-10603)

#### Checklist
Nothing applicable here.

### CODE REVIEW

**Comment by jespino** [comment]
Hi @pietroglyph, the change has a side effect, before this, some private links, simply wasn't generating the preview, because the login/404/whatever page that returns the server simply hasn't OpenGraph information. Now the preview is always generated, and for that cases, it only shows the requestURL link.

The solution is working properly for the example case gitlab private projects, but not for other cases like github private projects.

@jasonblais can you confirm that the expected behavior is: when it can generate the preview, show the preview with the link to the originally posted url, like in https://gitlab.com/jespino/test-project. And when it can't generate the preview, simply don't show any preview info at all, like in https://github.com/mattermost/enterprise

**Comment by jasonblais** [comment]
> @jasonblais can you confirm that the expected behavior is: when it can generate the preview, show the preview with the link to the originally posted url, like in https://gitlab.com/jespino/test-project. And when it can't generate the preview, simply don't show any preview info at all, like in https://github.com/mattermost/enterprise

That sounds correct to me.

**Comment by pietroglyph** [comment]
Sorry for overlooking that... I've changed it so the preview isn't shown when there isn't any Open Graph data/we don't change the URL if none has been provided (the former is a side effect of the latter.) Let me know if that looks good.

**Comment by jespino** [comment]
@pietroglyph Thanks!! Don't worry about the first approach, was a good try. For this are the PR reviews. One more time, thanks again. For me is working as expected (@jasonblais give it a try please, you can use this url "https://gitlab.com/jespino/test-project" as an example, the result is weird, but I think is correct. Weird because the link text is "Sign In" and the link points to the real URL, which is not the "Sign in" page).

**Comment by hmhealey** [comment]
Looks good to me. Thanks @pietroglyph!

**Pull request merged**
