### PR TITLE
[MM-28217] Server API to serve up cloud customer information

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Server portion of MM-28217. This enables Company Information (including name, # of employees and address) to show up in the System Console

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28217

#### Related Pull Requests
CWS: 
Enterprise: https://github.com/mattermost/enterprise/pull/778
Webapp: https://github.com/mattermost/mattermost-webapp/pull/6580
Redux: https://github.com/mattermost/mattermost-redux/pull/1249

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Looks good! Thanks @devinbinnie!

**Review by ethervoid — APPROVED** [review]
LGTM!

**Review by stevemudie — APPROVED** [review]
Will test once merged

**Comment by marianunez** [comment]
@devinbinnie We need to cherry-pick this to the new branch `cloud-ga`

**Pull request merged**
