### PR TITLE
MM-33903 rename slash commands & permission

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR implements a change to the shared channels slash command specification.  https://docs.google.com/document/d/12Jwu9aODzVArNP3z6_ivTePIvz9EsjDpwSSVmzl5pU8/edit#bookmark=id.j0ctjvp2k0h5

- rename slash commands
        - "remote" -> "secure-connection"
        - "share" -> "share-channel"
- change status icons to text (translated)
- remove channel invite "Description" field
- rename permission "manage_remote_clusters" -> "manage_secure_connections"

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33903

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM ☝️

**Review by furqanmlk — APPROVED** [review]
Thanks @wiggin77   for updating.

**Comment by wiggin77** [comment]
@furqanmlk FYI - I found and fixed an issue with renaming the manage_remote_clusters permission that would only affect instances that ran the 5.35 release before running this PR.

**Review by furqanmlk — APPROVED** [review]
All Slash commands and permission tested ✅ 
Test case has been updated.

**Pull request merged**
