### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by akrfjmt**
#### Summary
fix typo in build/README.md

#### Ticket Link
none

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you @akrfjmt! Would you be open to completing the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?

Please let us know if you have any questions.

**Comment by hanzei** [comment]
Hey @akrfjmt,

Do you need help with completing the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)? Let me know, if you have questions.

Please note that we will close this PR after another 30 days of inactivity. If you don't object, contributors might complete this PR for you.

**Comment by jasonblais** [comment]
@hanzei Wondering if this can be merged without a rebase? It's just a typo, and the one change to README (https://github.com/mattermost/mattermost-server/commit/6a3fdbd489956eb7faeef18bd60edb21b9e3fae4#diff-04c6e90faac2675aa89e2176d2eec7d8) doesn't affect the change proposed here

**Comment by hanzei** [comment]
@jasonblais Surely. But first the cla check has to pass. Do you know why it fails?

**Comment by jasonblais** [comment]
Looks like it's `/check-cla` not `/cla-check` :)

**Comment by hanzei** [comment]
Thanks for the fix @akrfjmt :+1:

**Pull request merged**
