### PR TITLE
Making default pdf extracting more robust

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Making default pdf extracting more robust

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35990

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by jespino** [comment]
@amyblais this probably is a good candidate for cherry-picking

**Comment by amyblais** [comment]
@ashishbhate @mgdelacroix This is a candidate to backport to v5.35.

**Review by mgdelacroix — APPROVED** [review]
LGTM :+1:

**Review by ashishbhate — APPROVED** [review]

**Comment by ashishbhate** [comment]
The CI failures are fixed in https://github.com/mattermost/mattermost-server/pull/17678

This PR will need a master merge after that one goes in.

**Comment by amyblais** [comment]
@ogi-m This is a candidate for v5.35 dot release.

**Comment by amyblais** [comment]
@ogi-m Kind reminder on this.

@jespino Will this PR also fix https://forum.mattermost.org/t/document-content-extractor-thinks-odts-are-zips-and-wont-extract/11743 & https://forum.mattermost.org/t/files-indexing-error-while-upgrade-to-5-35-0/11676?

**Review by ogi-m — APPROVED** [review]
Tested by Jesus. Approving 👍🏻

**Comment by amyblais** [comment]
@jespino Can you help cherry-pick to ``release-5.35`` and ``cloud`` branches?

**Comment by jespino** [comment]
@amyblais cherry-pick done

**Pull request merged**
