### PR TITLE
Revert MM-27312

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR reverts changes introduced in https://github.com/mattermost/mattermost-server/pull/16235 due to the significant performance impact of the related migration on MySQL installations.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by streamer45** [comment]
@lindy65 

This is mostly safe but just to be extra sure I'd request a smoke-test around file attachments, making sure that up to 5 files can be added per post.

**Comment by lindy65** [comment]
Hi @streamer45 

I'm still able to upload 10 files?

image

When I hit Enter to make the post though, I get "Retry/Cancel" on the post and errors in the js.console...

image

**Comment by streamer45** [comment]
> Hi @streamer45
> 
> I'm still able to upload 10 files?
> 
> image
> 
> When I hit Enter to make the post though, I get "Retry/Cancel" on the post and errors in the js.console...
> 
> image

Thank you @lindy65 . That is somewhat expected since the webapp changes have not been reverted (yet). cc @hmhealey

**Comment by lindy65** [comment]
Aaaaah, ok, thanks @streamer45 :)

Harrison, please let me know once webapp PR is merged so I can retest?  Thank you!

**Comment by lindy65** [comment]
Hey @streamer45 - I've tested on the [webapp PR](https://github.com/mattermost/mattermost-webapp/pull/7510) and can upload only 5 attachments per post so it looks good to me. I'll approve this PR now too.

**Review by lindy65 — APPROVED** [review]
Thanks, looks good to me 👍

**Pull request merged**
