### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-server_release-5-28/) for mattermost-languages-shipped/mattermost-server_release-5.28.

### CODE REVIEW

**Comment by amyblais** [comment]
@metanerd This one failed to build.

**Comment by metanerd** [comment]
I have to use force, this is not a rate limit issue like I thought it was. There is something wrong with the mmctl fetching process.

**Pull request merged**
