### PR TITLE
translations PR 20190401

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by enahum** [comment]
@cpanato this thing failing again, something about not able to find the config directory

**Comment by cpanato** [comment]
@enahum will check when i come back

**Comment by cpanato** [comment]
@enahum this is the errors:
```
=== RUN   TestExecCommand
        	            	--- FAIL: TestExecCommand (0.13s)
        	            	panic: unable to parse translation #84 because template: 명령 '{{.Trigger}'이(가) 응답을 게시하지 못하였습니다. 시스템 관리자에게 문의하십시오.:1: unexpected "}" in operand
        	            	map[id:api.command.execute_command.create_post_failed.app_error translation:명령 '{{.Trigger}'이(가) 응답을 게시하지 못하였습니다. 시스템 관리자에게 문의하십시오.] [recovered]
        	            		panic: unable to parse translation #84 because template: 명령 '{{.Trigger}'이(가) 응답을 게시하지 못하였습니다. 시스템 관리자에게 문의하십시오.:1: unexpected "}" in operand
        	            	map[id:api.command.execute_command.create_post_failed.app_error translation:명령 '{{.Trigger}'이(가) 응답을 게시하지 못하였습니다. 시스템 관리자에게 문의하십시오.]
        	            	
        	            	goroutine 37 [running]:
        	            	testing.tRunner.func1(0xc0011b6100)
        	            		/usr/local/go/src/testing/testing.go:830 +0x388
        	            	panic(0x1602900, 0xc0014b74c0)
        	            		/usr/local/go/src/runtime/panic.go:522 +0x1b5
        	            	github.com/mattermost/mattermost-server/cmd/mattermost/commands.InitDBCommandContextCobra(0x2a6f760, 0xc0011c4700, 0xc000089d60, 0xc0011c4700)
        	            		/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/init.go:21 +0x19b
        	            	github.com/mattermost/mattermost-server/cmd/mattermost/commands.addChannelUsersCmdF(0x2a6f760, 0xc0011cc000, 0x2, 0x5, 0x0, 0x0)
        	            		/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/channel.go:274 +0x51
        	            	github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x2a6f760, 0xc0000a24e0, 0x5, 0x6, 0x2a6f760, 0xc0000a24e0)
        	            		/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762 +0x465
        	            	github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2a76bc0, 0x7ffc225a0377, 0xb, 0x8)
        	            		/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852 +0x2c0
        	            	github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        	            		/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800
        	            	github.com/mattermost/mattermost-server/cmd/mattermost/commands.TestExecCommand(0xc0011b6100)
        	            		/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/exec_command_test.go:18 +0x11b
        	            	testing.tRunner(0xc0011b6100, 0x18ff6d0)
        	            		/usr/local/go/src/testing/testing.go:865 +0xc0
        	            	created by testing.(*T).Run
        	            		/usr/local/go/src/testing/testing.go:916 +0x357
```

**Comment by enahum** [comment]
@cpanato what about now?

**Comment by cpanato** [comment]
@enahum now was a flaky one. re triggered

**Pull request merged**
