### PR TITLE
Bump golang image

### PR DESCRIPTION
**Pull request by metanerd**
#### Release Note

```release-note
Bumped the Go version to 1.15.5.
```

### CODE REVIEW

**Comment by agnivade** [comment]
Is this ready for review? ;) Or are we waiting for something else?

**Comment by metanerd** [comment]
I don't want to change too many things at once. I think I want to move this until 1 week from now honestly, because it also requires jenkins changes again.

**Comment by agnivade** [comment]
No rush. Just checking. :+1:

**Comment by agnivade** [comment]
Just checking in on this again :)

**Comment by metanerd** [comment]
Soon :tm:

**Review by agnivade — APPROVED** [review]
Looks great

**Pull request merged**
