### PR TITLE
MM-30865 Invalid Participants handling on post delete in thread

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

don't remove the user from participants on post delete
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30865
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by reflog** [comment]
@amyblais this should be cherrypicked I think

**Comment by esethna** [comment]
@amyblais another one for v5.29 dot release ^

**Review by ashishbhate — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Comment by esethna** [comment]
@reflog what is needed from QA here? cc// @ogi-m as this is for v5.29 dot release

**Comment by reflog** [comment]
@ogi-m @esethna smoke testing around posts with replies

**Pull request merged**
