### PR TITLE
Implement empty translation check.

### PR DESCRIPTION
**Pull request by metanerd**
#### Summary
This is a workaround for this weblate issue: https://github.com/WeblateOrg/weblate/issues/4076

So this checks for occurrences like this:

   ```
 {
        "id": "api.post.delete_post.can_not_delete_post_in_deleted.error",
        "translation": ""
    },

```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Lgtm

**Comment by enahum** [comment]
Any QA needed?

**Comment by metanerd** [comment]
Wow, two approvals after 5 mins of requesting them on a Saturday. No QA needed for this.

**Comment by enahum** [comment]
Is all about teamwork

**Comment by jespino** [comment]
> Is all about teamwork

About teamwork and about knowing who is not good at disconnecting 🤣

**Pull request merged**
