### PR TITLE
MM-11348: Add telemetry for advanced permissions.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
Add telemetry for the advanced permissions feature.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-11348

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Includes text changes and localization file updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@wiersgallak Since you wrote the spec, would you like to give this one a try to verify the telemetry is correct? Steps for server-side events:

1) Log in to Segment, go to Data Sources > Mattermost Development Builds > Schema
2) Review the schema tables and confirm they follow according to the spec

**Comment by wiersgallak** [comment]
@grundleborg, can you please help me help get permissions turned on on the test server?

**Comment by wiersgallak** [comment]
@grundleborg I can see the system scheme telemetry, but not the team schemes.  When I try to add a team scheme to a specific team on this spinmint, I am getting a white screen.  A refresh takes me back to the team scheme, where I can attempt to add the team again, but again end up with white screen when I attempt again.  Any ideas to help me troubleshoot so I can finish testing?

**Comment by grundleborg** [comment]
@wiersgallak that's really weird, and sounds unrelated to this PR as it doesn't touch any code which could affect that. I'm going to do a rebase and recreate the spinmint, in case master had a bug at the moment where you were testing.

**Pull request merged**
