### PR TITLE
Update slash command permission

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
https://community.mattermost.com/private-core/pl/1ewong9ykbduxri5f5r1p1adze

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50379

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by GowthamD0606** [comment]
m

**Review by m1lt0n — DISMISSED** [review]

**Review by oh6hay — APPROVED** [review]
LGTM

**Review by mickmister — APPROVED** [review]

**Review by m1lt0n — APPROVED** [review]

**Comment by DHaussermann** [comment]
Tested and passed.

I have regression tested the affected area. No changes found LGTM!

**Review by DHaussermann — APPROVED** [review]

**Comment by amyblais** [comment]
Needs a cherry-pick to ``cloud``.

**Comment by amyblais** [comment]
> Needs a cherry-pick to `cloud`.

@hanzei Kind reminder in case you missed my previous notification.

**Pull request merged**
