### PR TITLE
[MM-29220] Adds a client function that retrieves the full status report

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR adds a new client method that returns the full ping report instead of filtering just the `status` key.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29220

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Lgtm

**Review by isacikgoz — APPROVED** [review]
Nice! 🤖

**Review by lindy65 — APPROVED** [review]
Thanks @mgdelacroix - this will be tested after merge 👍

**Pull request merged**
