### PR TITLE
MM-24388 update github.com/minio/minio-go/v6 to v6.0.53

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary

This PR updates github.com/minio/minio-go/v6 to v6.0.53 which fixes a bug in S3 IAM authentication reported by a customer.

Server unit tests passed locally.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-24388

### CODE REVIEW

**Comment by wiggin77** [comment]
> Do we have any sense why this /seemed/ to only start failing after the affected customer upgrade to v5.22? Was it just coincidence?

I looked at our usage of minio going back to pre-5.22 and no code changes.  I looked at the history of minio code for the codepath in question going back through all versions we've used; that code hasn't changed in years.  

However, the AWS APIs being called did add a new props engine that handles authentication (IMDSv1 -> IMDSv2) in Nov 2019.  Customer would set the new API in their AWS control panel.  

That said, I suspect a config change on customer's side causing a call to minio `getIAMRoleURL` without a hostname.

**Comment by lindy65** [comment]
Hi @wiggin77 - can this be tested on the spinwick or should an SDET test post-merge?

**Comment by wiggin77** [comment]
> Hi @wiggin77 - can this be tested on a spinwick or should an SDET test post-merge?

This library update fixes a bug in authenticating against an S3 file store.  I'm not sure how QA normally tests something like that.

**Comment by lindy65** [comment]
Thanks @wiggin77,

Can you tell me how you validated that your fix is working?  e.g. is S3 file storage with IAM credentials available for QA to test against?

**Comment by wiggin77** [comment]
> Can you tell me how you validated that your fix is working? e.g. is S3 file storage with IAM credentials available for QA to test against?

The fix was validated in the upstream library's repo.  I was not able to do any additional validation as I'm not set up for S3 access.  At some point I assume someone in QA tested S3 file storage, but possibly not with IAM credentials.  I don't know how far we want to go in testing upstream libraries against different AWS configurations.  That could balloon to a lot of new testing.

**Comment by wiggin77** [comment]
Hi @wiersgallak , is this something you need to approve:  update to library that fixes a bug?

**Comment by wiersgallak** [comment]
@wiggin77 No approval needed from me.  Thanks!

**Comment by saturninoabril** [comment]
Oh... sorry for removing cherry pick label.  It's done by mistake as I intended to add complete/add labels

**Comment by wiggin77** [comment]
Doesn't matter, looks like it has to be done manually due to merge conflict (?)

**Pull request merged**
