### PR TITLE
Update supported versions

### PR DESCRIPTION
**Pull request by amyblais**
- Our Desktop app v5.2 will release with Electron v20, which comes with Chrome v104+.
- Updated Edge version to match with Slack's supported version https://slack.com/help/articles/115002037526-System-requirements-for-using-Slack.

Will add the above updates to the changelog.

### CODE REVIEW

**Comment by amyblais** [comment]
/release-note

Will add the above notes to the changelog.

**Comment by esethna** [comment]
Changing the PM review to @nab-77 given this is a deployment AOR

**Comment by devinbinnie** [comment]
@amyblais I'm planning on upgrading to Electron v20 for Desktop v5.2 before we cut the release, so Chrome version should be v104.

**Review by devinbinnie — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
