### PR TITLE
Fix golangci-lint target for non GOPATH installations

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Fix running `make make golangci-lint` if your installation is not in `GOPATH`.

cc @agnivade

#### Ticket Link
Follow up on https://github.com/mattermost/mattermost-server/pull/12909

### CODE REVIEW

**Comment by agnivade** [comment]
It's slightly tricky. The installation command puts it in GOPATH/bin - `curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(GOPATH)/bin v1.21.0"`. So if one uses this, the current command is correct.

But if we want to do away with mentioning GOPATH, then we should change this command too to install somewhere else, or just make the directory to some placeholder value.

**Comment by hanzei** [comment]
I was assuming that `$GOPATH/bin` is part of `$PATH`, otherwise `command` would not find it anyway, right?

My goal here is to allow users to chose the way the install `golang-ci` and where they install it, as long it's in `$PATH`.

**Comment by agnivade** [comment]
Maybe my saying "it's tricky" implied that it would cause an error in some way. Sorry for the confusion. It's perfectly fine.

I meant that the install command puts it in GOPATH/bin. So it seems that we are asking the user to install the tool in GOPATH/bin, but using just the binary name while running it. Using just the binary name means to me that the binary can be in anywhere in PATH, which is not the case here.

I was saying if we are removing GOPATH from the invocation site, we should remove it from both places. 

Not a biggie for me. 1/5 on it.

**Comment by streamer45** [comment]
> Maybe my saying "it's tricky" implied that it would cause an error in some way. Sorry for the confusion. It's perfectly fine.
> 
> I meant that the install command puts it in GOPATH/bin. So it seems that we are asking the user to install the tool in GOPATH/bin, but using just the binary name while running it. Using just the binary name means to me that the binary can be in anywhere in PATH, which is not the case here.
> 
> I was saying if we are removing GOPATH from the invocation site, we should remove it from both places.
> 
> Not a biggie for me. 1/5 on it.

My interpretation of this is a bit different. I think we are targeting two different user types:

- The ones that don't know what `golangci-lint` is and for them we suggest they install it in `$GOPATH/bin` so they don't clutter up their system with that untracked dependency. I find this to be the correct approach.  
- Then we have more advanced users who either already use `golangci-lint` or are willing to install it in a different directory covered by `$PATH` or through a different mean (e.g. system package manager).

**Comment by hanzei** [comment]
I agree with your interpretations @streamer45. Could you elaborate why you think storing the binary in `$GOPATH/bin` is the correct approach?

I'm inclined to just link to https://github.com/golangci/golangci-lint#install instead of suggesting ` curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(GOPATH)/bin v1.21.0` and let the user figure out how he/she wants to install the software.

**Comment by streamer45** [comment]
> I agree with your interpretations @streamer45. Could you elaborate why you think storing the binary in `$GOPATH/bin` is the correct approach?

Well, maybe I should have said *a more* correct approach when the alternative is installing it in the default system path. Also, since it's a golang specific tool I think it makes sense for it to reside under `$GOPATH`.

> I'm inclined to just link to https://github.com/golangci/golangci-lint#install instead of suggesting ` curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(GOPATH)/bin v1.21.0` and let the user figure out how he/she wants to install the software.

This solution works for me too :+1:

**Comment by hanzei** [comment]
@agnivade @reflog @streamer45 Please take a second look

**Comment by hanzei** [comment]
@reflog Could you give this a review please?

**Pull request merged**
