### PR TITLE
[MM-51076] Fix dropdown in modal for adding users in a group

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
While there was a class about making overflow visible, it was overridden because of how CSS is structured.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51076

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected

**Before**

image

**After**

image

**Pull request merged**
