### PR TITLE
Add 'files' as a reserved team

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Noticed that we have a `/files` route in the root of the server, when `files` isn't in the reserved list. This PR add `files` to the reserved team list.

```release-note
Added 'files' as a reserved team name.
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
I know this is not a breaking change, but nevertheless, it might be a good idea to add it as a release note for the sake of completeness.

**Comment by devinbinnie** [comment]
> I know this is not a breaking change, but nevertheless, it might be a good idea to add it as a release note for the sake of completeness.

Added, let me know if the wording needs tweaking at all.

**Review by hmhealey — APPROVED** [review]

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4329

**Pull request merged**
