### PR TITLE
Cherry-Pick OAuthStore migration - Release 5.26

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

This PR adds the `OAuthStore` to return plain errors on top of release-5.26 branch.

### CODE REVIEW

**Comment by rvillablanca** [comment]
Failed CI 😔

**Comment by agnivade** [comment]
Can you do a "git commit --allow-empty -m "Trigger CI" && git push"?

**Comment by rvillablanca** [comment]
Didn't know about `--allow-empty` :) even it is not in my current bash completion. So now I won't have to add en empty line to trigger CI :sweat_smile:

**Pull request merged**
