### PR TITLE
[MM-52287] - Cloud Free should not show the ability to start a trial

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Before we reverse the current cloud flow, when workspaces are on starter and never done a trial, admins have the ability to start an enterprise trial. However, soon workspaces won't be able to request their own trials, and that means we need to take away this ability.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52287

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]

**Review by neallred — APPROVED** [review]
LGTM, thanks @AGMETEOR !

**Comment by AGMETEOR** [comment]
@marianunez can this wait for a QA review on Monday?

**Comment by marianunez** [comment]
> @marianunez can this wait for a QA review on Monday?

Yes, we currently can't cherry-pick to cloud so we have time

**Comment by yasserfaraazkhan** [comment]
Hi @AGMETEOR ,
in QA steps, 
should there be no way for Admin to start a trial ?

just wanted to check the Acceptance criteria
Screenshot 2023-04-24 at 12 48 21 PM

**Comment by yasserfaraazkhan** [comment]
> > Hi @AGMETEOR , in QA steps, should there be no way for Admin to start a trial ?
> > just wanted to check the Acceptance criteria Screenshot 2023-04-24 at 12 48 21 PM
> 
> Yes that's true

got it Allan

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by AGMETEOR** [comment]
Hey @amyblais I think we need to cherry-pick to cloud?

**Comment by AGMETEOR** [comment]
Alri

> Yes, after the current cloud incident has been resolved, we can cherry-pick this.

Alright. Thanks. Hey @yasserfaraazkhan I think this confirms cloud branch has some issues currently

**Pull request merged**
