### PR TITLE
[MM-12958] Support running two Mattermost instances on the same domain using subpaths

### PR DESCRIPTION
**Pull request by d28park**
#### Summary
Provides the option to allow authentication cookies to include subpath. This allows a user to have multiple sessions open under the same domain as long as they are at different subpaths (eg - example.com/chat1 and example.com/chat2). 

This functionality is active when both a 'SiteURL' is set and the 'AllowCookiesForSubdomains' flag is set to 'true'. Setting the flag to 'false' maintains the current subpath behavior (but will cause the new cypress test to fail).

#### Linked mattermost-webapp PR
https://github.com/mattermost/mattermost-webapp/pull/2533

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/10345

JIRA: https://mattermost.atlassian.net/browse/MM-12958

#### Required Testing

- Testing through a proxy server / in production environment
- Testing on all browsers (Chrome/Firefox done)
- Testing on Mobile
- MFA, OAuth2.0, SAML, LDAP

#### Known Issues

- Running a Mattermost instance both at top level (example.com) and a subpath (example.com/chat) allows the subpath to read the top level cookies and clear user cookies (several solutions available if this is going to be a common case)

### CODE REVIEW

**Comment by hmhealey** [comment]
I'm going to defer to @DSchalla on review for this one since I'm not that familiar with cookies, and I think he'd have a better idea of potential problems to look for.

**Comment by d28park** [comment]
Hi @DSchalla, thank you for the review!

It's an existing config flag, which looks like it was put in to enhance cookie security in the first place by explicitly setting domain. I tied the new functionality to that flag so developers / end users could choose between current subpath behavior and the new explicit path behavior.

I do agree though that the current pattern doesn't follow best practices and I would be happy to remove that option by forcing an explicit path attribute whenever Mattermost is running on a subpath. I believe @lieut-data did a lot of work on subpaths so I'll let him confirm if we need to keep the option to have top level cookies for subpath instances for any reason.

And yup, no breaking changes. I would like to reiterate though that always limiting cookie scope to subpath is still susceptible to the edge cases I have mentioned in the PRs.

**Comment by lieut-data** [comment]
Agree with @DSchalla here: I think the constrained cookie path should kick in automatically when a subpath is configured, negating the need to change the semantics of `AllowCookiesForSubdomains`.

**Comment by lieut-data** [comment]
Already posted as such on the webapp PR, but if I can help with this in any way, @d28park, let me know :)

**Comment by jasonblais** [comment]
Hey @d28park,

Let us know if you have any questions about the feedback from @lieut-data above. Would be happy to help you finish this PR? :)

**Comment by lieut-data** [comment]
@DSchalla & @crspeller, I've pushed some changes to address feedback above -- could I get another set of eyes on these changes?

**Comment by hanzei** [comment]
Thanks for the contribution @d28park and @lieut-data for finishing this! :tada:

**Pull request merged**
