### PR TITLE
[MM-52822] webapp/channels : Migrate "components/gif_picker/components/InfiniteScroll/index.js"

### PR DESCRIPTION
**Pull request by nazrul7711**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52822
Fixes https://github.com/mattermost/mattermost-server/issues/23438

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@nazrul7711 just curious why have you closed the PR

**Comment by nazrul7711** [comment]
hey @M-ZubairAhmed i am new to github and was not able to set up mattermost server locally. so i tried deleting repos and setting up afresh , didn't knew this would close the pr .
anyways m trying again if it works i will submit a new pr

**Comment by M-ZubairAhmed** [comment]
@nazrul7711 thank you for you reply. Can you reach out on https://community.mattermost.com/core/channels/tickets and tag me if you have any questions.

**Comment by nazrul7711** [comment]
Ok

**Pull request closed without merging**
