### PR TITLE
SystemStore migration to return plain errors

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

Continuing with the migration of store layer, this PR migrates the `SystemStore` to return plain errors in all its methods.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/14813

### CODE REVIEW

**Comment by hanzei** [comment]
@rvillablanca Heads up that there is an CI error:
```
golangci-lint run ./...
 
app/license.go:39:9: nilness: tautological condition: non-nil != nil (govet)
 
	if err != nil {
 
	       ^
 
app/license.go:30:49: nilness: tautological condition: non-nil != nil (govet)
 
			if _, err = s.SaveLicense(licenseBytes); err != nil {
 
			                                             ^
 
make: *** [Makefile:191: golangci-lint] Error 1
 ```

**Comment by rvillablanca** [comment]
Thanks for the heads up @hanzei they were already fixed

**Comment by agnivade** [comment]
@ogi-m - Testing the `/config/client` endpoint and saving/removing licenses should be sufficient. Thanks!

@rvillablanca - Quick note that this has some conflicts now.

**Comment by stylianosrigas** [comment]
test server removed due some underlying issues in the cluster that made this one unstable.

**Comment by hanzei** [comment]
@ogi-m Gentle reminder to QA test this PR :). Feel free to ask someone else for the review if you are short on time.

**Comment by rvillablanca** [comment]
Conflicts resolved!

**Comment by agnivade** [comment]
@rvillablanca - There seems to be a key `app.system.get.app_error` which does not have a corresponding translation string in en.json.

**Comment by rvillablanca** [comment]
@agnivade Fixed

**Pull request merged**
