### PR TITLE
Fix empty translation strings

### PR DESCRIPTION
**Pull request by metanerd**
#### Summary
Fixes 4 empty translation strings found in pt_BR.json 

#### Release Note

```release-note
```

### CODE REVIEW

**Comment by amyblais** [comment]
@metanerd Can you also help cherry-pick the translation PRs to the ``cloud`` branch?

**Review by jaydeland — APPROVED** [review]

**Comment by metanerd** [comment]
@amyblais Will do!

**Comment by metanerd** [comment]
Need to completely update this one. Closing.

**Pull request closed without merging**
