### PR TITLE
remove unsused/unnecessary gitlab ci steps

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
1. Remove unused gitlab-ci steps which was commented out more than a year. No need to have those.
2. Remove the schema tests as they are not required anymore.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by toninis** [comment]
@isacikgoz Is this related to [this](https://git.internal.mattermost.com/mattermost/ci-only/mattermost-server/-/pipelines/311437) failure from Gitlab ?

**Review by toninis — APPROVED** [review]

**Comment by isacikgoz** [comment]
@toninis Yes, it also removes the gitlab part of this script. I don't know why we left these over there 🤷

**Comment by toninis** [comment]
Nice 🚀  No worries . This should be cherry-picked on cloud branch then . 
cc: @amyblais

**Review by agnivade — APPROVED** [review]

**Comment by amyblais** [comment]
@isacikgoz Please help open a manual cherry-pick PR for the ``cloud`` branch.

**Pull request merged**
