### PR TITLE
MM-41909: Allow 1 char channel name

### PR DESCRIPTION
**Pull request by KevinSJ**
#### Summary

This pull request aims to reduce the limit of channel display name as well as channel URL (referred to as name) to one character assuming there are no technical reasons for the 2 char limit.

Note that the current server side code only enforces validation on the channel name (or so called url) only and not on the display name, it is kept this way.

I'm not sure about the way I handled the required regex changes, please suggest any changes needed.

This is the server side PR, additional PR on the UI side will be created separately.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/19788
JIRA: https://mattermost.atlassian.net/browse/MM-41909

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by KevinSJ** [comment]
I'm unable to check what's failing in the e2e run for some reason, can you share that with me? @hmhealey

**Comment by hmhealey** [comment]
I can't see any reason that it might be failing. I'll try updating the branch and restarting the tests

/update-branch

**Comment by isacikgoz** [comment]
@hmhealey do your remember why we were not allowing this before? I couldn't find the actual reasoning.

**Comment by hmhealey** [comment]
No, I can't find any reason for it. That's limit has existed as far back as the initial commit to GitHub ([link](https://github.com/mattermost/mattermost-server/blob/56e74239d6b34df8f30ef046f0b0ff4ff0866a71/model/utils.go#L232)). I haven't looked to see if there's any technical reason for it, but I guess it's possible that that was copied from the team naming restrictions. Those were more restrictive originally because they were used for subpaths (like `https://teamname.mymattermost.com` instead of `https://mymattermost.com/teamname`)

**Review by isacikgoz — APPROVED** [review]
LGTM thanks @KevinSJ 🚀

**Comment by hmhealey** [comment]
Merging this so that it can be tested as part of the corresponding web app PR

**Pull request merged**
