### PR TITLE
MM-36271: Bump major version to 6.0

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-36271

```release-note
We bump the major version to 6.0
```

### CODE REVIEW

**Comment by streamer45** [comment]
Were we planning of bumping model and schema version as well or keeping those in a separate PR?

**Comment by agnivade** [comment]
Ah good point. Let me do that.

**Comment by agnivade** [comment]
Done.

**Review by streamer45 — APPROVED** [review]
Awesome, thanks :+1:

**Comment by agnivade** [comment]
@streamer45 - the store schema version upgrade has a problem because there is a unit test which upgrades the DB schema and verifies it matches with `CurrentSchemaVersion`. Which essentially means we need to have the line `if shouldPerformUpgrade(sqlStore, Version5380, Version6000) {`.

Given that we don't even have the line for 5380 yet, I would defer it from being bumped until we actually cut v6.

Thoughts?

**Comment by streamer45** [comment]
> @streamer45 - the store schema version upgrade has a problem because there is a unit test which upgrades the DB schema and verifies it matches with `CurrentSchemaVersion`. Which essentially means we need to have the line `if shouldPerformUpgrade(sqlStore, Version5380, Version6000) {`.
> 
> Given that we don't even have the line for 5380 yet, I would defer it from being bumped until we actually cut v6.
> 
> Thoughts?

I think we should remove the if blocks from 5.38 since that will be based of Cloud which has been merged already and then proceed normally. Also, we just merged 6.0 branch into master so make sure to update the base branch for this.

**Comment by metanerd** [comment]
Changed base branch to master, otherwise I am not able to delete release-6.0 branch.

**Pull request merged**
