### PR TITLE
Add experimental setting in config for websocket jitter range

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Added new config value for jitter in websocket incoming connection.

#### Ticket Link
https://github.com/mattermost/mattermost-webapp/pull/12095

#### Release Note

```release-note
New experimental config for setting websocket jitter in client.
```

### CODE REVIEW

**Comment by agarciamontoro** [comment]
The code looks good. But should we let the jitter value be modified via the configuration? I wonder whether it would make more sense to be opinionated here and use the same value everywhere. We could still expose whether the jitter is enabled at all via the experimental setting, though.
Thoughts? Also: do we have data on what a good value for jitter is?

**Comment by M-ZubairAhmed** [comment]
@agarciamontoro we dont have data on whats the good value, generally its 1 sec.
Thats another reason we have range instead of on off setting for this.

**Review by agnivade — CHANGES_REQUESTED** [review]
I also commented on the other PR. I think we should investigate any ordering issues deeply before trying to solve it with a config.

**Pull request closed without merging**
