### PR TITLE
Fixed Typo in command_test.go

### PR DESCRIPTION
**Pull request by raghuiamsingh**

### CODE REVIEW

**Comment by raghuiamsingh** [comment]
@hanzei Found the typo while going through the command_test.go file

**Comment by hanzei** [comment]
@raghuiamsingh Would you be interested in adding automation to find these kind of issues?

**Comment by raghuiamsingh** [comment]
@hanzei Yes.

**Comment by raghuiamsingh** [comment]
@hanzei Will be integrating https://github.com/client9/misspell/ in a separate branch. You can merge this one.

**Comment by jespino** [comment]
Merged! Thanks @raghuiamsingh! :dancing_men:

**Pull request merged**
