### PR TITLE
MM-49638 - Prepackage calls v0.12.1

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Calls -> v0.12.1

/cc @amyblais

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-49638

#### Release Note
```release-note
Prepackage Calls version v0.12.1
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]

**Comment by streamer45** [comment]
> Creating a new SpinWick test server using Mattermost Cloud.

Plugin should start this time `rtcd` was updated.

**Review by crspeller — APPROVED** [review]

**Comment by cpoile** [comment]
Works on the test server.

**Pull request merged**
