### PR TITLE
MM-52161_The Marketplace modal has some display issues

### PR DESCRIPTION
**Pull request by julmondragon**
#### Summary
Updates in App Marketplace modal
- Records with a 2nd line for update now fits in the row without creating sub-scroll
- Long descriptions shown with ellipsis add a tooltip with full description
- Description opacity updated

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52161

#### Screenshots
Screen Shot 2023-04-18 at 4 08 43 PM

Screen Shot 2023-04-19 at 11 18 40 AM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]
Thanks @julmondragon

**Comment by annelieseklein** [comment]
looks good! I'd just left-align the tooltip please :)

**Review by annelieseklein — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
Looks great @julmondragon!

And the E2E tests passed without a hitch! 🎉

**Pull request merged**
