### PR TITLE
MM-29400  Mark all current notices as viewed for newly created users

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

 Added clearing of notices for new users
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-29400

### CODE REVIEW

**Review by ogi-m — APPROVED** [review]
QA will test after merge

**Comment by amyblais** [comment]
@ashishbhate Please prioritize review for v5.28.

@reflog Claudio is off today, maybe another dev can review this?

**Comment by reflog** [comment]
@amyblais - replaced him with @mgdelacroix

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Review by ashishbhate — APPROVED** [review]

**Pull request merged**
