### PR TITLE
Changed query in func (s SqlChannelStore) AutocompleteInTeam so that …

### PR DESCRIPTION
**Pull request by CCCCY096**
…private channel is included.

#### Release Note

```release-note
```

### CODE REVIEW

**Comment by hanzei** [comment]
@grundleborg Requesting a review from you as this is a quite substantial change I want to get confirmation that it's the right direction.

**Comment by mgdelacroix** [comment]
Thanks a lot for your contribution @CCCCY096! I just wanted to warn you that reviewing the pull request will take some time, as we're approaching the Christmas season and the changes you've proposed have some implications that we have to plan for. Those implications affect mainly UX/UI (how would we show and distinguish the private channels when autocompleting) and the search engines, as we'd have to add the necessary mechanisms for them to be able to index and search private channels as well.

We'll have a discussion around those and will let you know the next step for the PR

**Comment by jfrerich** [comment]
@mgdelacroix and @grundleborg, ping for reviews. 

Thanks for the PR, @CCCCY096!  The CI build is failing.  Could you please look into the failures and resolve them to help push this PR through to completion :)

**Comment by emilyacook** [comment]
> @mgdelacroix and @grundleborg, ping for reviews.
> 
> Thanks for the PR, @CCCCY096! The CI build is failing. Could you please look into the failures and resolve them to help push this PR through to completion :)

gentle ping @mgdelacroix @grundleborg @CCCCY096

**Comment by lindy65** [comment]
Hi @CCCCY096 - I'm helping to review stale PRs and, since we haven't heard from you in a few months, I'll close this PR for now. Please feel free to re-open if you're able to prioritize. Thanks!

//cc @mgdelacroix @grundleborg

**Pull request closed without merging**
