### PR TITLE
MM-26675/26676: Add missing translation strings

### PR DESCRIPTION
**Pull request by agnivade**
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-26675
https://mattermost.atlassian.net/browse/MM-26676

### CODE REVIEW

**Comment by agnivade** [comment]
@lindy65 - I am not sure if there's a good way to verify this. You would need to trigger 2 _exact_ errors and verify the error message.

**Comment by lindy65** [comment]
Thanks @agnivade - I'm not sure how to trigger those errors...  Is there a way one of the devs can peer-test locally?

**Comment by agnivade** [comment]
Might be difficult. @jespino - is it feasible to test this?

**Comment by lindy65** [comment]
@jespino - gentle ping on the question for testing above?

**Comment by agnivade** [comment]
/update-branch

@lindy65 - I don't believe there's a way to test this. Since this does not directly touch the code, I would say it is ok to merge.

**Pull request merged**
