### PR TITLE
[MM-30344] utils/markdown: fix index out of range

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Add a few checks to avoid out of ranges in `parseImageDimensions`.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30344

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Changes look good :+1: 
Overall logic is a bit convoluted but I guess that's what parsing can get like.

**Review by hmhealey — APPROVED** [review]

**Comment by isacikgoz** [comment]
@lindalumitchell Even though automated tests cover the possible occurrences, we can do some test with markdown with images.

**Review by lindalumitchell — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
