### PR TITLE
 Rename event-id -> event_id for API naming consistency and safe parameter/variable name use

### PR DESCRIPTION
**Pull request by unode**
#### Summary

Originally filed at https://github.com/mattermost/mattermost-plugin-playbooks/pull/1842

Hi everyone. I'm the maintainer of [python-mattermost-autodriver](https://github.com/embl-bio-it/python-mattermost-autodriver) a Python mattermost API driver created by automatic conversion of the [mattermost API reference OpenAPI spec](https://github.com/mattermost/mattermost-api-reference).

Since https://github.com/mattermost/mattermost-api-reference/commit/63ee7bf256e5c35144a317016df2068a16926825 the playbook API has been included in [mattermost API reference](https://github.com/mattermost/mattermost-api-reference) (commit by @neflyte back in October 2022).

In the automatic conversion used in [python-mattermost-autodriver](https://github.com/embl-bio-it/python-mattermost-autodriver) we treat URL argument names as parameters. In that context `event-id` is an invalid name for a parameter. Through the entire API spec, the variable included in this PR is is the only occurrence of a dash in a path parameter. In all other cases underscores are used.

This PR proposes renaming `event-id` to `event_id` ensuring consistency and allowing the conversion approach used by python-mattermost-autodriver to remain viable.

It's not clear to me if the YAML API file patched in this PR is automatically generated from some other file. The current is what I could trace coming from [mattermost API reference](https://github.com/mattermost/mattermost-api-reference).

Would the proposed rename be acceptable given the current API state or are additional changes needed elsewhere?

Thanks!

#### Release Note

* API additions—new endpoint, new response fields, or newly accepted request parameters.

```release-note
Use underscore in timeline API (event-id -> event_id) for consistency with other API arguments
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
Cool project! Glad these API docs are useful! 

Those are URL parameters so those names don't get used in the code anywhere so the change should be safe. 

I wonder if we can add a linting rule somehow to warn to use underscores instead of dashes?

**Review by lindalumitchell — APPROVED** [review]
Thanks, LGTM!

**Comment by unode** [comment]
Thanks everyone for your time!

**Pull request merged**
