### PR TITLE
Cherry-picking translations

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Cherry-picking translations into release-7.7

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/21909/

```release-note
NONE
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by amyblais — APPROVED** [review]

**Comment by amyblais** [comment]
@Willyfrog Would you know why the CI is still pending here?

**Comment by amyblais** [comment]
@m1lt0n Do you know if this can be merged manually or how the CI can be unblocked?

**Comment by m1lt0n** [comment]
Hey @amyblais I don't know what's blocking the "Testing EE" step as this step is not publicly available (to see where it fails or why it remains pending). I don't know if it is related to the issue we had a couple of weeks back where some changes in the circleci config of enterprise was needed and done. Release team should have access to the report of the pending step to inform us.

**Comment by amyblais** [comment]
> I don't know what's blocking the "Testing EE" step as this step is not publicly available (to see where it fails or why it remains pending). I don't know if it is related to the issue we had a couple of weeks back where some changes in the circleci config of enterprise was needed and done. Release team should have access to the report of the pending step to inform us.

@phoinixgrr Would you know why the CI is stuck here?

**Comment by phoinixgrr** [comment]
> > I don't know what's blocking the "Testing EE" step as this step is not publicly available (to see where it fails or why it remains pending). I don't know if it is related to the issue we had a couple of weeks back where some changes in the circleci config of enterprise was needed and done. Release team should have access to the report of the pending step to inform us.
> 
> @phoinixgrr Would you know why the CI is stuck here?

Seems like related to the changes introduced here: 
https://github.com/mattermost/enterprise/pull/1327

Will check and revert.

**Comment by Willyfrog** [comment]
@amyblais I just restarted the job, as it seem to fail setting up focalboard, but I'm not sure if that was the original issue

**Comment by m1lt0n** [comment]
@phoinixgrr The change in enterprise was introduced to fix the "testing EE" step being stuck on "pending" state in all PRs for translations, which means reverting it will probably lead to the issue starting to happen again though cc: @spirosoik

**Comment by phoinixgrr** [comment]
> @phoinixgrr The change in enterprise was introduced to fix the "testing EE" step being stuck on "pending" state in all PRs for translations, which means reverting it altogether will probably lead to the issue starting to happen again though (ie blocking server translations again) cc: @spirosoik

Thanks for the info @m1lt0n  
Since I do not have full context on this, I will need some time to :

1. Understand the changes introduced with https://github.com/mattermost/enterprise/pull/1327 
2. Understand the issue that we are currently facing 
3. Produce a solution.

Will revert when everything is in place.

**Comment by amyblais** [comment]
I've created a ticket to keep track of it: https://mattermost.atlassian.net/browse/CLD-4743.

**Comment by phoinixgrr** [comment]
Investigation has been performed, and findings are posted at https://mattermost.atlassian.net/browse/CLD-4743 

cc: @m1lt0n  @spirosoik , I will need some context in order to proceed with the fix. Kindly comment in the ticket above to unblock this.

**Review by m1lt0n — APPROVED** [review]

**Comment by phoinixgrr** [comment]
Merged https://github.com/mattermost/enterprise/pull/1347 and re-triggered tests. 
[Previous failing](https://app.circleci.com/pipelines/github/mattermost/enterprise/20145/workflows/cf270c39-e79a-4753-9506-0f41d2db2114) pipeline now [completes successfully  ](https://app.circleci.com/pipelines/github/mattermost/enterprise/20207/workflows/b0e07751-c75b-4a8a-a57f-298b91799e07) 

Fix is confirmed  
:shipit:

**Comment by amyblais** [comment]
Thank you Akis!

**Pull request merged**
