### PR TITLE
[MM-30910]: Change receiver name for (me *InitialLoad) in model/initial_load.go to be more idiomatic

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary 

Updated receiver name for (me *InitialLoad)  to be more idiomatic.

#### Ticket Link

Fixes: #16369 
JIRA: https://mattermost.atlassian.net/browse/MM-30910

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by haardikdharma10** [comment]
I think no change is required here @agnivade.

**Review by isacikgoz — APPROVED** [review]
Thanks for the contribution! @haardikdharma10 🎉

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
Since this is a code refactor, there's no QA needed for this.

**Pull request merged**
