### PR TITLE
[MM-47415] remove all mentions from Cloud Starter to Cloud Free

### PR DESCRIPTION
**Pull request by Afsoon**
#### Summary
Remove the mention to Cloud Starter on Delinquency Emails

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47415

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by emmyni — APPROVED** [review]
LGTM @Afsoon :)

**Comment by Afsoon** [comment]
gentle ping @AGMETEOR

**Review by AGMETEOR — APPROVED** [review]
LGTM

**Pull request merged**
