### PR TITLE
translations PR 20191104

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by enahum** [comment]
@cpanato no idea what this GolanCI analyze is doing.. can you take a look please.

**Comment by cpanato** [comment]
@hanzei please look on this, you are the father of golangci

**Comment by hanzei** [comment]
This should be fixed if https://github.com/mattermost/mattermost-server/pull/12987 is merged. You can just ignore this for now.

**Comment by enahum** [comment]
Well then @cpanato it appears that you can approve and merge ;)

**Pull request merged**
