### PR TITLE
[MM-45490] Adding compliance export config to client

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
This config is needed to determine top threads compliance checks

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45490

#### Related Pull Requests
- https://github.com/mattermost/mattermost-webapp/pull/10716

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by plant99 — APPROVED** [review]

**Comment by BenCookie95** [comment]
> Thanks @BenCookie95, looks good. A few really minor requests from me:
> 
> 1. Can we update the width of the confirmation modal to 600px instead of 800px?
> 2. I'm wondering if we should make the message in italics so it's visually differentiated from other thread previews. So it would look like the below
> 
> image

@matthewbirtch both are fixed now

**Review by matthewbirtch — APPROVED** [review]
LGTM!

**Pull request merged**
