### PR TITLE
[MM-27700] storetest/channel_store: fix flaky test for search too short term

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
This PR attempts to fix a flaky test that is probably caused for searching a too short term that could possibly generated in random names.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27700

### CODE REVIEW

**Comment by grundleborg** [comment]
Adding @mgdelacroix as hopefully he knows the search test suite well enough to judge my previous comment :)

**Comment by isacikgoz** [comment]
> One question, was `the` being used specifically to test for a stop word?

@grundleborg  There are several channel names that are generated with `model.NewId()`  in the same test suite which occasionally have `the` word in the name. And the failing test is searching for `the` in the channel names so it was finding more than 1 channels, it's a guess though.

**Comment by agnivade** [comment]
Yes, this has happened with other flaky tests which I fixed. The term has to be atleast 4 characters long to not collide randomly. Anything less than that is not random enough.

**Comment by grundleborg** [comment]
@isacikgoz I understand the issue, but I'm concerned that the fix you have made is possibly changing the nature of the test. If this test is testing searching for a "stop word", then changing it to "example" means the test is no longer testing for stop words ("example" is not a stop word). If that is the case, we'll need to find another way of doing this test that doesn't change what it is testing for. I'm not 100% sure about this though, so asking Miguel for his opinion since he knows search better than me, or we can reach out to Mario when he's back from holidays if not.

**Comment by grundleborg** [comment]
I had a look at the MySQL/Postgres/Elasticsearch stopword lists and the first 4+ letter one I spotted was `that`. Perhaps you can change it to that (haha) and we solve both problems?

**Comment by grundleborg** [comment]
Other option would be just not using randomly generated values for the searchable fields in this test?

**Comment by isacikgoz** [comment]
I see, it seemed a regular term search to me :) Anyway, if "that" solves the issue, I'm fine with it. If we decide to don't use randomly generated names there are several similar tests like this. Maybe we want to update them as well in a separate ticket.

**Pull request merged**
