### PR TITLE
MM-37417: Push notification authz fix.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Fixes the authorization of the `POST /api/v4/notifications/ack` API endpoint.

A bunch of places in code just do this channel-scoped authorization check:

```go
a.SessionHasPermissionToChannel(*session, channel.Id, model.PermissionReadChannel)
```

... and a few also do this team-scoped check:

```go
a.SessionHasPermissionToTeam(*session, channel.TeamId, model.PermissionReadPublicChannel)
```

I wasn't inclined to remove the team check as part of this fix, but rather opted to centralize similar checks into a common function. As a future iteration we can determine if the team-scoped permission checks are necessary.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37417

#### Release Note

```release-note
Fixed the authorization of the POST /api/v4/notifications/ack API endpoint.
```

### CODE REVIEW

**Comment by mkraft** [comment]
> Looks like a good clean-up from the code perspective (and added auth check, of course). I'll defer to @enahum if there's any implications from this change for the mobile apps.

It's still in `Work In Progress` status, I just wanted to get eyes on it early from an overall strategy perspective.

**Review by enahum — COMMENTED** [review]
LGTM, we need to make sure clients handle the error & status code appropriately

**Comment by mkraft** [comment]
> LGTM, we need to make sure clients handle the error & status code appropriately

I've created https://mattermost.atlassian.net/browse/MM-37465 to handle any potential client-side changes so that the authz fix isn't held up by anything.

**Review by srkgupta — APPROVED** [review]
Thanks @mkraft. Tested and the auth issue is fixed now and is working fine.

**Comment by mkraft** [comment]
@enahum The only change since your previous review is a unit test I added.

**Review by enahum — APPROVED** [review]

**Comment by amyblais** [comment]
Needs a manual cherry-pick to release-5.38. @mkraft

**Pull request merged**
