### PR TITLE
GH21563: Add the request context and logger to all public methods in app/admin.go

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR adds the request context and logger to all public methods in app/admin.go

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21563

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by sinansonmez** [comment]
cc @noxer

**Comment by sinansonmez** [comment]
cc: @isacikgoz

**Comment by agnivade** [comment]
Hey @sinansonmez - The objective here was to use the `Logger` method of the `request.Context` interface and replace all the `mlog.Debug|Info|Warn` calls with that.

Would you be able to fix the conflicts and replace those calls?

**Comment by sinansonmez** [comment]
@agnivade thanks for the clarification and sorry for the misunderstanding. I will try to replace calls with `Logger`

**Comment by sinansonmez** [comment]
@agnivade PR is ready for review

**Review by agnivade — APPROVED** [review]
Thanks!

**Comment by agnivade** [comment]
Hi @sinansonmez - the PR is good to go, but we've done some reorg in our codebase. Effectively all server code has moved under the server directory (with some exceptions). Would you like to fix the merge conflicts? Then we can merge this.

**Comment by sinansonmez** [comment]
Sure @agnivade, I will take a look

**Comment by sinansonmez** [comment]
@agnivade Opening a new PR was easier compared to fixing the conflicts. here is the new PR: https://github.com/mattermost/mattermost-server/pull/22898

**Pull request closed without merging**
