### PR TITLE
Update minimum supported Safari version to 12

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary
Update minimum supported Safari version to 12.

I'll try to remove the intl dep in the webapp repo in the coming days.

regards,
Nicolas

#Hacktoberfest

#### Ticket Link
Fixes :
* Fixes https://github.com/mattermost/mattermost-server/issues/12016
* https://mattermost.atlassian.net/browse/MM-13540

### CODE REVIEW

**Comment by cpanato** [comment]
@KuSh can you update this PR with latest master? thanks!

**Comment by KuSh** [comment]
@cpanato sure, I'll do it this evening (CEST)

**Comment by KuSh** [comment]
Done :+1:

**Pull request merged**
