### PR TITLE
doc: Added demo runner

### PR DESCRIPTION
**Pull request by belokonm**
#### Summary
This PR adds Runme button-label [Runme](https://runme.io/run?app_id=1919b7b7-0ecc-4965-a6c3-a9c35ee7775a) to run the project from latest commit with one click.
Button from summary running based on forked repo, in readme button will start working after PR is merge as for now there is no .runme folder in repo. 

**How it works:**
1. Runme clones the repository and builds a docker image for latest commit;
2. deploys docker image to k8s cluster;
3. creates domain with SSL certificate;
4. shows web application;
5. destroys app instance after 10 minutes.

You can find detailed information on how this works [here](https://runme.io/how-it-works). The small demo you can find [here](https://www.youtube.com/channel/UCEysV237wo321JatUTC6Rlg).

**Why it might be useful?**
- Runme is perfect solution to demonstrate current state of code/repository, anybody can just click the button and see the state;
- Runme totally free, we love open source projects and want to support them;
- Runme has only one limit: you can run one commit no more than once every 5 minutes;

### CODE REVIEW

**Comment by jasonblais** [comment]
Hi @belokonm, thanks for the contribution! What is a typical use case for people to use the runme app? It sounds like it is for demo purposes where you share the running application with others?

One concern with having it built the latest commit and run for 10 minutes is that the latest commit may be unstable and therefore lead to a bad user experience. Another worry I have is that it only lasts for 10 minutes, which may not be a sufficient time for demoing the Mattermost software (you can quickly test things like posting messages or inviting others, but people typically want to try an integration as well which takes a few extra minutes).

**Comment by belokonm** [comment]
@jasonblais , yes the main area for runme is quick demo without needs to install all locally. 
Potentially we can have button / branch. So if you have any branch which is stable or pre-released button can be created for them separately. Unfortunately I will not be able to impact 10 minutes limit it is predefined in service. Maybe it is better to contact owner of service directly.

**Comment by jasonblais** [comment]
Thanks @belokonm. Given Mattermost is a messaging app, we'd ideally have the demo run for more than 10 minutes. We want to give them time to invite others, try features, and more.

I really do appreciate the contribution, but at this time we'll have to close it given the limited benefit to the wider Mattermost user base. 

We're open to taking a second look if the service can run for longer than 10 minutes.

Thanks again,

**Pull request closed without merging**
