### PR TITLE
GH21563: Add the request context and logger to all public methods in app/admin.go

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR adds the request context and logger to all public methods in app/admin.go

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21563

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
Nice 👍

**Comment by agnivade** [comment]
@sinansonmez - There is a lint error:

```
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
channels/app/admin.go:13: File is not `gofmt`-ed with `-s` (gofmt)
	"github.com/mattermost/mattermost-server/v6/model"
```

**Comment by sinansonmez** [comment]
@agnivade I hope it is fixed now

**Review by agnivade — APPROVED** [review]
Thanks!

**Review by isacikgoz — APPROVED** [review]

**Pull request merged**
