### PR TITLE
[MM-18831] Trim whitespace of Display Name when channel is created

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

Per discussion [in the PR here](https://github.com/mattermost/mattermost-mobile/pull/3291), we now trim the whitespace of a channel's Display Name when the channel is created.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18831

### CODE REVIEW

**Comment by mickmister** [comment]
@migbot Is this good to merge for 5.17 or are we holding off on those PRs?

**Comment by mickmister** [comment]
@migbot In case I was a bit vague, I meant that since the fix version for this is 5.17, should this not be merged into master at this time?

**Comment by enahum** [comment]
@migbot you can merge now and cherry-pick after the branch is created or you can hold it as much as you want and merge it after the branch is cut. In this case @mickmister you can decide to merge it as it was already approved. Just don’t forget to cherry pick.

I’ll add the label so you don’t forget

**Comment by amyblais** [comment]
@mickmister Sorry, I think I accidentally approved this PR for v5.17 and didn't realize this is a feature. Can you revert the cherry-pick from v5.17 since we shouldn't introduce new functionality during quality releases?

**Comment by mickmister** [comment]
Thank you for pointing this out @amyblais :+1:

**Pull request merged**
