### PR TITLE
[MM-45868] Replace TeamId column with ThreadTeamId

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR replaces TeamId column in Thread table with ThreadTeamId column
See the discussion here https://community.mattermost.com/core/pl/55oqz4g7ni8tjnrgxd1y8cih1y

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-45868

#### Release Note

```release-note
Denormalizes Threads table by adding ThreadTeamId column
See details https://github.com/mattermost/mattermost-server/pull/21505#issuecomment-1290830941
```

### CODE REVIEW

**Comment by iomodo** [comment]
## Schema changes
Adding a new `ThreadTeamId` column to the `Threads` table. Even though it denormalizes the schema, we gain performance by removing the unnessesary joins.

## Test results for schema changes
instance: `db.r5.large`
size of `Threads` table: 846313 rows
number of posts: 12 million
number of reactions: 2.5 million

### MySQL
```sql
-- Drop any existing TeamId column from 000094_threads_teamid.up.sql
SET @preparedStatement = (SELECT IF(
    EXISTS(
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE table_name = 'Threads'
        AND table_schema = DATABASE()
        AND column_name = 'TeamId'
    ) > 0,
    'ALTER TABLE Threads DROP COLUMN TeamId;',
    'SELECT 1;'
));

PREPARE removeColumnIfExists FROM @preparedStatement;
EXECUTE removeColumnIfExists;
DEALLOCATE PREPARE removeColumnIfExists;

SET @preparedStatement = (SELECT IF(
    NOT EXISTS(
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE table_name = 'Threads'
        AND table_schema = DATABASE()
        AND column_name = 'ThreadTeamId'
    ),
    'ALTER TABLE Threads ADD COLUMN ThreadTeamId varchar(26) DEFAULT NULL;',
    'SELECT 1;'
));

PREPARE addColumnIfNotExists FROM @preparedStatement;
EXECUTE addColumnIfNotExists;
DEALLOCATE PREPARE addColumnIfNotExists;
```
Query OK, 0 rows affected (7.71 sec)

```sql
UPDATE Threads, Channels
SET Threads.ThreadTeamId = Channels.TeamId
WHERE Channels.Id = Threads.ChannelId
AND Threads.ThreadTeamId IS NULL;
```
Query OK, 846313 rows affected (51.32 sec)
Rows matched: 846313  Changed: 846313  Warnings: 0



### PostgreSQL
```sql
-- Drop any existing TeamId column from 000094_threads_teamid.up.sql
ALTER TABLE threads DROP COLUMN IF EXISTS teamid;

ALTER TABLE threads ADD COLUMN IF NOT EXISTS threadteamid VARCHAR(26);
```
ALTER TABLE
Time: 2.236 ms
```sql
UPDATE threads SET threadteamid = channels.teamid FROM channels WHERE threads.threadteamid IS NULL AND channels.id = threads.channelid;
```
UPDATE 847646
Time: 29744.608 ms (00:29.745)

## Backwards-compatibility
A previous version of Mattermost can run with the new schema changes 


## Table locks or impact to existing operations on the table
Table locks - Threads table
Zero downtime is possible when upgrading to this release.
Queries posted above can be run prior to upgrading Mattermost for both MySQL and PostgreSQL. After schema changes migration becomes instantaneous (0.78 sec)

**Review by lieut-data — APPROVED** [review]
Nice!!

**Comment by iomodo** [comment]
Any idea why building docker is failing?
```console
 > pushing mattermost/mm-te-test:2d40b41 with docker:
------
error: received unexpected HTTP status: 530 
```

**Review by agnivade — APPROVED** [review]

**Comment by iomodo** [comment]
Any additional checks needed? Or should we merge it?

Also should we remove the release note from the previous PR?

cc @lieut-data @agnivade

**Comment by lieut-data** [comment]
I'll defer to @agnivade, but am in favour of merging this patch.

**Comment by agnivade** [comment]
Go ahead with the merge. Amy will manage the release notes. Just be aware that you might be asked more questions regarding the migration during the final release. :)

**Pull request merged**
