### PR TITLE
Removed empty translation

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
For some reason there is a translation with an empty key and value

### CODE REVIEW

**Comment by metanerd** [comment]
I think someone tried to remove this one already, but the translation check script makes it fail. Can we just merge it even if it fails?

**Comment by enahum** [comment]
@jespino would you know why the check fails?

**Comment by metanerd** [comment]
```
/go/src/github.com/mattermost/mattermost-server/bin/mmgotool i18n extract --portal-dir=""
2a3,6
>     "id": "",
>     "translation": ""
>   },
>   {
```

**Comment by enahum** [comment]
There must be something in the codebase that has an empty string

**Comment by jespino** [comment]
@metanerd yes, the problem was an error that was using an empty string, now is fixed here: #15166

Should be fixed in master.

**Pull request closed without merging**
