### PR TITLE
MM-23666: rewrite TestHTTPClient

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
The existing `TestHTTPClient` actually tries to reach google.com, making it brittle to network hiccups (as unlikely as that might be). Rewrite the test to rely on a local server instead.

I found the existing implementation of `TestHTTPClient` extremely hard to understand, so I've rewritten it more explicitly, expanded coverage somewhat. In doing so, I found myself somewhat surprised by the current behaviour. If `allowHost` returns `true`, we ignore `allowIP` altogether. If `allowHost` returns `false`, we check with `allowIP`. There's a lack of symmetry here that the current filter names don't make clear. Perhaps `allowHost` should be renamed `skipIPCheckForHost`?

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-23666

### CODE REVIEW

**Comment by jupenur** [comment]
If I'm understanding this correctly, before this change the test covered a case with both an external host and a valid SSL certificate -- the `google.com` one. After this change it no longer does. Is that an acceptable compromise?

Otherwise looks great.

**Comment by lieut-data** [comment]
> We give priority to the hostname check. If that does not pass (or it's not passed in) we rely on IP addresses. That's how I read it.

@streamer45, that's a reasonable interpretation. I think I was just surprised that I could not /reject/ a host using `allowHost`, but can using `allowIP`. Superficially, the nomenclature suggests they should be parallel.

@jupenur, you're absolutely right that we're no longer testing `TestHTTPClient` against a server with a valid SSL certificate. I /think/ the compromise is ok, if not better, since we're now testing that a self-signed certificate is actually rejected or accepted based on the requested configuration. My gut says that if we were to regress and not notice, it would be this latter case, and not our ability to connected to a trusted endpoint.

Thoughts?

**Comment by jupenur** [comment]
Makes sense. FWIW, regarding `allowHost`, my interpretation was the same as @streamer45's, and I think it especially makes sense if you look at what it's used for currently: whitelisting either hosts or IPs based on a mixed list of both. Of course you shouldn't have to look at current use-cases to understand an API, but don't I think there's room for dangerously incorrect interpretations or anything like that.

**Comment by lieut-data** [comment]
@prapti, heads up that there are no changes to the product here, just expanded / modified test coverage.

**Comment by agnivade** [comment]
Would be nice to finally fix this. :+1:  This has been failing my PRs like 3 times out of 5. :(

**Pull request merged**
