### PR TITLE
Fix comment on PostAction.Options

### PR DESCRIPTION
**Pull request by ebiiim**
#### Summary

In integration actions, `PostActionOptions` is only for `POST_ACTION_TYPE_SELECT` but not `POST_ACTION_TYPE_BUTTON`.  However, the comment on PostAction.Options is now incorrect so I fixed it.

I've confirmed that another comment below imply the same (options is only for select dropdown).

https://github.com/mattermost/mattermost-server/blob/75197d291af8dd2f509c7c616a50a1ed21d114e6/model/integration_action.go#L59-L62

### CODE REVIEW

**Comment by hanzei** [comment]
@hmhealey Please take a look as you introduced this comment in https://github.com/mattermost/mattermost-server/pull/10659/

**Comment by hmhealey** [comment]
Also, thanks for fixing my typo with "dropdowon"

**Pull request merged**
