### PR TITLE
Updated NPS pluing to 1.2.0

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Bumped NPS pre-packaged plugin from 1.1.0 to 1.2.0

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42059

#### Release Note

```release-note
Updated NPS plugin to version 1.2.0
```

### CODE REVIEW

**Comment by hanzei** [comment]
Has the release been cut using Matterbuilt?

**Comment by marianunez** [comment]
> Has the release been cut using Matterbuilt?

Not yet. Waiting on permissions to be able to actually run the `/mb` command.

**Review by hanzei — COMMENTED** [review]
@marianunez Please let me know if I can help with anything related to the release

**Comment by marianunez** [comment]
@hanzei @JulienTant package was built now and this is green. Good to go for a review

**Comment by marianunez** [comment]
@hanzei do we still need to publish this to the marketplace? Not sure why we would need it there, it seems like an internal MM specific plugin

**Review by JulienTant — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by marianunez** [comment]
@stevemudie this would be just a quick smoke test that the NPS has been upgraded here to 1.2.0. which mainly includes: https://github.com/mattermost/mattermost-plugin-nps/pull/88

**Comment by marianunez** [comment]
@amyblais are we ok cherry-picking this into v6.7 release?

**Pull request merged**
