### PR TITLE
Fixed comments syntaxt in app config file

### PR DESCRIPTION
**Pull request by saneletm**
fixed syntax error in comment in config.go

### CODE REVIEW

**Comment by levb** [comment]
@saneletm thanks for catching these! Do you mind please sync&merge-ing your branch from master?

**Comment by levb** [comment]
Not sure what's going on with the failing test, can you please verify?

**Comment by saneletm** [comment]
I am getting a bit confused as to what and why some tests are failing. I will keep troubleshooting,
and consulting with the developer and contributer channels.
Does this look like the right workflow for syncing my fork and branch? 

```
 - mattermost-server git:(master) ✗ git remote add upstream https://github.com/mattermost/mattermost-server.git
 - mattermost-server git:(master) ✗ git fetch upstream
 - mattermost-server git:(master) ✗ git fetch upstream
 - mattermost-server git:(master) ✗ git pull upstream master
 - mattermost-server git:(master) ✗ git push
 - mattermost-server git:(master) ✗ git checkout mm-config-comments
 - mattermost-server git:(mm-config-comments) ✗ git pull --rebase origin master
 - mattermost-server git:(mm-config-comments) ✗ git pull
 - mattermost-server git:(mm-config-comments) ✗ git push
```

**Comment by cpoile** [comment]
@saneletm Once a PR is under review we recommend you just fetch master and then merge master into your PR branch. That will create one merge commit, and it won't cause a whole bunch of new commits that aren't yours. 

I'm not sure what the best way is to clean this up. Maybe: start a new PR with only your changes, reference this PR, close this PR, and submit the new PR.

**Comment by saneletm** [comment]
I like and I am more comfortable with suggestion from @cpoile above to start a new PR. The history here is a bit messy, and I can't tell what messing the tests.

**Pull request closed without merging**
