### PR TITLE
[MM-30292] Don't include prepackaged plugin into Marketplace response for cloud

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Some plugin don't work on cloud. The remote Marketplace is aware of this fact, but prepackaged plugins are not. Hence, on a cloud installation prepackaged plugins shouldn't be shown in the Marketplace modal.

The long term solution is to have a separate set of prepacked plugins for cloud: https://mattermost.atlassian.net/browse/MM-31331.

#### Ticket Link
Fixes 
- https://mattermost.atlassian.net/browse/MM-30292
- https://mattermost.atlassian.net/browse/MM-29147
- https://mattermost.atlassian.net/browse/MM-30080

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jwilander — APPROVED** [review]

**Review by levb — APPROVED** [review]

**Comment by levb** [comment]
Not sure who is the right QA for this, @DHaussermann ?

**Comment by DHaussermann** [comment]
@hanzei  I'm not actually sure how this could be conclusively tested before the merge. I did ping @jwilander here https://community-release.mattermost.com/core/pl/gawiw3yjcpnk5m55ck3fo8serh to see if we can make a config change on one of the servers running the release brach. This would be a conclusive way to test the change once it's merged into the cloud release brach. 

Any thoughts on how this would be testable before it's merged?

**Comment by hanzei** [comment]
@DHaussermann You need to setup a local marketplace by generating a release package using `make package` first. Then your run Mattermost from that package and provide a cloud license.

Please let me know if that helps.

**Comment by DHaussermann** [comment]
@hanzei I'd like to move this forward so we can get it in for the next cloud release. But I was unable to generate a release package. 

- Pull down this branch of mattermost-server
- run `make package`
- packaging process begins
Observed: 
```
gpg --import build/plugin-production-public-key.gpg
make: gpg: No such file or directory
make: *** [package] Error 1
```

Any thoughts on if some setup was missed?

**Comment by hanzei** [comment]
@DHaussermann To fix your build issue you need to install `gpp`.

Alternately, you can run `make prepackaged-plugins` to only download all prepacked plugins.

**Comment by hanzei** [comment]
@DHaussermann You need to install `gpg` using e.g. https://gpgtools.org/

**Comment by DHaussermann** [comment]
@hanzei When trying to test this I have the marketplace URL `https://api.integrations.mattermost.com` and I'm seeing that I can't connect to the Marketplace. However I think something setup related may be occurring because this is the behavior I see even when adding an E20 licence is applied.
Screen Shot 2021-01-27 at 12 48 18 AM

I did the following...
- Switched to this branch of server
- Used `make package` to build a Mac OS tar.gz package
- Unpacked the package and confirmed pre-packaged plugins are present
- Started a Mattermost DB in docker
- Ran the Mattermost binary form inside the `bin` folder in the package.
- Login to the MM server and open Marketplace
**Observed**: No plugins are available

Do you have any suggestions to try and isolate this?

**Comment by hanzei** [comment]
@DHaussermann Could you please double check `PluginSettings.Enable` is set to `true` and restart your MM server?

**Comment by DHaussermann** [comment]
Yes @hanzei I have tried this. Including trying again after building a new release after this last merge.
Both the cofig file, and the UI say plugins are enabled and the server has been restarted. 

One more detail that may help is the network error that occurs when laughing the marketplace.
Screen Shot 2021-01-28 at 9 00 28 PM

**Comment by hanzei** [comment]
@DHaussermann Could you please DM me the full server logs from the point on the Mattermost Server starts?

**Comment by DHaussermann** [comment]
@hanzei I tested this commit on other server and it was apparent to me that this issue was related to deployment somehow and no your code change. Let's leave this aside. @saturninoabril was able to suggest an alternative to running the manually compile binary by using Docker instead.   

Steps:
- Created fresh database container with docker
- Used Docker to create a webapp using this commit hash
- Supplied a default `config.json` to the web app

This creates a deployment where the license type can be changed at will and all prepackaged plugins are included as expected.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- When Cloud license is applied, Antivirus and Welcome Bot are not shown
- Antivirus and Welcome Bot are shown normally with E20 or E10 license
- Antivirus and Welcome Bot are not shown as expected when no license is applied
- No change to showing to the other pre-packaged plugins when Cloud license is applied

LGTM!
Huge thanks to @hanzei and @saturninoabril  for the help with testing setup on this one 🎉

**Pull request merged**
