### PR TITLE
Refactor bot store to use squirrel

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This pull request refactors the bot store to use squirrel queries instead of raw SQL queries. It creates as well the `botsQuery` field for the store as a starting point for the bot queries.

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@mgdelacroix is there testing needed for this one from QA, and/or unit / e2e tests?

**Comment by mgdelacroix** [comment]
@lindalumitchell apologies for the delay. The changes should be covered by unit tests, but to be sure they work the best approach would be to run some smoke tests around the entity of the store, bots in this case, creating and listing them

**Comment by lindalumitchell** [comment]
Thanks @migbot! I started some smoke testing around bots, but unfortunately it looks like there may be a separate issue on master (and release branch) with saving edits to bot username and display name, so I can't complete smoke tests for this PR yet. Filed https://mattermost.atlassian.net/browse/MM-25595 for the issue.

**Comment by cpanato** [comment]
terminating this test server because we need to clean the cluster that is running. If you still need a test server please add the label again in the future

**Comment by hanzei** [comment]
@mgdelacroix Is this PR ready to get merged?

**Comment by isacikgoz** [comment]
Hi @mgdelacroix, Note that we [merged multiple repositories into one monorepo](https://github.com/mattermost/mattermost-server/issues/22420) which may require you to resubmit these changes. I'm closing in the favor of reducing load on mattermod. Also the CI checks should run on our new pipelines. You can update the branch and re-open if you feel necessary.

**Pull request closed without merging**
