### PR TITLE
 chore project: Add to travis-ci.com

### PR DESCRIPTION
**Pull request by Apollo9999**
chore project: Add to travis-ci.com  with provided link https://docs.travis-ci.com/

### CODE REVIEW

**Comment by hanzei** [comment]
@Apollo9999 Could you please elaborate your changes a bit? What ticket are you trying to resolve?

**Comment by Apollo9999** [comment]
Sir,my intention to raise the PR is to integrate BPMN workflow for Mattermost

**Comment by jfrerich** [comment]
> Sir,my intention to raise the PR is to integrate BPMN workflow for Mattermost

Hi, @Apollo9999.  I'm not sure that I understand the request or intention of the PR, as it is currently designed. Adding a file named `chore project: Add to travis-ci.com` to the top-level `mattermost-server` repo does not seem plausible. 

Can you clarify with a more detailed description of the purpose of the PR?

**Comment by isacikgoz** [comment]
Hey @Apollo9999 Could you please answer the questions asked if you are planning to work on this? If not, I'm inclined to close this PR.

**Comment by Apollo9999** [comment]
@isacikgoz Sir Look in to this code and make necessary incorporations incase of requirement

**Comment by Apollo9999** [comment]
@isacikgoz Sir Look in to this code and make necessary incorporations incase of requirement

[travis-ci.zip](https://github.com/mattermost/mattermost-server/files/6130571/travis-ci.zip)

**Comment by isacikgoz** [comment]
Thanks for your interest @Apollo9999! Unfortunately, the requested change doesn't seem to be acceptable. Closing this PR.

**Pull request closed without merging**
