### PR TITLE
[GH-13074] Migrate TermsOfServiceCache from store/sqlstore/terms_of_service.go to the new store/localcachelayer

### PR DESCRIPTION
**Pull request by saneletm**
#### Ticket Link
 https://mattermost.atlassian.net/browse/MM-20095

### CODE REVIEW

**Comment by saneletm** [comment]
I suspect something went wrong again on my rebase from master. I might want to move this PR to a fresh branch. I am still verifying

**Comment by lindy65** [comment]
Hi @saneletm - once you've sorted out the rebase from master, please let me know so I can go ahead and QA :) Thanks!

**Comment by saneletm** [comment]
> Hi @saneletm - once you've sorted out the rebase from master, please let me know so I can go ahead and QA :) Thanks!

I have tried to clean up. the history on this branch doesn't look particularly good. I also see changes that are not mine, and I am a not sure if I inadvertently reverted some important commits.  If those `config` and `port` changes are really wrong, I think I would just move my changes into a new fresh branch. Please advise

**Comment by lindy65** [comment]
Thanks for the feedback @saneletm 👍 I'll defer to @jespino for guidance on whether you should move to a fresh branch...

**Comment by saneletm** [comment]
I would like to move this PR to this cleaner one: https://github.com/mattermost/mattermost-server/pull/13205

I hope I get a handle on these merges quickly

**Pull request closed without merging**
