### PR TITLE
MM-45871: Do not try to extract content from images

### PR DESCRIPTION
**Pull request by agnivade**
This creates faulty requests to Bifrost and results in
errors and warnings in the logs. Even without Bifrost,
this would make unnecessary requests to S3.

We only extract info from documents and therefore we can
safely avoid this.

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
Gentle ping @jespino

**Review by jespino — APPROVED** [review]
LGTM

**Review by saturninoabril — APPROVED** [review]
Thanks @agnivade! All good with E2E. LGTM.

I wonder what's with https://github.com/mattermost/mattermost-server/blob/9014849b35871e7df4a91505fb663a6922d6dd9d/app/upload.go#L327 and why it's not having the same implementation.

**Comment by agnivade** [comment]
You are right. Let me update the code.

**Pull request merged**
