### PR TITLE
Migrate GetDeletedByName from ChannelStore to return error interface

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

This PR migrates `GetDeletedByName` method.

Fixes https://github.com/mattermost/mattermost-server/issues/14717

### CODE REVIEW

**Comment by rvillablanca** [comment]
@agnivade Hi, we need a ticket for this :)

**Comment by teresa-novoa** [comment]
Thanks @rvillablanca, same as the other PR, Agniva self-assigned this, so he will be reviewing it shortly, best!

**Comment by agnivade** [comment]
Hi @teresa-novoa - Me and Rodrigo are in touch. We are waiting for the first set of PRs to be merged before looking at more. Rest assured, these PRs are not forgotten. :)

**Comment by rvillablanca** [comment]
Ok I'll fix it right now, just a couple of minutes

**Comment by rvillablanca** [comment]
Done @agnivade :+1: Good suggestion

**Comment by agnivade** [comment]
@srkgupta - Running a slack import and verifying there are no issues should be good enough.

**Comment by rvillablanca** [comment]
Conflicts resolved

**Comment by srkgupta** [comment]
Hi @rvillablanca 
Apologies for the delay in picking this story up for testing. I am ready to pick this up for testing now. Can you please resolve the merge conflicts. 
Thanks.

**Comment by rvillablanca** [comment]
Hi @srkgupta no problem :)
Conflicts were resolved!

**Comment by srkgupta** [comment]
> Hi @srkgupta no problem :)
> Conflicts were resolved!

Awesome. Thanks.

**Comment by rvillablanca** [comment]
Great, thanks @srkgupta. So we can move this into master @agnivade :)

**Pull request merged**
