### PR TITLE
[MM-33538] Trims space from user email when sanitizing user input

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
Trims space from user email when sanitizing user input

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33538

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Review by jespino — APPROVED** [review]
LGTM. Anyway, maybe this should be a "validation" process, also would be great to have a confirmation that a pre-existing "space-started/space-ended" emails keep working (I guess is not something that we want to support).

**Review by srkgupta — APPROVED** [review]
Thanks @mgdelacroix. The changes LGTM

**Pull request merged**
