### PR TITLE
Avoid counting top channel posts for posts made by plugins and OAuth apps

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

At the moment, posts made by integrations such as plugins and OAuth apps are being counted in the insights for finding the top channels and post counts. This PR makes use of the `from_plugin` and `from_oauth_app` props added here https://github.com/mattermost/mattermost-server/pull/20912 to filter these type of posts out of the query results.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45908
https://mattermost.atlassian.net/browse/MM-45734
https://mattermost.atlassian.net/browse/MM-41270

#### Release Note
```release-note
Insights feature now filters out posts made by plugins and OAuth apps
```

### CODE REVIEW

**Comment by mickmister** [comment]
@ashishbhate this PR and https://github.com/mattermost/mattermost-server/pull/20912 are currently blocking some functionality that we had to disable on community. Can you please take a look when you have the chance?

**Comment by ashishbhate** [comment]
@vish9812 and @Willyfrog 

Do we need to incorporate the changes made here and in [#20912](https://github.com/mattermost/mattermost-server/pull/20912) for post counting for cloud limits? 

I don't think so, but I thought I'd ask just in case. My understanding is that posts from plugins and OAuth apps should count towards the post limit.

**Review by ashishbhate — APPROVED** [review]

**Review by mkraft — APPROVED** [review]
Thanks for adding this. It's begging for a refactor to make this less error prone to typos; a function that accepts a slice of strings. Suite Users can do it in a separate PR though.

**Comment by vish9812** [comment]
> My understanding is that posts from plugins and OAuth apps should count towards the post limit.

Considering plugins themselves are part of the limit. So should be their posts.

**Comment by mickmister** [comment]
@mkraft: @DHaussermann is testing https://github.com/mattermost/mattermost-server/pull/20912 and can probably test this PR, though we may need some direction on how to test the Insights feature

**Comment by Willyfrog** [comment]
> I don't think so, but I thought I'd ask just in case. My understanding is that posts from plugins and OAuth apps should count towards the post limit.

That's what we agreed, yes. It would be cumbersome to check the limits otherwise.

**Comment by mkraft** [comment]
@furqanmlk Would you be able to support @DHaussermann if he has any questions?

**Comment by furqanmlk** [comment]
> @furqanmlk Would you be able to support @DHaussermann if he has any questions?

@mkraft Yes absolutely

**Comment by DHaussermann** [comment]
@furqanmlk I have setup a Zapier integration on the server above ☝️.

How do I turn on the Insights feature?

**Comment by furqanmlk** [comment]
> @furqanmlk I have setup a Zapier integration on the server above ☝️.
> 
> How do I turn on the Insights feature?

@DHaussermann 
We need to have License in order to see `Insights` features 
I have add the license, Insights is working now
https://mattermost-server-pr-20943.test.mattermost.cloud/pr20943/activity-and-insights

**Comment by DHaussermann** [comment]
Tested and passed
- Tested with Zapier posts
- Tested with bot post 
- Isights is only counting the posts by non bot users as expected

LGTM! 


@furqanmlk I have tested the issue as described and it is resolved. Can you please advise if any additional testing is needed for regression testing Insights?

**Comment by furqanmlk** [comment]
> https://mattermost-server-pr-20943.test.mattermost.cloud/pr20943/activity-and-insights

Hi @DHaussermann 
All look good

**Pull request merged**
