### PR TITLE
[MM-47367] Make sure mini preview is saved to database when updating database

### PR DESCRIPTION
**Pull request by RobBie1221**
#### Summary

Fixes [MM-47367].
When there is no minipreview in the database for an image (data is [null], which occurs for example for imported images), the minipreview is generated after opening it in a channel. The minipreview is however not stored in the database, because it is not included in the query built in `Upsert`. As a result, minipreviews are generated everytime these images are loaded. 

This PR adds the minipreview data to the query in `Upsert`.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47367

#### Release Note

```release-note
Fixed saving of minipreview data while saving an update for an image in the database.
```

[MM-47367]: https://mattermost.atlassian.net/browse/MM-47367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Thanks @RobBie1221 ! Would you mind adding a unit test for this? The tests are in store/storetest/file_info_store.go.

**Comment by RobBie1221** [comment]
I was afraid you might ask that ;)
I’ll give it a try.

**Comment by RobBie1221** [comment]
@agnivade Could you help me out a bit with running tests?
I tried `go test -v ./store/storetest`, but this does not seem to run tests in store/storetest/file_info_store.go.

```
=== RUN    TestNewTestId
--- PASS:  TestNewTestId (0.00s)
PASS
ok      github.com/mattermost/mattermost-server/v6/store/storetest      (cached)
```

If I try to address the file specifically (`go test -v -run='TestFileInfoStore' ./store/storetest`) I get:

```
testing: warning: no tests to run
PASS
ok      github.com/mattermost/mattermost-server/v6/store/storetest      (cached) [no tests to run]
```

**Comment by agnivade** [comment]
You have to pass the directory as `store/sqlstore`: `go test -v -run=<testname> ./store/sqlstore`.

**Comment by RobBie1221** [comment]
Added a unit test

**Review by agnivade — APPROVED** [review]
Thanks!

**Review by noxer — APPROVED** [review]
Awesome, thank you very much!

**Pull request merged**
