### PR TITLE
[MM-24461] Show last active time of users when not online

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
New config for globally controlling last active label

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24461

#### Related PRs
https://github.com/mattermost/mattermost-webapp/pull/8889

#### Release Note

```release-note
Show when a user was last online
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Comment by BenCookie95** [comment]
> @BenCookie95 thanks for getting back to this! Are we good to merge this server PR?

I was updating this last week because I wanted to run through the accuracy of the last active time before merging. We noticed last month when looking at another feature that the last active time only really updates on page refresh so if you are using the desktop app your last active time might be very inaccurate. I want to test with the desktop and ensure that isn't the case

**Comment by esethna** [comment]
@BenCookie95 just checking in, any updates on the above? ^

**Comment by BenCookie95** [comment]
@esethna Last update was this https://github.com/mattermost/mattermost-webapp/pull/8889#issuecomment-1065544179. Last piece is finding the cause of this memory leak

**Pull request merged**
