### PR TITLE
MM-18060: Include deleted posts in compliance export.

### PR DESCRIPTION
**Pull request by catalintomai**
**Summary**

Include deleted posts in compliance export. (preliminary work for MM-18060, MM-18446,MM-18059)

**Ticket**

https://mattermost.atlassian.net/browse/MM-18060

### CODE REVIEW

**Comment by srkgupta** [comment]
Thanks @catalintomai, I tested with the both the repo changes and now the deleted file shows up correctly in the exported file as expected. However just one small observation:

The Post type column for an attachment is correctly shown as ```deleted attachment```. However the Post type column for the message which was removed is still shown as ```message``` instead of ```deleted message```. Can you please check this ?

**Comment by catalintomai** [comment]
> Thanks @catalintomai, I tested with the both the repo changes and now the deleted file shows up correctly in the exported file as expected. However just one small observation:
> 
> The Post type column for an attachment is correctly shown as `deleted attachment`. However the Post type column for the message which was removed is still shown as `message` instead of `deleted message`. Can you please check this ?
> 
> Please check this screenshot, the Post ID are same for both these rows. However the first row shows as `message` instead of `deleted message`.
> Screenshot 2019-10-29 at 10 21 36 PM

***
This ticket only tackles the file delete events (similar to [MM-15925]  and [MM-18059]). For your ask, we would prob need to open a separate ticket(similar to [MM-18446]). Thanks.

**Comment by catalintomai** [comment]
> I'm a little confused... I tested this on October 3rd (and again today without this change) and it seems to me that deleted posts are already included. I wonder if my test is broken?
> 
> Steps:
> 
> 1. Create a post.
> 2. Delete the post.
> 3. Run export and observe message is included in the Actiance XML export.

Try the following steps:
1. Create the post + add an attachment
2. Run export and observe message is included in the Actianc/CSV export.
3. Delete attachment
4. Run export and check if message is included in the Actiance/CSV export. (in my tests is it not)

The change also gives us the post deletion time (see dependent PR MM-18446).

**Comment by mkraft** [comment]
> > I'm a little confused... I tested this on October 3rd (and again today without this change) and it seems to me that deleted posts are already included. I wonder if my test is broken?
> > Steps:
> > 
> > 1. Create a post.
> > 2. Delete the post.
> > 3. Run export and observe message is included in the Actiance XML export.
> 
> Try the following steps:
> 
> 1. Create post + add a file attachment
> 2. Run export and observe message is included in the Actianc/CSV export.
> 3. Delete post
> 4. Run export and check if message is included in the Actiance/CSV export. (in my tests is it not)
> 
> The change also gives us the post deletion time (see dependent PR MM-18446).

I see. Prior to the changes in https://github.com/mattermost/enterprise/pull/519 this change would have just re-exported a necessarily already-exported post without any additional information, but this change makes sense to me now that I see it associated to the other PR.

**Pull request merged**
