### PR TITLE
MM-33913: Fix read-after-write issues with team member

### PR DESCRIPTION
**Pull request by agnivade**
During LDAP sync, we would call AddTeamMember which had a read-after-write issue
where we would create a team member but then immediately after that
query the team member.

The same pattern was found in:
AddTeamMember
AddTeamMembers
AddTeamMemberByToken

To fix this, we just return the inserted team member from AddUserToTeam and use that
instead of query GetTeamMember again.

```release-note
NONE
```

https://mattermost.atlassian.net/browse/MM-33913

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by agnivade** [comment]
ping @mkraft

**Review by mkraft — APPROVED** [review]
Nice, this is great @agnivade

**Comment by agnivade** [comment]
ping @furqanmlk

**Review by furqanmlk — APPROVED** [review]
1. LDAP sync - verify that team members get added properly ✅ 
2. Add team member - verify ✅ 
3. Add user to a team by token_id - verify ✅ 
4. Add user to a team by invite_id - verify ✅

**Pull request merged**
