### PR TITLE
[MM-37664] Remove deprecated Backend field from plugin manifest

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The `Backend` field in the plugin manifest has been deprecated for 3 years now. While this change _does_ break existing plugins, I couldn't find a single one that (still) uses it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37664

#### Release Note
```release-note
Remove deprecated Backend field from plugin manifest
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
:+1:

**Comment by DHaussermann** [comment]
@hanzei can you think f any functional testing applicable here?

**Review by DHaussermann — APPROVED** [review]
Tested and passe
- Spot checked various plugins
- Installed and enabled plugins
- Briefly tested using various plugins from the user side
- No unexpected error in the logs
- No functional issues found

LGTM!

**Pull request merged**
