### PR TITLE
Bump pre-packaged version of Zoom to v1.6.0

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Bump pre-packaged version of Zoom to v1.6.0

#### Ticket Link
--

#### Release Note
```release-note
Updated pre-packaged Zoom plugin version to v1.6.0
```

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by agarciamontoro** [comment]
@DHaussermann, would you have some spare cycles to take a look at this?

**Review by lieut-data — APPROVED** [review]

**Comment by amyblais** [comment]
@mickmister @DHaussermann A kind note that v7.0 code freeze is this week Wednesday.

**Review by saturninoabril — APPROVED** [review]
Thanks @agarciamontoro! LGTM, will test after merge.

**Comment by agarciamontoro** [comment]
Whoops, @mickmister had approved and I re-requested his review, sorry for that.

**Pull request merged**
