### PR TITLE
MM-30338 Add feature flag for collapsedthreads

### PR DESCRIPTION
**Pull request by reflog**
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30338
#### Release Note

```release-note
Added CollapsedThreads feature flag
```
#### Feature Flags
This PR includes a new feature flag:
`CollapsedThreads bool` - possible values `true`, `false`.

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by crspeller — APPROVED** [review]

**Comment by cwarnermm** [comment]
@amyblais - Are there any outstanding feature flag docs needed for this PR?

**Comment by amyblais** [comment]
@cwarnermm I believe not, I'll change the label!

**Pull request merged**
