### PR TITLE
[MM-41611] Only check for userId when saving userTermsOfService

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
When storing userTermsOfService (the acceptance to the terms of service by a user), we usually update the value if exist to note the latest terms of service (by the terms of service id) and the create at.

https://github.com/mattermost/mattermost-server/commit/47de1f37e651f593fb500b72ee231871fb2a3842 introduced a regression by checking for both userId and termsofserviceId. This is fixed by removing the check on terms of serviceId.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41611

#### Release Note
```release-note
Fix bug when disabling and re-enabling Custom Terms of Service.
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Ooh nasty one indeed. Can we have a unit test please? :)

**Review by agnivade — APPROVED** [review]
Fantastic!

**Review by isacikgoz — APPROVED** [review]
Nice one 👍

**Comment by jgilliam17** [comment]
Thanks @larkox 
Tested, looks, [waiting for E2E report ](https://automation-dashboard.vercel.app/cycles/394da138-4e46-4454-9a34-05001de42e90)before approving.
- Verified acceptance of custom terms of service - as expected.

**Comment by jgilliam17** [comment]
[E2E report](https://automation-dashboard.vercel.app/cycles/394da138-4e46-4454-9a34-05001de42e90) looks good, no PR related failures.
@larkox unable to merge, please check failed checks - thanks 🙂

**Review by jgilliam17 — APPROVED** [review]

**Comment by larkox** [comment]
@amyblais This is merged, in case you want to cherrypick to any dot release.

**Pull request merged**
