### PR TITLE
MM-38634: Simplify image proxy

### PR DESCRIPTION
**Pull request by agnivade**
We copy over the necessary code to simplify
the local image proxy feature.

https://mattermost.atlassian.net/browse/MM-38634

```release-note
NONE
```

### CODE REVIEW

**Review by jupenur — APPROVED** [review]
This is so great, *thousands* of unused LOC gone! Amazing work Agniva!

**Comment by agnivade** [comment]
:tada: 
feels_good

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
> 🎉 feels_good

As a primarily JS developer these days, I'm conditioned to ignore lines of code coming from dependencies, so I don't think that counts 😛

**Comment by jgilliam17** [comment]
Thanks @agnivade 
This test failed MM-T1535
See full report [here](https://mattermost-cypress-report.s3.amazonaws.com/154381-74b2fb1-onprem-ent-server-pr-19603-mattermost/mm-ee-test74b2fb1/mochawesome.html)
This does not appear to be related to your changes, but it differs from [master report ](https://mattermost-cypress-report.s3.amazonaws.com/154101-onprem-ent-master-mm-ee-test:test/mochawesome.html)

**Comment by jgilliam17** [comment]
Also seeing one issue when manually testing.
Sharing a link to post with an image, removes that image from the channel

https://user-images.githubusercontent.com/52937121/155229135-501a076c-6d70-4ba5-b8f8-9c2ae113e707.mov

**Comment by agnivade** [comment]
@jgilliam17 - Thanks, I just checked and confirmed that same happens on master as well. Does it not reproduce on master for you?

**Comment by jgilliam17** [comment]
Thanks for checking @agnivade Yes, it repros for me too on daily. I'll file that separately. 
This PR is good to merge.

**Pull request merged**
