### PR TITLE
fixed compose makefile

### PR DESCRIPTION
**Pull request by HandsomeChoco**
#### Summary

improved compatibility for Apple silicon devices
#### Release Note

```release-note
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
Thanks for the contribution @HandsomeChoco 🎉  Could you elaborate how this change help with running the app on a Apple silicon device?

**Comment by HandsomeChoco** [comment]
> Thanks for the contribution @HandsomeChoco 🎉 Could you elaborate how this change help with running the app on a Apple silicon device?

Hello, as I know when we want to run development environment, 
we can run it with just a one line command "make run" on mattermost-server repository.

it was unavailable for arm Mac, because there's no mysql docker image for ARM, 
that source code is for  explicitly download mysql image for x86 architecture.

then, ARM Mac also available to run Mattermost development environment.

Also I don't think this code will affect to people who develop Mattermost on windows. 
because they will have to use WSL.

thank you

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by agnivade** [comment]
There's already this PR https://github.com/mattermost/mattermost-server/pull/17057 which does this.

**Comment by isacikgoz** [comment]
Thanks for pointing that one out @agnivade. That one escaped from me. In this case, @HandsomeChoco would you mind if we close this one and continue to work on with the branch that @agnivade mentioned?

**Comment by HandsomeChoco** [comment]
@isacikgoz Yes, sure!

**Pull request closed without merging**
