### PR TITLE
Update MM version/sqlstore to version 6.0.0

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Update MM version/sqlstore to version 6.0.0

#### Ticket Link
ref: https://community.mattermost.com/core/pl/hrq9g5m6y7d75gftaxyp7iiu3y
#### Release Note

```release-note
Update MM version/sqlstore to version 6.0.0
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]

**Review by agnivade — COMMENTED** [review]
Shouldn't we uncomment the `// if shouldPerformUpgrade(sqlStore, Version5380, Version600) {` line? Or is that to be done later?

**Comment by streamer45** [comment]
> Shouldn't we uncomment the `// if shouldPerformUpgrade(sqlStore, Version5380, Version600) {` line? Or is that to be done later?

I believe we tend to do that later in the process when we actually prepare the release.

**Comment by cpanato** [comment]
> > Shouldn't we uncomment the `// if shouldPerformUpgrade(sqlStore, Version5380, Version600) {` line? Or is that to be done later?
> 
> I believe we tend to do that later in the process when we actually prepare the release.

I depends on the release Manager and also if that will work fine with the other "communities.mattermost"

**Review by agnivade — APPROVED** [review]

**Comment by amyblais** [comment]
@cpanato / @metanerd This needs a manual cherrypick to ``cloud``. Would you have time to do that today?

**Comment by metanerd** [comment]
Done: https://github.com/mattermost/mattermost-server/commits/cloud
There are tests failing on the cloud branch currently. @amyblais . 0/5 if this gets actively checked.

**Pull request merged**
