### PR TITLE
[MM-22343] Add set_online option for creating a post to client4.go

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
This PR proposes to reflect the recent changes (https://github.com/mattermost/mattermost-server/pull/13538) made in the `CreatePost` method of the API. We can now set user status to offline while creating a post.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22343

### CODE REVIEW

**Comment by agnivade** [comment]
This is pretty much a breaking change, and we can't do this until v6 happens. Instead of adding a new method which will bloat the API, I would suggest to wait for v6 and then submit this.

**Comment by agnivade** [comment]
Gave some thought to it, I think it can be fixed from mmctl itself. We just need to construct the raw URL ourselves, and maybe construct a helper function around this.

```go
url := c.GetPostsRoute() + "?set_online=false"
r, err := c.DoApiPost(url, post.ToUnsanitizedJson())
if err != nil {
	return nil, BuildErrorResponse(r, err)
}
```

That's all you need basically. And then when v6 comes, add the new param and use the new method directly.

I think this is a decent compromise to maintain semver promise.

**Comment by mgdelacroix** [comment]
@agnivade I agree on it being a compromise, but bear in mind that we should create the same check in server to be able to test this type of changes in the API at the same time we deliver a feature, so although it might be something to use now, I think we should aim for a sustainable solution (maybe creating a `mattermost-go-driver` repo?) for v6

**Comment by isacikgoz** [comment]
Closing this PR and solving this issue through https://github.com/mattermost/mmctl/pull/143

**Pull request closed without merging**
