### PR TITLE
Bumped Autolink plugin version to 1.1.1

### PR DESCRIPTION
**Pull request by levb**
#### Summary
Bump the autolink plugin version to 1.1.1

- Awaiting https://github.com/mattermost/mattermost-plugin-autolink/pull/77

### CODE REVIEW

**Comment by DHaussermann** [comment]
@levb the server above gets created without any version of the AutoLink plugin installed. If you feel this might be caused by https://mattermost.atlassian.net/browse/MM-19042 (as was the case for other plugins), we can merge this to master where the issue is resolved to be tested again and create a follow-up task if needed.

Please advise if you think there may be separate issue to address. I see no issues with the code change on this task.

**Comment by levb** [comment]
Let me pull in the master changes here and re-test? This is not a critical PR for RC1.

**Comment by levb** [comment]
@DHaussermann try again once it's built, please?

**Pull request merged**
