### PR TITLE
Remove Custom statuses feature flag

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Remove Custom statuses feature flag

#### Ticket Link
[MM-33166](https://mattermost.atlassian.net/browse/MM-33166)

#### Release Note
```release-note
Add user custom statuses
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by reflog — APPROVED** [review]

**Comment by reflog** [comment]
sorry @jespino @esethna I pressed merge by mistake 😢

**Comment by jespino** [comment]
@amyblais this needs to get cherry-picked?

**Comment by jespino** [comment]
@reflog Don't worry, I think is not a big deal, because the changes are pretty straight forward, so... I don't see much risk there.

**Comment by amyblais** [comment]
@jespino Seems to need manual cherry picks to v5.33 and cloud.

**Comment by amyblais** [comment]
Need to discuss first before cherry-picking.

**Pull request merged**
