### PR TITLE
MM-42813: Fallback to default config if nil is passed

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-42813

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@saturninoabril - I tested the failing cypress tests and they are passing now.

**Review by isacikgoz — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks @agnivade! I'd recommend to cherry-pick this into cloud cc @amyblais

**Pull request merged**
