### PR TITLE
MM-46528_Verify Invitation Flow Tracking Telemetry

### PR DESCRIPTION
**Pull request by julmondragon**
#### Summary
We want to track the number of invited users by admins and by end users, as well as the success rate of invitations for each.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46528

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by salmanmanekia** [comment]
LGTM!

**Review by pvev — APPROVED** [review]
LGTM! Nice work @julmondragon, :shipit:

**Comment by julmondragon** [comment]
> @julmondragon gentle ping on this - anything that is blocking this and [mattermost/mattermost-webapp#11286](https://github.com/mattermost/mattermost-webapp/pull/11286)?

Only waiting on @dontoisme @sri-byte 's feedback from testing on test server in https://github.com/mattermost/mattermost-webapp/pull/11286

**Comment by cwarnermm** [comment]
@julmondragon @dontoisme - Is there Telemetry documentation impact for this PR, or is this a change we're making that doesn't need to be communicated externally?

**Comment by cwarnermm** [comment]
Friendly follow-up on this, @dontoisme. Is there telemetry documentation updates we'd like to see made associated with this change? My read of this is that telemetry updates aren't needed.

**Comment by dontoisme** [comment]
@cwarnermm apologies for the delay here. We need to do an update here for telemetry docs.

**Pull request merged**
