### PR TITLE
MM-29287 : Do not stop on first error when validating an import file.

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary

This PR aims to solve #16305 

#### Ticket Link

Fixes: #16305 
JIRA: https://mattermost.atlassian.net/browse/MM-29287

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@haardikdharma10 - I don't think this is the right approach for the fix. The code change that's needed is inside `func (a *App) bulkImport` method. You will see that we are spawning some workers and then returning from the method whenever we see any error which is not `api.file.upload_file.large_image.app_error`. We would need to modify the code there to ignore all errors if `dryRun` is set to true.

Additionally, a unit test to verify the functionality would also be great.

**Comment by haardikdharma10** [comment]
@agnivade, Got your point, Let me know if I am right this time. Adding something like this:

```
if dryRun == true {
	return model.NewAppError("BulkImport", "app.import.bulk_import.WHATSHOULDBEHERE?", nil, err.Error(), http.StatusBadRequest), lineNumber)
}
```
[here](https://github.com/mattermost/mattermost-server/blob/master/app/import.go#L142) should do the job :)

**Comment by agnivade** [comment]
That will just return from the method if dryRun is set to true. That's not what we want. Our objective is to not exit from the method the moment we encounter an error.

This is what the code does now:
- Takes the file reader
- Spawns some workers to consume each line
- Then listens for any errors on the `errorsChan`.
- The moment it gets a fatal error, it returns.

This is where we need to change the code - to not return if dryRun is set to true.

**Comment by jfrerich** [comment]
Hi @haardikdharma10. Do you need any further clarification or assistance from the reviewers?

**Comment by haardikdharma10** [comment]
Sorry for the delay on this @jfrerich! 
@agnivade, please let me know what you think on the above commits.

**Comment by agnivade** [comment]
Looking much better now! We need to work a bit on improving the code. I'd suggest to first assign the `model.NewAppError` to a new variable. And then if it's not dryRun, then return it, else do an `mlog.Warn` of the error. We also need to do the check in `stopOnError`.

**Comment by haardikdharma10** [comment]
> Looking much better now! We need to work a bit on improving the code. I'd suggest to first assign the `model.NewAppError` to a new variable. And then if it's not dryRun, then return it, else do an `mlog.Warn` of the error. We also need to do the check in `stopOnError`.

@agnivade, `dryRun` is local to the `bulkImport` function, how can I check for it in `stopOnError` 🤔 
Also, I think assigning `model.NewAppError` to a new variable is not something we should do (not done in any other files), the code just looks prettier this way. I don't know if I am right, so I'll wait for your response:)

**Comment by agnivade** [comment]
> dryRun is local to the bulkImport function, how can I check for it in stopOnError

I believe we can just do `if !dryRun && stopOnError(err) {` and log the error in an else condition.

> Also, I think assigning model.NewAppError to a new variable is not something we should do (not done in any other files), the code just looks prettier this way. I don't know if I am right, so I'll wait for your response:)

I am fine with the current way, but my concern was that the error logged and the error returned become different. And we are duplicating error strings when the AppError already contains all the info we want. I was looking to keep it uniform. A user might notice an error when actually importing a file, and then decide to dry run it again to see if there are any other errors. It might be a bit surprising to see the tool print a different error during dry run.

Thoughts?

**Comment by haardikdharma10** [comment]
> I am fine with the current way, but my concern was that the error logged and the error returned become different. And we are duplicating error strings when the AppError already contains all the info we want. I was looking to keep it uniform. A user might notice an error when actually importing a file, and then decide to dry run it again to see if there are any other errors. It might be a bit surprising to see the tool print a different error during dry run.
> 
> Thoughts?

Completely agree with you. One last silly question here, how do i go about assigning `model.newAppError` to a new variable (say e)? 😅

**Comment by agnivade** [comment]
The errors were being declared outside the if condition. There was no need to do that.

```diff
diff --git a/app/import.go b/app/import.go
index a39ca327c..a8856377e 100644
--- a/app/import.go
+++ b/app/import.go
@@ -129,7 +129,6 @@ func (a *App) bulkImport(fileReader io.Reader, dryRun bool, workers int, importP
        scanner := bufio.NewScanner(fileReader)
        buf := make([]byte, 0, 64*1024)
        scanner.Buffer(buf, maxScanTokenSize)
-       appErr := model.NewAppError("BulkImport", "app.import.bulk_import.json_decode.error", nil, "", http.StatusBadRequest)
 
        lineNumber := 0
 
@@ -147,6 +146,7 @@ func (a *App) bulkImport(fileReader io.Reader, dryRun bool, workers int, importP
 
                var line LineImportData
                if err := decoder.Decode(&line); err != nil {
+                       appErr := model.NewAppError("BulkImport", "app.import.bulk_import.json_decode.error", nil, "", http.StatusBadRequest)
                        if dryRun {
                                mlog.Warn(appErr.Where, mlog.Err(appErr))
                        } else {
@@ -233,8 +233,8 @@ func (a *App) bulkImport(fileReader io.Reader, dryRun bool, workers int, importP
                        mlog.Warn("Large image import error", mlog.Err(err.Error))
                }
        }
-       appErr = model.NewAppError("BulkImport", "app.import.bulk_import.file_scan.error", nil, appErr.Error(), http.StatusInternalServerError)
        if err := scanner.Err(); err != nil {
+               appErr := model.NewAppError("BulkImport", "app.import.bulk_import.file_scan.error", nil, err.Error(), http.StatusInternalServerError)
                if dryRun {
                        mlog.Warn(appErr.Where, mlog.Err(appErr))
                } else {
```

Try this.

**Comment by haardikdharma10** [comment]
@agnivade, can you help me on why the tests are failing here?

**Comment by emilyacook** [comment]
> @agnivade, can you help me on why the tests are failing here?

Hey @agnivade would you mind taking a look at this? :)

**Comment by agnivade** [comment]
Hey @haardikdharma10 - let me know if you are unable to reproduce the test failures locally.

**Comment by isacikgoz** [comment]
Hey @haardikdharma10 do you still plan to continue working on this? Let us know if you need any help.

**Comment by agnivade** [comment]
I had a chat with Haardik some time back. Let's open this up to others.

**Pull request closed without merging**
