### PR TITLE
Revert PLT-7809

### PR DESCRIPTION
**Pull request by jasonblais**
Based on feedback from leads.

See original PR here: https://github.com/mattermost/mattermost-server/pull/7590

### CODE REVIEW

**Comment by crspeller** [comment]
@jasonblais What's the reasoning for the revert? I can't find any discussion on this.

**Comment by jasonblais** [comment]
@crspeller The discussion happened privately, but in summary, the proposal from leads is to add support for Kopano integration via a plugin rather than hard-coding it. We'll do the same for Janus integration later.

Should have included in PR description. Let me know if you have further questions.

**Comment by jasonblais** [comment]
Have also discussed with Kopano members and they'll look at the plugin framework next for Kopano WebRTC.

**Comment by jasonblais** [comment]
Kopano is already starting to look into migrating the system to a plugin, so we don't need to keep it as an example.

Adding hard-coded support is moving the opposite way of what we plan to do (plugins) and adds maintenance support for future releases, for instance if a major customer uses it and it breaks for some reason. Also the library is GPLv3, not technically compatible with our licensing.

**Pull request merged**
