### PR TITLE
hotfix-threads-migrate

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

Fixes missing column in ThreadMemberships table

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]

**Comment by reflog** [comment]
@amyblais - where should this be cherry picked to?

**Comment by amyblais** [comment]
I added v5.31 milestone for now.

**Comment by amyblais** [comment]
@reflog Please also help cherry-pick to ``cloud`` when you have a chance.

**Comment by reflog** [comment]
@amyblais https://github.com/mattermost/mattermost-server/pull/16689

**Pull request merged**
