### PR TITLE
Migrates Channel.GetMembersForUserWithPagination to sync by default

### LINKED ISSUE #11214: Migrate "Channel.GetMembersForUserWithPagination" to Sync by default
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16346)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `GetMembersForUserWithPagination` in the `Channel` store.

The expected way to implement it is, go to the `Channel` store implementation in the `store/sqlstore/` directory, modify the method `GetMembersForUserWithPagination` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

This PR migrates `Channel.GetMembersForUserWithPagination` to sync by default.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-16346
Fixes #11214

### CODE REVIEW

**Comment by jespino** [comment]
@rvillablanca you branched from the wrong branch, and included the previous commit.

**Comment by rvillablanca** [comment]
I am sorry for that, I will have to change that

**Comment by rvillablanca** [comment]
@jespino is necessary to change the base branch of this PR is the other PR were merged?

**Comment by rvillablanca** [comment]
@jespino The base of this PR was merged so I think now is possible to make the code review

**Comment by jwilander** [comment]
Sorry for the late review on this @rvillablanca !

**Comment by rvillablanca** [comment]
There is no problem @jwilander

**Pull request merged**
