### PR TITLE
MM-47592 - Prepackage Calls v0.10.0

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Calls -> v0.10.0

/cc @amyblais

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-47037

#### Release Note
```release-note
Prepackage Calls version v0.10.0
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Thanks, just bear in mind Jesse is OoO today.

**Review by Phrynobatrachus — APPROVED** [review]

**Comment by cpoile** [comment]
@amyblais Are we okay to wait for tomorrow for Jesse? If it's easier to merge today, I don't think there will be any issues if we merge now.

**Comment by amyblais** [comment]
Tomorrow is fine 👍

**Review by lieut-data — APPROVED** [review]

**Comment by cpoile** [comment]
@amyblais Does this need to be cloud cherry picked?

**Comment by amyblais** [comment]
It doesn't - this will go into Nov 17th Cloud release. The next cloud fast-forward is scheduled for tomorrow.

**Comment by cpoile** [comment]
@amyblais Thank you!

**Pull request merged**
