### PR TITLE
[MM-37621] Update db schema validation scripts for 6.0

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR updates the db schema validation scripts for 6.0.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-37621

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Lovely

**Comment by amyblais** [comment]
@cpanato Kind reminder for PR review.

**Comment by agnivade** [comment]
Gentle ping @cpanato

**Comment by cpanato** [comment]
sorry missed this :(

**Review by cpanato — APPROVED** [review]

**Pull request merged**
