### PR TITLE
Revert "Revert "[MM-51274] Remove deprecated PermissionUseSlashCommands""

### PR DESCRIPTION
**Pull request by amyblais**
Reverts mattermost/mattermost-server#23405

Reverting the previous revert due to a bug found https://community.mattermost.com/core/pl/65qk8e9xitde8ym6r8msmm1whe.

### CODE REVIEW

**Comment by wiggin77** [comment]
I'm confused.  [[MM-51274] Remove deprecated PermissionUseSlashCommands](https://github.com/mattermost/mattermost-server/pull/22819) was found to break a Playbooks migration.  That PR was reverted and now no slash commands work?  Shouldn't we be back to where we started after the revert?  Also, do we know why unit tests are not catching a case where no slash commands work?

**Comment by amyblais** [comment]
If we merge this revert, I've opened a ticket for SET to triage the bug ticket for the Playbooks permission issue https://mattermost.atlassian.net/browse/MM-52574.

**Comment by wiggin77** [comment]
> If we merge this revert, I've opened a ticket for SET to triage the bug ticket for the Playbooks permission issue https://mattermost.atlassian.net/browse/MM-52574.

Sounds good.  Can we also get a ticket to make sure unit tests catch the `no slash commands work` issue?

**Review by wiggin77 — APPROVED** [review]

**Comment by amyblais** [comment]
Opened a ticket to add unit tests: https://mattermost.atlassian.net/browse/MM-52894.

**Review by lieut-data — APPROVED** [review]

**Pull request merged**
