### PR TITLE
MM-36486: Bump dependencies

### PR DESCRIPTION
**Pull request by agnivade**
Ran `make update-dependencies`

https://mattermost.atlassian.net/browse/MM-36486

```release-note
NONE
```

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]

**Comment by ashishbhate** [comment]
CI says some minor changes may be required to the code. LGTM otherwise.

**Comment by agnivade** [comment]
Thanks, will fix.

**Comment by agnivade** [comment]
ping @mkraft

**Comment by agnivade** [comment]
A flaky(actually bad) test has appeared - https://github.com/mattermost/mattermost-server/pull/17847. Waiting on it to be merged.

**Review by mkraft — APPROVED** [review]

**Pull request merged**
