### PR TITLE
[MM-30467] app/import_functions: fix a bug while importing for two different teams

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary

Messages were getting imported into a wrong team. If we have the same channel name for two different teams, we end up using wrong channel to import a post. I added another `map[teamName]` in front of the channel map so that we can have channels for the right team.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30467

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Good catch, thanks!. Looks good to me.

**Review by mgdelacroix — APPROVED** [review]
Nicely done! :rocket: LGTM!

**Review by lindalumitchell — APPROVED** [review]
Will test after merge.

**Pull request merged**
