### PR TITLE
[MM-42889] fixed search term for archived channels

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary
Search term was being ignored when browsing archived channels

#### Ticket Link
[MM-42889](https://mattermost.atlassian.net/browse/MM-42889)

#### Release Note
```release-note
Fixed search term for archived channels
```

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]
LGTM!

non-blocking: Unit test for this would be good.

**Review by koox00 — APPROVED** [review]

**Comment by Willyfrog** [comment]
> LGTM!
> 
> non-blocking: Unit test for this would be good.

you are right, but given code freeze I don't think I'll have that part in time. So I've created https://mattermost.atlassian.net/browse/MM-43151 to work on that on friday. Thanks for pointing it out

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
