### PR TITLE
MM-51846 : Upgrade Esint from 7 to 8+

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
We are finally ready to upgrade to the latest version of eslint despite the file changes and conflicts it has caused in the past with other dependencies supporting eslint 7 as a peer dependency. The main difference this upgrade introduces is the addition of semicolons at the end of class component methods created by the eslint fix.
Other changes required for the upgrade are
- removed 'eslint' dependency from products workspaces and added it to the root
- upgraded '@typescript-eslint' in product workspaces
- changed  "@babel/eslint-plugin" to '@babel' in plugins section of eslintrc of channels.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51846

#### Release Note

```release-note
Upgraded Eslint to 8.37.0
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]

**Review by neallred — APPROVED** [review]
LGTM, thanks @M-ZubairAhmed !

**Comment by M-ZubairAhmed** [comment]
Added another review as few changes were required after https://github.com/mattermost/mattermost-server/pull/22629 got merged

**Comment by M-ZubairAhmed** [comment]
Added another review from @calebroseland as few changes were required after rebasing with master

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
