### PR TITLE
Remove warn metric aka Mattermost Advisor

### PR DESCRIPTION
**Pull request by WGH-**
### Summary
This useless code serves no purpose other than annoy the hell out of admins, so remove it.

See also https://forum.mattermost.org/t/new-admin-advisor-notifications-in-mattermost-v5-26/10263/6

```release-note
Removed Mattermost Advisor (the bot that periodically messages server admins about enterprise license upgrade).
```

### CODE REVIEW

**Comment by jasonblais** [comment]
Hi @WGH-, thank you for your feedback. We really appreciate the input.

From your PR issue description, it sounds like the bot sends new messages periodically. Would you be open to sharing how frequently you're receiving these messages, and the content of each?

We have been tracking down a bug where the same notification is sent multiple times, but haven't been able to reproduce the issue. The intention is for a specific advisor bot notification to be sent only once.

cc @vient feel free to share the same if you're open to.

**Comment by WGH-** [comment]
They appear to be sent weekly, which corresponds to the logic in the source code. I updated the server recently, we've received only two messages so far, and they were different.

It wouldn't be that problematic if they didn't trigger the same notifications as ordinary messages (including desktop nofitications, phone notifications, etc.). I would be more or less fine with it if it only was some kind of silent nag bar. And if on top of that I could just disable it forever with a setting, it would be pretty much perfect.

@vient is from the same server as me.

**Comment by jasonblais** [comment]
@WGH- thank you for the feedback!

> I updated the server recently, we've received only two messages so far, and they were different.

Which version did you update to, and when did this take place?

You are correct that the original release of this feature in v5.26 sent the bot message once a week, but we subsequently adjusted the frequency. However, there may be a bug that we would need to resolve.

> It wouldn't be that problematic if they didn't trigger the same notifications as ordinary messages (including desktop nofitications, phone notifications, etc.). I would be more or less fine with it if it only was some kind of silent nag bar. And if on top of that I could just disable it forever with a setting, it would be pretty much perfect.

Thank you for the open feedback. I'll share it with the team to hear their thoughts.

**Comment by WGH-** [comment]
> Which version did you update to, and when did this take place?

I updated last thursday from 5.23.0 to 5.28.1.

**Comment by notnamed** [comment]
The way the behavior of this Advisor currently works, it is effectively a mailing list that I cannot unsubscribe from. In the [forum thread](https://forum.mattermost.org/t/new-admin-advisor-notifications-in-mattermost-v5-26/10263/5), this reply indicates that the notifications will stop if "learn more" or "contact us" is selected - but this isn't clear in the bot message; additionally, these actions share data with Mattermost with no opt-out.

I can see the use-case where the Advisor provides a useful notification for a server administrator who is not otherwise aware of relevant functionality in the Enterprise editions, based on the characteristics of how they are currently using the platform. It would make more sense for these messages to appear in the relevant sections of the System Console, I feel, where the actual pain would be experienced, but a bot message is not an invalid way to surface this information.

However, I agree with the PR author here, that generating push notifications and other normal-message-behavior from a bot providing marketing messages is pretty undesirable. While I'd be happy to accept that this is not the case, the current behavior implies that the Team Edition is no longer an open-core feature subset of the Mattermost collaboration platform, but is rather a limited preview, both feature- and time-bound, not suited for production use.

Providing an opt-out for these notifications would definitely be the ideal, from my perspective. Moving the messages to somewhere less-obtrusive, such as in the System Console, would also be a fine compromise. But I think the way these messages are worded, and the way the opt-out reported in the forum thread requires sharing data, both feels bad as an operator of the Team Edition and leaves me concerned as to the future of the Team Edition of the platform.

**Comment by jasonblais** [comment]
Thank you @WGH- and @notnamed - I'll find some more information on the intended behaviour as a next step, with an opportunity to document them as well to increase clarity on this feature.

The owner of this feature is on a personal leave, so there are a few things I'm currently catching up on from what he was working on. But this feature is certainly on my list to review.

**Comment by jasonblais** [comment]
I have assigned this to myself, and will follow up. Thank you for your patience?

**Comment by jasonblais** [comment]
Thanks everyone who have offered feedback about this feature in this GitHub PR, [our forums](https://forum.mattermost.org/t/new-admin-advisor-notifications-in-mattermost-v5-26/10263) and elsewhere.

Given the feedback, we’ll pause admin advisor notifications with the next self-managed release on May 16th. Ticket to follow progress can be found at https://mattermost.atlassian.net/browse/MM-34893.

The original vision for the admin advisor notification feature was to guide administrators through proper activation and configuration of the system as the needs of their user base evolves, with some additional capabilities in the Enterprise offering. However, based on the feedback, it is evident that the experience feels spammy with limited value which was not the intent, negatively impacting the trust with our community. Thus, we've decided to pause admin advisor notifications in the next release.

@WGH- @vient @notnamed I apologize for the delay in taking action faster, and for not being transparent with updates and communication for this feature (e.g. we had in our roadmap to make changes to this experience at the beginning of 2021, which got delayed due to other priorities). To prevent further delays, we'll pause the notifications on the next self-managed release.

Thank you for your patience, and for offering thoughtful feedback. It's very much appreciated.

**Comment by jasonblais** [comment]
PR is submitted here: https://github.com/mattermost/mattermost-server/pull/17422

**Comment by WGH-** [comment]
So I've just finally updated from my custom patched version to 5.37.0, hoping that I no longer have to patch out the advisor, and has been greeted with this stupid message that notified all the admins about "Using Advanced Permissions".

You briefly disabled the bot (a16fdb50019f8d06e6f3cd9a4323ab9f5cb0d1f0) only to re-enable it again (77d42568f94cf2f1c141d3ee4775269259b3d480). Just why?..

**Comment by WGH-** [comment]
Nothing some SQL couldn't fix:

```
sudo -u postgres psql mattermost -c "BEGIN; DELETE FROM posts WHERE type = 'warn_metric_status'; ALTER TABLE posts ADD CONSTRAINT fuck_off CHECK(type != 'warn_metric_status'); COMMIT;"
```

**Comment by jasonblais** [comment]
@WGH- that's disappointing :( Judging from the size of PR that added the feature back, I suspect it got added by accident. Seems like it had been open for a while and probably just had an improper rebasing to the main branch before merging the code.

I'll queue this to be disabled, really appreciate you letting us know and helping us track down what re-introduced it back.

**Comment by jasonblais** [comment]
Ticket created to re-disable it. I've also asked to add a unit test for it, so we catch in the future if it's re-enabled by mistake: https://mattermost.atlassian.net/browse/MM-37496

**Comment by WGH-** [comment]
Looking at this - 77d4256 - enormous diff again, I wonder if something else got rolled back as well...

**Comment by jasonblais** [comment]
@WGH- yea, in the Jira issue I created I asked to review if any other unintended changes were introduced after merging the associated pull request.

Here is the PR that disables the admin advisor notifications, planned for v5.38 (releasing on Aug 16).

**Comment by isacikgoz** [comment]
Hey @jasonblais is there any update to make this issue resolved?

**Comment by jasonblais** [comment]
Yes, https://github.com/mattermost/mattermost-server/pull/18054 was merged and shipped with August 16th release.

@WGH- curious if you've had an opportunity to upgrade to the August release (v5.38) to verify on your end?

**Comment by WGH-** [comment]
***@***.*** curious if you've had an opportunity to upgrade to the August release (v5.38) to verify on your end?

Not yet. And I protected the server with SQL constraints, so I wouldn't be able to tell anyway :)

In any case, I do believe you it's fixed, hopefully for good

**Comment by jasonblais** [comment]
Thanks @WGH-! :)

I'll close this as resolved via https://github.com/mattermost/mattermost-server/pull/18054

**Pull request closed without merging**
