### PR TITLE
[MM-48049] Including users who were removed from group in not_in_group response

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Users who were removed from a group couldn't be added back in through the UI

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48049

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by plant99 — APPROVED** [review]

**Comment by amyblais** [comment]
@BenCookie95 This has some failing tests.

**Review by cyrilzhang-mm — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working fine with these steps

1. Login as Admin
2. Create a user (UserA)
3. Create a Group (TestGroup)
4. Added UserA to TestGroup
5. Remove UserA from TestGroup
6. Refresh the page
7. Goto Add People from TestGroup
8. Type UserA

**Result:** UserA appeared in the results

**Pull request merged**
