### PR TITLE
Update supported browser/OS versions

### PR DESCRIPTION
**Pull request by amyblais**
- Updated Firefox version to Version 91+ (current ESR) (Let me know any concerns on this)
 - Corrected Windows support to 8.1+ (We dropped support for Win 7 for v6.0 release and it was communicated back then. This file missed getting updated)

Will add to release notes.

### CODE REVIEW

**Review by esethna — APPROVED** [review]

**Comment by esethna** [comment]
@amyblais do we want to write any blog or forum post about dropping Win 7, or do we already have public comms about this?

**Comment by amyblais** [comment]
> @amyblais do we want to write any blog or forum post about dropping Win 7, or do we already have public comms about this?

@esethna We dropped support for Win 7 for v6.0 release and it was communicated back then. This file missed getting updated.

**Review by hmhealey — APPROVED** [review]

**Comment by amyblais** [comment]
@svelle @coltoneshaw Let me know if the Support team has any concerns on the updates in this PR.

**Review by coltoneshaw — APPROVED** [review]

**Pull request merged**
