### PR TITLE
Adds server awareness.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Wraps the "fire and forget" background sync goroutines in the mechanism for server awareness in the case of a shutdown signal being sent.

#### Ticket Link

n/a

### CODE REVIEW

**Comment by srkgupta** [comment]
@mkraft can you please let me know what is impacted because of this change and what needs to be tested?

**Comment by mkraft** [comment]
@srkgupta Testing this would be a subset of the testing done for https://github.com/mattermost/mattermost-server/pull/13432.

**Pull request merged**
