### PR TITLE
re-assign cluster interface after initializing enterprise interfaces

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Fixes an issue where cluster interface was not passed to platform service after initialized.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46426

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
I can see this is starting to become more brittle :) I hope this is just a temporary pain until we shift more things under platform.

**Comment by isacikgoz** [comment]
@amyblais wondering if we can have a QA review on this? I just run HA locally so I was able enable plugin:

image

**Comment by amyblais** [comment]
> @amyblais wondering if we can have a QA review on this? I just run HA locally so I was able enable plugin:
> 
> image

cc @DHaussermann

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@isacikgoz Is it possible to have a unit test for general cluster communication?

**Comment by DHaussermann** [comment]
@isacikgoz I have tested this on `/cloud` servers running in HA and the solution function correctly. 

I attempted to disable and enable plugins about a dozen times on 2 different servers. I only saw one odd behavior - On one occasion when the plugin was `disabling` the UI hung and then one of the cluster instances went down. In HA health there was only one showing as yellow. A few minutes latter the servers was working normally again. I know this does occasionally happen to the `/cloud` servers. Just posting here to ask if there is any chance it is related to the change.

**Comment by isacikgoz** [comment]
@DHaussermann thanks, I don't think this is related with the changes we made in the https://github.com/mattermost/mattermost-server/pull/20718 or this PR but to understand better, did you observe any log messages during the app going down? Or, if the servers are live, would you mind sharing logs with me?

@mickmister this would be possible through mocking I guess, I'll look into it.

**Comment by DHaussermann** [comment]
@isacikgoz the server is here https://dkh-ha-fix.test.mattermost.cloud it uses the stock credentials. Happy to DM them to you if needed.

Unfortunately - the log level was set to `INFO` at the time which is the default setting.  I'm not seeing anything relevant error but I also don't know what to expect when one of the nodes goes down.

**Comment by isacikgoz** [comment]
Only seeing `failed to load global manifest`  but it's not a thing that could be related with our changes. On the other hand, I tested on my local HA setup and nearly 30 times I enabled/disabled a plugin, it didn't cause any problem.

**Comment by DHaussermann** [comment]
Thanks for checking @isacikgoz 

I have run now run various plugins through the enable / disable cycle several dozen times. The issue did not reproduce for me either. Given that you're not seeing a link to the code change and these `/cloud` server do occasionally exhibit temporary HA issues It seems reasonable to assume this one occurrence was unrelated to the PR. 
I just wanted to ask as a precaution in case you saw a technical reason it could be related.    

I think we should approve the PR. I can do so if the builds pass after the unit test was added above.

**Comment by amyblais** [comment]
@isacikgoz It looks like the tests are failing.

**Comment by isacikgoz** [comment]
> @isacikgoz It looks like the tests are failing.

I'll check once I get back home later today.

**Review by DHaussermann — APPROVED** [review]
This was tested and passed

Please merge once int tests are successful

LGTM!

**Pull request merged**
