### PR TITLE
User friendly error messages during OAUTH and SAML flows

### PR DESCRIPTION
**Pull request by anurag6713**
#### Summary
OAUTH & SAML Errors in WebView flow were printing JSON as response. It must be shown similar to web.

Old:
image-2020-02-14-10-34-55-468

New:
Untitled

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22594

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by sbishel — CHANGES_REQUESTED** [review]
Let's add some unit tests.

**Review by mkraft — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
image

image

**Pull request merged**
