### PR TITLE
[MM-52271] Add recommended tag to Work Template integrations

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Add a recommended tag to work template integration:

- Exclude them from the preview page.
- Remove those plugins from being sent for installation.

QA: everything must work as it did before

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52271

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @JulienTant !

**Review by pvev — APPROVED** [review]
LGTM! thanks @JulienTant :shipit:

**Comment by stevemudie** [comment]
@JulienTant I'm not seeing the Integrations card on the Work Templates so therefore I'm not seeing the recommended tag. Or am I missing something? 🤔

**Comment by JulienTant** [comment]
> @JulienTant I'm not seeing the Integrations card on the Work Templates so therefore I'm not seeing the recommended tag. Or am I missing something? 🤔

Hey, the integration thing is the usual spinwicks problem, and nothing is "shown" as recommended by the modal. I guess this is one more we need to postpone :/

**Review by stevemudie — APPROVED** [review]
I'll test this one post merge.

**Pull request merged**
