### PR TITLE
[MM-39999] Increase key length in plugin KV store to 150

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Given the need for longer keys from the Apps Plugin this PR increases the length to 150.

Even with large installation this migration should not take long. It also can run concurrently. 

The commands to run it manually are:
```SQL
ALTER TABLE PluginKeyValueStore ALTER COLUMN pKey TYPE VARCHAR(150);
ALTER TABLE PluginKeyValueStore MODIFY pKey VARCHAR(150);	
```

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39999

#### Release Note

```release-note
Increase key length in plugin KV store to 150
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by agnivade — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Heads up that this change should go into 6.2 if possible. Is there you need to test it?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Regression tested by installing, using and uninstalling various plugins
- As a precaution - Also tested on a server with scaled multitenant database.   
- No other functional testing applicable as nothing yet writes to the plugin KV store that exceeds the old limit. Ben has included a coded test that exercises this. 

No issues found.
LGTM!

**Comment by hanzei** [comment]
@amyblais I would like to cherry-pick this PR into cloud so it gets includes in 6.3, as these are required changes for the Apps Plugin. Are you fine that that?

**Comment by amyblais** [comment]
Yes, it can be cherry-picked to the 6.3 branch once it has been cut.

**Comment by hanzei** [comment]
@amyblais Just to double check: Should it also get cherry-picked into `cloud` to ensure it gets deployed there?

**Comment by amyblais** [comment]
> @amyblais Just to double check: Should it also get cherry-picked into `cloud` to ensure it gets deployed there?

Not needed to cherry-pick to cloud, 6.3 branch will be based off Dec 8th cloud release.

**Comment by amyblais** [comment]
@hanzei Needs a manual cherry-pick to ``release-6.3`` branch.

**Pull request merged**
