### PR TITLE
translations PR 20190225

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2408
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2595

### CODE REVIEW

**Comment by enahum** [comment]
@cpanato it seems that these PR's failed when not submitted against master

**Comment by cpanato** [comment]
@enahum looks like it is a positive error

```
        	            	--- FAIL: TestExecCommand (0.16s)
        	            	panic: unable to parse translation #928 because template: ID wywołania dla interaktywnego dialogu wygasło. Maksymalny czas życia dla ID wywołania wynosi {{.Seconds.}} sekund.:1: unexpected <.> in operand
        	            	map[id:interactive_message.decode_trigger_id.expired translation:ID wywołania dla interaktywnego dialogu wygasło. Maksymalny czas życia dla ID wywołania wynosi {{.Seconds.}} sekund.] [recovered]
        	            		panic: unable to parse translation #928 because template: ID wywołania dla interaktywnego dialogu wygasło. Maksymalny czas życia dla ID wywołania wynosi {{.Seconds.}} sekund.:1: unexpected <.> in operand
        	            	map[id:interactive_message.decode_trigger_id.expired translation:ID wywołania dla interaktywnego dialogu wygasło. Maksymalny czas życia dla ID wywołania wynosi {{.Seconds.}} sekund.]
        	            	
        	            	goroutine 25 [running]:
        	            	testing.tRunner.func1(0xc000200900)
        	            		/usr/local/go/src/testing/testing.go:792 +0x387
        	            	panic(0x1501760, 0xc001ce5dc0)
        	            		/usr/local/go/src/runtime/panic.go:513 +0x1b9
        	            	github.com/mattermost/mattermost-server/cmd/mattermost/commands.InitDBCommandContextCobra(0x27b43a0, 0xc000201100, 0xc000087ce0, 0x933b24)
        	            		/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/init.go:23 +0x190
        	            	github.com/mattermost/mattermost-server/cmd/mattermost/commands.addChannelUsersCmdF(0x27b43a0, 0xc0000e8780, 0x2, 0x5, 0x0, 0x0)
        	            		/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/channel.go:261 +0x43
        	            	github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x27b43a0, 0xc0000a0d80, 0x5, 0x6, 0x27b43a0, 0xc0000a0d80)
        	            		/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762 +0x473
        	            	github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x27bb340, 0xc00009e680, 0xf, 0xc00007b3f0)
        	            		/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
        	            	github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x27bb340, 0x7ffd191de37a, 0xb)
        	            		/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800 +0x2b
        	            	github.com/mattermost/mattermost-server/cmd/mattermost/commands.TestExecCommand(0xc000200900)
        	            		/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/exec_command_test.go:18 +0x117
        	            	testing.tRunner(0xc000200900, 0x17e53d0)
        	            		/usr/local/go/src/testing/testing.go:827 +0xbf
        	            	created by testing.(*T).Run
        	            		/usr/local/go/src/testing/testing.go:878 +0x353
```

**Comment by enahum** [comment]
Ah, lets take a look at what translation is causing the failure and I'll fix it

**Comment by enahum** [comment]
Fixed polish translation

**Comment by enahum** [comment]
@jasonblais what changes are you requesting?

**Pull request merged**
