### PR TITLE
MM-10766 - Replacing default profile image font

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-10766 - Replacing default profile image font
Using the google font: https://fonts.google.com/specimen/Nunito

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10766

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jespino** [comment]
@jasonblais could you confirm that the license is compatible with Mattermost?

**Comment by jasonblais** [comment]
@asaadmahmood @jespino Are we only including the binary form of this font?

**Comment by asaadmahmood** [comment]
@jasonblais That's all we need to generate images. This font is just used to generate images like the previous one. So I just replaced the .ttf file with the .ttf file of the new font.

**Comment by jasonblais** [comment]
@asaadmahmood Sounds good. And is this the source URL? https://github.com/google/fonts/blob/master/ofl/nunito/Nunito-Bold.ttf

**Comment by jasonblais** [comment]
Re: the license itself - I'll have to look into it a little more; the license is not directly compatible but should be okay if there's proper attribution for it.

I might need to contact our open source lawyer about this, since the license on this server repo is a bit more complicated.

**Comment by asaadmahmood** [comment]
@hmhealey Can you submit a commit to this branch based on your 2nd suggestion?

**Comment by hmhealey** [comment]
Yep, I've got the ticket to finish this up in the next week or so

**Comment by hmhealey** [comment]
@jasonblais Any update on the licensing situation?

**Comment by jasonblais** [comment]
@hmhealey Haven't heard from the lawyer now, reached out again. Will this need to go in by major feature date (tomorrow)?

**Comment by hmhealey** [comment]
@jasonblais No, it's fine to go in any time before code complete

**Comment by jasonblais** [comment]
@hmhealey Questions I got in return:

1. Are we compiling/merging the font software into our project or aggregating it so that it is distributed alongside our project?
 - I believe we merge the font software (?)

2. Also, are we modifying the font software?
 - No (?)

**Comment by hmhealey** [comment]
@jasonblais The font is distributed alongside the Mattermost executable. We are not modifying the font.

The specific wording of "font software" is a bit odd since it's a font file we're worried about, not a piece of code, but I guess that's some legalese that I'm missing.

**Comment by jasonblais** [comment]
Thanks, I'll let the lawyer know

**Comment by cpanato** [comment]
any update on this? should we remove this from the 5.1.0 release?

**Comment by jasonblais** [comment]
Lawyer was busy with end of quarter tasks. I expect to hear from her by end of day after which we can merge.

@asaadmahmood @hmhealey Can you help rebase so it's ready to merge later today? Sorry for the delay,

**Comment by cpanato** [comment]
waiting for @hmhealey

**Pull request merged**
