### PR TITLE
[MM-48542] Removing integration limits

### PR DESCRIPTION
**Pull request by javaguirre**
#### Summary

This PR Removes limits on Cloud integration installations.

- [Has Frontend changes that need to be merged before this](https://github.com/mattermost/mattermost-webapp/pull/11346)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48542

#### Release Note

```release-note
Removes limits in Cloud integration installations
```

### CODE REVIEW

**Comment by javaguirre** [comment]
Regarding removing parts of `integrations.go` I'm not sure [this](https://github.com/mattermost/mattermost-server/blob/master/app/integrations.go#L31-L70) can go, since it seems there are some stats related to it. I could remove all stats (I am doing it actually, `getIntegrationsUsage` and such).

This seems unrelated to cloud Freemium limits, but I might be wrong, and depends on `getInstalledIntegrations`.

https://github.com/mattermost/mattermost-server/blob/master/model/client4.go#L8423-L8433

WDYT @mickmister ?

**Comment by javaguirre** [comment]
Hello @neallred !

I have to remove the freemium limits, but I was wondering if the `getIntegrationsUsage` stats are still relevant in case we remove the limits? If they're not, I'll remove them, but they're probably still relevant, right?

[This is the code related to this, for context](https://github.com/mattermost/mattermost-server/blob/5e69c6b02f604ce1aecb4c22cc58f9412cc685a2/app/usage.go#L24-L42)

Thank you!

**Comment by neallred** [comment]
I think the usage stats can be removed as well as they're not used for any reporting or dashboards or anything; they are only used in the context of the workspace limits. Note that this PR should hol doff on merging until the related frontend work is ready to merge. Otherwise, if this deploys first, for cloud instances, the frontend will continue making requests to a now non-existent endpoint, creating lots of 4xx errors.

**Comment by mickmister** [comment]
> I think the usage stats can be removed as well as they're not used for any reporting or dashboards or anything

@neallred The integrations stats used to be displayed in the billing dashboard. Is this no longer the case? Just making sure. I'm up for removing all of the integrations-related code 🙂

**Comment by mickmister** [comment]
@neallred Okay so it seems that every instance of showing the number of installed integrations is related to displaying limits information. Therefore, there is no value in keeping the stats logic on the server at the moment. If we want to show admins (including on-prem admins) in the future, we will need to design how/where we show that information.

@javaguirre Based on this, I'm thinking we should remove all instances of the integrations usage. What are your thoughts?

**Comment by javaguirre** [comment]
> @neallred Okay so it seems that every instance of showing the number of installed integrations is related to displaying limits information. Therefore, there is no value in keeping the stats logic on the server at the moment. If we want to show admins (including on-prem admins) in the future, we will need to design how/where we show that information.
> 

Great! I'll also create a PR for the frontend before continuing with this.

> @javaguirre Based on this, I'm thinking we should remove all instances of the integrations usage. What are your thoughts?

Based on the code I've seen in the backend I agree with you. 👍

**Review by neallred — APPROVED** [review]
LGTM, thanks @javaguirre !

**Review by mickmister — APPROVED** [review]
`+0 −558`

Beautiful 🙂

**Review by noxer — APPROVED** [review]

**Review by DHaussermann — COMMENTED** [review]
Tested and passed. 
- Tested with several licenses including Cloud Starter
- Tested running in E0 with no license
- No functional issues found 
- No signs remaining of usage limits
- Also tested on HA and cloud test infrastructure
- No issues found

LGTM!

Thanks @javaguirre 🎉  sorry for the delay on this. Please merge.

**Pull request merged**
