### PR TITLE
MM-11713: Does not require edit_own_posts to edit_others_posts.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Changes the patch post API endpoint authorization logic to allow the `edit_others_posts` permission to function independently of `edit_own_posts`.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-11713

#### Related PRs

* https://github.com/mattermost/mattermost-mobile/pull/4406
* https://github.com/mattermost/mattermost-redux/pull/1171

### CODE REVIEW

**Comment by srkgupta** [comment]
Hi @mkraft and @thefactremains 
Can you please confirm if this change is only specific to Edit Other Posts. Or should this also be implemented for Remove Other Posts? Can you please confirm? I am not seeing changes related to Remove Other Posts in this PR.

**Comment by mkraft** [comment]
> Hi @mkraft and @thefactremains
> Can you please confirm if this change is only specific to Edit Other Posts. Or should this also be implemented for Remove Other Posts? Can you please confirm? I am not seeing changes related to Remove Other Posts in this PR.

The delete permissions already behave such that one can have the authorization to delete others posts without having the ability to delete ones own posts, so there was not change required.

**Comment by justinegeffen** [comment]
@mkraft, as this seems like expected behavior I don't see any doc updates needed as it fixes an issue. Please let me know if that's not the case. Thank you!

**Comment by mkraft** [comment]
> @mkraft, as this seems like expected behavior I don't see any doc updates needed as it fixes an issue. Please let me know if that's not the case. Thank you!

Agreed.

**Pull request merged**
