### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amyblais**
Remove link to demo server in the README file as it doesn't seem to work anymore -- demo.mattermost.com.

For https://github.com/mattermost/mattermost-server/issues/16764

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Should we link to a cloud sign up page like https://customers.mattermost.com/cloud/signup instead?

**Comment by jasonblais** [comment]
I like Ben's suggestion, perhaps with

```
- [Get started with Mattermost Cloud](https://customers.mattermost.com/cloud/signup) to try out Mattermost,
```

**Review by jasonblais — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Comment by amyblais** [comment]
I don't have merge permissions; assigned to Ben.

**Comment by amyblais** [comment]
Also updated the signup link to the community server as it was invalid.

**Review by hanzei — APPROVED** [review]

**Pull request merged**
