### PR TITLE
MM-10769 Rename references to spf13/viper to mattermost/viper

### PR DESCRIPTION
**Pull request by hmhealey**
When I forked the library, I was lazy and just replaced the files with the ones from the fork. This properly updates the import path and puts the files in the right place.

I updated the Gopkg files by hand since it was just a simple find and replace. Let me know if that'll cause any problems

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10769
https://github.com/mattermost/mattermost-server/issues/8883

### CODE REVIEW

**Comment by coreyhulen** [comment]
0/5 I might be misunderstanding, but can't you override the repo via Gopkg file without having to change to rename the package?

**Comment by hmhealey** [comment]
That's what I had originally done, but a community member filed an issue asking to change it since I think it was causing a dependency conflict or something.

**Comment by coreyhulen** [comment]
Ok, I'm +1 I guess. 

Would we ever push our changes back?

**Comment by hmhealey** [comment]
I submitted a PR to the parent repository back when I made the change, but I got no feedback from them about it

**Pull request merged**
