### PR TITLE
[MM-36387] Address db performance audit items

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR addresses some of the findings from the recent Percona audit:

- https://mattermost.atlassian.net/browse/MM-36334
- https://mattermost.atlassian.net/browse/MM-36338
- https://mattermost.atlassian.net/browse/MM-36339
- https://mattermost.atlassian.net/browse/MM-36366
- https://mattermost.atlassian.net/browse/MM-36475
- https://mattermost.atlassian.net/browse/MM-36477

They are mainly index additions to improve either expensive or very frequent queries.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-36387

#### Release Note

```release-note
Added the following db indexes:
- idx_posts_root_id_delete_at_create_at
- idx_channels_team_id_display_name
- idx_channels_team_id_type
- idx_threads_channel_id_last_reply_at
- idx_channelmembers_user_id_channel_id_last_viewed_at
- idx_channelmembers_channel_id_scheme_guest_user_id

Removed the following redundant db indexes:
- idx_posts_root_id
- idx_channels_team_id
- idx_threads_channel_id
- idx_channelmembers_user_id
```

### CODE REVIEW

**Comment by agnivade** [comment]
Amazing work! Couple of questions:
- Was the `channelstore.GetGuestCount` a frequent query? Seems surprising. I do see it appearing in the `getChannelStats` api call. But I don't see it in the top 10 DB queries in grafana.
- Can you expand a bit more on the `rootid_deleteat_createat` index? Is there a need to add `createat` too at the end? A slight concern that I have is that `DeleteAt` is a tricky column with low cardinality, and we are doing the same thing in the [query](https://mattermost.atlassian.net/browse/MM-36334) - filtering by `deleteat = 0` - which triggered the index intersection bug. Granted that we are deleting the sole rootid index, but you never know MySQL :man_shrugging: 

  It is also not super-clear to me exactly which sub-query within the whole query is being benefitted with this index. Would be great to see an EXPLAIN ANALYZE before-after especially for MySQL.

- One addition request, looking at the top-10 time taking [queries](https://grafana.mattermost.com/d/HyUDjBaWk/overall-stats?viewPanel=2&orgId=1&refresh=5m&from=1628297856408&to=1628319456408&var-app=community&var-top_db_count=All&var-top_db_latency=All&var-top_api_count=All&var-top_api_latency=All&var-top_db_weighted=All&var-top_api_weighted=All), I see that `StatusStore.UpdateExpiredDNDStatuses` has come into the picture. That is because the `DNDEndtime` column was added without any index. Would suggest replacing the `status` index by a `status+dndendtime` index.

- Everything else looks great!
- 0/5, lastly, I know the Percona report has been on MySQL, and we expect similar results for Postgres too, but it would be great to see a load-test result for Postgres. I know that eventually we will get a 5.38 vs 6.0 test anyways, so don't bother if you are busy with other stuff.

**Review by mkraft — APPROVED** [review]

**Comment by streamer45** [comment]
> * Was the `channelstore.GetGuestCount` a frequent query? Seems surprising. I do see it appearing in the `getChannelStats` api call. But I don't see it in the top 10 DB queries in grafana.

I've considered adding it since it's part of "view/switch channel" action. Not the most frequent since it's directly related to user input but it's something that still gets called a lot when running many users concurrently.

> * Can you expand a bit more on the `rootid_deleteat_createat` index? Is there a need to add `createat` too at the end? A slight concern that I have is that `DeleteAt` is a tricky column with low cardinality, and we are doing the same thing in the [query](https://mattermost.atlassian.net/browse/MM-36334) - filtering by `deleteat = 0` - which triggered the index intersection bug. Granted that we are deleting the sole rootid index, but you never know MySQL man_shrugging
>   It is also not super-clear to me exactly which sub-query within the whole query is being benefitted with this index. 

The improvement is just on the internal filtering. See Query 4 from [this document](https://github.com/mattermost/mattermost-server/files/6961322/output.pdf). 
We've been running 25k users on these changes and didn't spot issues so I am thinking MySQL is behaving correctly on this one.


> * One addition request, looking at the top-10 time taking [queries](https://grafana.mattermost.com/d/HyUDjBaWk/overall-stats?viewPanel=2&orgId=1&refresh=5m&from=1628297856408&to=1628319456408&var-app=community&var-top_db_count=All&var-top_db_latency=All&var-top_api_count=All&var-top_api_latency=All&var-top_db_weighted=All&var-top_api_weighted=All), I see that `StatusStore.UpdateExpiredDNDStatuses` has come into the picture. That is because the `DNDEndtime` column was added without any index. Would suggest replacing the `status` index by a `status+dndendtime` index.

Sure, I can have a look at that, thanks for pointing it out :+1: 

> * 0/5, lastly, I know the Percona report has been on MySQL, and we expect similar results for Postgres too, but it would be great to see a load-test result for Postgres. I know that eventually we will get a 5.38 vs 6.0 test anyways, so don't bother if you are busy with other stuff.

I ran a comparison with all these changes on both DBs and didn't notice any issue. What's not been possible yet, mainly due to the time required, was to do an analysis on each one of them separately. I am planning to at least do it from a query level by checking `EXPLAIN ANALYZE` outputs once I get to do the full migration analysis for 6.0.

**Comment by agnivade** [comment]
Sounds perfect. Just a small point on query 4. It looks like we are adding "CreateAt" to the index just for added performance later? This query seems to work fine with a create_at_delete_at index. I am okay with it, just for my own understanding.

**Comment by streamer45** [comment]
> Sounds perfect. Just a small point on query 4. It looks like we are adding "CreateAt" to the index just for added performance later? This query seems to work fine with a create_at_delete_at index. I am okay with it, just for my own understanding.

Honestly I thought it could help with the ordering of the main query but as is it really looks redundant since a `root_id_delete_at` index would achieve the same results. I'll get some confirmation from them before and if redundant we can remove it.

**Comment by agnivade** [comment]
lol I meant root_id_delete_at, not create_at_delete_at obviously :facepalm: 

>  I'll get some confirmation from them before and if redundant we can remove it.

Sounds good!

**Comment by streamer45** [comment]
@agnivade 

I've confirmed with Percona that indexing on the additional column (`CreateAt`) is not needed to optimize that query. I've updated the PR accordingly.

**Comment by agnivade** [comment]
Cool. Do you also plan to update the status index with the dndendtime column?

**Comment by streamer45** [comment]
> Cool. Do you also plan to update the status index with the dndendtime column?

Yes, will take a look later today.

**Review by agnivade — APPROVED** [review]

**Comment by streamer45** [comment]
@furqanmlk No functionality changes in this PR. I am thinking a successful run of e2e tests should be sufficient to cover it.

**Comment by amyblais** [comment]
@furqanmlk Kind reminder for PR review.

**Review by furqanmlk — APPROVED** [review]
All E2E test case PASSED
91.39% passed 
https://automation-dashboard.vercel.app/cycles/82eff234-1b9d-4e19-939f-c26e7e2ca727

**Pull request merged**
