### PR TITLE
[MM-40407] - Do not show the Renew Now if the license id does not exist in the portal

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR adds the necessary cloud interfaces to consume the new endpoint added in the portal

#### Ticket Link
[MM-40407](https://mattermost.atlassian.net/browse/MM-40407)

#### Related PRs
https://github.com/mattermost/enterprise/pull/1116
https://github.com/mattermost/customer-web-server/pull/632

#### Release Note
```release-note
NONE

```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]

**Review by marianunez — APPROVED** [review]

**Comment by amyblais** [comment]
@marianunez Is this needed for v6.3?

**Comment by marianunez** [comment]
> @marianunez Is this needed for v6.3?

Yes, and the related PRs as well: https://github.com/mattermost/enterprise/pull/1116 and https://github.com/mattermost/mattermost-webapp/pull/9544

**Pull request merged**
