### PR TITLE
[MM-42421] Prevent guests from seeing users through groups API

### PR DESCRIPTION
**Pull request by cyrilzhang-mm**
#### Summary

Adds view restrictions to the group store to only return users that the current user can see. This prevents guests from accessing user information through the groups API if they do not have a shared channel. Affects these endpoints:

```
/api/v4/groups?filter_has_member=<member_id>
/api/v4/users?not_in_group=<group_id>
/api/v4/users?in_group=<group_id>
/api/v4/groups/<group_id>?include_member_count=true
/api/v4/groups/<group_id>/members
```

#### Ticket Link

[Jira ticket](https://mattermost.atlassian.net/browse/MM-42421)

Steps to reproduce:
- View, as a guest account, a custom user group containing users that the guest shouldn't see. The guest is able to see these users.
- The guest can also use the API directly to get the list of users or number of users in a group.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by cyrilzhang-mm** [comment]
The tests are failing because users are now returned in a different order, since I removed the `order by` in the SQL query. If removing the order is fine, I will update the tests.

**Comment by BenCookie95** [comment]
> The tests are failing because users are now returned in a different order, since I removed the `order by` in the SQL query. If removing the order is fine, I will update the tests.

The frontend doesn't really care about the order by because we just arrange them alphabetically anyway. In order to avoid flakey tests lets add this order by: `ORDER BY u.CreateAt DESC`

**Comment by cyrilzhang-mm** [comment]
Marked as draft for now since I received a response on the Jira ticket and will need to make some modifications.

**Comment by cyrilzhang-mm** [comment]
I have updated this PR to address the feedback from the Jira ticket, so it's ready now. Please double-check my SQL, I'm not super confident at it yet.

**Review by mkraft — APPROVED** [review]
Looks great! And nice the squirrel migrations.

**Review by BenCookie95 — APPROVED** [review]
Looks great, thanks Cyril!

**Review by furqanmlk — APPROVED** [review]
1. /api/v4/groups?filter_has_member=<member_id>
Output: `[ ]`
2. /api/v4/users?not_in_group=<group_id> 
Result: **only shows user that are in team and channel**
3. /api/v4/users?in_group=<group_id>
Output: `[ ]`
4. /api/v4/groups/<group_id>?include_member_count=false 
Result: **It shows group info**
5. /api/v4/groups/<group_id>/members
Output: `"members": [ ],
"total_member_count": 0`

**Comment by amyblais** [comment]
@cyrilzhang-mm This needs manual cherry-picks to ``release-7.1``, ``release-7.3`` and ``release-7.4`` branches to backport this fix to supported versions.

**Pull request merged**
