### PR TITLE
MM-8839: Adds ChannelType to compliance-related model.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary
Adds `ChannelType` field to the compliance export related model for use in adding some extra headers to the GlobalRelay email.

#### Ticket Link
[MM-8839](https://mattermost.atlassian.net/browse/MM-8839)

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Has enterprise changes: https://github.com/mattermost/enterprise/compare/MM-8840...MM-8839?expand=1

### CODE REVIEW

**Comment by jespino** [comment]
Looks good, but tests are failing.

**Comment by jespino** [comment]
Ok, I re-lanched the tests and now works perfectly (probably it needs enterprise changes too).

**Comment by jasonblais** [comment]
@mkraft Give `MM-8840` branch was merged first, will these changes get properly merged to `master`?

**Comment by mkraft** [comment]
@jasonblais No they won't. I didn't notice that it was merged already based on the Github UI that I saw so I had to re-open a new PR for this and the enterprise PR.

**Pull request merged**
