### PR TITLE
[MM-28985] Remove pointers to slice (part 1)

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR removes all uses of pointer to slice for the following types:

- `model.ChannelList`
- `model.ChannelListWithTeamData`
- `model.ChannelMembers`
- `model.Preferences`
- `model.ProductNotices`

#### Ticket

https://mattermost.atlassian.net/browse/MM-28985

#### Release Note

```release-note
Removed use of pointers to the following types: 
- `model.ChannelList`
- `model.ChannelListWithTeamData`
- `model.ChannelMembers`
- `model.Preferences`
- `model.ProductNotices`
```

#### Related PRs

https://github.com/mattermost/enterprise/pull/1040

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Amazing work!

**Review by isacikgoz — APPROVED** [review]
Nice! the code base its getting better everyday :)

**Comment by streamer45** [comment]
@furqanmlk Again, this touches a lot of structures so there isn't a specific thing to check. I'd be happy to see e2e tests succeed.

**Review by furqanmlk — APPROVED** [review]
E2E test passed
Result: 96.10% passed
https://automation-dashboard.vercel.app/cycles/b86de19a-1a00-4478-ae82-8ba1aa0a4ad0

**Comment by hanzei** [comment]
@streamer45 Does this PR needs to get cherry picked into `cloud`?

**Comment by streamer45** [comment]
> @streamer45 Does this PR needs to get cherry picked into `cloud`?

I think it can wait given it's just a change around code style guidelines.

**Comment by hanzei** [comment]
@streamer45 We want this for v6.0, right? Do you plan to cherry-pick into the 6.0 release branch then?

**Comment by streamer45** [comment]
> @streamer45 We want this for v6.0, right? Do you plan to cherry-pick into the 6.0 release branch then?

Yes, depending on when I get to do it either on cloud or directly into 6.0 release branch.

**Comment by hanzei** [comment]
1/5 that we should use as much soak time as possible to spot issues eary.

**Comment by streamer45** [comment]
Sure, let's see what mattermod thinks about it.

**Comment by streamer45** [comment]
Looks like this is already in cloud :)

**Pull request merged**
