### PR TITLE
JobStore migration

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

Migration of `JobStore` to return plain errors.

Fixes https://github.com/mattermost/mattermost-server/issues/15035

### CODE REVIEW

**Comment by rvillablanca** [comment]
As you review PRs I will go fixing conflicts 👍

**Comment by jasonblais** [comment]
@ogi-m friendly reminder to help with QA review :)

**Comment by rvillablanca** [comment]
Conflicts resolved!

**Comment by rvillablanca** [comment]
I can't see what it is failing here (ee/circleci)

**Comment by agnivade** [comment]
This needs EE changes. I will do them tomorrow.

**Pull request closed without merging**
