### PR TITLE
MM-30836: Feature flag for remote cluster service

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-30836

```release-note
NONE
```

### CODE REVIEW

**Review by nronas — COMMENTED** [review]
Logic wise this looks good to me. But reading the ticket I got a bit confused, do we need just a license check here or an actual feature flag? https://github.com/mattermost/mattermost-server/blob/master/model/feature_flags.go

**Comment by agnivade** [comment]
I think that's a separate thing, which is the new "feature flags" functionality we introduced. This is just about adding a dedicated flag in config.json, which also technically qualifies as a "feature flag".

> So basically we can have SharedChannels disabled with RemoteClusterService enabled since this is a possibility because right now those flags are not mutually exclusive.

I guess so? I'll defer to @wiggin77

**Comment by wiggin77** [comment]
> I think that's a separate thing, which is the new "feature flags" functionality we introduced. This is just about adding a dedicated flag in config.json, which also technically qualifies as a "feature flag".
> 
> > So basically we can have SharedChannels disabled with RemoteClusterService enabled since this is a possibility because right now those flags are not mutually exclusive.
> 
> I guess so? I'll defer to @wiggin77

That is correct.  Remote Cluster Service can be enabled while Shared Channels disabled, however not the other way around.  Other services will share content using Remote Cluster Service hence its has independent flags.

**Review by wiggin77 — APPROVED** [review]
LGTM  :+1:

**Review by nronas — APPROVED** [review]
LGTM

**Comment by wiggin77** [comment]
@agnivade, sorry to drag this PR back up, but I'm wondering if this really added a Feature flag.  I re-read the spec https://docs.google.com/document/d/1B2oOeQsH0TiWObAMbHw_jLOSUjMRNfd3j8Df-2QKkDc/ and apparently feature flags live in the Config.Features struct and are populated externally.  This PR added a config setting, which is good, but not a feature flag.  Of course I could be missing something about how feature flags work.

**Comment by agnivade** [comment]
Yep, it's not a feature flag. That's what I said here https://github.com/mattermost/mattermost-server/pull/16574#issuecomment-747328390. I thought you wanted a dedicated config setting. So is it that you want all sites to have remote cluster service to be on eventually?

**Pull request merged**
