### PR TITLE
MM-38702: Do not fail during importing without attachment

### PR DESCRIPTION
**Pull request by agnivade**
We just log a warning instead of failing completely.

https://mattermost.atlassian.net/browse/MM-38702

```release-note
NONE
```

### CODE REVIEW

**Review by noxer — APPROVED** [review]
LGTM

**Review by isacikgoz — APPROVED** [review]
LGTM, good to go after i18n update like #20799

**Comment by saturninoabril** [comment]
Maybe related to server build which was fixed by https://github.com/mattermost/mattermost-server/pull/20807

**Comment by saturninoabril** [comment]
@phoinixgrr fyi, this failed on `build-docker`. Maybe something to look at by you or your team. TIA.

**Comment by agnivade** [comment]
One of those random failures: `error: Error response from daemon: Get https://registry-1.docker.io/v2/: EOF`. Don't think much can be done about it, except add a retry.

**Comment by phoinixgrr** [comment]
> @phoinixgrr fyi, this failed on `build-docker`. Maybe something to look at by you or your team. TIA.

Hello @saturninoabril. Thanks for reaching out. 

All tests are reported as successful from GitHub 
Could you raise a ticket in our board containing the link to the failed test for us to investigate? 

Feel free to directly raise tickets to [our board](https://mattermost.atlassian.net/jira/software/c/projects/CLD/boards/112) in case support is needed from our team. 

> One of those random failures: error: Error response from daemon: Get https://registry-1.docker.io/v2/: EOF. Don't think much can be done about it, except add a retry.

👌 
This seems like a transient network failure. As Agniva is mentioning, for the majority of these cases, these kind of failures are resolved with a simple retry.

**Comment by agnivade** [comment]
I retried it. This was the original failure: https://app.circleci.com/pipelines/github/mattermost/mattermost-server/36186/workflows/77e6f94e-966d-4dd4-a326-ca7012cef0c3/jobs/305733

**Comment by agnivade** [comment]
Failures are unrelated. Merging.

**Pull request merged**
