### PR TITLE
MM-27454 - Added CWSUrl to Client Config

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Added CWSUrl to the client config to create the url for Cloud contact us.

#### Related PRs:

- Webapp: https://github.com/mattermost/customer-web-server/pull/245
- Redux: https://github.com/mattermost/mattermost-redux/pull/1255

#### Ticket Link
Needed for [MM-27454 - Cloud Contact Us](https://mattermost.atlassian.net/browse/MM-27454)

### CODE REVIEW

**Comment by enahum** [comment]
out of curiosity, is this or anything related to this needed in other clients or is just for the webapp?

**Comment by marianunez** [comment]
> out of curiosity, is this or anything related to this needed in other clients or is just for the webapp?

This is related to cloud subscriptions and billing which is currently only supported in the webapp (mostly on the System Console).

**Review by ali-farooq0 — APPROVED** [review]

**Review by nickmisasi — APPROVED** [review]

**Comment by marianunez** [comment]
Will be tested post-merge as part of https://github.com/mattermost/customer-web-server/pull/245

**Pull request merged**
