### PR TITLE
MM-51795 remove cloud banner

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Removes the cloud free message displayed in Personal Server/Desktop. Displays by default in mono-repo code base.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-51795

```release-note
NONE

```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by mgdelacroix — APPROVED** [review]
LGTM :+1:

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - the Cloud banner has been removed 👍

**Comment by amyblais** [comment]
@sbishel Please cherry-pick to ``cloud`` branch.

**Pull request merged**
