### PR TITLE
Refactor more code to use testutils.WasCalled

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

Use the util function introduced in 8ab0e80b7799ba9fbcc90bbc62a609961143c679 to refactor more instances of such code.

### CODE REVIEW

**Comment by agnivade** [comment]
I agree that it's not abstract enough to be a util function. Will make it an internal function inside config_test.go.

**Comment by lieut-data** [comment]
@lindalumitchell, assigning you, since I'm not sure who should own this. Feel free to redirect :)

**Comment by agnivade** [comment]
Ah wait, there's a bug. The watcher_test.go file is in package config, whereas the other tests use config_test. I need to revert the changes in that file.

**Comment by lindalumitchell** [comment]
Thanks @lieut-data, I swapped in Saturn for this one. :)

**Pull request merged**
