### PR TITLE
MM-15320/MM-15518 When gzipping file responses add header for uncompressed content length

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
This bug appeared with the introduction of gzipping our API responses. The problem boils down to when an HTTP response's body is gzipped, the `Content-Length` header should contain the length of the content after compression. This can cause a problem when setting `Content-Length` to something other than the compressed length resulting in EOF errors if the content is too long or "wrote more than length" errors when too short. To deal with this the library we're using deletes any `Content-Length` headers before writing the response (see https://github.com/nytimes/gziphandler/blob/master/gzip.go#L157).

All this causes our clients a problem because they need the total length of the content uncompressed to display a progress percentage for how much of the file is loaded. The remedy is to use a custom header "X-Uncompressed-Content-Length" that our clients can read as needed.

Web app and RN pull requests will be coming shortly.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-15320
https://mattermost.atlassian.net/browse/MM-15518

### CODE REVIEW

**Comment by crspeller** [comment]
@jwilander I am confused. Why do they need the uncompressed length? Shouldn't download progress be the compressed length?

**Comment by jwilander** [comment]
Nope, apparently the [loaded](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/loaded) property measures the uncompressed content loaded so far. Not exactly sure how that works under the covers but it's definitely the case based on my logging/testing and what I've read (it's not documented particularly well).

**Comment by crspeller** [comment]
Looks like one of those JS things where you think "there must be a better way" and "you would think this has been figured out" but all you get is browser bugs closed as "won't fix".

**Comment by jwilander** [comment]
That definitely ran through my mind more than once while working on this :P

**Comment by hmhealey** [comment]
Ah, HTTP headers 😛

**Pull request merged**
