### PR TITLE
Add Makefile target to update development Docker container configuration

### PR DESCRIPTION
**Pull request by hmhealey**
Currently, the only time Docker containers are updated (like with the new location of `server/build/postgres/postgres.conf` after the monorepo update) is if you recreate the containers from scratch. This should let people update their Docker containers without recreating them from scratch.

I'm also going to add this to the dev docs since, even outside of the monorepo migration, it seems helpful to have around in case more changes are made to the Docker config (like us adding new containers or the user changing their overrides)

#### Related Pull Requests
https://github.com/mattermost/mattermost-developer-documentation/pull/1235

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by wiggin77** [comment]
@hmhealey what is the reason to use `run` instead of `up` for `docker-start`?

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by hmhealey** [comment]
@jespino Would you have a chance to review this sometime soon, or should we re-assign it?

**Review by jwilander — APPROVED** [review]
LGTM

**Pull request merged**
