### PR TITLE
Mm 49463 send invoices annual

### PR DESCRIPTION
**Pull request by Afsoon**
#### Summary

Attach the invoices after upgrading to an annual subscription, as we charge upfront. If we can't attach the invoice, I'm safely sending the email without the file, as we have the CTA as a fallback. 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49463

#### Screenshots

Yearly upgrade email
image

Invoice
image

#### Release Note

```release-note
Send the invoice attached when the admin upgrades to annual subscription
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @Afsoon !

**Review by yasserfaraazkhan — APPROVED** [review]
Had spin wick issues on PR.

Tested it together with Said.
The email notification contains invoice Pdf as expected.

**Comment by amyblais** [comment]
@marianunez Is this needed for Feb 2nd cloud release?

**Comment by marianunez** [comment]
> 

@amyblais not strictly required but a nice to have if we can include it.

**Comment by amyblais** [comment]
If it's not required, it can go to the next release.

**Pull request merged**
