### PR TITLE
[MM 12373] Create CLI command "webhook modify-outgoing"

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
A CLI command has been added to modify an outgoing webhook.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/9668

#### Checklist
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by hanzei** [comment]
Looks like. Do you need help with rebasing your branch?

**Comment by hanzei** [comment]
@migbot That's the best way!

**Comment by grundleborg** [comment]
@lieut-data hope you don't mind, I have switched you in for Jesus as a reviewer for this while he's away.

**Comment by hanzei** [comment]
@lieut-data @grundleborg Can we merge this one?

**Comment by hanzei** [comment]
Thank you very much @migbot for you contribution! :+1: :tada:

**Pull request merged**
