### PR TITLE
[MM-28945] api4/file: add missing return statement

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Add a missing `return` statement in case of an error.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28945

### CODE REVIEW

**Review by streamer45 — COMMENTED** [review]
Nice. I'd also add a test case. A simple HTTP GET after the file has been deleted in `TestGetPublicFile` would have triggered this.

**Review by streamer45 — APPROVED** [review]
:+1:

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by isacikgoz** [comment]
@lindalumitchell This is a fix for unhandled error if user requests deleted files from the server. Automated tests should be sufficient for this.

**Review by lindalumitchell — APPROVED** [review]

**Pull request merged**
