### PR TITLE
MM-35415: ignore 'any' notification setting for CRT reply posts

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Ignore 'Trigger notifications on messages in reply threads that I start or participate in' notification setting for CRT reply posts

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-35415

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by jwilander — APPROVED** [review]
Nice 👍

**Review by ekrem95 — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Comment by esethna** [comment]
@ashishbhate just to verify, this ignores both of these options and only counts direct mentions, DMs or words that trigger mentions toward the mention badge number, correct? 
image

**Comment by esethna** [comment]
@ogi-m can we please prioritize the PR reviews for any server related fixes for CRT? I think the server changes are at the biggest risk given our tight timeline.

**Comment by ashishbhate** [comment]
>@ashishbhate just to verify, this ignores both of these options and only counts direct mentions, DMs or words that trigger mentions toward the mention badge number for any new reply messages, correct?

Correct. The user will NOT get a mention badge simply because he participated in or started a thread.

**Comment by esethna** [comment]
@ogi-m or @jgilliam17 please help with priority reviews so we can get this on daily for the testing session tomorrow

**Review by ogi-m — APPROVED** [review]
Tested and passed
- Both _Trigger notifications on messages in reply threads that I start or participate in_ and
_Trigger notifications on messages in threads that I start_ reply notification settings are successfully ignored
- Only posts with mentions are counted as mention badges when CRT is turned on

**Comment by esethna** [comment]
@ashishbhate can you help resolve the conflict and merge?

**Pull request merged**
