### PR TITLE
[MM-49251] Add day of week field in user table

### PR DESCRIPTION
**Pull request by tanmaydatta**
#### Summary

This PR is for https://github.com/mattermost/mattermost-server/issues/21920
Aim is to make day of week customisable for user. 
Example: If user choses Tuesday, then the week should start from Tuesday.
This PR includes the backend changes. I will raise another PR which will include the FE changes

Screen recording: 

REST: 

https://user-images.githubusercontent.com/5559347/224496957-91e12e7b-bca8-4624-bb2c-d44df7c20619.mov

GraphQL:

https://user-images.githubusercontent.com/5559347/224502824-8bcebd73-f132-4443-b398-f8ff686dcaae.mov

#### Ticket Link

JIRA: https://mattermost.atlassian.net/browse/MM-49251
#### Release Note

```release-note
Add db migration for new column firstdayofweek 

Add first day of week in model.user, graphql and user queries. 
```

### CODE REVIEW

**Comment by tanmaydatta** [comment]
UI changes are in progress https://github.com/mattermost/mattermost-webapp/compare/master...tanmaydatta:mattermost-webapp:MM-49251_day_of_week_migration
Code is complete
Pending unit/e2e tests. This might take some time as this is the first time I will be writing tests for UI. 🙈

**Comment by tanmaydatta** [comment]
UI changes https://github.com/mattermost/mattermost-webapp/pull/12371

**Review by BenCookie95 — COMMENTED** [review]
Thank you for your contribution!

I think we should put this in the props field. I don't think it's worth creating a new column for this. Thoughts @agnivade?

**Comment by tanmaydatta** [comment]
Hi @BenCookie95 
Thank you for your comment.
And yes, you are right! I missed the props field. I will change the code accordingly and update the PR.
Will do this soon.
Thanks

**Comment by tanmaydatta** [comment]
@BenCookie95 I think no changes for the server code are required if we store it in props. So I will soon close this PR
The webapp changes are working with the props changes.
Which can been reviewed here: https://github.com/mattermost/mattermost-webapp/pull/12371

**Comment by agnivade** [comment]
Oh please ignore my comment. I completely missed that Ben already had the same exact thinking as me :P

**Comment by tanmaydatta** [comment]
hi @agnivade 
yes right. I am closing the PR now as no changes are needed if we use props instead of a new column
Already made necessary changes in the webapp
Thanks

**Pull request closed without merging**
