### PR TITLE
MM-21473: Remove unused cluster events

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-21473

```release-note
Removed several cluster events:
- ClusterEventInvalidateCacheForWebhook
- ClusterEventInvalidateCacheForChannelPosts
- ClusterEventInvalidateCacheForChannelMembers
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
:+1:

**Comment by cwarnermm** [comment]
@agnivade - This PR may have API documentation impact. Are you open to review and update the API docs as needed?

**Comment by agnivade** [comment]
Hey @cwarnermm - if you mean the REST API, then there's no impact on that. Only the model package will be affected, and the changes are outlined in the release notes [here](https://github.com/mattermost/mattermost-server/pull/17914#issue-689175749).

**Comment by cwarnermm** [comment]
Thanks, so much, @agnivade! I appreciate the confirmation.

**Pull request merged**
