### PR TITLE
MM-41294: Allow team scheme APIs to be accessed with a professional l…

### PR DESCRIPTION
**Pull request by mkraft**
…icense.

#### Summary

Allowed team scheme APIs to be administered with a Professional license.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41294

#### Related

* https://github.com/mattermost/mattermost-webapp/pull/11597

#### Release Note

```release-note
Allowed team scheme APIs to be administered with a Professional license.
```

### CODE REVIEW

**Comment by mkraft** [comment]
@plant99 @BenCookie95 Gentle ping so that we can hopefully get this into v7.6.

**Review by BenCookie95 — CHANGES_REQUESTED** [review]
Should we add some tests around licences in our existing unit tests?

**Review by plant99 — APPROVED** [review]

**Comment by mkraft** [comment]
> Should we add some tests around licences in our existing unit tests?

Yes. I'll add some. I'll re-request review when they're in.

**Review by BenCookie95 — APPROVED** [review]

**Comment by stevemudie** [comment]
@mkraft This worked as expected over on https://github.com/mattermost/mattermost-webapp/pull/11597 but not on this Spinwick even after upgrading to a Professional plan. 

Am I missing something?

**Comment by mkraft** [comment]
> @mkraft This worked as expected over on [mattermost/mattermost-webapp#11597](https://github.com/mattermost/mattermost-webapp/pull/11597) but not on this Spinwick even after upgrading to a Professional plan.
> 
> Am I missing something?

I believe that if you trigger the test server from the webapp PR it builds using the server branch matching by name. However, if you trigger the test server from the server repository 

> @mkraft This worked as expected over on [mattermost/mattermost-webapp#11597](https://github.com/mattermost/mattermost-webapp/pull/11597) but not on this Spinwick even after upgrading to a Professional plan.
> 
> Am I missing something?

Can you check again? I see it and the APIs work.

**Review by stevemudie — APPROVED** [review]
Working now @mkraft! Not sure what I did or didn't see before. 🤷🏻‍♂️

**Pull request merged**
