### PR TITLE
[MM-40177] Sanitize Teams response when requested with total count

### PR DESCRIPTION
**Pull request by anurag6713**
#### Summary
We are not sanitizing teams when requested for the total count.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40177

#### Release Note
```
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@mkraft @srkgupta This fix will need to be backported.

**Review by srkgupta — APPROVED** [review]
Thanks @anurag6713. Changes LGTM and is working fine. Please re-request my review if there are any changes based on the Dev review comments.

**Review by mkraft — APPROVED** [review]

**Comment by amyblais** [comment]
I will let you know where to cherry-pick this once this is ready to merge.

**Review by wiggin77 — APPROVED** [review]
LGTM 👍

**Review by AGMETEOR — APPROVED** [review]

**Comment by amyblais** [comment]
Needs a manual cherry-pick to ``release-5.37``.

**Comment by amyblais** [comment]
@anurag6713 Needs a manual cherry-pick to ``release-5.37``.

**Comment by amyblais** [comment]
@anurag6713 A kind reminder, please help manually cherry-pick this to ``release-5.37``.

**Comment by anurag6713** [comment]
Doing it ASAP. Thank you.

**Comment by anurag6713** [comment]
It's done, @amyblais 👍

**Comment by amyblais** [comment]
Thank you!

**Pull request merged**
