### PR TITLE
Update Bundled plugin packages for v5.32

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Update Bundled plugin packages for v5.31 based on the list from @aaronrothschild.

The update of AWS SNS failed for unknown reasons, but given that it isn't a popular plugin I think this is fine.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30709

#### Release Note
```release-note
Update bundled plugin packages
```

### CODE REVIEW

**Comment by amyblais** [comment]
@aaronrothschild @catalintomai Can we prioritize reviews ahead of the cloud release next week Tuesday?

**Comment by catalintomai** [comment]
@hanzei, are these new plugin versions the ones being installed/used in the community servers? (just to make sure we are not updating anything that was not exercised to a certain extent).

**Comment by hanzei** [comment]
@catalintomai The community server uses the latest version of each plugin. But from the list of updated plugin Jenkins is the only one that isn't installed there. Keep in mind that is is also true for the existing release.

**Review by catalintomai — APPROVED** [review]

**Review by aaronrothschild — APPROVED** [review]
LGTM

**Comment by amyblais** [comment]
@hanzei Is this critical for v5.30 or can be pushed to the next release?

**Comment by DHaussermann** [comment]
@hanzei I was discussing this with @aaronrothschild today and it seems it would be best if Jira `2.4.0` was the release we send out. The reason for this is that https://github.com/mattermost/mattermost-plugin-jira/issues/694 will not be resolved until Jira `3.0.1`
We would rather have `2.4.0` sent out now and then bump to `3.0.1` for the next server release.

**Comment by hanzei** [comment]
> @hanzei I was discussing this with @aaronrothschild today and it seems it would be best if Jira `2.4.0` was the release we send out. The reason for this is that [mattermost/mattermost-plugin-jira#694](https://github.com/mattermost/mattermost-plugin-jira/issues/694) will not be resolved until Jira `3.0.1`
> We would rather have `2.4.0` sent out now and then bump to `3.0.1` for the next server release.

Thanks for checking with @aaronrothschild :+1: I've downgraded the plugin in https://github.com/mattermost/mattermost-server/pull/16302/commits/8ddebf257d80cb061945a602b5d80c3e6008d58d. PTAL

**Comment by hanzei** [comment]
> @hanzei Is this critical for v5.30 or can be pushed to the next release?

@aaronrothschild What do you think? Is updating the plugins critical?

**Comment by metanerd** [comment]
@aaronrothschild ?

**Comment by aaronrothschild** [comment]
We can push this to next release, it's not critical and we may have 3.0.1 ready by then.

**Comment by amyblais** [comment]
Bumping this from v5.31 for now as this will miss code freeze deadline.

**Comment by hanzei** [comment]
@aaronrothschild This is ready for review

**Review by aaronrothschild — APPROVED** [review]
LGTM

**Review by DHaussermann — APPROVED** [review]
Tested and passed
Created a server from this branch and disabled Remote Marker place
- Confirmed that all pre-packaged plugins are still available to install via Marketplace
- Confirmed all expected version changes have been made
- Confirmed all plugins are installable

LGTM!

**Comment by DHaussermann** [comment]
@hanzei We should still be able to merge this in for 5.32.0 

cc @amyblais today is judgement day and we'd like to get this in.

**Comment by amyblais** [comment]
@DHaussermann Is this PR risky in any way? I just want to make sure we're comfortable taking this in last-minute as QA is wrapping up testing. We could also cherry-pick this separately to v5.32 branch as an exception once that branch has been cut.

**Comment by DHaussermann** [comment]
@amyblais this PR does not technically contain any new plugin functionality. Rather it updates some of the plugins that clients will have available to install on their instance. All the plugins listed have already been released to the Marketplace for other clients and so, there is not much in terms of new risk.   

Also @hanzei correct my understanding her but, When clients upgrade, do the installed plugins upgrade automatically or, will they see the update option so they are made aware of potential breaking changes?

**Comment by hanzei** [comment]
This PR will update all installed plugins automatically.

The changes aren't important for cloud, hence I suggest that we cherry-pick in the v5.32.0 release branch. Would you be fine with that @amyblais?

**Comment by amyblais** [comment]
> The changes aren't important for cloud, hence I suggest that we cherry-pick in the v5.32.0 release branch. Would you be fine with that @amyblais?

Yes, that should work.

**Pull request merged**
