### PR TITLE
MM-27412 Fixing /test command.

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Fixes /test command by using a non-expired session. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27412

### CODE REVIEW

**Comment by lindalumitchell** [comment]
@crspeller I'm still seeing the issue on the test server above. `/test channels 3` or `/test channels 1 3` shows a success message but I don't see any added channels.

**Comment by lindalumitchell** [comment]
Thanks @crspeller. I tried `/test channels 3` again, but now I see a new error (and no channels created):
Screen Shot 2020-08-04 at 5 24 23 PM

**Comment by crspeller** [comment]
@lindalumitchell OK I think it's working now. Retest?

**Comment by lindalumitchell** [comment]
Channels are being created 🎉 but not joined. Checking with CS.

**Pull request merged**
