### PR TITLE
Migrate tests from "model/emoji_search_test.go" to use testify #12423

### PR DESCRIPTION
**Pull request by akantsevoi**
Migrated server tests from using the t.Fatal method calls on their checks to use the testify toolkit in model/emoji_search_test.go

Fixes https://github.com/mattermost/mattermost-server/issues/12423

### CODE REVIEW

**Comment by akantsevoi** [comment]
@cpanato I fixed the 'akantsevoi needs to sign the CLA' issue. How can I trigger the rebuild action without fake push?

**Comment by akantsevoi** [comment]
@ali-farooq0 could you help me with that message from build system?
Clean checkout step is failed
"Couldn't find any revision to build. Verify the repository and branch configuration for this job."
What does it mean?

**Comment by jespino** [comment]
No QA needed for this PR, only changes unit tests.

**Pull request merged**
