### PR TITLE
MM-48345: Fix Critical level logging

### PR DESCRIPTION
**Pull request by agnivade**
Critical wasn't added in the StdLevels slice
and due to that mlog.Critical wasn't printing anything.
This was a complete blindspot that was missed.

We have removed all references to mlog.Critical in the codebase
and pointed Critical to be Fatal in the library.

In v8, we will remove Critical altogether.

```release-note
Servers with an encrypted key will throw an error
during startup now.
```

### CODE REVIEW

**Review by noxer — APPROVED** [review]
Good catch!

**Review by isacikgoz — APPROVED** [review]
Thanks!

**Comment by agnivade** [comment]
@amyblais - This will be good to backport to 7.7

**Pull request merged**
