### PR TITLE
[MM-51789] - Markdown in channel description at communication start not rendered

### PR DESCRIPTION
**Pull request by gitstart**
### Summary
Markdown in channel description at communication start not rendered

### Before
Screen Shot 2023-03-31 at 10 51 57

### After
Screen Shot 2023-03-30 at 13 59 42

**Summary**
MWAOSS-56 - Markdown in channel description at communication start not rendered 

**Ticket Link**

https://mattermost.atlassian.net/browse/MM-51789.

#### Release note
```release-note
Resolves Markdown in channel description at communication start not rendered
```

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Review by hmhealey — APPROVED** [review]
Looks good to me!

**Pull request closed without merging**
