### PR TITLE
MM-40817: Use license interface in Channels

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-40817

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
Always 👍 when we see `--- > +++`

**Comment by agnivade** [comment]
@saturninoabril - mind giving the results a quick glance? :)

**Comment by agnivade** [comment]
Gentle ping on this @saturninoabril

**Comment by jgilliam17** [comment]
Thanks @agnivade 
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/167587-1311c99-onprem-ent-server-pr-19678-mattermost/mm-ee-test1311c99/mochawesome.html) looks good, no PR related failures when compared to [master](https://mattermost-cypress-report.s3.amazonaws.com/168083-onprem-ent-master-mm-ee-test:test/mochawesome.html)

**Pull request merged**
