### PR TITLE
Remove model.AppError from store/storetest package

### LINKED ISSUE #16419: Remove model.AppError from store/storetest package
We are in the process of removing `model.AppError` completely from the `store` package. We have removed it from the `sqlstore` package, but there are still a couple left in some other packages under `store`.

This ticket is about removing `model.AppError` from the storetest package.

These are some remnants remaining from the AppError migration. We need to remove all the `model.AppError` occurences and change any code that's needed for the tests to still pass.

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

### PR DESCRIPTION
**Pull request by msal4**
#### Summary

In this pull request, I removed `AppError` and their checks. I found many occurrences of 'model.AppError' in the `model` package that all of the `storetest` package `AppError` checks depend on but I didn't touch them for fear that they might be out of the scope of this issue. But if they aren't I'd love to do so as I wouldn't have to remove the `AppError` type checks in the `storetest` package, just modify them a bit if needed.

#### Ticket Link

Fixes #16419

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
These don't seem redundant to me. These are coming from the model.AppError in the model package. And we should keep them.

The objective of the ticket was to remove any references to model.AppError which are now migrated to `error`s. If there aren't anything like that, then I think we can close the issue.

**Comment by msal4** [comment]
Yeah these are the only references to `model.AppError` in the `storetest` package

**Comment by agnivade** [comment]
Thanks. Then I don't think there is anything to be done here.

**Pull request closed without merging**
