### PR TITLE
MM-28103: prepackage incident-response

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package and auto-enable incident response so that Cloud customers get this installed by default. This is Phase 0 of the outline planned in https://docs.google.com/document/d/1f2ZKOTNOX-TLPDBDNXAq4M5U5V9E_C9UkJwfKanQq8Q/edit# that will later see us deprecate this approach for explicit support to pin plugins in Cloud instances.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28103

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
:tada:

**Comment by prapti** [comment]
@lieut-data Quick question: are we allowing the prepackaged install of the plugin in all TE, E10 and E20 editions?

**Comment by lieut-data** [comment]
@prapti, yes: for all intents and purposes, the prepackaged plugin will be installed in all those editions. We're not likely to ship this "as-is" in v5.28, but will make refinements to the experience for on-premise. This is primarily to ship to Cloud from `master` where everything is >= `E20`.

**Review by prapti — APPROVED** [review]
Thank you for verifying that @lieut-data!
It looks great. Tests passed in E10, E20, TE cloud servers and local instance. Didn't see anything worth noting. The plugin worked as expected:

- prepackaged plugin installed by default in fresh server installations
- plugin is enabled by default
- continues to work as expected upon server upgrades
- disabled plugin does not show upon server restart (same behavior as the NPS plugin).

Approving to merge.

**Comment by lieut-data** [comment]
Awesome, thanks @prapti! And apologies for forgetting to assign you :(

**Pull request merged**
