### PR TITLE
[MM-37726] -  Self-managed: Update email template to new branding - Invitation email

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR adjusts the image width in the invitation email template from 320px to 246px

#### Ticket Link
[MM-37726](https://mattermost.atlassian.net/browse/MM-37726)

#### Related Pull Requests
Has server changes (https://github.com/mattermost/mattermost-server/pull/18136)

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]
LGTM!

**Comment by marianunez** [comment]
@AGMETEOR don't forget to cherry-pick this and all other email changes to `cloud`

**Pull request merged**
