### PR TITLE
Test Renewal: V7.5 release

### PR DESCRIPTION
**Pull request by yasserfaraazkhan**
A test branch created from release-7.5 branch.

```release-note
None
```

### CODE REVIEW

**Review by marianunez — COMMENTED** [review]
@yasserfaraazkhan let me know if you need any help in getting a license about to expire

**Comment by marianunez** [comment]
> Mattermost test server with CWS created! 🎉
> 
> Access here: https://mattermost-server-pr-21626.test.mattermost.cloud
> 
> Account Type	Username	Password
> Admin	[user-mattermost-server-pr-21626@example.mattermost.com](mailto:user-mattermost-server-pr-21626@example.mattermost.com)	Cws@10102020

You probably need to setup the regular test server so you are able to see the license page and upload license

**Comment by yasserfaraazkhan** [comment]
> @yasserfaraazkhan let me know if you need any help in getting a license about to expire

Hi @marianunez , can you help me with an early expiring license?

**Comment by yasserfaraazkhan** [comment]
closing this PR as we were able to confirm the changes are working as expected 
https://mattermost.atlassian.net/browse/MM-47045

**Pull request closed without merging**
