### PR TITLE
Bump minimum Go version required

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

After the auto-vendoring change, minimum Go version
required is 1.14.

### CODE REVIEW

**Comment by grundleborg** [comment]
@agnivade have you announced this requirements bump? At least an @all in the Developers channel to make sure people are aware they will need to upgrade?

**Comment by agnivade** [comment]
I indeed have. :) https://community-daily.mattermost.com/core/channels/developers/7unudpr49pgsjx61apxutw4wsr

**Comment by reflog** [comment]
@agnivade https://developers.mattermost.com/contribute/server/developer-setup/ still tells users to install 1.13 , so I think that should be addressed first

**Comment by agnivade** [comment]
Done: https://github.com/mattermost/mattermost-developer-documentation/pull/590.

**Comment by agnivade** [comment]
@lindy65 - This is a tiny one and doesn't warrant any QA. That's why I didn't bother to file a ticket. Thanks.

**Pull request merged**
