### PR TITLE
[MM-25647][MM-25659] Add missed config settings to telemetry

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Add `EnableAPIChannelDeletion` and `EnableAPIUserDeletion` to telemetry.

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-25647 
- https://mattermost.atlassian.net/browse/MM-25659

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by wiggin77 — APPROVED** [review]

**Comment by ashishbhate** [comment]
@ogi-m this PR just adds some config values to diagnostics/telemetry. Nothing to test here.

**Comment by amyblais** [comment]
@ogi-m Kind reminder to review this for v5.28.

**Review by ogi-m — APPROVED** [review]
Thanks @ashishbhate! Approved.

**Comment by justinegeffen** [comment]
This is addressed in: https://github.com/mattermost/mattermost-server/pull/15202.

**Pull request merged**
