### PR TITLE
uncomment upgrade for 5.5.0

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
uncomment upgrade to 5.5.0

will cherry pick this to the release branch 5.5.0

### CODE REVIEW

**Comment by grundleborg** [comment]
I might be confused, but shouldn't this stay commented until *after* we release 5.5?

**Comment by cpanato** [comment]
we have the release 5.5 in place should this go only for that branch? i'm confused as well

**Comment by grundleborg** [comment]
I *think* that once this PR is merged, no further schema changes can be made for v5.5 (as it will stop running them). So probably this should go to *both* branches but not until there are definitely no more schema changes for 5.5?

**Comment by cpanato** [comment]
@grundleborg makes sense.
will close this one

**Comment by jwilander** [comment]
I think we also want to move the upgrade in this code to 5.6

**Pull request closed without merging**
