### PR TITLE
update test public key

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Update test license public key and accompanying CWS url config values. To be merged on April 17, as the start of the planned migration for test workspaces to use test licenses.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50177

```release-note
NONE
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]

**Review by marianunez — APPROVED** [review]

**Comment by saturninoabril** [comment]
@yasserfaraazkhan I went ahead and updated the test licenses in the pipeline, and ran [e2e-server-pr-test-license](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/commits/e2e-server-pr-test-license) against this PR. All good with [onprem](https://automation-dashboard.vercel.app/cycles/2f5cbfe1-9f2c-4741-ae4d-2e17091128ba) but not with [cloud](https://automation-dashboard.vercel.app/cycles/12f94035-1bfd-452c-b2a8-721b9afb05d9). Could you help investigate? Would be great to fix before merging this PR. TIA.

**Comment by saturninoabril** [comment]
@yasserfaraazkhan @neallred Just an update, on my local verification with `mattermostdevelopment/mm-ee-test:e4b16f4`, the license files at `/test` folder were returning "Invalid license file" error while those at `/prod` folder worked fine. I'm actually confused since I thought the test license are the ones to be used for `mm-ee-test` build. Please help check and clarify.

**Comment by neallred** [comment]
@saturninoabril good catch! We needed a small tweak of how mm-ee-test gets built and pushed to `mattermostdevelopment` docker org. I have a [PR](https://github.com/mattermost/enterprise/pull/1438) for that tweak, was able to rebuild against it (`mattermostdevelopment/mm-ee-test:ad04376` image), and verified that reruns of the [on prem](https://mattermost-cypress-report.s3.amazonaws.com/329904-ad04376-pr-onprem-ent-server-pr-22835-mm-ee-test:ad04376/mochawesome.html) and [cloud pipelines](https://mattermost-cypress-report.s3.amazonaws.com/329903-ad04376-pr-cloud-ent-server-pr-22835-mm-ee-test:ad04376/mochawesome.html) targeting this branch now succeed with as many tests as pass on the automatic daily e2e runs of [on prem](https://mattermost-cypress-report.s3.amazonaws.com/329580-3b45671-daily-onprem-ent-master-mm-ee-test:test/mochawesome.html) and [cloud](https://mattermost-cypress-report.s3.amazonaws.com/329577-3b45671-daily-cloud-ent-master-mm-ee-test:test/mochawesome.html).

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
