### PR TITLE
[Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-08-16

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Merge master into cloud branch for cloud release

Please let me know if you want any specific PRs to include this release cc @hanzei @streamer45 @agnivade.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hanzei** [comment]
@isacikgoz https://github.com/mattermost/mattermost-server/pull/18128 should also go in there.

**Review by jwilander — APPROVED** [review]

**Review by streamer45 — COMMENTED** [review]
Looks good although store migration code is incomplete since some PRs are still waiting to get merged (https://github.com/mattermost/mattermost-server/pull/17923 and https://github.com/mattermost/mattermost-server/pull/18078). I think we should consider including them. If not, I'll cherry-pick them later on.

**Comment by isacikgoz** [comment]
@amyblais we want to inlcude the 2 PRs @streamer45 mentioned, what do you think about holding this until they got merged?

**Comment by amyblais** [comment]
@isacikgoz https://github.com/mattermost/mattermost-server/pull/17923 was merged and can be included, the other one can be cherry-picked to the cloud branch later.

**Comment by amyblais** [comment]
@isacikgoz @streamer45 Although I'm not sure if we want to include https://github.com/mattermost/mattermost-server/pull/17923 in v6.0 as-is, since it's causing long migration time?

**Comment by streamer45** [comment]
> @isacikgoz @streamer45 Although I'm not sure if we want to include #17923 in v6.0 as-is, since it's causing long migration time?

My recommendation would be to include them, as planned. Long migration times are expected and not nothing unusual (we had something similar in 5.35). This is a major version release so I believe it's expected for the process to take longer than usual. Moreover, we will provide options for users/customers to potentially run part of the migrations ahead of time (e.g. off business ours).

**Comment by amyblais** [comment]
@streamer45 Kind note to prioritize this PR review.

**Review by streamer45 — APPROVED** [review]

**Pull request merged**
