### PR TITLE
MM-23221: Fix getAllTeams handler returning null

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

When the user doesn't have either of list_private_teams
or list_public_teams, then the code falls through and tries
to marshal a nil pointer, which generates "null".

Upon receiving null, the webapp fails to update it's UI and
the spinner still keeps spinning.

To fix this, we check for the permissions, and if it does not
exist, return an appropriate status code.

The test did not catch it because it never tested for no permissions
with WithCount enabled. If you test that, the client code immediately
crashes because the json unmarshalling fails. Returning an appropriate
error fixes that too.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-23221

### CODE REVIEW

**Comment by agnivade** [comment]
@wiersgallak - Any chance you could review the error message ?

**Comment by wiersgallak** [comment]
@agnivade Recommend following format of other permission errors: ```You don't have the appropriate permissions to list all teams.```

**Comment by agnivade** [comment]
Ah alright, I did see one of this. That's what I followed.

```
{
    "id": "api.command_invite.permission.app_error",
    "translation": "You don't have enough permissions to add {{.User}} in {{.Channel}}."
  },
```

Changing it now.

**Comment by agnivade** [comment]
@wiersgallak - PTAL.

**Pull request merged**
