### PR TITLE
fix a typo in the mysql/000010_create_group_channels.up.sql

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Fixes a typo in the script file

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
I thought we weren't supposed to touch the original files anymore?

**Comment by isacikgoz** [comment]
> I thought we weren't supposed to touch the original files anymore?

This isn't shipped yet so I think we are good to edit this.

**Review by agnivade — APPROVED** [review]
Sounds good. cc @amyblais for cherry-pick to 6.4. Do we also need to check community, or since it's an older migration, we expect community to be fine?

**Comment by isacikgoz** [comment]
/update-branch 

Community would be fine like you said; This was a fairly old migration, to be specific it was on `5.20`.

**Comment by amyblais** [comment]
@isacikgoz @agnivade Do you have more details on why this is urgent for v6.4? What functionality does it affect? (I'm about to cut Final for v6.4 this morning)

**Comment by isacikgoz** [comment]
@amyblais This will effect if a customer tries to upgrade to `v6.4` from a version below `5.20`. It will create a column with an incorrect name hence it will prevent app to run properly.

**Comment by amyblais** [comment]
@isacikgoz Is this ready to merge? Does it need additional testing / reviews?

**Comment by isacikgoz** [comment]
Yes, it's ready to merge. Just a small typo in the column name. I don't think further testing is required on this.

**Pull request merged**
