### PR TITLE
MM-44236 Update server dependencies

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
This PR updates the server dependencies and -- to prevent a build pipeline crash -- updates `golangli-lint` to version 1.46.2.
Subsequently there were some linter issues to be fixed but mostly simple optimizations.

#### Ticket Link
[MM-44236](https://mattermost.atlassian.net/browse/MM-44236)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Hmm, I thought we decided to wait on this till I fix the dyatlov issue? Did you update each dependency manually?

In any case, seems like there is an issue with the split-commons library:

```
# github.com/splitio/go-split-commons/v4/synchronizer
/go/pkg/mod/github.com/splitio/go-split-commons/v4@v4.0.5/synchronizer/manager.go:80:21: not enough arguments in call to backoff.New
	have ()
	want (int64, time.Duration)
```

in the ee pipeline.

**Comment by noxer** [comment]
When I reverted the dyatlov dependency, the tests seemed to be working, so I prepared all the other changes. I agree that we should delay merging it until that dependency issue is fixed (#20443 is merged).

Enterprise seems to be using version 4 of github.com/splitio/go-split-commons while mattermost-server seems to be using v3. Maybe thats the issue? I'll investigate further.

**Comment by agnivade** [comment]
> I agree that we should delay merging it until that dependency issue is fixed (https://github.com/mattermost/mattermost-server/pull/20443 is merged).

Sounds good.

**Comment by isacikgoz** [comment]
@noxer I merged #20443 feel free to hit ready for review button once you resolve the conflicts :)

**Review by agnivade — APPROVED** [review]
Finally :)

**Pull request merged**
