### PR TITLE
fix: e2e tests

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- fixed flaky E2E tests

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by furqanmlk — APPROVED** [review]
Thanks, @saturninoabril 
a big chunk of tests fixed 🎉

**Comment by furqanmlk** [comment]
e2e-test

**Comment by furqanmlk** [comment]
Hi @saturninoabril,  I have fixed and pushed some test cases as changes were related.

**Comment by saturninoabril** [comment]
Thanks @furqanmlk! I'm merging now.

**Comment by agnivade** [comment]
Testing cp functionality. Please ignore.

/cherry-pick cloud

**Pull request merged**
