### PR TITLE
Update prepackaged boards to v7.2.0

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update prepackaged boards version to v7.2.0

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/2546

#### Release Note
```release-note
 Update prepackaged boards version to v7.2.0
```

### CODE REVIEW

**Comment by sbishel** [comment]
Waiting for final Boards release to merge.

**Review by harshilsharma63 — APPROVED** [review]

**Review by mgdelacroix — APPROVED** [review]

**Pull request merged**
