### PR TITLE
[MM-47145] My Insights license change

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Moving my insights to free tier 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47145

#### Release Note

```release-note
Adding my insights to free tier
```

### CODE REVIEW

**Comment by BenCookie95** [comment]
Waiting for https://github.com/mattermost/mattermost-server/pull/21441/files before removing WIP labels

cc/ @plant99

**Review by plant99 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]

**Comment by BenCookie95** [comment]
@laneycs Just to confirm before I merge, these are the different copies we have:

**Pre trial**
admin-upgrade-modal

**During trial**
admin-during-trial

**Finished trial**
admin-after-trial

**Comment by laneycs** [comment]
@BenCookie95 Looks good to me!

**Pull request merged**
