### PR TITLE
[MM-51284] - Correctly check for mobile view in product menu list

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
The mobile menu check had a delay as it wasn't taking into account the current state when resize was happening after render. This was causing some items to disappear from the admin menu after the browser was back to its original size. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51284

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]
lgtm, just the lint error

**Review by AshishDhama — APPROVED** [review]

**Comment by nevyangelova** [comment]
cc @stevemudie

**Review by stevemudie — APPROVED** [review]
Worked as expected. Looks good @nevyangelova!

**Pull request merged**
