### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [mattermost-languages-shipped/mattermost-server-monorepo](https://translate.mattermost.com/projects/mattermost/mattermost-server-monorepo/).

It also includes following components:

* [mattermost-languages-shipped/mattermost-boards-webapp-monorepo](https://translate.mattermost.com/projects/mattermost/mattermost-boards-webapp-monorepo/)

* [mattermost-languages-shipped/mattermost-playbooks-webapp-monorepo](https://translate.mattermost.com/projects/mattermost/mattermost-playbooks-webapp-monorepo/)

* [mattermost-languages-shipped/mattermost-webapp-monorepo](https://translate.mattermost.com/projects/mattermost/webapp-monorepo/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by Willyfrog** [comment]
Thanks @metanerd and @harshilsharma63 💙

**Comment by Willyfrog** [comment]
seems like mattermost is not making the merge. Doing it manually

**Pull request merged**
