### PR TITLE
Enables PostPriority FeatureFlag by default

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Enables PostPriority FeatureFlag by default

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47018

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by esethna** [comment]
Adding back to the v7.6 milestone, but let's not merge until the features have soaked on community and cloud

**Review by marianunez — APPROVED** [review]
I don't have context of the actual Post Priority feature on what should be default but the code change here to turn on by default for on-prem, LGTM

**Comment by amyblais** [comment]
@koox00 The CI is failing here and it seems that ``/update-branch`` needs to be done manually.

**Comment by amyblais** [comment]
@koox00 The CI in this PR is hanging so the auto-merge label doesn't seem to work.

**Comment by koox00** [comment]
@amyblais I think I had to update my fork of focalboard for ee/circleci to pass, I think it will pass now.

**Pull request merged**
