### PR TITLE
MM-52613: Add icons to "Add channels" LHS menu

### PR DESCRIPTION
**Pull request by esethna**
https://mattermost.atlassian.net/browse/MM-52613

Release note:
```release-note
NONE
```

### CODE REVIEW

**Comment by pvev** [comment]
@esethna the color of the icons is not consistent with the other icons menus color and there are some unit test failing. Besides that, LGTM!

Screenshot 2023-05-02 at 18 08 47
Screenshot 2023-05-02 at 18 10 07

**Comment by esethna** [comment]
@pvev thanks, good catch! It looks like the color of the menu icons and text overall is different when compared to the + menu, perhaps that can be filed as a separate ticket unless there's a quick fix you can guide me to?

**Comment by pvev** [comment]
> @pvev thanks, good catch! It looks like the color of the menu icons and text overall is different when compared to the + menu, perhaps that can be filed as a separate ticket unless there's a quick fix you can guide me to?
> 
> I updated the test snapshot

sure @esethna  just place:

```
        .MenuItem button span {
            color: rgba(var(--center-channel-color-rgb), 0.72);
        }
```

 in the file:
`channels/src/sass/layout/_sidebar-left.scss`

line 746

From this:
Screenshot 2023-05-02 at 18 42 11

To this:
Screenshot 2023-05-02 at 18 41 59

Will result as:

Screenshot 2023-05-02 at 18 42 53

**Comment by pvev** [comment]
@esethna heads up that I updated the style above, not sure if you already tried the first version which is 5 min old :)

**Review by pvev — APPROVED** [review]
LGTM! thanks @esethna!

**Review by marianunez — APPROVED** [review]

**Review by stevemudie — APPROVED** [review]
Looks good @esethna!

**Pull request merged**
