### PR TITLE
[MM-44948] Update sync

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR will update sync. 

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-44948

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by jupenur — COMMENTED** [review]
This is a good approach I think -- doing it all in one place right before sending. But now the invocations in `fetchPostUsersForSync` are unnecessary and should be removed.

**Review by jupenur — APPROVED** [review]
Tested in a custom AWS deployment and seems to work as intended. Thanks Shota!

**Comment by furqanmlk** [comment]
> > Juho asked me to setup Custom Network logging in order to see the specific log.
> 
> 
> 
> @furqanmlk I think you'll need help from Cloud team to set up capture of network on a cloud instance.  Not sure if this is basic packet capture or something that can be done at the container level.  

Thanks @wiggin77 
How can I setup capture of network locally?

**Comment by wiggin77** [comment]
> Thanks @wiggin77
> How can I setup capture of network locally?

I don't know.  You'll have to reach out to cloud team for that.

**Pull request merged**
