### PR TITLE
[MM-49486]: Option to exclude file count in channel stats

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary

- Added a `exclude_files_count` param to exclude file counts from channel stats API. Returns -1 if file counts have been excluded. This is to differentiate between a zero files count, and excluded files count.
- cherry-pick https://github.com/mattermost/mattermost-server/pull/22096 

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-49486

#### Release Note

```release-note
Added a `exclude_files_count` parameter to exclude file counts from channel stats API
```

### CODE REVIEW

**Review by amyblais — APPROVED** [review]

**Comment by amyblais** [comment]
@AshishDhama Is this good to merge?

**Comment by AshishDhama** [comment]
I have fixed the issue causing the CircleCI here https://github.com/mattermost/mattermost-webapp/pull/12366

**Comment by AshishDhama** [comment]
@amyblais Build is passing now. Should I merge it?

**Comment by amyblais** [comment]
Yes, feel free to merge it.

**Pull request merged**
