### PR TITLE
Pre-package Channel Export plugin v1.0.0

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary

Pre-package Channel Export plugin v1.0.0

#### Ticket Link
--

#### Release Note

```release-note
Pre-packaged Channel Export v1.0.0
```

### CODE REVIEW

**Comment by agarciamontoro** [comment]
Looks like everything is working as expected:
image

- Correct version is installed.
- Public and private channels can be exported by sysadmins and regular users.

**Review by hanzei — APPROVED** [review]

**Review by lieut-data — APPROVED** [review]

**Comment by amyblais** [comment]
@lieut-data Is this needed for cloud?

**Comment by lieut-data** [comment]
@amyblais, yes, in that we'll want it for the 6.0 release on the 13th.

**Pull request merged**
