### PR TITLE
[MM-30136] - [GH-16253]  Issuing /dnd consecutively should not toggle the user status between …

### PR DESCRIPTION
**Pull request by OgmaJ**
#### Summary

/dnd will only do a do not disturb 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/16253
JIRA https://mattermost.atlassian.net/browse/MM-30136

#### Release Note
```release-note
 /dnd command will ONLY set a do not disturb status whatever the  current user status is 
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR!

Since we're no longer going to use the `api.command_dnd.error` and `api.command_dnd.disabled` translation strings, could you remove those from `i18n/en.json`? The translation system will automatically remove them for the rest of the languages.

**Comment by OgmaJ** [comment]
@hmhealey  : removing is done on i18n/en.json

**Review by hmhealey — APPROVED** [review]
Thanks! Hopefully that should get the build issues working since I think they were just temporary

**Review by ashishbhate — APPROVED** [review]

**Review by lindalumitchell — APPROVED** [review]
LGTM.

**Pull request merged**
