### PR TITLE
MM-34792 test shouldn't depend on upgrade sequence

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

Upgrade test was relying on specific migration version. Extracted the function under test to make it pass on future versions.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34792
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
:+1:

**Review by agnivade — APPROVED** [review]

**Comment by amyblais** [comment]
@reflog Can you help confirm again if this is needed for the next cloud release or only for master?

**Comment by ethervoid** [comment]
This should've been ported to the cloud branch as well. Fixing the conflicts

**Comment by amyblais** [comment]
@ethervoid If this should have been backported to cloud earlier, do you know if this needs to be cherry-picked to release-5.35 branch as well? 

PRs for v5.35 database upgrade were here: https://github.com/mattermost/mattermost-server/pull/17488, https://github.com/mattermost/mattermost-server/pull/17500

**Comment by ethervoid** [comment]
@amyblais this fix is already in 5.34 so no need :)

**Pull request merged**
