### PR TITLE
MM-23824 Clean up orphaned plugin process at test completion

### PR DESCRIPTION
**Pull request by gigawhitlocks**
#### Summary
@lieut-data noticed that calling `make test-server` was leaking a process on Linux systems. I confirmed this on my system and narrowed it down to the following test:
```
~/g/s/g/m/m/plugin » go test -run TestPluginHealthCheck  -v 
=== RUN   TestPluginHealthCheck
=== RUN   TestPluginHealthCheck/PluginHealthCheck_Success
=== RUN   TestPluginHealthCheck/PluginHealthCheck_Panic
{"level":"error","ts":1585953191.9874697,"caller":"mlog/log.go:175","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"foo","error":"unexpected EOF"}
{"level":"debug","msg":"Error pinging plugin","fields":[{"Key":"error","Type":25,"Integer":0,"String":"","Interface":{}}]}
--- PASS: TestPluginHealthCheck (3.14s)
    --- PASS: TestPluginHealthCheck/PluginHealthCheck_Success (1.53s)
    --- PASS: TestPluginHealthCheck/PluginHealthCheck_Panic (1.61s)
PASS
ok  	github.com/mattermost/mattermost-server/v5/plugin	3.146s
~/g/s/g/m/m/plugin » ps aux | grep backend.exe
ian      1395574  0.0  0.0 1235816 12832 pts/3   Sl   17:33   0:00 /tmp/234439674/backend.exe
ian      1396214  0.0  0.0 216120   892 pts/3    S+   17:33   0:00 grep --color=auto backend.exe
```

This PR resolves this bug by calling `Shutdown()` on the plugin supervisor at the end of the test. The process no longer leaks:
```
~/g/s/g/m/m/plugin » go test -run TestPluginHealthCheck  -v 
=== RUN   TestPluginHealthCheck
=== RUN   TestPluginHealthCheck/PluginHealthCheck_Success
=== RUN   TestPluginHealthCheck/PluginHealthCheck_Panic
{"level":"error","ts":1585953209.2415524,"caller":"mlog/log.go:175","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"foo","error":"unexpected EOF"}
{"level":"debug","msg":"Error pinging plugin","fields":[{"Key":"error","Type":25,"Integer":0,"String":"","Interface":{}}]}
--- PASS: TestPluginHealthCheck (3.56s)
    --- PASS: TestPluginHealthCheck/PluginHealthCheck_Success (1.85s)
    --- PASS: TestPluginHealthCheck/PluginHealthCheck_Panic (1.71s)
PASS
ok  	github.com/mattermost/mattermost-server/v5/plugin	3.564s
~/g/s/g/m/m/plugin » ps aux | grep backend.exe 
ian      1418211  0.0  0.0 216120   840 pts/3    S+   17:33   0:00 grep --color=auto backend.exe
```

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-23824

### CODE REVIEW

**Comment by mickmister** [comment]
Looks like there's another call to `newSupervisor` in the next test. @gigawhitlocks Can you please apply the same `Shutdown()` fix there, even if it's just for consistency?

**Comment by gigawhitlocks** [comment]
Yes @mickmister I can do that, but do be aware it will be a no-op because in the other test, the plugin panics (as expected) so it doesn't need to be stopped.

**Comment by mickmister** [comment]
Anyway QA can verify the fix, or does dev review suffice in this case?

**Comment by gigawhitlocks** [comment]
I don't know the answer to that question; this is my first PR in this repository :)

**Comment by prapti** [comment]
@gigawhitlocks A couple questions to test this PR: Do I need to verify this in a Linux env or will my mac work just as well? Can I test this with any plugin? Am I verifying that once `make test-server` completes, `ps aux | grep backend.exe` should only show me only one process still running?
If I'm missing anything, please feel free to update the test steps in [the Jira ticket](https://mattermost.atlassian.net/browse/MM-23824). Thank you!

**Pull request merged**
