### PR TITLE
Update Dockerfile to 1.18.1

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary
Update dockerfile to 1.18.1

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@amyblais - This needs to be backported to 6.7. It was a gap that we missed while doing the knowledge transfer from Carlos.

**Review by spirosoik — APPROVED** [review]
thanks Agniva

**Review by phoinixgrr — CHANGES_REQUESTED** [review]
I seem to get a different digest than the one committed here. is this expected? 
```
docker images --digests | grep golang
golang                                     1.18.1        sha256:12d3995156cb0dcdbb9d3edb5827e4e8e1bf5bf92436bfd12d696ec997001a9a   27959cb699fc   2 weeks ago    818MB
```

**Comment by agnivade** [comment]
This is the one which @pfltdv gave me during the initial 1.18 change. 

```
mustafa@mustafa-mattermost:/srv/gitlab/mattermost-build-server$ docker pull golang:1.18.1
1.18.1: Pulling from library/golang
Digest: sha256:3f0168c019343d7cc07bf2481e7b6555fbf2ebadfb01f9e77875da66439ba041
Status: Downloaded newer image for golang:1.18.1
docker.io/library/golang:1.18.1
mustafa@mustafa-mattermost:/srv/gitlab/mattermost-build-server$ docker inspect --format='{{.RepoDigests}}' docker.io/library/golang:1.18.1
[golang@sha256:3f0168c019343d7cc07bf2481e7b6555fbf2ebadfb01f9e77875da66439ba041 golang@sha256:ee752bc53c628ff789bacefb714cff721701042ffa9eb736f7b2ed4e9f2bdab6]
```

**Comment by pfltdv** [comment]
@phoinixgrr @agnivade Looks like we have an updated image for golang now. 

```
mmm:~> docker pull golang:1.18.1
1.18.1: Pulling from library/golang
6aefca2dc61d: Pull complete 
967757d56527: Pull complete 
c357e2c68cb3: Pull complete 
c766e27afb21: Pull complete 
d6a8ea6bd5f8: Pull complete 
13a9b904f742: Pull complete 
3447e3508f49: Pull complete 
Digest: sha256:12d3995156cb0dcdbb9d3edb5827e4e8e1bf5bf92436bfd12d696ec997001a9a
Status: Downloaded newer image for golang:1.18.1
docker.io/library/golang:1.18.1
mmm:~> docker images --digests
REPOSITORY                                 TAG                            DIGEST                                                                    IMAGE ID       CREATED       SIZE
mattermost/mattermost-enterprise-edition   <none>                         sha256:90cce607ffa0f1453c77b386675a5265a2fa93663c794820866286c82149f107   96f7e29f7f47   6 days ago    532MB
test                                       latest                         <none>                                                                    4d9b0fb269b4   6 days ago    383MB
<none>                                     <none>                         <none>                                                                    346d78d10220   6 days ago    5.57MB
ubuntu                                     latest                         sha256:2a7dffab37165e8b4f206f61cfd984f8bb279843b070217f6ad310c9c31c9c7c   3f4714ee068a   13 days ago   77.8MB
ubuntu                                     focal                          sha256:115822d64890aae5cde3c1e85ace4cc97308bb1fd884dac62f4db0a16dbddb36   1a437e363abf   13 days ago   72.8MB
golang                                     1.18.1                         sha256:12d3995156cb0dcdbb9d3edb5827e4e8e1bf5bf92436bfd12d696ec997001a9a   65375c930b21   2 weeks ago   964MB
alpine                                     <none>                         sha256:a777c9c66ba177ccfea23f2a216ff6721e78a662cd17019488c417135299cd89   0ac33e5f5afa   4 weeks ago   5.57MB
golangci/golangci-lint                     v1.45.2                        sha256:e84b639c061c8888be91939c78dae9b1525359954e405ab0d9868a46861bd21b   94f49b27b197   5 weeks ago   987MB
minio/minio                                RELEASE.2019-10-11T00-38-09Z   sha256:0d02f16a1662653f9b961211b21ed7de04bf04492f44c2b7594bacbfcc519eb5   22703664b877   2 years ago   51MB
mmm:~>  docker inspect --format='{{.RepoDigests}}' docker.io/library/golang:1.18.1
[golang@sha256:12d3995156cb0dcdbb9d3edb5827e4e8e1bf5bf92436bfd12d696ec997001a9a]
mmm:~> 
```

**Comment by agnivade** [comment]
Ok so it seems like the hashes are changing? Isn't pinning to any one hash sufficient or otherwise we need to have monitoring to consistently check for new hashes and keep updating.

**Review by phoinixgrr — APPROVED** [review]

**Comment by phoinixgrr** [comment]
👍  I am unblocking this

**Comment by pfltdv** [comment]
Normally pinning into one hash will be enough and it should not change after when tag is created unless they republish the image with same tag. And that tag is not visible at dockerhub as well.(https://hub.docker.com/layers/golang/library/golang/1.18.1/images/sha256-5b75b529da0f2196ee8561a90e5b99aceee56e125c6ef09a3da4e32cf3cc6c20?context=explore)

Looks like it is another topic we need to investigate.

**Comment by phoinixgrr** [comment]
> 

I think this is what is happening. Updated images are being pushed with the same tag. 
But isn't this the whole purpose of pining the image with the SHA digest?

**Comment by pfltdv** [comment]
@phoinixgrr Yes using the pinned image ensures that we will have same tested image at CI pipelines independent on whenever it is executed. It is tested and verified and it will work forever. 

But, if maintainers decided to rebuild and publish new image for same tag, most likely they have a good reason of doing it. And this case is totally another topic, we may need to discuss and decide what we will do. (Since pinned images will not be the latest image for that tag)

**Comment by phoinixgrr** [comment]
I totally agree @pfltdv  👍

**Pull request merged**
