### PR TITLE
MM-11229: Backport to 5.0

### PR DESCRIPTION
**Pull request by grundleborg**

### CODE REVIEW

**Comment by grundleborg** [comment]
@crspeller can we dismiss that codecov trigger? Not really sure why it's moaning about this.

**Comment by crspeller** [comment]
@grundleborg Ya, not sure what that's about, we can just ignore it.

**Comment by cpanato** [comment]
@grundleborg can you add this commit here as well? https://github.com/mattermost/mattermost-server/commit/dccd95bc67779a5b83a2660aec0cf4622cd56550

**Comment by hmhealey** [comment]
@grundleborg 
```
# github.com/mattermost/mattermost-server/app
app/command_invite_people_test.go:18:60: th.App.Config().ServiceSettings.EnableEmailInvitations undefined (type model.ServiceSettings has no field or method EnableEmailInvitations)
app/command_invite_people_test.go:20:68: cfg.ServiceSettings.EnableEmailInvitations undefined (type model.ServiceSettings has no field or method EnableEmailInvitations)
app/command_invite_people_test.go:22:68: cfg.ServiceSettings.EnableEmailInvitations undefined (type model.ServiceSettings has no field or method EnableEmailInvitations)
Makefile:250: recipe for target 'govet' failed
```

**Comment by grundleborg** [comment]
Revert the test change as it sets a config that didn't exist prior to 5.0

**Pull request merged**
