### PR TITLE
MM-21882: Remove the license requirement to promote guests to regular users

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
This PR remove the requirement of having a license to promote guests to users. This way, somebody that had a license but is no longer using it, can promote the guest to users. While there is no a license, the guest accounts are disabled, so looks sensible to apply this change.

#### Ticket Link
[MM-21882](https://mattermost.atlassian.net/browse/MM-21882)

### CODE REVIEW

**Comment by jespino** [comment]
@ogi-m @wiersgallak I saw that too, but I though that maybe we can leave that as a way to provide certain degree of "discovery" of the feature in the team edition. You see there "Demote to Guest", but when you try to use it, you see that for that you need some special license. I don't see that happening in the user facing part, but for the admin facing part makes sense.

**Comment by wiersgallak** [comment]
@jespino I'd rather not leave it because we may have other bad UX on the front-end and I think we'd want to design it a bit more.  I think hiding the Demote to Guest is a better option for now.

**Comment by jespino** [comment]
@ogi-m from the QA perspective I think this is working because this PR is for the server side, and the server side is working fine, I going to make another PR for the client side right away.

**Pull request merged**
