### PR TITLE
[MM-16791] Migrate Plugin.Delete to Sync by default

### LINKED ISSUE #11537: Migrate "Plugin.Delete" to Sync by default
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16791)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `Delete` in the `Plugin` store.

The expected way to implement it is, go to the `Plugin` store implementation in the `store/sqlstore/` directory, modify the method `Delete` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

### PR DESCRIPTION
**Pull request by phillipahereza**
#### Summary

This PR migrates Plugin.Delete in the Store layer to be sync by default

#### Ticket Link

[Jira Ticket](https://mattermost.atlassian.net/browse/MM-16791)

Fixes #11537

### CODE REVIEW

**Comment by hanzei** [comment]
@phillipahereza Looks like you have a build failure:
```# github.com/mattermost/mattermost-server/store/storetest/mocks

store/storetest/mocks/PluginStore.go:9:8: imported and not used: "github.com/mattermost/mattermost-server/store"

# github.com/mattermost/mattermost-server/store/storetest/mocks [github.com/mattermost/mattermost-server/utils.test]

store/storetest/mocks/PluginStore.go:9:8: imported and not used: "github.com/mattermost/mattermost-server/store"

# github.com/mattermost/mattermost-server/store/storetest/mocks [github.com/mattermost/mattermost-server/utils/fileutils.test]

store/storetest/mocks/PluginStore.go:9:8: imported and not used: "github.com/mattermost/mattermost-server/store"

# github.com/mattermost/mattermost-server/store/storetest/mocks [github.com/mattermost/mattermost-server/mlog.test]

store/storetest/mocks/PluginStore.go:9:8: imported and not used: "github.com/mattermost/mattermost-server/store"

# github.com/mattermost/mattermost-server/store/storetest/mocks [github.com/mattermost/mattermost-server/model.test]

store/storetest/mocks/PluginStore.go:9:8: imported and not used: "github.com/mattermost/mattermost-server/store"

# github.com/mattermost/mattermost-server/store/storetest/mocks [github.com/mattermost/mattermost-server/utils/markdown.test]

store/storetest/mocks/PluginStore.go:9:8: imported and not used: "github.com/mattermost/mattermost-server/store"

Makefile:298: recipe for target 'govet' failed

```

**Comment by phillipahereza** [comment]
@hanzei I'm a bit confused by this build error, aren't the mocks autogenerated by mockery? How do I stop the mocks from adding `github.com/mattermost/mattermost-server/store` to the imports in `PluginStore.go` mock?

**Comment by hanzei** [comment]
@phillipahereza AFAIK you have to manually remove the import from the mock file. I suppose this is due to a bug in `mockery`.

**Comment by phillipahereza** [comment]
@hanzei build is still failing, the build logs say a couple of things are messed up in `github.com/mattermost/mattermost-server/enterprise` module, AFAIK this module is not in this codebase. Please help

**Comment by hanzei** [comment]
@phillipahereza The build failed because of a broken build in the enterprise repo. This is fixed now. See https://community.mattermost.com/core/pl/6tfprj5qe7bfzbix3oouag8p1c for more details.

**Pull request merged**
