### PR TITLE
MM-15662: Rename "CreateBotAccounts" config.json setting to "EnableBotAccountCreation"

### PR DESCRIPTION
**Pull request by andresoro**
#### Summary
Changes config setting CreateBotAccounts to EnableBotAccountCreation. 

#### Ticket Link
[MM-15662](https://mattermost.atlassian.net/browse/MM-15662)

### CODE REVIEW

**Comment by andresoro** [comment]
@lieut-data I am not entirely sure why tests are not passing now? They passed when I initially opened the PR. The test case TestPublicFilesRequest is failing for me.

**Comment by andresoro** [comment]
I am unsure why the commit cannot be built. It passed CI when I pushed the last commit a few days ago.

**Comment by crspeller** [comment]
@andresoro You have some build errors to fix. 
```
# github.com/mattermost/mattermost-server/app

app/diagnostics.go:295:82: cfg.ServiceSettings.CreateBotAccounts undefined (type model.ServiceSettings has no field or method CreateBotAccounts)

# github.com/mattermost/mattermost-server/app [github.com/mattermost/mattermost-server/app.test]

app/diagnostics.go:295:82: cfg.ServiceSettings.CreateBotAccounts undefined (type model.ServiceSettings has no field or method CreateBotAccounts)

Makefile:291: recipe for target 'govet' failed
```

**Comment by andresoro** [comment]
Confused as to why the commit cannot be built. This is just a changing of a variable name. I am trying to see which test failed but the CI says all tests for the pipeline passed?

**Comment by andresoro** [comment]
@crspeller I am confused as to why the build is now failing. Before the update to app/diagnostics.go the build was working fine. These changes are simply renaming variables so it shouldn't have too much adverse effects, right? As to the tests that are actually failing on the CI, they all pass on my machine.

**Comment by andresoro** [comment]
@crspeller fixed build error and merged upstream.

**Pull request merged**
