### PR TITLE
Enable custom statuses feature flag by default

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Enable custom statuses feature flag by default

```release-note
NONE
```

### CODE REVIEW

**Comment by jespino** [comment]
@amyblais this is the change directly to the release-5.33 branch.

**Comment by amyblais** [comment]
Will there also be a PR for cloud branch for March 10th Cloud release?

**Comment by jespino** [comment]
@amyblais that probably is a question for @esethna If you want I can create one, for sure.

**Comment by esethna** [comment]
@amyblais @jespino yes we should enable the feature in cloud on March 10th as well.

**Review by esethna — APPROVED** [review]

**Comment by esethna** [comment]
@amyblais @jespino perhaps add different reviewers if this needs to go in today as Eli won't be around till tomorrow

**Comment by jespino** [comment]
@esethna @amyblais I think that is not needed for the cloud, because the cloud is though for enabling/disbling this things on the fly using their system. so... I shouldn't be necessary.

**Comment by esethna** [comment]
@jespino makes sense. @amyblais can we verify that the feature is enabled for the cloud march 10 release?

**Review by lieut-data — APPROVED** [review]
I'm not an expert here, but this seems consistent with how we've modified this value for the incident collaboration plugin.

But I had been under the impression, @crspeller, that we were going to /remove/ feature flags before they shipped on-premise, having validated them in cloud. Or has the process changed?

**Review by crspeller — APPROVED** [review]
@lieut-data This is actually process breaking. You are correct, the process is to remove the feature flag to ship to on-prem having been validated in cloud first. The feature flag has already been removed from master. This change only effects the 5.33 release branch.

The explanation I have been given is that this is an urgent feature that must be released immediately. Also we are in a state where we are confident enough in the feature to release it to on-prem customers, but not confident enough to release it to cloud without the feature flag. 
I have explained, and the release team understands that feature flags don't work on-prem and the only recourse would be to turn the feature off manually (something cloud customers can also do).

**Pull request merged**
