### PR TITLE
Update NOTICE.txt

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Comment by amyblais** [comment]
@crspeller See JB's notes above ^

**Comment by crspeller** [comment]
Nothing in Gopkg.toml should not be in the lock file. Taking a look at the dependencies you added a lot of them are dependencies of dependencies. So they are not actually used in MM, but our dependencies use them. Not sure if we need to include those.
Here is a list of all our first level dependencies:
```
github.com/avct/uasurfer                                                                                                                                                                                                                                                                                                                                                     
github.com/dgryski/dgoogauth                                                                                                                                                                                                                                                                                                                                                 
github.com/disintegration/imaging                                                                                                                                                                                                                                                                                                                                            
github.com/dyatlov/go-opengraph/opengraph                                                                                                                                                                                                                                                                                                                                    
github.com/fsnotify/fsnotify                                                                                                                                                                                                                                                                                                                                                 
github.com/golang/freetype                                                                                                                                                                                                                                                                                                                                                   
github.com/go-ldap/ldap                                                                                                                                                                                                                                                                                                                                                      
github.com/go-redis/redis                                                                                                                                                                                                                                                                                                                                                    
github.com/gorilla/handlers                                                                                                                                                                                                                                                                                                                                                  
github.com/gorilla/mux                                                                                                                                                                                                                                                                                                                                                       
github.com/gorilla/schema                                                                                                                                                                                                                                                                                                                                                    
github.com/gorilla/websocket                                                                                                                                                                                                                                                                                                                                                 
github.com/go-sql-driver/mysql                                                                                                                                                                                                                                                                                                                                               
github.com/hako/durafmt                                                                                                                                                                                                                                                                                                                                                      
github.com/hashicorp/memberlist                                                                                                                                                                                                                                                                                                                                              
github.com/icrowley/fake                                                                                                                                                                                                                                                                                                                                                     
github.com/lib/pq                                                                                                                                                                                                                                                                                                                                                            
github.com/mattermost/gorp                                                                                                                                                                                                                                                                                                                                                   
github.com/mattermost/html2text                                                                                                                                                                                                                                                                                                                                              
github.com/mattermost/rsc/qr                                                                                                                                                                                                                                                                                                                                                 
github.com/minio/minio-go                                                                                                                                                                                                                                                                                                                                                    
github.com/minio/minio-go/pkg/credentials                                                                                                                                                                                                                                                                                                                                    
github.com/nicksnyder/go-i18n/i18n                                                                                                                                                                                                                                                                                                                                           
github.com/NYTimes/gziphandler                                                                                                                                                                                                                                                                                                                                               
github.com/pborman/uuid                                                                                                                                                                                                                                                                                                                                                      
github.com/pkg/errors                                                                                                                                                                                                                                                                                                                                                        
github.com/prometheus/client_golang/prometheus                                                                                                                                                                                                                                                                                                                               
github.com/prometheus/client_golang/prometheus/promhttp                                                                                                                                                                                                                                                                                                                      
github.com/rwcarlsen/goexif/exif                                                                                                                                                                                                                                                                                                                                             
github.com/segmentio/analytics-go                                                                                                                                                                                                                                                                                                                                            
github.com/spf13/cobra                                                                                                                                                                                                                                                                                                                                                       
github.com/spf13/viper                                                                                                                                                                                                                                                                                                                                                       
github.com/stretchr/testify/assert                                                                                                                                                                                                                                                                                                                                           
github.com/stretchr/testify/mock                                                                                                                                                                                                                                                                                                                                             
github.com/stretchr/testify/require                                                                                                                                                                                                                                                                                                                                          
github.com/tylerb/graceful                                                                                                                                                                                                                                                                                                                                                   
golang.org/x/crypto/acme/autocert                                                                                                                                                                                                                                                                                                                                            
golang.org/x/crypto/bcrypt                                                                                                                                                                                                                                                                                                                                                   
golang.org/x/image/bmp                                                                                                                                                                                                                                                                                                                                                       
golang.org/x/net/bpf                                                                                                                                                                                                                                                                                                                                                         
golang.org/x/sys/unix                                                                                                                                                                                                                                                                                                                                                        
gopkg.in/gomail.v2                                                                                                                                                                                                                                                                                                                                                           
gopkg.in/natefinch/lumberjack.v2                                                                                                                                                                                                                                                                                                                                             
gopkg.in/olivere/elastic.v5                                                                                                                                                                                                                                                                                                                                                  
gopkg.in/throttled/throttled.v2                                                                                                                                                                                                                                                                                                                                              
gopkg.in/throttled/throttled.v2/store/memstore                                                                                                                                                                                                                                                                                                                               
gopkg.in/yaml.v2                                                                                                                                                                                                                                                                                                                                                             
go.uber.org/zap                                                                                                                                                                                                                                                                                                                                                              
go.uber.org/zap/zapcore
```

**Comment by crspeller** [comment]
Also this is the command to generate that list:
```
go list -f '{{ join .Imports "\n" }}' ./... | sort -u | grep vendor | sed -e "s/github.com\/mattermost\/mattermost-server\/vendor\///g"
```

**Comment by amyblais** [comment]
@crspeller I'm opening a new PR as it's easier to start fresh, however I'm wondering if the list of dependencies you have above is up to date? Some of those pages don't seem to exist, e.g. github.com/dyatlov/go-opengraph/opengraph, https://github.com/mattermost/rsc/qr, github.com/minio/minio-go/pkg/credentials, etc.

**Comment by crspeller** [comment]
@amyblais They are full import paths. You can find the repository by using only the first two parts of the path. So `github.com/dyatlov/go-opengraph/opengraph` becomes https://github.com/dyatlov/go-opengraph

**Pull request closed without merging**
