### PR TITLE
PLT-6871: Sort at-mention autocomplete by username starting with search string

### LINKED ISSUE #6699: Change at-mention autocomplete to prioritize entries where the username starts with the search string
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6871)

Change at-mention autocomplete to prioritize entries where the username starts with the search string

For the at mention autocomplete, it should sort users based on their username, but any user with their username starting with the search string should go first.

To give some context, if you search for "te" in the auto-complete right now on pre-release, you get the following results.

image

What you expect is this (those starting with "te" appear first, followed by other users in alphabetical order)

image

NOTE: You can compare to how the sorting is done for channel switcher shortcut (CTRL+K) https://github.com/mattermost/platform/pull/6486

Also, here is a start of a PR to get you started: https://github.com/mattermost/mattermost-webapp/pull/15

### PR DESCRIPTION
**Pull request by mikaoelitiana**
#### Summary
Change at-mention autocomplete to prioritize entries where the username starts with the search string

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6871

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

Fixes #6699

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana! 

The user autocomplete sorting works as expected. Nice work

image

----

I'm wondering if we should make the sorting consistent in the following places too.

If this isn't as easy or out of scope of the original ticket, let me know and I can create a separate one for this

1. `from:` autocomplete in search

image

2. Add/Manage Members user lists

image

**Comment by mikaoelitiana** [comment]
Hello. I wasn't aware of this, I will check

**Comment by mikaoelitiana** [comment]
@jasonblais I have added fixes for the 2 other lists

**Comment by jasonblais** [comment]
Thanks @mikaoelitiana! @lindalumitchell will help with a test pass -- it might be a few days since we're approaching 4.1 code complete, which is on Friday.

**Comment by jasonblais** [comment]
Hey @mikaoelitiana , we were busy with the 4.1 release but will test this PR soon. Big thanks for the contribution!

**Comment by lindalumitchell** [comment]
Hi @mikaoelitiana, thanks for this contribution! Testing this, I have a couple questions:

A) I'm seeing a Javascript error when I try to interact with the user filter in the View/Manage Member modal: 
1. Click member icon at top of a channel
2. Scroll down and click View/Manage Members
3. Type `ab` in the search box
4. Press Backspace to remove the `b`
Observed: Javascript error (screenshot attached)
screen shot 2017-08-17 at 8 44 32 am

B) There seem to be some users missing from the search/filter results in all three places (View/Manage members modal, @-username autocomplete in message box, and `from:` autocomplete in search box). 
I created users named `abba`, `abernathy`, `nate`, and `natalie`.
1.  Typing `ab` returns only `abernathy` but should also return `abba`
2. Typing `nat` returns `nate` and `natalie` but should also return `abernathy`, below the first two results. Containing `nat`, it should still be returned, I believe, just prioritized below the results that start with `nat`

@jasonblais can you help confirm I'm understanding the expected correctly?

**Comment by jasonblais** [comment]
Thanks @lindalumitchell! 

@mikaoelitiana The first one (A) looks like a bug, can you help take a look?

Chatted with Linda about (B) and it's working as expected so no need to make changes for it.

**Comment by jasonblais** [comment]
@mikaoelitiana   Heads up that Mattermost will be separating the `/platform` repo into two repositories on September 6th:
 - a new repository for webapp client code, hosted at github.com/mattermost/mattermost-webapp
 - existing repository (`/platform`) renamed to `/mattermost-server`, containing the server code.

Open PRs on September 6th may need to re-submit their pull request after the separation. For instance, PRs changing the UI would need to be re-submitted to the new `mattermost-webapp` repository.

More details here: https://forum.mattermost.org/t/mattermost-separating-platform-into-two-repositories-on-september-6th/3708/3

**Comment by crspeller** [comment]
This PR needs to be re-submitted to the new separated webapp and server repositories.

**Comment by mikaoelitiana** [comment]
OK I will ckeck

**Pull request closed without merging**
