### PR TITLE
Apt dependencies are not pinned, so upgrades will break docker builds…

### PR DESCRIPTION
**Pull request by pfltdv**
Cherry pick of #20901 on release-7.2.

/cc  @pfltdv

```release-note
NONE
```

### CODE REVIEW

**Comment by pfltdv** [comment]
Automated cherry pick is not working since it uses fork repository. PR to merge https://github.com/mattermost/mattermost-server/pull/20902

**Comment by amyblais** [comment]
This one is failing too.

**Comment by pfltdv** [comment]
> This one is failing too.

Yes it  is related to dockerhub rate limits, restarted failed jobs.

**Review by isacikgoz — APPROVED** [review]

**Comment by pfltdv** [comment]
Dockerhub rate limits failed tests, restarted the job again.

**Pull request merged**
