### PR TITLE
[MM-17889] Implement validation of plugin API version comments

### PR DESCRIPTION
**Pull request by pbitty**
This is to resolve issue #11912.  All feedback is welcome.

MM-17889

### CODE REVIEW

**Comment by pbitty** [comment]
I am wondering about where to invoke this check from.  Should it be part of the `make test` target, or perhaps added to `scripts/test.sh`?

Another thought I had was that this could be put into a unit test so that it simply runs as part of `go test`.  What are your thoughts on that idea?

**Comment by pbitty** [comment]
@levb @lieut-data, you are very welcome!

I took a look at the approach for implementing it as an "Analyzer" using `go/analysis` (the same package used by `go vet`).  It seems it would make the code simpler and keep the output consistent with the rest of the Go tools.

The only potential catch I found is that the `go/analysis` package doesn't give you a way to point it at a specific package (ie: `github.com/mattermost/mattermost-server/plugin`).  It simply provides a `singlechecker.Main()` method, which handles CLI args and expects a package to be passed in, similar to `go vet`.

This means the checker code would have no knowledge of the `plugin` package at all, it would have to be passed in as a CLI arg, eg:
```shell
go run plugin/checker/main.go github.com/mattermost/mattermost-server/plugin
```

To me this sounds reasonable and still worth implementing.  What do you think?

**Comment by lieut-data** [comment]
@pbitty: I agree with your analysis and recommendation. Are you still interested in running with this change? Would it make sense just to do it in this PR?

**Comment by pbitty** [comment]
@lieut-data I've just pushed the change.  There are a couple of little hacks I had to narrow it down to the file set that contains the `API` interface.  This approach does eliminate the code for loading the package and printing errors.  What do you think?

Looking at #11912, some of this code can probably be refactored to help there.

I've also gone ahead and vendored in the new dependencies, following the example of other PRs.

**Comment by pbitty** [comment]
The tests seem to be failing because of a package that was removed by `go mod vendor`.  I will look into this as soon as possible.

**Comment by lieut-data** [comment]
@prapti, strictly speaking, I don't think we have to review this one prior to merging to master, but if you're so inclined, it should be as easy as checking out this repository, hacking up `plugin/api.go` to break one of the comments there, and then running `make govet` to confirm.

**Comment by pbitty** [comment]
Thanks @lieut-data .  I should be able to look at this tonight.  I will ping you if I think I need help.

**Comment by pbitty** [comment]
@lieut-data, looks like the build was failing due to an out-of-sync branch.  I've since merged `master` and the "regular" checks are passing, but Circle CI is failing.

It looks to me like the CircleCI issue is across all PRs due to a missing config file.

**Comment by prapti** [comment]
> @prapti, strictly speaking, I don't think we have to review this one prior to merging to master, but if you're so inclined, it should be as easy as checking out this repository, hacking up `plugin/api.go` to break one of the comments there, and then running `make govet` to confirm.

Sounds good @lieut-data, I'll queue this up to test post merge. However, would the big number of changes in the PR warrant unit tests?

**Comment by lieut-data** [comment]
@prapti, I don't think the `vendor` changes here relate to the need for unit tests: the actual number of changes here are small. 

That being said, @pbitty, now that we pass the package parameter to the utility, would it make sense to write a unit test and a set of `plugin/checker/valid` and `plugin/checker/invalid` packages, each with a subset of the `API` interface to verify the code works over the long term.

**Comment by pbitty** [comment]
@lieut-data I can definitely do that.  I am thinking that the original implementation (without `go/analysis` would be easier and cleaner to unit-test.  The API was simply `func runCheck(pkgPath string) error`, which we could point at test packages and assert on the `error`.

The `go/analysis` implementation would have to be run as a proc and its exit code and stderr output checked.

What do you think of reverting to the original implementation and implementing the unit tests in Go?  If I have time, I will give it a shot and you can tell me if you like it.

**Comment by pbitty** [comment]
@lieut-data, I took the liberty to go with my suggestion above.  Let me know what you think and I can change it as needed.

**Comment by levb** [comment]
👍 thanks for the tests! Looks like it's now failing on 
```
+ make check-style BUILD_NUMBER=PR-11941-21
Running GOVET
go get golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
...
```
and then failing to find packages. I am not up to speed as to `go mod` and `vendor/` status in mattermost-server, @lieut-data perhaps can help look into this?

**Comment by pbitty** [comment]
@lieut-data , the tests have been consistently failing at this test:
```
--- FAIL: TestConfigSet (3.20s)
    --- PASS: TestConfigSet/Error_when_no_arguments_are_given (0.10s)
    --- PASS: TestConfigSet/Error_when_only_one_argument_is_given (0.10s)
    --- PASS: TestConfigSet/Error_when_the_wrong_key_is_set (0.39s)
    --- FAIL: TestConfigSet/Error_when_the_wrong_value_is_set (0.48s)
        config_test.go:141: 
            	Error Trace:	config_test.go:141
            	Error:      	"=== RUN   TestExecCommand
            	            	EmailSettings.ConnectionSecurity: ""
            	            	--- PASS: TestExecCommand (0.13s)
            	            	PASS
            	            	coverage: 1.6% of statements in github.com/mattermost/mattermost-server/api4, github.com/mattermost/mattermost-server/app, github.com/mattermost/mattermost-server/cmd/mattermost, github.com/mattermost/mattermost-server/cmd/mattermost/commands, github.com/mattermost/mattermost-server/cmd/platform, github.com/mattermost/mattermost-server/config, github.com/mattermost/mattermost-server/config/config_generator, github.com/mattermost/mattermost-server/config/config_generator/generator, github.com/mattermost/mattermost-server/einterfaces, github.com/mattermost/mattermost-server/einterfaces/jobs, github.com/mattermost/mattermost-server/einterfaces/mocks, github.com/mattermost/mattermost-server/imports, github.com/mattermost/mattermost-server/jobs, github.com/mattermost/mattermost-server/jobs/interfaces, github.com/mattermost/mattermost-server/manualtesting, github.com/mattermost/mattermost-server/migrations, github.com/mattermost/mattermost-server/mlog, github.com/mattermost/mattermost-server/mlog/human, github.com/mattermost/mattermost-server/model, github.com/mattermost/mattermost-server/model/gitlab, github.com/mattermost/mattermost-server/plugin, github.com/mattermost/mattermost-server/plugin/checker, github.com/mattermost/mattermost-server/plugin/checker/test/invalid, github.com/mattermost/mattermost-server/plugin/checker/test/missing, github.com/mattermost/mattermost-server/plugin/checker/test/valid, github.com/mattermost/mattermost-server/plugin/interface_generator, github.com/mattermost/mattermost-server/plugin/plugintest, github.com/mattermost/mattermost-server/plugin/plugintest/mock, github.com/mattermost/mattermost-server/plugin/scheduler, github.com/mattermost/mattermost-server/services/configservice, github.com/mattermost/mattermost-server/services/filesstore, github.com/mattermost/mattermost-server/services/filesstore/mocks, github.com/mattermost/mattermost-server/services/httpservice, github.com/mattermost/mattermost-server/services/imageproxy, github.com/mattermost/mattermost-server/services/mailservice, github.com/mattermost/mattermost-server/services/mfa, github.com/mattermost/mattermost-server/services/timezones, github.com/mattermost/mattermost-server/store, github.com/mattermost/mattermost-server/store/layer_generators, github.com/mattermost/mattermost-server/store/localcachelayer, github.com/mattermost/mattermost-server/store/sqlstore, github.com/mattermost/mattermost-server/store/storetest, github.com/mattermost/mattermost-server/store/storetest/mocks, github.com/mattermost/mattermost-server/testlib, github.com/mattermost/mattermost-server/utils, github.com/mattermost/mattermost-server/utils/fileutils, github.com/mattermost/mattermost-server/utils/imgutils, github.com/mattermost/mattermost-server/utils/jsonutils, github.com/mattermost/mattermost-server/utils/markdown, github.com/mattermost/mattermost-server/utils/testutils, github.com/mattermost/mattermost-server/web, github.com/mattermost/mattermost-server/wsapi, github.com/mattermost/mattermost-server/enterprise/account_migration, github.com/mattermost/mattermost-server/enterprise/cluster, github.com/mattermost/mattermost-server/enterprise/compliance, github.com/mattermost/mattermost-server/enterprise/data_retention, github.com/mattermost/mattermost-server/enterprise/elasticsearch, github.com/mattermost/mattermost-server/enterprise/imports, github.com/mattermost/mattermost-server/enterprise/ldap, github.com/mattermost/mattermost-server/enterprise/message_export, github.com/mattermost/mattermost-server/enterprise/message_export/actiance_export, github.com/mattermost/mattermost-server/enterprise/message_export/common_export, github.com/mattermost/mattermost-server/enterprise/message_export/csv_export, github.com/mattermost/mattermost-server/enterprise/message_export/global_relay_export, github.com/mattermost/mattermost-server/enterprise/metrics, github.com/mattermost/mattermost-server/enterprise/oauth/google, github.com/mattermost/mattermost-server/enterprise/oauth/office365, github.com/mattermost/mattermost-server/enterprise/saml" should not contain "invalid"
            	Test:       	TestConfigSet/Error_when_the_wrong_value_is_set
    --- FAIL: TestConfigSet/Error_when_the_wrong_locale_is_set (0.72s)
        config_test.go:148: 
            	Error Trace:	config_test.go:148
            	Error:      	"=== RUN   TestExecCommand
            	            	LocalizationSettings.DefaultServerLocale: "es"
            	            	--- PASS: TestExecCommand (0.13s)
            	            	PASS
            	            	coverage: 1.6% of statements in github.com/mattermost/mattermost-server/api4, github.com/mattermost/mattermost-server/app, github.com/mattermost/mattermost-server/cmd/mattermost, github.com/mattermost/mattermost-server/cmd/mattermost/commands, github.com/mattermost/mattermost-server/cmd/platform, github.com/mattermost/mattermost-server/config, github.com/mattermost/mattermost-server/config/config_generator, github.com/mattermost/mattermost-server/config/config_generator/generator, github.com/mattermost/mattermost-server/einterfaces, github.com/mattermost/mattermost-server/einterfaces/jobs, github.com/mattermost/mattermost-server/einterfaces/mocks, github.com/mattermost/mattermost-server/imports, github.com/mattermost/mattermost-server/jobs, github.com/mattermost/mattermost-server/jobs/interfaces, github.com/mattermost/mattermost-server/manualtesting, github.com/mattermost/mattermost-server/migrations, github.com/mattermost/mattermost-server/mlog, github.com/mattermost/mattermost-server/mlog/human, github.com/mattermost/mattermost-server/model, github.com/mattermost/mattermost-server/model/gitlab, github.com/mattermost/mattermost-server/plugin, github.com/mattermost/mattermost-server/plugin/checker, github.com/mattermost/mattermost-server/plugin/checker/test/invalid, github.com/mattermost/mattermost-server/plugin/checker/test/missing, github.com/mattermost/mattermost-server/plugin/checker/test/valid, github.com/mattermost/mattermost-server/plugin/interface_generator, github.com/mattermost/mattermost-server/plugin/plugintest, github.com/mattermost/mattermost-server/plugin/plugintest/mock, github.com/mattermost/mattermost-server/plugin/scheduler, github.com/mattermost/mattermost-server/services/configservice, github.com/mattermost/mattermost-server/services/filesstore, github.com/mattermost/mattermost-server/services/filesstore/mocks, github.com/mattermost/mattermost-server/services/httpservice, github.com/mattermost/mattermost-server/services/imageproxy, github.com/mattermost/mattermost-server/services/mailservice, github.com/mattermost/mattermost-server/services/mfa, github.com/mattermost/mattermost-server/services/timezones, github.com/mattermost/mattermost-server/store, github.com/mattermost/mattermost-server/store/layer_generators, github.com/mattermost/mattermost-server/store/localcachelayer, github.com/mattermost/mattermost-server/store/sqlstore, github.com/mattermost/mattermost-server/store/storetest, github.com/mattermost/mattermost-server/store/storetest/mocks, github.com/mattermost/mattermost-server/testlib, github.com/mattermost/mattermost-server/utils, github.com/mattermost/mattermost-server/utils/fileutils, github.com/mattermost/mattermost-server/utils/imgutils, github.com/mattermost/mattermost-server/utils/jsonutils, github.com/mattermost/mattermost-server/utils/markdown, github.com/mattermost/mattermost-server/utils/testutils, github.com/mattermost/mattermost-server/web, github.com/mattermost/mattermost-server/wsapi, github.com/mattermost/mattermost-server/enterprise/account_migration, github.com/mattermost/mattermost-server/enterprise/cluster, github.com/mattermost/mattermost-server/enterprise/compliance, github.com/mattermost/mattermost-server/enterprise/data_retention, github.com/mattermost/mattermost-server/enterprise/elasticsearch, github.com/mattermost/mattermost-server/enterprise/imports, github.com/mattermost/mattermost-server/enterprise/ldap, github.com/mattermost/mattermost-server/enterprise/message_export, github.com/mattermost/mattermost-server/enterprise/message_export/actiance_export, github.com/mattermost/mattermost-server/enterprise/message_export/common_export, github.com/mattermost/mattermost-server/enterprise/message_export/csv_export, github.com/mattermost/mattermost-server/enterprise/message_export/global_relay_export, github.com/mattermost/mattermost-server/enterprise/metrics, github.com/mattermost/mattermost-server/enterprise/oauth/google, github.com/mattermost/mattermost-server/enterprise/oauth/office365, github.com/mattermost/mattermost-server/enterprise/saml" should not contain "invalid"
            	Test:       	TestConfigSet/Error_when_the_wrong_locale_is_set
```

The test seems to be failing because I introduced the `checker/test/invalid` package, which contains the word `invalid`.  I will take a deeper look either tonight or tomorrow night (ET).  In the meantime, if you have any suggestions, please let me know.

**Comment by pbitty** [comment]
@lieut-data , 

I did a bit more digging and discovered that the output of `RunCommand` in the tests includes `go test` output, and when coverage reporting is enabled, it prints all the package names.  I added a package called `invalid`, which ends up being caught by the tests that assert on the absence of the word `invalid`.

You can reproduce it without running all the test with this command:
```
make TE_PACKAGES="github.com/mattermost/mattermost-server/cmd/mattermost/commands github.com/mattermost/mattermost-server/plugin/checker/test/invalid" TESTS=TestConfigSet test-server
```

Pending a deeper fix, I think simply changing the key to something else should be enough for this PR.  Let me know if you agree.

**Comment by lieut-data** [comment]
@pbitty, sorry for the delay in responding -- I'm currently out-of-office running a team meetup and have been slow to respond.

Winding the stack backwards, I think renaming the package to workaround the clash is fine. Thanks for digging into this!

On the `go/analysis` front, I'm 0/5, as both of your solutions seem really good. If we can unit test the approach you have now, that's great! I'm curious if the Go team had a plan for enabling unit testing using the `go/analysis` approach, but we can iterate on that independently.

Let me know if you think we're good, and I'll go ahead and merge this :)

**Comment by pbitty** [comment]
@lieut-data , no problem at all.  I think it's good to merge.

Before your reply, I had already renamed the key in the `TestConfigSet` test instead of the package name.  If you're okay with that, we're good to merge.  Otherwise, I can tweak it still.

**Comment by lieut-data** [comment]
Excellent! Looks good from my perspective -- @prapti, when you have a chance, can you give us guidance on whether we test before or after merging this feature?

**Comment by hanzei** [comment]
Thank you very much for this awesome PR @pbitty :dancer:

**Pull request merged**
