### PR TITLE
MM-52325: Bump morph

### PR DESCRIPTION
**Pull request by agnivade**
This is needed to implement non-transactional migrations

https://mattermost.atlassian.net/browse/MM-52325
```release-note
The Go MySQL driver has changed the `maxAllowedPacket` size from 4MiB to 64MiB. This is to make it consistent with the change in the server side default value from MySQL 5.7 to MySQL 8.0. If your `max_allowed_packet` setting is not 64MiB, then please update the MySQL config DSN with an additional param of `maxAllowedPacket` to match with the server side value. Alternatively, a value of 0 can be set to to automatically fetch the server side value, on every new connection, which has a performance overhead.
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM, shall we add `TestDatabaseSetFile/max_length` as flaky test? Never seen it happened though but GH env seems to be more congested compared to previous one.

**Comment by agnivade** [comment]
Yeah sure

**Comment by agnivade** [comment]
Well actually, this seems like a CI env issue to me:

```
[mysql] 2023/05/16 06:12:41 packets.go:174: write tcp 172.18.0.10:60868->172.18.0.8:3306: write: broken pipe
2023-05-16T06:39:17.9088405Z     database_test.go:963: 
2023-05-16T06:39:17.9088886Z         	Error Trace:	/mattermost-server/mattermost-server/server/config/database_test.go:963
2023-05-16T06:39:17.9089168Z         	Error:      	Received unexpected error:
2023-05-16T06:39:17.9089425Z         	            	invalid connection
2023-05-16T06:39:17.9089773Z         	            	failed to update row for toolong
```

invalid connection usually means something went wrong with the DB.

**Review by agarciamontoro — APPROVED** [review]

**Comment by agnivade** [comment]
No wait, that's an actual failure. I boiled it down to a mysql driver upgrade from 1.7.0 to 1.7.1: https://github.com/go-sql-driver/mysql/compare/v1.7.0...v1.7.1. They bumped up the maxPacketSize from 4MB to 64MB. And that's what's causing this. Trying to see how to fix the test.

**Comment by agnivade** [comment]
Ok I had to add a `&maxAllowedPacket=4194304` to the DSN. This is possibly a breaking change as now the driver will send more packets by default. So customers may need to check their DB config and update the DSN to match with whatever is configured on the DB. I will add in the PR release notes.

**Comment by agnivade** [comment]
This only affects inserting text larger than 4MB, which I think only affects saving the config in DB. Don't believe we need a full blown performance test for this.

cc @amyblais - there is a potential breaking change with this PR which has happened because of a dependency upgrade (out of our control). I have updated the release notes accordingly for what customers should do.

**Pull request merged**
