### PR TITLE
Mattermost Server OAuth Flow Cross-Site Scripting

### PR DESCRIPTION
**Pull request by anurag6713**
#### Summary
In Mobile OAUTH flow,  redirect url query param is used in output html without sanitisation, which could lead to XSS attack.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36250

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Review by srkgupta — APPROVED** [review]
Thanks @anurag6713. Tested the changes from security perspective and the issue is fixed now and is working fine.

**Comment by amyblais** [comment]
@mkraft @furqanmlk Please help prioritize reviews on this (this is for v5.36 and backports).

**Review by mkraft — APPROVED** [review]

**Comment by furqanmlk** [comment]
> @mkraft @furqanmlk Please help prioritize reviews on this (this is for v5.36 and backports).

Hi @amyblais , I was having issue with OAuth Sample app, I have session with Anurag today to resolve it.
I will update here today

**Comment by amyblais** [comment]
@furqanmlk Let me know if you have an update on this.

**Review by furqanmlk — APPROVED** [review]
Thanks @anurag6713 

Working as expected
**Result without this PR**
image

**Result with this PR**
image

**Comment by amyblais** [comment]
@anurag6713 Please help cherry-pick this to the following branches: ``release-5.36``, ``cloud``, ``release-5.35``, ``release-5.34``, ``release-5.33``, and ``release-5.31``.

**Comment by amyblais** [comment]
@anurag6713 Needs a manual cherry-pick to ``release-5.31``.

**Pull request merged**
