### PR TITLE
MM-22831: Allow config keys which don't have a period to be overridden

### LINKED ISSUE #13963: Environment variables for nested dictionary values in config.json do not work
I've been trying to add Mattermost environment variables for values in the "PluginSettings" section of the config.json file. 
For example, in the following example, if I wanted to add a variable for encryptionkey so that it overrides the value in config.json, according to the logic in the documentation, I would need to add and environment variable with the name MM_PLUGINSETTINGS_PLUGINS_GITHUB_ENCRYPTIONKEY . 

```
"PluginSettings": {
    ...
    "Plugins": {
        "github": {
            "encryptionkey": "<your encryption key>",
            "githuboauthclientid": "<your oauth client id>",
            "githuboauthclientsecret": "<your oauth client secrete",
            "githuborg": "<your github org>"
            "webhooksecret": "<your webhook secret>"
        },
    ...
    "PluginStates": {
        ...
        "github": {
            "Enable": true
        },
        ...
    }
},
```
However, this doesn't work. The variable is passed to the container, but it has no affect on the actual configuration. This is the same if I try to create a variable for any of these nested keys. 

Is this a limitation with the capabilities of Mattermost? The ability to do this is vital, because, without it, sensitive data would need to be added to the config.json file, and this isn't a good practice.

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

We get the original map from viper config. And then we populate the map
with those keys which do not have a period in them.
After we have unmarshalled the original values, we restore the original
values which did not have periods.

This allows us to atleast override values which don't have period in them.

But there is a subtle gotcha here, for the PluginSettings.Plugins section,
we can have nested maps of any depth. The current code is just able to handle
maps of depth 1. Anything more than that, will be flattened. This is technically
a regression, but I believe such a case was never needed.

Not a complete fix, because that needs to be done from within viper itself.
But it fixes the most common cases which don't have period in them.

Fixes #13963

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-22831

### CODE REVIEW

**Comment by agnivade** [comment]
> almost all plugins use a reverse DNS notation akin to com.mattermost.<plugin_id>. Wondering if it's worth fixing just an edge case if the larger problem remains unsolved?

Oh is it ? Didnt realize the other way round was the common case. In that case, I do agree that this isnt necessary. Feel free to close.

**Comment by hmhealey** [comment]
If having plugin IDs with only one part isn't well supported, perhaps we should note that limitation somewhere? We could also consider giving the GitHub plugin a more descriptive name as well if that would help.

**Comment by agnivade** [comment]
I think ids with one part are just legacy, and there is no limitation as such. But I don't know much about plugins. In any case, this issue is about the opposite case - that plugins with the reverse dns notation can't be overriden.

**Comment by lieut-data** [comment]
> If having plugin IDs with only one part isn't well supported, perhaps we should note that limitation somewhere? 

Yeah, there's no limitation here, just that we have been encouraging reverse DNS notation so that there /can/ be more than one GitHub plugin, etc.

@agnivade, based on your comments above, I'm inclined to close this out until we can revisit the viper situation. Granted, the "viper problem" has been a topic of discussion for over two years now, so I'm not terribly hopeful!

**Pull request closed without merging**
