### PR TITLE
translations PR 20200414

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

If you as a core committer are requested a review, please confirm there are no changes that would cause build or unit test failures, and merge the PR.

Notes:
1. Further changes to translations should be made to the [Mattermost Translation Server(https://translate.mattermost.com/projects/mattermost). These will be included in next week's PR.
2. If you see an English translation instead of the desired language, then this PR was submitted before the translation was made on the [Mattermost Translation Server(https://translate.mattermost.com/projects/mattermost). New translations will be included in next week's PR.

### CODE REVIEW

**Comment by amyblais** [comment]
Asked JasonD to check why this fails

**Comment by jaydeland** [comment]
It failed to upload to the codecov
Uploading reports
    url: https://codecov.io
    query: branch=translations-20200414&commit=83ead128aaf1755fa5000a3c500a20a7ec270817&build=1&build_url=https%3A%2F%2Fbuild.mattermost.com%2Fjob%2Fmp%2Fjob%2Fmattermost-server-pr-new%2Fjob%2Ftranslations-20200414%2F1%2F&name=&tag=&slug=mattermost%2Fmattermost-server&service=jenkins&flags=&pr=&job=
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200410-0786dee&token=secret&branch=translations-20200414&commit=83ead128aaf1755fa5000a3c500a20a7ec270817&build=1&build_url=https%3A%2F%2Fbuild.mattermost.com%2Fjob%2Fmp%2Fjob%2Fmattermost-server-pr-new%2Fjob%2Ftranslations-20200414%2F1%2F&name=&tag=&slug=mattermost%2Fmattermost-server&service=jenkins&flags=&pr=&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200410-0786dee&token=secret&branch=translations-20200414&commit=83ead128aaf1755fa5000a3c500a20a7ec270817&build=1&build_url=https%3A%2F%2Fbuild.mattermost.com%2Fjob%2Fmp%2Fjob%2Fmattermost-server-pr-new%2Fjob%2Ftranslations-20200414%2F1%2F&name=&tag=&slug=mattermost%2Fmattermost-server&service=jenkins&flags=&pr=&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200410-0786dee&token=secret&branch=translations-20200414&commit=83ead128aaf1755fa5000a3c500a20a7ec270817&build=1&build_url=https%3A%2F%2Fbuild.mattermost.com%2Fjob%2Fmp%2Fjob%2Fmattermost-server-pr-new%2Fjob%2Ftranslations-20200414%2F1%2F&name=&tag=&slug=mattermost%2Fmattermost-server&service=jenkins&flags=&pr=&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200410-0786dee&token=secret&branch=translations-20200414&commit=83ead128aaf1755fa5000a3c500a20a7ec270817&build=1&build_url=https%3A%2F%2Fbuild.mattermost.com%2Fjob%2Fmp%2Fjob%2Fmattermost-server-pr-new%2Fjob%2Ftranslations-20200414%2F1%2F&name=&tag=&slug=mattermost%2Fmattermost-server&service=jenkins&flags=&pr=&job=
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Uploading to Codecov

**Comment by jaydeland** [comment]
I reran the build and the same error shows up - we will have to debug tomorrow. @metanerd

**Pull request merged**
