### PR TITLE
Support darwin arm64 builds.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Adds support for building plugins to target darwin arm64 systems. This will allow plugins to do the following:

```diff
diff --git a/Makefile b/Makefile
index ca7f0bf..ef84135 100644
--- a/Makefile
+++ b/Makefile
@@ -57,6 +57,7 @@ ifneq ($(HAS_SERVER),)
 	mkdir -p server/dist;
 	cd server && env GOOS=linux GOARCH=amd64 $(GO) build $(GO_BUILD_FLAGS) -o dist/plugin-linux-amd64;
 	cd server && env GOOS=darwin GOARCH=amd64 $(GO) build $(GO_BUILD_FLAGS) -o dist/plugin-darwin-amd64;
+	cd server && env GOOS=darwin GOARCH=arm64 $(GO) build $(GO_BUILD_FLAGS) -o dist/plugin-darwin-arm64;
 	cd server && env GOOS=windows GOARCH=amd64 $(GO) build $(GO_BUILD_FLAGS) -o dist/plugin-windows-amd64.exe;
 endif
 
diff --git a/plugin.json b/plugin.json
index d0993cf..617e462 100644
--- a/plugin.json
+++ b/plugin.json
@@ -11,6 +11,7 @@
     "executables": {
       "linux-amd64": "server/dist/plugin-linux-amd64",
       "darwin-amd64": "server/dist/plugin-darwin-amd64",
+      "darwin-arm64": "server/dist/plugin-darwin-arm64",
       "windows-amd64": "server/dist/plugin-windows-amd64.exe"
     }
   },
```

#### Ticket Link

n/a

#### Release Note

```release-note
Added the ability to build plugins targeting darwin arm64 systems (ie Apple M1).
```

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
This change is not needed. `Executables` already is a `map[string]string` and supports any  platforms. `ManifestExecutables` should have been removed in `v6`, but it forget about it.

E.g. the starter template already makes use of out of darwin arm64 build: https://github.com/mattermost/mattermost-plugin-starter-template/blob/05c25c4c47d1780cbd0698da5ded65df9ff1fa85/plugin.json#L16

**Comment by mkraft** [comment]
> This change is not needed. `Executables` already is a `map[string]string` and supports any platforms. `ManifestExecutables` should have been removed in `v6`, but it forget about it.
> 
> E.g. the starter template already makes use of out of darwin arm64 build: https://github.com/mattermost/mattermost-plugin-starter-template/blob/05c25c4c47d1780cbd0698da5ded65df9ff1fa85/plugin.json#L16

I'm wondering why I had to make this change to build the app on my M1.

**Comment by hanzei** [comment]
@mkraft That could surely be the case. Plugin need to opt into the _any platform_ support by updating there dependencies. Which plugin did you try to build? Could you please test if you can build https://github.com/mattermost/mattermost-plugin-starter-template successfully?

**Review by cpanato — APPROVED** [review]

**Comment by mkraft** [comment]
> @mkraft That could surely be the case. Plugin need to opt into the _any platform_ support by updating there dependencies. Which plugin did you try to build? Could you please test if you can build https://github.com/mattermost/mattermost-plugin-starter-template successfully?

It was building https://github.com/hamzaMM/inappropriate-filter/blob/master/go.mod#L9 (using Mattermost v5.23.1).

**Comment by hanzei** [comment]
@mkraft Could you please update that to at least v5.32.0 as this includes https://github.com/mattermost/mattermost-server/pull/14682?

**Comment by mkraft** [comment]
> @mkraft Could you please update that to at least v5.32.0 as this includes #14682?

I just tested the starter template and it built for arm64. Closing this PR.

**Pull request closed without merging**
