### PR TITLE
[MM-37838]: remove feature flag for global header

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
removes feature flag `GlobalHeader`

#### Ticket Link
[MM-37838](https://mattermost.atlassian.net/browse/MM-37838)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by zefhemel — APPROVED** [review]

**Comment by michelengelen** [comment]
thanks @zefhemel ... just waiting for the related Frontend PR to be merged so we don't end up in a broken state again! :D

**Comment by jgilliam17** [comment]
@michelengelen I triggered the e2es here just to make sure we are not using/relying on the feature flag in any of our current tests

**Comment by jgilliam17** [comment]
[E2E report](https://automation-dashboard.vercel.app/cycles/b1c67008-1c5d-4850-947b-2dac2707d91b) looks good, no PR related failures.

**Review by ekrem95 — APPROVED** [review]

**Pull request merged**
