### PR TITLE
MM-51977 : Remove inconsistencies of the duplicate IDs with different defaultMessages

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Pretesting of running formatjs has revealed some warnings, such as duplicate IDs with different messages. These issues have been addressed in this PR. Furthermore, the finalized approach used in this PR has been discussed with our translators.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51977

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @M-ZubairAhmed !

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
