### PR TITLE
Fix misspellings and enable misspell on ci

### PR DESCRIPTION
**Pull request by nronas**
#### Summary
What it says on the tin. Fixes misspellings and enables `misspell` as part of ci.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-25370

#### Release Note
```release-note
Fix misspellings on various parts
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Nice. Been wanting to do this myself!

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by hanzei** [comment]
@michaelgamble There are a couple of misspells in the EE code. Would you be open on fixing those?

**Comment by hanzei** [comment]
Thank you very much for the contribution @nronas :+1:

**Pull request merged**
