### PR TITLE
GH-9630: Add GetPostsAfter() to plugin API

### LINKED ISSUE #9630: Add plugin API for GetPostsAfter method
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

The method `GetPostsAfter(channelId, postId string, page, perPage int, etag string) (*PostList, *Response) ` is available in `model/client4.go`, the Go REST API driver for Mattermost, but does not have an equivalent in the plugin API.

Not having this method in the plugin API limits what plugins can do. Hence, we would like to add an equivalent plugin API for it.

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/. Most of these methods should have fairly simple equivalents in the `app` package, making them trivial to implement.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

----

This ticket is part of a larger campaign for adding plugin API methods. See here: https://github.com/mattermost/mattermost-server/issues/9458

### LINKED ISSUE #9631: Add plugin API for GetPostsBefore method
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

The method `GetPostsBefore(channelId, postId string, page, perPage int, etag string) (*PostList, *Response)` is available in `model/client4.go`, the Go REST API driver for Mattermost, but does not have an equivalent in the plugin API.

Not having this method in the plugin API limits what plugins can do. Hence, we would like to add an equivalent plugin API for it.

Read about adding to the plugin API here https://developers.mattermost.com/contribute/server/plugins/. Most of these methods should have fairly simple equivalents in the `app` package, making them trivial to implement.

You'll want to look at these files:
* https://github.com/mattermost/mattermost-server/blob/master/plugin/api.go
* https://github.com/mattermost/mattermost-server/blob/master/app/plugin_api.go

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://pre-release.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

----

This ticket is part of a larger campaign for adding plugin API methods. See here: https://github.com/mattermost/mattermost-server/issues/9458

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR adds a `GetPostsAfter(channelId, postId string, page, perPage int)` method to plugin API.

#### Ticket Link
Fixes  #9630

### CODE REVIEW

**Comment by cpanato** [comment]
@hanzei can you please rebase this PR, then we can merge it. thanks again

**Comment by cpanato** [comment]
@hanzei can you check the build failure?

```
# github.com/mattermost/mattermost-server/app
app/plugin_api.go:326:2: syntax error: non-declaration statement outside function body
```

**Comment by hanzei** [comment]
May bad, fixed

**Comment by hanzei** [comment]
@cpanato Can this be merged?

**Pull request merged**
