### PR TITLE
[MM-41815] Fix UpdateUser Errors Not Being Handled For Custom Statuses

### PR DESCRIPTION
**Pull request by mylonsuren**
#### Summary

This PR fixes an issue where updating custom status would give a 200 success response even when the request actually failed. 

#### Ticket Link

Fixes [MM-41815](https://mattermost.atlassian.net/browse/MM-41815)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — CHANGES_REQUESTED** [review]
Good eye. Would you be able to add a small unit test for this please?

**Review by mkraft — CHANGES_REQUESTED** [review]
Instead of setting those functions as variables, you should be able to do something like this, which you can extrapolate upon for the other tests:

```diff
diff --git a/app/status_test.go b/app/status_test.go
index c7f3a45a2..888a50533 100644
--- a/app/status_test.go
+++ b/app/status_test.go
@@ -6,9 +6,13 @@ package app
 import (
 	"testing"
 
+	"github.com/stretchr/testify/mock"
 	"github.com/stretchr/testify/require"
 
+	"github.com/mattermost/mattermost-server/v6/app/users"
 	"github.com/mattermost/mattermost-server/v6/model"
+	"github.com/mattermost/mattermost-server/v6/store"
+	"github.com/mattermost/mattermost-server/v6/store/storetest/mocks"
 )
 
 func TestSaveStatus(t *testing.T) {
@@ -64,3 +68,35 @@ func TestCustomStatus(t *testing.T) {
 	require.Nil(t, err, "failed to get custom status after clear %v", err)
 	require.Equal(t, csClear, csSaved)
 }
+
+func TestSetCustomStatus(t *testing.T) {
+	t.Run("set custom status fails on get user", func(t *testing.T) {
+		th := SetupWithStoreMock(t)
+		defer th.TearDown()
+
+		fakeUserID := "foobar"
+
+		mockUserStore := mocks.UserStore{}
+		mockUserStore.On("Get", mock.Anything, mock.Anything).Return(nil, store.NewErrNotFound("User", fakeUserID))
+		var err error
+		mockSessionStore := mocks.SessionStore{}
+		mockOAuthStore := mocks.OAuthStore{}
+		th.App.ch.srv.userService, err = users.New(users.ServiceConfig{
+			UserStore:    &mockUserStore,
+			SessionStore: &mockSessionStore,
+			OAuthStore:   &mockOAuthStore,
+			ConfigFn:     th.App.ch.srv.Config,
+			LicenseFn:    th.App.ch.srv.License,
+		})
+		require.NoError(t, err)
+
+		cs := &model.CustomStatus{
+			Emoji: ":smile:",
+			Text:  "honk!",
+		}
+
+		appErr := th.App.SetCustomStatus(fakeUserID, cs)
+		require.Error(t, appErr)
+		require.Equal(t, MissingAccountError, appErr.Id)
+	})
+}
```

**Comment by mylonsuren** [comment]
@mkraft Sorry for the rebase, there were some issues with the pipeline after merging from master. I've implemented the mock store as you suggested and cleaned up the tests, so should be good for a second look.

**Review by BenCookie95 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
working as expected
image

**Pull request merged**
