### PR TITLE
MM-32048: Upgrade dependencies

### PR DESCRIPTION
**Pull request by agnivade**
Used `make update-dependencies`

```release-note
Updated Go dependencies to their latest minor version
```

https://mattermost.atlassian.net/browse/MM-32048

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by nronas — APPROVED** [review]
🎉  LGTM

**Comment by agnivade** [comment]
@lindalumitchell - can be qa-deferred.

**Comment by agnivade** [comment]
@metanerd - No saml change in this one. But please do check if there are any other libraries which don't need to be bumped.

**Review by lindalumitchell — APPROVED** [review]

**Pull request merged**
