### PR TITLE
MM-51870 Fix /test url and json

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fixed /test url and json by pointing to new server path

Note: @amyblais This should be cherry-picked for April 13th Cloud release.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51870

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM

**Review by lindy65 — APPROVED** [review]
Thanks @saturninoabril - looks good to me 👍

**Comment by saturninoabril** [comment]
@phoinixgrr @toninis @amyblais fyi, let me know if there's anything I should do. This is for the on going cloud release (Apr 13).

**Comment by amyblais** [comment]
@saturninoabril You can manually cherry-pick this to the ``cloud`` branch.

**Comment by saturninoabril** [comment]
Thanks @amyblais! Done manual cherry-pick onto the cloud branch - https://github.com/mattermost/mattermost-server/commit/38aec233e8629bb680a3df136b49d72438d7ff8f

**Pull request merged**
