### PR TITLE
[MM-28131] Fix desanitization of DataSourceReplicas and DataSourceSearchReplicas

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR fixes an issue with config desanitization that prevented `SqlSettings.DataSourceReplicas` and `SqlSettings.DataSourceSearchReplicas` from being properly migrated.

It also fixes the patch config API endpoint. The reported panic got fixed in https://github.com/mattermost/mattermost-server/pull/15262 but the original fix broke the actual patch behaviour.

@jespino 
I am adding you to review since you introduced the code I am touching in https://github.com/mattermost/mattermost-server/commit/ae328153d5d307bd5e57156906c4aa65391db717. Mainly I'd like to know if there's anything I am missing that could potentially cause problems.

#### Ticket

https://mattermost.atlassian.net/browse/MM-28131
https://mattermost.atlassian.net/browse/MM-28132

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by amyblais** [comment]
@streamer45 Jesus is off today, can another dev review this?

**Comment by streamer45** [comment]
> @streamer45 Jesus is off today, can another dev review this?

If we can wait a day more I'd really like him to have a look at this since I am touching code he wrote.
Otherwise I can assign someone else from our team.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by amyblais** [comment]
@streamer45 Please assign a QA reviewer so we can get this in for today's code freeze deadline.

**Comment by amyblais** [comment]
@streamer45 Do we know how risky this bug fix is and whether this is urgent to get into v5.27?

**Comment by streamer45** [comment]
> @streamer45 Do we know how risky this bug fix is and whether this is urgent to get into v5.27?

@amyblais 

I'd say it's not very risky. It's fixing a functionality that is not working right now so it can only improve.
As far as urgency I don't know, maybe @icelander has more information.

**Comment by icelander** [comment]
It's not urgent so if it doesn't make it to 5.27 it's okay.

**Comment by lindalumitchell** [comment]
Thanks @icelander. @jespino are there any areas of potential issues that QA should help check before merging this one?

**Comment by amyblais** [comment]
Pushing to v5.28,

**Comment by lindalumitchell** [comment]
@jespino @streamer45 just checking if there's anything in particular that QA should check on this one before approving it?

**Comment by streamer45** [comment]
> @jespino @streamer45 just checking if there's anything in particular that QA should check on this one before approving it?

Two things:

1. Patching a config with a patch object missing `ServiceSettings.SiteURL` should work.
2. Migrating a config with a non-empty `DataSourceReplicas` should not drop it but save it correctly in the new config.

**Review by srkgupta — APPROVED** [review]
Tested the following on this PR:

1. Restarted the server with empty SiteURL and the Admin console worked fine and was able to save other configs even with empty SiteURL. Also tested with valid SiteURL and no issues were found. 

2. Restarted the server with DataSourceReplicas populated in config.json and there were no issues found and site loaded fine. Also worked with empty DataSourceReplicas

Approving the PR.

**Pull request merged**
