### PR TITLE
MM-36894: Racy test: TestExecuteCommandInDirectMessageChannel

### PR DESCRIPTION
**Pull request by agnivade**
We were using the pointer to the same post object
in multiple push notifications because we were sending
it in a loop of mentioned user list.

This wasn't an issue so far, but after we started to parse
markdown in the push notification flow, we started to edit
the post struct as well.

To fix this, we move the markdown parsing deep into the push notification
construction such that we don't need to write back to the same post pointer
again.

https://mattermost.atlassian.net/browse/MM-36894

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
The post is already cloned once when the notification struct is created. But I did it again out of abundance of caution, in case the same struct is used elsewhere in future. Let me know if you prefer it to be removed.

**Comment by agnivade** [comment]
Actually, thinking a bit more, we can avoid this by doing the markdown stuff before sending it to the push notification hub. I thought of doing the parsing off the main code path. But it seems like to avoid races, we need to do a clone.

So the tradeoff is between doing a clone vs markdown parsing. :thinking:

**Review by streamer45 — COMMENTED** [review]
If the side effect isn't need elsewhere, I am wondering if this could be fixed by just moving the markdown parsing even deeper in the code, only in `buildFullPushNotificationMessage` at which point we would only care about the returned message.

**Comment by agnivade** [comment]
Nice one, I like it. :+1:

**Review by streamer45 — APPROVED** [review]
Nice :+1:

**Pull request merged**
