### PR TITLE
MM-49395: Increase compression for previews and emojis

### PR DESCRIPTION
**Pull request by agnivade**
We also reduce the max size of uploaded emojis to 512KiB.

https://mattermost.atlassian.net/browse/MM-49395

```release-note
Max size of uploaded emojis is now reduced to 512KiB
to reduce image download bandwidth.
```

[MM-49395]: https://mattermost.atlassian.net/browse/MM-49395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by noxer** [comment]
There seem to be sample files that need updating.

**Comment by agnivade** [comment]
Yep, will take a look.

**Comment by agnivade** [comment]
Done

**Review by isacikgoz — APPROVED** [review]

**Review by noxer — APPROVED** [review]
LGTM, thanks

**Pull request merged**
