### PR TITLE
MM-38122 Update to use new plugin ID for playbooks.

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Updates instances of the playbook plugin ID. 
Should be merged after https://github.com/mattermost/mattermost-plugin-playbooks/pull/740 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38122

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Should we pre-package a version with the `playbooks` id here too before merging?

**Review by cpoile — APPROVED** [review]

**Comment by crspeller** [comment]
@lieut-data It's not necessary to wait to merge I don't think since the in-between versions only effect our servers. I left in telemetry in for both.

**Pull request merged**
