### PR TITLE
[MM-10458] Change system response to "Could not find the channel" - bug fix

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Change system response to "Could not find the channel" when trying to invite user to private channel you can't see

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/MM-10458

#### Checklist
- [X] Added or updated unit tests (required for all new features)
- [X] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates

### CODE REVIEW

**Comment by jasonblais** [comment]
@DHaussermann can you help test `/invite` now works as expected?

@cpanato Can you help change the target branch to `release-4.10`?

**Comment by cpanato** [comment]
@jasonblais PR for release-4.10: https://github.com/mattermost/mattermost-server/pull/8738

Should I remove the PR for `master`?

**Comment by jasonblais** [comment]
@cpanato Yeah, we can close this one. @AndersonWebStudio handles merging changes made to the 4.10 release branch to master.

**Comment by jasonblais** [comment]
@DHaussermann pinged you at #8738 instead.

**Pull request closed without merging**
