### PR TITLE
MM-36764 mlog refactor

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR replaces mlog with a much simplified version from FocalBoard.  Removes dependency on Zap, while preserving existing functionality.

Refactoring due to new mlog:
- unit test helpers updated to use test logger
- logging configuration simplified.

**V6 Note:** This introduces a breaking change to the advanced logging configuration JSON. New docs provided in the Jira ticket. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36764

#### Release Note

```release-note
Advanced logging configuration schema changed.  This is a breaking change relative to 5.x.  See updated documentation. 
```

### CODE REVIEW

**Comment by agnivade** [comment]
Super excited for this!

I am wondering if this new refactor allows us to set the debug level output during a test via an env var/ anything else? 0/5.

I never did dig deeper though. But I always get overwhelmed by the same repetetive server startup logs for every test. So just checking if this refactor can easily make this happen. :)

**Comment by wiggin77** [comment]
> I am wondering if this new refactor allows us to set the debug level output during a test via an env var/

Yes, easy to add a feature to set test logging level via ENV var.  I didn't do any changes like that in this PR - just making sure everything works as before first.  Happy to do that in a follow-up PR.

One other note @agnivade, this PR will create merge conflicts with https://github.com/mattermost/mattermost-server/pull/18067

**Comment by agnivade** [comment]
> One other note @agnivade, this PR will create merge conflicts with #18067

No worries..

**Comment by wiggin77** [comment]
This PR needs some work around unit tests.  Will re-add reviewers when done.

**Comment by wiggin77** [comment]
Closing to re-create PR in the Mattermost repo.

**Pull request closed without merging**
