### PR TITLE
Adding enterprise commands support

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
This is a proposal to add support for commands in the enterprise version. It is
related with the future need of a command for manage advanced permissions.

To allow enterprise code to define and register commands I have to extract the common part of the commands to another package (not main) to be able to be imported (that is the cmdutils package). Basically the rest of the interesting code is in the `cmd/platform/mattermost.go` `init` function.

The new API is in the cmd/cmdutils/registry.go where It allows to register new commands. Once the commands are registered, if any of them have the same "name" (`cmd.Use`) the Enterprise command will replace the Team edition command.

### CODE REVIEW

**Comment by ccbrown** [comment]
So I'm not saying this has to be done for this PR, but this is my suggestion for the overall hierarchy of cmd/*:

* Make this `cmd/cmdutils` package the `cmd` package. The registration functions certainly aren't "utility" functions, being impure and fundamentally altering the program's functionality.
* Rename the `cmd/platform` package to `cmd/commands`, as it's a collection of command implementations.
* Move the root command to `cmd` and make `cmd/commands` also use a command registration mechanism. Expose the root command in `cmd` as a method `func Run(args []string) error`. Ideally we'd have our tests invoke this method instead of doing the re-exec trickery that they currently do.
* Create a main.go file in the root of the repo that simply invokes `cmd.Run(os.Args[1:])`. This'll make the server *kinda* go-gettable (`go get github.com/mattermost/mattermost-server && mattermost-server --help`) though all the commands will fail without configs / translations present.

**Comment by jespino** [comment]
Thanks @ccbrown, I going to try your approach :)

**Comment by jespino** [comment]
I've being making the changes, and I haven't followed some of your suggestions. For example:

1. I leave the main.go in cmd/platform/main.go, because this way we still have the "platform" binary and we don't break anything for anybody. We can create another main.go in the root directory (or a link to the platform one) but I think we can wait until we rename the platform command in v5.0.
2. I remove the "Registry", because I now expose publicly all the cobra.Command objects, so enterprise (or also plugins) could import the RootCmd or any other command, and add subcommands, remove subccommands, add extra options, or whatever.

I have to review my own code and test it against a "WIP" command that in have in the enterprise repo, to verify everything is working correctly. When it is ready to review, I will change the tags.

**Comment by ccbrown** [comment]
We can change the main package however we like and still name the executable “platform” in the distribution, which is all I think really matters. I don’t think the `go build` command that devs use to run commands from source is subject to any compatibility guarantees. It’s changed between releases in the past, and as long as the developer docs are updated, it should be fine.

**Comment by jespino** [comment]
Ok, I moved it to the root directory, changed how it is build in  build/release.mk` file (before `go install [...other-options] ./cmd/platform`, now `go build -i -o $(GOPATH)/bin/platform [...other-options] ./`) and changed how is call platform command from the Makefile (`PLATFORM_FILES` variable).

**Comment by jespino** [comment]
I think now is ready to review again @ccbrown. Thanks for your suggestions and your explanations :slightly_smiling_face:

**Comment by jespino** [comment]
It will need rebase after the saml command merge.

**Comment by jwilander** [comment]
@jespino has a PM looked at the text? Might want to get one of them to review it if not

**Comment by jespino** [comment]
We can take one PM to review the texts, but I think I didn't change any text. I only moved things to different places.

**Comment by jespino** [comment]
Another thing is that I'm not sure is a good idea to include this change in 4.8. It doesn't provide any feature or fix, and include a pretty big code restructuring, so I prefer to merge it after 4.8 release branch is created.

**Comment by jwilander** [comment]
My bad, I thought I saw some new text but I must have missed where it got moved from.

Agreed on waiting until 4.9 to merge this

**Comment by jespino** [comment]
Rebased and migrated the the new migrate_auth saml command to this new structure.

**Comment by jespino** [comment]
Rebased and waiting until tests passes, after that, I going to merge this.

**Pull request merged**
