### PR TITLE
MM-23542 add new permission PERMISSION_ACCESS_SYSTEM_CONSOLE

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary

This PR adds a new permission PERMISSION_ACCESS_SYSTEM_CONSOLE which determines if the System Console menu item should be displayed for a user in webapp.

- add to manage_system role
- include in permissions migration
- allow roles to be patched with new permission

Redux changes:  https://github.com/mattermost/mattermost-redux/pull/1110
Webapp changes:  https://github.com/mattermost/mattermost-webapp/pull/5234

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-23542

### CODE REVIEW

**Comment by mkraft** [comment]
> I don't think this makes sense as it's own permission. Your ability to access the system console should be derived from what permissions you have, not a separate permission on it's own. (If I take this away you can still do everything though the API).
> 
> This is also dangerous from a security perspective because it could confuse users into thinking they have actually removed those permissions when they actually have not.

To agree with this and add some further commentary, I think it's important that permissions not be added that are tied to the UI, avoiding things like: `action_some_page` or `action_some_widget` or `action_some_subset_of_the_system_console`. 

Permissions should continue to be `action_[optional_scopes]_model` where model/models are things like "posts" and "ldap" and "webhooks" that can be transferred to any part of the UX, API, CLI, etc.

One example of why this is important: say we had a permission `administer_system_console_groups_section` and then we invent a chat-facing UX for doing the same things. We would need a completely different permission for the chat-facing thing.

**Comment by wiggin77** [comment]
@grundleborg should I close these PRs for now?

**Comment by grundleborg** [comment]
Sorry @wiggin77 - this is my fault - I can see I should have confirmed the details with others before making this ticket, because there's very clear and justified disagreement with the approach I suggested. I agree it makes sense to close the PR.

**Comment by wiggin77** [comment]
Closing as new permission for system console access is not desired.

**Pull request closed without merging**
