### PR TITLE
Add output indicating success for restore channel command

### PR DESCRIPTION
**Pull request by vesari**
#### Summary
Add output indicating success for restore channel command. 

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/13144

### CODE REVIEW

**Comment by vesari** [comment]
I've submitted a draft PR as I wanted to make sure this addition is what you were expecting. Could you please also confirm that the Elasticsearch problem, originally part of this task, has been handled in an internal ticket and no action is required from my side with regard to this? Thank you! :)

**Comment by jwilander** [comment]
Looks good @vesari 👍 And yes, don't worry about the Elasticsearch error

**Comment by jasonblais** [comment]
@ogi-m Friendly reminder to help with PR review :)

**Pull request merged**
