### PR TITLE
Add ShowFullName property

### PR DESCRIPTION
**Pull request by shred86**
#### Summary

Adds the `ShowFullName` property to be used by the mobile app the same way `ShowEmailAddress` is being used for the user profile view.

#### Ticket Link

Related to:
- PR in mattermost-mobile [#4106](https://github.com/mattermost/mattermost-mobile/pull/4106)
- PR in mattermost-mobile [#4092](https://github.com/mattermost/mattermost-mobile/pull/4092)

### CODE REVIEW

**Comment by enahum** [comment]
I guess that is a question for PM

**Comment by marianunez** [comment]
> I guess that is a question for PM

@esethna thoughts on the above.

**Comment by esethna** [comment]
The config setting doesn't appear to be deprecated in the config documentation, so I would expect it's respected on the clients:

image

If webapp is ignoring this setting I would consider that a bug we should file a ticket for (unless I'm misunderstanding the conversation).

**Comment by enahum** [comment]
@esethna can you then confirm what's next? is this indeed an issue or was removed from the webapp on purpose? I have no knowledge on this.

**Comment by esethna** [comment]
cc// @thefactremains can you help with next steps on this? ^ Not sure if there's additional context here

**Comment by thefactremains** [comment]
It seems that currently neither the `ShowFullName` setting nor `ShowEmailAddress` are being honored (webapp or mobile). I will add a couple of bug tickets to get this corrected in webapp.

**Comment by shred86** [comment]
When I was testing this, setting Show Full Name and Show Email Address to false in the system console appeared to be working in both the web app and mobile app. On the mobile app specifically, I noticed the changes took effect immediately but for the full name field, it would still be displayed (this was testing with a PR I made to display full name in the profile view) until you viewed a profile you hadn't viewed previously.

My assumption was because when those settings are set to false, the database doesn't return the email address or full name, thus it won't be displayed. However, if it's cached on a users device (i.e. you viewed that same profile recently), the full name would still show up because a `ShowFullName` property does not exist. The email address would be hidden because a `ShowEmailAddress` property does exist.

Hopefully that makes sense - just my observation.

**Comment by teresa-novoa** [comment]
@enahum friendly reminder as looks like you are a pending reviewer, thanks!

**Comment by teresa-novoa** [comment]
Thanks @enahum! @thefactremains can you please check this PR?, Elias said: _"Code looks good, just not sure if we expect this setting to be used or not.. that would be a PM decision."_ Thanks!

**Comment by thefactremains** [comment]
I am good with this - assuming that when `ShowFullName` is set to false, the user's name is not displayed. For visibility, we are working on this change soon as well: https://mattermost.atlassian.net/browse/MM-24690

**Comment by shred86** [comment]
Unfortunately, I don’t know Go so I’m not entirely sure what needs to be added. Would you be able to provide an inline comment with what I need to add to the tests and I’ll make the correction and push the change?

I simply followed the how `ShowEmailAddress` was being exposed to the mobile app and made the changes based on that for `ShowFullName` since the setting already appeared to exist, just not exposed to the mobile app.

**Comment by marianunez** [comment]
> Unfortunately, I don’t know Go so I’m not entirely sure what needs to be added. Would you be able to provide an inline comment with what I need to add to the tests and I’ll make the correction and push the change?
> 

You can add a test case just like this https://github.com/mattermost/mattermost-server/blob/f51c4f18f007494c3858fd029bf76819ff12ff1e/config/client_test.go#L115-L127 but for `ShowFullName` setting. Let me know if you need more help with adding that case.

**Comment by teresa-novoa** [comment]
@jasonblais where are we with this PR? Thanks!

**Comment by jasonblais** [comment]
Hi @shred86, thanks for the updates! I see you added a test case, let us know if you feel it's ready for a second review from Maria.

@thefactremains if you're good with the changes, can you help approve the PR so it appears as such in the PR summary? Thank you!

image

**Comment by hanzei** [comment]
@enahum Should this PR go into `v5.24.0` given that https://github.com/mattermost/mattermost-mobile/pull/4092 is targeted for `v1.32`?

**Comment by enahum** [comment]
0/5 @hanzei PM should decide

**Comment by shred86** [comment]
Just want to make sure this doesn't get lost but once this PR is merged, [#4106](https://github.com/mattermost/mattermost-mobile/pull/4106) in mattermost-mobile will need to be merged and then a change can be made to incorporate it into the mobile app profile view.

I'm not sure how changes this like are usually rolled out but it would seem to me this would be a "breaking" change in the mobile app in the sense that you need to have the latest mattermost server that supports the `ShowFullName` property. Otherwise, I'd imagine you would receive an error in the mobile app. I could be completely wrong though.

**Comment by jasonblais** [comment]
@thefactremains FYI on the above conversations about version numbers and backwards compatability

image


@shred86 curious if there's a way to support backwards compatibility to avoid a breaking change? E.g. with an if statement (if server version >= XXX, use `ShowFullName` property, else fall back to previous method).

**Comment by thefactremains** [comment]
> @enahum Should this PR go into `v5.24.0` given that [mattermost/mattermost-mobile#4092](https://github.com/mattermost/mattermost-mobile/pull/4092) is targeted for `v1.32`?

@hanzei yes. I would prefer to get it into 5.24

**Comment by enahum** [comment]
@amyblais ☝️, not sure if it should be included at this point for 5.24, your call

**Comment by amyblais** [comment]
We're past feature complete for v5.24 and it is a little too late to introduce a new breaking change to the release. https://github.com/mattermost/mattermost-mobile/pull/4092 is not making use of this setting yet. Removing ``CherryPick/Candidate`` label,

**Comment by thefactremains** [comment]
@amyblais understood. I'm also glad to know that https://github.com/mattermost/mattermost-mobile/pull/4092 is not making use of the setting. thank you!

**Comment by shred86** [comment]
I'm probably missing something here but this PR is not a breaking change. It's simply making the `ShowFullName` property available for use. mattermost/mattermost-mobile#4092 doesn't use this setting because it's not available, hence the reason this PR exists. So in my mind:

Step 1: Make the `ShowFullName` property available (this PR).
Step 2: Create a new PR in mattermost-mobile to use the newly available `ShowFullName` property.

**Pull request merged**
