### PR TITLE
MM-23706 search executable dir before working dir when looking for i18n

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary

This PR fixes a bug where during server start-up, it searches for the `i18n` directory using paths relative to the current working directory. The search priority is:

- .
- ..
- ../..
- ../../..

When launching server with a working directory of `/opt/mattermost/client` it first searches for `i18n` within `client`, finds the webapp’s `i18n` directory and tries to parse those files as server language translations. Webapp translation files are not compatible and thus it fails.

To fix, a change was made to ensure directories relative to the executable are searched first when looking for `i18n`.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/14184

https://mattermost.atlassian.net/browse/MM-23706

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @wiggin77 - can you help provide test steps please?

**Comment by wiggin77** [comment]
> Hi @wiggin77 - can you help provide test steps please?

Hi @lindy65  Sorry about that.  Test plan is now in the ticket https://mattermost.atlassian.net/browse/MM-23706

**Comment by lindy65** [comment]
Thanks @wiggin77 and no worries :)

I'm going to request review from one of the QA SDETs as I don't have a local set-up. I'll switch out the QA reviewer soon...

**Comment by lieut-data** [comment]
One thought: I've added @hmhealey as dev reviewer to ensure this works with the GitLab deployment model, which has a unique directory layout IIRC.

**Comment by wiggin77** [comment]
Hi @hmhealey , any chance you can look at this?

**Comment by hmhealey** [comment]
The code for this looks good, but this is definitely something that should be tested with GitLab. I think their working directory is set to where the `i18n` folders are stored, but I want to double check that since it has caused issues like Jesse mentioned.

I'll make a note to go test out a build of that. Hopefully I can get to it today or tomorrow.

**Comment by hmhealey** [comment]
I tested running this version of Mattermost with GitLab and running CLI commands [using these steps](https://docs.gitlab.com/omnibus/gitlab-mattermost/#mattermost-command-line-tools-cli), and it looks good to me

**Comment by wiggin77** [comment]
Hi @prapti , any issues with getting this into 5.24?  I know you're busy - just checking if this needs to be deferred.

**Comment by prapti** [comment]
Testing now @wiggin77! Will ping you on DM for questions.

**Pull request merged**
