### PR TITLE
MM-26441 - fix for doPluginRequest

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Fix for a bug accidentally introduced by #14366 (because #14557 was merged while it was under review): the provided values were being overwritten by the rawQuery params. 
- Now we're merging them both.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-26441

### CODE REVIEW

**Comment by cpoile** [comment]
@lieut-data Done!  (Incidentally, unless I'm mistaken, I think we're missing tests for dynamic autocomplete (which would have caught this bug, too--because the `user_input` and `parsed` params were being lost). But these tests will catch such a regression in the future.

**Comment by cpoile** [comment]
@DHaussermann Considering this is a fix for a previous PR (which couldn't be tested), but now has unit tests, can we skip manual tests again?

**Comment by cpoile** [comment]
@amyblais Can this be cherry picked for 5.25?

**Comment by amyblais** [comment]
Yes, sure.

**Comment by DHaussermann** [comment]
@iomodo  or @cpoile Can you pleae provide guidance or steps for testing on this?  Did the related issue introduce a problem with slash command auto-complete that I can see and validate with functional testing?

**Comment by cpoile** [comment]
@DHaussermann It would be very difficult to test without a bunch of coding (or impossible), since it only pops up in the middle of an dynamic autocomplete call. That's why I think the unit tests are as good as we're going go get for this.

**Comment by cpoile** [comment]
@metanerd Thank you so much!

**Pull request merged**
