### PR TITLE
Ensure specific PostgreSQL full text idx is used

### PR DESCRIPTION
**Pull request by feikesteenbergen**
Addresses issue #9016

A function based (gin) index is defined on some columns.
For PostgreSQL to use a function based index, the WHERE parameter needs
to match the function
None of these queries have a matching WHERE parameter with the function
in the index, therefore, the index cannot be used to satisfy the given query.
As the schema has a lot of indexes, PostgreSQL still uses an index for
most queries it seems, so seeing full-blown Seq-Scan should be rare,
however when searching for a string in a given message, it would be most
useful to be able to use the full text search index.

Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
[A brief description of what this pull request does.]

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Hey @feikesteenbergen - sorry for the delay in responding here. We're having some conversations about the changes, I'll share with you soon!

Many thanks for your help here :)

**Comment by jasonblais** [comment]
Hello @feikesteenbergen, 

Highly appreciate your contribution and the detailed analysis you shared with us in the GitHub issue.

While the execution time for the query you shared was faster with the GIN index, we're not able to accept a PR at this time and it is completely our fault for communicating this incorrectly to you earlier. The reasons are:

1) the changes are high risk as the new code likely has some behavioural differences for non-English semantics. Hence, this requires significant testing effort to find potential edge cases;
2) despite the changes in execution time, the change is considered low impact because it's not currently a bottleneck for system performance for searching posts on PostgreSQL.

We're very thankful that you're part of the Mattermost community and are sorry that we cannot accept the PR at this point. You've triggered a conversation on what kinds of changes we're open to accepting that are related to performance to avoid this situation from happening in future.

We'll also keep the associated JIRA ticket open, so that we can revisit at a later time. I've also linked your PR in that ticket.

Let me know if you have any questions or comments?

**Comment by feikesteenbergen** [comment]
> the changes are high risk as the new code likely has some behavioural differences for non-English semantics.

Sure, that's why I was hesitant to create a pull request, but as nothing is being done, I thought I'll create one.

> the change is considered low impact because it's not currently a bottleneck for system performance for searching posts on PostgreSQL.

That is not true, at least not for me (I might be a black swan though)

As a followup: As you're not using the index for searching, you're only creating overhead when creating the indexes, which is detrimental to performance. So either fix the search using the index, or drop the index, the current state is neither here nor there.

**Comment by lieut-data** [comment]
@jespino, I wonder if you might be able to take a closer look at this issue and accompanying PR? @feikesteenbergen provided a lot of detailed analysis which showcased the bottleneck in his system, and I think it would be worthwhile to have an extra set of eyes on this to understand where it fits in the grander scheme of performance.

@feikesteenbergen, might you able to clarify the significant of hard-coding `english` in the `to_tsvector` invocation? I confess I haven't done the research here to understand what's going on under the covers, but naturally we'd want to converge on something that made sense for our international audience. I know there's a lot of "baked-in" assumptions that customers will set their database locales accurately, and I don't think we do a good job of clarifying that, but I definitely wouldn't want to make it "worse".

**Comment by jespino** [comment]
@lieut-data I'll try to review it during the next week, if you don't mind, I'm still landing from my wild January.

**Comment by feikesteenbergen** [comment]
@lieut-data I would probably not hardcode the value, however the index definition itself is also hardcoded here:

https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/supplier.go#L776

I'm unfamiliar with both:

* your codebase
* golang

So the pull request was meant more to show you guys where the fix could go in. Probably the language setting is something configured in the database, (but I can't find it) as the index needs to match the where clause anyway.
In the mattermost instance we're using, this is the index definition:

```
    "idx_posts_message_txt" gin (to_tsvector('english'::regconfig, message::text))
```

Even if the function in the index and the function in the where clause do not match, the worst that will happen is that the index is skipped, which is exactly what is currently the case anyway.

**Comment by lieut-data** [comment]
Thank you for the additional detail, @feikesteenbergen -- I agree with your analysis, and recommend that we proceed with your proposed change to at least hard-code the value where we use it. We should be able to verify the performance improvements using our loadtesting framework -- as it happens, this is precisely something @jespino and I will be using together shortly.

I'm going to re-open this given our discussion. Thanks for your patience :)

**Comment by jasonblais** [comment]
@lieut-data Is there a next step on how to proceed?

**Comment by hanzei** [comment]
@lieut-data Gently reminder about the above question. https://github.com/mattermost/mattermost-server/pull/9893#issuecomment-483622080

**Comment by lieut-data** [comment]
@jasonblais, @hanzei -- the changes here are believed to be good, but I haven't been able to find the time to loadtest the behaviour. We don't have a great setup for load testing PostgreSQL right now.

I'd be fine merging this as-is -- assuming buy-in from @jespino -- and leaving testing our regular PostgreSQL release testing.

**Comment by lieut-data** [comment]
I note that we will need @feikesteenbergen to sign the CLA before we can merge as well.

**Comment by jespino** [comment]
@feikesteenbergen We need you to sign the CLA before we get the PR merged.

**Comment by icelander** [comment]
@feikesteenbergen Have you had a chance to sign our CLA?

**Comment by svelle** [comment]
Hey @feikesteenbergen, really appreciate the contribution! 

Would you be open to help complete the [Mattermost contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/), after which we can merge your work? If you have any questions, don't hesitate to let us know.

We'll consider opening a pull request, if we don't hear back in about a week's time.

**Comment by jasonblais** [comment]
Hey @feikesteenbergen - given we haven't received an update about the CLA, we've reopened your PR here: https://github.com/mattermost/mattermost-server/pull/11022

Thanks again for your contribution and all of your analysis!

**Pull request closed without merging**
