### PR TITLE
MM-42282: handle teamId parameter correctly

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
As per https://community-daily.mattermost.com/core/pl/ugs7ue6e4j8a7cgegk1bxje8to, `ThreadStore.GetThreadsForUser` accepts a `teamId` parameter, but incorrectly handles an empty value of `""` as looking only for channels with an empty `teamId` (aka DMs and GMs) instead of finding all channels and effectively ignoring the team property. Fix the query here, and extend unit test coverage at the store level to verify same.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-42282

#### Release Note
```release-note
Fixed ThreadStore.GetThreadsForUser to count correctly when no team id is specified.
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Great stuff!

**Review by anurag6713 — APPROVED** [review]

**Comment by lieut-data** [comment]
@jgilliam17, I tried running `/e2e-test` manually this time, but I admit I'm not sure how to find the results as you did previous. Can you help teach me and spot check anything related to CRT?

**Comment by jgilliam17** [comment]
Thanks for running the E2Es @lieut-data, I'll take a look when the report posts.
Going forward, don't hesitate to ping anyone from QA to check the report for you on any PR.

For future reference when deferring QA: 
 Results can be found [here](https://automation-dashboard.vercel.app/cycles) or in [qa-test-automation-reports](https://community-daily.mattermost.com/core/channels/qa-test-automation-reports) channel. 
QA Channel link leads to a report that may be slightly easier to read ( < I personally prefer this one)
Once you have the PR E2E report, look for the report from master that posted recently, in `qa-test-automation-reports` channel it will have a text similar to this 

E2E for Master Nightly Build (Prod tests)
[98.25% (1569/1597) in 522 suites](https://mattermost-cypress-report.s3.amazonaws.com/158134-onprem-ent-master-mm-ee-test:test/mochawesome.html) | 289.93 mins | [Recorded test executions](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testPlayer/MM-R2755)

I usually open both reports, PR and master, side by side, select failed list, and compare the failures. Each test case I confirm as also failing on the master, I would collapse (click on test header) to hide the error.  I would return to re-test/check all the uncollapsed tests manually and to read the error in detail if any.
See sample screenshot below. Hope this helps.

Screen Shot 2022-03-07 at 4 45 59 PM

**Comment by lieut-data** [comment]
Thank you for the overview, @jgilliam17! I /think/ I found the run at https://automation-dashboard.vercel.app/cycles/9342562a-93e0-4f10-a2d0-6b2bf8fce9e8, but it seems like it failed to actually run any tests, but instead timed out? Did I run the command too early in the pipeline?

**Comment by jgilliam17** [comment]
There was an issue with the cypress pipeline, unrelated to this PR. I'll re-run E2Es

**Comment by lieut-data** [comment]
Thanks, @jgilliam17! Taking a look at https://automation-dashboard.vercel.app/cycles/1c6a72ea-07d6-43f7-b652-150f9cb001a4, it seems like most passed. Is there a master with CRT enabled that I should compare against specifically?

**Comment by jgilliam17** [comment]
I've started one [here](https://automation-dashboard.vercel.app/cycles/77756eda-c835-4e5f-aa75-b906a8322320) and will compare reports when run competes.

**Comment by jgilliam17** [comment]
@lieut-data E2E reports compared: few failures differ from master report, but are mainly related to images not PR changes.

**Comment by jgilliam17** [comment]
For manual testing, which area of the app is directly affected?

**Comment by lieut-data** [comment]
@jgilliam17, I believe the primary area of focus should be the `Threads` interface in the LHS.

**Review by jgilliam17 — APPROVED** [review]
Thanks @lieut-data 
Tested, looks good to merge.
- Verified Threads sidebar item bolding, unbolding, mentions and count - as expected.

**Comment by lieut-data** [comment]
Thank you, @jgilliam17!

**Pull request merged**
