### PR TITLE
MM-48048 - Update HTML lang attribute when a user updates locale

### PR DESCRIPTION
**Pull request by gitstart**
### Summary
The HTML tag always has lang="en" even if the language in settings is set to a different language

#### Fixes https://github.com/mattermost/mattermost-server/issues/21552

Moved from https://github.com/mattermost/mattermost-webapp/pull/12159

#### Demo video
https://www.loom.com/share/19060c7452614ae984e31bc3fb757223

#### Release note
```release-note
Updates HTML lang attribute when a user updates locale
```

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@stevemudie gentle ping on this one :)

**Review by yasserfaraazkhan — APPROVED** [review]
@M-ZubairAhmed , e2e seems to time out. I did a smoke test locally to make sure no flow is broken when changing lang

**Comment by saturninoabril** [comment]
@yasserfaraazkhan This is still a known issue about building image with PR from forked repo.

**Comment by M-ZubairAhmed** [comment]
@yasserfaraazkhan you need to do the duplicate PR approach, is that right @saturninoabril ?

**Comment by yasserfaraazkhan** [comment]
> @yasserfaraazkhan you need to do the duplicate PR approach, is that right @saturninoabril ?

@M-ZubairAhmed , https://github.com/mattermost/mattermost-server/pull/23074
was able to run it , nothing failed with current changes

**Comment by hangyas** [comment]
@M-ZubairAhmed was this PR closed on purpose? The issue still exists and it's causing us problems when Google Chrome decides to translate the page for some users (to the same language but replacing random words)

**Comment by M-ZubairAhmed** [comment]
@hangyas the PR was closed by the author. the issue is still open here https://github.com/mattermost/mattermost/issues/21552

**Pull request closed without merging**
