### PR TITLE
[MM-31277]: Change default MaxFileSize from 50Mb to 100Mb

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary

This PR aims to solve #16664 

#### Ticket Link

Issue: #16664 
JIRA: https://mattermost.atlassian.net/browse/MM-31277

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hahmadia — CHANGES_REQUESTED** [review]
Hey! I think rather than putting 100MB as bytes, you can make the code a little bit more readable by doing the following:

In `model/utils.go`, put a constant in the `const` section `MB = 1 << 20`.
`model/utils.go`
```
const (
	LOWERCASE_LETTERS = "abcdefghijklmnopqrstuvwxyz"
	UPPERCASE_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	NUMBERS           = "0123456789"
	SYMBOLS           = " !\"\\#$%&'()*+,-./:;<=>?@[]^_`|~"
	MB                = 1 << 20
)
```

Then here, you can do a `MB * 100` just so the code would be more readable.
Thanks! Appreciate the change.

**Comment by hahmadia** [comment]
Don't forget to press this button once you address the comment so I can be notified to re-review this PR! Thanks
image

**Review by hahmadia — APPROVED** [review]
Great! Thanks

**Comment by hahmadia** [comment]
@hmhealey Bump. Could you review this when you have time. Thanks

**Review by hmhealey — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Looks good to me
New test case has been created 
[MM-T1169](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T1169)

image

**Pull request merged**
