### PR TITLE
Ability to make "message" and "reply" interactive actions.

### PR DESCRIPTION
**Pull request by bezumkin**
#### Summary
This PR extends interactive buttons functionality by adding 2 new response types of [interactive messages](https://docs.mattermost.com/developer/interactive-messages.html): `reply` and `message`. If you click on this buttons - you will create a new message in current dialog.

It is needed for better experience when you have chat with a bot.

####
[Watch demo](https://file.modx.pro/files/c/e/7/ce74370d8e67f7a7f4cf19642fedf63b.mp4)

I'm [using this python bot](https://github.com/attzonko/mmpy_bot), here is the code of the demo
```python
channel_id = message['post']['channel_id']
if message['post']['message'] == 'Regular message':
    self._client.api.create_post(user_id=None, channel_id=channel_id, message='Thank you!')
elif message['post']['message'] == 'It is reply':
    self._client.api.create_post(user_id=None, channel_id=channel_id, message='Nice reply!',
                                 pid=message['post']['id'])
else:
    self._client.api.create_post(user_id=None, channel_id=channel_id, message='', props={
        'attachments': [{
            'fallback': 'Hello!',
            'text': 'Please, select your action',
            'color': '#59afe1',
            'actions': [{
                'name': 'Answer as regular message',
                'response_type': 'message',
                'integration': {
                    'context': {
                        'action': 'Regular message',
                    }
                },
            }, {
                'name': 'Answer as reply to thread',
                'response_type': 'reply',
                'integration': {
                    'context': {
                        'action': 'It is reply',
                    }
                }
            }]
        }]
    })
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

Recreated PR from #10046

### CODE REVIEW

**Comment by jasonblais** [comment]
@levb I think you had a recommended approach for this feature, would you be open to sharing it here?

**Comment by hanzei** [comment]
Hey @bezumkin,

Sorry for letting this one be stale.

I wonder what the use case for this. I can't think of a one.

**Comment by bezumkin** [comment]
@hanzei Please [watch this](https://file.modx.pro/files/c/e/7/ce74370d8e67f7a7f4cf19642fedf63b.mp4)

**Comment by hanzei** [comment]
Sure, I see _what_ this, but _why_ do you need this? The video is more like a demo.

**Comment by bezumkin** [comment]
@hanzel Right now I moved one company from Telegram to Mattermost and they use chat-bot for selling reports.

Bot asks questions:
- please select region
- please select city of region
- please select mobile operator of this city
- please type phone number of customer

So, user should have ability to type phone number to bot. That is why I cant use outgoing hooks, and use real chat bot via API.
And user don't want to type city and mobile operator each time, because of time and typos.

And if we have chat bot, why we need to send actions to it with separate POST requests to some connector, if we can just send him a message from given actions? So, lets create messages from actions!

It is small improvement, but it will allow to create complicate chat bots.

**Comment by hanzei** [comment]
I'm still not fully getting why this change is needed to full fill your use case.

With this PR Users will be able to respond to a post by clicking on a integration action with a _static_ message. This is very limited. How does this help your use case? Who is the one creating the post action? The bot? If you are using the REST API, why don't you create the posts via the API?

I'm just trying to understand how this feature can be used.

**Comment by bezumkin** [comment]
@hanzei 
> With this PR Users will be able to respond to a post by clicking on a integration action with a _static_ message.

Yes, static message without typos.

> Who is the one creating the post action? The bot?

Yes

> If you are using the REST API, why don't you create the posts via the API?

Bot uses REST API, and I don't want to make warkaround sending some messages to API and others to Bot.

**Comment by levb** [comment]
@bezumkin, I agree that we should better address creating new messages from PostActions, but no specific proposal for how to work it into the current API has been found acceptable. I suggest that we resort to using the REST API, as @hanzei suggested for the time being.

When the time comes for the next API revision we should find more consistency across CommandResponse, PostActionResponse, and CreatePost() API.

**Comment by bezumkin** [comment]
@levb I don't see how I can create message from user by REST API, because it requires token, but POST action will send only `context` property from Bot, that doesn't know user token and couldn't fill this property.

That is what I'm trying to achieve - https://core.telegram.org/bots#keyboards

**Comment by hanzei** [comment]
You're correct, you can achieve what you want with just a outgoing webhook. But this is also part of a security concept.

Instead you can:
- Use personal access token
- Write this as a plugin

**Pull request closed without merging**
