### PR TITLE
[MM-34840] Remove the Remove System Permissions

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

We should stop removing the old system console section permissions for a while since people who upgrade then downgrade get a funky and whacky system console. It's better to keep them for the time being.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34840

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]

**Review by sbishel — APPROVED** [review]
Hey Hossein. Let's create a ticket to remove these in a few releases.

**Comment by hahmadia** [comment]
> Hey Hossein. Let's create a ticket to remove these in a few releases.

@sbishel 
Done!
https://mattermost.atlassian.net/browse/MM-34887

**Review by furqanmlk — APPROVED** [review]
LGTM

**Pull request merged**
