### PR TITLE
MM-10319: Use normalized email for Saml (migration)

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
I normalized all the emails stored in the AuthData of the users in the saml
authentication and migration. This migration normalize the AuthData for the
existing saml accounts.

My unique concern here is that now can exists 2 accounts with the same AuthData
(email) with different case, and if this happens for 2 different accounts with
saml authentication, the migration will fail.

#### Ticket Link
[MM-10319](https://mattermost.atlassian.net/browse/MM-10319)

#### Checklist
- [x] Has enterprise changes (https://github.com/mattermost/enterprise/pull/284)
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
We should probably give Shift and any other large customers using SAML a heads up about this. They may want to run this themselves first as large updates have been known to cause replication lag. FYI @jasonblais @esethna

**Comment by jasonblais** [comment]
@jespino To confirm, will this fix an issue reported by customer here: https://pre-release.mattermost.com/core/pl/uq4g7eqght81j8snqxbe5n1zjh

@jwilander Okay, noted.

**Comment by lieut-data** [comment]
@jespino, this migration might fail too, right, if there's already a duplicate?
```
table.ColMap("AuthData").SetMaxSize(128).SetUnique(true)
```

Instead of modifying the data, is it feasible to modify the queries, e.g. `WHERE LOWER(AuthData) = ...`? I know this can be indexed in Postgres, thought I don't believe that's possible in MySQL. That being said, I don't think our `Users` table is generally so big as to be a problem?

**Comment by lieut-data** [comment]
Also, can you point me at where we always save `LOWER(AuthData)` for SAML, preventing future records from being created with mixed case? Should we be doing that directly in the stores?

**Comment by jespino** [comment]
It is not so simple, is something done at application level because depending on the kind of AuthService you may want or may not want to lowercase the AuthData. I can think in something like a Base64 encoded "Id", where case has important meaning. Currently it is done at application level for SAML AuthData.

About `WHERE LOWER(AuthData)` would be indexable in postgres, but not in MySQL. We can assume that the number of users in the instances aren't so big, but we will must accept that each login implies a full scans of the users table. If that is acceptable, I'm ok. (in this case we can be apply it to the SAML queries only, which is ok).

**Comment by lieut-data** [comment]
I suspect that a one time migration will serve us better than an ongoing impact against the `Users` table, so I'm fine with the changes as-is. Thanks for clarifying :)

Regarding a potential migration failure, will this prevent the server from starting until the data is fixed manually? Would there be a case to make this a user-driven upgrade note vs. something automatic?

**Comment by jespino** [comment]
Actually, I think we must have that kind of feature for all the migrations, something like a settings for "ManualMigrations" (false by default), and a platform command to run the migrations manually.

**Comment by jasonblais** [comment]
@jespino FYI, a note from a customer:

> I actually don't think [...] would have helped us at all... I had to set authdata to mixed case for users to be able to log in

https://pre-release.mattermost.com/core/pl/mc8o8wwzq7ymmj1mdsj9fj3t5w

**Comment by jespino** [comment]
Thanks @jasonblais, the concerns of the customer makes sense because he only knows this PR, but the PR in the enterprise repo completes the solution, and would work correctly for him.

**Comment by jasonblais** [comment]
@jespino Thanks sounds good. I'm also gathering a list of customers that would be affected by this and notify them ahead of the release.

I'll also add an upgrade notice for it.

**Comment by jasonblais** [comment]
@jespino @jwilander Is there any rough idea on what a "large" customer would mean in this context? Is it larger than 10K users for instance? Or should we just let all SAML customers know about it?

**Comment by jwilander** [comment]
@jespino another concern is replication lag between the master and any slaves. We've seen that large updates can cause big replication lag, at least on Aurora. That can really lock up the DB sometimes.

@jasonblais I'd suggest we communicate to any customer using SAML that they should perform this upgrade off peak hours at minimum. I don't expect the update time will be too bad but if the DBs are already under a lot of load the system could have long response times as a result until the upgrade and replication completes

**Comment by jasonblais** [comment]
So, something like this? https://github.com/mattermost/docs/pull/1987

**Comment by jwilander** [comment]
Yes that looks good. I'd also mention the change is not backwards compatible so it won't work with old MM versions so once they run the SQL they need to upgrade to 4.10 immediately, right @jespino? 

Also wouldn't hurt to mention they should be backing up their DB beforehand as well

**Comment by jasonblais** [comment]
> so it won't work with old MM versions so once they run the SQL they need to upgrade to 4.10 immediately,

@jwilander I see, maybe in that case we wouldn't include that piece in the upgrade note since it could cause issue, but provide it as an option when we email to our largest customers.

> Also wouldn't hurt to mention they should be backing up their DB beforehand as well

Yeah, this is already in our upgrade guide.

**Comment by jespino** [comment]
> Yes that looks good. I'd also mention the change is not backwards compatible so it won't work with old MM versions so once they run the SQL they need to upgrade to 4.10 immediately, right @jespino?
That is half true, eventually it can work if all the accounts in the saml server use lowercase emails. If not, there will be problems. But for me make sense to "generalize".

> So, something like this? mattermost/docs#1987
I see a problem with the suggested "pre-upgrade" query execution. This query execution before the deployment, will do the changes, but wont prevent the "re-execution" of the query during the proper migration process. The proposed procedure doesn't allow to avoid the migration at first new server version run.

**Comment by jasonblais** [comment]
Okay, so sounds like we should include this as the upgrade note, 

> Those servers with SAML authentication enabled should upgrade during non-peak hours. SAML email addresses are migrated to lowercase to prevent login issues, which could result in longer than usual upgrade time and replication lag. 

and then let Shift know about the database upgrade query since they handle upgrades differently.

@jwilander @jespino

**Comment by jwilander** [comment]
I'd omit the replication lag part, it sounds scary and it isn't really useful information here

**Pull request merged**
