### PR TITLE
MM-41191: Apply upload_sessions incorrect index fix

### PR DESCRIPTION
**Pull request by agnivade**
This was supposed to be fixed via https://github.com/mattermost/mattermost-server/pull/19155, but then morph got merged first. So we apply the same fix in the new model.

https://mattermost.atlassian.net/browse/MM-41191

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@isacikgoz  - There seems to be some difference during manually running morph to run the migration in case of MySQL. It fails with a syntax error, but that passes when I run it via Mattermost. Something to look into later.

**Review by streamer45 — APPROVED** [review]
:+1:

**Comment by agnivade** [comment]
@isacikgoz - Going to merge this because I need to backport to cloud before 6.4 gets cut.

**Comment by agnivade** [comment]
@amyblais - Requesting a cherry pick to cloud.

**Comment by isacikgoz** [comment]
> @isacikgoz - There seems to be some difference during manually running morph to run the migration in case of MySQL. It fails with a syntax error, but that passes when I run it via Mattermost. Something to look into later.

@agnivade I think it was due to unicode escape sequences in the DSN and it was not parsing the multiple statements parameter.

**Comment by agnivade** [comment]
Oh I see .. wondering if we could detect that while running the CLI and throw a better error?

**Comment by agnivade** [comment]
SGTM.

**Pull request merged**
