### PR TITLE
Fix username uniqueness unit test

### PR DESCRIPTION
**Pull request by mehran-prs**
#### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Hello @mehran-prs - could you clarify which two unit tests are fixed and why?

**Comment by mehran-prs** [comment]
Hello @agnivade 
Sure, 

Acutely the fix is on two assertions of one unit test :) (I'll change the title):

__The first assertion:__ its purpose is to make sure the `username` of users will be unique.
So it assigns the `username` of the first user(`u1`) to the second user(`u2`), but it tries to store the first user in the database instead of trying to store the second user to get the error.

__The second assertion__ is the same, but with an empty `username` for `u2` and again it's saving the first user while we didn't change it.

I hope I've not misunderstood it :)

**Review by agnivade — APPROVED** [review]
Thank you, nice catch!

**Comment by agnivade** [comment]
@spirosoik - It looks like Akis and Mustafa are on PTO. The docker build step is failing with 

```
#0 3.954 E: Version '1.17-3+deb10u3' for 'libkrb5support0' was not found
#0 3.954 E: Version '1.17-3+deb10u3' for 'libk5crypto3' was not found
#0 3.954 E: Version '1.17-3+deb10u3' for 'libkrb5-3' was not found
#0 3.954 E: Version '1.17-3+deb10u3' for 'libgssapi-krb5-2' was not found
```

Would someone be able to take a look?

**Pull request merged**
