### PR TITLE
[MM 12458] Include user preferences in bulk export

### PR DESCRIPTION
**Pull request by dos1701**
#### Summary
Implement the User Preference bulk export feature

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/9538

#### Checklist

- [x] Added or updated unit tests (required for all new features)

I actually would like a feedback on the pattern I used in this pull request, I think I might over complicated things to generalize them too much.
I'm also in the process of writing unit tests

### CODE REVIEW

**Comment by jespino** [comment]
@dos1701 It is very generic, but makes sense. I think you are in the right path :)

**Comment by dos1701** [comment]
> @dos1701 It is very generic, but makes sense. I think you are in the right path :)

Thanks @jespino! I'll wrap it up then!

**Comment by grundleborg** [comment]
I'm going to close and reopen the PR to re-trigger the Continuous Integration build.

**Comment by hanzei** [comment]
Hey @dos1701,

Thank you very much for your contribution! Can we help you with the `gofmt` issue? Do you have any other questions?

Please note that we will close this PR after another 30 days of inactivity. If you don't object, contributors might complete this PR for you.

**Comment by hanzei** [comment]
I added a simple test and fixed the linter issues. @dos1701 I hope you don't mind.

@grundleborg @jespino Can you review?

@wiersgallak Do you also want to review?

**Comment by hanzei** [comment]
How should I check that the values are as excepted? `ExportAllUsers` creates a bytes blob. Running `BulkImport()` is kind of a cycle test. Should I just check the content of the blob? But this is like rewriting the import.

**Comment by grundleborg** [comment]
I think the BulkImport cycle test approach is fine:

1. Create and populate a User object with preferences.
2. Do an export.
3. Delete the User Object and Preferences from the DB.
4. Do an import.
5. Check the User Object and Preferences are as expected.

Although, thinking about it some more, a cleaner approach would probably be to refactor the new code in `ExportAllUsers` to be in a separate function, so that you can then test that function in isolation, and in conjunction with `ImportLineFromUser` and not have to fight with how to unit test these details in `ExportAllUsers`.

**Comment by cpanato** [comment]
@dos1701 please update this branch with latest master

**Comment by hanzei** [comment]
It's up-to-date

**Comment by grundleborg** [comment]
@hanzei thanks! Please could you merge master into this branch again, as the build failure is due to a bad merge that Carlos fixed yesterday?

**Comment by hanzei** [comment]
Merged. Please take a look at the test. I ended up writing a "E2E" for `ExportAllUsers`.

**Comment by hanzei** [comment]
Also thanks to @dos1701 for creating this PR! :tada:

**Pull request merged**
