### PR TITLE
fix conflict in migration numbers

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Two PRs (#20247 and #20164) went in with the same migration number, causing a conflict. This PR fixes it by moving the most recently merged migration to the correct migration number

#### Ticket Link

- NA

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by ashishbhate** [comment]
Users whose migration DB is in a "conflicted" state will have to run

`delete from db_migrations where version = 85;` to fix their DB

**Review by nickmisasi — APPROVED** [review]
Had opened https://github.com/mattermost/mattermost-server/pull/20277 to fix this but then noticed yours. Just dropping in for a quick approval.

**Review by streamer45 — APPROVED** [review]

**Comment by stafot** [comment]
I recommend that we need to add a control at CI level for this to ensure that we would never merge conflicted codebases especially on migrations.

**Comment by ashishbhate** [comment]
Yep, I created a ticket for the server platform team yesterday - https://mattermost.atlassian.net/browse/MM-44563

**Comment by amyblais** [comment]
@ashishbhate Is this needed for 7.0? https://github.com/mattermost/mattermost-server/pull/20164 will be included in 7.0 but https://github.com/mattermost/mattermost-server/pull/20247 will not be.

**Comment by ashishbhate** [comment]
>@ashishbhate Is this needed for 7.0? https://github.com/mattermost/mattermost-server/pull/20164 will be included in 7.0 but https://github.com/mattermost/mattermost-server/pull/20247 will not be.

This PR only needs to go in whereever #20247 goes in. So this doesn't need to go into v7.0.

**Pull request merged**
