### PR TITLE
MM-50087_Add marketplace button to apps bar

### PR DESCRIPTION
**Pull request by julmondragon**
#### Summary
Show the marketplace button in the App Bar.
Additionally standardized for all places where the marketplace can be opened:
- Marketplace should be enabled and user should have `SYSCONSOLE_WRITE_PLUGINS` permission.
- Label should read "App Marketplace"
- Icon should be `view-grid-plus-outline` Screen Shot 2023-03-06 at 11 52 58 AM
- Current event tracking for Marketplace modal opened is now enhanced to report the source of the action.
  ```
    properties: {
        category: "plugins",
        type: "ui_marketplace_opened",
        from: "actions_menu" | "app_bar" | "channel_header" | "command" | "open_plugin_install_post" | "product_menu"
        ...
    }
  ```

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50087

##### App Bar enabled
Mar-14-2023 14-03-45

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by julmondragon** [comment]
@pvev @marianunez @stevemudie @annelieseklein This PR replaces https://github.com/mattermost/mattermost-webapp/pull/12308 in the new monorepo, which was already approved. Thanks!

**Review by marianunez — APPROVED** [review]
Approving per review in the original linked PR

**Review by annelieseklein — APPROVED** [review]

**Review by pvev — APPROVED** [review]
LGTM! thanks @julmondragon :shipit:

**Review by stevemudie — APPROVED** [review]

**Pull request merged**
