### PR TITLE
Commenting out delete command test becase race condition

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by lieut-data** [comment]
In the future, can we leverage `t.Skip()` instead? All the same benefits, but without having to comment out import headers, and we get a nice listing in the new containerized build output on what tests are currently disabled.

**Comment by cpanato** [comment]
fine for me

**Comment by cpanato** [comment]
i will update that after the RC @lieut-data

**Comment by cpanato** [comment]
cherry picked 6a2f81601dc24f84f6eff174eb1c4f258546e5a3 into release branch 5.6

**Pull request merged**
