### PR TITLE
Add back consumeAndClose functionality. 

### PR DESCRIPTION
**Pull request by crspeller**

### CODE REVIEW

**Comment by ccbrown** [comment]
Actually I do think a change is warranted: Document whatever rationale there is for this in a comment.

**Comment by coreyhulen** [comment]
I think we fixed a similar issue reported with https://github.com/mattermost/mattermost-server/issues/3145

**Comment by coreyhulen** [comment]
I think you're using up all the file descriptors and it failing when it tries to create a new DB connection.

**Comment by ccbrown** [comment]
That sounds like a Go bug to me, but at least add a comment to this function.

I'd also recommend changing the ReadAll to `io.Copy(ioutil.Discard, r.Body)`. Probably slightly better performance since ReadAll allocates memory.

Do those things and you have my 👍 .

**Comment by crspeller** [comment]
Added some missed cases, a comment, and switched to using ioutil.Discard. 
Let me run a loadtest before we merge this.

**Pull request merged**
