### PR TITLE
MM-11529: Allow to Leave an archived channel from the API

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Allow to Leave an archived channel from the API when you are the channel
member. Also avoid any notification outgoing from archive channels
interaction.

#### Ticket Link
[MM-11529](https://mattermost.atlassian.net/browse/MM-11529)

#### Checklist
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by jwilander** [comment]
The behavior here is that you can still remove yourself from archived channels but not other users? Just wondering why the channel being archived changes the permissions behavior

**Comment by jespino** [comment]
Yes, that is the behavior. Currently the archived channels are read-only by definition (actually we changed it in the store), is a matter of interpretation, but from the store point of view now, when you archive a channel you "freeze" the channel in the current state. You can consider that it's bypassing the permissions system, but is like other objects in the system, you can't system emojis, no matter if you have emoji edition permissions.

**Comment by jwilander** [comment]
If the state is frozen, then why can I still remove myself? And if my users can remove themselves from an archived channel, then as an an admin I would want that power over other users

**Comment by jespino** [comment]
Good point. The reason behind allow you to removed yourself from the channel is to leave the channel for ever and don't see the results in the searches.

Probably makes sense to allow admins to do it too. What do you thing @wiersgallak?

**Comment by wiersgallak** [comment]
@jespino I would agree with you.  The admin should have the same option as the end user to remove themselves from the archived channel.

**Comment by jespino** [comment]
@wiersgallak The admin will have the option of remove himself, as any other regular user. The question is, If I have the permission to remove a user from a regular channel, have I the permission to remove the other users from that channel after the channel is archived? @jwilander point here is that if you can remove yourself, then the "admins of the channel" should can to remove you too.

**Comment by wiersgallak** [comment]
My misunderstanding - thanks for clarifying @jespino .   I think that also makes sense.

**Comment by jespino** [comment]
Ok, then, I'll change a bit my PR and we'll be ready :)

**Comment by jespino** [comment]
@jwilander PTAL

**Pull request merged**
