### PR TITLE
MM-25450  deleted posts should be  sanitised

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
added post sanitation for deleted posts

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-25450

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @reflog - can you help with test steps please?  Thanks!

**Comment by lindy65** [comment]
Thanks @reflog - Saturn will help review this PR 👍

**Comment by hanzei** [comment]
@reflog Should this go into v5.25.0?

**Comment by reflog** [comment]
@hanzei no idea :) cc @wiersgallak

**Pull request merged**
