### PR TITLE
MM-33233: Fix double close of webconn pump

### PR DESCRIPTION
**Pull request by agnivade**
There would be an edge case where an epoll HUP event
would occur at the same time as a connection close event,
and both would race to close the connection.

We fix this by enclosing the Close method with a sync.Once
thereby guaranteeing idempotency.

https://mattermost.atlassian.net/browse/MM-33233

```release-notes
Fixed a race condition which would crash the app server due
to improper handling of websocket closing.
```

### CODE REVIEW

**Comment by agnivade** [comment]
@streamer45 - It would be good to have your magic touch with a load test just to see if it reproes again. :wink:  No rush of course.

**Review by nronas — APPROVED** [review]
LGTM

**Review by streamer45 — APPROVED** [review]
Nice :+1: Stress-tested this for a while and couldn't reproduce :rocket:

**Comment by agnivade** [comment]
Verified with load tests. So no QA needed for this.

**Pull request merged**
