### PR TITLE
[PLT-3755] Consolidate add/remove/join/leave system message

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Consolidate add/remove/join/leave system message, by:
- updating the latest post is that's one of add/remove/join/leave system message
- set a max of 50 consolidated add/remove/join/leave system messages

Note: The post updates are on server side with expensive read & update to old post and insert to new post.

#### Ticket Link
Jira ticket: [PLT-3755](https://mattermost.atlassian.net/browse/PLT-3755)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes (https://github.com/mattermost/mattermost-webapp/pull/51)
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates
- [x] Touches critical sections of the codebase (store)

@jasonblais Here is the updated "improved join/leave system message". I'd like to request for some testing (meeting the specification) just in case I missed something. For performance testing, let's ask for @crspeller's help. thanks!

### CODE REVIEW

**Comment by saturninoabril** [comment]
Test server was created but was not accessible. In addition, not sure if the test server considered the changes in mattermost-webapp repo.

**Comment by saturninoabril** [comment]
@jasonblais as discussed in Dev channel, this server-side change will be for Dev review. Once approved and merged, you may take a look once the test server is setup at `mattermost-webapp` repo.

**Comment by jwilander** [comment]
I'm going to let @crspeller load test this before I dive too far into a review but I wish there was a more elegant solution to this

**Comment by crspeller** [comment]
@saturninoabril I can loadtest this. But why are there server side changes? Why not just consolidate on the client?

**Comment by saturninoabril** [comment]
Per discussion in [dev channel](https://pre-release.mattermost.com/core/pl/a1gki579up8td8yz9yawhneade), this is agreed to be on client-side. I'll resubmit this PR.

**Comment by jwilander** [comment]
Closing per above comment

**Pull request closed without merging**
