### PR TITLE
use testify's assert on modeltestlib tests

### PR DESCRIPTION
**Pull request by aladhims**
#### Summary

Convert model/modeltestlib_test.go to use Testify's assert instead of t.Fatal
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/12669
Jira: https://mattermost.atlassian.net/browse/MM-19272

### CODE REVIEW

**Comment by aladhims** [comment]
@hanzei Should I registered and signed the CLA a bit late after I opened this PR, should I open a new PR again?

**Comment by jespino** [comment]
QA not needed for this kind of PRs. Only tests changed.

**Comment by jespino** [comment]
Merged! Thanks @aladhims! :dancer:

**Pull request merged**
