### PR TITLE
[MM-46604] Prevent concurrent access to WebConn.session

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
Concurrent read and write accesses to normal Go maps are forbidden. There are instances where this happened in WebConn, because the `model.Session` struct has no mechanisms to prevent this.
* The direct way to fix it would be to introduce a mutex in `model.Session` and use methods to access the fields of the struct. Unfortunately mutexes can't be copied (a `*sync.Mutex` would work, though) and the struct is used in multiple instances throughout the server, making this a huge change.
* Another option would be to replace the `map[string]string` with a `sync.Map`, which still requires refactorings all over the server and does not prevent the conurrent access to the other fields (they can still be unsafely accessed concurrently, they just don't throw a `panic` every time). Also the autogeneration of serializers wouldn't work anymore.
* The approach I settled for is to just allow the access to the session by calling `WithSession(f func(*model.Session))` which allows you to handle the session related data within `f` and then unlocks the mutex when it's done.

#### Ticket Link
[MM-46604](https://mattermost.atlassian.net/browse/MM-46604)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
I am not sure if this identifies the real root cause behind the issue. According to the issue, the crash happens due to concurrent read/writes to the Props map here: https://github.com/mattermost/mattermost-server/blob/aef5165cdc7d302fff589204b23a48e7a6753d54/app/web_conn.go#L792

But every time we set a session to webconn via `wc.SetSession`, we do a full deep copy of the map https://github.com/mattermost/mattermost-server/blob/aef5165cdc7d302fff589204b23a48e7a6753d54/app/web_conn.go#L300-L302 and then store.

And nowhere else we are setting the props of the session object from web_conn. So I am not sure where the "write" is coming from?

I'd like to understand this first. Can you check?

**Comment by noxer** [comment]
You are absolutely right @agnivade, something is strange there. From what I can see, the only way a reference of the session could escape would be via https://github.com/mattermost/mattermost-server/blob/8f362cb8f64615892595a19625d3c88e00404152/app/web_conn.go#L310
My current hypothesis is that this gets triggered while another Go routine is still trying to access the `WebConn`. So far I've not found a way this could happen but I've still a few more ways to check. I'll turn this into a draft again. Sorry for the noise.

**Comment by agnivade** [comment]
Yep, you are definitely on the right track. The returning to pool is the only place where it gets leaked.

Digging a bit deeper, I have a theory:
1. The props access happens in `shouldSendEvent`, which is actually called from web_hub broadcast event.
2. Now, the returnSessionToPool happens after the `HubUnregister` call, which removes this web_conn from the conn_index.
3. BUT, I am wondering if there's a case, where the broadcast loop has already called `candidates := connIndex.All()` which has the victim conn, and then the victim conn gets disconnected, which unregisters, and returns the session to pool.
4. And then _just_ when the `if webConn.shouldSendEvent(msg) {` gets called, the returned session is fetched from the pool and a new session is inserted into it.

This would possibly try to read the `Props` map of a stale web_conn whose session is already returned to the pool.

You'll have to go through a lot of the web_conn and web_hub flow to understand this. But it's a very interesting race condition. :)

Could you check if this hypothesis is valid?

**Comment by noxer** [comment]
@agnivade I've disabled returning the session struct to prevent the escape and the unchecked access.

I'm still unable to find a way this can happen but it's the only option I see.

**Comment by agnivade** [comment]
Ok, you want me to take a look?

**Comment by noxer** [comment]
It was more the question if we merge this so we've got more time to nail this down. You are welcome to take a look of course.

**Comment by agnivade** [comment]
It's not a very frequent crash which would make this very urgent, so we have time on our hands. I'd like to understand the root cause first before merging any code. Removing the return to pool will likely fix the issue, but I'd like to understand the issue first. And confirm that what we suspect is actually true.

**Comment by noxer** [comment]
Superseded by https://github.com/mattermost/mattermost-server/pull/20996

**Pull request closed without merging**
