### PR TITLE
MM-26203: Fix TestChannelStore//SearchAllChannels flake

### PR DESCRIPTION
**Pull request by agnivade**
Using random strings for channel names creates chances of collisions
when searching for specific strings.

We increase the search space increasing the size of the search string
to be searched. This reduces collisions and makes the tests more reliable.

For the "off-" family of tests, this probably needs more length. But
it would also need the tests to be changed slightly as the "off-" part
acts as a prefix. I accidentally stumbled upon it while running the test
50 times. Adding a "-" is probably good enough for now. We can revisit
if it fails again in CI.

#### Ticket link

https://mattermost.atlassian.net/browse/MM-26203

### CODE REVIEW

**Comment by agnivade** [comment]
@lindy65 - No testing needed here as it just fixes a flaky test. Thanks.

**Comment by agnivade** [comment]
Sorry, I actually didn't see the label. @lindy65 - any reason this is slated for 5.25? This just fixes a flaky test and not related to the code in any way.

**Comment by amyblais** [comment]
Per Agniva's comment, this seems fine for v5.26.

**Comment by lindy65** [comment]
Apologies @agnivade! An error on my part!

**Pull request merged**
