### PR TITLE
[MM-51479] Cloud Reverse Trial Banner Updates

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
Updates to the existing banner verbiage. Feature flagged, so new verbiage will only apply after reverse trial is released. 

A small adjustment to existing Cloud Enterprise trials: Rather than the warning threshold being 3 days, it's now 7 (to bring it in line with the new flow)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51479

#### Screenshots
Last day: 
image

7 days left 
image

30 days left
image

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by ConorMacpherson — DISMISSED** [review]

**Comment by nickmisasi** [comment]
@AGMETEOR @annelieseklein gentle ping on this one - need to get this in for Thursday's fast forward

**Comment by annelieseklein** [comment]
@nickmisasi the spacing looks off for the button - it looks like there is more space on the top than the bottom

**Comment by annelieseklein** [comment]
> @nickmisasi the spacing looks off for the button - it looks like there is more space on the top than the bottom

Screen Shot 2023-04-11 at 3 38 38 PM

**Comment by nickmisasi** [comment]
@annelieseklein all I really did was change the wording - this is an existing shared component that we (self serve/growth) aren't the only owners of

The padding inside the button was already 4px left and right, 8px top and bottom. I think visually the string is just bottom heavy, so doesn't look centered even though it is. I've changed the top padding to be 2px rather than 4 (leaving the rest the same) and this is how it looks:
image lmk what you think.

Adjusting the background color of the announcement bar button would affect every bar, unless we did a bunch of work to ensure certain cases inherit the colour (ie, like the blue one in this PR) and others don't. Is it ok to leave the background color of the bar as it was already implemented?

**Review by AGMETEOR — APPROVED** [review]

**Review by ConorMacpherson — APPROVED** [review]

**Comment by annelieseklein** [comment]
noted - thanks for explaining. The padding looks better, thank you!

**Review by annelieseklein — APPROVED** [review]

**Pull request merged**
