### PR TITLE
[MM-31674] app/product_notices: implement notices for ext. dependencies

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Adds support for noticing external dependencies.

image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31674

#### Release Note
```release-note
Add deprecating external dependencies to product notices
```

### CODE REVIEW

**Review by wiersgallak — APPROVED** [review]
Thanks, @isacikgoz

**Review by reflog — APPROVED** [review]
looks great! don't forget to update the schema JSON file in mattermost-notices repo so that AJV validation that we run during notices CI will pass.

**Review by grundleborg — APPROVED** [review]
LGTM

**Review by lindalumitchell — APPROVED** [review]

**Pull request merged**
