### PR TITLE
[MM-52444] - Hide dot menu for users when they can't delete a system post 

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary
This PR Fixes a bug for regular users that shows the dot menu for system posts even when there are no actions available.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52444

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by harshilsharma63** [comment]
It would be super awesome if we can add new tests for this. There are no tests for this component right now.

**Comment by nevyangelova** [comment]
> It would be super awesome if we can add new tests for this. There are no tests for this component right now.

tickets is on my board https://mattermost.atlassian.net/browse/MM-52133

**Comment by yasserfaraazkhan** [comment]
@amyblais the functionality is working fine.
Screenshot 2023-05-17 at 10 02 43 PM


there's a bit of UI and accessibility issue.
the dot menu on sys-admin's message doesn't have Tab support that moved the focus to `delete` option

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by amyblais** [comment]
> there's a bit of UI and accessibility issue.
the dot menu on sys-admin's message doesn't have Tab support that moves the focus to delete option

@yasserfaraazkhan Do you know if this is a new regression caused by the code changes in this PR or is this an existing issue?

**Comment by yasserfaraazkhan** [comment]
> > there's a bit of UI and accessibility issue.
> > the dot menu on sys-admin's message doesn't have Tab support that moves the focus to delete option
> 
> @yasserfaraazkhan Do you know if this is a new regression caused by the code changes in this PR or is this an existing issue?

@amyblais I looked into this, its is existing issue. non blocking, its only with when we use keyboard.

**Comment by harshilsharma63** [comment]
Closing in favor of #23487 as this one is not triggering a circleci pipeline.

**Pull request closed without merging**
