### PR TITLE
[MM-13787] fixing mv channel CLI syntax

### LINKED ISSUE #10115: CLI channel move syntax "wrong"
Hi all

#### Summary
The CLI channel move syntax is not common.

#### Issue
At the moment the channel move is using the syntax:
channel move [destination] [source] --username myusername

but every program that moves something has the syntax:
mv [source] [destination]

By switching the syntax it makes the cli more consistent with other move tools and also within the cli. For example channel rename uses also the schema [source] [destination]
##
I tried to simple flip the arguments in the channel.go but that's not working at all but its clearly limited due to my inexisting program skills

Best regards

JtheBAB

### PR DESCRIPTION
**Pull request by adzimzf**
#### Summary
Change CLI  move channel syntax from `channel move [destteam] [sourcechannel]` to `channel mv [sourcechannel] [destteam]`

#### Ticket Link
Fixes #10115

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by JtheBAB** [comment]
As the owner of the issue: Thank you :)
One feedback: i think move instead of mv is better and consistent with the other cli commands.

**Comment by adzimzf** [comment]
Hi @JtheBAB,
Oke, I can change it, but let @wiersgallak review it first.

**Comment by jespino** [comment]
The code looks good, but It is a problem of backward compatibility, if somebody have an script that  use this command, this change will break his script. At least we should add a notice or something in the release which includes this changes. Thoughts @wiersgallak?

**Comment by wiersgallak** [comment]
We can add a note in our release documents for the change.  Thanks for pointing out @jespino.

**Comment by jespino** [comment]
ok, then :)

**Comment by lieut-data** [comment]
I also note that `mv` does actually support the original syntax:
```sh
NAME
       mv - move (rename) files

SYNOPSIS
       mv [OPTION]... [-T] SOURCE DEST
       mv [OPTION]... SOURCE... DIRECTORY
       mv [OPTION]... -t DIRECTORY SOURCE...
```

Note that if you want to specify multiple source files to move into a directory (very much like multiple channels into a team), the directory comes first (but with a special flag) and the variable number of source files are listed afterwards.

Though I think it still probably makes more sense to limit ourselves to just one channel.

**Comment by adzimzf** [comment]
Hi @lieut-data,
I agree with you, it'll make CLI command clearer.
but let @wiersgallak give a thought

**Comment by hanzei** [comment]
@wiersgallak Can you pleas take a look at the discussion above and propose some next steps?

**Comment by wiersgallak** [comment]
Changing the behavior from many to one seems like a fairly significant backwards incompatible change to me.  Is this something that we could queue for developer's meeting for a best practice and then open another PR if we decide to move forward? We would need to update this command and the ``command move`` command.

**Comment by lieut-data** [comment]
@wiersgallak, agreed that we should raise this at the developer's meeting. I'll queue something.

**Comment by adzimzf** [comment]
@wiersgalak, @lieut-data I've already updated the PR regarding add -t flag. if -t flag will not include in this PR I can revert the last commit.

**Comment by lieut-data** [comment]
@wiersgallak, the dev team met and agree that we need to maintain backwards compatibility until the next major version, after which we're essentially free to make whatever changes are necessary. I don't know when v6.0 is scheduled, but it sounds like this PR (or any variant of it) will have to wait until then.

Can you provide guidance on how to proceed here?

**Comment by wiersgallak** [comment]
Thank you for queuing the discussion. I would recommend taking the changes as they are and opening another PR for the improvements @lieut-data.   Thank you @adzimzf for your patience and for the contribution.

**Comment by lieut-data** [comment]
@wiersgallak, sorry for the confusion on my part, but the discussion led us to conclude that we can’t take these changes (as they are or with any of the proposed improvements) until v6.0, as they break our SemVer guarantees.

**Comment by wiersgallak** [comment]
Gotcha - sorry for not verifying my understanding.  I think it is best then to hold this PR until that is scheduled and if @adzimzf is unable to contribute at that time, the Mattermost team can complete any additional improvements.  We are still working on the date of 6.0.

**Comment by lieut-data** [comment]
@wiersgallak, with the introduction of mmctl, I'm wondering if we can make a new decision on this issue?

**Comment by wiersgallak** [comment]
@isacikgoz Can this issue be closed since we are working on the other pull request for MMCTL?

**Comment by isacikgoz** [comment]
@wiersgallak Yes, we can close this PR. We are migrating this command to `mmctl` in https://github.com/mattermost/mmctl/pull/149. As for the change suggestions; we can consider those for v6.

**Comment by teresa-novoa** [comment]
@jasonblais looks like this PR can be closed?

**Comment by jasonblais** [comment]
@teresa-novoa yes you're correct. I will close this PR. Thank you @adzimzf for the initial contribution, can't believe it's taken this long. Hope you are doing well :)

**Pull request closed without merging**
