### PR TITLE
[MM-22103] Push notification workers started on demand

### PR DESCRIPTION
**Pull request by Pomyk**
#### Summary
Push notification workers started on demand and stopped after being idle for over 10 minutes.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13777

### CODE REVIEW

**Comment by agnivade** [comment]
Any performance numbers that we can attach to this ?

**Comment by Pomyk** [comment]
Not a benchmark but similar code tested with 16 mln events (with no processing).
Old way:
real    0m3,284s
user    0m33,890s

Start workers on demand:
real    0m3,326s
user    0m34,541s

Start on demand and stop after idle time:
real    0m3,486s
user    0m39,130s

And for comparison start/stop with fnv changed to xxhash:
real    0m2,857s
user    0m31,102s

So there is some performance hit for the timeout code, but using slow hash function has higher impact. I would go for starting workers on demand and not stopping them.

**Comment by josephbaylon** [comment]
@agnivade I'm not quite sure what to test here. Can you please provide more details on what you need me to test on this and steps on how to them? Thanks

**Comment by agnivade** [comment]
@josephbaylon - Testing would be anything around push notifications. But don't start testing yet. This PR still needs to be discussed more and finalized.

**Comment by agnivade** [comment]
Me and @jespino discussed a bit about this offline. He needs to take a look at this sometime.

**Comment by jasonblais** [comment]
@agnivade @jespino While the conversation is on-going, should we apply a `Lifecycle/Frozen` label?

> If the contribution is inactive but shouldn't be closed, the Coordinator adds a lifecycle/frozen label to the contribution. An example of this is when a design decision is being discussed but no decision has been arrived at yet.

https://developers.mattermost.com/contribute/getting-started/inactive-contributions/

**Comment by agnivade** [comment]
SGTM

**Comment by jespino** [comment]
I general I like it, but the problem now is we are thinking about removing scalling the channels on runtime, because we want to decrease the memory footprint of the an idle instance. I think this is a good start but we have to think a bit more about it. @agnivade maybe we can have a meeting to brainstorm about how to solve bot problems at the same time.

**Comment by agnivade** [comment]
I have been thinking about it. I have some ideas, but they need more gestation. One problem with the existing approach is that the sharding is based on userID. Which means if a group of users mapping to the same shard generates too many messages, then other goroutines are sitting idle doing nothing. I plan to kill these 2 birds with one stone.

Let me spend some time on this, and then let's have a call to discuss our ideas.

**Comment by agnivade** [comment]
I am finally ready to work on this now that the refactoring and basic performance improvements are done. I have a couple of approaches. I will need to benchmark each of them and measure the throughput and how much code complexity is traded off.

I will send a PR as soon as I have it ready. Thanks for your patience everyone.

**Comment by agnivade** [comment]
I stumbled upon another fact which unfortunately makes this PR unnecessary. Our push-proxy deployment is actually load-balanced, meaning that ordering in messages is actually not guaranteed even if we send it in an ordered manner. So there's not much use trying to enforce order from the app. I will use a simple counting semaphore for this.

Going ahead and closing this. I apologize for wasting your time @Pomyk and thanks so much for working on this !

**Pull request closed without merging**
