### PR TITLE
[MM-44850] Prevent sanitising event to source user on profile image update

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

Sends three separate levels of sanitized events to admin, source user, other users. This already happens in case of updating other fields in user profile. 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-44850

#### Release Note

```release-note
Fixed bug where SAML controlled user is prompted for MFA setup after updating profile picture.
```

### CODE REVIEW

**Comment by sadohert** [comment]
@plant99 I am working on testing in localdev, but it would be great to find another developer to look at the code changes ... I'm not a good reviewer for that :)

**Comment by sadohert** [comment]
I can confirm I no longer see the issue on recent master:

```$git log
commit 5707e2ec334d3eac9b10052a41c6872efaf23b3b (HEAD -> master)
Author: Shivashis Padhi <shivashispadhi@gmail.com>
Date:   Fri Jun 17 18:41:46 2022 +0530

    Prevent sanitization of event to source user in setProfilePicture handler

commit 24c44736c0e88858cfac926d0c10b2443d8a4482 (upstream/master, upstream/HEAD)
Author: Zach Zundel <me@zachzundel.com>
Date:   Fri Jun 24 17:37:07 2022 +0100

    [MM-41115] Add server-side username colorize preference (#19382)

    * Server support for collapse consecutive preference

    * Add server-side username colorize preference
```

**Comment by plant99** [comment]
Sure @sadohert , thanks for testing its resolution.

**Review by agnivade — COMMENTED** [review]
Let's have a unit test please :)

**Review by agnivade — APPROVED** [review]
Nicely done!

**Comment by plant99** [comment]
Closing this since @furqanmlk can't reproduce this in latest master. Will reopen if there are more errors in future.

cc: @sadohert

**Pull request closed without merging**
