### PR TITLE
[MM-30916]: Change receiver name for (me *LogoutProvider) in app/slashcommands/command_logout.go to be more idiomatic.

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary 

Updated receiver name for (me *LogoutProvider) to be more idiomatic. 

#### Ticket Link

Fixes: #16375   
JIRA: https://mattermost.atlassian.net/browse/MM-30916

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by darkLord19** [comment]
Wouldn't `lp` for `LogoutProvider` make more sense?

**Comment by haardikdharma10** [comment]
Hi @agnivade, Initially all the 17 tests passed for all the similar PR's I opened up. Now there is this 1 failed check in every PR. I wonder what that is?

**Comment by agnivade** [comment]
That check ensures that your PR branch has not fallen behind master by a lot. We fix that by a GitHub automation we have to merge the latest master branch with your PR.

/update-branch

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
This is an internal refactor. So no QA is needed.

**Pull request merged**
