### PR TITLE
[MM-50349] Add Feature Flag to Disable Tour Tips

### PR DESCRIPTION
**Pull request by mylonsuren**
#### Summary

Adds a feature flag to disable tour tips.

*See https://community.mattermost.com/core/pl/b4pwu6jeb3n7pkejqcci5uy7fh for further context.*

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-50349

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]

**Review by vish9812 — APPROVED** [review]
@mylonsuren The JIRA ticket is specific to disable Draft. Will you be raising another PR for that with another flag?

**Comment by mylonsuren** [comment]
> @mylonsuren The JIRA ticket is specific to disable Draft. Will you be raising another PR for that with another flag?

@vish9812 Sorry, should've linked it on this PR as well. This is the webapp PR that disables it specifically for drafts, threads, and messages actions: https://github.com/mattermost/mattermost-webapp/pull/12167

**Review by lindy65 — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
