### PR TITLE
Update the get release script for mmctl to get the latest release eve…

### PR DESCRIPTION
**Pull request by jaydeland**
#### Summary
Update mmctl get logic for master builds

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28205

### CODE REVIEW

**Comment by gabrieljackson** [comment]
@jaydeland, looks like there may be an unrelated build issue here?

**Comment by jwilander** [comment]
Should be fixed with https://github.com/mattermost/mattermost-server/pull/15380 @gabrieljackson

**Comment by gabrieljackson** [comment]
If I understand our new mmctl pull-in process correctly, we should cut a pre-release in the mmctl with a `-rc` suffix before merging this?

**Comment by jaydeland** [comment]
> If I understand our new mmctl pull-in process correctly, we should cut a pre-release in the mmctl with a `-rc` suffix before merging this?

Correct

**Pull request merged**
