### PR TITLE
[MM-44364] make config override actually override defaults

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
This PR fixes a few issues in the Makefile:
- The Makefile now respects the `ENABLED_DOCKER_SERVICES` variable specified in `config.override.mk`. Before it would treat them like the default ones and add services it deemed useful. This broke some workflows as undesired services could not be excluded when testing.
- The Makefile contained an invalid `ifeq` conditional, which was prefixed with a tab. The GNU make docs explicitly state that this prevents `make` from evaluating the conditional (as it's considered a recipe line).
- The Makefile had a rule `start-docker-check` which contained just conditionals, variable assignments, and no prerequisites; making it a NOOP. It would run on initialization anyway, so this PR removes the rule (but keeps the conditionals).
- Made the formatting of conditionals more uniform throughout the file.

#### Ticket Link
[MM-44364](https://mattermost.atlassian.net/browse/MM-44364)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
This only seems to work for environment vars, but still doesn't respect the variables in config.override.mk.

I specified `ENABLED_DOCKER_SERVICES = mysql postgres inbucket` in my config.override.mk and it still tried to start elasticsearch.

**Comment by noxer** [comment]
Then you had it launched with the old config before. Run `make clean-docker` and try again.

**Comment by noxer** [comment]
I've added a call to automatically remove start_dependencies to force docker-compose to recreate it with the correct dependencies set. Now it should work reliably.

**Comment by agnivade** [comment]
Hmm .. it's still not working. I did a `clean-docker` as well.

This is what I am seeing:

```
make start-docker
Starting docker containers
docker-compose rm start_dependencies
No stopped containers
go run ./build/docker-compose-generator/main.go mysql postgres inbucket  minio openldap elasticsearch | docker-compose -f docker-compose.makefile.yml -f /dev/stdin  run -T --rm start_dependencies
Pulling elasticsearch (mattermost/mattermost-elasticsearch-docker:7.17.3)...
```

And this is my config.override.mk
```
RUN_SERVER_IN_BACKGROUND=false

ENABLED_DOCKER_SERVICES = mysql postgres inbucket
```

**Comment by noxer** [comment]
Huh, that's strange. This is how it looks for me.
```bash
tim@mattermachine:~/projects/mattermost-server$ make start-docker
ENABLED_DOCKER_SERVICES has been overridden
Starting docker containers
docker-compose rm start_dependencies
No stopped containers
go run ./build/docker-compose-generator/main.go mysql postgres inbucket | docker-compose -f docker-compose.makefile.yml -f /dev/stdin  run -T --rm start_dependencies
[+] Running 4/0
 ⠿ Network mattermost-server_mm-test  Created                              0.0s
 ⠿ Container mattermost-inbucket      C...                                 0.0s
 ⠿ Container mattermost-postgres      C...                                 0.0s
 ⠿ Container mattermost-mysql         Crea...                              0.0s
[+] Running 3/3
 ⠿ Container mattermost-inbucket  Start...                                 0.7s
 ⠿ Container mattermost-postgres  Start...                                 0.7s
 ⠿ Container mattermost-mysql     Started                                  0.7s
Waiting for mysql to listen on 3306...
sleeping
sleeping
sleeping
sleeping
Waiting for postgres to listen on 5432...
Waiting for inbucket to listen on 9001...
```
with the override file
```
RUN_SERVER_IN_BACKGROUND=false

ENABLED_DOCKER_SERVICES = mysql postgres inbucket

```

**Comment by agnivade** [comment]
What is the value of your `echo $ENABLED_DOCKER_SERVICES`? Mine is empty.

**Comment by noxer** [comment]
Mine is empty, too.

**Comment by agnivade** [comment]
This logic: `ifneq (,$(ENABLED_DOCKER_SERVICES))` will check if `ENABLED_DOCKER_SERVICES` is not empty and only then will set `DOCKER_SERVICES_OVERRIDE` to true.

According to this, in my machine it works correctly. If I have an env var set, it works correctly. But if I don't have it set, it doesn't override. It seems to follow what is written. If I change ifneq to ifeq, it takes my config.override.mk file.

We need to support env vars as well as the config.override.mk file. The order of priority should be:
1. config.mk
2. config.override.mk
3. env vars.

**Comment by noxer** [comment]
The logic is
- import the config.override.mk if it exists
- check if `$ENABLED_DOCKER_SERVICES` has been set (either from config.override.mk or the env variables)
- import the config.mk (which sets the `ENABLED_DOCKER_SERVICES` only if they have not been set before)

To prioritize the env variables over the override file, you need to set it with `ENABLED_DOCKER_SERVICES ?= mysql postgres inbucket`

`ifneq (,$(ENABLED_DOCKER_SERVICES))` should be the same as `if ($ENABLED_DOCKER_SERVICES != "")`, right?

**Comment by agnivade** [comment]
Lol ignore me :facepalm: I placed the file in the wrong directory.

**Review by agnivade — APPROVED** [review]
Neatly done!

**Review by isacikgoz — APPROVED** [review]
LGTM

**Pull request merged**
