### PR TITLE
[MM-31018] Update email address for admin advisor contact requests to support-advisor@mattermost.com

### PR DESCRIPTION
**Pull request by jasonblais**
#### Summary
Update email address for admin advisor contact requests to support-advisor@mattermost.com. Also update constant from `MM_SUPPORT_ADDRESS` to `MM_SUPPORT_ADVISOR_ADDRESS` given the change in the email address being used.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31018

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/7145

### CODE REVIEW

**Comment by jasonblais** [comment]
Associated PR with https://github.com/mattermost/mattermost-webapp/pull/7145

**Review by catalintomai — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jasonblais** [comment]
@furqanmlk please help with QA review :)

**Review by furqanmlk — COMMENTED** [review]
as per @jasonblais comments,
I am only able to verify `mailto: email address` for `Email us` button,
But `Contact us` button still pointing to old support email.
Please see attachment for reference.
image

**Comment by jasonblais** [comment]
@catalintomai is this something you can assist with? I did not find where to change the email address of the `Contact us` button?

**Comment by catalintomai** [comment]
@jasonblais , you will need to update the MM_SUPPORT_ADDRESS value in mattermost-server/model/config.go. cc: @furqanmlk An improvement, since you are in the area, would prob be to replace the hard-coded `MailRecipient: "support-advisor@mattermost.com"` with `MailRecipient: model.MM_SUPPORT_ADDRESS` to make the address change only once in mattermost-server.

**Comment by jasonblais** [comment]
Thanks Catalin! Both suggested changes made.

Moreover, I updated the constant from `MM_SUPPORT_ADDRESS` to `MM_SUPPORT_ADVISOR_ADDRESS` given the change in the email address being used.

**Review by furqanmlk — APPROVED** [review]
Tested Contact Us and Email Us button are sending email to support-advisor@mattermost.com.
Test cases have been created for the same feature
MM-T3656

**Pull request merged**
