### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-server_master/) for mattermost-languages-shipped/mattermost-server.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by angeloskyratzakos** [comment]
testing creation of a spinwick

**Comment by puerco** [comment]
Conflicts resolved and cherry-picks filed:
https://github.com/mattermost/mattermost-server/pull/18534
https://github.com/mattermost/mattermost-server/pull/18533

**Pull request merged**
