### PR TITLE
golangci: bring back the unused linter

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

https://github.com/golangci/golangci-lint/issues/885 is fixed wth 1.23.3.
We can now bring back unused.

Special thanks to @ernado for the fix.

### CODE REVIEW

**Comment by agnivade** [comment]
@ernado - It seems like the golangci service does not have 1.23.3 yet. Is that something that's going to happen soon ? Thanks.

**Comment by ernado** [comment]
Oh, I can't update the hosted version of golangci, sorry.

CC: @jifrag

**Comment by hanzei** [comment]
@agnivade `v1.23.3` has to be added to https://github.com/golangci/golangci-api/blob/master/pkg/goenvbuild/preparer.go. There is no PR for this so you might consider submitting one yourself.

**Comment by ernado** [comment]
You can also consider to run golangci-lint directly in your CI.

Currently I have no push rights in https://github.com/golangci/golangci-api so can't help and there are no ETA for this to change.

**Comment by ernado** [comment]
Seems like maximum is 1.23.3 in hosted version

**Comment by hanzei** [comment]
You are correct @ernado. Let's go with 1.23.3, as 1.23.6 didn't bring much fixes anyway.

**Pull request merged**
