### PR TITLE
[MM-26463] Keep query parameter for interplugin requests

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Rewriting the URL caused the query parameter to get dropped. This PR fixes that and adds a test.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-26463

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann This change is required in order for https://github.com/mattermost/mattermost-plugin-github/pull/315 to work. Hence, I think it's best tested with that PR together.

**Comment by DHaussermann** [comment]
@hanzei I have both PR deployed on a server but, for this PR, are you able to provide test steps?  I'm not sure how to setup a scenarios for this or expose the query string.

**Comment by DHaussermann** [comment]
Tested and passed.
Using the server with this PR code as well as a GitHub https://github.com/mattermost/mattermost-plugin-github/pull/315 
Ben provided a modified version of Matterpoll that would pass the question text to the GitHub plugin. The GitHub plugin then  created an issue with this text so I could observed that it had been passed from one plugin to the other.

This is working as expected. 
LGTM!  

Huge thanks to @hanzei for test steps and resources on this one. 

I will add a test to release testing that links to the needed resources.

**Pull request merged**
