### PR TITLE
translations PR 20180212

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/784

### CODE REVIEW

**Comment by kaakaa** [comment]
There are some un-translated message that was added by commit [9707ac3](https://github.com/mattermost/mattermost-server/commit/9707ac3aaf2cb4352c573aadf54b8535e237dd9e#diff-8aed887c744b7eb6f40c0a268ae06e7b).
However, the message doesn't appers in translation server.

Can not translate this messages for v4.7?

**Comment by jasonblais** [comment]
@kaakaa Good catch! It's in the translations server now, but it's too close to the release date to submit another PR.

Good thing is that it's an error message only admins will see, so it has low impact. We'll be able to fix in v4.8 :)

**Comment by kaakaa** [comment]
@jasonblais 
> Good thing is that it's an error message only admins will see, so it has low impact. 

I see and I agree with you. 
Thank you!

**Comment by wget** [comment]
`fr` LGTM.

**Pull request merged**
