### PR TITLE
Migrates the lastPostsCache from PostStore into cache layer

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

This PR migrates the lastPostsCache from PostStore into cache layer

#### Ticket link

https://mattermost.atlassian.net/browse/MM-20109

#### Issue link

Fixes https://github.com/mattermost/mattermost-server/issues/13098

### Changes

- [x] Move cache to cache layer
- [x] Create tests

### CODE REVIEW

**Comment by rvillablanca** [comment]
This PR is ready to be reviewed. 

cc @hanzei

**Comment by hanzei** [comment]
@rvillablanca You have some failing tests: https://app.circleci.com/jobs/github/mattermost/mattermost-server/13492/tests

**Comment by rvillablanca** [comment]
I can't see the page, 404 is showed

**Comment by rvillablanca** [comment]
I just forgot to register

**Comment by rvillablanca** [comment]
I think this time the tests are failing because the store `PostStore` in `store/sqlstore` package is being tested using the cache but it was removed with this PR, so in order to fix it I should enable the cache layer when initializing the stores in `initStore` function. 

However I'm not so sure about enabling it because all tests related with the new cache layer are being tested in the `store/localcachelayer` package and not in `store/sqlstore`, maybe this was a mistake.

For other migrations of the cache (`ReactionStore` for example) the tests are not using the cache feature so that they are running successfully.

**Comment by jespino** [comment]
@rvillablanca if there is anything testing the cache behavior in the sqlstore, should be removed or moved to the cache layer, the idea is in the near term the sql store is not going to know anything about the cache (except certain parameters that is going to receive and ingore, like `allowFromCache`)

**Comment by rvillablanca** [comment]
Ok so I will move that tests to the cache layer @jespino

**Comment by rvillablanca** [comment]
Updated with master :+1:

**Pull request merged**
