### PR TITLE
MM-47795 Match teams, channels, and users case insensitively on import

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
Depending on the database config teams, users and channels might be matched case insensitive on import. That can lead to crashes when the casing in the import file doesn't 100% match the one in the database. This PR fixes the problem by making the match case insensitive in the server as well (for the import).

#### Ticket Link
[MM-47795](https://mattermost.atlassian.net/browse/MM-47795)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by noxer** [comment]
I could not find a way to test this properly. The tests all run on databases with case sensitive matches. If you've got an idea, please let me know.

**Comment by agarciamontoro** [comment]
> I could not find a way to test this properly. The tests all run on databases with case sensitive matches. If you've got an idea, please let me know.

I'm not super familiar with those tests, but would it be possible to add a new `SetupWithCaseInsensitive` similar to [`Setup`](https://github.com/mattermost/mattermost-server/blob/6ac0faf99ea6de16f597fc4cf1a1b341826d5784/app/helper_test.go#L141-L151)? Not sure the access you have to the DB internals there.

**Comment by agarciamontoro** [comment]
With respect to the changes themselves: is it possible that import files that rely on being case sensitive? Or is that not possible?

**Comment by noxer** [comment]
> With respect to the changes themselves: is it possible that this breaks import files that rely on being case sensitive? Or is that not possible?

We allow the database to be configured as case insensitive, if that was a problem, MM would crash all the time. The primary problem is the team name vs. team display name that gets confused when preparing the import.

We could also cancel the import and report an error. I'm just trying to get this a robust as possible.

**Comment by noxer** [comment]
> I'm not super familiar with those tests, but would it be possible to add a new SetupWithCaseInsensitive similar to [Setup](https://github.com/mattermost/mattermost-server/blob/6ac0faf99ea6de16f597fc4cf1a1b341826d5784/app/helper_test.go#L141-L151)? Not sure the access you have to the DB internals there.

I like the idea. Maybe we can force the collation on those tables to be case insensitive.

**Comment by isacikgoz** [comment]
@noxer This only happens on slack imports right? I think we already not allowing uppercases for name fields for teams, users and channels.

**Comment by noxer** [comment]
> This only happens on slack imports right?

The problem or the fix? Both only apply to imports. 

> I think we already not allowing uppercases for name fields for teams, users and channels.

That's also my thought. The ID will still be corrected to the correct casing, with this fix it will just also match the wrong one.

**Review by isacikgoz — APPROVED** [review]
Thanks for the explanation, lgtm 👍

**Pull request merged**
