### PR TITLE
Add missing field "sortOrder" to graphQL schema

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
We still missed one field on the channel categories.

#### Ticket Link
None

#### Release Note
```release-note
Add `sortOrder` support for channel categories graphQL queries.
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Looks good. Let's add a quick test. File is api4/resolver_sidebar_categories_test.go

**Comment by larkox** [comment]
@agnivade not sure why it is failing (apparently, it is not showing me what is wrong, not sure if I have to do anything extra).

**Comment by larkox** [comment]
My bad, I wasn't logged in. But still... seems not related with my PR.

**Comment by agnivade** [comment]
Yeah, one of the problems of golangci is that the error messages are super hard to understand. We already discussed about placing the `go vet` first, and then run `golangci`.

In your case, I think an 

/update-branch

should fix issues.

**Review by agnivade — APPROVED** [review]
Nice, I'll just run an e2e test to verify no regressions. Please hold merging until then.

**Comment by agnivade** [comment]
Results look good. Feel free to merge at your convenience @larkox.

**Pull request merged**
