### PR TITLE
PLT-6577 scroll sidebar on click "more unreads"

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by jespino** [comment]
Hi, I have changed the behavior to match the animation and I have changed the way to access to the container element (now I'm using the parent function container variable in the inner function), if you want I can change it again to use this.refs.container.

**Comment by jespino** [comment]
Sure! :smile:

**Comment by jespino** [comment]
You are completely right @hmhealey , I moved all the logic related to the scroll to two methods and call it on click, I think now is better, and clearer :) thanks!

**Comment by crspeller** [comment]
This PR needs to be re-submitted to the new separated webapp and server repositories.

**Comment by jespino** [comment]
Done. mattermost/mattermost-webapp#2

**Pull request closed without merging**
