### PR TITLE
PLT-6453 Migrate installed_incoming_webhooks.jsx to be pure and use Redux

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
WIP: Migrate installed_incoming_webhooks.jsx to be pure and use Redux
#### Ticket Link
#6449
#6453 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by jwilander** [comment]
@sudheerDev this looks about right. Should we move ahead with this one and close #7191?

**Comment by jwilander** [comment]
The build failure is from one of the new tests:
```
FAIL  tests/components/integrations/installed_incoming_webhook.test.jsx
  ● components/integrations/InstalledIncomingWebhook › should match snapshot

    expect(value).toMatchSnapshot()
    
    New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.
    
    This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.
      
      at Object.<anonymous> (tests/components/integrations/installed_incoming_webhook.test.jsx:47:25)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
```

**Comment by sudheerDev** [comment]
@jwilander Yes, You can close it. I will update that failed test along with new tests for `installed_incoming_webhooks.jsx` component.

**Comment by sudheerDev** [comment]
@jwilander Can u go through this again. There is no logic in it connected component here. Does it require tests?. Let me know if there are any changes to be made.

**Comment by crspeller** [comment]
This PR needs to be re-submitted to the new separated webapp and server repositories.

**Pull request closed without merging**
