### PR TITLE
Support hiding plugin settings based on hosting environment

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR makes it so a given plugin can hide specific plugin settings based on the hosting environment of the server.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-44843

#### Related Pull Requests

- https://github.com/mattermost/mattermost-webapp/pull/10799
- https://github.com/mattermost/mattermost-plugin-zoom/pull/269

#### Release Note

```release-note
Plugins can now hide plugin settings based on the server's hosting environment.
```

### CODE REVIEW

**Comment by DHaussermann** [comment]
update-brach

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Tested with https://github.com/mattermost/mattermost-plugin-zoom/pull/269 which includes `"hosting": "on-prem"`
- Worked a expected for TE, E0, On-Pem and Cloud type licenses
- Briefly regression tested existing plugins that don't toggle field based on hosting. No impact found.
LGTM!

**Review by catalintomai — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Pull request merged**
