### PR TITLE
GH-12569: Migrates tests for "model/initial_load_test.go" to use testify

### LINKED ISSUE #12569: Migrate tests from "model/initial_load_test.go" to use testify
Mattermost is migrating its server tests from using the `t.Fatal` method calls on their checks to use the [testify toolkit](https://github.com/stretchr/testify). The goal of this migration is to improve the readability of the tests, making them more concise and meaningful. This Help Wanted issue is to migrate the tests in the `model/initial_load_test.go` file.

The expected way to migrate this is to go to the `model/initial_load_test.go` file and modify the calls to `t.Fatal` and the condition checks that lead to them, replacing them with calls to the [the `require` package](https://godoc.org/github.com/stretchr/testify/require) if a failure should stop the execution of the test, or [the `assert` package](https://godoc.org/github.com/stretchr/testify/assert) if it shouldn't.

Example: mattermost/mattermost-server#12039

If you have questions about the ticket or you need any help, feel free to contact `miguel.delacruz` or `jesus.espino` in <https://community.mattermost.com/>

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-19139

### PR DESCRIPTION
**Pull request by sahilsharma011**
Summary

Migrates tests for "model/initial_load_test.go" to use testify
Ticket Link

Fixes #12569

### CODE REVIEW

**Comment by sahilsharma011** [comment]
> sahilsharma011 needs to sign the CLA

I have signed the CLA but it is still showing that I need to sign it?

**Comment by marianunez** [comment]
@sahilsharma011 it looks like you would only need to synch your branch and then we would be able to merge your PR 🎉

**Comment by jespino** [comment]
Merged! Thanks @sahilsharma011! :tada:

**Pull request merged**
