### PR TITLE
Fix GetPluginStatus in a non-cluster environment

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The non-cluser case was not thought about in the initial implementation.

https://github.com/mattermost/mattermost-server/commit/4e93ffadb7c9eac7598c022a2b17512662f82b48 also fixes an issue with `setupMultiPluginApiTest` cleaning up `pluginDir` before the test completes.

While debugging a seemingly unrelated CI failure from `TestPostActionRelativePluginURL` I found that `setupMultiPluginApiTest` doesn't set `PluginStates` correctly to `Enable`. Because of that `SyncPlugins` will remove the plugin and the test fails. Fixed this in 048b61b65.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27481

### CODE REVIEW

**Comment by amyblais** [comment]
Removing from v5.27 for now until there are further details on urgency / level of risk.

**Review by crspeller — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei are you able to provide any guidance or test steps for this? I'm not quite understanding the issue and solution. 
Are we preventing the sync from happening now when it's a non-clustered environment?

**Comment by hanzei** [comment]
@DHaussermann The best way to test this PR is by verifying that the `GetPluginStatus` API method work with this fix:
1. Run a MM server with this changes
2. Deploy https://github.com/mattermost/mattermost-plugin-community
3. Deploy https://github.com/mattermost/mattermost-plugin-github
4. Connect GitHub account using `/github connect`
5. Run a slash command of the community e.g. `/community commiter mattermost 2019-01-01 2019-01-31`
6. Confirm that the command executes without an error.

**Comment by amyblais** [comment]
@DHaussermann Kind reminder to review for v5.28.

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Deployed this PR along with https://github.com/mattermost/mattermost-webapp/pull/6476 to be able to use GitHub connect normally
- Followed steps provided by Ben 
- Both commands worked as expected
LGTM!

Added test coverage for this to TM4J

**Pull request merged**
