### PR TITLE
MM-47064 Migrate "components/suggestion/suggestion.jsx" to Typescript

### PR DESCRIPTION
**Pull request by gitstart**
Summary
Migrate "components/suggestion/suggestion.jsx" to Typescript

### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21099
https://mattermost.atlassian.net/browse/MM-47064

### Release note
```release-note
Migrate "components/suggestion/suggestion.jsx" to Typescript
```
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Looks good to me. Thanks for moving this over and making those changes from last time

**Comment by hmhealey** [comment]
Actually, skipping QA review since these changes only affect type definitions and not the user-facing code

**Review by hmhealey — CHANGES_REQUESTED** [review]
@gitstart There's actually some type checking issues. Could you take a look at those?

https://github.com/mattermost/mattermost-server/actions/runs/4551459498/jobs/8039962722?pr=22725

**Review by hmhealey — CHANGES_REQUESTED** [review]
Now there's some linting errors unfortunately. We updated our version of ESLint, so those might be a "conflict" that didn't cause a git conflict

**Pull request closed without merging**
