### PR TITLE
MM-50419: Fix panic at interface conversion

### PR DESCRIPTION
**Pull request by agnivade**
We were incorrectly returning a subset of the methods,
whereas at other places, clients needed access to other
interfaces as well.

https://mattermost.atlassian.net/browse/MM-50419

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@amyblais - cp candidate for 7.7.

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
Merging, no issues related to bulk import.

**Comment by agnivade** [comment]
I'll send cp's myself.

**Pull request merged**
