### PR TITLE
[MM-51236] - Update newsletter opt-in copy

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Update copt of newsletter opt-in

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51236

#### Screenshots
Screenshot 2023-04-05 at 18 07 01

Screenshot 2023-04-05 at 18 07 53

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]

**Review by marianunez — COMMENTED** [review]
Thanks @AGMETEOR! Code LGTM but discussing with @johndavidlugtu some tweeks to the copy. Will update if there is changes

**Review by marianunez — CHANGES_REQUESTED** [review]
@AGMETEOR updated copy: 

`
I would like to receive Mattermost security updates via newsletter. By subscribing, I consent to receive emails from Mattermost with product updates, promotions, and company news. I have read the Privacy Policy and understand that I can unsubscribe at any time.
`

Same links as before. cc/ @johndavidlugtu

**Comment by johndavidlugtu** [comment]
@marianunez first sentence in bold yeah?

**Comment by marianunez** [comment]
> @marianunez first sentence in bold yeah?

@AGMETEOR, @annelieseklein updated the design here: https://www.figma.com/file/BVTl713i3DwG6lpKyziuYH/Account-Owner-Improvements?node-id=1%3A5611&t=JX1ialmjiZJudEG3-4 with the copy update and font change for the second part of the message

**Review by neallred — DISMISSED** [review]
:shipit:

**Comment by annelieseklein** [comment]
@AGMETEOR looks good! The bolded part should no longer be bold, but just normal, center channel text

**Comment by AGMETEOR** [comment]
Screenshot 2023-04-12 at 10 28 53

Screenshot 2023-04-12 at 10 29 39

cc: @annelieseklein

**Review by neallred — APPROVED** [review]

**Review by marianunez — APPROVED** [review]
Thanks @AGMETEOR! Code looks good, noticed that the light gray is slightly different than the other subtext in the fields above (username). @annelieseklein can confirm what color it should be

**Comment by annelieseklein** [comment]
> Thanks @AGMETEOR! Code looks good, noticed that the light gray is slightly different than the other subtext in the fields above (username). @annelieseklein can confirm what color it should be

@AGMETEOR booth should be 56% Center channel text

**Comment by AGMETEOR** [comment]
Screenshot 2023-04-13 at 09 56 15
cc: @annelieseklein

**Review by annelieseklein — APPROVED** [review]
looks great, thanks!

**Pull request merged**
