### PR TITLE
[MM-31745] Add translations for enterprise PR#1266

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

 Add translations for https://github.com/mattermost/enterprise/pull/1266

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-31745
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Will defer to Juho for another look at the error message.

**Comment by jupenur** [comment]
This error isn't really about verifying the certificate, right? It's about loading/parsing it?

**Comment by plant99** [comment]
> This error isn't really about verifying the certificate, right? It's about loading/parsing it?
Correct, let me change that.

**Review by jupenur — APPROVED** [review]
Much better, thanks @plant99!

**Comment by mkraft** [comment]
@plant99 What's the status of this PR?

**Comment by plant99** [comment]
https://github.com/mattermost/enterprise/pull/1266 this has to be e2e-tested, the command didn't work in the pull request itself. Requested Malik for help there.

**Pull request merged**
