### PR TITLE
Ordering clarifications

### PR DESCRIPTION
**Pull request by agnivade**
Clearly outline the dependency graph
during server bootup.

https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=87df1e15-588e-49ff-8bd1-ffa9651b8c82

### CODE REVIEW

**Comment by agnivade** [comment]
/release-note-none

@streamer45 - Could you re-check this? The plugin initialization is now moved out from NewServer to the products.Start phase. So the imaging initialization isn't really dependent on this any more. I tested with some plugins and it seems to work fine. Although I couldn't find any plugins that update user profiles on startup.

**Comment by streamer45** [comment]
> @streamer45 - Could you re-check this? The plugin initialization is now moved out from NewServer to the products.Start phase. So the imaging initialization isn't really dependent on this any more. I tested with some plugins and it seems to work fine. Although I couldn't find any plugins that update user profiles on startup.

Sure. Any plugin that calls `EnsureBot` with an image should trigger that I believe (e.g. playbooks).

**Comment by agnivade** [comment]
Yep, confirmed. Works fine.

**Review by streamer45 — APPROVED** [review]
Looks good :+1: 

My only comment is that we may consider placing imaging initializations further up given they are completely decoupled from the rest. I can see some of the logic that happens before potentially requiring those at some point (e.g. in app migrations, jobs). Not a blocker though.

**Comment by agnivade** [comment]
No worries, let me move up.

**Pull request merged**
