### PR TITLE
MM-23185 - Markdown image hosted by plugins are not shown if local image proxy is enabled

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
Local images (like the ones provided by plugins) should not go through proxy.
This PR checks is URL being passed is an absolute one before passing it to proxy

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23185

### CODE REVIEW

**Comment by lindy65** [comment]
@reflog - can you help upload `memes-1.1.0.tar.gz` from https://github.com/mattermost/mattermost-plugin-memes/releases to the spinwick for me please?  I am getting an error `Failed to fetch`

**Comment by reflog** [comment]
@lindy65 - done. plugin installed

**Comment by lindy65** [comment]
Thanks @reflog :)

**Comment by lindy65** [comment]
@reflog - checking that I am testing this correctly:
- enable local proxy
- post `/meme brace yourself. memes are coming.`
Expected: image for the meme is displayed

**Comment by reflog** [comment]
@lindy65 correct. with and without local image proxy being enabled

**Pull request merged**
