### PR TITLE
MM-10688: allow client4 http keep-alive

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Some years ago, we explicitly disallowed keep-alive on connections
initiated by the golang driver to the mattermost-server, possibly due to
memory leak issues. While this path isn't used directly via a typical
werver/webapp setup, it makes sense to allow keep-alive for any
third-party programmatic use of the API.

This commit will allow us to test `master` with the behaviour over some
time to identify any potential new troubles.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10688

#### Checklist
- [ ] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by lieut-data** [comment]
ABC discussed merging this to soak and verify that we aren't seeing any weird issues. We're already using it to good success on a custom build for a customer.

**Comment by jwilander** [comment]
I missed the discussion but by "soak" what do you mean? Just that the unit/load tests will run with it for a while? Because, as you say, it's not used in a normal server setup

**Comment by crspeller** [comment]
Going to use this as a PR to test loadtest label.

**Comment by jasonblais** [comment]
@crspeller Did the loadtest label work?

**Comment by jasonblais** [comment]
Moving to v5.1 since we're two days from code complete

**Comment by crspeller** [comment]
@jasonblais Unrelated to this PR, was just using it as a test.

**Comment by lieut-data** [comment]
@jwilander, yeah, the "soaking" was meant to ascertain if the unitests and/or loadtests started causing issues. Given the uncertain history of the original change here, I wanted to make sure we aren't missing something.

Once merged, I'll update the loadtests to reference same.

**Pull request merged**
