### PR TITLE
 [MM-11157]  Migrate "Channel.UpdateMember" to Sync by default

### LINKED ISSUE #11157: Migrate "Channel.UpdateMember" to Sync by default
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16332)

Mattermost is migrating its Store layer to be sync by default, and only use Async when needed and we're looking for contributors to help with that effort. This Help Wanted issue is to migrate the `UpdateMember` in the `Channel` store.

The expected way to implement it is, go to the `Channel` store implementation in the `store/sqlstore/` directory, modify the method `UpdateMember` to return directly an object from the `model` module, and a `*model.AppError` (removing the `store.Do` wrapper). After that, you must modify the interface defined in `store/store.go` to match with the changes. Then, you should execute `make store-mocks` to rebuild the mocks with the new interface. And finally, modify the rest of the code (tests included) to use the new interface of the function properly.

Example: mattermost/mattermost-server#10613

### PR DESCRIPTION
**Pull request by nafisfaysal**
#### Summary

This PR will migrate `Channel.UpdateMember` to Sync by default
#### Ticket Link
Fixes #11157

### CODE REVIEW

**Comment by jespino** [comment]
@nafisfaysal There are still some errors in the build.

**Comment by jespino** [comment]
@nafisfaysal can you take a look into this? it needs a merge from master and maybe review the failing tests.

**Comment by nafisfaysal** [comment]
@jespino Sorry for the late reply. I will work on there.

**Comment by jespino** [comment]
@nafisfaysal Thanks! :smiley:

**Comment by nafisfaysal** [comment]
@jespino Thank you so much for helping to solve this problem :D

**Comment by jespino** [comment]
Merged! Thanks @nafisfaysal! :tada:

**Pull request merged**
