### PR TITLE
MM-42714: Trim token sizes to 26 characters

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-42714

```release-note
NONE
```

### CODE REVIEW

**Review by srkgupta — APPROVED** [review]
Hi @agnivade 

The changes LGTM and is working fine. However a quick observation:

I am not sure if the length of HeaderCloudToken & HeaderRemoteclusterToken used in the same ParseAuthTokenFromRequest function will be less than or equal to 26. Can you please confirm this?

**Comment by agnivade** [comment]
It should be, but raised it to 50 to be safe.

**Review by noxer — APPROVED** [review]
Clever use of `defer`. LGTM.

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
Crap, I forgot that I ran an e2e test. @saturninoabril - could you please check the e2e and let me know if there were any issues?

**Pull request merged**
