### PR TITLE
add missing colmap

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
add missing ColMap

CI failure https://app.circleci.com/pipelines/github/mattermost/mattermost-server/24154/workflows/dfd64b19-7489-4e92-8809-719f0684b424/jobs/154862

🧵  (internal) https://community.mattermost.com/private-core/pl/n6aznzgxfjro9k9m5m6fajigjo

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by streamer45** [comment]
I am not sure the original PR (https://github.com/mattermost/mattermost-server/pull/17361) has been merged properly. This is missing other things like the index definition. I'd like @wiggin77 to take a look.

**Comment by cpanato** [comment]
yes, looks like there are more things to do.

**Comment by wiggin77** [comment]
> I am not sure the original PR (#17361) has been merged properly. This is missing other things like the index definition. I'd like @wiggin77 to take a look.

The PR referenced looks correct.
```
		tableSharedChannelUsers := db.AddTableWithName(model.SharedChannelUser{}, "SharedChannelUsers").SetKeys(false, "Id")
		tableSharedChannelUsers.ColMap("Id").SetMaxSize(26)
		tableSharedChannelUsers.ColMap("UserId").SetMaxSize(26)
		tableSharedChannelUsers.ColMap("RemoteId").SetMaxSize(26)
		tableSharedChannelUsers.ColMap("ChannelId").SetMaxSize(26)
		tableSharedChannelUsers.SetUniqueTogether("UserId", "ChannelId", "RemoteId")
```
Includes the colmap for ChannelId and has the correct unique columnns (should be 3).

**Comment by cpanato** [comment]
ahh looks like this PR was not cherry picked to the release-5.35 branch

> > I am not sure the original PR (#17361) has been merged properly. This is missing other things like the index definition. I'd like @wiggin77 to take a look.
> 
> The PR referenced looks correct.
> 
> ```
> 		tableSharedChannelUsers := db.AddTableWithName(model.SharedChannelUser{}, "SharedChannelUsers").SetKeys(false, "Id")
> 		tableSharedChannelUsers.ColMap("Id").SetMaxSize(26)
> 		tableSharedChannelUsers.ColMap("UserId").SetMaxSize(26)
> 		tableSharedChannelUsers.ColMap("RemoteId").SetMaxSize(26)
> 		tableSharedChannelUsers.ColMap("ChannelId").SetMaxSize(26)
> 		tableSharedChannelUsers.SetUniqueTogether("UserId", "ChannelId", "RemoteId")
> ```
> 
> Includes the colmap for ChannelId and has the correct unique columnns (should be 3).

**Comment by cpanato** [comment]
will close this and cherry pick that PR

**Comment by cpanato** [comment]
@wiggin77 humm ok, will check what is going on in the branch

**Pull request closed without merging**
