### PR TITLE
translations PR 20180903

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1656
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2072

### CODE REVIEW

**Comment by enahum** [comment]
should we close this one? it is against the wrong branch?

**Comment by cpanato** [comment]
maybe. @jasonblais ?

**Comment by jasonblais** [comment]
No harm merging these to master. As per https://github.com/mattermost/mattermost-server/pull/9350#pullrequestreview-152083172, we'll submit another PR to release branch after Friday's deadline.

**Comment by jasonblais** [comment]
Or is there harm?

**Comment by enahum** [comment]
there is probably going to be merge conflicts when merging the release branch to master again

**Comment by jasonblais** [comment]
I see, didn't realize. Fine to close then.

Closing given there may be merge conflicts when merging the release branch to master.

**Comment by cpanato** [comment]
Or we merge and cherry pick to the release branch

**Pull request closed without merging**
