### PR TITLE
[MM-16437] Plugin crashes the server when calling WriteHeader with an invalid http code

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Calling WriteHeader with an invalid http code will cause a panic (see: https://golang.org/pkg/net/http/#ResponseWriter) and crash the server. This fix will check if the provided code is valid, and prevent that crash by returning a error.
- Unfortunately, the error goes nowhere. WriteHeader does not return an error, so there's no way for the plugin to know it made a mistake. Not sure if there's a better way to do this. Open to suggestions.

#### Ticket Link
[MM-16437](https://mattermost.atlassian.net/browse/MM-16437)

### CODE REVIEW

**Comment by crspeller** [comment]
> Unfortunately, the error goes nowhere.

Could we pass a logger to `httpResponseWriterRPCServer` so it can log the error?

**Comment by hanzei** [comment]
@cpoile What do you think about the feedback above?

**Comment by jasonblais** [comment]
@cpoile Are there next steps for this PR?

**Comment by cpoile** [comment]
@lieut-data I think it makes sense to have a recover, but I assume it's out of scope for this PR. Made a ticket for Toolkit: https://mattermost.atlassian.net/browse/MM-17377

**Comment by cpoile** [comment]
@jasonblais Thanks, updated.

@crspeller Ready for review.

**Comment by jasonblais** [comment]
Thanks @cpoile! Looks like the latest commit failed to build.

**Comment by cpoile** [comment]
@jasonblais Thanks for the notification. It's an enterprise problem, or something. I'll just kick it a few times, hope that helps.

**Comment by lieut-data** [comment]
@cpoile, do we have any data on the prevalence of this problem? If this particular issue isn’t happening frequently, then I’m not really convinced we need to special case a fix for it when a more general class of problems with a more general solution exists.

Would I be correct in assuming that `WriterHeader(0)` was just a coding mistake in some plugin and isn’t likely to be encountered in real life?

**Comment by cpoile** [comment]
@lieut-data I mean, it's coder error for sure -- no-one should be setting a header to an invalid code. But we also shouldn't be crashing the server for some values of arguments. We may as well protect against it. Special case this now, and work on a general solution later?

**Comment by lieut-data** [comment]
My gut says there’s probably lots of ways to crash the server via a plugin, and that special casing a solution to one particular case isn’t the right approach.

IMO, I think we should set aside this solution and tackle the more general problem (perhaps by just throwing the ticket back into Toolkit’s backlog).

**Comment by cpoile** [comment]
Ok fair enough, I’ll throw it to Toolkit. :)
There is the ticket I created above, that covers this.

Closing based on discussion above.

**Comment by lieut-data** [comment]
@prapti, I think the behaviour you describe would unfortunately be expected -- there's actually no way for the error to be sent back to the plugin that they specified an invalid status code (since the `WriteHeader` interface doesn't return an error), so the default behaviour of emitting 200 when no other status code is actually sent would prevail. 

The error log would be expected to alert the developer, along with the fact that they won't get the desired status code.

**Comment by prapti** [comment]
Thanks for clarifying that @lieut-data!

**Pull request merged**
