### PR TITLE
[MM-49087] Bump NPS to 1.3.1

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Bump NPS version to 1.3.1

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49087

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]

**Review by marianunez — APPROVED** [review]

**Comment by JulienTant** [comment]
I swear I did not break all of that CI red nonsense 😂

**Comment by JulienTant** [comment]
Hi @amyblais, we would like to have this PR cherry pick in the next `7.5.x` release, fixing this bug: https://mattermost.atlassian.net/browse/MM-49064

**Comment by amyblais** [comment]
Sounds good 👍

**Review by lieut-data — APPROVED** [review]

**Comment by amyblais** [comment]
This will need a manual cherry-pick.

**Comment by JulienTant** [comment]
https://github.com/mattermost/mattermost-server/pull/21892

**Pull request merged**
