### PR TITLE
MM-23211: Fix user not being notified in out of channel mentions

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

If the @username ended with a period, then we would send the string
containing the period to the DB to get the user profile. This would
not return anything and therefore, that user would not be part of
the mention post that would be sent.

We fix this by checking if the mentioned word ends with a character
that can be at the end of a sentence, and then remove that character.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-23211

### CODE REVIEW

**Comment by agnivade** [comment]
Hi @jgilliam17 - This is ready for QA review now. Thanks.

**Comment by cpanato** [comment]
im checking the test server issue

**Pull request merged**
