### PR TITLE
move migration to future release as 536 is already done

### PR DESCRIPTION
**Pull request by darkLord19**
Related to PR #17680

### CODE REVIEW

**Comment by darkLord19** [comment]
@agnivade

**Review by jespino — APPROVED** [review]
LGTM

**Comment by agnivade** [comment]
@darkLord19 - I am trying to look back into the timeline of events here. It seems like the revert commit added the migration rather than removing it. Was that intentional?

And did the revert happen _after_ 5.36 was released or before?

**Comment by darkLord19** [comment]
@agnivade 
original pr was reverted on 21st may, so there you can see migration being removed
then i had reverted the above revert to basically bring back the feature which was merged around 14-15th June and it's not shipped in 5.36.1
So, i have raised this pr to move migrations to 5.37 release

**Comment by agnivade** [comment]
Right, so then technically, when we un-reverted it, the migration should have moved to the 5.37 function right? Just confirming the timeline of events here.

**Comment by darkLord19** [comment]
Yes you are correct. I was under the impression that it'll go in 5.36 but today I got the chance to take look at release branch and didn't find the pr there so raised separate pr to move the migration

**Review by agnivade — APPROVED** [review]

**Pull request merged**
