### PR TITLE
allow "postgresql://" URL scheme for config in database

### PR DESCRIPTION
**Pull request by jetpackdanger**
The libpq code accepts both postgres:// and postgresql://, and
the latter already works when set in e.g. MM_SQLSETTINGS_DATASOURCE.

I discovered this while working on a Mattermost deployment that
uses a Juju-deployed database.  The URL returned by the interface
code to my charm begins with "postgresql://", which did not cause
a problem until I supplied the same data source URL in MM_CONFIG.

### CODE REVIEW

**Comment by agnivade** [comment]
If we allow this, I think we should also allow "postgresql" in the `DriverName`. It would look inconsistent if one uses postgres, and other uses postgresql.

**Comment by jetpackdanger** [comment]
Thanks for taking a look at this! I've pushed a new version with the parseDSN change.

I've made a start on allowing "postgresql" to be a valid DriverName, but I have a ways to go yet. A couple of tricky points I've found: quite a bit of code makes comparisons to DriverName struct members directly for various purposes; and lib/pq only registers itself as "postgres", despite accepting URLs with a scheme of "postgresql". I hope to have time to work more on this soon.

**Comment by jasonblais** [comment]
@lieut-data @agnivade friendly reminder to help with QA review :) Should this also get a review from a PM (probably Dennis).

Big thanks @jetpackdanger for the contribution! Apologies for the long review time.

**Comment by agnivade** [comment]
Hi @jetpackdanger - It seems that this PR still needs to be updated with the DriverName changes. Do you have that in your radar? Also, it would be good to have some tests to cover the new scenarios.

**Comment by hanzei** [comment]
@jetpackdanger Do you have questions about the feedback? 
Please note that we will close this PR after another 10 days of inactivity. If you don't object, other contributors might complete this PR for you.

**Comment by isacikgoz** [comment]
Closing this PR due to inactivity, thanks for the effort anyway @jetpackdanger 👍

**Pull request closed without merging**
