### PR TITLE
Migrate SAML keys and certificates

### PR DESCRIPTION
**Pull request by RajatVaryani**
#### Summary
Config migrate SAML keys and certificates

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/10654

### CODE REVIEW

**Comment by hanzei** [comment]
@RajatVaryani Let me know, when this is ready for review

**Comment by RajatVaryani** [comment]
> @RajatVaryani Let me know, when this is ready for review
Sure I will. Give me some time.

**Comment by RajatVaryani** [comment]
@hanzei Was in some other work. I will complete the PR in a couple of days.

**Comment by RajatVaryani** [comment]
I will raise another PR.

**Pull request closed without merging**
