### PR TITLE
[MM-36664] Added plugin API methods for user access tokens and OAuth apps

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR adds plugin API methods to create and revoke access tokens and create, get and delete OAuth apps.

The PR is base off https://github.com/mattermost/mattermost-server/pull/17798 so plugin can pick up the changes in both PRs.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36664

#### Release Note
```release-note
Added plugin API methods for user access tokens and OAuth apps
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
:tada:

**Review by ankitnayan — APPROVED** [review]

**Review by mickmister — APPROVED** [review]
Nice!

**Comment by hanzei** [comment]
@DHaussermann My suggestion would be to test this PR as part of https://github.com/mattermost/mattermost-plugin-apps/pull/209.

**Comment by hanzei** [comment]
@larkox @mickmister Heads up that I added an `UpdateOAuthApp` method in [`a30cf31` (#17832)](https://github.com/mattermost/mattermost-server/pull/17832/commits/a30cf31ea0bcd5223fed04fb54b682645d7dc2a6). It's a minor change and hence I didn't re-request a review.

**Comment by DHaussermann** [comment]
@hanzei 
1. Can you provide some test guidance or steps for this short of regression testing (with focus on install/uninstall flows)?
2. There is an issue preventing me form deploying this for testing. The changes seem to depend on https://github.com/mattermost/mattermost-server/pull/17798 however, when I have this branch of server deployed, I do not meet the minimum version of `v5.37.0` and get `ERRO[2021-07-05T11:21:22.2081149-04:00] Unable to activate plugin                     caller="mlog/log.go:251" error="plugin requires Mattermost 5.37.0: com.mattermost.apps" plugin_id=com.mattermost.apps` Is there an easy way to side step this? applying a cloud license did not change the behavior.

**Comment by hanzei** [comment]
1. My suggestion is to test this PR alongside https://github.com/mattermost/mattermost-plugin-apps/pull/209 as that PR make great use of the added changes. Same with https://github.com/mattermost/mattermost-server/pull/17798.
2. Good catch. Merging `master` should have fixed that. Please test again.

**Comment by hanzei** [comment]
@DHaussermann 

1. My suggestion is to test this PR alongside https://github.com/mattermost/mattermost-plugin-apps/pull/209 as that PR make great use of the added changes. Same with https://github.com/mattermost/mattermost-server/pull/17798.
2. Good catch. Merging `master` should have fixed that. Please test again.

**Comment by amyblais** [comment]
@DHaussermann Kind note that v5.38 feature complete is next Monday, July 19th (this PR has a v5.38 milestone).

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Install path is working normally
- On uninstall
  - OAth app is deleted
  - Bot bos deactivated
  - Bot token is deleted
 - Confirmed this with 3 different apps
 - Confirmed with apps installed both via http and AWS (though this is likely irrelevant)
 - Confirmed install / uninstall is working both with this PR as well as latests release of apps plugin (`v0.7.0`)
 - No issues found related to this change
 
 LGTM!

**Pull request merged**
