### PR TITLE
Replacing test images no longer available at source

### PR DESCRIPTION
**Pull request by lindalumitchell**
#### Summary
Four test images used in this test post are no longer available at the source. Replaced URLs with working test images.

#### Ticket Link
No ticket; updating a test only.

### CODE REVIEW

**Comment by amyblais** [comment]
The "Tall Portrait Image" ones are not rendering when I preview this doc. Also, when I paste them in a pre-release channel they don't have a link preview. Wondering if this is because they are not set up for opengraph. We can also ask Asaad if he knows why they don't render here.

**Comment by lindalumitchell** [comment]
Thanks Amy! I'll take another look. I tested around this requirement manually as well, so it's not urgent for this release.

**Comment by lindalumitchell** [comment]
@amyblais I took another look; I think the preview within GitHub may do that sometimes; I fired up a spinmint and `/test url test-markdown-basics` works there, with all images rendering as expected. If you try it on the spinmint does it appear as expected for you?

I also am seeing the image when I post the image URL `https://upload.wikimedia.org/wikipedia/en/9/93/Burj_Khalifa.jpg` or `Portrait` on rctesting, pre-release, and ci-linux-postgres. But I'm wondering what you saw/didn't see when you tested? Was it just the image URL or the inline image?

**Comment by amyblais** [comment]
@lindalumitchell They work properly on spinmint 👍 They also work on ci servers.

However, on pre-release they don't work for me - either only the link gets posted or the attached happens: 

screenshot at nov 08 14-27-06

But this is not related to this PR so I can investigate further.

**Comment by jasonblais** [comment]
Is this one ready to merge @lindalumitchell @amyblais ?

**Comment by lindalumitchell** [comment]
@jasonblais I think there are still issues on community.mattermost.com with the test images I selected, possibly due to image proxy? That particular release test is not meant to include image proxy, so it would be fine, though if anyone also tries it on community the same questions might arise. I tried to find suitable test image URLs that work on both but so far no luck.

I think for now it would be okay to merge, and I can make a note in the test that it is not meant for testing on a server with image proxy. If others are okay with that, then we can merge.

**Comment by jasonblais** [comment]
I'm curious why the image links don't work with an image proxy. Is that a bug?

**Comment by lindalumitchell** [comment]
Still looking into this; found an older ticket where the following images were used for this test (instead of the ones I found, which may be unsuitable in a way I'm not yet aware of), and they worked perfectly on the Se server, but mixed results on other servers. None were broken images, but the resizing was inconsistent (not resized at all, or the third one resized but not to a square). Did some research but still not clear about inconsistent behavior between servers; will ask Asaad after this release is done. Tested manually for v5.6.

```
Tall Portrait Image:  
![Portrait](http://coolinfographics.com/storage/VinTank%20Infographic%20FINAL%20600px%20revised.jpg)

Tall Portrait Image (resized):  
![Portrait](http://coolinfographics.com/storage/VinTank%20Infographic%20FINAL%20600px%20revised.jpg?__SQUARESPACE_CACHEVERSION=1305727805878 =x200)

Tall Portrait Image (resized to a square):  
![Portrait](http://coolinfographics.com/storage/VinTank%20Infographic%20FINAL%20600px%20revised.jpg?__SQUARESPACE_CACHEVERSION=1305727805878 =200x200)
```

**Comment by hanzei** [comment]
Hey @lindalumitchell, did you got an update from Asad? Just want to check if there any updates.

**Comment by hanzei** [comment]
@lindalumitchell Could you take a look at my question above?

**Comment by lindalumitchell** [comment]
Thanks @hanzei and so sorry I've let this sit stale! I think I'll close this for now and open a new PR after I've fine-tuned the details rather than leaving this sitting open. I've been testing this one manually and have put investigating the remaining questions in my 'backlog'. Filed https://mattermost.atlassian.net/browse/MM-13821 to follow up.

**Pull request closed without merging**
