### PR TITLE
Filter by templated schema name for postgres queries

### PR DESCRIPTION
**Pull request by agnivade**
- Also upgrading other parts of the codebase that used morph
since there were other changes to the morph API.

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
waiting for https://github.com/mattermost/morph/pull/19 to merge first.

**Comment by agnivade** [comment]
@isacikgoz - New one with your proposed change.

**Review by isacikgoz — APPROVED** [review]
LGTM 🚀

**Comment by agnivade** [comment]
Cool, going to see if this commit triggers the correct build vars.

**Comment by nab-77** [comment]
@cwarnermm I don't see a need to call it out as we don't currently document/support multiple MM instances in a single DB.

**Comment by agnivade** [comment]
This change is mainly helpful in our cloud production environment, where we use multiple instances in a single DB. Other customers should not need to know about this.

**Pull request merged**
