### PR TITLE
MM-22188  Minor grammatical error in Guest User restriction text

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
Fixed wording

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-22188

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @reflog 

Tested on the spinwick and it seems an extra word - `via` - has crept in to the sentence. It should read `Guests are restricted from joining a team with an invite link. Please request a guest email invitation to the team.`

image

**Comment by reflog** [comment]
@lindy65 - I've added 'via' according to the comment from Justine

**Comment by reflog** [comment]
just need to remove the 'with' word :)

**Comment by lindy65** [comment]
Ah, I've just seen Justine's suggestion on the ticket...  Then the word `with` should be removed and it should read:
`Guests are restricted from joining a team via an invite link. Please request a guest email invitation to the team.`

**Comment by reflog** [comment]
@lindy65 - done

**Pull request merged**
