### PR TITLE
Document minimum server version for plugin API methods

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR adds an additional comment line to the API methods in `plugin/api.go` to documented the minimum server version.

If this PR gets accepted, a note about this should be added to https://developers.mattermost.com/contribute/server/plugins/.

#### Ticket Link
https://pre-release.mattermost.com/core/pl/uoysz3mtrfyc7ksdt7buuds64e

### CODE REVIEW

**Comment by hanzei** [comment]
I created this PR via https://github.com/mattermost/mattermost-server/commits/master/plugin/api.go. Hope I did't miss something.

**Comment by hanzei** [comment]
There are currently a lot of open PR which add methods to the plugin API. How do we deal with this?

**Comment by jasonblais** [comment]
> Off topic question: Why did you assign this to v5.6.0? isn't v5.5.0 the next release?

Good question. Mattermost is moving to a different release cycle starting in October, where 
 - every second month we have a feature release (October, December, February, ..), and
 - every second month we have a quality/bug fix release (November, January, ..).

So given this is not a bug fix, it's shipped in v5.6 by default.

**Comment by hanzei** [comment]
> Mattermost is moving to a different release cycle starting in October

Oh interesting. Didn't know this until now.

Knowing this I will have to update the version since I assumed changes on the current master would go into v5.5 but instead they will go into v5.6.

**Comment by lieut-data** [comment]
@hanzei, re: all the open PRs, I agree we should starting asking contributors to add a comment. Having your PR merged will provide a reference point as such.

**Comment by hanzei** [comment]
Thanks for the feedback @lieut-data ! I updated the file to be in sync with master.

**Comment by lieut-data** [comment]
Thanks so much, @hanzei :)

**Comment by lieut-data** [comment]
@hanzei, feel free to dive in with a suggestion block comment. I've been circling back to them as I do reviews, but don't mind at all if you provide feedback as well :)

**Pull request merged**
