### PR TITLE
[MM-16146] When converting a bot to a user, set the role to system_user

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
When a bot is created via the `/api/v4/bots` endpoint, and then converted to a user, via the mattermost CLI, that user will not be able to view any joinable teams once logged into to Mattermost.  This was caused by the converted bot user not having any specified roles. 

To fix this, set the role to `model.SYSTEM_USER_ROLE_ID` (resolves to "system_user").

I question whether there would be a case where we would want any other role setting, other than `model.SYSTEM_USER_ROLE_ID`.  The other options would be to set to as system admin or as previously set in this bug, with no roles.

Note that once a bot is converted to a user, the sysadmin of the mattermost instance has the power to adjust any permissions just as a normally created user. 
#### Testing

1. Create bot with `http://localhost:8065/api/v4/bots` endpoint
2. Payload example `{"username":"api_junkbot10","display_name":"api_junkbot4","description":"test bot"}`
3. Convert bot to user with `mattermost user convert api_junkbot10 --user --email api_junkbot10@fakedomain.com --password password1`
4. login as bot and observe availabe teams to join

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16146

### CODE REVIEW

**Comment by crspeller** [comment]
@jfrerich I just created some bot users locally and they all have the `system_user` role. Under what conditions does it not get set?

**Comment by jfrerich** [comment]
@crspeller they don't get the `system_user` role when the bot is created through the API.  Through the UI works correctly.  Were your bot creations through the UI?

**Comment by crspeller** [comment]
@jfrerich I did create them though the UI. But the UI uses the API to create them. Did you mean the plugin API? The github bot account on my local instance has the right role.

**Comment by jfrerich** [comment]
The UI calls `http://localhost:8065/api/v4/bots`, but also calls `/api/v4/users/<userId>/roles` to set the the `system_user` role.  

The issue Dylan was noticing (or expecting) is that creating a bot through `api/v4/bots` and then converting the bot to a user through the CLI should allow that user to join open teams.  The issue is that this puts the bot in a state that does not have any `roles`.  

Perhaps this is not an actual issue, but incorrect usage of the API and the user should also call the `/api/v4/users/<userId>/roles` endpoint?  Should we handle the setting of the `roles` through `http://localhost:8065/api/v4/bots` endpoint or do you recommend leaving as is?

**Comment by jfrerich** [comment]
@crspeller Another thought is that I should probably leave the `app/bot.go` alone and handle the roles inside `botToUser()` function in `cmd/mattermost/commands`

**Comment by crspeller** [comment]
@jfrerich Ahhh that's what is happening.

> Another thought is that I should probably leave the `app/bot.go` alone and handle the roles inside `botToUser()` function in `cmd/mattermost/commands`

Yes. But to prevent this from being blank I think you should add it to the user before it gets saved in CreateBot. Rather than updating it after the fact.

**Comment by jfrerich** [comment]
@crspeller Roles is now added to the user object before the Bot user is created.

**Comment by aaronrothschild** [comment]
Noted in documentation that when a bot is converted to a user, they are automatically assigned the role of 'system_user'

**Pull request merged**
