### PR TITLE
MM-11229: Backport to 4.10

### PR DESCRIPTION
**Pull request by grundleborg**

### CODE REVIEW

**Comment by amyblais** [comment]
Harrison is off also tomorrow, is there another dev that can review these backport PRs?

**Comment by cpanato** [comment]
@grundleborg can you add this commit here as well? https://github.com/mattermost/mattermost-server/commit/dccd95bc67779a5b83a2660aec0cf4622cd56550

**Comment by cpanato** [comment]
@amyblais are we planning release for 4.10?

**Comment by amyblais** [comment]
@cpanato Yes, and also for 5.0 https://github.com/mattermost/mattermost-server/pull/9075.

4.10 and 5.0 dot releases should be released at the same time as v5.1.

**Comment by hmhealey** [comment]
@grundleborg Same errors as on the other PR

**Comment by grundleborg** [comment]
Reverted the test change as it sets a config that didn't exist prior to 5.0

**Comment by amyblais** [comment]
Is anything blocking merging the backport PRs so we can cut RC-1s soon?

**Comment by cpanato** [comment]
Will cut the RC for 4.10.2

**Pull request merged**
