### PR TITLE
Fix add bot error handling

### PR DESCRIPTION
**Pull request by LeonardJouve**
#### Release Note

```release-note
NONE
```
Please have a look at this PR [Github](https://github.com/mattermost/mattermost-webapp/pull/12174)

### CODE REVIEW

**Comment by hmhealey** [comment]
@M-ZubairAhmed @mickmister This PR finished dev review on the web app repo, so feel free to just do a quick check to make sure that changes look the same before approving

**Review by mickmister — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
When the error occurs now it stops the user from returning to the bot list and show a validation message.
Briefly explore for regressions. No issues found. 
 
image

Thanks @LeonardJouve for fixing this. This issue was bothersome as the users chnages get silently discarded with no details.

**Comment by DHaussermann** [comment]
Hi @LeonardJouve, Sorry I missed getting to your PR before the Monorepo change. 
There is 1 dev review left before merge but, I did not want to risk this slipping too far into my queue again so I have approved it now. 
Someone will re-request review if dev review requests any code changes.

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
