### PR TITLE
add docker-compose for ci

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
when using the port to map the port from the docker to the host we cannot run multiple docker compose in the same host which for CI will break

the current master is failing because the job run the build for EE and TE in the same node, also we might see PR failing because the PR build can run in the same node for multiple PRs at same time

This PR adds a docker-compose file for CI the downwards of that is we will need to maintain two docker compose when updating.

#### Ticket Link
n/a

### CODE REVIEW

**Comment by cpanato** [comment]
if we merge this:
- i will update the job for the branch
- i will update the job for enterprise

**Comment by ali-farooq0** [comment]
Is this why https://build.mattermost.com/blue/organizations/jenkins/mp%2Fmattermost-server-pr-new/detail/PR-11779/17/pipeline is failing?

Having two very similar docker compose files might result in future maintenance pain. Any way we can dynamically derive one from the other?

**Comment by cpanato** [comment]
@ali-farooq0 yes this is the reason, we need to remove the ports from the docker-compose

**Comment by lieut-data** [comment]
@cpanato / @mkraft, I took the liberty of adopting my own proposals in your PRs to push the commit above, hoping to side-step issues tomorrow morning when everyone else comes back online.

**Comment by cpanato** [comment]
thanks so much, @lieut-data for stepping in agree and I will merge this to unblock the others

**Pull request merged**
