### PR TITLE
[MM-29901] Remove redundant indexes

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR removes several redundant db indexes on columns that were covered by existing keys:

```
# ########################################################################
# mattermost_test.ChannelMembers                                          
# ########################################################################

# idx_channelmembers_channel_id is a left-prefix of PRIMARY

# ########################################################################
# mattermost_test.Channels                                                
# ########################################################################

# idx_channels_name is a left-prefix of Name

# ########################################################################
# mattermost_test.Emoji                                                   
# ########################################################################

# idx_emoji_name is a left-prefix of Name

# ########################################################################
# mattermost_test.OAuthAccessData                                         
# ########################################################################

# idx_oauthaccessdata_client_id is a left-prefix of ClientId

# ########################################################################
# mattermost_test.OAuthAuthData                                           
# ########################################################################

# idx_oauthauthdata_client_id is a duplicate of PRIMARY

# ########################################################################
# mattermost_test.Posts                                                   
# ########################################################################

# idx_posts_channel_id is a left-prefix of idx_posts_channel_id_update_at

# ########################################################################
# mattermost_test.Preferences                                             
# ########################################################################

# idx_preferences_user_id is a left-prefix of PRIMARY

# ########################################################################
# mattermost_test.ProductNoticeViewState                                  
# ########################################################################

# idx_notice_views_user_id is a left-prefix of PRIMARY
# idx_notice_views_user_notice is a duplicate of PRIMARY

# ########################################################################
# mattermost_test.PublicChannels                                          
# ########################################################################

# idx_publicchannels_name is a left-prefix of Name

# ########################################################################
# mattermost_test.RetentionPolicies                                       
# ########################################################################

# Key IDX_RetentionPolicies_DisplayName_Id ends with a prefix of the clustered index

# ########################################################################
# mattermost_test.SharedChannelUsers                                      
# ########################################################################

# idx_sharedchannelusers_user_id is a left-prefix of UserId

# ########################################################################
# mattermost_test.Status                                                  
# ########################################################################

# idx_status_user_id is a duplicate of PRIMARY

# ########################################################################
# mattermost_test.TeamMembers                                             
# ########################################################################

# idx_teammembers_team_id is a left-prefix of PRIMARY

# ########################################################################
# mattermost_test.Teams                                                   
# ########################################################################

# idx_teams_name is a duplicate of Name

# ########################################################################
# mattermost_test.UserAccessTokens                                        
# ########################################################################

# idx_user_access_tokens_token is a duplicate of Token

# ########################################################################
# mattermost_test.UserTermsOfService                                      
# ########################################################################

# idx_user_terms_of_service_user_id is a duplicate of PRIMARY

# ########################################################################
# mattermost_test.Users                                                   
# ########################################################################

# idx_users_email is a duplicate of Email
```

@mgdelacroix I wasn't exactly sure how we wanted this handled in the new migration. I've modified the existing files to make things work but let me know if we should add new ones instead.

#### Ticket

https://mattermost.atlassian.net/browse/MM-29901

#### Release Note

```release-note
Removed several redundant db indexes.
```

### CODE REVIEW

**Comment by agnivade** [comment]
Can't wait for this to go live.. Will be also interesting to see the total size reduction of our Community cluster.

**Review by mkraft — APPROVED** [review]

**Review by agnivade — APPROVED** [review]

**Comment by streamer45** [comment]
@saturninoabril 

Was thinking an e2e test run should cover this, just making sure functionality is kept unchanged.

**Comment by streamer45** [comment]
Going to defer QA since Saturn is out. Ran a comparative load-test which didn't show any significant change in performance. I think it's good to get tested on community.

**Comment by mgdelacroix** [comment]
Just back from PTO. This is awesome @streamer45!! :rocket: Will include the changes in the new system as well

**Comment by streamer45** [comment]
> Just back from PTO. This is awesome @streamer45!!  Will include the changes in the new system as well

Thanks Miguel, that would be great :+1:

**Pull request merged**
