### PR TITLE
allow plugins on FreeBSD

### PR DESCRIPTION
**Pull request by swills**
#### Summary
Plugins don't currently work on FreeBSD, though the server does. This
fixes the plugins.

#### Release Note

Fix plugins on FreeBSD

### CODE REVIEW

**Comment by swills** [comment]
Maybe not needed due to #14493 #14682

**Review by hanzei — CHANGES_REQUESTED** [review]
https://github.com/mattermost/mattermost-server/pull/14682 recently added support for arbitrary platform. It isn't released yet and will be added in v5.32.0 releasing next month.

Could you give that PR a try and let me know if it resolves your need?

**Comment by emilyacook** [comment]
@swills let me know if this PR can be closed or if there's anything else we can help you with!

> #14682 recently added support for arbitrary platform. It isn't released yet and will be added in v5.32.0 releasing next month.
> 
> Could you give that PR a try and let me know if it resolves your need?

**Comment by hanzei** [comment]
Please note that we will close this PR after another 10 days of inactivity. If you don't object, other contributors might complete this PR for you.

**Comment by lindy65** [comment]
Closing this PR based on the above comment back in March.

**Pull request closed without merging**
