### PR TITLE
[MM-22846]: add a feature flag for post forwarding

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
adds a feature flag for post forwarding

#### Ticket Link
[MM-22846](https://mattermost.atlassian.net/browse/MM-22846)

#### Release Note
```release-note
adds a feature flag for post forwarding
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by amyblais** [comment]
@michelengelen Will this be merged now too?

**Comment by michelengelen** [comment]
@amyblais IDK why the CI run failed there.

**Comment by amyblais** [comment]
@michelengelen Are you able to check the details for the CI failure?

**Comment by michelengelen** [comment]
@amyblais I have no idea whats going wrong there ... I have not changed anything on i18n 

@ashishbhate could you assist?

**Comment by ashishbhate** [comment]
The CI is complaining about a translation string that was removed in #20368. This shouldn't be happening because this PR is up to date with master and hasn't changed any of the i18n files.

I don't know why the CI check is find the translations again. Could be a caching issue with the CI workspace. 

@amyblais who owns the Circle CI stuff? I think they might need to take a look.

**Comment by pfltdv** [comment]
Pipeline code creates temporary branches to execute some checks. It is needed since we have multi repositories and some of the pipelines need to be executed in enterprise and in different CI system. This happened cause of just bad timing. Will fix branch on enterprise.
https://github.com/mattermost/enterprise/tree/feature/MM-22846

**Comment by pfltdv** [comment]
EE repo is updated and New pipeline is triggered https://app.circleci.com/pipelines/github/mattermost/enterprise/17534/workflows/163c8aa0-b896-4432-928c-312b7fde7b96

**Pull request merged**
