### PR TITLE
MM-47537 Export and import read channels

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
This PR adds the (un)read status of channels to the exports. This prevents all channels from being marked as unread on import which makes moving servers more convenient for users.

#### Ticket Link
[MM-47537](https://mattermost.atlassian.net/browse/MM-47537)

#### Release Note
```release-note
Export files now contain the (un)read status for channels.
```

[MM-47537]: https://mattermost.atlassian.net/browse/MM-47537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Can we update the `TestExportUserChannels` test to ensure that these new fields are included in the export?

**Review by agnivade — APPROVED** [review]
Nice!

**Comment by justinegeffen** [comment]
I'm putting together the docs for this and noticed that for ``UrgentMentionCount *int64                            `json:"urgend_mention_count,omitempty"``` there's a possible typo ("urgend"). @noxer, would you be open to adjusting this if it is a typo? :)

**Pull request merged**
