### PR TITLE
Cherry pick of #20295  into release-6.5

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Cherry pick of #20295 

FYI @agnivade backported sqlx methods as well for the `AutoComplete` methods.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
Crap, this is failing because the CI machine image is outdated. We updated it in master, but now we need to backport that in all of these branches as well.

cc @pfltdv @phoinixgrr

**Comment by amyblais** [comment]
I created a ticket for devops https://mattermost.atlassian.net/browse/DOPS-1050.

**Pull request merged**
