### PR TITLE
MM-32657: Update group sync to work with AD - SAML ids

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
When using SAML (ADFS) for authentication and LDAP Group Sync (AD/LDAP). LDAP Group Sync doesn't work unless EnableSyncWithLdapIncludeAuth = true, which causes the AuthData to be stored in AD/LDAP format.

This PR updates the Group Sync process to check for both formats. This is a similar change that was made to the user sync process.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32657
also fixes
https://mattermost.atlassian.net/browse/MM-29522

#### Related PRs
https://github.com/mattermost/enterprise/pull/945
#### Release Note
```release-note
Fixed Group Sync issue using ADFS and AD/LDAP
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by hahmadia — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
image

**Pull request merged**
