### PR TITLE
Revert "MM-24530-Add support for search terms with underscore using postgresql engine"

### PR DESCRIPTION
**Pull request by agnivade**
Reverts mattermost/mattermost-server#16618

Failed during release testing.

```release-note
NONE
```

### CODE REVIEW

**Review by ethervoid — APPROVED** [review]
LGTM!

**Comment by amyblais** [comment]
@agnivade Ok, probably good to also cherry-pick to ``cloud`` for the next release. Is this a high severity issue?

**Comment by agnivade** [comment]
I would say it's medium severity. The impact is that any search containing an underscore would fail for 99% of Postgres databases.

/cherry-pick cloud

**Comment by agnivade** [comment]
Haha @isacikgoz , funny bug. I mixed the cherry-pick command with other text, and it picked up the branch as "would", which is the second word in the message :stuck_out_tongue:

**Pull request merged**
