### PR TITLE
MM-52888 Always load users mentioned in message attachments

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
We currently render at-mentions in message attachments, but only if those users were loaded some other way. Now they're always loaded like we do for post text

#### Ticket Link
MM-52888

#### Related Pull Requests
https://github.com/mattermost/mattermost-mobile/pull/7361

#### Release Note
```release-note
Ensured users mentioned in message attachments are loaded by the web app
```

### CODE REVIEW

**Review by cpoile — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
Hi @hmhealey ,
I tried few e2e tests locally. it seem's to throw error `You do not have the appropriate permissions` for /leave, /invite (for most of slash commands)

can you please help in analysing if there anything causing it?

**Review by yasserfaraazkhan — APPROVED** [review]
thank you for the changes Harrison

**Pull request merged**
