### PR TITLE
[MM-45052] Mark method as deprecated

### PR DESCRIPTION
**Pull request by cyrilzhang-mm**
#### Summary

Mark method as deprecated 

#### Ticket Link

[Jira ticket](https://mattermost.atlassian.net/browse/MM-45052)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by plant99 — APPROVED** [review]
I'm sure we might have considered, but plugins might break if people would update mattermost without updating plugins. Let's keep an eye out for the errors.

**Comment by BenCookie95** [comment]
I think focalboard currently supports

> I'm sure we might have considered, but plugins might break if people would update mattermost without updating plugins. Let's keep an eye out for the errors.

This is a valid concern, I'm not sure if this is something we officially support or not. Would be worth checking out

**Review by agnivade — CHANGES_REQUESTED** [review]
Sorry, we cannot remove any public method from model package until 8.0. It's a breaking change.

**Comment by agnivade** [comment]
Plugins are tied to a specific dependency version, so they won't break immediately when a new MM server is used. But they'll break if they upgrade the MM dependency version.

**Comment by cyrilzhang-mm** [comment]
Thanks @agnivade. Can we do something like mark it as deprecated instead?

**Comment by agnivade** [comment]
We sure can: https://github.com/golang/go/wiki/Deprecated

> To signal that an identifier should not be used, add a paragraph to its doc comment that begins with Deprecated: followed by some information about the deprecation, and a recommendation on what to use instead, if applicable. The paragraph does not have to be the last paragraph in the doc comment.

**Review by BenCookie95 — APPROVED** [review]

**Pull request merged**
