### PR TITLE
Pre-package Playbooks v1.28.1

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package Playbooks v1.28.1.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-44232

#### Release Note
```release-note
Pre-package Playbooks v1.28.1.
```

### CODE REVIEW

**Comment by lieut-data** [comment]
@jgilliam17, would you be in a position to help validate this PR? The primary goal is to ensure Playbooks v1.28 is pre-packaged, but of course I can do that too. I recall there are also manual smoke tests that we are building up in Zephr, but I'm not as familiar with those.

**Comment by jgilliam17** [comment]
@lieut-data 
Should I have a playbook tour available when I login for the first time
Screen Shot 2022-06-01 at 5 08 50 PM
?

**Comment by lieut-data** [comment]
> Should I have a playbook tour available when I login for the first time

@jgilliam17, I believe so, but I don't know how that feature works without the corresponding portal flow to "ask" what features you want to setup. @marianunez, would you happen to know what triggers this?

**Comment by jgilliam17** [comment]
@lieut-data version v1.28 is correct on new installations (tested on PR server and 2 additional server created via cloud bot)
Few observations from the manual test:
on starter edition server 
- I am able to create a private playbook (per test I found in Zephyr I shouldn't be able to - I'm unsure if this is just new functionality for v7)
- Retrospective prompt is present 
- I was never presented with Start Trial (Is this also new for v7?)

**Comment by lieut-data** [comment]
Thanks, @jgilliam17! I believe those observations are all tied to our (slightly peculiar) behaviour of enabling enterprise features if certain developer modes are enabled (settings that would be unsafe in a real production environment). I think we have plans to either a) launch these test servers without those settings, or b) change our approach to overriding the enterprise license for community development. I think we can disregard these observations for now, as we'll be bug bashing on this tomorrow with various licenses.

**Comment by jgilliam17** [comment]
You're welcome! Here's the [e2e report](https://mattermost-cypress-report.s3.amazonaws.com/201483-a27d3fa-onprem-ent-server-pr-20341-mattermost/mm-ee-testa27d3fa/mochawesome.html) too, no PR related issues.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
