### PR TITLE
translations PR 20190520

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by wget** [comment]
LGTM even if this is basically just adding new untranslated strings.

**Comment by uhlhosting** [comment]
@wget any chance to add the existing translations of the new strings? I just completed it yesterday. Wish I would have a better notification when new translations are available.

**Comment by enahum** [comment]
@uhlhosting they should be included in the next automated PR

**Comment by uhlhosting** [comment]
@enahum Can you remind me how often PRs are made?

**Comment by enahum** [comment]
@uhlhosting every monday same time as this one

**Comment by wget** [comment]
> @wget any chance to add the existing translations of the new strings? I just completed it yesterday. Wish I would have a better notification when new translations are available.

Btw, I'm just a contributor like you, so I don't have power in this, I'm not a Mattermost employee :)

Like Elias just said, just wait for the next batch or for 5.12. 5.11 has already been released any way :)

**Comment by jasonblais** [comment]
@uhlhosting These strings go to v5.12, which isn't released until June 16th - so we'll have time to submit new PRs in coming weeks :)

**Comment by jasonblais** [comment]
@cpanato @enahum looks like the build for this PR is failing

**Comment by jespino** [comment]
@jasonblais Probably that can be solve merging the release-5.12 branch into the branch of the PR, I going to do that

**Comment by cpanato** [comment]
@jasonblais i just land in Berlin, give to me a few hours to arrive at home and i will look into it

**Comment by enahum** [comment]
a newer PR has been submitted

**Pull request closed without merging**
