### PR TITLE
Cherry-picking translations

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Cherry-picking translations from master
**This pr contains the monorepo translations for the webapp as well!**

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/22979

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Comment by amyblais** [comment]
There are some CI failures here.

**Comment by ctlaltdieliet** [comment]
Hi @amyblais ,
I'm afraid that I don't have access to EE/CircleCI test, so I can't check what went wrong

**Comment by amyblais** [comment]
@Willyfrog @m1lt0n Are you able to help take a look at the failing CI?

**Pull request merged**
