### PR TITLE
[MM-41115] Add server-side username colorize preference

### PR DESCRIPTION
**Pull request by 3ach**
#### Summary

This pull-request adds the server-side portion of the colorize-usernames preference. This preference, when set, will hash the user's username to a color in the client, allowing for quickly separating a message by its username. 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41115

#### Release Note

```release-note
* Added new ColorizeUsernames preferences on the server which can be configured in the API and UI. 
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
fixes https://github.com/mattermost/mattermost-webapp/pull/9684

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by Willyfrog** [comment]
gentle reminder @koox00 to review

**Review by koox00 — COMMENTED** [review]
LGTM, I just wonder, wouldn't it make sense to create the colors server side, instead of client side?

**Review by koox00 — APPROVED** [review]

**Comment by 3ach** [comment]
@koox00 - colors may change if the client changes the theme, to maintain contrast. To make this simpler (and avoid users x themes colors stored on the browser) the client will compute the color.

**Review by jgilliam17 — APPROVED** [review]
Thanks @3ach 
Tested, looks good to merge.
@Willyfrog Can you please review and approve one remaining workflow to unblock merge? Thanks 🙂

**Comment by jgilliam17** [comment]
@3ach Can you please fix few failing checks so we can merge? Thanks 🙂

**Comment by Willyfrog** [comment]
@3ach seems the code is not properly formatted, can you run gofmt on `import_functions.go` to unblock?

**Pull request merged**
