### PR TITLE
[MM-28520] Update bundled version of nps to 1.1.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Update bundled version of nps to 1.1.0

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28520

### CODE REVIEW

**Comment by hanzei** [comment]
cc @sbishel

**Comment by esethna** [comment]
@hanzei to confirm, these changes are in v1.1? https://github.com/mattermost/mattermost-plugin-nps/pull/75
https://github.com/mattermost/mattermost-plugin-nps/pull/62

**Review by esethna — APPROVED** [review]

**Comment by hanzei** [comment]
@esethna Yes, they are

**Review by larkox — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by amyblais** [comment]
@DHaussermann Kind reminder to review this for v5.28.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- NPS `v1.1.0` is installed on fresh install
- Plugin is enabled on fresh install
- Marketplace show plugin as enabled

**Pull request merged**
