### PR TITLE
MM-38982: fixes SVG uploading

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Uploading SVG files was "almost" treated like an image in some places,
resulting in not showing the SVG on the client.
This is happening because when we fail to generate a mini preview for an
image, we prepend "invalid-" to the MimeType.

This commit adds a check to guard against SVG files in methods that make
no sense for SVGs.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-38982

#### Release Note

```release-note
Fixes uploading SVG files
```

### CODE REVIEW

**Comment by streamer45** [comment]
Thanks @koox00, I am thinking the core issue here is that we are messing with the mime-type which we shouldn't. 

@cpoile  I assume that was a temporary solution and that we figured out the problem eventually so does it still make sense to keep that logic?

**Comment by koox00** [comment]
> Thanks @koox00, I am thinking the core issue here is that we are messing with the mime-type which we shouldn't.

That's true, but also some methods are too specific for images, that assume a `thumb` file and a `preview` one, which don't exist for SVGs

**Comment by koox00** [comment]
>  @koox00 Am I right in assuming that even if we removed the invalid- mime prefix we would still need these changes?

@cpoile not that the app is going to crash without the changes, but IMO, yes either way these changes would be good to have

**Comment by agnivade** [comment]
Yeah, the original OOM issue was due to passing the image preview as part of *model.Post to all plugins. Therefore, serializing the huge byte slice caused a large allocation. Then there was another unrelated issue caused by a model API change, but that didn't cause any memory problem.

We can revert this one if it does not make sense any more.

**Comment by koox00** [comment]
@agnivade, @cpoile what do you propose to do, 
so should I close this PR, 
revert this one https://github.com/mattermost/mattermost-server/pull/18445,
or just re-assign the ticket?

**Comment by agnivade** [comment]
I'll defer to Claudio/CPoile on this.

**Comment by streamer45** [comment]
@koox00 I think we can remove the "invalid" mime type fix on top of this PR and proceed.

**Comment by koox00** [comment]
> @koox00 I think we can remove the "invalid" mime type fix on top of this PR and proceed.

@streamer45 done

**Review by cpoile — APPROVED** [review]
Thanks @koox00 !

**Review by streamer45 — APPROVED** [review]
There are a couple more places where we check against `image/svg+xml`. I'd suggest using the nice util you added here. Other than that, it looks great, thanks :+1:

**Comment by jgilliam17** [comment]
@koox00 Sometimes when I add a single .svg file it is not shown, but if the file is part of multi-attachment post it is shown. 
On the image, the window svg was posted twice (see red lines) and it failed to be shown, but preview is there when it is posted later in a multi-attachment post 
Screen Shot 2022-05-16 at 6 02 08 PM

**Comment by koox00** [comment]
> @koox00 Sometimes when I add a single .svg file it is not shown, but if the file is part of multi-attachment post it is shown.
On the image, the window svg was posted twice (see red lines) and it failed to be shown, but preview is there when it is posted later in a multi-attachment post

The previews are shown now though, right? I assume it's this (the timestamp matches):

Screenshot 2022-05-17 at 11 52 10 AM

**Comment by jgilliam17** [comment]
@koox00 I still don't see the single svg posts on Chrome and Safari. They are visible on FirefoxScreen Shot 2022-05-17 at 8 47 54 AM

**Comment by koox00** [comment]
@jgilliam17 OK the issue for not showing are CSS rules, (which this PR doesn't change).
I'll raise a webapp PR as well.

**Comment by jgilliam17** [comment]
@koox00 do we have to wait for webapp PR before merging this one?

**Comment by jgilliam17** [comment]
Just waiting for E2Es to finish, will merge after report posts and if everything looks good.

**Comment by koox00** [comment]
> @koox00 do we have to wait for webapp PR before merging this one?

@jgilliam17 I've added this ticket for webapp https://mattermost.atlassian.net/browse/MM-44470

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
