### PR TITLE
[MM-50516] Support multiple embed

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
Currently, we only support one. This way, we could make sure multiple works as well.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50516

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Review by jupenur — APPROVED** [review]
LGTM. Thanks @kostaspt!

**Comment by amyblais** [comment]
@kostaspt Please help open manual cherry-pick PRs for ``cloud``, ``release-7.8``, ``release-7.7`` and ``release-7.1`` branches.

**Pull request merged**
