### PR TITLE
MM-46947 - Fix: Manifest parsing won't allow placeholders for custom pluginSettingType

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Allow custom setting types to specify a placeholder

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-46947

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by cpoile** [comment]
@lieut-data I can't think of a reason it was omitted.  That check was added only a couple weeks after the Custom type was added... Maybe it was just missed? Or maybe no-one thought that a custom type would make use of the placeholder field.

**Comment by streamer45** [comment]
Yeah, a placeholder really makes sense for basic types and for custom we have control over everything so a placeholder functionality can be always achieved through other means if needed.

**Comment by cpoile** [comment]
I still think it would be useful though... There doesn't seem to be a reason not to have it, so may as well?

**Comment by streamer45** [comment]
> I still think it would be useful though... There doesn't seem to be a reason not to have it, so may as well?

Totally :+1:

**Review by streamer45 — APPROVED** [review]

**Comment by streamer45** [comment]
@cpoile Could you just add a test case to `TestSettingIsValid` so that it doesn't easily revert?

**Pull request merged**
