### PR TITLE
MM-25404: Add GetHealthScore metric for the cluster

### PR DESCRIPTION
**Pull request by agnivade**
This PR adds the necessary function to the cluster interface
so that they can be called from App code.

#### Ticket link

https://mattermost.atlassian.net/browse/MM-25404

### CODE REVIEW

**Comment by agnivade** [comment]
Gentle ping @srkgupta

**Comment by agnivade** [comment]
@srkgupta - Should be fixed now.

**Comment by srkgupta** [comment]
@agnivade I am still seeing errors in the build lint process. Can you please recheck.

**Comment by agnivade** [comment]
@srkgupta - Please ignore that.

That's due to the lag between server and EE branches. When you update one, either one has to fail. I just restarted the build. The failure points to an old code which isn't actually there in the PR.

**Comment by srkgupta** [comment]
@agnivade I am not sure if HA cloud instance will be created if any of the build process fails. I have initiated the request, let's see.

**Comment by agnivade** [comment]
Indeed, this is a CI issue where re-triggering the build does not get the latest from the EE branch.

**Comment by agnivade** [comment]
@srkgupta - All good now. Sorry for the troubles.

**Pull request merged**
