### PR TITLE
Migrate tests from model/search_params_test.go to use testify

### PR DESCRIPTION
**Pull request by lurcio**
#### Summary
Migrate tests from "model/search_params_test.go" to use testify

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12572

### CODE REVIEW

**Comment by stevemudie** [comment]
LGTM

**Comment by sudheerDev** [comment]
@lurcio Can you merge master into this branch so i can go ahead and merge this?

**Comment by lurcio** [comment]
@sudheerDev done, but confused where the additional changes have appeared from.

**Comment by sudheerDev** [comment]
@lurcio Aah, Ya i see i don't know what went wrong here. Can you revert the other PR's so we have your required changes alone in the PR?

If you are not sure here is a crude way of doing it.

1. Create a temp branch just in case from this branch here. `git checkout -b temp/anything`
2. checkout to master
3. update master
3. delete branch `GH-12572`
4.  create a new branch `GH-12572`
5.  cherrypick your commit `a1ef1806715ac8b1c7316979d62370de0a6f8b34`
6.  git force push

**Comment by lurcio** [comment]
@sudheerDev Thank you for the help. I think it's OK now.

**Comment by jespino** [comment]
Merged! Thanks @lurcio! :dancing_men:

**Pull request merged**
