### PR TITLE
Pre-package Playbooks v1.29.3 to v7.1

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package Playbooks v1.29.3 to v7.1

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-47981
Fixes: https://mattermost.atlassian.net/browse/MM-48007
Fixes: https://mattermost.atlassian.net/browse/MM-48008

#### Release Note
```release-note
Pre-package Playbooks v1.29.3
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Review by trilopin — APPROVED** [review]

**Comment by lieut-data** [comment]
@amyblais, are there any other ESR patches with which to coordinate a v7.1 update?

**Comment by amyblais** [comment]
There are some security and bug fixes that we're ready to backport. Please add reviewers as needed.

**Comment by lieut-data** [comment]
Thank you, @saturninoabril!

**Pull request merged**
