### PR TITLE
Ability to make "message" and "reply" interactive buttons

### PR DESCRIPTION
**Pull request by bezumkin**
#### Summary
This PR extends interactive buttons functionality by adding 2 new types of [interactive messages](https://docs.mattermost.com/developer/interactive-messages.html): `reply` and `message`. If you click on this buttons - you will create a new message in current dialog.

It is needed for better experience when you have chat with a bot.

####
[Watch demo](https://file.modx.pro/files/c/e/7/ce74370d8e67f7a7f4cf19642fedf63b.mp4)

I'm [using this python bot](https://github.com/attzonko/mmpy_bot), here is the code of the demo
```python
channel_id = message['post']['channel_id']
if message['post']['message'] == 'Regular message':
    self._client.api.create_post(user_id=None, channel_id=channel_id, message='Thank you!')
elif message['post']['message'] == 'It is reply':
    self._client.api.create_post(user_id=None, channel_id=channel_id, message='Nice reply!',
                                 pid=message['post']['id'])
else:
    self._client.api.create_post(user_id=None, channel_id=channel_id, message='', props={
        'attachments': [{
            'fallback': 'Hello!',
            'text': 'Please, select your action',
            'color': '#59afe1',
            'actions': [{
                'name': 'Answer as regular message',
                'type': 'message',
                'integration': {
                    'context': {
                        'action': 'Regular message',
                    }
                },
            }, {
                'name': 'Answer as reply to thread',
                'type': 'reply',
                'integration': {
                    'context': {
                        'action': 'It is reply',
                    }
                }
            }]
        }]
    })
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by levb** [comment]
Hello @bezumkin and thank you for the PR. I see how adding these 2 new action types with built-in handling behavior saves bot coders time from implementing posting the messages inside the plugin, and avoids the need to implement the http "integration" interface. 

I would have a slight personal preference (1/5) that we didn't create a new action `Type` for this, it is essentially still a _Button_, just with pre-defined semantics (like, say often times the Cancel button).  My preference would be to trigger these pre-defined, built-in click handlers with other metadata in `model.PostAction` and keep the `Type` focused on presentation. An example of what I mean: to display a channel or a user `select` we do not have special `select_user` or `select_channel` types, but instead use the `data_source` attribute value with the type "select`.

I will let others chime in on this. One change I'd request if we add the new action types, is to explicitly list them in https://github.com/mattermost/mattermost-webapp/blob/master/components/post_view/message_attachments/message_attachment/message_attachment.jsx#L97, and maybe add a godoc comment athttps://github.com/mattermost/mattermost-server/blob/master/model/integration_action.go#L33

**Comment by hanzei** [comment]
I agree with @levb. Adding a new `Type` for this seams to much for me. As already stated "message" and "reply" are just buttons and therefore similar to "button". 2/5

**Comment by jasonblais** [comment]
Hi @levb, do you have a proposal we can offer to @bezumkin on how to proceed?

**Comment by bezumkin** [comment]
Sorry for this mess.

I will create an another PR.

**Pull request closed without merging**
