### PR TITLE
[MM-28371] store/channel_store_categories: fix index out of bounds 

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
In such cases we got an empty `[]sidebarCategoryForJoin`. This was causing a panic.  Better to return 404.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28371

### CODE REVIEW

**Comment by hmhealey** [comment]
Do we know what was causing this specific case? Is something calling the API with an invalid ID?

**Review by hmhealey — APPROVED** [review]

**Review by mgdelacroix — APPROVED** [review]

**Comment by isacikgoz** [comment]
@hmhealey the report doesn't have such context but my guess is they didn't run the migration earlier? All I can do is guessing according to the query.

**Comment by hmhealey** [comment]
`GetSidebarCategory` requires an ID when it's called, so I'd assume migration would've been ran by that point for have an ID to pass in the first place.

We don't actually use the corresponding API for that from the client, so something on the server would be calling it. Outside of the respective API call, it's used when checking permission to a category or when updating a category. Perhaps it's a database replication issue of some sort in one of those places. I'm not aware of what the side effect of that would be though.

**Review by lindalumitchell — APPROVED** [review]

**Comment by isacikgoz** [comment]
@hmhealey yes, you're right. It is caused when updating a category. Having said that, this should be a DB issue since it already passed the permission check which has the same call with the update method. If it'd be something with the `Id` or whatsoever it should also panic in the permission check step.

**Pull request merged**
