### PR TITLE
MM-22678 Use more user-friendly errors for channel commands

### PR DESCRIPTION
**Pull request by hmhealey**
The old "Error to update the current channel." error was both gramatically incorrect and didn't actually tell the user what went wrong. This should hopefully improve both of those.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22678

#### Release Note
```release-note
Improved error messages for /header and /purpose commands.
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by jgilliam17 — CHANGES_REQUESTED** [review]
Thanks @hmhealey 
Seeing few items we should change
- Suggested a text change based on Andrew's design note from the linked ticket. 
- Can you also add this suggested error message to Channel Header modal? Hopefully it wraps well on the modal, it is slightly longer than the existing error text. Thanks.
Screen Shot 2021-04-27 at 3 57 04 PM

**Comment by hmhealey** [comment]
@jgilliam17 I've updated the text like you suggested. The error text in the modal will need its own PR since it comes from the webapp.

**Review by jgilliam17 — APPROVED** [review]
Thanks @hmhealey 
Tested, looks good to merge.
- Verified text length errors for header and purpose slash commands.
- Channel Header modal error text will be updated in a separate PR.

**Pull request merged**
