### PR TITLE
MM-45039 create mctx package

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
This PR creates a context package that can be used throughout the server. The context can be created from the `web.Context` and passed to most packages without creating dependency loops.

I tried a few other approaches before settling on the most simple one.
- An approach similar to (or even extending) Go's `context` package would work but introduce unnecessary overhead (since we are not passing the context to external packages).
- Moving the `web.Context` in it's own package and abstracting access to it's contents via interfaces would entail a massive refactoring of the `app` package (and a few more).
- Just passing on the logger (which was the original goal) wastes the opportunity to introduce context to each request throughout the server and makes future extensions difficult. Adding a parameter to a great portion of methods should be a rare occurrence.

To use the new context, you need to create it from the `web.Context` (or it's alias `app.Context`) by calling `ctx.MContext()`. It can be passed on to the `app` and `store` packages. I'd suggest to split the introduction into further, small PRs, since it will most likely interfere with other PRs currently in the making. A few other parameters may be dropped when passing the new context. Any parameter using `request.Context` or it's contents may be replaced. Sometimes, especially with sessions, it may be useful to not replace parameters, even if they may be retrieved from the context, since it obscures where the session info comes from (and there may be use cases for passing sessions other than the user's).
Also be aware that even changes to just a few methods may cascade into huge refactorings. To prevent this, consider not passing the context on to all other methods but to limit the changes to the package you are currently working on.

#### Ticket Link
[MM-45039](https://mattermost.atlassian.net/browse/MM-45039)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
Would it be possible to access contexts from the `context.Context`? Rather than adding a new package maybe? We can use `context.WithValue` and add a utility function to access any type of context form the values to access safely.

**Comment by noxer** [comment]
We'd probably need a new package for those utility functions as well. That approach was actually my starting point but did not have the simplicity I hoped for. The downsides are that it obscured the passing of the logger and it's not as performant as passing a pointer to the `mlog` struct. In my opinion it also mixes the pure passing of request related context with dependency injection. There is controversy about that approach. That said, I'm not strictly opposed to the idea of using `context.Context` either. It would allow us to propagate cancellations from the request all the way to the database, maybe even allowing us to implement rollbacks when later steps in the processing fail, are cancelled or time out.

**Comment by agnivade** [comment]
I agree that adding the logger to `context.WithValue` is not idiomatic. It's okay to use that as a pointer to the struct.

Some further questions from my side:
- It looks like we are adding the request.Context, along with the logger and appErr. Could we not expand the request.Context itself with those 2 fields? Unless there would be a cyclic dependency to import request.Context from the store packages?

Overall, it seems a bit confusing to have 3 separate context packages. It gives the impression that something is not properly designed.

> The context can be created from the web.Context and passed to most packages without creating dependency loops.

Can we not create an interface on the consumer side along with methods that return the specific things that we need? e.g. - logger, request.Context, err etc. That would circumvent the need to import any package.

```go
type ctxInterface interface {
  AppContext() *request.Context
  Logger()     *mlog.Logger
}
```

And then do, `ctx.Logger().Info("...")`.

**Comment by noxer** [comment]
I agree that it's a bit confusing. I put it in a separate package to make it clear that it's intended as context for the whole server. If we had a cyclic dependency, we couldn't import it in `mctx` anyway. Just using the interface would be feasible but comes with the same performance downsides as all interfaces.
My original idea included having a structure similar to `context.Context` (with wrapping new instances around old ones). I haven't completely given up on it, since it could provide the rollback functionality mentioned earlier. For that we'd need interfaces as well, though.

**Comment by agnivade** [comment]
> Just using the interface would be feasible but comes with the same performance downsides as all interfaces.

Performance overhead with interfaces is not a bottleneck for us. Our main bottleneck remains database queries.

> My original idea included having a structure similar to context.Context (with wrapping new instances around old ones). I haven't completely given up on it, since it could provide the rollback functionality mentioned earlier. 

Ok, you can look into it. But note that rollback/cancellation functionality isn't our main priority right now. It would be good to have, but a lot of work to ensure everything works correctly.

My main objective is to avoid another package. Interfaces are perfectly fine to use. I'll leave the rest to you :)

**Comment by agnivade** [comment]
I was thinking some more on this and found a better solution - which can possibly lead us towards using `context.Context`.

We have 2 main problems to solve:
1. Move away from global logger to a local logger.
2. Add request context to the logger.

This means we actually don't need to pass around the logger instance via contexts. We can let the logger be attached to the store struct while creation. And in the app layer, we have direct access to the *Server struct, so no additional field is required.

What only remains is to pass the `requestID` via contexts from api -> app -> store. And while logging, we just need to add the `requestID` to every line. Something like `app.Srv().Logger.WithRequestID(requestID).Info("...")`.

And `requestID` is a simple string that can be passed easily via `context.WithValue`.

Although I see the `.Err` field so we might need a struct eventually, but passing the logger in the context isn't necessary any more.

**Comment by agnivade** [comment]
Understood, let's do that :)

**Review by agnivade — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
LGTM 🚀

**Pull request merged**
