### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-server_master/) for mattermost-languages-shipped/mattermost-server.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by amyblais** [comment]
@mgdelacroix This could still make it to v5.34.

**Comment by cpanato** [comment]
@amyblais i will cherry pick after we merge this

**Comment by cpanato** [comment]
cherry pick done in https://github.com/mattermost/mattermost-server/pull/17382

**Pull request merged**
