### PR TITLE
[MM-51805  + MM-51806 + MM-51041] Work template: multiple UI fixes

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary

Preview step:
- changing the margin between the top of the modal and the content
- remove the "download" icon and add "status text" for each case
- other: fix showing plugin status

Customize Step:
- Fix border of the input

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51805
https://mattermost.atlassian.net/browse/MM-51806
https://mattermost.atlassian.net/browse/MM-51041

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
LGTM! thanks @JulienTant

**Comment by pvev** [comment]
I noticed two things:
- that the playbooks image is missing
Screenshot 2023-04-06 at 09 22 02

- the integrations doesn't show in the spinwick server so to verify your change I pull it locally and it works fine:

Screenshot 2023-04-06 at 09 30 30

**Review by julmondragon — APPROVED** [review]
LGTM @JulienTant !

**Comment by annelieseklein** [comment]
https://user-images.githubusercontent.com/29821919/231304666-0257494e-61d2-475a-8ce8-ea5d6ad3a44f.mov

there seems to be some movement of the "Boards" text and number when it is selected versus not

**Review by stevemudie — APPROVED** [review]
It looks like I'll need to test this post merge due to not being able to access plugins.

**Review by pvev — APPROVED** [review]
LGTM! thanks @JulienTant :shipit:

**Comment by JulienTant** [comment]
@annelieseklein did you want to take a new look at this? Or can "report" other eventual fixes to a later date?

**Review by annelieseklein — APPROVED** [review]
lgtm!!

**Pull request merged**
