### PR TITLE
Add retry logic to initialize CodeQL

### PR DESCRIPTION
**Pull request by agnivade**
```release-note
NONE
```

### CODE REVIEW

**Comment by srkgupta** [comment]
Hi @agnivade 

I earlier tried with the Retry Action but it was failing as seen here. 

The issue with Github Actions failing which we had earlier encountered would not be resolved with the retry actions because as shown here in the failing the job, the Github action already has an internal retry logic:

https://github.com/mattermost/mattermost-server/runs/5481605618?check_suite_focus=true

```
    request: {
      agent: [Agent],
      hook: [Function: bound bound register],
      retryCount: 3,
      retries: 3,
      retryAfter: 16
    }
```

If you check the logs, the issue happened because the Action made a GET request to `https://api.github.com/repos/mattermost/mattermost-server/actions/runs/1957816678` API endpoint which responded back with a 502 Server Error. 

Also, as mentioned in the Github CodeQL action's troubleshooting [documentation here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#error-server-error), the only suggested approach is to contact their Support Team. 

```
If the run of a workflow for code scanning fails due to a server error, try running the workflow again. If the problem persists, contact [GitHub Support](https://support.github.com/contact?tags=docs-generic).
```

So the suggested approach would be to enable debug mode as done here and then try to contact the Github Support Team, if we are seeing the issues again. 
https://github.com/srkgupta/mattermost-server/blob/master/.github/workflows/codeql-analysis.yml#L29

Also please note that Github Actions was experiencing disruptions during that period as highlighted here:
https://www.githubstatus.com/incidents/cypv026dr23w

So considering all of these points, I would recommend to only enable the debug mode as of now and then relook at this if it is failing again.

**Comment by agnivade** [comment]
Interesting, I missed that it has an internal retry logic. Agree, let's enable debug mode and see.

**Comment by agnivade** [comment]
@srkgupta - PTAL

**Review by srkgupta — APPROVED** [review]
Thanks @agnivade. LGTM

**Pull request merged**
