### PR TITLE
[MM-50996] Set WorkTemplate FF to true by default

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Change work template feature flag value to true.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50996

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks @JulienTant!

**Review by julmondragon — APPROVED** [review]

**Comment by JulienTant** [comment]
trying to figure why CI is breaking 😅

**Comment by marianunez** [comment]
> trying to figure why CI is breaking 😅

Added that tag that kicks off enterprise tests in the pipeline. Hopefully that fixes it

**Comment by JulienTant** [comment]
it seems many PR face this issue

**Comment by amyblais** [comment]
@JulienTant Please help open a cherry-pick PR for ``release-7.9`` branch.

**Pull request merged**
