### PR TITLE
[MM-51466] Fixing monorepo websockets for boards

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Fixing websockets

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51466

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
Nice!

**Review by sbishel — APPROVED** [review]

**Comment by sbishel** [comment]
LGTM

**Comment by BenCookie95** [comment]
@sbishel What's the process for merging into mono-repo? Is there QA or can I just merge this?

**Comment by sbishel** [comment]
I wouldn't worry about QA at least for something like this. A bug fix to get mono-repo running. Which everything really should be going into mono-repo. 

@wiggin77 - I'm not sure about which tests are expected to pass.

**Comment by wiggin77** [comment]
Yes, we're still working on those unit tests.  It's ok to merge this.

**Pull request merged**
