### PR TITLE
[MM-46440]: Update Logo and Remove grey email border

### PR DESCRIPTION
**Pull request by emmyni**
#### Summary
Removed the grey border in the "reset password" and "cloud welcome" emails
Changed the blue/grey Mattermost logo to the black Mattermost logo on the "cloud welcome" and "password reset" emails

Other related PRs: 
https://github.com/mattermost/customer-web-server/pull/939/files
https://github.com/mattermost/mattermost-plugin-nps/pull/92

#### Screenshots
image

Note: Some of the issues reported in the MM-46440 couldn't be replicated on local (mainly the grey borders), but they were happening on the actual test portal (gmail). So I inspected the emails from the test portal and tried to modify the code based on those properties.

#### Ticket Link

[MM-46440](https://mattermost.atlassian.net/browse/MM-46440)
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by AGMETEOR** [comment]
@emmyni might be better to make the changes in the corresponding `.mjml` files and thereafter generate the templates with `make`

**Comment by emmyni** [comment]
> @emmyni might be better to make the changes in the corresponding `.mjml` files and thereafter generate the templates with `make`

@AGMETEOR I tried to do what you suggested by only making changes to the `.mjml` file, however i couldn't override the `!important` in the `emailBody` css class. So I ended up removing the !important from the `emailBody` class in `styles.css` and adding an inline style to `reset_body.mjml` to override the background colour for that email only. This allowed the "reset password email" to get its grey border removed while the other emails remained the same. 

Additionally, the `.mjml` file did not allow the `background` property (which was previously used in the `styles.css` file), so I had to set the inline colour using `background-color`. Then, when the `make build-templates` command executed, it kept putting the `background` property after the ` background-color` property so it was overriding my inline colour changes. As a result, I ended up changing the property “background” to “background-colour” in the `styles.css` file. 

The functionality of the other emails shouldn’t be changed but in the “files changed”, on Github there are some minor code differences.

**Comment by emmyni** [comment]
> @emmyni The password change email looks good but I'm still seeing the grey border on the welcome email? 🤔
> 
> Just so I know I'm looking at the correct one, it's the "You joined [server URL]" / "Welcome to the team" one right?
> 
> Screenshot 2022-10-12 at 12 09 27 PM

Thanks @stevemudie, yeah when I ran the make command, it seems  that`welcome_body.html` got overridden. I'll fix that, thanks.

**Review by stevemudie — APPROVED** [review]
Looks good @emmyni!

**Review by annelieseklein — APPROVED** [review]

**Review by AGMETEOR — APPROVED** [review]

**Pull request merged**
