### PR TITLE
[MM-41330] Fix JSON type check in `hasMissingMigrationsVersion600`

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

MySQL returned type for JSON would be lowercase but we checked against an uppercase string, hence failing the check and re-triggering the migration every time.

/cc @neillcollie @isacikgoz 

@amyblais This goes directly into 6.3 release and will need to be included in a dot release. From what I can see bug also affects 6.0.x,6.1.x,6.2.x releases.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-41330

#### Release Note

```release-note
Fixed an issue that on MySQL installations would re-trigger 6.0 migration on server restart.
```

### CODE REVIEW

**Comment by neillcollie** [comment]
Thanks Claudio. Will this affect the 5.37.x branch as well perhaps? I have another customer reporting similar issue

**Comment by streamer45** [comment]
> Thanks Claudio. Will this affect the 5.37.x branch as well perhaps? I have another customer reporting similar issue

This specific issue is 6.0 onward only as the affected migration was introduced in 6.0 .

**Review by agnivade — APPROVED** [review]
Sorry, I somehow thought that I had approved this.

**Comment by amyblais** [comment]
@streamer45 Do you recommend also cherry-picking this to 6.2 / 6.1? (I'm ok with it).

**Comment by streamer45** [comment]
> @streamer45 Do you recommend also cherry-picking this to 6.2 / 6.1? (I'm ok with it).

@amyblais That should be done already.

**Pull request merged**
