### PR TITLE
used squirrel to write query

### PR DESCRIPTION
**Pull request by prakharporwal**
#### Summary
Migrated SqlChannelStore.GetMembersByIds/GetMembersByChannelIds to write sql query using squirrel 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/19336

<!--
Add a release note for each of the following conditions:

* Config changes (additions, deletions, updates)
* API additions—new endpoint, new response fields, or newly accepted request parameters
* Database changes (any)
* Websocket additions or changes
* Anything noteworthy to a Mattermost instance administrator (err on the side of over-communicating)
* New features and improvements, including behavioural changes, UI changes and CLI changes
* Bug fixes and fixes of previous known issues
* Deprecation warnings, breaking changes, or compatibility notes

If no release notes are required write NONE. Use past-tense. Newlines are stripped.

Examples:

```
Added new API endpoints POST /api/v4/foo, GET api/v4/foo, and GET api/v4/foo/:foo_id.
```

```
Added a new config setting ServiceSettings.FooBar. Added a new column Foo to the Users table.
```

```release-note
Using Squirrel to create Sql Query 
```

### CODE REVIEW

**Comment by agnivade** [comment]
@prakharporwal - This PR needs some more work. Please take a look at how some of the other queries are written in that file.

The final objective is to replace the GetReplica/GetMaster calls with GetReplicaX/GetMasterX. Let's add some newlines to the query object to make it more readable.

**Comment by isacikgoz** [comment]
Hey @prakharporwal let us know if you need additional guidance :)

**Comment by prakharporwal** [comment]
@isacikgoz Hey Yes . I don't understand first why you want to move it and build the query using squirrel. Also I read the squirrel doc and create the above changes . I am not able to figure out what is going wrong.

**Comment by agnivade** [comment]
No worries @prakharporwal. :) Would you mind if someone else takes up on this task?

**Comment by prakharporwal** [comment]
Yeah . I know I have taken too long to complete this issue . But can you answer the first part . Why this squirrel?

**Comment by agnivade** [comment]
Sure, we are moving away from using gorp as our ORM layer due to various reasons (unmaintained, buggy) to raw SQL queries constructed via Squirrel for complicated cases.

**Pull request closed without merging**
