### PR TITLE
Pre-package Playbooks v1.32.7 to v7.5

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package Playbooks v1.32.7 to v7.5

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-47981
Fixes: https://mattermost.atlassian.net/browse/MM-48007
Fixes: https://mattermost.atlassian.net/browse/MM-48008

#### Release Note
```release-note
Pre-package Playbooks v1.32.7
```

### CODE REVIEW

**Comment by amyblais** [comment]
@lieut-data There are some security and bug fixes that we're ready to backport. Please add reviewers as needed.

**Review by saturninoabril — APPROVED** [review]
Tested and looks good to me. Thanks Jesse!

**Pull request merged**
