### PR TITLE
[MM-51302] Fix scroll to the bottom of editor after pasting long text

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
When the editor is in focus, CRT should be scrolled there.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51302

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Comment by furqanmlk** [comment]
@koox00 Everything looks fine. For the new test case, I will have to create a test case in `test-managment-repo`.  In order to get the test id, I will provide you the test id.

**Comment by furqanmlk** [comment]
@kostaspt 
Can you please update the test case with id `MM-T5413`
https://github.com/mattermost/mattermost-server/pull/22491/files#diff-60aad280600bf661040526cc52ecc3ca1d1cf9cae6811c5825a12e8d98e75dbeR180

**Comment by kostaspt** [comment]
@furqanmlk Done

**Review by furqanmlk — APPROVED** [review]

**Comment by amyblais** [comment]
@kostaspt Please open a manual cherry-pick PR for ``release-7.10`` branch.

**Comment by amyblais** [comment]
@kostaspt I realized that this would also be good to cherry-pick to the ``cloud`` branch.

**Pull request merged**
