### PR TITLE
MM-20223 Add webp emoji support 

### LINKED ISSUE #20223: Add support for WebP Emojis
See: https://github.com/mattermost/mattermost-server/issues/20116

##### Summary

We previously added unintentional support for uploading WebP images as custom emojis, but this was broken when some dependencies on the server changed. We should add proper support for this including whatever changes are required on the server to support webp and updating the help text for custom emojis to note that this is an option.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-43949

### PR DESCRIPTION
**Pull request by aavsss**
#### Summary
This pr updates the version of golang.org/x/image to support 'webp' images fully. Please note that the library still doesn't have encoding support, but the tests were already in place.  

#### Ticket Link
Fixes #20223 

#### Release Note
<!--
Add a release note for each of the following conditions:

```
Added support for webp image types for emojis and image file uploads.
```

### CODE REVIEW

**Comment by agnivade** [comment]
@aavsss - Have you tested this PR yourself? Perhaps, I am missing it, but can you point me to the place where the webp decoder is registered? 

Also, this PR needs tests. Please take a look at https://github.com/mattermost/mattermost-server/pull/20283.

**Comment by agnivade** [comment]
Hi @aavsss - Just checking to see if you are still interested in working on this PR?

**Comment by aavsss** [comment]
Hi @agnivade, sorry I could not work on it last week. I did test it locally and was able to upload and view webp images. According to [this](https://pkg.go.dev/golang.org/x/image/webp) documentation, I only needed to import this library and the webp decoder is registered by itself. 

Could you tell me more about what kind of tests to write? Because according to #20283, tests to check against webp images have already been implemented.

**Comment by agnivade** [comment]
You are right about the tests. They were already added. I got confused with another PR which was reverted, so I thought we'll need to add the tests back. Specifically, we reverted this [PR](https://github.com/mattermost/mattermost-webapp/pull/10668), we'll need to re-revert it.

Regarding your specific change, you have just bumped the dependency with one commit, which is https://github.com/golang/image/commit/41969df76e82aeec85fa3821b1e24955ea993001 which updates the font versions. So I am not sure what exactly does that change. The webp decoder already exists in the current version of the dependency.

Have you tested and found that you were _not_ able to upload webp emojis in the current version, and only after updating the dependency you were able to upload?

**Comment by agnivade** [comment]
Also, from what I understand from @Willyfrog, the client side code needs to be changed to allow users to select webp images. Guillermo, you mentioned that the emoji picker in the system console was affected:

> In the system console, go to add a new custom emoji and the file browser won’t allow selecting webp files

But the emoji picker exists in the emoji react section now. Can you clarify this?

**Comment by aavsss** [comment]
I am not sure if it works on the current version. I will test it out and let you know. 
From the client side, I believe that we have to allow the file picker to accept webp file formats. Currently, it only accepts jpeg, png, and gif.

**Comment by aavsss** [comment]
You are right. The current version of the server already supports webp images. Could you please specify which PR to revert in the web app? Or should I create a new PR that allows the web app to upload webp images?

**Comment by agnivade** [comment]
We need to re-revert this PR: https://github.com/mattermost/mattermost-webapp/pull/10668. We reverted that because the webp functionality was broken.

@Willyfrog - can you please help with the test steps to verify what you were seeing?

**Comment by agnivade** [comment]
Let's close this PR then and continue the conversation in your new PR.

**Comment by aavsss** [comment]
Got it. Will do

**Comment by Willyfrog** [comment]
> But the emoji picker exists in the emoji react section now. Can you clarify this?

yes, I meant this:
CleanShot 2022-08-12 at 12 39 30@2x

> can you please help with the test steps to verify what you were seeing?

Sure! are the changes merged? or do i need to setup a server/web with several PRs?

Sorry it took so long to respond, but I'm not fully available until next week

**Comment by agnivade** [comment]
There is no server change needed for this as webp decode support is already there. We just need to unblock the file-picker dialog to accept .webp images. 

@aavsss - can you add support for .webp images in the custom emoji picker, and see if you are able to upload webp images? Thanks.

**Pull request closed without merging**
