### PR TITLE
[MM-35501] Remove Determining Ancillary Permissions from Frontend to Backend

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Currently, we are determining the ancillary permissions required on the front-end. This should be done on the backend.
This will allow us to eliminate having to keep a copy of ancillary permissions on the front-end.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-33501

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by mkraft — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Please see QA comments for details 
https://github.com/mattermost/mattermost-webapp/pull/7628

**Pull request merged**
