### PR TITLE
MM 17466 : Add custom post types to compliance exports

### PR DESCRIPTION
**Pull request by catalintomai**
#### Summary
This is an upstream version/clone of https://github.com/mattermost/mattermost-server/pull/11781 , created in order to solve cross-dependencies between enterprise and server repos.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-17466

### CODE REVIEW

**Comment by amyblais** [comment]
@catalintomai FYI that this should be cherry-picked or otherwise it's not included in v5.18.

**Comment by catalintomai** [comment]
> @catalintomai FYI that this should be cherry-picked or otherwise it's not included in v5.18.

Thanks. I see you CherryPick/Approved it earlier, is there some further action to take on it?

**Comment by amyblais** [comment]
@catalintomai You will need to cherry-pick it to v5.18 and then change the label to CherryPick/Done

**Comment by catalintomai** [comment]
FYI - I just CherryPick/Approved https://github.com/mattermost/enterprise/pull/525 - the PR complementing this one, for some reason the label color is different.

**Comment by amyblais** [comment]
@catalintomai I'm not sure about the colour, but if you have any issues with the cherry-picking you can probably ask any devs on your team to help out.

**Comment by cpanato** [comment]
i add the label after the merge it will not run the automated cherry pick, however you can run the slash command `/cherry-pick release-x.yy`

**Comment by catalintomai** [comment]
> i add the label after the merge it will not run the automated cherry pick, however you can run the slash command `/cherry-pick release-x.yy`

Thanks Carlos, I was wondering about how to do exactly that.

**Comment by cpanato** [comment]
ok looks like there are some conflicts @catalintomai  you need to do manually

**Comment by catalintomai** [comment]
> ok looks like there are some conflicts @catalintomai you need to do manually

Thanks, do you happen to have a standard sequence of git commands for that (equivalent of above)? The MM documentation only describes that a cherry pick has to happen but no details (see https://developers.mattermost.com/contribute/getting-started/branching/ step 5) .

**Comment by cpanato** [comment]
@catalintomai it is a normal cherry pick 
Git checkout release-5.18
Git pull upsteram release 5-18
Git checkout -b newbracnh for cherry pick
Git cherry-pick sha of your pr
Git push
Open a pr

**Comment by catalintomai** [comment]
> @catalintomai it is a normal cherry pick
> Git checkout release-5.18
> Git pull upsteram release 5-18
> Git checkout -b newbracnh for cherry pick
> Git cherry-pick sha of your pr
> Git push
> Open a pr

Thanks, will follow that. So the "git cherry-pick" runs on the newbranch (hence the PR), not on the release one (the actual pr move from master happens only after the merge of the final pr).

**Comment by catalintomai** [comment]
> > @catalintomai it is a normal cherry pick
> > Git checkout release-5.18
> > Git pull upsteram release 5-18
> > Git checkout -b newbracnh for cherry pick
> > Git cherry-pick sha of your pr
> > Git push
> > Open a pr
> 
> Thanks, will follow that. So the "git cherry-pick" runs on the newbranch (hence the final pr), not on the release one (the actual pr move from master happens only after the merge of the final pr).

@cpanato , just occurred to me, if we create a PR for integration of this PR into 5.18 branch and another one for the integration of https://github.com/mattermost/enterprise/pull/525 into 5.18 branch, won't the automation fail again because of the cross-dependecy between enterprise and server repos? or should the git push above be to "git push upstream newbranch" like for the original PRs? Thanks.

**Comment by amyblais** [comment]
@cpanato @catalintomai Do you know if this has been cherry-picked?

**Comment by catalintomai** [comment]
> @cpanato @catalintomai Do you know if this has been cherry-picked?
I believe it (automatically) went in into the release branch when hmhealey cheked in the golangci change - see https://community-release.mattermost.com/core/pl/6uajp7p3hprttegu8kne9mia5w.

**Comment by justinegeffen** [comment]
@cpanato / @catalintomai, could you let me know whether this change is in all the export types or just global relay?  If the latter, I've raised this PR for Actiance changes and can add relevant CSV/Global Relay changes in there if needed.

**Comment by cpanato** [comment]
this is more a question for @catalintomai and not for me @justinegeffen

**Comment by justinegeffen** [comment]
Thanks, @cpanato. I wasn't sure who to tag. :)

**Comment by justinegeffen** [comment]
My initial comment is actually a bit misleading, so I have added @catalintomai to my PR for review and to confirm that the update is accurate.

**Comment by catalintomai** [comment]
Hi @justinegeffen , are your referring to this PR? : 
https://github.com/mattermost/docs/pull/3221 
If that is the case, that one talks about deleted messages/files messages, while this one deals with custom message types (which are global relay only fwik -  @icelander , who did the actually work, can confirm.

**Comment by justinegeffen** [comment]
Thanks for clarifying, @catalintomai! That makes sense. So, reading through what I wrote, it looks like I should edit the first bullet list so that "Posts from plugins" and "Posts from bots/webhooks" have "Global Relay Only). @icelander, could you confirm this? :)

**Pull request merged**
