### PR TITLE
[MM-32626] Disable notices for migrations test helper

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Disable notices for migrations test helper.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-32626

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by reflog** [comment]
LGTM. We've discussed this before and it's unfortunate that we have to do a blocking call on startup, but I think it's still better than over complicating notices fetcher with synchronization.

**Review by reflog — APPROVED** [review]

**Review by streamer45 — COMMENTED** [review]
Do we have a rough idea on how long this takes on average?
Also, is the race also affecting normal server execution or just the test case?

**Comment by isacikgoz** [comment]
On average it took 300ms to 400ms. Tested with `https://notices.mattermost.com/`.  It's affecting the testlib specifically at `setupTestHelper` and the reason is [here](https://github.com/mattermost/mattermost-server/blob/c1dd23a3c80365c4ca4e2721e55c0c2c90038b25/migrations/helper_test.go#L44).

**Comment by streamer45** [comment]
> On average it took 300ms to 400ms. Tested with `https://notices.mattermost.com/`. It's affecting the testlib specifically at `setupTestHelper` and the reason is [here](https://github.com/mattermost/mattermost-server/blob/c1dd23a3c80365c4ca4e2721e55c0c2c90038b25/migrations/helper_test.go#L44).

I assume those numbers are from an (almost) empty instance? If I recall correctly we end up calling `AnalyticsPostCount` eventually which could take far more than a few seconds to complete on big posts tables so I am a bit worried that to fix a test we significant deteriorate the startup process.

**Comment by isacikgoz** [comment]
Very good point @streamer45 I didn't take that into account. And the numbers are from my local instance and as you guessed it has the initial test data. I'm going back to the parallel approach again 👍

**Comment by isacikgoz** [comment]
@reflog Asking a re-review since the implementation is changed :)

**Review by streamer45 — APPROVED** [review]
Thanks @isacikgoz , this looks like a great solution :+1:

**Review by reflog — APPROVED** [review]

**Pull request merged**
