### PR TITLE
MM-24817: Bump hashicorp/memberlist

### PR DESCRIPTION
**Pull request by agnivade**
- go get -u github.com/hashicorp/memberlist
- go mod tidy
- go mod vendor

#### Ticket link
https://mattermost.atlassian.net/browse/MM-24817

### CODE REVIEW

**Comment by agnivade** [comment]
Yes, that's what v0.2.2 contains.

**Comment by grundleborg** [comment]
@agnivade @ogi-m is there a plan for QA-ing this PR pre-merge, or do we just need to push ahead and merge it and test on community?

**Comment by agnivade** [comment]
I have mentioned the QA steps. It is very easily reproducible, so can be tested pre-merge.

**Pull request merged**
