### PR TITLE
MM-18668: Fix for scan error selecting null SchemeGuest columns.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Fix for scan error querying `TeamMembers` or `ChannelMembers` when the `SchemeGuest` column is `null`.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18668

### CODE REVIEW

**Comment by mkraft** [comment]
@lindalumitchell The error wouldn't reproduce on a spinwick without DB manipulation because it requires `ChannelMembers.GuestScheme` columns to be `null`.

**Comment by lindalumitchell** [comment]
Ah, thank you @mkraft; I didn't realize. Will add a note to the ticket so we don't test incorrectly there as well. 👍

**Comment by mkraft** [comment]
> Ah, thank you @mkraft; I didn't realize. Will add a note to the ticket so we don't test incorrectly there as well. 👍

@lindalumitchell I have always added the QA steps after the PR is approved because that's when Jira prompts one to do so, but perhaps with more QA happening in the PR phase we should change that prompt for QA steps to happen in Jira when one transitions to Submit PR.

**Comment by lindalumitchell** [comment]
@mkraft that is an excellent idea. Will suggest doing that. Thanks!

**Pull request merged**
