### PR TITLE
Adding IdAttribute setting for SAML

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Adding IdAttribute setting for SAML for allow more robust treatment of
deactivated accounts

#### Ticket Link
[MM-10532](https://mattermost.atlassian.net/browse/10532)

#### Checklist
- [x] Has enterprise changes (mattermost/enterprise#341)
- [x] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
@jespino Can you help add this to the diagnostics.go, similar to https://github.com/mattermost/mattermost-server/blob/master/app/diagnostics.go#L461

**Comment by jespino** [comment]
@jasonblais sure! :)

**Comment by jespino** [comment]
@jasonblais Done! :)

**Comment by jespino** [comment]
@jasonblais done :)

**Pull request merged**
