### PR TITLE
UCHAT-60 change default notification settings for new users

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
These were more practical defaults compared to the original very noisy defaults, which have come quieter overtime. Let's discuss.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

cc @dmeza

### CODE REVIEW

**Comment by esethna** [comment]
@dmeza can you help me understand what is the change to the Reply Notifications setting?

We've been investigating other changes to default notification settings as well. Would be good to hear your thoughts on:

1. Turning off "Your case sensitive first name" and "Your non-case sensitive username" in Words that trigger mentions
2. Send Desktop Notifications for "Only for mentions and direct messages"
3. Agree on switching push notifications to away and offline only

**Comment by dmeza** [comment]
@esethna discussed with @csduarte. The change is for 3, but we definitively agree that all 3 are the best default options.

**Comment by esethna** [comment]
@dmeza let me know if you have any questions about the above ^?

**Comment by dmeza** [comment]
@esethna sorry for the delay, I made sure all my changes worked as expected for defaults. Rebased to latest from master. These are the changes:
1. Mobile push notifications: Trigger push notifications when "Away or offline"
2. Words that trigger mentions: turn off "Case sensitive first name"
3. Desktop Notifications when "Only for mentions and direct messages"
4. Reply Notifications when "Do not trigger notifications on messages in reply threads unless I'm mentioned"
Let me know if everything matches. A single extra change on the `webapp`: https://github.com/mattermost/mattermost-webapp/pull/332.
cc @csduarte

**Comment by dmeza** [comment]
@esethna let me know if these changes and the webapp changes are ok.

**Pull request merged**
