### PR TITLE
MM-34787: Add colored output for non JSON console logs

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-34787

```release-note
A new field EnableColor is added to LogSettings and NotificationLogSettings.
Non-JSON console logs will now be colored if that field is set to true.
```
colors

### CODE REVIEW

**Review by streamer45 — COMMENTED** [review]
Nice addition :+1: I have just a couple of minor concerns with the design:

I am not entirely convinced about passing the whole config just to get `DeveloperMode`.
Do we need the `mlog` package to be aware of the `DeveloperMode`?
I am thinking the decision of using colored output or not can be either left to the caller or even made directly configurable from `model.LogSettings`.

**Comment by agnivade** [comment]
I actually wanted colored output to be by default for all non-JSON output. But there might be some customers running non-JSON in production, in which case they might start to get weird characters in their console. Adding another field to `LogSettings` sounds good to me.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by streamer45 — APPROVED** [review]
Looks great :+1: 

I am guessing this might need a minor addition to the docs so it probably makes sense to add the label.

**Pull request merged**
