### PR TITLE
MM-46911: P1 - Fix MySQL query to filter bots out of TopDM

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

- DM channel names are of the form `userid1__userid2`. The query checks if both substrings are ordinary `non-bot` users.
- The MySQL query using `SUBSTRING_INDEX` was wrong and for `userid2` check was not successful due to wrong syntax.
- Test was flaky because in some cases `userid1` was bot and that part succeeded, it failed when `userid2` was bot. This is alphabetical and randomly generated.

This PR makes the following changes

 - Fixes MySQL query
 - Adds a sqlstore test to verify exclusion of bot DMs

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-46911

Will create a new and appropriate ticket when JIRA is up.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by agnivade — APPROVED** [review]
Great work on prompty fixing this @plant99 . Appreciate it!

**Review by furqanmlk — APPROVED** [review]

**Pull request merged**
