### PR TITLE
Adding the focalboard plugin feature flag

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Adding the focalboard plugin feature flag

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by jespino** [comment]
@lieut-data I don't know if this needs QA or if it is easy or hard of QA.

**Review by lieut-data — APPROVED** [review]
I don't think this needs QA, no. Exciting, @jespino!

**Review by crspeller — APPROVED** [review]

**Comment by amyblais** [comment]
@jespino @mgdelacroix If this is for v5.36, it needs to be cherry-picked to ``cloud`` branch.

**Comment by jespino** [comment]
Yes, we need that for cloud.

**Comment by jespino** [comment]
@amyblais cherry-picked to cloud :)

**Pull request merged**
