### PR TITLE
MM-34000: Use non-epoll mode for TLS connections

### PR DESCRIPTION
**Pull request by agnivade**
A *crypto/tls.Conn does not expose the underlying TCP connection
or even a File method to get the underlying file descriptor
like the way a *net/TCPConn does. Therefore the netpoll code would
fail to get the file descriptor.

Relevant issue here: https://github.com/mailru/easygo/issues/3

It is indeed possible to use reflect black magic to get the unexported
member, but I have found unexpected errors during writing to the websocket
by getting the file descriptor this way. I do not want to spend time investigating
this especially since this is already released.

Once this is out, we can decide on the right way to fix this, most probably
by proposing to expose the File method or some other way.

https://mattermost.atlassian.net/browse/MM-34000

```release-note
Fix an issue where websockets wouldn't work with TLS connections.
In that case, we just fall back to the way it works for Windows machines,
which is to use a separate goroutine for reader connection.
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Looks good :+1: Good thing we have kept the other implementation around :)

**Review by nronas — APPROVED** [review]
Nice finding. LGTM

**Comment by agnivade** [comment]
@lindalumitchell - I would like this to be tested out by an SDET since this was a regression from a release. The test steps are mentioned in the ticket. Please feel free to assign to anybody.

**Comment by saturninoabril** [comment]
@agnivade Did the steps in the ticket and was able to setup the TLS in local. TLS is verified working both in Chrome and Firefox.
Screen Shot 2021-03-18 at 10 59 52 PM
Screen Shot 2021-03-18 at 11 00 14 PM

But got error on user login and other user activities, like below:
- `ERRO[2021-03-18T23:06:05.624897+08:00] http: panic serving [::1]:60178: could not get file descriptor`
Screen Shot 2021-03-18 at 11 07 43 PM

**Comment by saturninoabril** [comment]
Hmm, for some reason, my config was reset. I didn't know why. But now, I can confirm that my settings are correct (see below).
Screen Shot 2021-03-18 at 11 21 05 PM

With server restart,
1. When TLS is set, the original error on file descriptor is no longer showing up.
2. However, when TLS is set, I'm seeing error log `... websocket.read: error during writing to websocket ...` (See screenshot. Can be seen easily on user logout).
Screen Shot 2021-03-18 at 11 34 53 PM
3. Note that item 2 error didn't show up when TLS is not set.

**Review by saturninoabril — APPROVED** [review]
@agnivade Thanks for updating. Tested and passed. No longer seeing the error logs related to websocket, and TLS and websocket connection works as expected.

**Comment by amyblais** [comment]
@agnivade Please also cherry-pick to ``cloud`` in addition to v5.33.

**Comment by agnivade** [comment]
Will do.

**Comment by agnivade** [comment]
Btw, I also cherry-picked another important bug fix which got missed out to be backported to 5.33 (https://github.com/mattermost/mattermost-server/pull/17026). Both of them are part of https://github.com/mattermost/mattermost-server/pull/17179.

The cloud branch already had the other fix.

**Pull request merged**
