### PR TITLE
Change Dockerfile HEALTHCHECK intervals

### PR DESCRIPTION
**Pull request by cadavre**
We should not use such a long `HEALTHCHECK` `--interval` as first task check if happening after given time, and before healthcheck returns `0` – **task won't be available** to the Docker networks – meaning that Mattermost won't work until then even if it deployed correctly!

And in Docker envs it happens often – that DB is available all the time, and just MM app is being updated. In this case even if we are healthy since 1s – we need to wait 5min until it goes online.

### CODE REVIEW

**Comment by teresa-novoa** [comment]
Hi @cadavre I see that @hanzei requested a review on your side, let us know if you need any help. Thanks!

**Comment by hanzei** [comment]
@cpanato @metanerd Could you please provide QA test steps for this PR?

**Comment by teresa-novoa** [comment]
@cpanato can you help to sync and merge this PR? Thanks!

**Comment by teresa-novoa** [comment]
Thanks @cpanato!

**Pull request merged**
