### PR TITLE
WIP: [MM-9937] Add support for sending a message to a different channel than where the slash command was issued from

### PR DESCRIPTION
**Pull request by cpanato**
@jasonblais open the PR for early feedback to check if this what needs to be done.

@jwilander please let me know if override the args.channelId is good otherwise I will create a new parameter for the functions or create a new args parameter.

TODO: check the permissions: if the user has permission to post on the override channel and other checks.

#### Summary
Add support for sending a message to a different channel than where the slash command was issued from

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/MM-9937
GitHub: https://github.com/mattermost/mattermost-server/issues/8512

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jwilander** [comment]
I think overriding `args.channelId` is fine but you'll need to check and make sure the user has permission to the channel they're trying to execute the slash command in

**Comment by jasonblais** [comment]
@cpanato Does this change apply to all slash commands? (custom and built-in)

**Comment by cpanato** [comment]
@jasonblais yes, apply to the built-in and custom

**Comment by cpanato** [comment]
@jasonblais I agree, i will think a bit and see what we can do.

**Comment by cpanato** [comment]
closing this one, will make another PR based on a discussion with @jasonblais

**Pull request closed without merging**
