### PR TITLE
Add missing timezone setting to app/diagnostics.go

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by hmhealey** [comment]
@jasonblais Should we also look at the TimezoneSettings as well?
```
    "DisplaySettings": {
        "ExperimentalTimezone": true
    },
    "TimezoneSettings": {
        "SupportedTimezonesPath": "timezones.json"
    }
```

**Comment by jasonblais** [comment]
@hmhealey Probably, but I don't know how we would go about adding it to the diagnostics, or knowing if an admin modified that file.

**Comment by hmhealey** [comment]
I just mean looking at TimezoneSettings.SupportedTimezonesPath to see if it's set. Not that I think we care about it though

**Comment by jasonblais** [comment]
@hmhealey Ah I see - it may or not be needed, but probably better to include for completeness.

I'm not entirely sure what the entry for it would be, is it

```
"isdefault_ supported_timezones_path":                                      isDefault(*cfg.TimezoneSettings.SupportedTimezonesPath, model.TIMEZONE_SETTINGS_DEFAULT_SUPPORTED_TIMEZONES_PATH),
``` 

^guess based on other similar entries where we check for a default that's not null

**Comment by jasonblais** [comment]
@hmhealey Committed the change to add diagnostic for `TimezoneSettings` - once you've had a chance to add `model.TIMEZONE_SETTINGS_DEFAULT_SUPPORTED_TIMEZONES_PATH`, feel free to merge. Thanks for the help!

**Pull request merged**
