### PR TITLE
[MM-20706] Drop 26 character requirement from post action IDs

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR drops the 26 character requirement from post actions IDs. Given that post actions are namespaced inside there corresponding post, they don't have to be globally unique.

Given that we are enforcing post actions ids to have a least one character in https://github.com/mattermost/mattermost-server/blob/master/api4/integration_action.go#L14, I did drop `Context.RequireActionId` entirely.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20706

### CODE REVIEW

**Comment by hanzei** [comment]
@jwilander Including you as a reviewer because it's a quite "old" code piece, which you have worked on in the past and I want to make sure, I've not missed an edge case.

**Comment by hanzei** [comment]
Heads up that this is for 5.20, so take your time to review.

**Comment by levb** [comment]
@hanzei sync and merge, please; not sure if jenkins enterpise failure is ok.

**Comment by hanzei** [comment]
The jenkins failure is unrelated.

**Comment by hanzei** [comment]
@prapti Heads up: This PR does require in depth QA testing as there is a high chance for regressions. I've added QA test steps to the ticket. Let me know, if you need additional information.

Please note that this PR is for 5.20, so you have a lot of time to review this.

**Comment by jasonblais** [comment]
@prapti Quick reminder to help with QA review when you have time. v5.20 feature merge deadline is set to January 16th.

**Comment by prapti** [comment]
> @prapti Quick reminder to help with QA review when you have time. v5.20 feature merge deadline is set to January 16th.

Thanks @jasonblais! Yup getting on the 5.20 PRs now that we're officially on it :)

**Comment by prapti** [comment]
In test queue

**Comment by prapti** [comment]
Test in progress

**Comment by hanzei** [comment]
Awesome @prapti. Thank you very much for the in depth testing :+1:

**Comment by hanzei** [comment]
@aaronrothschild This change definitely need to be document. From now on integrations should always provide there own action IDs instead of relying on the server to generate them. This is a best practise to document.

**Comment by jasonblais** [comment]
@hanzei is this a breaking change? cc @amyblais

**Comment by hanzei** [comment]
No, the change is fully backwards compatible

**Comment by justinegeffen** [comment]
@hanzei, do you have a specific section that needs to be updated? Or, if it's new content, do you have a link for where it should go? Thanks!

**Comment by justinegeffen** [comment]
Thanks @hanzei. Would you be open to updating the content? Alternatively if you could share some rough content/examples that'll be helpful. :)

**Comment by hanzei** [comment]
@justinegeffen Let me take care of documenting this PR myself.

**Pull request merged**
