### PR TITLE
Simplify two queries in channel store

### PR DESCRIPTION
**Pull request by Pomyk**
#### Summary
Query in GetMoreChannels was executed with 'dependant subquery' in MySQL <= 5.7. Now it is ~20% faster in MySQL and ~10% faster in PostgreSQL.
Query in getSearchGroupChannelsQuery is around 20% faster in MySQL. In PostgreSQL it is, depending on data, up to a few times faster but sometimes ~20% slower.

### CODE REVIEW

**Comment by jespino** [comment]
@Pomyk Hi, thanks for your PR, I have to think about it and see if we are not changing the behavior here.

**Comment by Pomyk** [comment]
I think it is equivalent. Upon further inspection it looks like GetMoreChannels function is not used anymore?
I'm also working on a benchmark and from first tests the simplified getSearchGroupChannelsQuery is not faster on MySQL. I will test on PostgreSQL later today.

**Comment by Pomyk** [comment]
Just ran the benchmark and for MySQL the new version looks a bit faster actually, but for PostgreSQL it's slower. 

    benchmark                                                      old ns/op     new ns/op     delta
    BenchmarkChannelStore/mysql/GetMoreChannels-16                 655245        591167        -9.78%
    BenchmarkChannelStore/mysql/SearchGroupChannels-16             755131        694325        -8.05%
    BenchmarkChannelStore/postgres/GetMoreChannels-16              1143659       1086207       -5.02%
    BenchmarkChannelStore/postgres/SearchGroupChannels-16          1523730       1974434       +29.58%

**Comment by Pomyk** [comment]
I will close this for now, needs more testing :)

**Pull request closed without merging**
