### PR TITLE
MM-25115 - move cache2 package to cache

### PR DESCRIPTION
**Pull request by liusy182**
#### Summary

This PR is the last one in the series. It does a few clean up tasks:

- remove the old `cache` package; rename the new `cache2` package to `cache`

- remove the old `server.CacheProvider`; rename `server.CacheProvider2` to `server.CacheProvider`

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-25115

### CODE REVIEW

**Comment by agnivade** [comment]
@ogi-m - Just some general smoke testing is sufficient.

**Comment by amyblais** [comment]
@agnivade Can this be pushed to v5.28 or does this need to be merged into 5.26 together with the other PRs related to this?

**Comment by agnivade** [comment]
Nope. Can be moved to 5.28. :+1:

**Pull request merged**
