### PR TITLE
MM-35127 CRT: Marking thread as unread doesn't set the timestamp correctly

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

correctly handle mention counting on timestamp change
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-35127
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by ogi-m** [comment]
@reflog Here are the steps:

**Threads bolded + mention badge:**
1. Create a root post with a mention for user-1 and add a reply post to it
2. As user-1 open the thread and make sure it's marked as read
3. Now mark the thread as unread

Expected: _Threads_ should be bolded but without mention badge
Observed: _Threads_ is bolded and mention badge is displayed

**Threads not bolded but mention badge shown:**
1. Create a root post with a mention for user-1
2. As user-1 add a reply to the root post
3. As user-1  open the thread and make sure it's marked as read
3. Now mark the thread as unread 

Expected: _Threads_ should be bolded but without mention badge
Observed: _Threads_ is not bolded and mention badge is displayed next to it

SharedScreenshot

**Comment by reflog** [comment]
@ogi-m - I checked the hash on the test-server you created and it doesn't match the webapp PR. I'll try re-creating the server and testing again

**Comment by reflog** [comment]
@ogi-m - tried on the newly created server, seems to be working correctly

**Review by ashishbhate — APPROVED** [review]

**Comment by ogi-m** [comment]
@reflog I'm still seeing the same behaviour

**Comment by ashishbhate** [comment]
@ogi-m FWIW, in my local checkout it works as expected.

**Review by ogi-m — APPROVED** [review]

**Pull request merged**
