### PR TITLE
MM-41153: Add seats deployed to support packet

### PR DESCRIPTION
**Pull request by agnivade**
Support packet contains 2 new fields:
1. Active users.
2. License supported users.

We refactor the code to its separate file.

```release-note
The Support Packet now contains 2 additional fields in the support_packet.yaml file:
1. Active users.
2. License supported users.
```

### CODE REVIEW

**Comment by agnivade** [comment]
Random review request since Ibrahim is out :)

**Comment by agnivade** [comment]
cc @svelle

**Comment by svelle** [comment]
Awesome, thanks for the ping agniva.

**Review by streamer45 — APPROVED** [review]
Looks good, assuming most of the code was just moved :+1:

**Pull request merged**
