### PR TITLE
[MM-52547] Include current user profile in every redux action

### PR DESCRIPTION
**Pull request by LeonardJouve**
#### Summary
Update current user in the store on every profiles related redux actions

This PR is a follow up to this [PR](https://github.com/mattermost/mattermost-server/pull/23071) and related to this [JIRA](https://mattermost.atlassian.net/browse/MM-52547) ticket.

#### Release Note

```release-note
Include current user profile in every redux action
```

### CODE REVIEW

**Review by M-ZubairAhmed — COMMENTED** [review]
This looks good :shipit: to me unless Harrison has some comments. Thank you

**Comment by hmhealey** [comment]
The code changes look good to me, and the E2E tests are passing, but I'm waiting on QA for the PR that this is based off of to run before signing off

**Review by yasserfaraazkhan — APPROVED** [review]
thank you for the changes!
e2e tests have passed

**Comment by M-ZubairAhmed** [comment]
@hmhealey is it now ready to be merged?

**Review by hmhealey — APPROVED** [review]
Yep, sorry for the delay. This looks good to me!

Thanks again for cleaning this all up, @LeonardJouve. I'm glad that those actions won't have any more unexpected behaviour any more

**Pull request merged**
