### PR TITLE
MM-49862 - remove no longer needed webapp calls to action and pulsati…

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
Manual cherry-pick for https://github.com/mattermost/mattermost-server/pull/22699

#### Ticket Link
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@pvev Why are we cherry-picking this?

**Comment by pvev** [comment]
> @pvev Why are we cherry-picking this?

ok, this was intended to go to cloud release. cc: @marianunez

**Comment by amyblais** [comment]
I think this can go to April 27 release unless Maria says otherwise.

**Comment by marianunez** [comment]
> I think this can go to April 27 release unless Maria says otherwise.

This was mostly a bug fix so I thought we had time to cherry pick to cloud. Not a blocker

**Pull request closed without merging**
