### PR TITLE
prepackage boards to v0.11.0

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update prepackaged boards version to 0.11.0

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/1831

#### Release Note
```release-note
Update prepackaged boards version to 0.11.0
```

### CODE REVIEW

**Review by chenilim — APPROVED** [review]
LGTM

**Review by mgdelacroix — APPROVED** [review]
LGTM :+1:

**Pull request merged**
