### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-server_master/) for mattermost-languages-shipped/mattermost-server.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by amyblais** [comment]
@puerco Can you help cherry-pick the latest server/webapp translations PRs to ``cloud`` and ``release-6.0`` branches?

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
@amyblais i will do that

**Comment by puerco** [comment]
@amyblais of course :+1:

**Comment by cpanato** [comment]
conflicts! need to do manually

**Comment by puerco** [comment]
I can handle the merge conflicts if you want :)

**Pull request merged**
