### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by james-mm**
Customer wanted us to be more explicit on this page about searching for existing tickets in JIRA vs Github before proceeding to submit a new ticket.

Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).

When filling in a section please remove the help text and the above text.

#### Summary
[A brief description of what this pull request does.]

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by jasonblais** [comment]
Was the customer frustration that they filed a ticket, which already existed in JIRA?

**Comment by james-mm** [comment]
The frustration was that it was not clear in Github itself that JIRA was also being used and that the customer should click on that link and follow the instructions first (which includes searching in JIRA) before filing the ticket.

**Comment by james-mm** [comment]
I think the edit made it clearer that they should follow the instructions in http://www.mattermost.org/filing-issues/ (and mentioning that they need to search in JIRA first) before filing an issue in Github. 

But agree, it would be good to explain the process as there tends to be confusion about what is stored where and why. E.g. why Github and JIRA are both being used for tracking.  

Thoughts @lfbrock @jasonblais ?

**Comment by jasonblais** [comment]
I'm 0/5, I'm okay with what Lindsay and you are suggesting. They make sense.

**Comment by jasonblais** [comment]
@james-mm Were you going to help with the update based on LB's feedback?

**Comment by james-mm** [comment]
@jasonblais Just updated, please review

**Pull request merged**
