### PR TITLE
Display board statistics

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
When retrieving Boards statistics a permission check for `display-board-statistics` which requires the additional API `HasPermissionTo`

#### Ticket Link
https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/b4ctmm917q3rzdfi451qtuxjzcw/vn3tt1q8ndj87frb4uyu4936yfh/ccitgbkb11bgxbyirdgnun9u7mw

#### Required for Boards
https://github.com/mattermost/focalboard/pull/4025

#### Release Note

```release-note
Added new Plugin endpoints to PermissionService interface.

```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM  This will require some plumbing along two code paths in Boards (plugin and product mode)

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
Oops, I though this was in focalboard repo and I merged before QA, not a big deal, because the QA part of this would be almost impossible, but sorry for that.

**Comment by amyblais** [comment]
@sbishel Is this for v7.5?

**Pull request merged**
