### PR TITLE
[MM-30980] Avoid modifying original post when sending a notification

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
The code to send a notification was modifying the original post before, which caused the fallback text to appear repeated in the interface.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30980

#### Release Note
```release-note
Fixes messages with fallback text repeated
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Nice one

**Review by isacikgoz — APPROVED** [review]
Wow, nice catch!

**Review by lindy65 — APPROVED** [review]
Thanks @mgdelacroix - will test this after merge 👍

**Comment by amyblais** [comment]
@mgdelacroix Please help cherry-pick manually to ``release-5.31``.

**Comment by amyblais** [comment]
@mgdelacroix Can you help cherry-pick this manually to ``release-5.31``?

**Comment by mgdelacroix** [comment]
@amyblais cherry-pick done at https://github.com/mattermost/mattermost-server/commit/585f34fa8c2ea3f3e882db924a29d8dc3924bc5f

**Pull request merged**
