### PR TITLE
Revert "Revert "Set BoardsProduct FF to on by default" (#22177)"

### PR DESCRIPTION
**Pull request by agnivade**
This reverts commit aa61f8dfbbccc9fecb7cee20af1cd2feccffcf48.

### CODE REVIEW

**Review by amyblais — CHANGES_REQUESTED** [review]
Since we have already reverted this twice, are we 100% sure that there won't be any other major issues caused by this? Are there any other test scenarios or test enviroments where this should be tested before this goes into a release?

**Comment by agnivade** [comment]
I don't know how does spinwicks upgrade their instances, but if they are similar to how our cloud production servers work, then we can do what @saturninoabril mentioned here:

`/cloud create server-name` at current master
and then
`/cloud upgrade server-name` to this PR.

If they are not the same as how it works in production, then we should test in a dummy cloud instance with current master and upgrade that to this PR and test.

@saturninoabril - can you check with the cloud platform team on this?

**Comment by saturninoabril** [comment]
Will update the branch to recheck the behavior I'm seeing.

**Review by saturninoabril — APPROVED** [review]
Thanks @agnivade! Tested and passed.

**Review by amyblais — APPROVED** [review]

**Comment by JulienTant** [comment]
🙏🏻 can't wait to get this back 😅

**Pull request merged**
