### PR TITLE
Fix broken master; ensure all product service APIs have correct implementations

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR fixes a breaking change introduced via https://github.com/mattermost/mattermost-server/pull/20575.  The structs passed during product init must implements the interfaces defined in `product/api.go`.  Unfortunately, when the method signatures are changed the failures happen at run-time via type assertions.

Additionally, this PR adds compile-time checks to ensure changes to method signatures are detected immediately.

#### Ticket Link
NONE 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by noxer** [comment]
Very sorry I missed that. The fixes look good. To check for interface compatibility you can do `var _ Interface = (*mytype)(nil)` which avoids an allocation.

**Comment by wiggin77** [comment]
> Very sorry I missed that. The fixes look good. To check for interface compatibility you can do `var _ Interface = (*mytype)(nil)` which avoids an allocation.

No worries @noxer. You had no way to know those changes would break anything.  I updated the PR to use zero allocation checks.  Thanks for the tip.

**Review by noxer — APPROVED** [review]
LGTM. Is this dependency documented somewhere other than the code? I'd like to read up on it.

**Comment by wiggin77** [comment]
> LGTM. Is this dependency documented somewhere other than the code? I'd like to read up on it.

It's part of the multi-product architecture defined [in this spec](https://docs.google.com/document/d/1CdfFsJcP_QXthNuowXy4OXhFvRvfQZyRY6fBF2VyW7A/edit)   See the associated [channel](https://community.mattermost.com/core/channels/multi-product-architecture).

**Pull request merged**
