### PR TITLE
Hide tutorial with config

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Add config option to hide tutorial screens. The tutorial doesn’t necessarily apply, rather than choose parts to show and not others, we’ve added a config to be sent to frontend.

web pr: https://github.com/mattermost/mattermost-webapp/pull/325
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

cc @dmeza

### CODE REVIEW

**Comment by esethna** [comment]
@dmeza can you please help fix the conflicts and build server so we can get a test server running?

**Comment by dmeza** [comment]
@esethna fixed your comments and rebased to latest.

**Comment by esethna** [comment]
Cool, thanks, will test on the webapp PR!

**Comment by dmeza** [comment]
@crspeller @esethna rebased to latest and fixed conflicts.

**Comment by dmeza** [comment]
@jwilander @esethna rebased and tested that server is running properly. Also rebased `webapp` PR: https://github.com/mattermost/mattermost-webapp/pull/325

**Pull request merged**
