### PR TITLE
MM-49486: Option to exclude file count in channel stats

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Added a `exclude_files_count` param to exclude file counts from channel stats API. Returns -1 if file counts have been excluded. This is to differentiate between a zero files count, and excluded files count. 

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-49486

#### Release Note

```release-note
Added a `exclude_files_count` parameter to exclude file counts from channel stats API
```

### CODE REVIEW

**Comment by AshishDhama** [comment]
@ashishbhate yeah, Thanks for this.

**Review by AshishDhama — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by agnivade** [comment]
Ah man, this would be so easy to just avoid the `file_count` attribute in GraphQL. Unfortunately, do to some technical challenges, the channel stats API isn't well suited to GraphQL.

**Comment by ashishbhate** [comment]
@jgilliam17 This PR adds a parameter to the channel stats API. It isn't used anywhere yet. Some smoke testing around loading channels and viewing the channel header and info, especially the file counts, should be good.

**Review by jgilliam17 — APPROVED** [review]
Thanks @ashishbhate 
Tested, looks good to merge.
Verified channel loading and viewing the channel header and channel info. Channel info sidebar displays correct  file counts.
[E2E report ](https://mattermost-cypress-report.s3.amazonaws.com/294500-fe9d6a1-onprem-ent-server-pr-22096-mm-ee-test:fe9d6a1/mochawesome.html)- no PR related failures.

**Pull request merged**
