### PR TITLE
Last 4 credit card digits as a string

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Represent last 4 digits of credit cards as a string.

Supports https://github.com/mattermost/mattermost-webapp/pull/8463.
Depends on https://github.com/mattermost/customer-web-server/pull/529

No QA Review because the changes should be tested as part of the mattermost-webapp PR.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31950

#### Release Note

```release-note
Represent last 4 digits of credit cards as a string.
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
LGTM! Can you link in the PR description the related CWS PR as well ?

**Review by nickmisasi — APPROVED** [review]

**Pull request merged**
