### PR TITLE
translations PR 20171121

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

See the webapp PR at https://github.com/mattermost/mattermost-webapp/pull/336

### CODE REVIEW

**Comment by wget** [comment]
`fr` LGTM

**Comment by kaakaa** [comment]
Hi.
I cannot translate `.api.command_groupmsg.invalid_user.app_error` correctly.
https://translate.mattermost.com/ja/mattermost/translate/platform.po#unit=529107

When I see other language's translation, there are two input box. (ex. [de](https://translate.mattermost.com/de/mattermost/translate/platform.po#unit=528767), [es](https://translate.mattermost.com/es/mattermost/translate/platform.po#unit=528823), [pt_BR](https://translate.mattermost.com/pt_BR/mattermost/translate/platform.po#unit=529331))
How can I display the second input box?


And the rest is LGTM

**Comment by jasonblais** [comment]
@kaakaa I'm not sure.. @enahum would you have any idea?

**Comment by enahum** [comment]
I'll take a look. but anyway I'm going to close this PR as there is a new one already submitted

**Comment by enahum** [comment]
@kaakaa @jasonblais Japanese should be showing plurals now

image

**Comment by kaakaa** [comment]
Thank @enahum! It looks good to me now!!

**Pull request closed without merging**
