### PR TITLE
Add front wildcard search for users

### PR DESCRIPTION
**Pull request by haalcala**
Allow users to be searched with containing term instead of starting with.

This gives more convenience to users finding users from a large list.

### CODE REVIEW

**Comment by jfrerich** [comment]
Hi @haalcala, do you have an associated Github Issue, Jira ticket, or Mattermost discussion for this PR?  Thanks!

**Comment by haalcala** [comment]
Hi,

I do not have a ticket.

**Comment by grundleborg** [comment]
@esethna please could you comment on whether this change is desirable from a product point of view before we do a dev review on it?

**Comment by esethna** [comment]
I'll leave it to @mgdelacroix to respond here as he's been discussing next steps for this on community.

**Pull request closed without merging**
