### PR TITLE
[MM-39072] - Run make build-templates on latest master

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Some code from the style.mjml partial was not built into some generated templates when `make build-templates` is run. This means there's a diff when `make build-templates` is run on master, which shouldn't be the case.

From the diff files, only the invitation template has changes that are not just CSS classes. However, it still renders as before

Screenshot 2021-10-05 at 12 06 18

The guest email template was failing as a result of this change. This was expected due to a change in the past that updated the card.mjml partial for messages notification like mentions and batch email but didn't consider the fact that guest invitation templates also use it.

#### Ticket Link
[MM-39072](https://mattermost.atlassian.net/browse/MM-39072)

#### Release Note
```release-note
NONE

```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Comment by AGMETEOR** [comment]
Hi @koox00 so maybe I can merge this first and then this https://github.com/mattermost/mattermost-server/pull/18525 goes in after

**Comment by koox00** [comment]
> Hi @koox00 so maybe I can merge this first and then this #18525 goes in after

yes!

**Comment by AGMETEOR** [comment]
Hi @stevemudie . Requesting a QA review because there was some changes made to the invite template. Both members and guest invitations should be QA tested

**Review by stevemudie — APPROVED** [review]
Looks good @AGMETEOR!

Both Guest and Member invite emails land looking as they should.

**Review by marianunez — APPROVED** [review]

**Comment by agnivade** [comment]
Would you like it if I add a CI check for this so that it gets caught much earlier?

**Pull request merged**
