### PR TITLE
dockerfile: bump base MM package to 5.23.1

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
dockerfile: bump base MM package to 5.23.1

I will cherry pick this to release-5.23 branch to sync

#### Ticket Link
n/a

### CODE REVIEW

**Comment by cpanato** [comment]
the EE tests failed but never reported back 
/cc @metanerd

**Comment by cpanato** [comment]
@metanerd when I mention you were not to trigger, this I did :). was to you to check why it failed and not report back the failure.

**Comment by cpanato** [comment]
what!

**Comment by metanerd** [comment]
> @metanerd when I mention you were not to trigger, this I did :). was to you to check why it failed and not report back the failure.

Rate limit was the reason why it didn't report back after failing. 
I am reenabling cherry picking. You can wait a bit and try again.

**Comment by cpanato** [comment]
@metanerd was not, the job that reports back never run

**Comment by metanerd** [comment]
This job was run and it reports back when there is a failure: https://github.com/mattermost/enterprise/blob/6185b9c3def6bd3265940f6bef48b03d9c349f0d/.circleci/config.yml#L228 but then it ran into the rate limit.

**Comment by cpanato** [comment]
sent a message in MM

**Comment by cpanato** [comment]
doing manually

**Comment by cpanato** [comment]
done

**Pull request merged**
