### PR TITLE
Cherry pick of MM-38634: Simplify image proxy (#19603) to release 6.3

### PR DESCRIPTION
**Pull request by isacikgoz**
Cherry-pick of #19603
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Ok clockwork got removed as well. Which is what I was seeing. I thought it wouldn't get removed on your setup. :thinking:

**Comment by agnivade** [comment]
Ah there you go : `error: pathspec './vendor/github.com/prometheus/client_golang/prometheus/collectors' did not match any file(s) known to git`. This is because client_golang got removed and we have this line here: https://github.com/mattermost/enterprise/blob/015c5033fa8112864dd97faa8f02c0f3595e6dff/.circleci/config.yml#L99.

Sorry it's one hack after the other. If client_golang indeed gets removed, then I think we need to remove that line as well. But curiously, when you run `go mod tidy` in master, there's no change? When I run it in master, client_golang and others get removed.

**Comment by isacikgoz** [comment]
When I run `go mod tidy` on master it gets changed..

```diff
diff --git a/go.mod b/go.mod
index 94609af14..d178b5908 100644
--- a/go.mod
+++ b/go.mod
@@ -52,7 +52,6 @@ require (
        github.com/hashicorp/yamux v0.0.0-20211028200310-0bc27b27de87 // indirect
        github.com/jaytaylor/html2text v0.0.0-20211105163654-bc68cce691ba
        github.com/jmoiron/sqlx v1.3.4
-       github.com/jonboulle/clockwork v0.2.2
        github.com/klauspost/compress v1.14.2 // indirect
        github.com/klauspost/cpuid/v2 v2.0.11 // indirect
        github.com/ledongthuc/pdf v0.0.0-20210621053716-e28cb8259002
@@ -85,13 +84,12 @@ require (
        github.com/pierrec/lz4/v4 v4.1.14 // indirect
        github.com/pkg/errors v0.9.1
        github.com/prometheus/client_golang v1.12.1
-       github.com/prometheus/client_model v0.2.0
        github.com/reflog/dateconstraints v0.2.1
        github.com/richardlehane/mscfb v1.0.4 // indirect
        github.com/rs/cors v1.8.2
        github.com/rs/xid v1.3.0 // indirect
        github.com/rudderlabs/analytics-go v3.3.2+incompatible
-       github.com/russellhaering/goxmldsig v1.1.1
+       github.com/russellhaering/goxmldsig v1.1.1 // indirect
        github.com/rwcarlsen/goexif v0.0.0-20190401172101-9e8deecbddbd
        github.com/segmentio/backo-go v0.0.0-20200129164019-23eae7c10bd3 // indirect
        github.com/spf13/cobra v1.3.0
```

**Comment by agnivade** [comment]
Wait, what? Then both of us are on the same page. How come it was different in https://github.com/mattermost/mattermost-server/pull/19618?

**Comment by isacikgoz** [comment]
@agnivade I am very surprised too, will take a look that on Monday though.

**Pull request merged**
