### PR TITLE
[MM-19948] Set version on module file and internal paths

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR changes the `mattermost-server` import path of all the go files in the repository as well as the module line to comply with the module version specification.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-19948
Fixes: https://github.com/mattermost/mattermost-server/issues/13077

#### Related Pull Requests

- [Enterprise](https://github.com/mattermost/enterprise/pull/529)

### CODE REVIEW

**Comment by hanzei** [comment]
The root problem we want to fix there is that it was not possible for integrations to use a release as a dependency. I'm wondering if it makes sense to cut a test tag pointing to this commit and confirm everything works fine.

Thoughts?

**Comment by mgdelacroix** [comment]
Agree, I've validated the PRs integrating them in `mmctl` through a local import and `replace`, but it would be nice to try in a scenario as close as possible to the real one.

**Comment by mgdelacroix** [comment]
Thanks to the help of @cpanato we've validated that importing the repo works after adding a testing tag :tada:

**Comment by hanzei** [comment]
@amyblais This definitely needs an entry in the changelog as it's a breaking change for all go projects importing this repo as a dependency.

@mgdelacroix What do you think about providing a `sed` command for the changelog so other projects can easily change there import path?

**Pull request merged**
