### PR TITLE
Boards data retention

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Implements Boards as part of the DataRetention Job, handled via new hook for any plugin. However, config setting is board specific.

#### Ticket Link
(https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vezy9zbpm1tnmfecbuoopjgsgqc/c88h9o9twcbgw787cd61r5a3wkw)

#### Related Pull Requests
- Has server changes 
https://github.com/mattermost/enterprise/pull/1126

- Has webapp changes
https://github.com/mattermost/mattermost-webapp/pull/9602

#### Release Note
```release-note
Added Boards as part of Data Retention
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by harshilsharma63 — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
Flag working as expected, the feature is not exposed in the UI with the flag disabled

**Comment by justinegeffen** [comment]
This will only need docs for 6.5, @amyblais. Just FYI. :)

**Comment by justinegeffen** [comment]
Confirmed with @wuwinson that this is going out in 6.6, apologies for the late notice @amyblais!

**Comment by justinegeffen** [comment]
@amyblais, this will only be shipping in August (7.2). :)

**Comment by cwarnermm** [comment]
@justinegeffen - Any outstanding documentation impact associated with this PR?

**Comment by wuwinson** [comment]
@cwarnermm @justinegeffen This was merged last year, but we haven't turned on the FF for it yet. We'll likely hold off on doing that until after the v7.8 ESR, in which time we will then need docs. Thanks and apologies for the confusion! cc @sbishel @ogi-m

**Comment by justinegeffen** [comment]
Thanks both! I've changed the milestone to 7.8.

**Comment by cwarnermm** [comment]
@wuwinson - Does this Engineering PR still require product documentation?

**Comment by wuwinson** [comment]
@cwarnermm We decided to not release this feature as part of the scope reduction after the re-org. Removed the docs label.

**Pull request merged**
