### PR TITLE
Revert "Dependency updates. (#14033)"

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
This reverts commit f14c79f170d3456ae9db7739f88563b37183e9a3. With @stylianosrigas's help, I've proven it resolves https://mattermost.atlassian.net/browse/MM-24165, and expect it to be related to https://mattermost.atlassian.net/browse/MM-24166 and https://mattermost.atlassian.net/browse/MM-24118 as well.

I don't currently have a detailed explanation of which dependency broke this behaviour, but @agnivade and I suspected something to do with `memberlist`. I had some trouble reverting just a subset of the dependencies, so opted to just rip it out altogether and punt the issue back to the server team for detailed analysis.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24165

### CODE REVIEW

**Comment by lieut-data** [comment]
@agnivade, that's correct -- it reproduced 100% of the time against `-daily` until this commit (after 1-3 attempts), and 0% of the time against `-release` and the other servers.

**Comment by lieut-data** [comment]
@lindy65, this one is "hard to test" outside of just merging it to community... which it already technically is since we've temporarily pointed `-daily` at this branch. So if you just gave `community-daily` a smoke test, I think that would suffice for QA testing.

**Comment by lieut-data** [comment]
Also, it's important to note that the issue was `HA` specific, so if we do test using a spinmint, we'll need an HA equipped one too for maximum coverage.

**Comment by agnivade** [comment]
@lieut-data - Got it. I'll look into it.

**Comment by lindy65** [comment]
Thanks @lieut-data - appreciate the info.  I'll smoke test around the tickets listed in this PR 👍

**Pull request merged**
