### PR TITLE
MM-30450: Pre-pacakge Incident Management v1.2.0

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package incident management v1.2.0.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-30450

#### Release Note
```release-note
Pre-package Incident Management v1.2.0.
```

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
🎉

**Review by crspeller — APPROVED** [review]

**Review by prapti — APPROVED** [review]
1.2 successfully being prepackaged on cloud and local plugins folder.
🎉

**Comment by agnivade** [comment]
@lieut-data - Is there anything else blocking this PR from being merged? Cloud team is looking to try out the plugin DB connection improvements in a test cluster.

**Comment by lieut-data** [comment]
@agnivade, strictly speaking, no -- we could merge this PR. The "official release" of IR v1.2 is pending final sign-off from @prapti, after which we'll merge https://github.com/mattermost/mattermost-marketplace/pull/156 to make it "public".

I'm happy to merge this to unblock your efforts.

**Comment by agnivade** [comment]
Amazing, thanks Jesse!

**Pull request merged**
