### PR TITLE
update morph dependency

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
A bug in morph was preventing to clear expired mutex from the lock table. The newest version promises to fix this issue 🤞

#### Release Note

```release-note
Bugfix on schema migrations where the mattermost server was failing to restart after having an error in the migration process.
```

### CODE REVIEW

**Comment by agnivade** [comment]
@amyblais - This will need to be backported till 6.4.

**Comment by amyblais** [comment]
This needs manual cherry-picks to 6.5 and 6.4 branches.

**Pull request merged**
