### PR TITLE
[MM-42083] Remove bots from add users to group dropdown

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

Fixes issue of bots showing up in

`/api/v4/users?not_in_group=<group_id>&page=0&per_page=100`

and therefore in the UI modal where users are added to usergroups.

#### Ticket Link

JIRA: https://mattermost.atlassian.net/browse/MM-42083
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by furqanmlk — APPROVED** [review]
Thanks @plant99  Working as expected, if @mkraft request some changes please reassign to me for retest.

**Before**

image

**After**

image

**Comment by mkraft** [comment]
@plant99 Should we close this?

**Pull request closed without merging**
