### PR TITLE
Metrics operations shouldn't be inside goroutine

### PR DESCRIPTION
**Pull request by ethervoid**
#### Summary

Metrics operations are done in memory so there is no need
to spawn a new goroutine

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-22714

### CODE REVIEW

**Comment by agnivade** [comment]
@ethervoid - I am inclined to run some smoke tests here since it is a non-superficial change, albeit small. Thoughts ?

**Comment by ethervoid** [comment]
@agnivade I've made some test by myself but ill do some more and also have someone from QA helping too

**Comment by ethervoid** [comment]
I've made more tests in my local environment and as you can see in the next screenshot the counters have been increased without errors:

Screenshot from 2020-02-28 13-38-16

I can't think of another scenario where we face a side-effect of this change or a bug

**Comment by agnivade** [comment]
Thanks @ethervoid. @srkgupta - This code touches the websocket metrics. Some general smoke testing on websockets on a metrics enabled server should be sufficient. I have updated the JIRA ticket with the steps.

**Pull request merged**
