### PR TITLE
Update pre-package boards to v7.7.0

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update pre-package boards to v7.7.0

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/4222

#### Release Note
```release-note
Update pre-package boards to v7.7.0
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]

**Comment by wiggin77** [comment]
Looks like enterprise is trying to pull from cloud branch.

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Pull request merged**
