### PR TITLE
[MM-50007] WorkTemplate: disallow creating private playbook without an enterprise license

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
This PR ensures that we do not let users create private playbooks if the server's license is not enterprise or E20.

A PR will come later in the webapp to disable the "private" option if the server does not hold an E20 license.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50007

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Nice, thank you @JulienTant!

**Review by mhd-sln — APPROVED** [review]
LGTM! Thanks @JulienTant!

**Comment by stevemudie** [comment]
This worked as expected @JulienTant but separate from the template approach I was able to create a private playbook directly.

I suppose that's out of scope for what you're doing here but what are your thoughts?

**Comment by JulienTant** [comment]
> This worked as expected @JulienTant but separate from the template approach I was able to create a private playbook directly.

Do you mean create it directly in playbooks? If so you can probably forward it to the playbooks team (cc @lieut-data) as it is a bug from my understanding.

**Comment by lieut-data** [comment]
It looks likespinwicks are configured with `ServiceSettings.EnableDeveloper` and `ServiceSettings.EnableTesting`:
CleanShot 2023-01-27 at 13 23 21@2x
CleanShot 2023-01-27 at 13 23 25@2x

See https://github.com/mattermost/mattermost-plugin-playbooks#license, but this effectively unlocks all Playbooks enterprise functionality for the purpose of developer testing. (We don't expect these values to be enabled in production since they allow for destructive changes.) If one or both of these are disabled, private playbooks should be restricted accordingly.

**Pull request merged**
