### PR TITLE
[MM-12374] Add CLI command for moving outgoing webhook

### PR DESCRIPTION
**Pull request by RajatVaryani**
#### Summary
Fixes https://github.com/mattermost/mattermost-server/issues/9769

TODO:
- [x] Add logic to check channel is in same team. 
- [x] Pass on appropriate message to the user
- [ ] Add translations for the message @jespino 

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/9769

### CODE REVIEW

**Comment by RajatVaryani** [comment]
@hanzei Need someone's help to close this. Can you please assign someone?

**Comment by RajatVaryani** [comment]
@jespino How are tackling rollback of a database query when the dependent one fails? It would be great if you point me to an example in code.

**Comment by jespino** [comment]
@RajatVaryani sorry for the delay in my reply. If you need that fine grained transaction control, you need to create your own store function (which is going to be called from the app layer, and then you can call that from your command). Normally we accept intermediate state if that is not generating an inconsistent situation in the database, if is properly notified and if is not something dangerous. For example, if you are moving a webhook from one team to another, probably the first thing is to create the new one, if then you fail removing the old one, as far as you properly inform the user about that situation, is safe.

**Comment by RajatVaryani** [comment]
@jespino Let me do that then. Let me propagate the message to the end user.

**Comment by RajatVaryani** [comment]
@jespino Can you please help with the pipeline failure as well. I am not able to figure why is it failing.

**Comment by RajatVaryani** [comment]
@jespino It's ready for review. I have added the message in `en.json`. The pipeline is failing because the translation of the message is not added.

**Comment by RajatVaryani** [comment]
Closing this PR. As my fork of the repo has deleted accidentally, Will raise another one.

**Pull request closed without merging**
