### PR TITLE
Migration of UserTermsOfServiceStore to return plain errors

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

This PR migrates the whole `UserTermsOfServiceStore` store to return plain errors in all its methods.

Additionally the `en.json` translation file has been ordered.

Fixes https://github.com/mattermost/mattermost-server/issues/14789

Jira ticket: https://mattermost.atlassian.net/browse/MM-25948

### CODE REVIEW

**Comment by rvillablanca** [comment]
Ticket needed here @agnivade :raised_hands: :woman_dancing: Thanks

**Comment by rvillablanca** [comment]
So is there indeed enterprise translation keys not starting with `end`?

**Comment by agnivade** [comment]
@lindy65 - All testing around user terms of service is necessary. Like loading TOS and saving/deleting TOS. Thanks.

**Comment by rvillablanca** [comment]
@agnivade I fixed the translations file so can you add the ee tags again please

**Pull request merged**
