### PR TITLE
MM-29379 Ignore channel mentions when channel is muted and channel mention setting is not updated by the user

### PR DESCRIPTION
**Pull request by sowmiyamuthuraman**
Added a condition to ignore the channel mentions when the channel is muted and the ignore_channel_mention field of notify_ prop is default while sending notification

Fixes mattermost/mattermost-server#15823
JIRA: https://mattermost.atlassian.net/browse/MM-29379

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/6718

#### Release Note
```release-note
Automatically disable channel wide mentions when a user mutes a channel
```

### CODE REVIEW

**Review by reflog — APPROVED** [review]
LGTM!

**Review by esethna — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Thanks for changing your PR up, @sowmiyamuthuraman. Looks good to me!

**Comment by hmhealey** [comment]
For QA, when testing this PR, you'll want to test that channel-wide mentions don't trigger notifications and don't cause the mention badge to be incremented for muted channels. The accompanying webapp PR will make it so that the Ignore Channel Mentions channel setting changes in the UI when the channel is muted and unmuted.

**Review by calebroseland — APPROVED** [review]

**Review by ogi-m — APPROVED** [review]
Tested and passed - verified that @channel, @all & @here channel mentions don't trigger notifications or increment the badge on muted channels

**Comment by hanzei** [comment]
Thanks for the great contribution @sowmiyamuthuraman :tada:

**Pull request merged**
