### PR TITLE
MM-23244: Validate that AuthData and AuthService fields are mutually inclusive.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Adds a new validation to the bulk importer for mutual inclusivity between `(*User).AuthData` and `(*User).AuthService`.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-23244

### CODE REVIEW

**Comment by srkgupta** [comment]
Hi @mkraft 
I tried to replicate this issue by first exporting the data containing LDAP users & then removing the auth_data for one of the users. When I import such a file, the import operation stops with an error "User AuthService and AuthData are mutually inclusive.". Is this expected that the import operation stops with an error (or) should the expected behavior be as mentioned in the JIRA ticket. Can you please confirm. 

> Create bulk import file with "auth_method":"ldap" and "auth_data":"" for any particular user (make sure the user also exists inside of LDAP and the username and email attributes are matching) run the import and after that ldap sync.

**Comment by mkraft** [comment]
> Hi @mkraft
> I tried to replicate this issue by first exporting the data containing LDAP users & then removing the auth_data for one of the users. When I import such a file, the import operation stops with an error "User AuthService and AuthData are mutually inclusive.". Is this expected that the import operation stops with an error (or) should the expected behavior be as mentioned in the JIRA ticket. Can you please confirm.
> 
> > Create bulk import file with "auth_method":"ldap" and "auth_data":"" for any particular user (make sure the user also exists inside of LDAP and the username and email attributes are matching) run the import and after that ldap sync.

I changed the behaviour to prevent the data from being imported invalidly, like the other validations already do, by throwing halting with an error message.

**Comment by srkgupta** [comment]
> I changed the behaviour to prevent the data from being imported invalidly, like the other validations already do, by throwing halting with an error message.

@mkraft Can you please update the Repro steps & Expected Results in the JIRA ticket. Because the current implementation conflicts with what is expected as per the JIRA ticket.

**Comment by amyblais** [comment]
@mkraft Is this risky or do we want this for v5.23 as it's a customer bug?

**Comment by mkraft** [comment]
@amyblais Yes it was reported by a customer but it's not an important change to the validation. It could wait for v5.24.

**Pull request merged**
