### PR TITLE
Add RequestTrialLicense function to the plugin API

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Expose the trial license request functionality to the plugins.

#### Ticket Link
Related to https://mattermost.atlassian.net/browse/MM-34665

#### Release Note
```release-note
Added a new function to the plugin API: RequestTrialLicense.
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Review by cpoile — APPROVED** [review]

**Comment by agarciamontoro** [comment]
Oopsie, I assumed that was the error ID, but it's actually the translation string ID. Fixing in a second.

**Comment by lieut-data** [comment]
Assigning @prapti to get this on her radar.

**Comment by agarciamontoro** [comment]
We are skipping QA here and testing this as part of https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/546 This PR is very isolated, and the worst case scenario is that the function added here to the plugin API does not work as intended. As https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/546 is the only usage of that function, testing that PR is enough.

**Pull request merged**
