### PR TITLE
db: upgrade db to 5.30

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
db: upgrade db to 5.30

/cc @amyblais 

#### Ticket Link
NONE

#### Release Note

```release-note
db: upgrade db to 5.30
```

### CODE REVIEW

**Comment by amyblais** [comment]
@jespino @hmhealey Please help prioritize reviews so we can add this to v5.30 when the branch is cut.

**Review by hmhealey — APPROVED** [review]

**Review by jespino — APPROVED** [review]

**Comment by amyblais** [comment]
@cpanato Ready to merge,

**Comment by cpanato** [comment]
the code is already in the release branch, no cherry pick needed

**Pull request merged**
