### PR TITLE
Fix empty string comparison issues in the codebase

### PR DESCRIPTION
**Pull request by madhavhugar**
#### Summary

See the issue for details

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/16674

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by madhavhugar** [comment]
@agnivade I force pushed a change. Would that be a problem? not sure why the build fails with `build - Unauthorized`

**Comment by agnivade** [comment]
I would assume it's because you are touching the Makefile. Can you remove the bit from the Makefile and update the PR? A staff member can send an upstream PR to finally make the Makefile change.

**Review by agnivade — APPROVED** [review]
Great work!

**Review by streamer45 — APPROVED** [review]
Thank you @madhavhugar , very nice work on this :+1:

**Pull request merged**
