### PR TITLE
Do not send categories for teams deleted or not member of

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
We used to send the categories for teams deleted or not a member of when we use the "exclude" option. This fixes that.

#### Ticket Link
None

#### Release Note
```release-note
Get categories with the "exclude" option does not return categories for deleted or teams you are no longer a member.
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Seems like some tests are failing due to this? Wondering if this was intentional? If not, then we'd need to change the tests as well.

cc @hmhealey for thoughts.

**Comment by hmhealey** [comment]
Back when I wrote the original version, I think a team ID was required and there wasn't any options for getting multiple teams at once. Since the client never requested categories for deleted teams, the query didn't need to care about it

**Comment by agnivade** [comment]
Makes sense. @larkox - would you mind fixing the tests and perhaps adding a check to ensure that no deleted teams are returned by checking the `DeleteAt` field?

**Comment by agnivade** [comment]
Thanks, I am on PTO tomorrow. If it's urgent, please feel free to request @isacikgoz for a review.

**Review by agnivade — APPROVED** [review]
Thanks!

cc @agarciamontoro . This changes some SQL queries for sidebar categories. Just a headsup for your next load test in case this causes perf regressions.

I don't want to burden Daniel with running another load test, but just something for you to look into in case we see regressions.

**Comment by agarciamontoro** [comment]
Thanks for the heads-up, Agniva, I'll keep an eye out for this.

**Comment by larkox** [comment]
@agnivade I checked the e2e tests, and it seems it passed, but the report step failed. Is that expected? Is there anything I have to do on my side?

**Comment by agnivade** [comment]
Here is the report: https://mattermost-cypress-report.s3.amazonaws.com/247703-b96df1b-onprem-ent-server-pr-21038-mm-ee-test:b96df1b/mochawesome.html

I don't see any failures related to sidebar categories. So looks good.

**Pull request merged**
