### PR TITLE
[MM-49180] Error message not clear when creating group with mention name matching username

### PR DESCRIPTION
**Pull request by kostaspt**
#### Summary
The webapp is expecting an error with type `app.group.username_conflict` to show a related error message, while we didn't return any related errors for this case.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49180

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by plant99 — APPROVED** [review]

**Review by mkraft — CHANGES_REQUESTED** [review]
Looks good. Can we add a test for this?

**Review by furqanmlk — APPROVED** [review]
Working as expected with the following steps:
1. Login as sysadmin
2. Create `user-1`
3. Go to product menu > User Groups
4. Select `Create Groups`
5. Type `user-1` in `Name` field
6. Add some users in `Add People` field
7. Click `Create Group` button
Result: `A username already exists with this name. Mention must be unique.` is getting show in `mention` field.

**Before**

image

**After**

image

### **API**

**Before**
image

**After**
image

**Pull request merged**
