### PR TITLE
[MM-48391] Store the server info in the export version line

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
Currently the export files just contain a version number (which is always '1'). This PR adds additional info about the generator of the export file. One such line may look like this:
```
{"type":"version","version":1,"info":{"generator":"mattermost-server","version":"7.6.0 (29bb1e53ef5a439c73065f47de2972f9bbcb09a4, enterprise: true)","created":"2022-11-22T16:40:51.019582328+01:00"}}
```
The change is fully backwards compatible. The import currently ignores the info.
- `generator` holds a string containing the name of the tool used to create the export file.
- `version` contains a string with the version information. It should always start with a semantic version followed by a space (or the end of the string). This will allow us to determine the exact version the file with created with in case we find incompatibilities later.
- `created` contains a timestamp then this file was generated.
- `additional` (not in the example) may contain arbitrary data which may be used by tools to store additional info about the export, like statistical data. It must be valid JSON.

#### Ticket Link
[MM-48391](https://mattermost.atlassian.net/browse/MM-48391)

#### Release Note
```release-note
The export file now contains the server version and a creation timestamp
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 🌮 Neat!

**Review by agarciamontoro — APPROVED** [review]
Neat! The only ask I have is: if the generator can change, should we document somewhere how this should be done for other exporters?

**Comment by noxer** [comment]
Yes @agarciamontoro that sounds sensible. Shall we put it into https://docs.mattermost.com/manage/bulk-export-tool.html ?

I've made a small change, the `created` field is not just a string so decoding doesn't fail for an empty or malformed time.

**Comment by agarciamontoro** [comment]
> Shall we put it into https://docs.mattermost.com/manage/bulk-export-tool.html ?

Seems like a good place to me.

**Comment by cwarnermm** [comment]
Thank you, @noxer and @agarciamontoro, for updating the docs for this PR!

**Pull request merged**
