### PR TITLE
MM-48504: Bump dependencies

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-48504

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
@saturninoabril - can you check the [results](https://automation-dashboard.vercel.app/cycle/287227) once and confirm everything is as expected?

**Review by saturninoabril — APPROVED** [review]
Verified all tests and all good. Send separate PR to address several flaky tests - https://github.com/mattermost/mattermost-webapp/pull/11984

**Review by noxer — APPROVED** [review]

**Pull request merged**
