### PR TITLE
Pre-package Playbooks v1.22.1

### PR DESCRIPTION
**Pull request by lieut-data**
#### Release Note
```release-note
Pre-package Playbooks v1.22.1.
```

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-40108

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Comment by lieut-data** [comment]
@Phrynobatrachus, once this PR builds and sets up the cloud test server, would you be able to confirm that v1.22.1 is installed and available without further configuration required?

**Review by Phrynobatrachus — APPROVED** [review]
Screenshot from 2021-12-07 13-51-47

LGTM :+1:

**Comment by amyblais** [comment]
@lieut-data Is this needed for cloud (Dec 8th is last cloud release of 2021)?

**Comment by lieut-data** [comment]
@amyblais, it would indeed be great to avoid cloud getting behind the December self-managed release. Can you help include this in cloud?

**Pull request merged**
