### PR TITLE
Expose boards APIs for MPA

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR exposes the Boards product APIs to other products.  Includes a refactor of product initialization:
- Initializer is where a product adds its own APIs to the services map and remembers the built-in suite APIs
- `Start` is called with a fully populated services map; product API dependencies are remembered here and is any are missing the method errors.

This PR includes Boards as a Channels dependency.  This can be removed as its not strictly needed yet.

Corresponding Boards PR:  https://github.com/mattermost/focalboard/pull/4372

#### Ticket Link
NONE

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by wiggin77** [comment]
It's not picking up the identically named branch in the focallboard repo.  Argh.

**Comment by agnivade** [comment]
How come? How did Ibrahim's PRs work then?

**Review by isacikgoz — COMMENTED** [review]
API looks good, also passing services to the `Start()` method is also okay but if we remove the dependency resolution, we can't guarantee the init order of the products. I think that was a safety mechanism to ensure all dependent services are fulfilled. 

IMO, any service provided by other products (other than Channels) should be `nil` checked on use. Otherwise this will start to become convoluted process in a near feature. Alternatively we can just hardcode every initialization and force building boards with channels.

**Comment by wiggin77** [comment]
> I think that was a safety mechanism to ensure all dependent services are fulfilled.

Thanks @isacikgoz. The dependencies are still checked to ensure they are fulfilled, it just completes the check in 'start' instead of the initializer.  It still errors if any are missing.

**Comment by wiggin77** [comment]
> How come? How did Ibrahim's PRs work then?

I don't know.  I'll look into it in a few hours.

**Comment by isacikgoz** [comment]
> Thanks @isacikgoz. The dependencies are still checked to ensure they are fulfilled, it just completes the check in 'start' instead of the initializer. It still errors if any are missing.

Yeah but it doesn't retry to sort the sequence, the idea of handling these in initialization was enabling one way product to product dependency. At this point we have to hardcode the initialization sequence if I'm not missing something.

**Comment by isacikgoz** [comment]
I'm trying to say that product initialization is not ordered with your changes, it will randomly initialize the products due to random access on the `map`. We either need to hardcode it, or do some sort of dependency resolution (which was the case before this refactor).

**Comment by wiggin77** [comment]
> product initialization is not ordered with your changes

Before this change, product initialization was not really ordered, it was taking multiple passes until all the dependencies were fulfilled or retries was exceeded.  After the refactor initialization order doesn't matter because product APIs are not consumed in the initializer.  In `Start` the code to ensure Channels starts first is preserved.  We may need to build on this if the order Start is called matters for the rest of the products, but currently it doesn't.

**Comment by isacikgoz** [comment]
But product APIs could and should (to me) be consumed at initialization if they are mandatory for the product. All my refactor PRs recently was about ensuring any product other than Channels to get their required services at initialization. Why we are postponing consuming services to start phase? That's the point I couldn't get actually.

**Comment by wiggin77** [comment]
The refactor was reverted.

**Review by agnivade — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
Thanks @wiggin77 We can discuss further on a call if more refactor is required. This looks good to me 👍

**Pull request merged**
