### PR TITLE
[MM-31391]: Add connection idle timeout to DB config 

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary

This PR aims to solve #16601 

#### Ticket Link

Issue: #16601 
JIRA: https://mattermost.atlassian.net/browse/MM-31391

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Hey @haardikdharma10 - just ping me here whenever this is ready to review.

**Comment by haardikdharma10** [comment]
Hi @agnivade, All checks are passing and the PR is ready for review:)

**Comment by agnivade** [comment]
Amazing work @haardikdharma10 ! We'll also need the webapp changes side by side as we'd want merge both of them at once. It will be a bit tricky after that because we'd need both changes from both the repos to be working together, so a staff would need to send both of your changes to the upstream branch. But that comes after we have gone through the PRs. So let's work on the webapp changes first :)

**Comment by haardikdharma10** [comment]
> Amazing work @haardikdharma10 ! We'll also need the webapp changes side by side as we'd want merge both of them at once. It will be a bit tricky after that because we'd need both changes from both the repos to be working together, so a staff would need to send both of your changes to the upstream branch. But that comes after we have gone through the PRs. So let's work on the webapp changes first :)

I'll start working on it!

**Comment by agnivade** [comment]
Going to close this one and will create a PR directly as an upstream branch because we need to test both of them together.

**Pull request closed without merging**
