### PR TITLE
MM-20970 - Unnecessarily permissive file mode in server-local file storage

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
corrected file permissions for localstore
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20970

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @reflog - can you help with QA testing steps for this PR please?

**Comment by reflog** [comment]
@lindy65 - in the Jira ticket there are steps to confirm. Basically - newly created files in ./data folder should have proper permissions, so QA here should be done server-side

**Comment by amyblais** [comment]
@reflog FYI this PR hasn't been cherry-picked yet.

**Comment by reflog** [comment]
thanks @amyblais , will do it now

**Pull request merged**
