### PR TITLE
[MM-43785] Hide insights feature intro for new users

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
We don't want to overburden new users with tours and tips constantly so hide insights intro by default. It should only appear for existing users

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43785

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by plant99** [comment]
Looks good to me. Will wait for Circle CI run to finish before approving.

**Review by neallred — APPROVED** [review]
LGTM!

**Review by mkraft — APPROVED** [review]

**Review by plant99 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
As discussed with Ben,
Following two tests were verified

**Test Case 01**
1. Create server and enable Feature Flag ✔️ 
2. Add new user and login using new user ✔️ 
3. User should NOT see Insights feature intro ✅ 


**Test Case 02**
1. Disable insights Feature Flag ✔️ 
2. Create a new user and login  ✔️ 
3. Enable insights feature flag ✔️ 
4. Refresh page for logged in user ✔️ 
5. User should see Insight feature intro ✅

**Pull request merged**
