### PR TITLE
[MM-22831] nested config value setting using env vars

### PR DESCRIPTION
**Pull request by gabor-boros**
#### Summary

Configuring plugins using environment variables is not possible, however, if Helm charts are used, only environment variables could be used to configure Mattermost. ref: https://github.com/mattermost/mattermost-helm/pull/366

Since the environment variables cannot be used for that purpose, other community members has issues with enabling plugins using env vars too. ref: https://forum.mattermost.com/t/automatically-activate-plugin/6289/8

This PR resolves the issue by extending the environment configuration parsing to be able to parse JSON formatted aka. `map[string]interface{}` values.

Example configuration that was not parsed before this change:

```json
{
  "mattermost-autolink": {
    "links": [
      {
        "Pattern": "(?P<project>KEY)-(?P<id>\\d{1,6})(?P<comma>[,;]*)",
        "Template": "[$project-$id](https://example.atlassian.net/browse/$project-$id)$comma"
      }
    ]
  }
}
```

#### Ticket Link

* Mattermost Jira ticket: https://mattermost.atlassian.net/browse/MM-22831
* Discourse forum post: https://forum.mattermost.com/t/automatically-activate-plugin/6289/8

#### Release Note

```release-note
Added JSON-compatible nested config value parsing from environment variables.
```

### CODE REVIEW

**Comment by agnivade** [comment]
I believe this just adds support for passing the whole map as a string value. But the main challenge in https://mattermost.atlassian.net/browse/MM-22831 was that periods in map keys messed up when converted to the viper env var string. So while you can set the whole map object, you cannot do down arbitrary map structures and set a single key.

Solving that is tricky because you need to specially handle periods and recursively traverse maps.

More discussion here: https://community.mattermost.com/core/pl/b1cg9j8643fn3m9z6hzycgmr9h

cc @lieut-data

**Comment by gabor-boros** [comment]
@agnivade Ah, thanks for the clarification. It wasn't completely clear without the missing conversation you just linked.

Unfortunately, I do not have enough time to implement the traversal and individual field settings.

Even though it does not allow setting individual map fields, this would allow setting plugin configs for Helm charts using environment variables, which is better than nothing.

What do you think about that? Currently, it is not possible to set any plugin config using env vars, even if it would be the whole object.

**Comment by agnivade** [comment]
Yep, agree that it's better than nothing. Looks fine from my side. @lieut-data - I know you were involved in the original discussion. Any concerns with this PR?

**Review by lieut-data — APPROVED** [review]
Ah, interesting! If I parse correctly, I guess it's now possible to enable and configure plugins with the pair, `MM_PLUGINSETTINGS_PLUGINSTATES` and `MM_PLUGINSETTINGS_PLUGINS`, provided that these environment variables define the /full/ configuration for all required plugins?

That feels like a solid improvement, even if it's still cumbersome. Nice!

**Comment by gabor-boros** [comment]
> Ah, interesting! If I parse correctly, I guess it's now possible to enable and configure plugins with the pair, `MM_PLUGINSETTINGS_PLUGINSTATES` and `MM_PLUGINSETTINGS_PLUGINS`, provided that these environment variables define the /full/ configuration for all required plugins?

@lieut-data Although I couldn't build the server myself to try it in a production setup, based on the tests, yes.

**Comment by agnivade** [comment]
@isacikgoz - removing you since we already have an approval from Jesse.

**Pull request merged**
