### PR TITLE
[WebApp][MM-48061]: Allow CTRL/CMD + K to insert link formatting when text is selected 

### PR DESCRIPTION
**Pull request by kyeongsoosoo**
#### Summary

Previous WebApp PR: https://github.com/mattermost/mattermost-webapp/pull/12256
This PR only needs to go through the QA stage.

This PR resolves two issues.

If the user hits CTRL/CMD + K then add the markdown link formatting (same as if they hit CTRL + Alt + K).
If the clipboard contains a URL beginning with http:// or https:// and the user pastes, format it as a markdown hyperlink with the selected text.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/21575

#### Release Note

```release-note
Allow CTRL/CMD + K to insert link formatting when text is selected
```

### CODE REVIEW

**Comment by kyeongsoosoo** [comment]
@furqanmlk I opened a new PR. Could you please check?

**Review by furqanmlk — APPROVED** [review]
Working as expected.

**Comment by kyeongsoosoo** [comment]
@AshishDhama I think the process is completed, could you check it out?

**Comment by AshishDhama** [comment]
@kyeongsoosoo Sorry for the delay, could you please fix the coflicts.

**Comment by kyeongsoosoo** [comment]
@AshishDhama  Conflicts resolved :)

**Review by AshishDhama — APPROVED** [review]

**Comment by AshishDhama** [comment]
> @AshishDhama There is a server creation failure similar to the pr I opened recently(#23117) It’s been solved after updating my fork's branch. So I think this would have been fixed, too. Could you check it out?

Yeah, same issue

**Comment by kyeongsoosoo** [comment]
> Yeah, same issue
Thanks. I think only e2e test is left as the last step, could you trigger it?

**Pull request merged**
