### PR TITLE
Fix ResetLastPictureUpdate flaky test

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

The test performs two sequential operations that update the `UpdateAt` field of a user record. An assertion expects the time to be different after the second operation, but if it has not been 1 millisecond since the last call to `model.GetMillis()` then the `UpdateAt` will not change.

~~This PR puts a small wait in the test so that the second operation will not set the same value for `UpdateAt`. I chose `10 ms` because that is what all other similar `Sleep` calls are using in this file.~~
I've changed all similar sleeps in this file to be `1 ms`.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-26204

### CODE REVIEW

**Comment by mickmister** [comment]
@agnivade Agreed, thanks for the link. All other sleeps have been changed to reflect this.

**Comment by agnivade** [comment]
@lindy65 - No need for QA on this one. Yet another flaky test fix.

**Comment by agnivade** [comment]
@mickmister - I'm going to merge this myself as this is failing a lot of CI builds. Sorry about that.

**Comment by mickmister** [comment]
@agnivade No problem!

**Pull request merged**
