### PR TITLE
MM-44410 Add subresource integrity

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Adding subresource integrity to the graphqli html.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44410

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Lol ignore my previous comment. Catching up on my review queue :)

**Review by agarciamontoro — APPROVED** [review]
:tada:

**Comment by amyblais** [comment]
@crspeller Is this needed for v7.0?

**Pull request merged**
