### PR TITLE
fix issue #8605

### PR DESCRIPTION
**Pull request by qichengzx**
#### Summary
check if username and nickname is system when update user info

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/8605

### CODE REVIEW

**Comment by jasonblais** [comment]
@qichengzx Thanks for the PR! We'll discuss this with our team.

One question: Is this validated if you try to set your username/nickname to `system`, but not otherwise? Just want to make sure existing users wouldn't be affected.

**Comment by qichengzx** [comment]
@jasonblais yes , I tested it, will not affect existing users .

**Comment by tanskann** [comment]
In Russian translation "System" `system.message.name` is translated as система so this PR wouldn't fix that.

**Comment by qichengzx** [comment]
@jasonblais  I know what tanskann mean，but this will deal with much more languages. Maybe need a more specific plan ？such like add all language word to i18n folder?

**Comment by jasonblais** [comment]
@qichengzx I really apologize for my late reply here.

> such like add all language word to i18n folder?

That would make sense to me. Would you be able to help with that change, or should I create a separate issue for it? I'm okay creating a separate issue given it's out of scope of the original help wanted ticket.

> check if username and nickname is system when update user info

Right now we only restrict the username field, and not nickname. Why do you feel restricting the nickname is also important?

**Comment by qichengzx** [comment]
@jasonblais Yes, I think I'm ok to do that but for now I don't have a clear idea.
about nickname, I think maybe it's important too.

**Comment by jasonblais** [comment]
@qichengzx @tanskann Two things that I thought about, which I'd be curious to hear your thoughts on:

1) I'm not sure how the localization would work system-wide. For instance, suppose we have languages set for the following users like this:
 - user 1: English
 - user 2: Russian
 - user 3: Spanish

Should all variations of `system` be restricted? That may seem confusing to the user.

2) You can also overwrite the username with integrations, and I'm not aware of a good way to restrict usernames for that case.

**Comment by qichengzx** [comment]
@jasonblais  How about if we only restrict the Mattermost system language's username.

**Comment by jasonblais** [comment]
@qichengzx Good suggestion - would this also work for integrations, for instance webhooks?

**Comment by jasonblais** [comment]
@qichengzx I still have worries about the approach, given that `System` is dependent on the user's account settings, not the system language. For instance, in the attached case the system langauge is English but my account setting is Spanish.

image

I've pinged our team for their thoughts on this as well. Really appreciate your continued help here! :)

**Comment by tanskann** [comment]
@jasonblais I would only restrict nicknames. Usernames may indeed come from some integration and restricting that might create unnecessary problems for users. And if administrator chooses she can restrict free picking of username.

About the languages, maybe `System` should indeed always be `System` and should not be translated. 

BTW, closing the issue and tracking this issue is not a very good workflow. All this discussion should happen on #8605 and not on this PR.

**Comment by jasonblais** [comment]
Does that sound good to you too @tanskann?

**Comment by tanskann** [comment]
@jasonblais sorry for the delay. That indeed sounds good.

**Comment by jasonblais** [comment]
Thanks @qichengzx @tanskann! Really great discussion here, and appreciate your feedback.

I'll close this PR and we'll track the issue with https://mattermost.atlassian.net/browse/MM-10554

**Pull request closed without merging**
