### PR TITLE
GH-19148: lower case column names in the application level

### PR DESCRIPTION
**Pull request by SharathHuddar**
#### Summary
lower case column names in the application level

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/19148

#### Release Note
```release-note
Convert column name and table name to lower case at the application level
```

### CODE REVIEW

**Comment by SharathHuddar** [comment]
@agnivade can you please take a look at this one ?

**Review by agnivade — COMMENTED** [review]
Looks like a good start @SharathHuddar. Can you try to add a test to this? Have a look at `TestAlterDefaultIfColumnExists` in store_test.go for something similar. We would want to change the charset of the database, recreate it, and run the `GetColumnInfo` method.

Mainly I want to confirm how the information_schema.columns view stores its data.

**Comment by SharathHuddar** [comment]
@agnivade I'm not sure how to re-create a DB from the test case. Also, wouldn't recreating the DB make the test case slow ?

**Comment by agnivade** [comment]
> I'm not sure how to re-create a DB from the test case. 

You'll have to go through the codebase a bit more to see how we are setting up the DB and the tables. Take a look at `MakeSqlSettings` in storetest/settings.go. That's responsible for creating the database. We want to extend that to be able to specify the charset.

Then from inside the test, you need to drop the DB and create a new one.

>  Also, wouldn't recreating the DB make the test case slow ?

Our first objective is to write a test, and then improve performance. :) In the larger scheme of things, every package runs its tests in parallel. So the whole runtime is dictated by the package taking longest - which is api4 right now.

**Comment by SharathHuddar** [comment]
@agnivade sounds good. Is there a list of char sets that we need to support in `MakeSqlSettings` ?

**Comment by agnivade** [comment]
We can start with UTF-8 and ISO-8859-9.

**Comment by isacikgoz** [comment]
Hi @SharathHuddar, big thanks for your contribution! There hasn't been recent activity on this PR so I've marked it as inactive. Following our [inactive contribution process](https://developers.mattermost.com/contribute/getting-started/inactive-contributions/), the PR is now closed due to 30 days or more of inactivity.

However, if you're still interested working on the changes, let us know! Note that we [merged multiple repositories into one monorepo](https://github.com/mattermost/mattermost-server/issues/22420), which may require you to resubmit the changes. 

If you have any questions, don't hesitate to let us know, we're happy to help.

**Pull request closed without merging**
