### PR TITLE
[MM-41956] Unique name error on update

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Sending back the correct error ID so we can display the proper message on the frontend.
```
id: "app.custom_group.unique_name"
```

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-41956

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mkraft — CHANGES_REQUESTED** [review]
If no test fail because of this change then we're missing a unit test.

**Comment by BenCookie95** [comment]
> If no test fail because of this change then we're missing a unit test.

Updated store test

**Review by mylonsuren — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]

**Pull request merged**
