### PR TITLE
Document sqlTeamStore GetAll methods

### PR DESCRIPTION
**Pull request by FlaviaBastos**
#### Summary
Documenting 'sqlTeamStore' GetAll methods

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/14008

JIRA: [JIRA: https://mattermost.atlassian.net/browse/MM-22998](https://mattermost.atlassian.net/browse/MM-22998)

### CODE REVIEW

**Comment by agnivade** [comment]
@lindy65 - This should not need any tests as this is just a documentation addition. Let me know your thoughts :)

**Comment by teresa-novoa** [comment]
_"This PR needs to sync and merge"?_ @jespino will that be you?  Thanks!

**Comment by jespino** [comment]
@teresa-novoa yes, I can take care of this :). Thanks for the heads up.

**Pull request merged**
