### PR TITLE
[GH-18306] Make getPrepackaged resilient to missing plugin icons

### PR DESCRIPTION
**Pull request by namreg**
#### Summary

Make getPrepackaged resilient to missing plugin icons

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/18306

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Review by cpoile — APPROVED** [review]

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @namreg

**Comment by lieut-data** [comment]
@cpoile, is this one ready to be merged, or are we blocked on something?

**Comment by namreg** [comment]
Is there anything I need to do?

**Comment by lieut-data** [comment]
Sorry about the delay merging, @namreg -- nothing for you to do. We'll take care of resolving this :)

**Comment by lieut-data** [comment]
Thanks again, @namreg!

**Pull request merged**
