### PR TITLE
Use different user-agent for twitter links

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Twitter doesn't send Open Graph data for most user agents. But there are a couple of ones where they send the data. `facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)` is one of these.

By proofing to use that user agent twitter link preview work again.

I thought about adding a test, but that will break as soon as Twitter changes what user ages they accept.

I changed to signature of `MakeTransport` to return the actual implementation, which agiles with Go's rule of accepting interfaces and returning concrete types.

For more details please see https://community.mattermost.com/core/pl/oyf6memfsprdzr9xkd9iahibea

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-25940

#### Release Note

```release-note
Fix broken link preview for twitter links
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by hanzei** [comment]
Swapping out @larkox for @levb

**Review by levb — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thank you @hanzei 
Tested, looks good to merge.
- Verified tweeter links have a preview box.

**Comment by amyblais** [comment]
@hanzei I removed v5.30 fix version from a few PRs based on https://community-release.mattermost.com/core/pl/qwq65andnibdtjwk5e1tjftiur. Concerns can be raised to me

**Pull request merged**
