### PR TITLE
fix issue with card id being valid block but not card

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Fixes issue where bad board link can cause issue with displaying channels.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-51713

#### Release Note
```release-note
Fixes issue with bad board link 
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by crspeller — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Hi @sbishel - I've requested @oh6hay to QA review this on my behalf on the linked Jira

**Review by oh6hay — APPROVED** [review]
+1

**Pull request merged**
