### PR TITLE
[MM-51922] Enforce minimum 10 seats in seats selector

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
This enforces a minimum of 10 seats OR the current number of licensed users - whichever is greater. The minimum 10 seat count error will show until the seat count exceeds 10 - at which point if the user is still below their current user count, they'll get the existing error.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51922

#### Screenshots
image

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by neallred — DISMISSED** [review]
LGTM, thanks @nickmisasi !

**Review by neallred — APPROVED** [review]

**Review by neallred — APPROVED** [review]

**Review by marianunez — APPROVED** [review]
Code LGTM 👍 

From a UX perspective, if they have less than 10 users when they go to subscribe they are shown the error message as soon as they open the modal. Should we default to 10 instead so they don't start in an error state? @annelieseklein thoughts? 
Screen Shot 2023-04-12 at 7 13 55 PM

**Review by yasserfaraazkhan — APPROVED** [review]
thank you @nickmisasi 
the message appears if seats are below 10.

Screenshot 2023-04-13 at 5 10 15 PM

**Comment by annelieseklein** [comment]
> Code LGTM 👍
> 
> From a UX perspective, if they have less than 10 users when they go to subscribe they are shown the error message as soon as they open the modal. Should we default to 10 instead so they don't start in an error state? @annelieseklein thoughts? Screen Shot 2023-04-12 at 7 13 55 PM

I think the user should enter "10" themselves otherwise they may not even look and just assume it has their current number. we may get messages of people accidentally purchasing 10, when they meant to do just 1. 

@marianunez what was the reasoning again for requiring a min of 10 seats for pro annual?

**Comment by marianunez** [comment]
> @marianunez what was the reasoning again for requiring a min of 10 seats for pro annual?

@annelieseklein this is the minimum amount of seats for cloud to be cost effecitve and also aligns with the min required for self-hosted license

**Pull request merged**
