### PR TITLE
api4/system: adjust permissions for applied schema migrations

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Adjust the permission requirement to be similar with other system console permission levels.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42573

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Can we add a quick test?

**Review by agnivade — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected. E2E Passed

image

image

image

**Comment by amyblais** [comment]
@isacikgoz May need a manual cherry-pick to ``cloud``.

**Pull request merged**
