### PR TITLE
[MM-47805] Remove CRT feature flag

### PR DESCRIPTION
**Pull request by vish9812**
#### Summary

Remove the CRT feature flag given it’s out in GA and stable.

#### Ticket Link

JIRA - https://mattermost.atlassian.net/browse/MM-47805

#### Related Pull Requests

- WebApp - (https://github.com/mattermost/mattermost-webapp/pull/11706)
- Mobile - (https://github.com/mattermost/mattermost-mobile/pull/6848)

#### Release Note

```release-note
Removed the CRT feature flag.
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Comment by vish9812** [comment]
@jgilliam17 I've updated the webApp PR, so it should be fixed now.

**Comment by jgilliam17** [comment]
Thanks @vish9812 
Tested, looks good to merge with one comment
[E2E report](https://mattermost-cypress-report.s3.amazonaws.com/275261-904f306-onprem-ent-server-pr-21788-mm-ee-test:904f306/mochawesome.html) shows one test failing relating to CRT. MM-T4144_1 can you please take a look?

**Review by jgilliam17 — APPROVED** [review]
Thanks @vish9812 
Verified flag is removed and remaining System Console options for CRT.
Looks good to merge.

**Comment by jgilliam17** [comment]
@vish9812 please merge both PRs in order you see fit. Thanks 🙂

**Pull request merged**
