### PR TITLE
[WIP] Add command to modify outgoing webhooks

### PR DESCRIPTION
**Pull request by wgfm**
#### Summary
This PR implements a command to modify outgoing webhooks.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/9668

### Outstanding questions
There's a --title flag in the proposed command - should this map to DisplayName?
The --url flag does not seem to have a direct mapping. Is it related to CallbackURLs somehow?
--trigger-in also does not seem to have a direct mapping.

For --trigger-words, I wonder why a newline was chosen as a separator

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by jasonblais** [comment]
@grundleborg Would you be able to help with the community member's outstanding question?

**Comment by wgfm** [comment]
I would like some answers to my questions, so I can proceed with this pull request. I fully understand if you're busy, of course.

**Comment by grundleborg** [comment]
HI @wgfm  - really sorry about how long it took me to reply to your questions. Here are the answers:

1. `--title` does indeed map to the `DisplayName` field.
2. For `--url` - that's a really good question. I think the person who created the ticket missed that this was a string list. For now, I think that field should just replace the values of the `CallBackURLs` field with the one provided on the CLI, but we should think about a better way to do this with explicit support for multiple URLs.
3. `--trigger-in` is a channel I think.

**Comment by wgfm** [comment]
Hi @grundleborg, thanks for your reply, and sorry for my own late reply. I will be able to handle `--url` and `--title` now, but `--trigger-in` is still unclear to me. There is a `ChannelId` field in the `OutgoingWebhook` struct, but it's already mapped to the `--channel` argument. Are these two arguments duplicates of each other?

There _is_ a `TriggerWhen` integer field, but I don't know what it's purpose is.

**Comment by grundleborg** [comment]
Bringing in @jespino to help answer questions here now he's back, as he originally created the ticket :)

**Comment by jespino** [comment]
@wgfm Sorry the delay, I was in my parental leave.

About the `--url`, I would propose to use `StringArray` flag type which will accept multiple `--url` flags, like `mattermost webhook modify-outgoing xxxxxxx --url url1 --url url2 --url url3`.

About the `--trigger-in`, I think was a typo (sorry about that), it would be `--trigger-when` which correspond to the `TriggerWhen` field in the outgoing webhook which value must be 0 or 1 (in the code, but must be something different in the cli interface). The values 0 and 1 are, `TRIGGERWORDS_EXACT_MATCH == 0` and `TRIGGERWORDS_STARTS_WITH == 1`.

And yes, the `--title` is the `displayName`.

**Comment by wgfm** [comment]
I'm sorry for ghosting. I do not have the time to finish this pull request at the moment, so I will close it for now. Thanks for taking the time to answer my questions, it will help the next person implementing this feature.

**Comment by hanzei** [comment]
Thanks for the time and effort you put into this @wgfm!

**Pull request closed without merging**
