### PR TITLE
MM-49679 - Prepackage calls 0.13.0

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Calls -> v0.13.0

/cc @amyblais

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-49679

#### Release Note
```release-note
Prepackage Calls version v0.13.0
```

### CODE REVIEW

**Comment by cpoile** [comment]
I'll do QA review

**Review by streamer45 — APPROVED** [review]
Thanks!

**Review by mickmister — APPROVED** [review]

**Comment by cpoile** [comment]
It installs, good to go.

**Comment by cpoile** [comment]
@amyblais I'm a little unsure about what's releasing this time -- can you add the labels and cherry picks as needed? Then I'll merge. Thanks

**Comment by amyblais** [comment]
Just v7.8.0 👍

**Pull request merged**
