### PR TITLE
re-enabling TestSendMailUsingConfigAdvanced

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
re-enabling the TestSendMailUsingConfigAdvanced test

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/MM-9705

### CODE REVIEW

**Comment by jwilander** [comment]
It seems to pass fine on the jenkins machines that run on the slaves but when it runs on the master node it fails and that's where the release builds run

**Comment by cpanato** [comment]
We should not run anything on master. only on slaves.

I will take a look on that

**Comment by cpanato** [comment]
ok, ran on master. the issue was we were using a wrong tag from `inbucket` was set to latest and latest is not the better tag to use. We are using `release-1.2.0` so I set the master to use that.

test passed on master:
```
=== RUN   TestSendMailUsingConfigAdvanced
{"level":"debug","msg":"sending mail to test2@example.com with subject of 'Testing this email'"}
--- PASS: TestSendMailUsingConfigAdvanced (0.02s)
PASS
ok      github.com/mattermost/mattermost-server/utils   0.026s
```

**Comment by cpanato** [comment]
PTAL @jwilander @lieut-data

**Pull request merged**
