### PR TITLE
Added log Message in Makefile

### PR DESCRIPTION
**Pull request by 0xrishabh**
Related to https://github.com/mattermost/mattermost-server/issues/17433

Now the process of running the server is done in two stages as suggested in the issue thread.
- First, the binary is built and stored in bin/ 
- Then it's invoked with proper logging

### CODE REVIEW

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @0xrishabh

**Review by wiggin77 — CHANGES_REQUESTED** [review]
@0xrishabh will you be able to sign the CLA?  Merging is blocked until then.

**Comment by 0xrishabh** [comment]
> @0xrishabh will you be able to sign the CLA? Merging is blocked until then.

Yes, can you direct me on how to do it?

**Comment by roointan** [comment]
> > @0xrishabh will you be able to sign the CLA? Merging is blocked until then.
> 
> Yes, can you direct me on how to do it?

@0xrishabh 

I think these can help with signing the CLA: https://developers.mattermost.com/contribute/getting-started/contribution-checklist/ and https://mattermost.com/mattermost-contributor-agreement/

**Comment by isacikgoz** [comment]
Hi @0xrishabh, big thanks for your contribution! There hasn't been recent activity on this PR so I've marked it as inactive. Following our [inactive contribution process](https://developers.mattermost.com/contribute/getting-started/inactive-contributions/), the PR is now closed due to 30 days or more of inactivity.

However, if you're still interested working on the changes, let us know! Note that we [merged multiple repositories into one monorepo](https://github.com/mattermost/mattermost-server/issues/22420), which may require you to resubmit the changes. 

If you have any questions, don't hesitate to let us know, we're happy to help.

**Pull request closed without merging**
