### PR TITLE
Change bulk export order to export emoji last

### PR DESCRIPTION
**Pull request by svelle**
Exporting emoji is possibly the least important step in the process, however it can very well cause the whole export to crash if there's anything wrong with the emoji directories (emojis deleted, export started from the wrong directory, etc.).
Changing the order of the export to export the emoji last is a simple yet effective workaround, imo, to prevent hours of exporting to be needed to run again as a lot of customers that ran into this issue cared little about custom emoji in comparison to having all their messages exported correctly without interruptions.

From what I could tell there's no need to adjust any tests as they don't test the order of operation only the specific exports.

### CODE REVIEW

**Review by jespino — DISMISSED** [review]
Looks good to me.

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by isacikgoz** [comment]
@furqanmlk one or two export runs should be enough to verify this change. @svelle GitHub conflict resolver messed up with `gofmt` and I don't have access to update the PR, can you please pull the recent changes and run `gofmt -s -w ./app/export.go` to fix the issue?

**Comment by furqanmlk** [comment]
@isacikgoz Did you have a chance to look at the issue I sent over chat.

**Comment by isacikgoz** [comment]
@furqanmlk Finally had the chance to debug the issue, it seems like the error occurs while importing and it's also happening in `master`. Created the ticket: https://mattermost.atlassian.net/browse/MM-38759 The issue is not related with this PR. But we can wait until that bug is resolved.

**Comment by furqanmlk** [comment]
> @furqanmlk Finally had the chance to debug the issue, it seems like the error occurs while importing and it's also happening in `master`. Created the ticket: https://mattermost.atlassian.net/browse/MM-38759 The issue is not related with this PR. But we can wait until that bug is resolved.

Thanks @isacikgoz 👍 
Sure, we will wait

**Comment by isacikgoz** [comment]
Hi @svelle, Note that we [merged multiple repositories into one monorepo](https://github.com/mattermost/mattermost-server/issues/22420) which may require you to resubmit these changes. I'm closing in the favor of reducing load on mattermod. Also the CI checks should run on our new pipelines. You can update the branch and re-open if you feel necessary.

**Pull request closed without merging**
