### PR TITLE
Add `from_plugin` and `from_oauth_app` props to posts created by plugins and OAuth apps

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

The Insights feature has run into an issue where posts are being counted, even though the posts are not being created by actual users. This PR makes it so posts being created by plugins are marked with a `from_plugin` prop, and posts made with an OAuth token are marked with a `from_oauth_app` prop.

This is to make it so we can filter out the following posts in the Insights feature. The follow up PR for this is here https://github.com/mattermost/mattermost-server/pull/20943

- A post made using an OAuth token
- A post made by a bot user
- A post made using the plugin API
- A post made from an incoming webhook
- A post made from a slash command response

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-45908
https://mattermost.atlassian.net/browse/MM-45734
https://mattermost.atlassian.net/browse/MM-41270

#### Release Note

```release-note
Added `from_plugin` and `from_oauth_app` prop to posts created by integrations
```

### CODE REVIEW

**Comment by mickmister** [comment]
@mkraft Note that this PR contains no changes to the logic of the Insights feature. Do you know where the change needs to go to factor in this new `from_integration` prop?

**Review by mkraft — COMMENTED** [review]
I understand adding the prop for calls to `(*PluginAPI).CreatePost` but I'm not clear on the need for adding the prop in cases where we already have `from_webhook` or `from_bot`. Could you remind me?

**Comment by mickmister** [comment]
@mkraft The idea is to add the `from_integration` prop when the post is made by any type of integration. Alternatively, we can use `from_plugin` and `from_oauthapp` (or `from_oauth_app`) for the places that are not already covered, and not introduce a `from_integration` prop. If we were to only apply the `from_integration` prop to a subset of places where posts are made by integrations, we could cause more confusion than is already there with the existing props.

Having the props be more granular makes more sense I think. I'll make the change to use `from_plugin` and `from_oauth_app`, and remove the `from_integration` prop. Does this make sense to you?

**Comment by mickmister** [comment]
@mkraft The PR is now updated to use `from_plugin` and `from_oauth_app`, in order to avoid adding props in cases already handled that have `from_webhook` and `from_bot` props added

**Comment by mkraft** [comment]
> @mkraft The PR is now updated to use `from_plugin` and `from_oauth_app`, in order to avoid adding props in cases already handled that have `from_webhook` and `from_bot` props added

Looks good to me. 

If necessary, in the future we can consider a migration to a single JSON key, like `"source"`, with values `"oath"`, `"webhook"`, or `"bot"` if it opens us to more efficient JSON indexes.

**Review by mkraft — APPROVED** [review]

**Review by ashishbhate — APPROVED** [review]

**Comment by DHaussermann** [comment]
Tested and working. I can see the props for `from_oauth_app": "true"` and `"from_plugin": "true"` now being added. 
Running E2E tests and will approve if nor failures seem related.

**Review by DHaussermann — APPROVED** [review]
Tested and passed

The change is functional and no relevant E2E failures were found.

LGTM!

**Comment by mickmister** [comment]
Closing due to these changes already existing in https://github.com/mattermost/mattermost-server/pull/20943

**Pull request closed without merging**
