### PR TITLE
Revert "Move config store into Platform Service"

### PR DESCRIPTION
**Pull request by amyblais**
Reverts mattermost/mattermost-server#20718

### CODE REVIEW

**Comment by agnivade** [comment]
@amyblais - can you point me to the context behind the revert? I might have missed it.

**Comment by isacikgoz** [comment]
@agnivade the context is here: https://community.mattermost.com/core/pl/3he6buddnjbkfnyxo37pjxorjh and the issue is this: https://mattermost.atlassian.net/browse/MM-46426

**Comment by agnivade** [comment]
Thanks :)

**Pull request closed without merging**
