### PR TITLE
[MM-34303] Add team ID to response when linking a channel to a group

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
When we add a channel to a group and then remove the team from the group, redux was unable to remove channels associated to that team because the state had no team information for each team. This adds the team ID to the response when linking a channel to a group.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34303

#### Release Note
```release-note
Added a new field, team_id, to the response of POST api/v4/groups/{group_id}/channels/{channel_id}/link
```

### CODE REVIEW

**Review by mkraft — COMMENTED** [review]
Are there any tests that can be updated to reflect these changes?

**Review by mkraft — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Review by furqanmlk — APPROVED** [review]
Tests passed ✅

**Pull request merged**
