### PR TITLE
Migrate CommandWebhook.TryUse to sync by default

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-16787

### CODE REVIEW

**Comment by rvillablanca** [comment]
Conflicts were resolved :upside_down_face:

**Comment by rvillablanca** [comment]
I think this doesn't have conflicts now, they were resolved previously

**Comment by jespino** [comment]
@rvillablanca We have a check for the PRs to not allow merge PRs that are "a bit far" from the master branch, but don't worry, I already merged it :)

**Comment by rvillablanca** [comment]
Yes but when I do a merge it shows me `Already up to date.`

```bash
rodrigo@asus:~/go/src/github.com/mattermost/mattermost-server (11541-CommandWebhook.TryUse)$ git fetch origin 
rodrigo@asus:~/go/src/github.com/mattermost/mattermost-server (11541-CommandWebhook.TryUse)$ git merge origin/master 
Already up to date.
```
:thinking:

**Comment by jespino** [comment]
I have updated it, maybe you have pulled my merge commit already.

**Pull request merged**
