### PR TITLE
Remove Webapp Build Hash

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
A discrete webapp build hash is no longer needed with the mono-repo.
image

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-51741

#### Release Note
```release-note
Remove Webapp Build Hash since now identical to Server Build Hash
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM 👍

**Review by hmhealey — APPROVED** [review]

**Comment by lieut-data** [comment]
Deferring QA as I've tested the feature with the test server above. Will wait for e2e results and then merge.

**Comment by lieut-data** [comment]
@lindy65, there's a lot of test failures here that don't seem related to my PR. Any advice on how to proceed?

**Comment by lindy65** [comment]
> @lindy65, there's a lot of test failures here that don't seem related to my PR. Any advice on how to proceed?

Hey @lieut-data I'm going to have to ask for help on the failing E2Es from @saturninoabril or @furqanmlk 

I also tested on the spinwick and the WebApp Build Hash has been removed. Please add milestone to the PR and Fix Version to the Jira ticket :)

**Comment by saturninoabril** [comment]
@lindy65 The easiest would be to compare to the recent run against master - https://automation-dashboard.vercel.app/cycles/25b2a206-a301-4924-a53c-a7dcbf7a8e66.

We're still in the process of cleaning up all the failed tests and will come up with the manageable result soon.

**Comment by lindy65** [comment]
@lieut-data I checked this PRs E2E test run against `master` and failing tests are the same - don't seem to have anything to do with your PR.  

> We're still in the process of cleaning up all the failed tests and will come up with the manageable result soon.

**Comment by lieut-data** [comment]
@amyblais, I'd propose we include this with cloud when we first ship monorepo in a few weeks, underscoring that webapp is no longer separately versioned. Thoughts?

**Comment by amyblais** [comment]
@lieut-data Feel free to cherry-pick to ``cloud`` branch.

**Comment by lieut-data** [comment]
Manually cherry-picked and pushed to `cloud`.

**Pull request merged**
