### PR TITLE
MM-46871: Add remining search parameters to be escaped

### PR DESCRIPTION
**Pull request by agnivade**
The first try wasn't exhaustive. I was planning to use
https://github.com/mattermost/mattermost-server/blob/1f933263e76739e4e3f089b6cefbdbeb41dd29e4/store/sqlstore/post_store.go#L1738-L1748 for this
but it also contained `@` which we don't want.

In the end, I just used a separate slice for all
the characters to be escaped.

https://mattermost.atlassian.net/browse/MM-46871

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@noxer - I went with the simple approach. I think it should be fine for our purposes.

**Review by streamer45 — APPROVED** [review]

**Review by noxer — APPROVED** [review]

**Comment by agnivade** [comment]
e2e [results](https://mattermost-cypress-report.s3.amazonaws.com/239160-4903ebf-onprem-ent-server-pr-20963-mm-ee-test:4903ebf/mochawesome.html) look good. Merging.

**Pull request merged**
