### PR TITLE
[MM-12374] Add command to move webhook from one team to another

### PR DESCRIPTION
**Pull request by checkaayush**
#### Summary
Add command to move webhook from one team to another

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/9769
https://mattermost.atlassian.net/browse/MM-12374

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Added API documentation (required for all new APIs) (PR: https://github.com/mattermost/docs/pull/2609)

### CODE REVIEW

**Comment by hanzei** [comment]
@checkaayush let me know when this is ready for review

**Comment by hanzei** [comment]
@checkaayush Is this ready for review?

**Comment by hanzei** [comment]
@checkaayush Three tests are failing: https://build.mattermost.com/blue/organizations/jenkins/mp%2Fmattermost-server-pr-new/detail/PR-10489/22/tests

**Comment by jasonblais** [comment]
Hey @checkaayush, just touching base to see if you have any questions about above? Would be happy to help with the unit tests.

**Comment by checkaayush** [comment]
Hey @jasonblais, I was stuck at this: https://github.com/mattermost/mattermost-server/issues/9769#issuecomment-477104983. 

Didn't get the confirmation on what was the expected behavior: https://github.com/mattermost/mattermost-server/issues/9769#issuecomment-479853721.

Could you take a look at it?

**Comment by jasonblais** [comment]
Thank you @checkaayush for reaching out. Katie helped respond at https://github.com/mattermost/mattermost-server/issues/9769#issuecomment-490589778, let me know if this is helpful?

**Comment by hanzei** [comment]
Hey @checkaayush,

Just want to check if Katies comment helped with resolving the confusion about what the command should do? Do you have any other questions?

**Comment by hanzei** [comment]
This PR has become orphaned and will be closed. Still, thanks for your contribution @checkaayush. Feel free to reopen, if you want to continue working on this.

**Pull request closed without merging**
