### PR TITLE
Inline ThreadStore.MarkAllAsUnreadByTeam

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
The query to `MarkAllAsUnreadByTeam` first fetched all thread memberships, then fed just the ids back to a second query to ensure all are marked as unread. Optimize this by simply doing a single `UPDATE` query with the necessary joins.

#### Ticket Link
None.

#### Release Note
```release-note
Optimize ThreadStore.MarkAllAsUnreadByTeam
```

### CODE REVIEW

**Comment by lieut-data** [comment]
Building this off https://github.com/mattermost/mattermost-server/pull/20915 to take advantage of the denormalized `TeamId` there, but also to avoid adding something which will need to be updated once that PR goes on.

**Review by iomodo — APPROVED** [review]
Looks great!

**Review by ashishbhate — APPROVED** [review]
Nice!

**Comment by lieut-data** [comment]
@Phrynobatrachus, could I get your help kicking off an e2e run for this PR?

**Review by Phrynobatrachus — APPROVED** [review]

**Pull request merged**
