### PR TITLE
Duplucate test scenario fix

### PR DESCRIPTION
**Pull request by Quaqmre**
#### Summary
Duplucated test case fix , 2 times testing Mysql prefix in config package

#### Ticket Link
 N/A 

```release-note
Test case checks sould check the Mysql and Postresql prefix
```

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1: Thanks @Quaqmre!

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @Quaqmre! :tada:

**Comment by jespino** [comment]
QA not needed because it only changes the unit tests.

**Pull request merged**
