### PR TITLE
[MM-52164]

### PR DESCRIPTION
**Pull request by vish9812**
#### Summary

Use StringBuilder.

#### Ticket Link

JIRA - https://mattermost.atlassian.net/browse/MM-52164

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
I am not sure what is the problem we are trying to solve here. `strings.Builder` is just a faster way to build a string. Is this a performance improvement?

The PR message is short and unclear as to the underlying problem.

Let's try to clarify the objective with a nicely written PR message :)

**Review by oh6hay — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
