### PR TITLE
[MM-15744] remove store from api4/user

### PR DESCRIPTION
**Pull request by zaviermiller**
#### Summary
This pull request adds a new function (`App.GetTokenFromString(string)`) to the App Interface in order to remove the Store call from `api4/user.go`.

### CODE REVIEW

**Comment by jasonblais** [comment]
@zaviermiller Thanks for your contribution!

It looks like you may have submitted the CLA with the username `zavierjmiller ` with an extra j.

Are you open to help resubmit the form with the `zaviermiller` username? We'll then get the review process started.

**Comment by zaviermiller** [comment]
Oops, yeah my bad. Just got that done!

**Comment by jespino** [comment]
@zaviermiller do you mind to return an AppError from the new App method and move the error to AppError conversion code from the api to the app?

**Comment by jasonblais** [comment]
Hi @zaviermiller, let us know if you have any questions regarding Jesús' feedback above. We'd be happy to help :)

**Comment by isacikgoz** [comment]
Gentle ping on this @zaviermiller :)

**Comment by jasonblais** [comment]
Big thanks for your contribution! @zaviermiller 

However, it has been more than 60 days with no activity so we've marked your PR as orphaned and we'll close it. [Per our inactive contribution process](https://developers.mattermost.com/contribute/getting-started/inactive-contributions/), it is eligible to be assumed by another community member interested in working on the ticket. 

If there are any areas we can help clarify or provide guidance, let us know! We'd be happy to help :)

**Pull request closed without merging**
