### PR TITLE
MM-51436: fixes broken link

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Replaces the broken Message Priority feedback link on TE servers.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-51436

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by kostaspt — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Comment by amyblais** [comment]
@koox00 Please help open manual cherry-pick PRs for ``cloud`` and ``release-7.9`` branches.

**Comment by amyblais** [comment]
Updated my previous comment - just cherry-picking to 7.9 branch for now is fine.

**Comment by koox00** [comment]
@amyblais I'll manually cherry-pick, sorry the wait, and thanks!

**Pull request merged**
