### PR TITLE
Bump GitHub plugin version to 2.1.5

### PR DESCRIPTION
**Pull request by mickmister**
#### Ticket Link

https://github.com/mattermost/mattermost-plugin-github/pull/660

#### Release Note

```release-note
Include GitHub plugin v2.1.5
```

### CODE REVIEW

**Review by trilopin — DISMISSED** [review]

**Review by m1lt0n — APPROVED** [review]

**Review by trilopin — APPROVED** [review]

**Comment by m1lt0n** [comment]
@DHaussermann Is this ok to merge? So that it makes it for 8.0?

**Review by m1lt0n — APPROVED** [review]

**Pull request merged**
