### PR TITLE
MM-19310 - Wrong validation message when Bot name ends in a .

### PR DESCRIPTION
**Pull request by ali-farooq0**
#### Summary
Added a test to solidify the current behaviour. Added UI validation on the webapp to address the issue. https://github.com/mattermost/mattermost-webapp/pull/4062

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-19310

### CODE REVIEW

**Comment by ali-farooq0** [comment]
> Won't other symbols be problem as well? like `@`?

We only allow `.` `-` and `_` characters in username so if you try `@` it complains that the username contains illegal characters, rather than complaining that the email is incorrect.
image

**Comment by crspeller** [comment]
@ali-farooq0 What happens if I try to create a bot `mybot.` then `mybot`?

**Comment by ali-farooq0** [comment]
> @ali-farooq0 What happens if I try to create a bot `mybot.` then `mybot`?

@crspeller ahh tricky

image


Won't let me create it because email is already used.

Maybe we shouldn't let users create a bot with username ending with `.`. That seems to be only reasonable option here. Whatcha think?

**Comment by crspeller** [comment]
@ali-farooq0 I think that makes sense.

**Comment by ali-farooq0** [comment]
@crspeller added client side validation for this case: https://github.com/mattermost/mattermost-webapp/pull/4062

Added a unit test to lock down the current behaviour.

**Comment by ali-farooq0** [comment]
QA done as part of https://github.com/mattermost/mattermost-webapp/pull/4062#event-2757524944

**Pull request merged**
