### PR TITLE
Force right index for post deletion

### PR DESCRIPTION
**Pull request by agnivade**
During v6 indexing changes, we replaced
idx_posts_root_id with idx_posts_root_id_delete_at.
This causes MySQL to trigger the index_merge path
again with PRIMARY and idx_posts_root_id_delete_at
as shown below:

```
mysql> UPDATE Posts SET DeleteAt = 1637998911685, UpdateAt = 1637998911685, Props = JSON_SET(Props, '$.deleteBy', 'buqskqrwmjnhfuqskqrwmjn4ca') Where Id = 'q38uaydtpink5f4wkmcsn8h47o' OR RootId = 'q38uaydtpink5f4wkmcsn8h47o';
Query OK, 9 rows affected (17.29 sec)
Rows matched: 10  Changed: 9  Warnings: 0
mysql> EXPLAIN UPDATE Posts SET DeleteAt = 1637998911685, UpdateAt = 1637998911685, Props = JSON_SET(Props, '$.deleteBy', 'buqskqrwmjnhfuqskqrwmjn4ca') Where Id = 'q38uaydtpink5f4wkmcsn8h47o' OR RootId = 'q38uaydtpink5f4wkmcsn8h47o'\G
*************************** 1. row ***************************
           id: 1
  select_type: UPDATE
        table: Posts
   partitions: NULL
         type: index_merge
possible_keys: PRIMARY,idx_posts_root_id_delete_at
          key: idx_posts_root_id_delete_at,PRIMARY
      key_len: 107,106
          ref: NULL
         rows: 9
     filtered: 100.00
        Extra: Using sort_union(idx_posts_root_id_delete_at,PRIMARY); Using where; Using temporary
1 row in set, 1 warning (0.00 sec)
```

To fix the temporary sort, we order by Id

```
mysql> UPDATE Posts SET DeleteAt = 1637998911686, UpdateAt = 1637998911686, Props = JSON_SET(Props, '$.deleteBy', 'buqskqrwmjnhfuqskqrwmjn4ca') Where Id = 'q38uaydtpink5f4wkmcsn8h47o' OR RootId = 'q38uaydtpink5f4wkmcsn8h47o' ORDER BY Id;
Query OK, 9 rows affected (0.01 sec)
Rows matched: 9  Changed: 9  Warnings: 0
mysql> EXPLAIN UPDATE Posts SET DeleteAt = 1637998911686, UpdateAt = 1637998911686, Props = JSON_SET(Props, '$.deleteBy', 'buqskqrwmjnhfuqskqrwmjn4ca') Where Id = 'q38uaydtpink5f4wkmcsn8h47o' OR RootId = 'q38uaydtpink5f4wkmcsn8h47o' ORDER BY Id\G
*************************** 1. row ***************************
           id: 1
  select_type: UPDATE
        table: Posts
   partitions: NULL
         type: index_merge
possible_keys: PRIMARY,idx_posts_root_id_delete_at
          key: idx_posts_root_id_delete_at,PRIMARY
      key_len: 107,106
          ref: NULL
         rows: 9
     filtered: 100.00
        Extra: Using sort_union(idx_posts_root_id_delete_at,PRIMARY); Using where; Using filesort
1 row in set, 1 warning (0.00 sec)
```

Postgres uses Bitmap Heap scan which does
a Bitmap OR of the index tuples and _then_
fetches the rows from the heap. This is a
much better and sophisticated way. Sadly, MySQL
will fetch the rows from the indexes first,
and then do an OR, which is why index_merge_intersection
is so bad.

See: https://developers.mattermost.com/blog/mysql-index-merge/
for more info.

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Waiting for the user's confirmation (who reported the issue) that the new index fixes the issue before merging.

**Comment by streamer45** [comment]
Interesting, were you able to test this on some significant dataset? I am wondering if forcing the primary could worsen the performance of thread deletion.

**Comment by agnivade** [comment]
It will only affect that query right? The thread deletion is a different query.

I haven't tested on a large data set. But I went back to 5.36 and checked that this was the original query plan, so using the original index should fix it. Anyways, I am waiting for confirmation on the forum user - their dataset is 18M+ posts.

**Comment by streamer45** [comment]
> It will only affect that query right? The thread deletion is a different query.
> I haven't tested on a large data set. But I went back to 5.36 and checked that this was the original query plan, so using the original index should fix it. Anyways, I am waiting for confirmation on the forum user - their dataset is 18M+ posts.

By thread a I really just mean a post with replies. Deleting a single post should work fine but forcing the primary will not help much on fetching (and updating) the replies (RootId condition) which I am assuming is different from how the index was operating before.

**Comment by agnivade** [comment]
Found another query which needed fixing. PTAL.

**Comment by streamer45** [comment]
> Found another query which needed fixing. PTAL.

Interestingly this oddity seems to be affecting UPDATEs only:

```
mysql> EXPLAIN DELETE FROM Posts WHERE Id = '1114f5co77gbpmnpfahgm8c1qc' OR RootId = '1114f5co77gbpmnpfahgm8c1qc'\G
*************************** 1. row ***************************
           id: 1
  select_type: DELETE
        table: Posts
   partitions: NULL
         type: index_merge
possible_keys: PRIMARY,idx_posts_root_id_delete_at
          key: idx_posts_root_id_delete_at,PRIMARY
      key_len: 107,106
          ref: NULL
         rows: 11
     filtered: 100.00
        Extra: Using sort_union(idx_posts_root_id_delete_at,PRIMARY); Using where
1 row in set, 1 warning (0.01 sec)

mysql> EXPLAIN UPDATE Posts SET DeleteAt = 1 WHERE Id = '1114f5co77gbpmnpfahgm8c1qc' OR RootId = '1114f5co77gbpmnpfahgm8c1qc'\G
*************************** 1. row ***************************
           id: 1
  select_type: UPDATE
        table: Posts
   partitions: NULL
         type: index_merge
possible_keys: PRIMARY,idx_posts_root_id_delete_at
          key: idx_posts_root_id_delete_at,PRIMARY
      key_len: 107,106
          ref: NULL
         rows: 11
     filtered: 100.00
        Extra: Using sort_union(idx_posts_root_id_delete_at,PRIMARY); Using where; Using temporary
1 row in set, 1 warning (0.00 sec)
```

```
mysql> DELETE FROM Posts WHERE Id = '1114f5co77gbpmnpfahgm8c1qc' OR RootId = '1114f5co77gbpmnpfahgm8c1qc';
Query OK, 11 rows affected (0.01 sec)
```

**Comment by agnivade** [comment]
Thanks, will revert the last one.

**Review by streamer45 — APPROVED** [review]

**Comment by agnivade** [comment]
No, this is not a regression for 6.3.

**Comment by 42wim** [comment]
This seems to be a regression in v6.3 also, I'm getting hit by it on v6.3.5 after upgrade from previous LTS

Code in v6.3.5 is still3 
```
	} else {
		_, err = transaction.Exec(`UPDATE Posts
			SET DeleteAt = ?,
			UpdateAt = ?,
			Props = JSON_SET(Props, ?, ?)
			Where Id = ? OR RootId = ?`, time, time, "$."+model.PostPropsDeleteBy, deleteByID, postID, postID)
	}
```

**Comment by agnivade** [comment]
This is not a regression for 6.3 because the issue was introduced in 6.0. But it should be fine to backport given 6.3 is an ESR. cc @amyblais

**Comment by amyblais** [comment]
> This is not a regression for 6.3 because the issue was introduced in 6.0. But it should be fine to backport given 6.3 is an ESR. cc @amyblais

@agnivade Ok, please help cherry-pick to ``release-6.3``.

**Pull request merged**
