### PR TITLE
Migrate channelbynamecache storelayer

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

This migrates the `channelByNameCache` from `ChannelStore` to `LocalCacheChannelStore`.

#### Ticket Link

#13100

### CODE REVIEW

**Comment by rvillablanca** [comment]
@jespino you could be interested in this change, although I still need to add the tests

**Comment by rvillablanca** [comment]
At first the tests are passing but I think this could need more tests, I have to more for `GetByNames`

**Comment by agnivade** [comment]
This is okay, but ideally, we need to intercept _all_ the store methods in the cache layer and move all the invalidations from the app layer to the cache layer. I am 0/5 on whether to do it in this PR or later, but for your understanding, this is the ideal way to do it.

**Comment by rvillablanca** [comment]
I have some conflicts here but I'm not sure if it is worth fixing, I know that there are some bugs around cache and you are taking another approach to improve the caching process.

When I get feedback from you I'll make the changes only if is necessary :)

**Comment by agnivade** [comment]
The conflicts are for the migration to the cache2 interface. It is an orthogonal thing to the cache invalidation bugs that we want to address. You can take a look at this PR https://github.com/mattermost/mattermost-server/pull/14691 which migrates everything else to cache2.

**Pull request closed without merging**
