### PR TITLE
remove @ that is prefixed while sending notifications

### PR DESCRIPTION
**Pull request by Sheshagiri**
#### Summary
remove @ that is prefixed while sending notification. made changes in the `server` side based on the review comments in https://github.com/mattermost/mattermost-webapp/pull/2114

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/MM-12795
Git Issue: Fixes https://github.com/mattermost/mattermost-server/issues/9807

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by Sheshagiri** [comment]
@esethna I did a quick test with the above setup and in the browser, I still see the `@`?. I'm not sure how to test mobile notifications.

**Comment by esethna** [comment]
Hey @Sheshagiri, for the desktop notifications you have pictured above, it will require a PR to the webapp repo. We just need to address the bug found with this PR (see review comments about nickname teammate name display): https://github.com/mattermost/mattermost-webapp/pull/2114

For push notifications, we can try pointing the mobile app at the spinmint server created by mattermod

**Comment by lieut-data** [comment]
Note that I didn't actually merge this PR: GitHub seems to have associated me with this PR because of my https://github.com/mattermost/mattermost-server/commit/aca8914e3584ee60d919819caa1d394c648d3d39 commit, and some put forcibly updated the fork to the latest changes (but discarded the original commits?). I'm not sure what's going on here.

**Comment by Sheshagiri** [comment]
@lieut-data it was the `pull` app that merges changes from upstream to the forked repo. I'm not sure why it discarded the original commits, I'll look into that and for now, I un-installed the app from my Github.

**Comment by Sheshagiri** [comment]
@esethna I tired the push notifications point my app to the above-mentioned server and I still see that `@` is being prefixed.



I'm planning to do a debug over the weekend any pointers on where to start looking will be really helpful.

**Pull request merged**
