### PR TITLE
[Partial Fix #16623]: Fix initialism errors in codebase.

### LINKED ISSUE #16623: Fix all initialism errors in the codebase
#### Summary
This ticket is about fixing any variable naming issues that do not follow the initialism convention as laid out in: https://github.com/golang/go/wiki/CodeReviewComments#initialisms.

The way to go about it would be to make the following change to .golangci.yml

```diff
diff --git a/.golangci.yml b/.golangci.yml
index 29d9a4622..662931923 100644
--- a/.golangci.yml
+++ b/.golangci.yml
@@ -49,7 +49,7 @@ issues:
 
     - linters:
       - golint
-      text: "should have|should be|should replace|stutters|underscore|annoying|error strings should not be capitalized"
+      text: "should replace|stutters|underscore|annoying|error strings should not be capitalized"
 
     - linters:
       - golint      
```

And then fix all issues that arise until make golangci-lint passes with no errors.

### PR DESCRIPTION
**Pull request by SimonSimonB**
#### Summary
Aims to partially solve #16623.

#### Ticket Link
#16623 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by agnivade — APPROVED** [review]
Great work @SimonSimonB !

**Comment by agnivade** [comment]
No testing needed as they are just cosmetic changes.

**Pull request merged**
