### PR TITLE
Mono repo -> Master

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR will merge mono-repo into master.  See mono-repo proposal [here](https://docs.google.com/document/d/1dbofEY-JJ65Hh_g93OJB0zIG-ao0fzjGuiwij8V-Tus/edit) for background. 

Combines the following repositories into one:
- https://github.com/mattermost/mattermost-server
- https://github.com/mattermost/mattermost-webapp
- https://github.com/mattermost/focalboard
- https://github.com/mattermost/mattermost-plugin-playbooks

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51556

#### Release Note
```release-note
The following repositories have been merged into one: mattermost-server, mattermost-webapp, focalboard, mattermost-plugin-playbooks.  Developers should read updated Developer Guide for details.
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
> Test server creation failed. See the logs for more information.

@toninis @phoinixgrr Do you know where can we get these logs? The docker images should be available but there is still a problem about creating the test servers.

**Comment by phoinixgrr** [comment]
> > Test server creation failed. See the logs for more information.
> 
> @toninis @phoinixgrr Do you know where can we get these logs? The docker images should be available but there is still a problem about creating the test servers.

@isacikgoz SpinWick support is performed by the SRE team. I'd suggest reaching out to them for comprehensive troubleshooting. cc: @stylianosrigas

**Comment by sbishel** [comment]
Quickly banging on the spinwick, everything looks good so far.

**Comment by agnivade** [comment]
Frankly, I am not sure if it's possible to do a complete review of this PR. Is there something in particular you want me to look at?

**Comment by wiggin77** [comment]
> Frankly, I am not sure if it's possible to do a complete review of this PR. Is there something in particular you want me to look at?

This is more to accept the criteria for merge:  spinwicks working; unit tests passing

**Review by lieut-data — APPROVED** [review]
I'm leaving my approval here as requested by @wiggin77, recognizing that we're not reviewing this line-by-line, but aim to stabilize thereafter. The merge conditions on passing tests have now been met.

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by sbishel — APPROVED** [review]
LGTM - Awesome work!!!!

**Review by crspeller — APPROVED** [review]
Excited to see this go in! 🎉

**Review by saturninoabril — APPROVED** [review]
Thank you @wiggin77 and to all of you for making this happen!

**Pull request merged**
