### PR TITLE
Migrate channel_store to sqlx

### PR DESCRIPTION
**Pull request by agnivade**
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/chur9rxkghprg7dz1mcqssj34ic

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Just uploading the branch before I take off.

**Comment by agnivade** [comment]
This is ready now. There are some queries which are complicated to be convered to squirrel in this PR itself. I will create separate HW tickets for them.

**Review by isacikgoz — COMMENTED** [review]
LGTM 👍  A question though: Are the TODOs in the file supposed to be help-wanted tickets?

**Comment by agnivade** [comment]
Yes, I need to create them.

**Review by isacikgoz — APPROVED** [review]
Wondering if we should include the ticket numbers rather than just leaving the TODOs as is. It can be done in a separate PR though. 0/5 on either.

**Comment by agnivade** [comment]
Yeah, I plan to merge the PR first, and then create the tickets.

**Pull request merged**
