### PR TITLE
Re-initialize plugins only when needed

### PR DESCRIPTION
**Pull request by agnivade**
Previously, for every config change, we would re-initialize
plugins irrespective of whether there would be any actual
plugin related changed or not.

Now, we compute the difference between previous and new configs
and check whether there has been any changes to plugin related
configuration, and re-init plugins only if that's true.

This improves performance as plugin re-initialization is quite
costly.

https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/bed59298-27da-4b74-8be5-cdeb4c50c3e2

```release-note
Plugins are re-initialized only when Plugin related config changes happen. This improves performance by avoiding plugin initialization which is quite costly.
```

### CODE REVIEW

**Comment by agnivade** [comment]
Thank you @streamer45 for `config.Diff` :slightly_smiling_face: 

cc @sadohert

**Comment by agnivade** [comment]
The right change would be to pass the diff in the config change handler itself. Expect an improvement PR later.

**Review by streamer45 — COMMENTED** [review]
Nice addition :+1: 

Wondering if we could quantify the overhead that's getting saved here. I'd expect the plugin handling logic to avoid doing much unless plugins got enabled/disabled. Could you explain what is the costliest operation currently happening on every config change?

**Comment by agnivade** [comment]
Basically, there's some redundant code being executed;

```go
if pluginsEnvironment != nil || !*ch.srv.Config().PluginSettings.Enable {
	ch.syncPluginsActiveState()
	pluginsEnvironment.TogglePluginHealthCheckJob(*ch.srv.Config().PluginSettings.EnableHealthCheck)
	return
}
```

It will go through `ch.syncPluginsActiveState()` every time - which needlessly runs through all enabled plugins, all disabled plugins and tries to enable/disable them respectively. Nothing much happens, but a lot of needless CPU.

**Review by streamer45 — APPROVED** [review]
:100:

**Review by isacikgoz — APPROVED** [review]
Looks great, going to ask if this was prone to race, it seems like the lock has been called while we are invoking the config listeners. Great job @streamer45 @agnivade 💯

**Comment by agnivade** [comment]
@isacikgoz - Just so I understand, which lock were you referring to?

**Comment by isacikgoz** [comment]
I was referring to
https://github.com/mattermost/mattermost-server/blob/186475db3beba84298998bfaa0f482f65285ecce/config/store.go#L236-L238

**Comment by agnivade** [comment]
Going to run an E2E test.

**Comment by agnivade** [comment]
@saturninoabril - Could you please take a look at https://automation-dashboard.vercel.app/cycles/19388205-037a-4bf5-9079-2b772d88628c and confirm that the failures are expected? Thanks!

**Review by saturninoabril — APPROVED** [review]
Thanks @agnivade! All good and failed tests are known bugs.

**Comment by agnivade** [comment]
Thanks @saturninoabril !

**Comment by amyblais** [comment]
@agnivade Is this needed for v6.3?

**Comment by agnivade** [comment]
No, this is not a regression.

**Pull request merged**
