### PR TITLE
MM-30819: Change to idiomatic receiver names for slashcommands.PurposeProvider

### LINKED ISSUE #16331: Change receiver name for (me *PurposeProvider) in app/slashcommands/command_channel_purpose.go to be more idiomatic
The Mattermost codebase has a lot of methods with receiver names as `me`. This is a carry-over from other Object Oriented languages and not idiomatic Go as pointed out <here>(https://github.com/golang/go/wiki/CodeReviewComments#receiver-names).

This ticket is about changing the receiver name from `me` to something more suitable for `(me *PurposeProvider)` in `app/slashcommands/command*channel*purpose.go`.

Example Pull Request: #16298

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-30819

### PR DESCRIPTION
**Pull request by CandyZack**
#### Summary
Updated the receiver names in methods to be more idiomatic and removed receiver names where it were not being used.
#### Ticket Link
JIRA - https://mattermost.atlassian.net/browse/MM-30819
Issue - Fixes #16331

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Looks great!

**Review by jespino — APPROVED** [review]
Looks good to me. Thanks @tbalthazar! :sparkles:

**Comment by jespino** [comment]
@agnivade this doesn't change any behavior, I would add the label for tests not needed, but I leave this up to you.

**Comment by agnivade** [comment]
The `Tests Not Needed` label is not for us devs to add. It's meant for the QA team to mark something as release tests not to be added. It's a bit confusing, I know :)

**Pull request merged**
