### PR TITLE
MM-50123 : Identify causes of removal of channel and channel members re fetching on team switch

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
We already fetch everything related to the channel and channel members on team controller mount https://github.com/mattermost/mattermost-webapp/blob/ed4baa6e0cc30c0c8e9a111bbe0d12bf5a3ba372/components/team_controller/team_controller.tsx#L55-L67  On Each team switch requesting the same data is redundant.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50123

#### Screenshots
n/a

#### Release Note

```release-note
Removed re-fetching of channels and channel members in team switch.
```

### CODE REVIEW

**Comment by agnivade** [comment]
Just confirming: this sort of behavior is something we have been doing in the webapp in general. Overfetching data even if we have it in the redux store. Likely there are other places also where we can remove redundant API calls. Does this mean we plan to make changes in all those places? Or was this a one-off thing?

**Comment by M-ZubairAhmed** [comment]
Yes, @agnivade, we plan on doing this more in other places of over-fetching. In the meantime, please get in do inform us if you find other areas for such improvements.

**Comment by agnivade** [comment]
Sounds good. I'll check and let you know.

cc @agarciamontoro - a potential perf improvement here.

@M-ZubairAhmed - just let me know once you merge this. I'll monitor community graphs.

**Review by agnivade — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
@M-ZubairAhmed We should probably make an announcement about this in R&D meeting on Thursday so that people are aware we're making changes to this. I'd hope we don't run into any issues, but it'd be good to get others watching for any bugs that might crop up.

@agnivade We got into a bad habit of doing that sort of thing early on when websockets were less reliable, and I don't think the server/network impacts of that were really considered at the time. We're hoping that the websockets are reliable enough nowadays that this shouldn't be necessary any more

**Review by yasserfaraazkhan — APPROVED** [review]
thank you Zubair, ran it locally and checked switching channels. everything worked as expected.

**Comment by saturninoabril** [comment]
@M-ZubairAhmed @yasserfaraazkhan This has caused so many failing tests both with GraphQL [not enabled](https://automation-dashboard.vercel.app/cycles/125df661-1694-432f-940d-5cdf70c79e7f) and [enabled](https://automation-dashboard.vercel.app/cycle/327085). I wonder if those results were looked at and addressed before merging this PR. Please prioritize fix or best to revert this PR. Let me know. TIA.

**Comment by yasserfaraazkhan** [comment]
> @M-ZubairAhmed @yasserfaraazkhan This has caused so many failing tests both with GraphQL [not enabled](https://automation-dashboard.vercel.app/cycles/125df661-1694-432f-940d-5cdf70c79e7f) and [enabled](https://automation-dashboard.vercel.app/cycle/327085). I wonder if those results were looked at and addressed before merging this PR. Please prioritize fix or best to revert this PR. Let me know. TIA.

Thank you Saturn, 
I did see this https://automation-dashboard.vercel.app/cycle/327085 and did a manual check for channel messaging.
in the 'last runs' the test appear failed or skipped. Will cross check again with few other PRs too.

**Pull request merged**
