### PR TITLE
Gh 13908 fix bot missing username error

### PR DESCRIPTION
**Pull request by dihmuzikien**
#### Summary

Change validation logic for bot creation to validate some fields before attempting to create the bot

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13908

#### Release Note

```release-note
Fixes an issue where creating bot with invalid username returns "invalid email"
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
Sorry to keep this waiting @dihmuzikien we will review this one shortly.

**Review by streamer45 — APPROVED** [review]
Thank you @dihmuzikien , PR looks good :+1:

**Review by isacikgoz — APPROVED** [review]
Thanks for the contribution @dihmuzikien 🎉 Could you please remove the empty lines before this gets ready to merge? Otherwise LGTM 👍

**Review by furqanmlk — APPROVED** [review]
Working fine in API and UI
image

image

**Comment by dihmuzikien** [comment]
Thanks everyone! pushed the whitespace change

**Pull request merged**
