### PR TITLE
Fixing race condition on status serialization

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
During status serialization the serialized object could be modified while is
been serialized, so I copied the object before serializing it.

#### Ticket Link
[MM-23505](https://mattermost.atlassian.net/browse/MM-23505)

### CODE REVIEW

**Comment by streamer45** [comment]
> During status serialization the serialized object could be modified while is
> been serialized, so I copied the object before serializing it.

What happens if the object gets modified while we are making the copy?
I see how this would fix the panic but the underlying cause might be simply covered.

**Comment by jespino** [comment]
@streamer45 I think the underlying problem is related to the cache of pointers that we have. That is already been addressed by a @liusy182 in the pr #14118. I think is where all this "shared memory" errors are at the end.

**Comment by streamer45** [comment]
> @streamer45 I think the underlying problem is related to the cache of pointers that we have. That is already been addressed by a @liusy182 in the pr #14118. I think is where all this "shared memory" errors are at the end.

Sounds good. Do you think this is not strictly related to the reported data race affecting `model.Status`?

**Comment by jespino** [comment]
@streamer45 I'm not sure :( could be. @agnivade is investigating that.

**Comment by streamer45** [comment]
> @streamer45 I'm not sure :( could be. @agnivade is investigating that.

Alright, my only fear here is that we could potentially go from panic to silent data corruption.

**Comment by agnivade** [comment]
> What happens if the object gets modified while we are making the copy?

These were the only modification paths which affected `ActiveChannel`. That's why I commented that this will atleast take care of _this_ race. But there maybe other races too.

And yes, the cache of pointers is related too. That would fix these sorts of races and data corruption both.

**Comment by agnivade** [comment]
@amyblais - Do you think this could be backported to 5.23 ? This is technically a bug, and is causing crashes when we run our load tests. So would be good to be able to run a crash-free load test :)

I think the risk is very minimal, but I will defer to @jespino in case since he submitted the fix.

/cc @grundleborg

**Comment by grundleborg** [comment]
Yes, if possible please can we backport this @jespino @agnivade @amyblais

**Comment by amyblais** [comment]
@jespino Assigned to you to cherry-pick to v5.23

**Pull request merged**
