### PR TITLE
MM-19138 - Adjust test to use require.

### PR DESCRIPTION
**Pull request by Muscaw**
#### Summary
This PR adjusts the test in `model/cluster_discovery_test.go` to use the `require` package.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12570

### CODE REVIEW

**Comment by Muscaw** [comment]
@hmhealey Hey, I did not know about this difference. I'll do the changes during the day.
Thank you for the comment

**Comment by lindy65** [comment]
Thanks @Muscaw - nothing specific to QA - only the tests are modified.

**Comment by Muscaw** [comment]
@hmhealey I applied the changes. Tell me if there is anything else.

**Comment by hmhealey** [comment]
Looks like CircleCI is having some issues. I'll try re-running the tests in a bit since the build errors aren't caused by this PR

**Pull request merged**
