### PR TITLE
MM-34774 Root post with mention should be auto-followed but hidden from thread results

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

    implemented auto follow based on root post

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-34774

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by zefhemel — APPROVED** [review]

**Review by jespino — APPROVED** [review]
Nice, LGTM.

**Comment by esethna** [comment]
@ogi-m on very brief smoke testing this as well with the feature flag off.

**Comment by esethna** [comment]
Ping @ogi-m on this guy too, thanks!

**Review by ogi-m — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
