### PR TITLE
Check for cloud license and CWS error when checking integration freemium limits

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

When checking the freemium limits for enabling an integration, we check the Cloud Freemium feature flag, but we don't check for a Cloud license. This is not an issue in production, but testing servers are having issues when the feature flag is set, but a Cloud license is not installed. An error occurs when we request limits from the CWS server in this case.

This PR makes it so we check for the Cloud license, and avoid checking limits when there is not one present.

This PR also treats the case where we receive an error from the CWS server as a pass. The only time we will block an integration enable is when we have proof that a server has reached its limit.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-44905

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]

**Comment by mickmister** [comment]
@neallred I've changed the logic here a bit more. In the case of a CWS error (Stripe being down etc.), we will now treat this as a "pass" when checking integration freemium limits.

**Review by neallred — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- No issues installing plugins via marketplace. 
- No issues enabling plugins in system console. CWS error appears resolved. 
- Tested to ensure no integration limits affect the servers without cloud license or Stripe connectivity
- Tested on E0 and on-prem licenses
- Tested on HA  
- No issues found 

LGTM!

Please re-request review if dev reviews prompts any additional changes

**Review by marianunez — APPROVED** [review]

**Comment by mickmister** [comment]
@amyblais This PR fixes an additional issue where we would handle a CWS error incorrectly, and would assume a customer is past their freemium limits if we can't fetch the limits. This error can happen for a number of things beyond our control, e.g. the external service "Stripe" being down.

The affected code is currently only in the `cloud` branch, and would only affect Cloud environments even if it was in the on-prem release. 5/5 this should be cherry-picked to `cloud` if possible. There is essentially no risk, and impact is high. Preemptively made a PR here https://github.com/mattermost/mattermost-server/pull/20424

**Pull request merged**
