### PR TITLE
MM-44130: Changed email button text.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Changed email button text from "View Message" to "Reply in Mattermost".

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-44130

#### Release Note

```release-note
Changed the email notifications button text.
```

Screen Shot 2022-05-24 at 4 52 51 PM

### CODE REVIEW

**Review by jasonblais — APPROVED** [review]
Thank you!

**Comment by jasonblais** [comment]
cc @amyblais candidate for v7

**Review by plant99 — APPROVED** [review]

**Comment by mkraft** [comment]
@BenCookie95 gentle ping

**Review by BenCookie95 — APPROVED** [review]

**Comment by furqanmlk** [comment]
@mkraft I have updated a related test case, please merge this PR.

**Pull request merged**
