### PR TITLE
Dev license Server

### PR DESCRIPTION
**Pull request by ethervoid**
Dev license test server - USED FOR DEV PURPOSES

For test license check https://github.com/mattermost/mattermost-server/pull/17490

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by angeloskyratzakos** [comment]
Hey all, I will remove the tag `Setup Cloud Test Server` for maintenance reasons. Feel free to re-add it when you need it. Thank you

**Comment by isacikgoz** [comment]
@AGMETEOR @marianunez do you know what is the state for this PR? Can we close it?

**Comment by marianunez** [comment]
> @AGMETEOR @marianunez do you know what is the state for this PR? Can we close it?

We also have this one for the dev license key (instead of prod or test). This one we use rarely so I can close this for now.

**Pull request closed without merging**
