### PR TITLE
Adding terms_accepted and receive_emails_accepted params to request trial

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Adding terms_accepted and receive_emails_accepted params to request trial

#### Ticket Link
[MM-26481](https://mattermost.atlassian.net/browse/MM-26481)

### CODE REVIEW

**Comment by esadur** [comment]
FYSA @Adovenmuehle

**Comment by jespino** [comment]
@esadur the new design doesn't affect at all to this PR.

**Comment by jespino** [comment]
@stevemudie this is the backend part of the `Get trial license` should behave exactly the same than the other PR, but needs the other PR to have the right interface. Maybe makes sense to test it after merge, or at least wait until the other related PR is merged.

**Pull request merged**
