### PR TITLE
MM-19163 - Refactored team search tests to testify

### LINKED ISSUE #12593: Migrate tests from "model/team_search_test.go" to use testify
Mattermost is migrating its server tests from using the `t.Fatal` method calls on their checks to use the [testify toolkit](https://github.com/stretchr/testify). The goal of this migration is to improve the readability of the tests, making them more concise and meaningful. This Help Wanted issue is to migrate the tests in the `model/team_search_test.go` file.

The expected way to migrate this is to go to the `model/team_search_test.go` file and modify the calls to `t.Fatal` and the condition checks that lead to them, replacing them with calls to the [the `require` package](https://godoc.org/github.com/stretchr/testify/require) if a failure should stop the execution of the test, or [the `assert` package](https://godoc.org/github.com/stretchr/testify/assert) if it shouldn't.

Example: mattermost/mattermost-server#12039

If you have questions about the ticket or you need any help, feel free to contact `miguel.delacruz` or `jesus.espino` in <https://community.mattermost.com/>

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-19163

### PR DESCRIPTION
**Pull request by VictorAvelar**
#### Summary
Moves testing for `team_search.go` from the standard library to testify.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/MM-19163
Fixes #12593 on Github

### CODE REVIEW

**Comment by VictorAvelar** [comment]
@amyblais Hi, this one is ready for review, I already signed the CLA agreement. Let me know if something else is required please.

**Comment by amyblais** [comment]
@VictorAvelar Thank you, nothing else is required. One of our devs or product managers will assign reviewers for this PR and then they will get it reviewed.

**Comment by VictorAvelar** [comment]
Ok, thanks for the feedback 👍

**Pull request merged**
