### PR TITLE
[MM-51233] Updates for Trial Requests

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary

This PR replaces https://github.com/mattermost/mattermost-server/pull/22521 (gave up on fixing conflicts)

This PR adds a new Trial Request Form, leveraged from all Channels entrypoints into the Trial Request flow. This new form asks for new information including:

Name
Email (that is validated against the CWS to be a business email)
Company Name
Company Size
Company Country

These fields are passed to the backend and the backend sends them along with its trial request to the CWS. The CWS does not yet support these new fields, but should consume the trial requests with the supported existing fields just fine. 

Explicit support for embargoed entities will be covered in a future PR, under ticket: https://mattermost.atlassian.net/browse/MM-51470

#### Screenshots
The email field is pre-filled based on the current user's email address
image

Business email is validated on blur
image

Cannot submit without valid business email 
image

Filled form
image

Clicking Start Trial opens the trial benefits modal on success
image

Failure to activate trial request results in modal:
image

This is slightly different from the designs as it allowed me to re-use some existing components as well as allow the following UX: Clicking Try Again returns you to the Start Trial modal with the same information you entered originally. For now, this error modal will be for _all errors_ including export compliance errors, and air gapped instances (to be fixed in a future iteration)
image

#### Ticket Link
This PR encapsulates a few different tickets:
https://mattermost.atlassian.net/browse/MM-51348
https://mattermost.atlassian.net/browse/MM-51233
https://mattermost.atlassian.net/browse/MM-51424

#### Release Note

```release-note
Updates to trial request forms to allow for a more tailored trial experience
```

### CODE REVIEW

**Comment by nickmisasi** [comment]
@pvev @neallred I gave up on fixing the merge conflicts here: https://github.com/mattermost/mattermost-server/pull/22521 so moved all my changes into this branch and applied the feedback you gave from the other PR

**Review by neallred — APPROVED** [review]
:rocket: :shipit:

**Review by pvev — APPROVED** [review]
LGTM! thanks @nickmisasi 👍

**Comment by nickmisasi** [comment]
@annelieseklein one note on the trial activation error modal - I re-used our generic Icon + Message + buttons modal instead of what was in figma. Rather than the primary CTA being "Start trial" which was just supposed to resubmit the trial request, I opted for a "Try Again" that returns to the form to allow the user to change things. This made the code flow and exit points a little more clear, and allows the user to change up any fields before re-submitting (it also made keeping the fields through subsequent attempts easier)

**Comment by yasserfaraazkhan** [comment]
Hi @nickmisasi 
on this PR's spinwick

- for some reason , the `Start trial` button doesn't seems to get enabled
- if we select country like `Afghanistan` will it be screen for compliance ?
- The trial flow is same for `Professional` and `enterprise` features right ? The pop-up doesn't convert which trial is being tried 
Screenshot 2023-03-25 at 12 35 54 AM
Screenshot 2023-03-25 at 12 40 32 AM

**Comment by nickmisasi** [comment]
@yasserfaraazkhan in implementing pr feedback I introduced a bug that caused the business email validation to only run on initial load, so the start trial button wasn't being enabled since the modal would open with a non-business email. Next commit should fix that up. 

>if we select country like Afghanistan will it be screen for compliance ?

There's no descartes compliance screening for these. We have CloudFlare blocks on the Customer Portal for embargoed entities trying to activate a trial.

>The trial flow is same for Professional and enterprise features right ? The pop-up doesn't convey which trial is being tried

There's no such thing as a self hosted Professional trial (at least, not from an in-product activation perspective)

**Comment by annelieseklein** [comment]
Looks good @nickmisasi !

1. For the error message, can you please make sure there is spacing of 4px between the icon and the text and that the icon is vertically centered with the text?
current implementation:
Screen Shot 2023-03-24 at 5 33 39 PM

2. Also the design has the error message text as semibold
see design here:
Screen Shot 2023-03-24 at 5 34 33 PM

3. For the error modal, I'm fine with keeping it consistent with "Try again" as the main cta and contact support as the secondary CTA, however in terms of UI, can we try to more closely match what is in Figma in terms of : 

1. illustration size 
2. max width of body text 
3. spacing in between title and body text
4. location of CTAs on the modal
5. margins of the modal

What I have in Figma is what is consistent with our design system library which we use in the product. 

Current implementation: 
Screen Shot 2023-03-24 at 5 35 25 PM

current design:
Screen Shot 2023-03-24 at 5 35 41 PM

**Comment by annelieseklein** [comment]
Also could you please share a test server account info I can use ?

**Comment by nickmisasi** [comment]
@annelieseklein 
updated error modal:
image

updated errors
image

**Comment by nickmisasi** [comment]
@annelieseklein you can access the spinwick with https://github.com/mattermost/mattermost-server/pull/22620/#issuecomment-1485539293

**Comment by nickmisasi** [comment]
@annelieseklein lmk what you think
image

**Comment by annelieseklein** [comment]
> @annelieseklein lmk what you think image

Looks good! just two more small things are that 

1. The rounded corners should be at a factor of 8
2. There should be space below and to the right of the Try Again button of 24px each.

**Comment by annelieseklein** [comment]
Also please update the button text styling to reflect what is in the design (see below) Should be Open Sans, semibold, 12px: 

Screen Shot 2023-03-28 at 2 30 44 PM

**Comment by nickmisasi** [comment]
@annelieseklein 

image

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by annelieseklein — APPROVED** [review]

**Pull request merged**
