### PR TITLE
[MM-31731] Fix cleanup threads to properly handle not found errors

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
At this point, we were checking for `sql.ErrNoRows` instead of a `NotFoundErr`. Since the underlying function (`Thread().Get()`) is already transforming the ErrNoRows into a NotFoundErr, this check was failing.

This mainly caused that permanent deleting users or channels failed on previous versions (e.g. 5.29.1).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31731

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by reflog — APPROVED** [review]
great catch, thanks @larkox

**Review by nronas — APPROVED** [review]
Nice catch, LGTM

**Review by ogi-m — APPROVED** [review]
Tested and passed
- successfully deleted users and channels with mmctl
- no error

**Pull request merged**
