### PR TITLE
MM-21481: Fixed several issues from user marshalling

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

- Fixed the root cause for panic by properly converting
the map to a User struct.
- Added a check for type conversion for extra safety.
- Fixed a somewhat unrelated issue of a pointer to pointer reference.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-21481

### CODE REVIEW

**Comment by amyblais** [comment]
Please help cherry-pick to 5.18.

**Comment by streamer45** [comment]
> Please help cherry-pick to 5.18.

I can help with that. I am guessing since it's a bug we can cherry-pick to 5.19 also, correct?

**Comment by amyblais** [comment]
@streamer45 It can be cherry-picked to 5.19 after v5.19 is released because we're just working on final testing for it now. I'll let you know later today.

**Comment by amyblais** [comment]
@streamer45 This can now be cherry-picked to v5.19.

**Comment by agnivade** [comment]
Thanks for taking care of this @streamer45 !

**Pull request merged**
