### PR TITLE
WIP: Convert store/storetest/post_store.go t.Fatal calls into assert/requi…

### LINKED ISSUE #12785: Migrate tests from "store/storetest/post_store.go" to use testify
Mattermost is migrating its server tests from using the `t.Fatal` method calls on their checks to use the [testify toolkit](https://github.com/stretchr/testify). The goal of this migration is to improve the readability of the tests, making them more concise and meaningful. This Help Wanted issue is to migrate the tests in the `store/storetest/post_store.go` file.

The expected way to migrate this is to go to the `store/storetest/post_store.go` file and modify the calls to `t.Fatal` and the condition checks that lead to them, replacing them with calls to the [the `require` package](https://godoc.org/github.com/stretchr/testify/require) if a failure should stop the execution of the test, or [the `assert` package](https://godoc.org/github.com/stretchr/testify/assert) if it shouldn't.

Example: mattermost/mattermost-server#12039

If you have questions about the ticket or you need any help, feel free to contact `miguel.delacruz` or `jesus.espino` in <https://community.mattermost.com/>

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-19451

### PR DESCRIPTION
**Pull request by rv404674**
#### Summary
Convert store/storetest/post_store.go t.Fatal calls into assert/require calls.

#### Ticket Link
Fixes #12785

### CODE REVIEW

**Comment by jasonblais** [comment]
Hi @rv404674! Just checking to see if this is still a work in progress, and if you have any questions we can help with? Thanks for your contribution!

**Comment by rv404674** [comment]
Hi @jasonblais . Sorry for the delay. I am out of station for a week, hence wasn't able to work on it. Will it be fine if I complete it in couple of days.

**Comment by jasonblais** [comment]
@rv404674 Definitely fine! Thanks for the heads up 👍

**Comment by jasonblais** [comment]
Hi @rv404674, similarly to https://github.com/mattermost/mattermost-server/pull/12837, let us know if you have any questions to help you with this PR? :) We really appreciate your contributions!

**Comment by hanzei** [comment]
Hi @rv404674,

I'm also going to close this PR.

**Pull request closed without merging**
