### PR TITLE
[MM-40898] Sanitize message in email template

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR adds HTML sanitization to the message field that gets inserted in the email template for guest users invitations.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-40898

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by AshishDhama — APPROVED** [review]
LGTM!! Thanks @streamer45

**Comment by AshishDhama** [comment]
@srkgupta @isacikgoz could you please prioritise review of this branch

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Review by srkgupta — APPROVED** [review]
Thanks @streamer45. Tested and the issue is working fine now. LGTM.

**Pull request merged**
