### PR TITLE
MM-15184: Migrate WebHookStore Interface methods to sync by default.

### PR DESCRIPTION
**Pull request by therealpuneeth20**
#### Summary
This PR mainly focus on migrating the WebHookStore Interface methods to Sync by default.

Note: commit-wise review would be easier.
Edit: closing this PR. creating a PR for method/help ticket.

### CODE REVIEW

**Comment by jespino** [comment]
Hi @therealpuneeth20, I really appreciate your work here, but we prefer on PR per method, is way easier to review, and in this case you are migrating things that were already migrated by other community member. Actually in some cases "undoing" the explicit async usage of the store. The whole plan of this set of help wanted tickets is to remove the "Async" by default approach of the store, but not remove the "explicit async calls" in the Application layer.

Normally to avoid this kind of problems the people "ask" for take care of concrete help wanted tickets before start to work on them to remove the "up for grabs" label.

**Comment by therealpuneeth20** [comment]
Hi @jespino, I should have commented on the help ticket before starting the work. I have been reviewing the store code, I found similar issues regarding webhook interface. All tickets were labelled `up for grabs` except GH-10618. I just removed the `store.Do` wrapper in WebHook interface. The ticket also mentions to return objects from `model` package, which requires the change in interface.
Please, correct me if i'm wrong.

**Comment by jespino** [comment]
Yes, the concrete case is the `AnalyticsIncommingCount` method, already merged from other community member.

**Comment by therealpuneeth20** [comment]
After chat with @jespino, decided to break this PR into multiple PR's for each method. Opened multiple PR for each method/help wanted ticket. Closing this PR.

**Pull request closed without merging**
