### PR TITLE
MM-18115: fix segment v3 usage

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
In v5.14, we updated [github.com/segmentio/analytics-go](https://github.com/segmentio/analytics-go) to v3 as part of https://mattermost.atlassian.net/browse/MM-12389. As noted in the [migration guide](https://segment.com/docs/sources/server/go/#migrating-from-v2), the API subtly changed to expect a struct value and not a struct pointer:

```go
// in v2, you would call the `Track` method with a `Track` struct.
client.Track(&track)

// in v3, you would call the `Enqueue` method with a `Track` struct.
// Note that a pointer is not used here.
client.Enqueue(track)
```

Unfortunately, we kept passing a pointer, and the package didn't complain since it only required an interface -- which the pointer to these structs still implemented. Internally, it only checked for the value types, and failed to annotate our payloads with the requisite metadata. Upstream, segment.io accepted the payload, but then discarded it silently.

This has since been reported and fixed in https://github.com/segmentio/analytics-go/pull/146, but isn't yet part of a tagged release of the package.

Fix our code to pass struct values instead.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18115

### CODE REVIEW

**Comment by streamer45** [comment]
This was a pretty bad mistake. I guess being new to _golang_ could have been part of it but still I should have checked the updated API more carefully. I was completely fooled by the lack of errors.

I will review this shortly.

**Comment by lieut-data** [comment]
@streamer45, I don't fault you for this mistake -- it caught me off guard as well! Even their examples on segment.com using their debugger show Go code using the `&` before the struct, so it was completely non-obvious.

It seems like the package isn't regularly maintained, since although they've fixed this issue long before we migrated, they haven't released the version with the fix. /shrug :)

**Comment by saturninoabril** [comment]
@lieut-data Do you have specific test steps in mind to validate the change? Or do QA test after this is merged (see if telemetry reports on sentry)?

**Comment by lieut-data** [comment]
@saturninoabril, yeah, we just need to verify that after fixing this we start seeing data on segment.io. I've gained production access as such to vet these changes, but @jasonblais could also help confirm once we merge to community-daily.

**Comment by lieut-data** [comment]
Swapping out @stylianosrigas for @deanwhillier as he's unavailable this week.

**Pull request merged**
