### PR TITLE
MM-49485: Set BoardsProduct FF to on by default

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-49485

```release-note
Boards will be served as an in-built product from
within Mattermost server instead of a plugin.

If you want to disable this, please set the
MM_FEATUREFLAGS_BoardsProduct env var to "false" (without
the quotes).

In this mode, the boards plugin will remain disabled.
```

[MM-49485]: https://mattermost.atlassian.net/browse/MM-49485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]

**Comment by agnivade** [comment]
@wiggin77 - I am seeing this failure in the tests:

```
panic: failed to initialize products: error initializing product "boards": failed to create Boards service: error initializing the DB: driver: mysql, message: failed when applying migration, command: apply_migration, originalError: Error 1146: Table 'db4ao9ydg3k78pjnd9es6rku56ww.focalboard_blocks' doesn't exist, query: 


			SET @stmt = (SELECT IF(
				(
				  SELECT COUNT(column_name) FROM INFORMATION_SCHEMA.COLUMNS
				  WHERE table_name = 'focalboard_blocks'
				  AND table_schema = 'db4ao9ydg3k78pjnd9es6rku56ww'
				  AND column_name = 'root_id'
				) > 0,
				'SELECT 1;',
				'ALTER TABLE db4ao9ydg3k78pjnd9es6rku56ww.focalboard_blocks ADD COLUMN root_id varchar(36) ;'
			));
			PREPARE addColumnIfNeeded FROM @stmt;
			EXECUTE addColumnIfNeeded;
			DEALLOCATE PREPARE addColumnIfNeeded;
		
```

Unable to reproduce locally. Digging deeper.

**Review by isacikgoz — APPROVED** [review]

**Comment by wiggin77** [comment]
> @wiggin77 - Any idea why https://github.com/mattermost/focalboard/blob/f909c2552e376b025217fa45be97054c98491413/mattermost-plugin/server/boards/boardsapp.go#L82 `IsPlugin` is hardcoded to `true` here? Shouldn't it be dynamically decided depending on where it is called from?

That "isPlugin" differentiates from personal-server SKU.  In this case MPA mode is still "plugin=true".  We'll clean up the naming of these flags when we rip plugin support out.

**Comment by wallyf1972** [comment]
Approved

**Pull request closed without merging**
