### PR TITLE
[MM-40778] Fix select queries for GroupStore

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Fixes select queries for GroupStore.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40778

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by streamer45** [comment]
This is the backward compatible way of fixing the issue although I think we should decide if it's worth it. The change was introduced in version 5.6 so it's been a long time. I am thinking that https://github.com/mattermost/mattermost-server/pull/19263 should be enough but happy to hear others opinions. /cc @agnivade

**Comment by isacikgoz** [comment]
Actually the reason why I created this PR is to fix this issue for 6.2 and 6.3 dot releases and then apply the migration for upcoming 6.x versions. But yeah the more opinions on this the healthier solution can emerge. 0/5 on either anyway :)

**Comment by agnivade** [comment]
I agree that #19263 should be enough. Maybe we can selectively cherry-pick this PR only for the dot releases and keep master clean?

**Comment by amyblais** [comment]
@isacikgoz Sven mentioned that this is enough for v6.3 (cherry-pick for https://github.com/mattermost/mattermost-server/pull/19263 is done) and is not needed for previous versions https://community.mattermost.com/core/pl/xbmquz8oa7raxm3dz5mhxt3qfw. Not sure if this PR is still needed.

**Comment by isacikgoz** [comment]
@amyblais if customers are OK with upgrading to 6.3 or running the script, it's fine by our side. Closing the PR.

**Pull request closed without merging**
