### PR TITLE
update prepackage boards to v7.8.0

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update pre-package boards to v7.8.0

#### Ticket Link
  Fixes https://github.com/mattermost/focalboard/issues/4471

#### Release Note
```release-note
Update prepackaged boards version to v7.8.0
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]

**Review by mgdelacroix — APPROVED** [review]

**Comment by sbishel** [comment]
@amyblais This need cp'ed to `cloud`. Right?

 What about `cloud-2023-02-02-backup` or does that get recreated?

**Comment by amyblais** [comment]
> @amyblais This need cp'ed to `cloud`. Right?
> 
> What about `cloud-2023-02-02-backup` or does that get recreated?

Just ``cloud`` is fine. A new release tag  will be created.

**Pull request merged**
