### PR TITLE
MM-46408: adds PostPriority feature flag and admin setting

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Adds the PostPriority feature flag. You can enable it by setting the
env variable `MM_FEATUREFLAGS_POSTPRIORITY=true`.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-46414

#### Release Note

```release-note
Added a new feature flag PostPriority.
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by vish9812 — APPROVED** [review]

**Comment by jgilliam17** [comment]
/e2e-test MM_ENV="MM_FEATUREFLAGS_POSTPRIORITY=true","MM_SERVICESETTINGS_POSTPRIORITY=true"

**Comment by saturninoabril** [comment]
/e2e-test MM_ENV="MM_FEATUREFLAGS_POSTPRIORITY=true,MM_SERVICESETTINGS_POSTPRIORITY=true"

**Comment by saturninoabril** [comment]
/e2e-test MM_ENV="MM_FEATUREFLAGS_POSTPRIORITY=true,MM_SERVICESETTINGS_POSTPRIORITY=true"

**Comment by saturninoabril** [comment]
/e2e-test MM_ENV="MM_FEATUREFLAGS_POSTPRIORITY=true,MM_SERVICESETTINGS_POSTPRIORITY=true"

**Review by jgilliam17 — APPROVED** [review]
Tested, looks good to merge.
Both, webapp and server PRs were tested on the server created on this PR.

**Pull request merged**
