### PR TITLE
Pre-package Playbooks v1.32.7 to v7.4

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package Playbooks v1.32.7 to v7.4

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-47981
Fixes: https://mattermost.atlassian.net/browse/MM-48007
Fixes: https://mattermost.atlassian.net/browse/MM-48008

#### Release Note
```release-note
Pre-package Playbooks v1.32.7
```

### CODE REVIEW

**Comment by lieut-data** [comment]
@amyblais, are there any other v7.4 patches with which to coordinate?

**Comment by amyblais** [comment]
There are some security and bug fixes that we're ready to backport as soon as the release branch issues have been fixed https://mattermost.atlassian.net/browse/MM-48430.

**Comment by amyblais** [comment]
@lieut-data Looks like 7.4 is now fixed. Please add reviewers as needed.

**Review by trilopin — APPROVED** [review]

**Review by gbochora — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Tested and looks good to me. Thanks Jesse!

**Pull request merged**
