### PR TITLE
introduce jenkins prepackaged v1.0.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

Releasing Jenkins prepackaged as v1.0.0

### CODE REVIEW

**Comment by crspeller** [comment]
@mickmister I think you accidentally committed some extra files. Please remove.

**Comment by mickmister** [comment]
@crspeller thanks fixed :+1:

**Comment by mickmister** [comment]
@crspeller it looks like there is a formatting issue with `app/diagnostics.go`. It looks like it's a whitespace issue because I don't see a difference between the two lines in the picture. `go vet github.com/mattermost/mattermost-server/app` passes for me locally on this branch.

image

**Comment by mickmister** [comment]
@crspeller nvm `go fmt` fixed the whitespace issue

**Comment by crspeller** [comment]
Ya. That was fixed by https://github.com/mattermost/mattermost-server/pull/11891

**Comment by amyblais** [comment]
@mickmister Was this cherry-picked?

**Comment by mickmister** [comment]
@amyblais Yes it was cherry-picked here https://github.com/mattermost/mattermost-server/pull/11894

**Pull request merged**
