### PR TITLE
Update jobs.go

### PR DESCRIPTION
**Pull request by VelamuriPrasad**
#### Release Note

```release-note
```

### CODE REVIEW

**Comment by hanzei** [comment]
@VelamuriPrasad Is there a specific ticket that this change is build for?

**Comment by VelamuriPrasad** [comment]
Show*On Oct 23, 2020 2:50 PM, velamurip@yahoo.com wrote:Yeah to die the status of application for job seekers I added another method... On Oct 23, 2020 2:15 PM, Ben Schumacher <notifications@github.com> wrote:
@VelamuriPrasad Is there a specific ticket that this change is build for?

**Comment by VelamuriPrasad** [comment]
Yeah to die the status of application for job seekers I added another method... On Oct 23, 2020 2:15 PM, Ben Schumacher <notifications@github.com> wrote:
@VelamuriPrasad Is there a specific ticket that this change is build for?

**Comment by jfrerich** [comment]
@VelamuriPrasad, can you please share the Jira ticket or Github issue that your PR references?

**Comment by jasonblais** [comment]
@VelamuriPrasad Thanks for the pull request! We appreciate your contribution, but these changes do not appear to be applicable at this time.

If you are looking for good ways to contribute, see https://mattermost.com/contribute/ to get started.

If there was a GitHub issue or Jira ticket you made these changes, let us know and we're happy to review.

**Pull request closed without merging**
