### PR TITLE
Add missing wrapped errors

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
There are a couple of places where `model.NewAppError` doesn't wrap a returned `error`. This makes debugging harder.

I stumbled across this when debugging an issue in `app/user.go` and decided to fill all other occurrences that I found. The regex I've used is `err != nil \{\n\t+return model.NewAppError\("[a-zA-Z]+", "[a-zA-Z._]+", nil, ""`. Please note that this is surely not an _exhaustive_ fix, but rather a one time afford. 

#### Ticket Link
https://community-daily.mattermost.com/core/pl/3aya19tnmirabcuxjy7jznmejo

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by streamer45** [comment]
Awesome, thank you @hanzei :+1: 

> Please note that this is surely not an exhaustive fix, but rather a one time afford.

I am wondering how feasible it would be to write a vet check for this. In any case it's something to keep in mind when reviewing.

**Review by streamer45 — APPROVED** [review]

**Review by agnivade — APPROVED** [review]

**Comment by hanzei** [comment]
@streamer45 That is surely feasible, but I've shied away from it due to the mana required.

**Comment by streamer45** [comment]
No worries, that was more of an open question to ourselves (server team). If doable, it might be a good help-wanted candidate.

**Pull request merged**
