### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by crspeller**
Enterprise: https://github.com/mattermost/enterprise/pull/375

Also updates gomail to a maintained fork: https://mattermost.atlassian.net/browse/MM-13022

### CODE REVIEW

**Comment by hanzei** [comment]
Why did `"github.com/sirupsen/logrus` and `github.com/blang/semver` got removed?

**Comment by hanzei** [comment]
@crspeller We use `logrus` and `semver` directly in the codebase. Hence we might want to upgrade there versions explicitly.

I think all directly imported dependencies should be stated in `Gopkg.toml`. This way we can remove  `Gopkg.lock` and regenerate if needed.

**Comment by crspeller** [comment]
Yes. And if we need to explicitly upgrade them we can add them. The idea of how we use the `Gopkg.toml` is to specify exceptions to the general rule of "use the most recent release".

**Comment by hanzei** [comment]
> The idea of how we use the `Gopkg.toml` is to specify exceptions to the general rule of "use the most recent release".

Thanks for the information. I didn't know this.

**Pull request merged**
