### PR TITLE
[MM-28123] app/post: continue to loop in case of an error

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
We should break the execution if we get an error here. Dug this from a sentry report.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28123

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Nice one :+1:

**Review by jespino — APPROVED** [review]
Very good one :)

**Comment by jespino** [comment]
@isacikgoz I'm not 100% sure if this needs QA I added the label, feel free to remove it or assign the QA person based on your own criteria.

**Comment by isacikgoz** [comment]
@jespino Thanks for the heads up, I believe we notify QA in any case and let them label this with `QA:Deferred` if it is necessary :)

**Review by lindalumitchell — APPROVED** [review]

**Pull request merged**
