### PR TITLE
issue #7775: Do not auto-join 'off-topic' channel if it is private

### PR DESCRIPTION
**Pull request by liusy182**
#### Summary
Do not auto-join 'off-topic' channel if it is private channel.
This PR contains server side change for issue #7775 

Corresponding client side PR:
https://github.com/mattermost/mattermost-webapp/pull/418

#### Ticket Link
#7775 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @liusy182! Testing will be completed on the webapp PR, moving this to dev review

**Comment by liusy182** [comment]
On my end I am seeing the rebase has been made successfully. Did I do something wrong or the rebase hook needs to be rerun?

**Comment by hmhealey** [comment]
@liusy182 If you've rebased on your end, you'll need to do a `git push -f` to see the changes here

**Comment by liusy182** [comment]
Looks like I have completely messed up the rebase. I will try to fix it later in the day.

**Comment by liusy182** [comment]
@hmhealey can u help to trigger CI jobs again? My local rebase has been forcefully pushed but the system is not updating.

**Comment by hmhealey** [comment]
Closing and reopening to trigger a new build

**Comment by hmhealey** [comment]
It looks like your PR still needs to be rebased. I checked out your branch locally, and it looks like you've rebased off of your copy of the master branch which is out of date. You'll need to update your master branch to the latest (some instructions are [here](https://help.github.com/articles/syncing-a-fork/)) before rebasing so that it picks up the latest changes.

**Comment by liusy182** [comment]
Thanks @hmhealey ! It turns out I set up my upstream branch wrongly to my own branch :(

**Comment by hmhealey** [comment]
Ah, that would do it. I'm glad I don't have to work with an upstream branch since they're a pain to work with sometimes :)

It looks like the PR is failing on an unrelated unit test, so I'm going to re-run everything
```
--- FAIL: TestRemoveChannel (0.74s)
	assertions.go:229: 
                        
	Error Trace:	platform_test.go:37
		
			channel_test.go:36
		
	Error:		Received unexpected error exit status 2
		
	Messages:	[2017/12/13 14:50:43 UTC] [INFO] Configuration change detected, reloading log settings
		panic: send on closed channel
		
		goroutine 2150 [running]:
		github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go.(*ConsoleLogWriter).LogWrite(0xc422008000, 0xc4221ce240)
			/home/ubuntu/jenkins/workspace/mattermost-platform-pr-split/src/github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go/termlog.go:41 +0x43
		github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go.Logger.intLogf(0xc420082cf0, 0x4, 0xc421e526e0, 0xaa, 0x0, 0x0, 0x0)
			/home/ubuntu/jenkins/workspace/mattermost-platform-pr-split/src/github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go/log4go.go:223 +0x289
		github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go.Info(0x12dff20, 0xc4221d1430, 0x0, 0x0, 0x0)
			/home/ubuntu/jenkins/workspace/mattermost-platform-pr-split/src/github.com/mattermost/mattermost-server/vendor/github.com/alecthomas/log4go/wrapper.go:195 +0x1bc
		github.com/mattermost/mattermost-server/utils.InitializeConfigWatch.func1()
			github.com/mattermost/mattermost-server/utils/_obj/config.go:294 +0x4bc
		created by github.com/mattermost/mattermost-server/utils.InitializeConfigWatch
			github.com/mattermost/mattermost-server/utils/_obj/config.go:280 +0x119
		
		
[2017/12/13 14:50:43 UTC] [INFO] Server stopped
```

**Pull request merged**
