### PR TITLE
Fix/conflicts transl

### PR DESCRIPTION
**Pull request by spirosoik**
#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by spirosoik** [comment]
@pfltdv @DSchalla please have a look

**Review by pfltdv — COMMENTED** [review]
@spirosoik, Json structure and files are ok. But some resource files does not have url modification ie. `api.command_invite.channel.error` (https://about.mattermost.com/default-channel-handle-documentation). But old url redirects to new address. Do we have a plan to keep old url redirected until all translation files contains new url ?

**Comment by spirosoik** [comment]
> @spirosoik, Json structure and files are ok. But some resource files does not have url modification ie. `api.command_invite.channel.error` (https://about.mattermost.com/default-channel-handle-documentation). But old url redirects to new address. Do we have a plan to keep old url redirected until all translation files contains new url ?

@cwarnermm as you have more context for links

**Comment by cwarnermm** [comment]
@spirosoik - Yes, there are redirects in place for all legacy domains and URLs. This is something Marketing set up and those redirects will be in place for quite some time to ensure that there's always a backup way to get users to the correct destination URL. 

If I'm understanding this issue correctly, there are additional legacy links that need updates related to our APIs?

**Review by pfltdv — APPROVED** [review]
LGTM.

**Review by DSchalla — APPROVED** [review]

**Pull request merged**
