### PR TITLE
Update DockerFile to Ubuntu LTS Base Image

### PR DESCRIPTION
**Pull request by DSchalla**
#### Summary
Update Docker Base Image to Ubuntu 22.04 LTS and remove apt pinning as the Debian Base Image in order to remediate outstanding CVEs in our Docker image.

#### Ticket Link
https://mattermost.atlassian.net/browse/SEC-3562

#### Release Note
```release-note
Updated Docker Base Image from Debian to Ubuntu 22.04 LTS
```

### CODE REVIEW

**Review by esarafianou — APPROVED** [review]

**Comment by phoinixgrr** [comment]
🚀
No objections merging this, upon e2e testing completed.

**Review by agnivade — COMMENTED** [review]
Overall, I will defer to you, but there was a reason we pinned the dependencies: https://github.com/mattermost/mattermost-server/pull/20901

**Comment by agnivade** [comment]
> No concerns around the impact on Mattermost Server?

As long as we are able to build successfully, no concerns from my side :)

**Review by agnivade — APPROVED** [review]

**Comment by phoinixgrr** [comment]
This recommendation about dependencencies, was initiated by using [hadolint](https://github.com/hadolint/hadolint) to lint dockerfiles. 
Was introduced with this PR: https://github.com/mattermost/mattermost-server/pull/20807 

I'd go with unpinning the dependencies, simplifying this process.

**Review by phoinixgrr — APPROVED** [review]

**Comment by phoinixgrr** [comment]
Cypress e2e tests failing with: 
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[452:0420/115940.966218:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

We may need to disable GPU acceleration, since running on non GPU nodes. 
```
env:
  ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'
```

Looping in QA @saturninoabril

**Review by iyampaul — APPROVED** [review]

**Comment by saturninoabril** [comment]
fyi, Mario is looking into this and fixing E2E pipeline. Will defer for his review (will add once his GH access is re-activated).

**Comment by phoinixgrr** [comment]
@mvitale1989 Got your back :)

**Comment by mvitale1989** [comment]
Thank you @phoinixgrr :smile: 
Looks good to merge for me

**Review by mvitale1989 — APPROVED** [review]

**Comment by DSchalla** [comment]
@spirosoik Resolved the merge conflict, after the tests pass can you take a look? Thanks!

**Review by spirosoik — APPROVED** [review]
LGTM

**Comment by DSchalla** [comment]
@spirosoik Can you confirm which branches we must cherrypick this change? cloud and `release-7.8`?

**Comment by spirosoik** [comment]
We need `cloud`, `cloud-latest`. I think we discussed we want to add in `release-7.10` right?

**Comment by DSchalla** [comment]
release-7.11 which wasn't cut yet is early enough, 7.8 I'd say to add it in the ESR build. So overall let's do

- [ ] master
- [ ] release-7.8
- [ ] cloud
- [ ] cloud-latest

So that 7.11, Cloud, and 7.8 as ESR have the new base image. What you think?

**Comment by amyblais** [comment]
@DSchalla Feel free to do the cherry-picks (likely this needs manual cherry-picks). Not sure if https://github.com/mattermost/enterprise/pull/1429 needs to be cherry-picked at the same time.

**Comment by cwarnermm** [comment]
@amyblais @DSchalla - Is there any outstanding documentation effort needed for this PR from your perspective?

**Comment by amyblais** [comment]
@cwarnermm You had suggested here to update the Docker Readme file https://github.com/mattermost/docs/pull/6369#discussion_r1259686143. I'll defer to Daniel if this needs to be done.

**Comment by spirosoik** [comment]
@DSchalla it's not deprecated we still maintain it

cc @nab-77

**Pull request merged**
