### PR TITLE
[MM-52574] Add back PermissionUseSlashCommands

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
https://github.com/mattermost/mattermost-server/pull/22819 introduce a regression, that causes server which import the load-test DB dump to fail on startup.

As part of the migrations that happen on every server start, all roles [get fetched from the store](https://github.com/mattermost/mattermost-server/blob/cfa5be4d3e0da608d0f0cb3cacc5925ce2a864b3/server/channels/app/permissions_migrations.go#L1140-L11449). These roles do contain the legacy permission `use_slash_commands`, as it's still in the DB.

Later, the roles [get saved in the DB](https://github.com/mattermost/mattermost-server/blob/cfa5be4d3e0da608d0f0cb3cacc5925ce2a864b3/server/channels/app/permissions_migrations.go#L231) again (which in most cases is a no-op). As part of that, [it's checked if the permissions of the role are known](https://github.com/mattermost/mattermost-server/blob/cfa5be4d3e0da608d0f0cb3cacc5925ce2a864b3/server/public/model/role.go#L697-L703). This check fails for `use_slash_commands`, as the permission does not longer exist in the code.

This PR adds the permission back, therefore fixing the role check.

I did test the changes against the load-test DB dump and can confirm the server starts without an issue.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52574

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Thanks, @hanzei!

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@hanzei Does this need QA review?

**Comment by hanzei** [comment]
@DHaussermann Could you please test this PR for regressions?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Legacy permission still not available in the UI (as expected)
- No issue with current permission functionality for edit slash command 
- No sign of any migration issues when upgrading an existing server to this PR. Looks seem normal.

LGTM!

**Comment by hanzei** [comment]
@amyblais Into which branches does this PR need to be cherry-picked?

**Comment by amyblais** [comment]
I'll cherry-pick it to the cloud branch tomorrow.

We had to revert recent commits from the cloud branch to prepare a patch release, and we'll be restoring those commits tomorrow, and then I can cherry-pick this.

**Pull request merged**
