### PR TITLE
MM-14795 Added "from_webhook" to protected props in DoPostAction

### PR DESCRIPTION
**Pull request by levb**
Per @hanzei's request
- https://github.com/mattermost/mattermost-server/pull/10546#issuecomment-481997493
- https://mattermost.atlassian.net/browse/MM-14795

### CODE REVIEW

**Comment by jasonblais** [comment]
> but this also means that the plugin will no longer be able to change this value

You mean plugins cannot override the username and icon URL?

**Comment by levb** [comment]
@jasonblais 
1) the username/icon overrides are old logic, did not change with any of these PRs.
2) these are (now 3) properties to preserve if DoPostAction updates the original post by means of returning an `Update` post value.
3) if the plugin absolutely needs total control, it always has the option of using `p.API.UpdatePost` itself, and return a nil `Update` value.

**Comment by hanzei** [comment]
> but this also means that the plugin will no longer be able to change this value

Please note that integrations were not able to do before https://github.com/mattermost/mattermost-server/pull/10546. Hence this PR is **not** a breaking change.

**Comment by jasonblais** [comment]
Thanks all! Looks good. With #10546 and #10593, let's make sure we just document everything well before we ship 5.12

**Comment by hanzei** [comment]
@jasonblais Just to double check: https://github.com/mattermost/mattermost-server/pull/10546 is marked for v5.11 and this PR for v5.12. Can these two PR go into v5.11?

**Comment by jasonblais** [comment]
@hanzei Yes, 5.11 is fine 👍

**Pull request merged**
