### PR TITLE
wip: Improves on MM-28949

### PR DESCRIPTION
**Pull request by levb**
#### Summary
TO BE EDITED

In the ticket there is a discussion that concurrent HTTP downloads of plugins have increased the memory utilization.

I am having a difficult time testing locally at the moment, pushing the draft PR to run tests and to ask for opinions, or maybe someone can take over/help with the testing?

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28949

### CODE REVIEW

**Comment by levb** [comment]
@hanzei I can appreciate help tracking down the source of the test failures - they seem to be passing locally with go test, and `make test` appears substantially broken for me for reasons not understood. In general, this is not a tested PR, more an illustration of concept.

I may have missed one another needed Tee to extract, maybe? Then why are the api4 tests passing locally?..

**Review by hanzei — CHANGES_REQUESTED** [review]
I did test the PR on the test server using my script. I can still crash the pot. It's also worth pointing out that no plugin can be successfully installed. They all error with `Unable to verify plugin signature`. I can reproduce that issue locally.

Without that issues beein fixed, it's hard to estimate if this PR is an improvment.

**Comment by levb** [comment]
See https://github.com/mattermost/mattermost-server/pull/15616 - the general UploadFile is getting a facelift

**Comment by isacikgoz** [comment]
Gentle ping on this @levb, do you plan to continue working on this? (I'm trying to clean the stale PRs therefore I'm asking)

**Pull request closed without merging**
