### PR TITLE
MM-31105 /Join <channel name> is case sensitive 

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

make join case insensitive

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-31105

#### Release Note

```release-note
`/join` command is now case-insensitive
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by ashishbhate — APPROVED** [review]

**Comment by ogi-m** [comment]
@reflog The command now opens the channel in a new tab, which is especially inconvenient in the desktop app where it will open a browser window.

**Comment by reflog** [comment]
@ogi-m - that is rather bizzare, surprising that my change affected this. Can you confirm please that this behavior doesn't happen on master?

**Comment by ogi-m** [comment]
@reflog - confirmed, it doesn't happen on master 🤔

**Comment by reflog** [comment]
@ogi-m - thanks, I'll check what's happening there

**Review by ogi-m — APPROVED** [review]
Approving since the issue turned out to be unrelated to the PR 👍🏻

**Pull request merged**
