### PR TITLE
[MM-51881] : btn-primary SCSS leaves button white when not focussed

### PR DESCRIPTION
**Pull request by hchorfispiria**
#### Summary
Fixing Matterpoll button votes visibility

#### Ticket Link

  Fixes https://github.com/mattermost/mattermost-server/issues/22776
  https://mattermost.atlassian.net/browse/MM-51881

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]
Thanks @hchorfispiria it looks good, I see a lint error that might be related to some recent changes on master that your fork might need. Could you try to update it?

**Review by BenCookie95 — APPROVED** [review]

**Comment by furqanmlk** [comment]
update-branch

**Review by BenCookie95 — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@yasserfaraazkhan can you create an upstream branch to create a test server

**Comment by hchorfispiria** [comment]
@yasserfaraazkhan I created the upstream branch
Anybody can approve it?

**Review by yasserfaraazkhan — APPROVED** [review]
thank you for the changes,
e2e have passed on this pr https://github.com/mattermost/mattermost-server/pull/23503

**Comment by lindy65** [comment]
Hi @BenCookie95
I'm on PTO until 12 June
Please assign another QA, Thanks 😊

**Pull request merged**
