### PR TITLE
MM-40148: threadsOnly query param for user threads

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

Currently we always calculate counts when fetching user threads.
Those counts include total, unread replies, and unread mentions,
and are potentially expensive to calculate.

This commit adds a new query param 'threadsOnly' which won't calculate
any counts and just return threads.

This PR is the same as https://github.com/mattermost/mattermost-server/pull/19349, but built on top of https://github.com/mattermost/mattermost-server/pull/19709. 

**Related WebApp PR:** https://github.com/mattermost/mattermost-webapp/pull/10064
#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-40148

#### Release Note

```release-note
Added a threadsOnly query parameter for getting user threads
```

### CODE REVIEW

**Comment by ashishbhate** [comment]
The original PR was from Kyriakos' fork. I've pushed a separate PR to the mattermost org so I can make changes easily.

**Comment by ashishbhate** [comment]
Opening this PR up for review. Functionally it is the same as https://github.com/mattermost/mattermost-server/pull/19349, but built on top of https://github.com/mattermost/mattermost-server/pull/19709. 

I think this PR can go in as is, and we can add additional perf optimizations on top of this in later PRs.

**Review by agnivade — APPROVED** [review]
Nice!

**Review by lieut-data — APPROVED** [review]
:tada:

**Comment by ashishbhate** [comment]
I've updated the webapp PR that goes with this server PR. After the webapp PR is reviewed, I'll request a QA review for both PRs together.

**Review by jgilliam17 — APPROVED** [review]
Tested on related webapp PR.

**Pull request merged**
