### PR TITLE
[MM-10867] Clean up and add thorough tests to app/notification.go 

### LINKED ISSUE #8942: Clean up and add thorough tests to app/notification.go
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-17130)

Clean/split up the `sendNotification` and other large functions in app/notification.go into smaller, more testable functions. Then add tests for these functions to throughly test as many cases as possible.

Goal here is to reduce the chances of a bug being introduced into the complex and critical notification code paths by reducing complexity and thoroughly testing with unit tests.

### PR DESCRIPTION
**Pull request by fedealconada**
#### Summary
This PR is basically trying to refactor a bit `notification.go`.
I have tried to add as many commits as possible. Most of the changes are about renaming, moving functions around and splitting functions.

Moreover, while I was working on this, there were some new changes pushed to `notification.go` so you will see the merge commit when I have updated to branch.

There are still some parts of the file not tested, specifically:
- getMentionedUsersFromOtherChannels
- splitAtFinal
- sendNoUsersNotifiedByGroupInChannel 
- sendChannelWideMentionsDisabledPost
- sendPushNotifications
- createNewPostEvent 
- makeOutOfChannelMentionPost

The PR is getting large, I could work on the remaining tests if we manage to merge these changes. 

#### Ticket Link
Fixes #8942

### CODE REVIEW

**Comment by jasonblais** [comment]
@fedealconada  Deep apologies for such a long reply time. This PR slipped our queue and our `mattermod` reminders for stale PRs was broken. I'm queuing this PR for dev review now. Huge thank you for your contribution 🙏

**Comment by agnivade** [comment]
@fedealconada - Would you be able to fix the merge conflicts and update the PR? We can get to reviewing then :)

**Comment by jasonblais** [comment]
@fedealconada - Let us know if you have any questions about resolving the merge conflicts and update the PR. Happy to help :) Thanks for the contribution!

**Comment by hanzei** [comment]
@fedealconada 
Please note that we will close this PR after another 10 days of inactivity. If you don't object, other contributors might complete this PR for you. Let me know if you need any help resolving the merge conflict.

**Comment by fedealconada** [comment]
@hanzei sorry for the delay on responding to this. I'm a bit packed at the moment and its been a while since I've done these changes. I'd prefer somebody else to pick it up and continue it. Sorry about that :/

**Comment by hanzei** [comment]
@isacikgoz Could someone from your team pick this up or do you think the amound of merge conflicts is just to much?

**Comment by isacikgoz** [comment]
Finally I got the chance to review this PR! @fedealconada Thanks for the effort that you put into this! Since this PR is submitted _very_ long time ago, there are a lot of conflicts, changes in the code so I'd rather to start over for the refactoring.

As for the PR review; I appreciate the effort making code more readable and reorganizing the file. Also renaming variables to be more convenient is a good start too! However, the PR lacks some granular tests as required from the ticket. The goal here is to be able to have more control over `(*App).SendNotifications()` method. 

@hanzei Since the contributor is not able to continue this, I am closing this PR. In fact, we may want to remove this ticket from `Help Wanted` tickets since it could be a quite complicated to ask from the community.

**Pull request closed without merging**
