### PR TITLE
handle all JSON marshal errors in model/client4.go

### PR DESCRIPTION
**Pull request by Ballista01**
#### Summary

This PR adds code to all JSON marshal errors in model/client4.go.

When a error found when marshaling, the method will return nil response and an error created by ```NewAppError```

Here's the pattern to handle JSON marshal errors:
```
	<payload>, jsonErr := json.Marshal(request)
	if jsonErr != nil {
		return <nil method responses>, NewAppError(<method name in string>, "api.marshal_error", nil, jsonErr.Error(), http.StatusInternalServerError)
	}
```
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/20342

Mattermost:
https://mattermost.atlassian.net/browse/MM-40710
#### Release Note
<!--
Add a release note for each of the following conditions:

* Config changes (additions, deletions, updates)
* API additions—new endpoint, new response fields, or newly accepted request parameters
* Database changes (any)
* Websocket additions or changes
* Anything noteworthy to a Mattermost instance administrator (err on the side of over-communicating)
* New features and improvements, including behavioural changes, UI changes and CLI changes
* Bug fixes and fixes of previous known issues
* Deprecation warnings, breaking changes, or compatibility notes

If no release notes are required write NONE. Use past-tense. Newlines are stripped.

Examples:

```
Added new API endpoints POST /api/v4/foo, GET api/v4/foo, and GET api/v4/foo/:foo_id.
```

```
Added a new config setting ServiceSettings.FooBar. Added a new column Foo to the Users table.
```

```
NONE
```

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
One error check is missing in L4162. Everything looks good otherwise!

**Comment by agnivade** [comment]
Hi @Ballista01 - just checking on this one. Let us know if you need any help.

**Comment by Ballista01** [comment]
> One error check is missing in L4162. Everything looks good otherwise!

Oops: /
Sorry I overlooked that

**Comment by Ballista01** [comment]
> Hi @Ballista01 - just checking on this one. Let us know if you need any help.

np, just been busy with an aws exam recently.
If there's anymore problem just let me know : )

**Comment by Ballista01** [comment]
> Hi @Ballista01 - just checking on this one. Let us know if you need any help.

I see 
```func (c *Client4) RequestCloudTrial(email *ValidateBusinessEmailRequest) (*Subscription, *Response, error)```
has changed into
```func (c *Client4) RequestCloudTrial(email *StartCloudTrialRequest) (*Subscription, *Response, error)```

Shall I add another commit to change ```email *ValidateBusinessEmailRequest``` to ```email *StartCloudTrialRequest```?

**Comment by agnivade** [comment]
@Ballista01 - yes let's do that

**Review by agnivade — APPROVED** [review]
Nice work!

**Pull request merged**
