### PR TITLE
MM-40818: Pass filestore to channels

### PR DESCRIPTION
**Pull request by agnivade**
We move away from referencing server struct
but pass the filestore service to Channels
explicitly.

https://mattermost.atlassian.net/browse/MM-40818

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
I did not implement the `Namer` interface because the interface was defined in the shared/filestore package itself. But let me know if you prefer to have it. Should be simple enough to embed the interface within another.

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
@saturninoabril - this job failed to run for some reason, can you check?

**Comment by agnivade** [comment]
Ping @saturninoabril

**Comment by agnivade** [comment]
Help needed here as well @jgilliam17 :)

**Comment by jgilliam17** [comment]
Re-running E2Es, will check when report is posted.

**Comment by jgilliam17** [comment]
[E2E report](https://automation-dashboard.vercel.app/cycles/64ea8308-7d29-4e18-8e35-30e6655d1186) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
