### PR TITLE
MM-15325: Allowing to configure the device for detect the IP in HA clusters

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Allowing to configure the device for detect the IP in HA clusters

#### Ticket Link
[MM-15325](https://mattermost.atlassian.net/browse/MM-15325)

Corresponding enterprise PR mattermost/enterprise#438

### CODE REVIEW

**Comment by jespino** [comment]
@coreyhulen I added you here because you were the original creator of the code, but I added two more reviewers, so... feel free to not review it if you can't.

**Comment by jespino** [comment]
Yes sorry, here it is: mattermost/enterprise#438

**Comment by coreyhulen** [comment]
We should make sure this soaks on community.

**Comment by jasonblais** [comment]
@amyblais we should add changelog and docs for the config settings

**Pull request merged**
