### PR TITLE
[MM-51489]: Fix issue with compact message mode

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Fix issue with compact message mode

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-51489
  Fixes https://github.com/mattermost/mattermost-server/issues/22551

### Screenshots
| Before | After |
| ------ | ------ |
| Screenshot 2023-03-28 at 6 22 57 PM | Screenshot 2023-03-28 at 6 17 15 PM |
| Screenshot 2023-03-28 at 6 23 04 PM | Screenshot 2023-03-28 at 6 17 38 PM | 

#### Release Note

```release-note
- Fix issue with compact message mode
```

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@AshishDhama Found a few issues that need clarification, on the cloud test server above:

1. On consecutive posts, names are being duplicated when they should not. (CRT Enabled and disabled)
Screenshot 2023-03-29 at 12 24 09 PM
Screenshot 2023-03-29 at 12 30 33 PM


2. On RHS names and update your status is being duplicated (CRT Enabled and Disabled)
Screenshot 2023-03-29 at 12 24 00 PM
Screenshot 2023-03-29 at 12 30 40 PM

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
See comments below.

**Comment by AshishDhama** [comment]
@asaadmahmood As discussed in community, 
- [x] 1. Is due to this [pr-mattermost-webapp-9668](https://github.com/mattermost/mattermost-webapp/pull/9668)
[MM-41114](https://mattermost.atlassian.net/browse/MM-41114)
So will be keeping as it is right now.
- [x] 2. I have fixed

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Review by harshilsharma63 — CHANGES_REQUESTED** [review]
Current code changes look fine but the same fix needs to be applied to RHS as well.

**Comment by AshishDhama** [comment]
@harshilsharma63 This is how it was in 7.7
https://ashish74.test.mattermost.cloud/captain/threads/an8whx49u3yj7rwtyf7fujt8fy

Username | Password | Note
-- | -- | --
sysadmin | Sys@dmin123 | Admin user
user | User@123 | Regular user

**Review by harshilsharma63 — APPROVED** [review]
The fix for RHS can be done in a separate PR, later on.

**Review by kostaspt — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working fine

**Comment by amyblais** [comment]
@AshishDhama Please help open manual cherry-picks for ``release-7.10``, ``release-7.9`` and ``cloud`` branches.

**Pull request merged**
