### PR TITLE
[MM-46216] P3 Bugfix - Oauth redirectURI with query parameters generates malformed redirect URL

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

Since oauth handlers append parameters to a string, the callback URL is malformed if it already has query parameters. This change uses `net/url` to handle the issue.

Note that query parameters are accepted while _registering_ OAuth callback URLs [reference](https://datatracker.ietf.org/doc/html/rfc6749#section-3.1.2)

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/20716
#### Release Note

```release-note
Fixed a bug in OAuth service which generated malformed redirect URLs if the registered Callback URLs already had static query parameters.
```

### CODE REVIEW

**Comment by furqanmlk** [comment]
@plant99 can you please fix conflict?

**Comment by plant99** [comment]
@furqanmlk please review again

**Review by furqanmlk — APPROVED** [review]
Working as expected 
Performed following steps
1. Once you have a mattermost server with o-auth active ( `ServiceSettings:EnableOAuthServiceProvider = true`)
2. Turn 'record session' on in browser console
3. Register following url as callback URL in mattermost and note `Client ID:` after saving.
    `http://localhost:3000/oauth/callback
http://localhost:3000/oauth/callback?xregister=yes&fc=anderchlect`
image
4. Open new browser and navigate to following url
http://mattermost-server-pr-20854.test.mattermost.cloud/oauth/authorize?state=1234&response_type=code&approval_prompt=auto&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth%2Fcallback%3Fxregister%3Dyes%26fc%3Danderchlect&client_id=](http://localhost:8065/oauth/authorize?state=1234&response_type=code&approval_prompt=auto&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth%2Fcallback%3Fxregister%3Dyes%26fc%3Danderchlect&client_id=%3Cclient_id_oauth)<Client ID>

Note: Replace the Client ID with noted value in step # 03.


5. Check Network tab on browser and examine `Requesr Url`. It should have only one `?`
image

**Pull request merged**
