### PR TITLE
MM-49214 : Filter out bot users shown in Apps modal form user pickers

### PR DESCRIPTION
**Pull request by qvarnstr0m**
#### Summary
This issue involves updating the user picker functionality in the Mattermost web app's app framework. Currently, bot users are being displayed in the user picker for forms, which is not desired. The goal is to hide bot users from the user picker dropdown and only show real users. This can be achieved by filtering out any user that is a bot using the user.is_bot property. The necessary changes have been made in the apps_form_select_field.tsx file, specifically in the loadDynamicUserOptions function, which has been updated to filter out bot users using .filter((user) => !user.is_bot).

Manual testing has been done, no new tests have been added, all existing tests have passed.

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost-server/issues/22123
https://mattermost.atlassian.net/browse/MM-49214

#### Release Note

```release-note
Hide bot users in user selector in apps forms
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Thanks for resubmitting this. The original PR is https://github.com/mattermost/mattermost-webapp/pull/12297 for future reference

**Comment by qvarnstr0m** [comment]
> Thanks for resubmitting this. The original PR is [mattermost/mattermost-webapp#12297](https://github.com/mattermost/mattermost-webapp/pull/12297) for future reference

NP, happy I could contribute! Let me know if I need to do anyting further to move this issue along. :)

**Comment by qvarnstr0m** [comment]
Let me know if there is anything I can do to move this pull request forward.

**Comment by M-ZubairAhmed** [comment]
@DHaussermann gentle ping on this one :)

**Comment by M-ZubairAhmed** [comment]
@DHaussermann gentle ping on this one

**Comment by DHaussermann** [comment]
Sorry @qvarnstr0m and @stevemudie for the delay. I can't recall if something blocked me last time I tried to test this. 

Let me take a look.

**Comment by stevemudie** [comment]
Thanks @DHaussermann 

Also, the E2E for this has been triggered twice but for some reason it keeps timing out. Thoughts?

**Comment by DHaussermann** [comment]
@qvarnstr0m thank you for your patience with this. I was able to deploy this locally and confirm that bot accounts are removed form the user pickers in forms 👍 
image

Some quick regression testing here found no issues LGTM!
Thanks for implementing this change.

**Comment by DHaussermann** [comment]
@mickmister note that when passing in values with the command line parser this is still possible.
image

I'm not sure if this now is something we need a separate PR for?

**Comment by mickmister** [comment]
> @mickmister note that when passing in values with the command line parser this is still possible.
> I'm not sure if this now is something we need a separate PR for?

@DHaussermann I suppose we would also want this change for slash commands. But yeah that's definitely out of scope of this PR.

**Comment by mickmister** [comment]
@qvarnstr0m Thanks so much for this improvement :tada:

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by qvarnstr0m** [comment]
> @qvarnstr0m Thanks so much for this improvement 🎉

NP, glad I could be of help! 😄

**Pull request merged**
