### PR TITLE
MM-43780: Adjust getPostThread API for easier pagination

### PR DESCRIPTION
**Pull request by ashishbhate**
#### Summary

- Allow pagination using just `FromCreateAt`, instead of requiring both `FromCreateAt` and `FromPost`. This will enable clients to easily paginate to the middle of a thread of posts, without having to load posts before (or after) the given CreateAt. 

#### Ticket Link

- https://mattermost.atlassian.net/browse/MM-43780

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM ... but please consider adding someone else with more experience as additional reviewer, since I am not too familiar with Go and the codebase

**Comment by ashishbhate** [comment]
>LGTM ... but please consider adding someone else with more experience as additional reviewer, since I am not too familiar with Go and the codebase

Yep, this was more like a heads up about the change. I've requested a review from Agniva to review the actual code.

**Review by agnivade — APPROVED** [review]
Nicely done. Great usage of squirrel.

**Comment by ashishbhate** [comment]
@jgilliam17 The changes in this PR haven't been implemented on the client side yet, but that shouldn't block the reviewing and merging of this PR. The changes in this PR are supposed to be backwards compatible. 
Some smoke testing around the getting posts in a thread should do it for now.

**Comment by amyblais** [comment]
@jgilliam17 Kind reminder that v7.0 feature complete is this Wednesday, May 18th.

**Comment by jgilliam17** [comment]
[E2E report ](https://automation-dashboard.vercel.app/cycles/9ca0f53f-fa62-48e8-bc09-627b4eab42ab)from yesterday show large number of failures. Updating and running again

**Comment by jgilliam17** [comment]
Thanks @ashishbhate 
Tested, looks good to merge.
- Verified/smoke tested threads - no change.
-[ E2E report](https://mattermost-cypress-report.s3.amazonaws.com/198687-5af2dd2-onprem-ent-server-pr-20172-mm-ee-test:5af2dd2/mochawesome.html) looks good, no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Comment by amyblais** [comment]
@ashishbhate Is this for 7.0 or 7.1, or does it matter?

**Comment by ashishbhate** [comment]
>@ashishbhate Is this for 7.0 or 7.1, or does it matter?

It doesn't matter. The webapp/mobile don't use the changes in this PR yet. The changes in this PR are backwards compatible so it can go in any version.

**Pull request merged**
