### PR TITLE
[MM-52681] webapp/channels : Remove 't' functions for defineMessages in channels and update mmjstool version

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
- [X] The support for `defineMessages` is now added in mmjstool, so the `t` functions are not needed anymore.
- [x] Updated the version of mmjstool

~~🏗️ Should be merged after https://github.com/mattermost/mattermost-utilities/pull/73~~

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52681

#### Screenshots
none

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
LGTM, thanks @M-ZubairAhmed !

**Comment by M-ZubairAhmed** [comment]
@yasserfaraazkhan this is the PR in reference to https://github.com/mattermost/mattermost-server/pull/23007#issuecomment-1542158323 comment

**Comment by M-ZubairAhmed** [comment]
I checked out the latest E2E report all the test which failed are marked as flaky. cc @yasserfaraazkhan

**Review by yasserfaraazkhan — APPROVED** [review]
thank you Zubair!

**Pull request merged**
