### PR TITLE
Disambiguates some units.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Small refactor:

* Changes `PostDuration` to `PostDurationDays` (this could probably even be refactored to use `time.Duration` in the future).
* Adds comments to `TeamSettings.UserStatusAwayTimeout` and `ServiceSettings.TLSStrictTransportMaxAge` indicating that their units are seconds.

#### Ticket Link

n/a

#### Release Note

```release-note
NONE
```

#### Related

https://github.com/mattermost/enterprise/pull/1179

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM, just a small suggestion to make it even less ambiguous.

**Review by BenCookie95 — APPROVED** [review]

**Comment by mkraft** [comment]
These tests are all passing locally so I'm wondering if the CI is pulling the enterprise changes.

**Review by BenCookie95 — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
Perfect 👌

**Pull request merged**
