### PR TITLE
Cherry pick of #19610

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Cherry pick of #19610 

#### Ticket Link
None

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@larkox This one seems to fail too. Do we need help from Devops?

**Review by amyblais — APPROVED** [review]

**Comment by larkox** [comment]
@amyblais Seems like the three tests that are failing are flagged as flaky and don't seem related. Not sure if they have to be re-run, or is there any other process for this.

**Comment by amyblais** [comment]
> @amyblais Seems like the three tests that are failing are flagged as flaky and don't seem related. Not sure if they have to be re-run, or is there any other process for this.

@larkox Can the tests be fixed with a code change? Another option might be to just merge the PR if the tests can't be fixed.

**Comment by amyblais** [comment]
@larkox Do you have access to re-trigger the CI?

**Pull request merged**
