### PR TITLE
Removing FilesSearch feature flag

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Removing FilesSearch feature flag

#### Ticket Link
[MM-33136](https://mattermost.atlassian.net/browse/MM-33136)

#### Related Pull Requests
- Has server changes mattermost/mattermost-webapp#8029
- Has mobile changes mattermost/enterprise#988

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]

**Comment by amyblais** [comment]
@jespino I believe Eli is no longer in Mattermost, can you help request someone else's review for these PRs?

**Comment by amyblais** [comment]
@ogi-m Kind note to review these PRs or let me know any concerns.

**Review by reflog — APPROVED** [review]
missing license on the test, otherwise, looks good :)

**Comment by amyblais** [comment]
@esethna Should this also be cherry-picked to the cloud branch for Cloud May 5th release?

**Comment by esethna** [comment]
@amyblais probably not necessary, as long as it's in for the on-prem v5.35 release

**Pull request merged**
