### PR TITLE
Add ChannelId and TeamId to PostActionIntegrationRequest

### PR DESCRIPTION
**Pull request by Hanzei**
#### Summary
This PR adds a `ChannelId` and `TeamId` field to `model.PostActionIntegrationRequest`.

### Ticket Link
See https://pre-release.mattermost.com/core/pl/se1g1wck47raxp9ui91fwtuc4w

### CODE REVIEW

**Comment by jwilander** [comment]
@Hanzei mind adding a couple quick tests cases to `TestPostAction` in `app/post_test.go`?

**Comment by Hanzei** [comment]
Sure I can do this, but can't start this until next week. I can submit a new PR for the tests or include them into this one.

**Comment by jwilander** [comment]
@jasonblais we'll need to add this to the docs

**Comment by jasonblais** [comment]
Sure thing, added https://github.com/mattermost/docs/pull/2294

Big thanks @Hanzei for the contribution.

**Pull request merged**
