### PR TITLE
Replication lag hotfix

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Hotfix for some replication lag issues. The cherry-picks weren't feasible, so this PR recreates the changes from https://github.com/mattermost/mattermost-server/pull/16888.

The changes are in 3 commits:

* Actual customer-facing code changes.
* Updates to test files.
* Tooling changes (needed for QA).

#### Release Note

```release-note
Hotfixed the changes for some replication issues.
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Are we doing this especially for ESR?

**Comment by mkraft** [comment]
> Are we doing this especially for ESR?

There's a discussion at https://community-daily.mattermost.com/private-core/pl/oekeex5os3gg9ejtb3mmcwpafw about which option to proceed with:

1. leave this branch un*used* (close this PR) and these fixes can just be available in v5.34
1. leave this branch un*merged*, but the branch can be used to make a custom build for Dancing Penguin
1. merge this branch into `release-5.31` as a hotfix for the ESR

**Review by sbishel — APPROVED** [review]
Compared to earlier PR and existing code. It appears all here. LGTM

**Comment by sbishel** [comment]
@mkraft - There are some failing tests.

**Review by furqanmlk — APPROVED** [review]
1. Reply to new post before replication completes. See no error. ✅ 
2. Login and clear cache before replication completes. Reload page. ✅ 
3. First login of LDAP user gets all expected memberships (groups, teams, and channels). ✅ 
4. LDAP sync adds the following memberships for q users where q > 1 (group, team, channel). ✅ 
5. Clear all caches as system admin, reload the page and don't get logged out immediately. ✅ 
6. General smoke testing of the app does not trigger too many unnecessary extra reads ✅ against master (as monitored by the logging).

**Comment by amyblais** [comment]
@metanerd Would you have any thoughts on the errors here?

**Pull request merged**
