### PR TITLE
Divide TrialEnd date by 1000 to account for it being in ms

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
The other emails that are generated have the trial end passed to them in seconds - this email uses the subscription's data (because it's not webhook triggered), which has the trial end in milliseconds. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-44098

#### Release Note

```release-note
None
```

### CODE REVIEW

**Comment by nickmisasi** [comment]
cc @amyblais we'll want to cherry pick this into the cloud release

**Review by neallred — APPROVED** [review]
LGTM, thanks @nickmisasi  :timer_clock:

**Comment by marianunez** [comment]
> cc @amyblais we'll want to cherry pick this into the cloud release

@amyblais is it too late to cherry pick considering that the release was scheduled for today?

**Pull request merged**
