### PR TITLE
MM-31492 - fix error message

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates error message to use the correct variable.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31492

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Comment by sbishel** [comment]
@furqanmlk Not sure there is anything to QA here.

**Comment by furqanmlk** [comment]
@sbishel 
I will make sure there is no error message and test cases are created/updated

**Comment by furqanmlk** [comment]
> @furqanmlk Not sure there is anything to QA here.

@sbishel 
I will make sure there is no error message and test cases are created/updated

**Review by furqanmlk — APPROVED** [review]
Tested all accounts (GitLab, Office 365, GoogleApp). Working fine as expected.

**Pull request merged**
