### PR TITLE
MM-52441: Apply path filtering to selectively run workflows

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-52441
```release-note
NONE
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
@agnivade seems like it's still running `Web App CI`, can you check?

**Comment by agnivade** [comment]
Yes that's fine. Because this touches the `.github` directory. We want to run all CI if anything changes in those directories.

I chose an inverse filter because it's easier that way, and there are also some files in the root dir, which would make the direct filter slightly more complicated.

**Review by isacikgoz — APPROVED** [review]
Okay, right it's the inverse filter. LGTM (should've look at the code first :p)

**Review by toninis — APPROVED** [review]
LGTM 👍🏼

**Comment by hmhealey** [comment]
Does the server's `build-mattermost-server` job still need to run for web app changes to be able to spin up test servers and run E2E tests? I don't know if any of the artifacts produced by the server build are still needed for those or else I would've added these myself

Also, I feel like using non-inverse filters here would be a more straightforward. The only file outside of `webapp` or `.github` that affects the web app build is `.nvmrc`, and I don't think the server build depends on anything other than `.github` and `server`. Only 1/5 on that though since we can always change it if we run into issues

**Comment by agnivade** [comment]
> Does the server's build-mattermost-server job still need to run for web app changes to be able to spin up test servers and run E2E tests? I don't know if any of the artifacts produced by the server build are still needed for those or else I would've added these myself

That's a good point. I'm hoping you can clarify something here:
- The webapp CI's `build` job runs `npm run build` to create the webapp build.
- But the server CI's `build-mattermost-server` job just runs `make build-cmd` which builds the server code. 
- The artifacts.yml depends on the server CI workflow to finish to upload artifacts to S3.

So what I can see is that there is a definite dependency on server CI to upload to S3. What I am missing is that how is the webapp artifact included in the final build, since `npm run build` and `make build-cmd` seems to happen on different jobs.

@isacikgoz - any thoughts on the above?

cc @toninis

**Comment by crspeller** [comment]
This seems to be a microcosm of our bigger issue of builds not being straightforward and the actual testing is going on on builds that are not the correct ones. Maybe we should hold on this until we can solve that bigger issue?

**Review by crspeller — APPROVED** [review]
Well carry on then 👍

**Comment by hmhealey** [comment]
@agnivade Could you remove the changes from the web app workflow? I've got those handled in https://github.com/mattermost/mattermost-server/pull/23232

**Comment by agnivade** [comment]
Nice, I'll put this on hold. You can merge https://github.com/mattermost/mattermost-server/pull/23232 first.

**Comment by agnivade** [comment]
@hmhealey - Would you mind giving this another look? Thanks

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
