### PR TITLE
[MM-30911]: Change receiver name for (me *TestHelper) in app/slashcommands/helper_test.go to be more idiomatic.

### PR DESCRIPTION
**Pull request by haardikdharma10**
### Summary 

Updated receiver name for (me *TestHelper) to be more idiomatic. This one was tiring haha:)

#### Ticket Link

Fixes: #16370 
JIRA: https://mattermost.atlassian.net/browse/MM-30911

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
This is an internal refactor and does not need any QA testing.

/update-branch

**Comment by agnivade** [comment]
@haardikdharma10 - there's a small merge conflict.

**Comment by haardikdharma10** [comment]
Hi @agnivade, I think this PR is now ready to merge:)

**Pull request merged**
