### PR TITLE
Add prepackage plugins for react-dom updates

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR updates the prepackaged versions of specific plugins that are affected by the React 17 upgrade. More context here https://github.com/mattermost/mattermost-plugin-starter-template/pull/169

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47046

#### Release Note

```release-note
Update prepackaged version of plugins affected by React 17 upgrade
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for all the work that went into these!

**Review by hanzei — APPROVED** [review]
:tada:

**Comment by hmhealey** [comment]
@DHaussermann We want to get this in for 7.6. Are you able to find some time to review this today or tomorrow?

**Comment by amyblais** [comment]
@DHaussermann Kind reminder to prioritize this PR review.

**Comment by DHaussermann** [comment]
There have been complications with the the build process for 3 of these plugins. @mickmister has been working to resolve these issue but I believe the latest on this is that the tags and version numbers need to be bump. Therefore I think the of the plugins in the commit need to be updated.

**Review by hanzei — APPROVED** [review]

**Comment by mickmister** [comment]
@DHaussermann This PR is ready for review. Please see these steps for testing:

-----

- Create a cloud server with the following command:

`/cloud create react-dom-prepackage-test --version 7.5 --env MM_LOGSETTINGS_FILELEVEL=DEBUG`

- Install the following plugins from the marketplace, and enable each plugin. Note that the version numbers should match:
  - confluence - v1.2.0
  - custom-attributes - v1.3.0
  - github - v2.1.2
  - gitlab - v1.5.0
  - jira - v3.2.0
  - jitsi - v2.0.0
  - todo - v0.6.0

- Go the custom attributes plugin's settings page
- Attempt to add a new attribute, including typing in the `teamName` select box
- Notice the webapp crashes due to ReactDOM issue

-----

- Redeploy the server with the prepackage updates:

`/cloud upgrade react-dom-prepackage-test --version 16e6946 --image mattermost/mm-ee-test`

- Notice installed plugin versions have been updated:
  - confluence - v1.3.0
  - custom-attributes - v1.3.1
  - github - v2.1.4
  - gitlab - v1.5.2
  - jira - v3.2.2
  - jitsi - v2.0.1
  - todo - v0.6.1

- Go the custom attributes plugin's settings page
- Attempt to add a new attribute, including typing in the `teamName` select box
- Notice that the plugin functions correctly, and the webapp does not crash 
- Perform exploratory testing with the other plugins, particularly where select boxes are used

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- New versions of pre-packaged plugins are available on never creation
- Created a server and upgraded to this PR code - All active plugins upgrade as expected. 
- New plugins added to pre-packaged list - Confluence, To Do and Jitsi
- **note** Bundle size went from 340MB to 379MB 

LGTM!

**Pull request merged**
