### PR TITLE
MM-28103: prepackage incident-response (#15360)

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Cherry-pick https://github.com/mattermost/mattermost-server/pull/15360 to cloud-beta.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-28103

### CODE REVIEW

**Comment by lieut-data** [comment]
Skipping `3: QA Review` since already completed in https://github.com/mattermost/mattermost-server/pull/15360.

**Comment by marianunez** [comment]
@lieut-data Should this be rebased to `cloud-beta`?

**Comment by lieut-data** [comment]
Indeed, thanks @marianunez! (Serves me right for trying to click buttons on GitHub after hours ;P)

**Review by marianunez — APPROVED** [review]
Incident Response on it's way to Cloud Beta 🎉

**Review by gabrieljackson — APPROVED** [review]
👍

**Pull request merged**
