### PR TITLE
MM-48990: Prevent the router from cleaning double slashes

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Prevent the router from cleaning double slashes, to avoid cases such as `/api/v4/users//preferences` (which is an error of a null `user_id`) being magically converted to `/api/v4/users/preferences` (which will end up being processed by a different handler than the one originally intended).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48990

#### Release Note
```release-note
The server no longer cleans double slashes in client requests.
```

### CODE REVIEW

**Comment by agnivade** [comment]
Looks like you have some tests failing. Was there something that relied on this behavior?

**Comment by agarciamontoro** [comment]
Huh, it seems the `model.Client4` (implicitly) relies on double slashes being cleaned up. As [an example](https://github.com/mattermost/mattermost-server/blob/9ab1d8f805c6a7e9b560f3f71d051dc0fb51137e/model/client4.go#L6689-L6703):
```go
func (c *Client4) emojisRoute() string {
	return "/emoji"
}

func (c *Client4) emojiRoute(emojiId string) string {
	return fmt.Sprintf(c.emojisRoute()+"/%v", emojiId)
}

func (c *Client4) GetEmojiImage(emojiId string) ([]byte, *Response, error) {
	r, err := c.DoAPIGet(c.emojiRoute(emojiId)+"/image", "")
	// rest of the handler
}
```

With the current code, when calling `c.GetEmojiImage("")`, we end up making a request to `/api/v4/emoji//image`. This is checked [in the tests](https://github.com/mattermost/mattermost-server/blob/master/api4/emoji_test.go#L594) to return a 400 Bad Request, but with the changes in this PR, it returns a 404 Not Found.

The thing is that in this example, without this PR, the URL is cleaned and becomes `/api/v4/emoji/image`, so this is processed by the [`getEmoji` handler](https://github.com/mattermost/mattermost-server/blob/9ab1d8f805c6a7e9b560f3f71d051dc0fb51137e/api4/emoji.go#L196-L216), which rejects it because the string `image` is not a valid ID; i.e., it's not a 26-char long string (hence, it returns a 400). But what if we add a new endpoint which is `/api/v4/emoji/{emoji_id}/astringthatisexactly26charslong`?  This hypothetical endpoint would create some confusion when calling its route with an empty emoji ID, since instead of being handled by it, it would be handled by `getEmoji` again, which would try to get an emoji whose ID is that `astringthatisexactly26charslong` string. This seems wrong.

I see several options here:
- Accept that `/api/v4/emoji//image` is a malformed URL and that it should return 404 because it does not exist. We'd

**Comment by agarciamontoro** [comment]
Huh, it seems the `model.Client4` (implicitly) relies on double slashes being cleaned up. As [an example](https://github.com/mattermost/mattermost-server/blob/9ab1d8f805c6a7e9b560f3f71d051dc0fb51137e/model/client4.go#L6689-L6703):
```go
func (c *Client4) emojisRoute() string {
	return "/emoji"
}

func (c *Client4) emojiRoute(emojiId string) string {
	return fmt.Sprintf(c.emojisRoute()+"/%v", emojiId)
}

func (c *Client4) GetEmojiImage(emojiId string) ([]byte, *Response, error) {
	r, err := c.DoAPIGet(c.emojiRoute(emojiId)+"/image", "")
	// rest of the handler
}
```

With the current code, when calling `c.GetEmojiImage("")`, we end up making a request to `/api/v4/emoji//image`. This is checked [in the tests](https://github.com/mattermost/mattermost-server/blob/master/api4/emoji_test.go#L594) to return a 400 Bad Request, but with the changes in this PR, it returns a 404 Not Found.

The thing is that in this example, without this PR, the URL is cleaned and becomes `/api/v4/emoji/image`, so this is processed by the [`getEmoji` handler](https://github.com/mattermost/mattermost-server/blob/9ab1d8f805c6a7e9b560f3f71d051dc0fb51137e/api4/emoji.go#L196-L216), which rejects it because the string `image` is not a valid ID; i.e., it's not a 26-char long string (hence, it returns a 400). But what if we add a new endpoint which is `/api/v4/emoji/{emoji_id}/astringthatisexactly26charslong`?  This hypothetical endpoint would create some confusion when calling its route with an empty emoji ID, since instead of being handled by it, it would be handled by `getEmoji` again, which would try to get an emoji whose ID is that `astringthatisexactly26charslong` string. This seems wrong.

I see several options here:
- Accept that `/api/v4/emoji//image` is a malformed URL and that it should return 404 because it does not exist. We'd need to test
Huh, it seems the `model.Client4` (implicitly) relies on double slashes being cleaned up. As [an example](https://github.com/mattermost/mattermost-server/blob/9ab1d8f805c6a7e9b560f3f71d051dc0fb51137e/model/client4.go#L6689-L6703):
```go
func (c *Client4) emojisRoute() string {
	return "/emoji"
}

func (c *Client4) emojiRoute(emojiId string) string {
	return fmt.Sprintf(c.emojisRoute()+"/%v", emojiId)
}

func (c *Client4) GetEmojiImage(emojiId string) ([]byte, *Response, error) {
	r, err := c.DoAPIGet(c.emojiRoute(emojiId)+"/image", "")
	// rest of the handler
}
```

With the current code, when calling `c.GetEmojiImage("")`, we end up making a request to `/api/v4/emoji//image`. This is checked [in the tests](https://github.com/mattermost/mattermost-server/blob/master/api4/emoji_test.go#L594) to return a 400 Bad Request, but with the changes in this PR, it returns a 404 Not Found.

The thing is that in this example, without this PR, the URL is cleaned and becomes `/api/v4/emoji/image`, so this is processed by the [`getEmoji` handler](https://github.com/mattermost/mattermost-server/blob/9ab1d8f805c6a7e9b560f3f71d051dc0fb51137e/api4/emoji.go#L196-L216), which rejects it because the string `image` is not a valid ID; i.e., it's not a 26-char long string (hence, it returns a 400). But what if we add a new endpoint which is `/api/v4/emoji/{emoji_id}/astringthatisexactly26charslong`?  This hypothetical endpoint would create some confusion when calling its route with an empty emoji ID, since instead of being handled by it, it would be handled by `getEmoji` again, which would try to get an emo  ji whose ID is that `astringthatisexactly26charslong` string. This seems wrong.

I see several options here:
- Accept that `/api/v4/emoji//image` is a malformed URL and that it should return 404 because it does not exist. We'd need to update all those failing tests to make sure this is handled properly.
  - Here, we could also enforce the IDs in the routers regexes to be 26 chars long, with something like `/emoji/{emoji_id:[A-Za-z0-9]{26}}`. This would still return 404 for a malformed URL like `/api/v4/emoji//image`.
- Change the routers regexes so that they accept an empty ID and error in the proper handler. For example, change the `api.BaseRoutes.Emoji` router regex from `/emoji/{emoji_id:[A-Za-z0-9]+}` to /emoji/{emoji_id:[A-Za-z0-9]}`, so that `/api/v4/emoji//image` is handled by `getEmojiImage` instead of `getEmoji`. `getEmojiImage` then would error because the ID is not correct.
- Keep things as they are right now (i.e., with gorilla/mux cleaning double slashes) and fix individual bugs we find along the way. For the bug that motivated this PR I don't see any other fix than changing the router regex to expect a 26-char long ID, though.

Thoughts?

**Comment by agnivade** [comment]
Option 1 sounds good to me.

**Comment by agarciamontoro** [comment]
Huh!  It turns out that calling `SkipClean(true)` in the router not only skips cleaning double slashes, as the documentation states. It also makes something quite important, completely undocumented: it skips resolving `.` and `..` paths, so that `/plugins/plugin.id/public/../file.png` is by default handled by returning a 301 redirection to `/plugins/plugin.id/file.png`! You can see this in the code inside [this block](https://github.com/gorilla/mux/blob/eb99d7a67714bbab6db27f896a8c8c947b51b610/mux.go#L176-L195) that only gets executed if the internal variable `skipClean` is set to false (the default value). That block calls this [`cleanPath` function](https://github.com/gorilla/mux/blob/eb99d7a67714bbab6db27f896a8c8c947b51b610/mux.go#L462-L479), which in turns calls `path.Clean` on the URL of the request.
Now, if `SkipClean(true)` is called, then the double dot is **not** resolved, and the handler of `/plugins/plugin.id/public/{pathtofile}/` receives `../file.png` as the `pathtofile` variable. However, the code of that handler is smart enough to call `path.Clean` on that path by itself, and then it double-checks that the cleaned path still lives under the public directory, so no file on any parent directory can be accessed. The case affected by this is isolated in the latest commit, . The other changes in the first commit,, are expected bad-requests that are now not-founds.

All in all, this change seems to be safe for this case, but it was an interesting journey to understand why the test expected a 301 in the first place.

Please, give the whole change a second thought, and let's test it thoroughly before merging, since there may be other places that could be affected by this. In any case, not resolving `.` and `..` seem even safer than resolving them by default, so I'd say this change may end up making other handlers safer.

**Comment by agarciamontoro** [comment]
Also, I've decided against my initial suggestion of enforcing the IDs in the routers regexes to be 26 chars long (something like  `/emoji/{emoji_id:[A-Za-z0-9]{26}}`). I think that may be helpful at some point, but it does fall out of scope of this PR, and I'd rather keep these changes as isolated as possible.

**Comment by agnivade** [comment]
Can we just copy over just the "prevention of cleaning double slashes" part in our code? Then we can bypass this altogether.

**Comment by agarciamontoro** [comment]
> Can we just copy over just the "prevention of cleaning double slashes" part in our code? Then we can bypass this altogether.

For this, we'd need to copy over the whole cleaning code and remove only the cleaning of double slashes. I'm not sure it would give us a lot of benefit.

**Comment by hmhealey** [comment]
Seeing as this is getting a lot more involved than what we originally expected, maybe we should leave this as a potential TODO for API v5? 0/5

**Comment by agarciamontoro** [comment]
> maybe we should leave this as a potential TODO for API v5?

Yeah, @agnivade and I have been discussing just now in a DM that this seems to be more risky than anticipated and he suggested to push this to 8.0. I no longer believe that the benefits outweigh the risks here, so I'd rather close this and revisit in API v5 if needed (maybe for v5 we'll use something entirely different from Gorilla, for what it's worth). Do we have a list of TODOs for v5?

**Comment by agarciamontoro** [comment]
Closing. Let's continue the discussion in the server channel.

**Pull request closed without merging**
