### PR TITLE
MM-10684: Show logs on Slack Import CLI.

### PR DESCRIPTION
**Pull request by grundleborg**
#### Summary
Show importer logs at the end of CLI SLack import, to make it the same as the web based import.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10684

### CODE REVIEW

**Comment by jespino** [comment]
makes sense to include a new flag for the print log? something like "--verbose" or "--quite" depending on which is the default desired behavior.

**Comment by grundleborg** [comment]
I don't think there's any need for that - you really ought to be looking at that output even if you don't think you should!

**Comment by jespino** [comment]
ok, that makes sense, but in case of error, it will show only the error, not the logs. I think the logs must be shown anyway.

**Comment by grundleborg** [comment]
Not sure about that. If it fails with an error, the error that caused it to fail is printed. These are not really "logs", more "completion report".

**Comment by jespino** [comment]
Yes, now I see it will generate logs only for non-error paths, so makes no sense.

**Pull request merged**
