### PR TITLE
fix announcement bar overlap after signup

### PR DESCRIPTION
**Pull request by okanisildar**
#### Summary
After signup when you redirected to teams screen (to create a new team or choosing an existing), announcement bar is overlapped with signup-header. This issue wasn't there on the other screens.

#### Ticket Link
N/A
There wasn't a ticket for this. I followed the contribution guideline and did not create a new issue. 

#### Screenshots

|  before  |  after  |
|----|----|
|  before-announcement-bar|after-announcement-bar|

#### Release Note
```release-note
Fixed UI glitch
```

P.S: Firstly, I created this PR for the webapp reposityory, then warned to raise the PR here. You can see the [details](https://github.com/mattermost/mattermost-webapp/pull/12372)

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
@stevemudie Since we can't get a test server for this up, I ran it locally to confirm it worked. Hopefully that's good enough since this seems like a straightforward enough PR to test
Screen Shot 2023-03-29 at 4 18 31 PM

**Comment by okanisildar** [comment]
With pleasure @stevemudie! 
Should I move forward with the merging process? @hmhealey @stevemudie

**Comment by hmhealey** [comment]
@okanisildar This is good to go on your end. We just forgot to run the enterprise tests since those have some extra permission checks behind them currently

**Pull request merged**
