### PR TITLE
Use seconds instead of nanoseconds for the store time layer metrics

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
We were using seconds for api metrics, and nanoseconds for store metrics, this
way both related metrics are consistent

### CODE REVIEW

**Comment by jespino** [comment]
@george The reasons behind this, is, there is already existing data with "seconds" measure, and we are already collecting store methods performance in nanoseconds, so... I want to preserve the consistency with the store (because is similar and is already in 5.16) but at the same time I want to maintain the consistency with the old existing data, so... not a big deal to change it nanoseconds for the API, but can be a problem for other measures.

Other option is do it all the way around and change the store measures to a float of seconds, but it would need to change the things before 5.16 is definitively cut, I don't know what we prefer here.

**Comment by grundleborg** [comment]
Current code is fine with me - makes sense.

**Comment by grundleborg** [comment]
But entirely fine with changing them all too - up to you entirely.

**Comment by jespino** [comment]
@grundleborg looks like everywhere else is using seconds so I going to change it and patch the time layer for that, and cherry-pick in to 5.16.

**Comment by jespino** [comment]
@grundleborg done, PTAL

**Pull request merged**
