### PR TITLE
Manual cherry pick of #22155

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
Manual cherry-pick of #22155.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by noxer** [comment]
@amyblais merging this PR will also fix other failing cherry-picks, once they are /update-branch'd

**Review by amyblais — APPROVED** [review]

**Comment by noxer** [comment]
This one https://github.com/mattermost/mattermost-server/pull/22182/commits/17fc3915220fc0b391c45f1f871d959778a314f3

**Comment by amyblais** [comment]
https://github.com/mattermost/mattermost-server/pull/22107 wasn't originally meant to go into v7.8 but is scheduled for v7.9. Is the Go update necessary to add for v7.8?

**Comment by noxer** [comment]
The updated Go version came with updated tooling. Focalboard was failing because the golangci-lint was too old.
We could try to just upgrade golangci-lint for 7.8.

**Comment by agnivade** [comment]
> Is the Go update necessary to add for v7.8?

No, and is not advised.

>  Focalboard was failing because the golangci-lint was too old.

I think that was because it wasn't an upstream cherry pick.

**Comment by noxer** [comment]
We could also create a `release-7.8` branch in focalboard with the correct version before the "fix" for the golangci-lint update.

**Comment by noxer** [comment]
That is probably the better idea. Now the enterprise repo is causing problems due to the version change.

**Review by amyblais — APPROVED** [review]

**Pull request merged**
