### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rishabh710**
addition of contributing section

#### Summary
addition of cotributing section

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jasonblais — APPROVED** [review]

**Comment by rishabh710** [comment]
Can you help in signing CLA

**Comment by jasonblais** [comment]
@rishabh710 certainly! Do you have questions about the CLA?

**Comment by rishabh710** [comment]
Yes, Actually I am new to Github. So, Can you help to sign the CLA.How can I sign the CLA

**Comment by jasonblais** [comment]
@rishabh710 You can complete the Mattermost contribution license agreement (CLA) here: http://www.mattermost.org/mattermost-contributor-agreement/

Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

Let me know if any questions :)

**Comment by rishabh710** [comment]
@jasonblais  thank you for your support

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
Thanks @rishabh710 :+1:

**Pull request merged**
