### PR TITLE
preserve ClientError cause with es2022

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Building the client package with `es2022` and exposing the optional `.cause` property on Errors effectively allowing us to wrap caught errors in the client package and re-throw with the context from the request, all while preserving a useful backtrace.

Before (running PlayWright tests):
image

After (running PlayWright tests):
image

Note that we haven't historically exported the client package, so existing plugins that import it from mattermost-redux and mattermost-webapp should be left unimpacted.

#### Ticket Link
None, this is a developer optimization only.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by furqanmlk** [comment]
@lieut-data 43 test cases are failing in [e2e](https://automation-dashboard.vercel.app/cycles/694d73d2-2f9d-40f1-8b40-cdff02d37ca7), Can you please have a look

**Comment by lieut-data** [comment]
@furqanmlk, comparing this [latest e2e run](https://automation-dashboard.vercel.app/cycle/323983) with the [master e2e test run](https://automation-dashboard.vercel.app/cycle/323955), it looks similar? Should I investigate further relative to this PR?

| This PR | Master
| -------- | ------ | 
| image | image |

**Review by furqanmlk — APPROVED** [review]
E2E looks good 
https://automation-dashboard.vercel.app/cycle/327837

**Pull request merged**
