### PR TITLE
Resolving Error code "2" in Makefile for Stopping Processes

### PR DESCRIPTION
**Pull request by gomessguii**
#### Summary

This fixes error (2) that occurred when running the `make stop` command on the webapp. The error was caused by a termination code 2 when attempting to stop the webapp processes. The `|| true` command was unable to ignore this error, which led to several cascade errors on other make targets that depended on it, such as the stop target on the server Makefile.

When running `make stop` from the server folder, it should stop the server, stop the client, and then stop the containers. However, due to the error on the stop target in the webapp, it was unable to stop the containers.

To resolve this issue, I added a "-" before the command in the Makefile, which allowed make to ignore the error and proceed as it should.

When running `make stop` from the server folder before:
``` zsh
➜  server git:(webapp-makefile-stop-fix) ✗ make stop
Stopping mattermost
Stopping mattermost client
cd ../webapp && make stop
make[1]: Entering directory '/my-directory/mattermost-server/webapp'
Stopping changes watching
make[1]: *** [Makefile:16: stop] Terminated
make[1]: Leaving directory '/my-directory/mattermost-server/webapp'
make: *** [Makefile:625: stop-client] Error 2
➜  server git:(webapp-makefile-stop-fix) ✗ echo $?
2
``` 
and now:
``` zsh
➜  server git:(webapp-makefile-stop-fix) ✗ make stop
Stopping mattermost
Stopping mattermost client
cd ../webapp && make stop
make[1]: Entering directory '/my-directory/mattermost-server/webapp'
Stopping changes watching
make[1]: [Makefile:16: stop] Terminated (ignored)
make[1]: Leaving directory '/my-directory/mattermost-server/webapp'
Stopping docker containers
docker-compose stop
[+] Running 4/0
 ⠿ Container mattermost-inbucket  Stopped                                                                                                                                                                                                0.0s
 ⠿ Container mattermost-postgres  Stopped                                                                                                                                                                                                0.0s
 ⠿ Container mattermost-minio     Stopped                                                                                                                                                                                                0.0s
 ⠿ Container mattermost-mysql     Stopped                                                                                                                                                                                                0.0s
➜  server git:(webapp-makefile-stop-fix) ✗ echo $?  
0
```

#### Ticket Link

N/A

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Sorry for the delay on this. I remember discussing this, but I lost track of the PR for it.

This looks good to me!

**Review by wiggin77 — APPROVED** [review]
Nice fix. Thanks. This will fix it for 'make run' from the server directly as it calls into this makefile.

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
