### PR TITLE
Cherry-picking translations

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Cherry-picking translations from master

#### Related Pull Requests
https://github.com/mattermost/mattermost-server/pull/21954

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]

**Comment by amyblais** [comment]
@ctlaltdieliet Feel free to add translations from this latest PR that was merged today: https://github.com/mattermost/mattermost-server/pull/21975.

**Comment by amyblais** [comment]
@ctlaltdieliet I'm not sure why the CI here is failing. Today is code freeze for v7.7, let me know if you'd be able to submit a new PR for this if you have time.

**Pull request closed without merging**
