### PR TITLE
[MM-36563] Only read body from inter-plugin request if there is one

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
If a inter-plugin request doesn't have a body the `apiRPCClient` still tries to read it and panics. With this PR the body is only read if there is one.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36563

#### Release Note
```release-note
Fix inter-plugin requests without a body
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by crspeller — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei  are there specific steps I can use to validate this change aside from the regression testing for https://github.com/mattermost/mattermost-server/pull/17832 ?

**Comment by DHaussermann** [comment]
@hanzei  I can test this once you merge in https://github.com/mattermost/mattermost-server/pull/17832 but, I'm still unclear on if there are specific steps for this one. Any thoughts?

**Comment by hanzei** [comment]
@DHaussermann This PR contains a little change which is greatly covered by tests and you also tested it as part of https://github.com/mattermost/mattermost-server/pull/17832 by confirming that the apps plugin  works fine.

I'm going to merge it as I don't think there is much more to test here.

**Pull request merged**
