### PR TITLE
[MM-29224] Fix bug where markdown image link doesn't show preview

### PR DESCRIPTION
**Pull request by camgraff**
Fixes https://github.com/mattermost/mattermost-server/issues/15822

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29224

### CODE REVIEW

**Review by nevyangelova — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @camgraff. This looks good to me!

Here's a screenshot of how it looks in practice:
image

**Comment by hanzei** [comment]
Switching out @saturninoabril for as a reviewer to even out the workfload

**Review by saturninoabril — APPROVED** [review]
Thanks @camgraff! Tested and passed.

**Comment by hmhealey** [comment]
We're reverting this temporarily because of some unforeseen interactions with other integrations which are linked on the attached Jira ticket. Once we've figured out how to deal with those, this'll be un-reverted.

**Pull request merged**
