### PR TITLE
[MM-14699] Add MimeType to Emoji

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
On iOS, custom GIF emoji's do not animate unless the cached file extension is `.gif`. Since the URL to get the custom emoji image from the server does not contain any information regarding the type, the mobile app does not know the type of image until the image is fetched. However, the app requires knowledge of this type prior to making the get request as the file path with extension is determined prior to the request and used in RNFetchBlob's `config`, which then uses that file path to save the image automagically on success of the request. With this change, the response from getting the custom emoji will include a MIME type which the mobile app can then use to create a correct file path prior to sending the request to get the image.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-14699

### CODE REVIEW

**Comment by enahum** [comment]
@migbot the only worry that I have is that this is not backwards compatible.

Is there a way to get the mime type from the actual binary or something that we can get to set the Response header instead?

**Comment by enahum** [comment]
@migbot @migbot RNFetchBlob has API's to move the file and I would prefer that before being backwards incompatible.

What I mean about backwards compatible is in the case of the server and uploaded custom emoji's.
For example, you have uploaded 2000 custom emojis with gif format, I would expect them to work after the fix but they will not have the mime-type set, so they'll behave as png instead.

**Comment by enahum** [comment]
@migbot lets discuss this tomorrow to see the alternatives

**Comment by lieut-data** [comment]
@migbot, I've added the `Awaiting Submitter Action` label to this PR -- let me know when you want me to take a look at the changes.

**Pull request closed without merging**
