### PR TITLE
[MM-34216] app/import: do not break import process if a dm channel is invalid

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Added a check if DM channels has no active members so that they won't get exported. In the meantime, we may have some previous import files with invalid DM channels. I added invalid channel member count error to `stopOnError` to not break whole import process. It will simply skip those invalid channels while importing. I wonder if it would be more sensible to ask users to filter out the invalid import lines. 0/5 on both actually, want to hear reviewer opinions.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34216

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by streamer45** [comment]
I agree on making the import process more resilient although I am wondering if we should be exporting such DMs in the first place.

**Comment by isacikgoz** [comment]
@streamer45 I already added the change below: https://github.com/mattermost/mattermost-server/blob/eb48a7a3c1170c256c96c6ef13e4cc40fe56ea69/app/export.go#L614 But, do you mean why they are not being deleted from the server? Or why there is no check while fetching those channels from the store?

**Comment by streamer45** [comment]
> @streamer45 I already added the change below:

Apologies, I originally read the PR summary and thought it was an import only modification (should have looked at the diff really).
Never mind then, I'll review shortly :)

**Review by streamer45 — APPROVED** [review]
Awesome :+1: 

Personally I think it's okay to do it this way. We are already avoiding exporting other things (e.g. deleted channels) so it makes sense to do the same here. One possible evolution on this would be to keep track of such skipped entities (log them somewhere) so that the user is informed. This is of course out of scope for this PR.

**Review by mgdelacroix — APPROVED** [review]
LGTM! :rocket: 

I agree with the analysis and with following the current pattern. And to add on top of @streamer45 suggestion, we could actually export those invalid entities into a file (maybe suffixed with `_invalid`) to allow the user not only to be aware of those but to manually modify them if they want and port them back to the original export.

**Review by lindy65 — APPROVED** [review]
Thanks @isacikgoz 👍

**Comment by isacikgoz** [comment]
Created the [ticket](https://mattermost.atlassian.net/browse/MM-35100) 👍

**Pull request merged**
