### PR TITLE
Moving markdown to corelibs

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Moving markdown to shared libs

#### Ticket Link
[MM-33006](https://mattermost.atlassian.net/browse/MM-33006)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Looks good once we have decided the name of the package in https://github.com/mattermost/mattermost-server/pull/16914.

**Review by agnivade — APPROVED** [review]

**Review by mgdelacroix — APPROVED** [review]
LGTM :+1:

**Review by lindy65 — APPROVED** [review]
Thanks @jespino - tested as per steps in Jira ticket as well as some other basic markdown tests and did not find any issues. 👍

**Pull request merged**
