### PR TITLE
[MM-24391] Render icon_emoji names surrounded by colons in incoming webhooks

### LINKED ISSUE #15691: Incoming Webhook - icon_emoji should render emoji with colon
When using the slack message and using the `icon_emoji` it does not override the icon if a colon is provided before and after the emoji name e.g. `:tada:` . It does work with `tada`.

To test can use this message

```java
{
    "channel": "#town-square",
    "icon_emoji": ":tada:",
    "username": "testing",
    "attachments": <
        {
            "color": "#4286f4",
            "title": "blablababla",
            "text": "xoxoxoxoxoox"
        }
    >
}
```

Please also check what the behaviour on mobile is.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-24391

### PR DESCRIPTION
**Pull request by edtrist**
#### Summary
Removes any colons in `icon_emoji` name before passing it to `GetEmojiStaticUrl` to allow for emojis to be specified with surrounding colons, e.g. `:tada:`.

Also added a test, and updated docs: https://github.com/mattermost/mattermost-developer-documentation/pull/696

#### Ticket Link
Fixes #15691 

https://mattermost.atlassian.net/browse/MM-24391

#### Release Note
```release-note
Updated `icon_emoji` field in incoming webhooks to allow for emojis to also be specified with surrounding colons
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Great work :+1:

**Review by catalintomai — APPROVED** [review]

**Comment by hanzei** [comment]
@prapti Could you please help with reviewing this PR as @DHaussermann has a lot on this plate?

**Review by prapti — APPROVED** [review]
@edtrist Thank you for contributing this! Tested locally and works great.
Approving to merge 🎉

**Comment by hanzei** [comment]
Thanks for the great PR @edtrist :rocket:

**Pull request merged**
