### PR TITLE
[MM-43798] Change default CRT option from Disabled to AlwaysOn

### PR DESCRIPTION
**Pull request by vish9812**
#### Summary

Change default CRT option from Disabled to AlwaysOn

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-43798

#### Related Pull Requests
- Dependent on changes in https://github.com/mattermost/mattermost-server/pull/20088
- Dependent on changes in https://github.com/mattermost/enterprise/pull/1201

#### Release Note

```release-note
The default for `ServiceSettings.CollapsedThreads` has been changed to "always_on". This does not affect existing configurations where this value is already set to some other value.
```

### CODE REVIEW

**Comment by vish9812** [comment]
This PR branch is taken from MM-32692-crt-options branch which has this [PR-20088](https://github.com/mattermost/mattermost-server/pull/20088).
So review & merge, the main PR-20088 first, then this one.

**Comment by ashishbhate** [comment]
@vish9812 It looks like some of the enterprise tests are failing because those enterprise tests assume that CRT is default_off. By changing the setting to always_on, the behaviour in those tests change. 
If you look at the full output of the test failure in the circleCI, you'll see where the tests are failing.

**Comment by amyblais** [comment]
@vish9812 @koox00 @ashishbhate Kind reminder that v7.0 feature complete is this Wednesday, May 18th.

**Review by Willyfrog — APPROVED** [review]
Changes look ok, so once the tests are fixed it is good to go

**Comment by vish9812** [comment]
Tests have been fixed in this PR - https://github.com/mattermost/enterprise/pull/1201

**Comment by ashishbhate** [comment]
Added the "Do Not Merge" while we figure out when this PR needs to go in

cc/ @Willyfrog

**Pull request merged**
