### PR TITLE
MM-31258 move UserType header into the right column

### PR DESCRIPTION
**Pull request by maxerenberg**
#### Summary
This pull request moves the UserType field in the CSV compliance report into the right column. Currently this field is at the end of the row, causing headers and data to be misaligned.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31258

#### Release Note
```release-note
Compliance report field headers are now correctly aligned.
```

### CODE REVIEW

**Review by sbishel — COMMENTED** [review]
Any way to add a test to prevent these from getting out of sync again?

**Comment by maxerenberg** [comment]
Yes, I was going to add a test to the enterprise repo (since the other compliance tests are there). I need https://github.com/mattermost/mattermost-server/pull/16700 to get merged first though.

**Comment by maxerenberg** [comment]
@sbishel  I added a test here https://github.com/mattermost/enterprise/tree/MM-31258_Compliance_Monitoring_CSV_Headers

**Review by sbishel — APPROVED** [review]
Thanks, go ahead and create a PR for the Unit Test and tie it to this PR and Jira.

**Comment by maxerenberg** [comment]
I'm going to close this PR and reopen it upstream so that the tests on the enterprise repo will run against it.

**Pull request closed without merging**
