### PR TITLE
Added code of conduct to project

### PR DESCRIPTION
**Pull request by jivthesh**

### CODE REVIEW

**Comment by aspleenic** [comment]
Hey @jivthesh,

I wanted to make sure - for this PR are you using the latest revision of the Contributor Covenant?

**Comment by jivthesh** [comment]
@aspleenic yes I am using the latest revision of the Contributor Covenant

**Comment by aspleenic** [comment]
Awesome - thanks @jivthesh

**Review by aspleenic — APPROVED** [review]

**Comment by aspleenic** [comment]
Hey @jivthesh - We are going to mark this as Hacktoberfest Accepted and close the PR. Thanks in part to your efforts, we have adopted the Contributor Covenant to the global Mattermost project.

Thanks for being an awesome part of the community!

**Comment by jivthesh** [comment]
@aspleenic will this count towards sucessful contribution?will this be merged

**Comment by aspleenic** [comment]
Hey @jivthesh - we checked with Digital Ocean and, because it is marked as "Hacktoberfest-Accepted" it will be counted.

**Comment by jasonblais** [comment]
Hi @jivthesh - huge thank you for your contribution here. We adopted the code of conduct organization-wide via https://github.com/mattermost/.github/pull/4, which is referenced any time someone opens a new GitHub pull request.

Given this upstream pull request applies to all repositories, we won't need the individual change to the server PR and will close it at this time.

However, we will leave the `hacktoberfest-accepted` label to ensure it gets counted towards Hacktoberfest. In the event it does not, let us know and we'll resolve it immediately for you.

As a final note, we are considering announcing our new code of conduct in a short blog post. We'd love to recognize your initiative in the blog. Let us know if it's okay to mention you in it?

Again, huge thank you, this is incredibly valuable to the entire community.

**Pull request closed without merging**
