### PR TITLE
MM-30917 Fix invalid reply count calculation during thread migration

### PR DESCRIPTION
**Pull request by reflog**
#### Summary

fix reply count calculation (avoid deleted posts)
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30917
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]

**Comment by reflog** [comment]
@amyblais cherry pick candidate

**Review by ethervoid — APPROVED** [review]
LGTM

**Comment by reflog** [comment]
@amyblais - where should this be cherry picked?

**Comment by amyblais** [comment]
@reflog Let's cherry-pick this at same time when https://github.com/mattermost/mattermost-server/pull/16407 is ready when the time comes.

**Pull request merged**
