### PR TITLE
MM-47838 - Conclude A/B test for upgrade button

### PR DESCRIPTION
**Pull request by ConorMacpherson**
#### Summary

A/B testing was setup to see if the text "View Plans" could influence/drive greater traffic to the plans modals.
Based on the [data](https://mattermost.looker.com/explore/data_warehouse/feature_flag_telemetry?toggle=fil&qid=Yf0VTKJdfGC5lro9H7Io4z), "View Plans" performed better than "Upgrade"

This change removes references to the feature flag made for A/B testing.

#### Ticket Link

[MM-47838](https://mattermost.atlassian.net/browse/MM-47838)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by neallred — APPROVED** [review]
I think the `template/cloud_30_day_arrears.html` change was unintentional and maybe snuck in from another branch. Could it be reverted prior to merging?

**Comment by ConorMacpherson** [comment]
> I think the `template/cloud_30_day_arrears.html` change was unintentional and maybe snuck in from another branch. Could it be reverted prior to merging?

Sure, I can revert that @neallred A check in the pipeline failed and mentioned running `make build-templates` to fix it.

**Comment by neallred** [comment]
Ahh, ok. Looking at mattermost's version of this repo, it looks to me like you might be missing a commit from its master branch: https://github.com/mattermost/mattermost-server/commit/532a3c1f2276e436e7d543e38d0ee8def6d575de . Can you try pulling in latest master?

**Comment by ConorMacpherson** [comment]
@neallred Ah, I think I was on a forked repo. I'll try to switch over to the original repo.

**Comment by ConorMacpherson** [comment]
Should be up to date now.

**Review by AGMETEOR — APPROVED** [review]

**Comment by marianunez** [comment]
@yasserfaraazkhan please make sure to also approve the PRs so that is visible as part of the people that reviewed besides that tags. Thanks!

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
> @yasserfaraazkhan please make sure to also approve the PRs so that is visible as part of the people that reviewed besides that tags. Thanks!

sure @marianunez

**Comment by yasserfaraazkhan** [comment]
tested this with the server [PR](https://github.com/mattermost/mattermost-webapp/pull/11442)

**Comment by marianunez** [comment]
> tested this with the web app [PR](https://github.com/mattermost/mattermost-webapp/pull/11442)
> 
> changes are working fine.

Thanks @yasserfaraazkhan!

**Pull request merged**
