### PR TITLE
MM-29522:fix typo in constant name

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Fixes a typo in constant name. Updates all references.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29547

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
LGTM, thanks Scott! :)

**Review by hahmadia — APPROVED** [review]

**Review by mkraft — APPROVED** [review]
:)

**Review by srkgupta — APPROVED** [review]
Changes are straightforward and LGTM.

**Pull request merged**
