### PR TITLE
[MM-22037] Enable uppercase letters in the email

### PR DESCRIPTION
**Pull request by iomodo**
#### Summary
This PR will enable uppercase letters in the emails.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-22037

### CODE REVIEW

**Comment by iomodo** [comment]
@hmhealey kind reminder to review the PR.

**Comment by hmhealey** [comment]
I wonder what the original reason was behind requiring that an email is lower case. Unfortunately, `git blame` doesn't tell us anything since that code predates this git repository.

**Comment by iomodo** [comment]
@hmhealey No one seems to remember the original reason. But as I think of it, the proposed change will cause inconsistency such as `a@b.com` and `A@b.com` will be the different user. Maybe what we should do is except uppercase emails and convert them to lowercase.
Thoughts @jwilander ?

**Comment by jwilander** [comment]
Thinking about it some more I agree with you @iomodo. Accept the uppercase emails but just lowercase them before we save them. No difference to the user, since whatever case the enter will work, and then it keeps the DB consistent and makes comparing/querying easy as long as we lowercase what we're querying/searching/comparing with

**Comment by hmhealey** [comment]
That's a good point. That's probably why we did that in the first place.

We could lowercase the email in the `PreSave` and `PreUpdate` methods on the user to ensure that they're saved to the database correctly, although if we do that, we should also make sure to lowercase the emails when logging in or getting the user by email.

**Comment by iomodo** [comment]
@hmhealey I don't think it's a good idea to introduce this logic in DB layer. Whenever user inputs email we should lowercase it and use it further. Thoughts?

**Comment by hmhealey** [comment]
Generally we use those methods for normalization, so I don't think it's that much of a stretch to do it there as well.

Now that I look at it though, we do already lower case the email in `PreSave` and `PreUpdate` since it calls [`NormalizeEmail`](https://github.com/mattermost/mattermost-server/blob/master/model/user.go#L312).

**Pull request merged**
