### PR TITLE
Migrate GetDeleted method from ChannelStore to return error interface

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

This PR migrates `GetDeleted` method.

Fixes https://github.com/mattermost/mattermost-server/issues/14714

Jira ticket: https://mattermost.atlassian.net/browse/MM-25689

### CODE REVIEW

**Comment by rvillablanca** [comment]
Hi @agnivade, friendly reminder for the ticket :)

**Comment by teresa-novoa** [comment]
Thanks @rvillablanca for the contribution, Agniva already self assigned this for review, best!

**Comment by rvillablanca** [comment]
So this needs another approval from a second reviewer :)

**Comment by agnivade** [comment]
Woops, thanks for that Rodrigo.

**Comment by rvillablanca** [comment]
Conflicts solved

**Comment by agnivade** [comment]
@lindy65 - This would involve some testing around loading archived channels. Thanks.

**Pull request merged**
