### PR TITLE
MM-51768: Scrub username/password from SQL datasource

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-51768
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
I know it's a bit thin on test cases :P Let me know if you'd prefer more.

**Comment by agnivade** [comment]
@streamer45 @esarafianou - PTAL.

**Review by esarafianou — APPROVED** [review]
LGTM

**Review by streamer45 — APPROVED** [review]
Looks great, thanks :+1:

**Comment by amyblais** [comment]
@agnivade This can be cherry-picked to cloud branch.

**Comment by amyblais** [comment]
@agnivade Please help open manual cherry-pick PRs to ``release-7.1``, ``release-7.7``, ``release-7.8``, ``release-7.9`` and ``release-7.10`` branches.

**Comment by agnivade** [comment]
@amyblais - All automated cherry picks to non-monorepo branches will fail. Don't bother. It'll be painful for a while.

**Pull request merged**
