### PR TITLE
MM-52216: Trim errors

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-52216
```release-note
NONE
```

### CODE REVIEW

**Review by oh6hay — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
:+1:

**Comment by agnivade** [comment]
@oh6hay - Requesting a re-review.

**Review by oh6hay — APPROVED** [review]
:+1:

**Comment by amyblais** [comment]
@agnivade Needs a manual cherry-pick to ``release-7.1`` branch.

**Pull request merged**
