### PR TITLE
[MM-48010] Fetch Threads since parameter should return threads with new replies.

### PR DESCRIPTION
**Pull request by anurag6713**
#### Summary
When the `since` param is used, API only returns new threads with `since` greater than `ThreadMembership.LastUpdatedAt`. Due to this threads with new replies are not synced on the mobile client. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48010

#### Release Note
```
behavioral change
```

### CODE REVIEW

**Comment by esethna** [comment]
@amyblais can we cherry pick this into any supported versions if we have dot releases planned?

cc// @Willyfrog

**Review by vish9812 — APPROVED** [review]

**Review by koox00 — APPROVED** [review]

**Pull request merged**
