### PR TITLE
[MM-17377] Add top-level `recover` to prevent a plugin panic from crashing the server

### PR DESCRIPTION
**Pull request by jozuenoon**
Jira: https://mattermost.atlassian.net/browse/MM-17377
GH Issue: https://github.com/mattermost/mattermost-server/issues/11863

### CODE REVIEW

**Comment by jozuenoon** [comment]
After investigation the stack trace unfortunately starts inside `net/rpc` library. This is probably not easily fixable by only using `recover`.

```
/mattermost-server/plugin$ go test -run TestRecoverFromWrongHttpCode 
panic: invalid status code

goroutine 2667 [running]:
github.com/mattermost/mattermost-server/plugin.(*PanicResponseWriter).WriteHeader(0xc00145dd00, 0x3e7)
        /home/wk/github/mattermost-server/plugin/client_rpc_test.go:88 +0x50
github.com/mattermost/mattermost-server/plugin.(*httpResponseWriterRPCServer).WriteHeader(0xc002482720, 0x3e7, 0x17ab440, 0x0, 0x0)
        /home/wk/github/mattermost-server/plugin/http.go:27 +0x3d
reflect.Value.call(0xc0024d2300, 0xc00214f4e8, 0x13, 0xe9954b, 0x4, 0xc000081f18, 0x3, 0x3, 0xc0024c2040, 0xc000178fe8, ...)
        /usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0xc0024d2300, 0xc00214f4e8, 0x13, 0xc001094718, 0x3, 0x3, 0xc000178fc0, 0xc001094710, 0xc0010947b8)
        /usr/local/go/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc0024c2500, 0xc0021b0690, 0xc0024c4270, 0xc0024c4280, 0xc00239ca80, 0xc0024c6b40, 0xd1d0e0, 0xc0024c43f8, 0x182, 0xd03620, ...)
        /usr/local/go/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:481 +0x42b
exit status 2
FAIL    github.com/mattermost/mattermost-server/plugin  2.314s
```

**Comment by lieut-data** [comment]
@jozuenoon, hmm, indeed this does appear to be nigh impossible as per https://github.com/golang/go/issues/27777. I'll give this some more thought.

**Comment by hanzei** [comment]
@lieut-data Gentle reminder about this investigation https://github.com/mattermost/mattermost-server/pull/11915

**Comment by lieut-data** [comment]
I've given this some on and off thought, and I don't believe there to be any tractable solution. cc @cpoile, since your original idea of repeating the checks ourselves was likely the right approach all along. Rather unfortunate, actually, since we're pretty much exposed to any `panic` we trigger this way.

Closing this issue for now, since it's not feasible.

**Pull request closed without merging**
