### PR TITLE
[MM-23327] webapp/channels : add full stop to the end of first sentence in welcome popup

### PR DESCRIPTION
**Pull request by saideepesh000**
#### Summary
add full stop to the end of first sentence to maintain consistency

#### Ticket Link
fixes https://github.com/mattermost/mattermost-server/issues/23327

#### Release Note

```
NONE

```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by saideepesh000** [comment]
> @saideepesh000 please check the failing CI

hey @M-ZubairAhmed , i don't see any issues with lining, what might be the issue here?
Screenshot 2023-05-12 at 10 35 05 PM

**Comment by M-ZubairAhmed** [comment]
> @saideepesh000 please check the failing CI

It looks like CI just randomly failed, i have merged latest lets see the CI

**Review by marianunez — APPROVED** [review]

**Review by marianunez — APPROVED** [review]
Thanks @saideepesh000!

**Pull request merged**
