### PR TITLE
MM-30802: Enable GoSAML2 library support

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
ReEnables SAML2 library as the only library used, requires Enterprise related changes.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30802

#### Release Note
```release-note
Enable goSAML2 library as the only supported SAML Library.
```

#### Related PRs
https://github.com/mattermost/enterprise/pull/832

### CODE REVIEW

**Review by jupenur — APPROVED** [review]

**Review by hahmadia — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Review by srkgupta — APPROVED** [review]
Will be tested post merge. Approving the PR as is.

**Pull request merged**
