### PR TITLE
[MM-37730] - Self-managed: Update email template to new branding - Batch Email

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
Batch Email template is similar to DM, GM and Mention template. This PR however fixes the message button color to that of the new branding

#### Ticket Link
[MM-37730](https://mattermost.atlassian.net/browse/MM-37730)

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Review by pablovelezvidal — APPROVED** [review]
LGTM!

**Review by neallred — APPROVED** [review]
lgtm!

**Review by andrewbrown00 — CHANGES_REQUESTED** [review]
Hey, @AGMETEOR, I tested the batch emails a few times, but for some reason, I could only get it to work the first time. See the issues below:

image

- [ ] 1. We need to adjust the message if only 1 user sends multiple messages via a channel, DM, and GM to read "{userName} sent you new messages"
- [ ] 2. All three of the message I sent were combined into a single card, instead of three separate cards? Is this because I sent the same message to a channel, DM, and GM? Either way, they should be treated as individual cards and sent as a batch.
- [ ] 3. User avatar is missing, likely because of the collision of the messages
- [ ] 4. Assuming this is wrapping because of the issue with all the messages being sent in one card. If not, we may need to consider changing the truncating rules?
- [ ] 5. The timestamp is broken, not sure why it’s showing the 24-hour clock, we have 12-hour set on the PR
- [ ] 6. The `channel tag` is broken, but I assume this won’t be an issue once we resolve the message being grouped vs the expected of individual cards?

**Comment by amyblais** [comment]
@AGMETEOR Kind reminder for fixes ^

**Comment by AGMETEOR** [comment]
> @AGMETEOR Kind reminder for fixes ^

Yes I have it on the radar

**Comment by AGMETEOR** [comment]
Hello @andrewbrown00 thanks for the feedback. Most of the issues you mentioned were pre-existing. I have tried to fix all of them and the PR is ready for another review.

**Review by andrewbrown00 — CHANGES_REQUESTED** [review]
Thanks, @AGMETEOR, this is a great improvement over the current broken experience. We are really close to nailing this down. The `Group` messages have a few items to resolve:


- [x] 1. The count is still off, I only sent messages from 2 users to the same user. For simplicity, let’s simplify the title for batch messages to read “You have new messages”
- [x] 2. 'View this message' isn’t centered on any of the cards
- [ ] 3. One message was missed from the batch and came as a single message, see second screenshot below
- [ ] 4. Fix the styling of users' tags for group messages by removing the channel icon and show count as we do in the LHS. It's using the channel icon (I assume this is because group messages are technically channels and not treated as a group 'direct' message).
   - The user name should follow the same truncation rule we set for the other emails, truncate at 22 characters   
   - Don't wrap the user names inside the tag, there should also truncate based on the available space to stay on a single line. This should also resolve the timestamp wrapping.
   - **Note**, the username, timestamp, and tag should only occupy one line, no wrapping

    image

   **Solo message that should have been part of the batch**

   image

**Comment by AGMETEOR** [comment]
Hello @andrewbrown00 this hasn't been worked on for a while because I was out the whole of last week till Tuesday this week. 
I have worked on the following points as pointed out in your last feedback
1) Worked on it
2) Worked on it
3) Couldn't fix on this PR. I have failed to reproduce this issue on my side. This issue also looks like it's best suited for someone on the platform team.
4) Worked on it

Screenshot 2021-09-09 at 15 24 06

**Comment by AGMETEOR** [comment]
Hi @andrewbrown00 , gentle ping on this

**Review by stevemudie — APPROVED** [review]
These all look good and contain the new branding as expected. Nice work @AGMETEOR!

**Review by andrewbrown00 — CHANGES_REQUESTED** [review]
Thanks, @AGMETEOR, we really close.

**Item to resolve**
- [ ] The message from a group was _partially_ resolved. It does display the user count to align with how group messages display in the LHS, but we also need to include the user names for context. Note, this should not wrap and follow the other truncation rules to stay on a single line.

Group message 1 | Group message 2
----- | -----
image | image

**Both of these ☝️ should include the usernames following the `#` (count)**, for example `2` userName, userNa... (this is showing if there's not enough horizontal space and we have to truncate).

**Comment by andrewbrown00** [comment]
@AGMETEOR, regarding:

>  Couldn't fix on this PR. I have failed to reproduce this issue on my side. This issue also looks like it's best suited for someone on the platform team.

Will you work with someone on the platform team to help resolve the batching issue, thanks.

**Comment by AGMETEOR** [comment]
> Thanks, @AGMETEOR, we really close.
> 
> **Item to resolve**
> 
> * [ ]  The message from a group was _partially_ resolved. It does display the user count to align with how group messages display in the LHS, but we also need to include the user names for context. Note, this should not wrap and follow the other truncation rules to stay on a single line.
> 
> Group message 1	Group message 2
> image	image
> **Both of these ☝️ should include the usernames following the `#` (count)**, for example `2` userName, userNa... (this is showing if there's not enough horizontal space and we have to truncate).

**Comment by AGMETEOR** [comment]
> @AGMETEOR, regarding:
> 
> > Couldn't fix on this PR. I have failed to reproduce this issue on my side. This issue also looks like it's best suited for someone on the platform team.
> 
> Will you work with someone on the platform team to help resolve the batching issue, thanks.

Opened an issue here https://mattermost.atlassian.net/browse/MM-38602

**Comment by AGMETEOR** [comment]
@andrewbrown00 just a note that for GM I change the truncating rule for the channel name to truncate at 11 chars in order to have content fit on one line

**Review by andrewbrown00 — APPROVED** [review]
Thanks, @AGMETEOR, looks great 🙌 

image

**Pull request merged**
