### PR TITLE
MM-32013: Do not allow password change in /auth endpoint

### PR DESCRIPTION
**Pull request by agnivade**
We were allowing new password to be reset without asking
for the old password. This was not advertised but was possible nevertheless
through the API.

Since there is already a separate API to change password, we choose to remove
this functionality.

https://mattermost.atlassian.net/browse/MM-32013

```release-note
The /api/v4/users/me/auth API endpoint cannot be used to change password anymore.
This was a hidden feature that was not documented, but was nevertheless possible.
We are just removing the hidden feature.
```

### CODE REVIEW

**Comment by srkgupta** [comment]
Hi @agnivade 
Can you please fix the failing unit tests.

**Comment by isacikgoz** [comment]
The ticket description may be misleading. This API was allowing sysadmins to update any users password w/o requiring the existing one. Updating a users own password is another thing. I mean, I am thinking that this API can used by system administrators in some scenarios and I wonder if this was intended?

**Comment by srkgupta** [comment]
@isacikgoz Currently when sysadmin sets password for a different user, it leverages a different API endpoint, i.e. `/password`.  Hence ideally the `/auth` API endpoint is not & should not be used to reset any user's password. I am 3/5 if this API is even called from system console.

**Comment by isacikgoz** [comment]
I see, thanks for the explanation @srkgupta.

**Review by srkgupta — APPROVED** [review]
Thanks @agnivade. The changes LGTM

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by agnivade** [comment]
This just removes hidden functionality. So nothing to verify.

**Pull request merged**
