### PR TITLE
[MM-37727] - Self-managed: Update email template to new branding - Mention

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR updates email templates for Mentions and consequently as updates templates for DMs and GMs

Screenshot 2021-08-13 at 11 33 56
Screenshot 2021-08-13 at 11 35 12
Screenshot 2021-08-13 at 11 39 58

#### Ticket Link
[MM-37727](https://mattermost.atlassian.net/browse/MM-37727)
[MM-37728](https://mattermost.atlassian.net/browse/MM-37728)
[MM-37729](https://mattermost.atlassian.net/browse/MM-37729)

```release-note
NONE

```

### CODE REVIEW

**Comment by AGMETEOR** [comment]
@matthewbirtch just a note that in the email templates `@usernames` are currently not styled as this would require some text formatting code that's not yet available.

**Comment by matthewbirtch** [comment]
@AGMETEOR can I test these out using a SpinWick test server?

**Review by matthewbirtch — DISMISSED** [review]
Hey @AGMETEOR it looks like the mention email has a broken layout. I'm guessing it's mostly due to the unrealisticly long username?

**Long username**
image

**Short username**
image

Is it possible to truncate the username with a `…` so we don't have this problem?

**Review by nickmisasi — APPROVED** [review]
Code LGTM! lmk if you want another review after implementing some of Matt's requested changes!

**Review by marianunez — APPROVED** [review]

**Comment by AGMETEOR** [comment]
> Hey @AGMETEOR it looks like the mention email has a broken layout. I'm guessing it's mostly due to the unrealisticly long username?
> 
> **Long username**
> image
> 
> **Short username**
> image
> 
> Is it possible to truncate the username with a `…` so we don't have this problem?

@matthewbirtch updated the code to do that. See screenshots
Screenshot 2021-08-16 at 13 47 19

Screenshot 2021-08-16 at 13 48 34

**Review by pablovelezvidal — APPROVED** [review]
LGTM! :shipit:

**Comment by AGMETEOR** [comment]
Hello @stevemudie , I have included the QA steps in the tickets

**Comment by andrewbrown00** [comment]
Hey, @AGMETEOR, we need to truncate the **username**, looks like the `channelName` is get truncated instead

image

**Comment by AGMETEOR** [comment]
> Hey, @AGMETEOR, we need to truncate the **username**, looks like the `channelName` is get truncated instead
> 
> image

@andrewbrown00 sorry, my bad it was supposed the username not channel name

Screenshot 2021-08-16 at 20 58 51

**Review by stevemudie — APPROVED** [review]
Tested and passed. Looks good!

New branding observed in all three scenarios laid out in the associated tickets.

**Comment by andrewbrown00** [comment]
Thanks, @AGMETEOR 👍 

What are the rules for truncation? It looks like we are truncating the username with a lot of space left over. It would be best to fill the space available on the single line and truncate only if needed.

**Current**
image

**Proposed**
image

**Comment by AGMETEOR** [comment]
> Thanks, @AGMETEOR 👍
> 
> What are the rules for truncation? It looks like we are truncating the username with a lot of space left over. It would be best to fill the space available on the single line and truncate only if needed.
> 
> **Current**
> image
> 
> **Proposed**
> image

@andrewbrown00 the code truncates if the name is greater than 9 characters long. We can increase that 38 characters as per your screenshot?

**Comment by andrewbrown00** [comment]
@AGMETEOR are we able to set it based on the available space since the time stamp and channel name can change? Or do we have to give it a fixed character count to truncate?

> @andrewbrown00 the code truncates if the name is greater than 9 characters long. We can increase that 38 characters as per your screenshot?

**Comment by AGMETEOR** [comment]
> @AGMETEOR are we able to set it based on the available space since the time stamp and channel name can change? Or do we have to give it a fixed character count to truncate?
> 
> > @andrewbrown00 the code truncates if the name is greater than 9 characters long. We can increase that 38 characters as per your screenshot?

With the way email templating works, it's really hard to do that. We just have to depend on the characters of the name and truncate

**Comment by andrewbrown00** [comment]
Thanks for the context, let's go ahead and set the rule to be 22 characters. This matches the character limit when creating a username. We can adjust accordingly if this is problematic to handle username and or first and last name use cases.

**Comment by AGMETEOR** [comment]
> Thanks for the context, let's go ahead and set the rule to be 22 characters. This matches the character limit when creating a username. We can adjust accordingly if this is problematic to handle username and or first and last name use cases.

I have adjusted to 22 as suggested.

**Comment by AGMETEOR** [comment]
@stevemudie here are the users

#### Existing
- username: sysadmin | password: Sys@dmin123


#### New users
- username: existing-1 | password: Sys@dmin123

**Review by andrewbrown00 — CHANGES_REQUESTED** [review]
Thanks, @AGMETEOR, looking good, small change:

- [ ] The `highlight` is missing from the @mention. It should use the `Denim/Mention Highlight BG #FFD470` color.

Channel | Direct Message | Group Message
------------ | ------------- | -------------
image | image | image

**Comment by AGMETEOR** [comment]
> Thanks, @AGMETEOR, looking good, small change:
> 
> * [ ]  The `highlight` is missing from the @mention. It should use the `Denim/Mention Highlight BG #FFD470` color.
> 
> Channel	Direct Message	Group Message
> image	image	image

@andrewbrown00 it’s technically not possible to style the “@mention” because of the way the templating is done.

**Comment by AGMETEOR** [comment]
> > Thanks, @AGMETEOR, looking good, small change:
> > 
> > * [ ]   The `highlight` is missing from the @mention. It should use the `Denim/Mention Highlight BG #FFD470` color.
> > 
> > Channel	Direct Message	Group Message
> > image	image	image
> 
> @andrewbrown00 it’s technically not possible to style the “@mention” because of the way the templating is done. We send the entire message as one to the template. Even in the templates before this change the highlight is not there.

**Comment by AGMETEOR** [comment]
> Thanks, @AGMETEOR, looking good, small change:
> 
> * [ ]  The `highlight` is missing from the @mention. It should use the `Denim/Mention Highlight BG #FFD470` color.
> 
> Channel	Direct Message	Group Message
> image	image	image

Hello @hmhealey , any idea on how we can do this?

**Comment by andrewbrown00** [comment]
Thanks, @AGMETEOR, I'll wait and see if Harrison has any feedback. If we can't do it, then I'll re-review the PR and approve since all other changes were good to go 🙂 .

> @andrewbrown00 it’s technically not possible to style the “@mention” because of the way the templating is done. We send the entire message as one to the template. Even in the templates before this change the highlight is not there.

**Review by andrewbrown00 — APPROVED** [review]
Thanks, @AGMETEOR, changes looking good 🙂 

* Verified the email is sent and styled correctly for:
   * Channel mentions
   * Direct messages
   * Group messages 

Channel | Direct Message | Group Message
------------ | ------------- | -------------
image | image | image

**Comment by hmhealey** [comment]
The at mention can’t actually be styled since we don’t have any logic on the server for recognizing those in emails yet. There’s almost certainly a ticket around for it somewhere though.

**Comment by AGMETEOR** [comment]
> The at mention can’t actually be styled since we don’t have any logic on the server for recognizing those in emails yet. There’s almost certainly a ticket around for it somewhere though.

Thanks for the verification.

**Pull request merged**
