### PR TITLE
Update incident-collaboration to 1.4.0

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Update incident-collaboration plugin to 1.4.0
- To be approved/merged after pre-release smoke tests have passed.

#### Ticket Link
- none
- 
#### Release Note
```release-note
Updated Incident-collaboration plugin from 1.3.2 to 1.4.0.
```

### CODE REVIEW

**Review by prapti — COMMENTED** [review]
This seems a bit odd that I'm getting the following server error on this branch although nothing stands out to me as unusual in this PR:
`# github.com/mattermost/mattermost-server/v5/enterprise/saml
enterprise/saml/saml_base_tests.go:789:44: too many arguments in call to sth.th.App.Srv().Store.User().Get
	have (context.Context, string)
	want (string)`
And there is also the following JS error in the console:
`Warning: Failed prop type: The prop `defaultMessage` is marked as required in `FormattedMarkdownMessage`, but its value is `undefined`.`

@cpoile Am I missing something?

**Comment by cpoile** [comment]
@prapti Seems to be fine now? Is it good to go?

**Review by prapti — APPROVED** [review]
Yeah, looking good now! No errors on local startup.
Approving.

**Comment by amyblais** [comment]
@lieut-data Is this for v5.33 or v5.34?

**Comment by lieut-data** [comment]
@amyblais, I was hoping this would get (organically) included in v5.33 on the assumption that we've abandoned the quality release cadence and will just cut v5.33 from master. If we're still following the quality release cadence, I'll need to sync with @itao since I'm not sure if we should be pushing "feature changes" in quality releases.

**Comment by amyblais** [comment]
@lieut-data v5.33 will based off of Cloud February 24th release. I can cherry-pick this to the ``cloud`` branch.

**Comment by lieut-data** [comment]
Ah yes, the cloud cadence -- I hadn't done the math correctly there. Thanks for the assist, @amyblais!

**Comment by cpoile** [comment]
Thanks @amyblais !

**Pull request merged**
