### PR TITLE
Creating post by intercepting requests

### PR DESCRIPTION
**Pull request by safakkizkin**
#### Summary
Prevents post creation on private channel with non-member user token. 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/21124

#### Release Note
```release-note
Changed Post_Test, if channel is private user should be in the channel.
Added IsSessionMemberOfChannel to app interface.
```

### CODE REVIEW

**Comment by safakkizkin** [comment]
As described in the [issue](https://github.com/mattermost/mattermost-server/issues/21124), the request goes to 123, but what I thought we need to solve it before the request comes there. So I added the return to there. Because of my unfamiliarity to the codebase, let me know if I need to change it on function [SessionHasPermissionToTeam](https://github.com/mattermost/mattermost-server/blob/25e9399b3e07df30dd862df8721d33596101562d/app/authorization.go#L128), [SessionHasPermissionTo](https://github.com/mattermost/mattermost-server/blob/25e9399b3e07df30dd862df8721d33596101562d/app/authorization.go#L131) or any other function.

**Comment by safakkizkin** [comment]
rebased to be sure everything is great

**Comment by mkraft** [comment]
We're going to be having a discussion about whether membership in channels will be a requirement to read and post in private channels. I'll circle back with our decisions.

**Comment by mkraft** [comment]
I'm going to close this since authorization to post should be managed via the permissions system not via membership.

**Pull request closed without merging**
