### PR TITLE
Revert "fix npm ci step"

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
This reverts commit 05192cb3f8e60898d4fb9ef9c012e6679d5a8aad.
This CI step was simplified in the past, but doesn't seem to work, so reverting to previous solution

### CODE REVIEW

**Comment by hanzei** [comment]
I would like to deffer this to @cpanato as he introduced the change AFAIK

**Comment by cpanato** [comment]
agree on that, but include the @mattermost/core-build-engineers as well in the discussion


removing @stylianosrigas from the review as well

**Comment by cpanato** [comment]
@reflog i think you need to do the same in the enterprise repo

**Comment by reflog** [comment]
> @reflog i think you need to do the same in the enterprise repo

Good catch, will do

**Comment by reflog** [comment]
@cpanato - just checked, it's already fixed in enterprise

**Pull request merged**
