### PR TITLE
MM-15219 Add support for introduction text in interactive dialogs

### PR DESCRIPTION
**Pull request by tgkouras**
#### Summary
Adds an optional field to the `model.Dialog` struct  called `introductionText` that can accept markdown formatted text.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-15219
https://github.com/mattermost/mattermost-server/pull/12029

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/3583
https://github.com/mattermost/mattermost-plugin-demo/pull/64
https://github.com/mattermost/mattermost-api-reference/pull/470
https://github.com/mattermost/mattermost-mobile/pull/3222

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for PR @tgkouras. Let me know, when this is ready for review!

**Comment by tgkouras** [comment]
@hanzei @lieut-data This should now be ready.  There is a discussion starting in the mobile app PR regarding what markdown to support (mattermost/mattermost-mobile#3222)

**Comment by hanzei** [comment]
This will be tested with the webapp PR.

**Comment by marianunez** [comment]
Great addition! Using this now and found this looking at the code and the demo plugin example. 

@aaronrothschild should we update the documentation [here](https://docs.mattermost.com/developer/interactive-dialogs.html#parameters) to include this new feature so it can be discoverable by all?

**Pull request merged**
