### PR TITLE
Bump GitLab plugin prepackaged version to 1.6.0 

### PR DESCRIPTION
**Pull request by mickmister**
#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-49047

#### Release Note

```release-note
Update prepackaged GitLab plugin version to v1.6.0.
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM, but we need to wait for https://github.com/mattermost/mattermost-plugin-gitlab/pull/340 to be merged.

**Comment by amyblais** [comment]
@DHaussermann Please help prioritize this review today https://github.com/mattermost/mattermost-plugin-gitlab/pull/340.

**Review by lieut-data — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Pre-packaged bumped to `v1.6.0`
- `v1.6.0` is available with no remote marketplace access
- Tested on server running older server code that this pre-package plugin upgrade occurs successfully

No issues found LGTM!

**Comment by DHaussermann** [comment]
@amyblais sorry for delays on this. This is now ready to merge.

**Pull request merged**
