### PR TITLE
Moved UserHasJoinedTeam after the processing

### PR DESCRIPTION
**Pull request by levb**
#### Summary
`UserHasJoinedTeam` was being called _before_ the user was added to the team, resulting in a permission violation in the apps plugin, which was trying to access the team with the user's credentials, expecting them to work. Now it is called after the user is in the team.

Known plugins relying on UserHasJoinedTeam:
- https://github.com/mattermost/mattermost-plugin-demo
- https://github.com/mattermost/mattermost-plugin-nop
- https://github.com/mattermost/mattermost-plugin-welcomebot
- https://github.com/mattermost/mattermost-plugin-apps
- https://github.com/mattermost/mattermost-plugin-recommend

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43960

#### Release Note
```release-note
Moved UserHasJoinedTeam callback to after the user is added to team
```

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by levb** [comment]
@DHaussermann the "core" testing of this PR is handled by https://github.com/mattermost/mattermost-plugin-apps/pull/336; `bot_joined_team` was not working until, and now is.

I checked the source code of the 5 plugins ^^ and they do not appear to depend on the before/after timing, specifically because the plugin API is not permission-checked. However, some level of testing on these 5 is due, particularly `welcomebot`.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- As per guidance from Lev, I did a significant amount of regression testing here. 
- Tested demo-plugin, welcomebot and channel recommend
- For all 3 plugins - No change in behavior observed
- All Plugins behave as expected when a new user joins the team
- Also did brief testing with Apps plugin no functional changes found.  

LGTM!

Will test this change with https://github.com/mattermost/mattermost-plugin-apps/pull/336 as well

**Pull request merged**
