### PR TITLE
Cache test users to speed up testing

### PR DESCRIPTION
**Pull request by Pomyk**
#### Summary
Users were recreated for many tests and hashing passwords takes a lot of
time. Testing /api4 takes around 120s less and /app 60s less.

### CODE REVIEW

**Comment by agnivade** [comment]
I will let @jupenur review this because it has some security implications. Even for tests.

**Comment by jasonblais** [comment]
@agnivade @jespino is this PR ready to merge, or is it pending another review? Should QA have a look?

**Comment by agnivade** [comment]
Nope, I think this is good to go.

**Comment by hanzei** [comment]
@jespino @jupenur This PR seam to require EE changes as `UseTestStore` is used in the EE code. Would one of you be open on submitting a PR for this?

**Comment by jasonblais** [comment]
@agnivade @jespino @jupenur on the above note from Hanzei

> This PR seam to require EE changes as `UseTestStore` is used in the EE code. Would one of you be open on submitting a PR for this?

**Comment by agnivade** [comment]
I will let either of the reviewers do it.

**Comment by jupenur** [comment]
I'm not a dev, so hoping @jespino can handle it.

**Comment by jespino** [comment]
@jupenur sure, I can

**Comment by jespino** [comment]
@Pomyk Thanks! now is merged, and it saving some minutes to the CI and running the integration tests locally! :tada:

**Pull request merged**
