### PR TITLE
move file backend to the platform service

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Move file backend into platform service

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45840

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
ping @noxer

Also, tested this on community on demand and I was able to upload attachments. I would like to try plugin upload but it's above my authority with the testuser :p

**Review by noxer — APPROVED** [review]

**Comment by isacikgoz** [comment]
Let's run an e2e test to be sure.

/e2e-test

**Comment by isacikgoz** [comment]
@saturninoabril the report job (https://git.internal.mattermost.com/qa/cypress-ui-automation/-/jobs/1138373) is constantly failing but the tests seem to look okay. Do you think it's okay to merge anyway?

**Comment by saturninoabril** [comment]
Thanks for checking! Looking at this now.

**Review by saturninoabril — APPROVED** [review]
All looks good. Found 3 specs different from master but all were verified passing locally.
Screen Shot 2022-10-21 at 5 16 22 PM
Screen Shot 2022-10-21 at 5 17 11 PM
Screen Shot 2022-10-21 at 5 19 29 PM

**Pull request merged**
