### PR TITLE
IS-299: Checkout webapp over HTTPS on CircleCI

### PR DESCRIPTION
**Pull request by jupenur**
#### Summary
Checkout the webapp repo over HTTPS to avoid `StrictHostKeyChecking=no`.

#### Ticket Link
https://mattermost.atlassian.net/browse/IS-299

### CODE REVIEW

**Comment by agnivade** [comment]
Apologies for the drive-by comment, but I am wondering whether we could keep the ssh cloning and still have the stricthostkey checking ?

Is using `ssh-keyscan github.com >> ~/.ssh/known_hosts` known to have vulnerability issues ?

A quick search here: https://discuss.circleci.com/t/add-known-hosts-on-startup-via-config-yml-configuration/12022 shows that only for proxy servers, this does not work. But it should work in all other cases.

**Comment by jupenur** [comment]
@agnivade sure, adding to `known_hosts` works fine, I just opted for HTTPS since it was a smaller change. Is there a specific reason why SSH should be preferred?

**Comment by agnivade** [comment]
> Is there a specific reason why SSH should be preferred?

Yes, cloning over ssh is usually faster than https because you don't have the application layer overhead. Typically https is only to be used for situations where you are behind a corporate firewall that do not allow anything other than http/https trafic, or in situations where you don't have the technical know-how to create and add ssh keys.

GitHub has changed their stance several times over which method is recommended. Currently they recommend https, but that's only because it's dead simple to setup. But if we can, I think we should use ssh.

It's just a suggestion. Please feel free to take a call. I don't have any experience in this area whatsoever.

**Comment by jupenur** [comment]
Let's go with HTTPS if there's no clear reason to prefer SSH. HTTPS has at least the following benefits:
 - The change is smaller and the resulting config less complicated
 - In the long-term it's more maintainable because there are no hard-coded host keys

We can always switch back to SSH if a reason comes up.

**Pull request merged**
