### PR TITLE
9140 find the mentions with spaces

### PR DESCRIPTION
**Pull request by pradeepmurugesan**
#### Summary
Mentions with spaces are not supported. adding the server side support for the same

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/9140 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

### CODE REVIEW

**Comment by pradeepmurugesan** [comment]
rewrite the existing mention parser is hard since the string matching algorithms usually find the substring and its hard to differentiate for the message 

```This is the message for user.name in channel x```

and the available keywords being 

```user.name and user. ```

In the above case both will be notified. 

So handled the spaces separately for now.

**Comment by pradeepmurugesan** [comment]
@hmhealey thanks for reviewing.. I will look into the library..

**Comment by pradeepmurugesan** [comment]
@hmhealey I tried out the library. I think its still not solving the problem of matching the whole words.

Will look if I can find something to solve this problem. 

Kindly look into the screenshot and let me know if I am missing something.

I am having an array of string that needs to be matched
```
 ["red car", "this is a", "another strg"].
```

the text is 

```
"this is a message with another string and seared carrots"
```

I console log the hits and got the result as [0, 1]. i.e  ```red car``` and ```this is a``` gets matched

screen shot 2018-08-26 at 15 35 08

**Comment by esethna** [comment]
Thanks guys, bumped this from the v5.3 milestone given we are approaching feature complete

**Comment by hmhealey** [comment]
Hmm. We might need to look for a different approach then or to add some additional logic to check word boundaries then, although that may get complicated quickly. Perhaps there's some other library we could use to search for mention keywords

**Comment by jasonblais** [comment]
@hmhealey @esethna Any next steps here we can share?

**Comment by hmhealey** [comment]
Nothing that I'm aware of. I haven't been able to set aside any time to investigate this further

**Comment by cpanato** [comment]
`Setup Test Server` label detected. Spinmint test server created if build succeeds (checks pass and no conflicts with base branch).

**Comment by cpanato** [comment]
Spintmint test server creation failed. See the logs for more information.

**Comment by esethna** [comment]
Closing as per: https://github.com/mattermost/mattermost-webapp/pull/1489#issuecomment-444560116

**Pull request closed without merging**
