### PR TITLE
MM-47400 Stop trying to rewrite missing CSP meta tag in subpath code

### PR DESCRIPTION
**Pull request by hmhealey**
As part of https://github.com/mattermost/mattermost-webapp/pull/11001, I removed the CSP meta tag from the web app's HTML since it's unnecessary when the MM server is adding a CSP header, and I didn't want to spend more time trying to keep the two in sync. Unfortunately, this broke the part of the server that rewrites files when applying subpaths because it errors out if that tag isn't found.

I'm not 100% certain if this fixes the issue with subpaths since I don't have a local setup for it, but it seems like a pretty good shot. At the very least, the web app is now writing the script tag properly that sets `window.publicPath`, so hopefully that fixes the issue.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47400
https://mattermost.atlassian.net/browse/MM-47410

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@hmhealey There are some failing tests. And I believe Miguel is out of office next week.

**Comment by devinbinnie** [comment]
@hmhealey Tested this locally with this fix and can confirm the issue still persists. I think there's something in the webapp that needs to be addressed.

**Comment by hmhealey** [comment]
Cross-posting this from MM, but even if there's another PR needed, this fix is still needed

**Comment by amyblais** [comment]
> Cross-posting this from MM, but even if there's another PR needed, this fix is still needed

cc @srkgupta FYI

**Review by lieut-data — APPROVED** [review]
Looks good! Seems like the embedded `Content-Security-Policy` tag was removed with https://github.com/mattermost/mattermost-webapp/pull/3050. 

I guess the "new" `CSP_UNSAFE_EVAL_IF_DEV` handling in webpack.config.js takes care of the development flow, and the server already emits its own headers, but I'm wondering if we've missed the case where the webapp is hosted on a CDN -- https://docs.mattermost.com/configure/configuring-cloudfront-to-host-mattermost-static-assets.html.

**Comment by hmhealey** [comment]
Ugh, I didn't realize that was an option. That's also going to cause problems with how I was planning for the web app multi-product stuff to work as well...

I guess I'll just revert the client changes related to adding the CSP meta tag since I think you're right that that case will need it even though it's not needed in the vast majority of ways of running the web app.

Thanks for catching that now though since I'd rather deal with it now than have it go through support in a couple weeks

**Pull request closed without merging**
