### PR TITLE
Ordered plugin settings

### PR DESCRIPTION
**Pull request by ccbrown**
#### Summary
Allows plugin authors to define the order of their settings.

#### Ticket Link
N/A

#### Checklist
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by coreyhulen** [comment]
Looks good, but why 2 file types yaml and json?  why not just force everyone to pick one to make it simpler (0/5).  I don't think will use/allow yaml anywhere else in the code base.

**Comment by ccbrown** [comment]
If we had to pick only one, I would fight _**hard**_ for it to be YAML.

I'm 0/5 on supporting both vs. supporting only YAML, but I'm dead set on supporting YAML.

**Comment by ccbrown** [comment]
Also FYI support for both was something that was done from the beginning months ago, so definitely not within the scope of this PR. We can make a separate ticket if anyone feels strongly enough about dropping one (JSON).

**Comment by hmhealey** [comment]
This doesn't affect the schema of the plugin settings in the config.json, does it? It's possible that it would cause problems for our integration wtih GitLab if it did

**Comment by jwilander** [comment]
Nope, this is just for the schema for displaying the settings in the system console

**Comment by coreyhulen** [comment]
In cases like these I think it's way more important to be consistent (5/5).  We can debate the merits of JSON vs YAML, but the reality is both standards get the job done and it's hard to argue one is clearly superior over the other.

I'm OK with letting this in as long as our samples and documentation show JSON.

**Comment by ccbrown** [comment]
@coreyhulen I think we have a 5/5 versus 5/5 situation here. I think it's very easy to argue that YAML is superior and I'm extremely against JSON being the one more prominently shown in our documentation. Why do you think every modern technology we use (Docker, Travis, Codecov, Kubernetes, etc.) uses YAML?

**Comment by ccbrown** [comment]
> I'm OK with letting this in as long as our samples and documentation show JSON.

@coreyhulen I'm merging this anyways because this PR has absolutely nothing to do with this conversation. Let's continue this elsewhere.

**Pull request merged**
