### PR TITLE
Use the correct error variable from provider.GetSSOSettings

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-39208

https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=bd79b0b2-39d8-4538-81e1-a275b35ff910

```release-note
NONE
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Nice :+1:

**Comment by agnivade** [comment]
cc @amyblais for cherrypick candidate.

**Comment by amyblais** [comment]
@agnivade I missed checking earlier. Does this affect v5.37 ESR?

**Comment by agnivade** [comment]
Yes.

**Comment by amyblais** [comment]
@agnivade Since we're doing a 5.37 backport now, maybe this can be included. But it needs a manual cherry-pick :(

**Comment by agnivade** [comment]
Yep, expected. :(

**Pull request merged**
