### PR TITLE
Remove remnants of config watcher

### PR DESCRIPTION
**Pull request by agnivade**
The last part of config watching was in advanced logging.
We remove it from there too to keep things consistent.

https://community-daily.mattermost.com/plugins/focalboard/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=a1b58527-6a3d-4faa-8144-166a3698731f

```release-note
Removed config watch feature from advanced logging config.
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Farewell :wave:

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by agnivade** [comment]
@saturninoabril - Some testing around advanced logging configuration would be very helpful. We have removed the config watch feature. Just want to ensure that it didn't break anything else.

**Comment by agnivade** [comment]
@lindalumitchell - Since Saturn is out, wondering if you can suggest someone to run some quick tests around advanced logging on this one.

**Comment by lindalumitchell** [comment]
@agnivade, Malik will take a look at this. 👍

**Review by furqanmlk — APPROVED** [review]
### Type : File 

image

### Type: console ✅ 

Changed config while server is running 

image

**Comment by agnivade** [comment]
Hey @furqanmlk - the file option seems to be configured to write to mattermost_logr.log, but you are checking mattermost.log. Can you confirm you see the file mattermost_logr.log too?

**Comment by furqanmlk** [comment]
> Hey @furqanmlk - the file option seems to be configured to write to mattermost_logr.log, but you are checking mattermost.log. Can you confirm you see the file mattermost_logr.log too?

Hay @agnivade, sorry I attached wrong log.
Yes I can see the ```mattermost_logr.log```
So basically I am seeing one log file ```mattermost.log``` in log folder and two logs files ```mattemost.log``` and ```mattermost_loger.log``` in root folder

image

**Comment by agnivade** [comment]
Thanks for the confirmation!

**Pull request merged**
