### PR TITLE
MM-30836: Use feature flags for RemoteClusterService

### PR DESCRIPTION
**Pull request by agnivade**
We use a proper feature flag for toggling this feature.

### CODE REVIEW

**Comment by wiggin77** [comment]
Looks good @agnivade .  Can we also leave the `Config().ExperimentalSettings.EnableRemoteClusterService` in place as well?  We'll need both.  On-prem customers would enable/disble via that instead of feature flags.

**Comment by agnivade** [comment]
On-prem customers can also use feature flags via environment variables as per my understanding. Do we explicitly want to have both? That might defeat the purpose of having a feature flag. Either it's a config, or a feature flag.

**Comment by wiggin77** [comment]
> On-prem customers can also use feature flags via environment variables as per my understanding. Do we explicitly want to have both? That might defeat the purpose of having a feature flag. Either it's a config, or a feature flag.

Feature flags eventually get removed whereas we'll always need a way to disable these services.  I'm not clear on whether a config setting would suffice and obviate the need for feature flags.  Feature flags would allow cloud team to selectively enable via  Split. We can ask @crspeller what the indention is... do we need config setting and feature flags for enabling/disabling a service?

**Comment by agnivade** [comment]
I see. Then using a config flag is the correct way for this. Feature flags are meant to be like temporary things for experimental stuff which is eventually meant to be stable and enabled. That's why I asked originally whether you want a feature flag or not in the first place. If this is a permanent thing, then it's not a feature flag.

**Comment by wiggin77** [comment]
> I see. Then using a config flag is the correct way for this. Feature flags are meant to be like temporary things for experimental stuff which is eventually meant to be stable and enabled. That's why I asked originally whether you want a feature flag or not in the first place. If this is a permanent thing, then it's not a feature flag.

I still think we need both feature flags and config.  For example, when cloud team wants to try out these services they would enable in config, but use Split to activate for specific clusters.  The feature flag spec describes this use case.

**Comment by agnivade** [comment]
Sure.

**Comment by agnivade** [comment]
So which one should take priority? Feature flag or the config? Should we document this somewhere?

**Comment by crspeller** [comment]
@wiggin77 Does an experimental config and a feature flag make sense? 
I can see a regular config setting plus a feature flag. The config setting is just part of the feature.  But I feel like feature flags replace experimental config settings. Like @agnivade pointed out on-prem customers can enable feature flags using environment variables. 

Maybe I don't understand the rollout plan though. What's the plan for rolling this feature out to customers?

**Comment by wiggin77** [comment]
> @wiggin77 Does an experimental config and a feature flag make sense?
> I can see a regular config setting plus a feature flag. The config setting is just part of the feature. But I feel like feature flags replace experimental config settings. Like @agnivade pointed out on-prem customers can enable feature flags using environment variables.
> 
> Maybe I don't understand the rollout plan though. What's the plan for rolling this feature out to customers?

Thanks @crspeller.  There will always need to be a way to enable/disable these services via config, so eventually these will stop being experimental config items and move into the main config set.  IMO, the feature flags are not needed for on-prem but for cloud.  Cloud would enable the services in config, but use feature flags to enable for select customers.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
