### PR TITLE
 MM-14845 Fix for 4.10

### PR DESCRIPTION
**Pull request by grundleborg**

### CODE REVIEW

**Comment by grundleborg** [comment]
@cpanato is there a way to get Jenkins to run the tests on this PR (note that it's against the `release-4.10` branch)?

**Comment by cpanato** [comment]
@grundleborg i will check on Monday that

**Comment by cpanato** [comment]
09328741092837401928374

**Comment by cpanato** [comment]
@grundleborg saw this error

```
--- FAIL: TestSetRolePermissionsFromConfig (0.00s)
    authorization_test.go:100: Expected 'channel_user' to have 'delete_public_channel' permission when 'RestrictPublicChannelDeletion' is set to 'all'.
    authorization_test.go:100: Expected 'channel_user' to have 'manage_public_channel_properties' permission when 'RestrictPublicChannelManagement' is set to 'all'.
    authorization_test.go:100: Expected 'channel_user' to have 'manage_private_channel_properties' permission when 'RestrictPrivateChannelManagement' is set to 'all'.
```

**Comment by cpanato** [comment]
09328741092837401928374

**Comment by cpanato** [comment]
09328741092837401928374

**Pull request merged**
