### PR TITLE
[MM-20723] Add golint for plugin package to golangci

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
https://github.com/mattermost/mattermost-server/pull/12686  added support for golint checks but this doesn’t work because golint isn’t installed on the CI machines. Now we have `golangci-lint` in place, we can just use this.

The only solution I could come up with was adding a blacklist to the check. This has the nice benefit of enforcing the check for newly added packages. I also fixed some low hanging fruits in `plugin` to keep the blacklist shorter.

Please note that issues of the type `(comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)` are ignore my `golangci-lint` by default. We can iterate on this later. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20723

### CODE REVIEW

**Comment by hanzei** [comment]
cc @agnivade

**Comment by hanzei** [comment]
> And probably we can open a HelpWanted task to add the comments on exported functions/methods/structs. It would help flesh out the godocs and also help anybody reading the codebase.

Big :+1: for this. I would like to first fix these "easy" issues and then add the comments, because it's much harder and will probably require un exporting some structs.

**Comment by ali-farooq0** [comment]
@hanzei what kind of QA does this require? Just smoke test?

**Comment by hanzei** [comment]
@ali-farooq0 Please see the QA test steps in the ticket.

**Comment by agnivade** [comment]
Gentle bump on this. The golint step is actually polluting the CI logs by throwing "command not found" and confusing folks. @reflog got bit by this.

**Comment by hanzei** [comment]
@grundleborg Great that you support the change :+1:

**Comment by hanzei** [comment]
@saturninoabril Would you be open on reviewing this ticket given that @prapti is busy testing plugin signing?

**Comment by saturninoabril** [comment]
Sure, will take a look

**Comment by saturninoabril** [comment]
@hanzei Feel free to merge.

**Comment by hanzei** [comment]
> Non-blocking but should this warning be fixed in this PR:
> 
> ```
> level=warning msg="[runner] Can't run linter goanalysis_metalinter: findcall: analysis skipped: errors in package: [/go/src/github.com/mattermost/mattermost-server/v5/testlib/resources.go:64:58: cannot use (func(fileInfo os.FileInfo) bool literal) (value of type func(fileInfo os.FileInfo) bool) as func(os.FileInfo) bool value in argument to fileutils.FindPath /go/src/github.com/mattermost/mattermost-server/v5/testlib/resources.go:49:57: cannot use (func(fileInfo os.FileInfo) bool literal) (value of type func(fileInfo os.FileInfo) bool) as func(os.FileInfo) bool value in argument to fileutils.FindPath]"
> ```

Do you see this warning locally or on CI?

**Comment by saturninoabril** [comment]
Only in CI - https://golangci.com/r/github.com/mattermost/mattermost-server/pulls/13090

**Comment by hanzei** [comment]
Fixed a ticket for this: https://mattermost.atlassian.net/browse/MM-21069

cc @agnivade

**Pull request merged**
