### PR TITLE
translations PR 20181128 (adds Ukrainian)

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by jasonblais** [comment]
@enahum Build failed

**Comment by enahum** [comment]
No idea why is this failing now, @cpanato can you take a look please

**Comment by cpanato** [comment]
@enahum build running again

**Comment by jasonblais** [comment]
@enahum let's merge

**Pull request merged**
