### PR TITLE
[MM-33264] db/migrations: add migration scripts for Remote Clusters

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary

Add migration scripts for Remote Clusters

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-33264

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by nronas** [comment]
@isacikgoz if my understanding is correct here, this will potentially have to be amended as soon as the shared channels branch is merged on master right? So in a sense, we are adding a dependency between migrations and shared channels. Happy with it, just want to double-check with you if that's the case

**Review by nronas — APPROVED** [review]
Codewise in comparison with master LGTM. Prob this will change as soon as shared channels is merged to master.

**Comment by isacikgoz** [comment]
@nronas Yes, I think these migrations should be on hold until shared channels is merged to master branch. Adding the label.

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Pull request merged**
