### PR TITLE
typo in makefile

### PR DESCRIPTION
**Pull request by neallred**
#### Summary
Noticed this typo which makes the command fail

#### Ticket Link
N/A

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Ahh I missed that, Thanks!

**Comment by neallred** [comment]
I don't know mockery all that well, but also noticed `sharedchannel-mocks` has `--inpkg` errors with no argument that is causing it to error. Should there be an argument supplied there? If so, what? If I remove, it succeeds, but it also creates new files, which I'm guessing isn't rigiht.

```
services/sharedchannel/AppIface_test.go
services/sharedchannel/ServerIface_test.go
```

**Comment by agnivade** [comment]
Please change `--inpkg` to `--inpackage`. I upgrade the tool and did not exhaustively run all of the mock commands. My apologies.

**Comment by neallred** [comment]
@AGMETEOR gentle ping to review

**Review by AGMETEOR — APPROVED** [review]

**Pull request merged**
