### PR TITLE
MM-12211 Add setting to let everyone create user access tokens

### PR DESCRIPTION
**Pull request by ThiefMaster**
#### Summary
Enabling this lets all users create user access tokens, without requiring an admin to enable tokens for them first.

#### Ticket Link
https://pre-release.mattermost.com/core/pl/jkerpgtu63ywxej84aqhhmw6ie

#### Checklist
- [ ] Added or updated unit tests [TODO]

### CODE REVIEW

**Comment by jasonblais** [comment]
Two quick notes:

1) Is there a concern with making it super-simple for admins to give all users access to create personal access tokens? Given the session never expires and given people are typically more careful with sharing passwords than they are with sharing tokens. There have been issues in the past where Slack access tokens were shared in a public GitHub repo as they didn't understand the consequences.
2) Any conflicts with the advanced permissions feature?

**Comment by jasonblais** [comment]
Discussion for the above questions was held here: https://pre-release.mattermost.com/core/pl/pq1yahyn3tb1ddifnrfa1n6ftr

Conclusion: We'll keep the changes you've made here @ThiefMaster. That means by default we'll:

1. restrict personal access token creation to admins by default
2. give an option in TE and EE to enable personal access token creation for all users so that integration development is easier and more secure, given admins can already allow all users to create integrations

This is also consistent with `EnableOnlyAdminIntegrations` setting.

----

The only caveat is that `EnableOnlyAdminIntegrations` was moved to the permissions scheme in Enterprise Edition, so we'd need to do the same for the new tokens setting too. Not sure if that's something that only a Mattermost staff member can do.

**Comment by jasonblais** [comment]
@ThiefMaster Apologize for the delay, but we're ready to proceed. I have created a ticket for us to track: https://mattermost.atlassian.net/browse/MM-12211

The only change I have in mind is whether the config.json setting should be named `EnableOnlyAdminUserAccessTokens`. Thoughts @jwilander?

This is otherwise ready for dev review.

**Comment by jasonblais** [comment]
@ThiefMaster This would also need a rebase.

**Comment by jwilander** [comment]
I don't like `EnableOnlyAdminUserAccessTokens` because that's really confusing to me and would flip the bit. I'm OK with the current name though it should be `Personal` not `User` as all our documentation calls them "Personal Access Tokens" (even though in code they're user access tokens).

If we were to change it, I'd go with `AllowPersonalAccessTokensForAllUser`. To me that's very readable and clear

**Comment by jasonblais** [comment]
Is it clear to use personal access tokens since the other setting is `EnableUserAccessTokens`?

**Comment by jwilander** [comment]
Oh didn't realize the other setting was `User` not `Personal`. In that case I'd say let's use `AllowUserAccessTokensForAllUsers`

**Comment by ThiefMaster** [comment]
rebase+rename done

**Comment by jwilander** [comment]
Actually asking for @grundleborg's review as this is permission related

**Comment by cpanato** [comment]
@ThiefMaster thanks for this PR. Can you add some tests cases for this change?

**Comment by jwilander** [comment]
@cpanato let's hold off on dev review, I think @jasonblais is working with @ThiefMaster on gathering use cases

**Comment by jasonblais** [comment]
Adding a "work in progress" label for this for now while the use cases are discussed. For those interested, you can read the thread here https://github.com/42wim/matterircd/issues/29#issuecomment-423632179

**Comment by jasonblais** [comment]
Hey @ThiefMaster - wondering your thoughts on this PR?

While I see your use case for personal access tokens, I'm wondering if that is the optimal approach for solving the problem (as discussed and outlined at https://github.com/42wim/matterircd/issues/29#issuecomment-423632179)

Are there other approaches or capabilities that Mattermost could better support GitLab (and other non-email logins) on matterircd? Or are personal access tokens the only way to go?

**Comment by ThiefMaster** [comment]
I think the problem with any other options is that they need to go through the login flow - either using credentials or SSO (both are not nice for standalone clients, since you might not want to put them in a config file there or enter them every time you start them) or OAuth (which is not really a suitable option for clients that are not web-based)

**Comment by jasonblais** [comment]
I'm curious how other apps handle it? Is it with a personal access token, do you know?

**Comment by ThiefMaster** [comment]
At least apps using the GitHub API usually ask the user to generate a token (unless they're webapps that can use oauth). Not sure about other services providing this kind of integrations

**Comment by jasonblais** [comment]
Do they ask to generate one before logging in? Curious what the user experience is like for the GitHub API.

**Comment by ThiefMaster** [comment]
Yep, e.g. https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

**Comment by evaryont** [comment]
@ThiefMaster is there a reason why this PR was closed?

**Comment by jasonblais** [comment]
@evaryont 

The main use case for this PR is to more easily allow end users to use GitHub SSO on clients like Matterircd https://github.com/42wim/matterircd

However, we're hesitant taking the PR as-is given
1. it adds long-term support and testing effort for a use case the personal access tokens weren't initially intended for
2. it can encourage administrators to enable access tokens to anyone, when in the general use case (integrations) it should only be enabled to a limited subset of users for security reasons.

We are exploring other approaches. I have opened a comment to discuss with the Matterircd community if there are other options we can take: https://github.com/42wim/matterircd/issues/29

The other approach is writing a small plugin that lets admins enable tokens for users if they want to use a Matterircd-type client.

**Pull request closed without merging**
