### PR TITLE
ComplianceStore migration

### PR DESCRIPTION
**Pull request by rvillablanca**
#### Summary

Migration of `ComplianceStore` to return plain errors.

### CODE REVIEW

**Comment by rvillablanca** [comment]
Unable to reproduce these failed tests, random failed tests again :( ?

**Comment by agnivade** [comment]
The test is fixed in master. Should be good once you get the latest.

**Comment by rvillablanca** [comment]
Strange because it is already based on the latest master :thinking:, even the others PR are updated as well

**Comment by jespino** [comment]
@agnivade: I think this needs changes in enterprise too.

**Comment by agnivade** [comment]
@jespino - yep. Would you be open to fixing this one? :D I can take the next one.

**Comment by rvillablanca** [comment]
> @jespino - yep. Would you be open to fixing this one? :D I can take the next one.

Give me access and I will fix both and more for you :sweat_smile:

**Comment by agnivade** [comment]
> Give me access and I will fix both and more for you 

We are hiring :wink:

**Comment by agnivade** [comment]
So there's already a PR for this https://github.com/mattermost/mattermost-server/pull/14808. I am not sure if we should go ahead with this without giving the other contributor a chance to fix the suggestions. I will ping on the other PR and wait for some time. If we don't get a reply, then we can go ahead with this.

**Comment by rvillablanca** [comment]
> > Give me access and I will fix both and more for you
> 
> We are hiring

Not in my country :chile: unfortunately, also I applied in the past without success :sweat:

**Comment by rvillablanca** [comment]
> So there's already a PR for this #14808. I am not sure if we should go ahead with this without giving the other contributor a chance to fix the suggestions. I will ping on the other PR and wait for some time. If we don't get a reply, then we can go ahead with this.

Sorry about that I didn't see it, giving priority to him is ok :+1:

**Comment by agnivade** [comment]
@rvillablanca - can you sync with master and fix the conflicts? This is now ready to go.

**Comment by rvillablanca** [comment]
@agnivade PR updated

**Comment by rvillablanca** [comment]
Conflicts resolved

**Comment by agnivade** [comment]
This needs EE changes again.

**Pull request closed without merging**
