### PR TITLE
[MM-45769] Properly initialize the request.Context for imports and tests

### PR DESCRIPTION
**Pull request by noxer**
#### Summary
Some imports and tests just initialize an empty context, causing nil pointer dereferences is the server. This PR initializes them.
Thanks to @josephbaylon for reporting this issue.

#### Ticket Link
[MM-45769](https://mattermost.atlassian.net/browse/MM-45769)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
Thanks for jumping into this @noxer !

**Review by agarciamontoro — APPROVED** [review]
Still wrapping my head around how this works, but code looks good! Thanks, @noxer :)

**Comment by noxer** [comment]
> Still wrapping my head around how this works, but code looks good! Thanks, @noxer :)

Do you have any questions? I'll gladly answer them.

**Comment by agarciamontoro** [comment]
@noxer, I still don't, but I will definitely send questions your way as soon as they come up :)

**Pull request merged**
