### PR TITLE
fix mem leak in hubConnectionIndex

### PR DESCRIPTION
**Pull request by byigorv**
#### Summary

We still hold pointer of the last element when WebConn is removed. https://go101.org/article/container.html#slice-manipulations:~:text=Delete%20one%20slice%20element

#### Ticket Link

Fixed https://github.com/mattermost/mattermost-server/issues/22351

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Thanks, indeed good catch! However, I don't believe this is the cause for the massive memory spikes in https://github.com/mattermost/mattermost-server/issues/22351. The memory leak here should get amortized as we keep removing and adding connections to the slice. Nevertheless, this is a leak no doubt. I will take a deeper look tomorrow.

**Comment by byigorv** [comment]
I'll try to explain. If WebConn is active we populate WebConn.deadQueue with WebSocketEvent. When user disconnects we set WebConn.active to false and send events to WebConn.send but don't read it. One WebConn can accumulate 384 WebSocketEvent in total. Yes, you're right, the leak has limit because we add and remove WebConn from slice, but this limit might be too big if you have a lot of users.

**Review by agnivade — APPROVED** [review]
Thanks!

**Comment by agnivade** [comment]
Blocked until monorepo is done.

**Comment by byigorv** [comment]
Done!

**Pull request merged**
