### PR TITLE
MM-34983: Remove check for number of data sources

### PR DESCRIPTION
**Pull request by agnivade**
In case of Aurora databases, a single endpoint
might load balance between multiple replicas.
In that case, this check is incorrect. Therefore,
we remove it

https://mattermost.atlassian.net/browse/MM-34983

### CODE REVIEW

**Comment by agnivade** [comment]
@amyblais - This would be good to cherry-pick to 5.35.

**Review by streamer45 — APPROVED** [review]

**Comment by amyblais** [comment]
@nronas v5.35 will be based on Cloud April 21st release which is coming on Wednesday, please help prioritize review.

**Review by nronas — APPROVED** [review]
LGTM

**Comment by agnivade** [comment]
Oh the branch isn't cut yet.

**Pull request merged**
