### PR TITLE
Include dejavu in docker compose

### PR DESCRIPTION
**Pull request by ethervoid**
#### Summary

Proposal to add [dejavu](https://github.com/appbaseio/dejavu), an Elasticsearch UI, to our docker-compose as an optional tool. So it's configured but you can run it if needed

It's a proposal because when you need to check or edit the ES data or indexes is painful so this tool helps a lot in that task

### CODE REVIEW

**Comment by ethervoid** [comment]
@agnivade in this case of you do `make run-server` dejavu is not launched you only get dejavu downloaded of your do either `docker-compose run -d dejavu` or `docker-compose up`. So this change shouldn't increase the size or download

**Comment by agnivade** [comment]
Ah okay, so `docker-compose run --rm start_dependencies` appropriately checks that dejavu is not dependant on start_dependencies and thereby does not download it ? Nice.

I thought that it would download it, but won't start since it's not part of the dependencies.

**Comment by ethervoid** [comment]
Yes that's the idea, I have to double check but given that dejavu is not part of `start_dependecies` should be downloaded or started

**Comment by agnivade** [comment]
Ah okay, so it's not confirmed. Might be good to do it sometime. So that we know exactly what happens. Not blocking this PR of course. :)

**Comment by ethervoid** [comment]
As you can see here:
```
$ docker-compose run --rm start_dependencies
Starting mattermost-minio    ... done
Starting mattermost-openldap ... 
Starting mattermost-openldap      ... done
Starting mattermost-elasticsearch ... done
Starting mattermost-postgres      ... done
Waiting for postgres to listen on 5432...
Waiting for mysql to listen on 3306...
Waiting for minio to listen on 9000...
Waiting for inbucket to listen on 10080...
Waiting for openldap to listen on 389...
Waiting for elasticsearch to listen on 9200...
```

Calling `docker-compose -rm start_dependencies` is not downlading the dejavu image or bringin the container up

But when you call `docker-compose up -d dejavu`:
```
$ docker-compose up -d dejavu                       
Pulling dejavu (appbaseio/dejavu:3.4.2)...
3.4.2: Pulling from appbaseio/dejavu
4fe2ade4980c: Pull complete
c245f6a8ecc5: Pull complete
82bdc9503d50: Pull complete
dab3ac909585: Pull complete
be00a0cee7f1: Pull complete
62ac1b8aad8c: Pull complete
f8ec33ce23c2: Pull complete
644d4a78cdb5: Pull complete
81a5dec482cf: Pull complete
Digest: sha256:8f2f4d45565da53c4235495737fff3921d302955daeb2f53a433c7b0e2044951
Status: Downloaded newer image for appbaseio/dejavu:3.4.2
Creating mattermost-dejavu ... done
```

**Comment by agnivade** [comment]
Awesome, thanks for verifying !

**Comment by ethervoid** [comment]
@lindy65 this is just an addition to the dev infrastructure in the server but just in case I let you know

**Pull request merged**
