### PR TITLE
MM-10640 Set EnableUserCreation to true by default

### PR DESCRIPTION
**Pull request by balasankarc**
Closes: #8813

#### Summary
Set default value of EnableUserCreation to true.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/8813

https://mattermost.atlassian.net/browse/MM-10640

### CODE REVIEW

**Comment by balasankarc** [comment]
I understand https://github.com/mattermost/mattermost-server/blob/master/app/user_test.go#L91 needs to be changed too. Will `NewBool` method be available there?

**Comment by balasankarc** [comment]
@mkraft Any pointers regarding https://github.com/mattermost/mattermost-server/blob/master/app/user_test.go#L91 ? :)

**Comment by balasankarc** [comment]
@hmhealey Actually, this happens for some other settings also. My logic is any setting that is not given a default value - both `bool` and `String` - is affected. `bool` defaults to `false` and `String` defaults to `""`.

A few of them are (I couldn't check the whole file, sorry)

```
EnableIncomingWebhooks
EnableOutgoingWebhooks
EnableConsole
EnableFile
EnableWebhookDebugging
EnableSignUpWithEmail
EnableSignInWithEmail
EnableSignInWithUsername
ShowEmailAddress
ShowFullName
```

As mentioned in the GitLab MR comment, I will ship the upstream `config.json` file so that this doesn't impact GitLab customers and we are not blocked by it. But I guess, this issue is still valid for Mattermost.

**Comment by hmhealey** [comment]
@balasankarc I'll make a ticket to go check it out. Basically any field defined in model/config.go that isn't a pointer may have an incorrect default. Most of them aren't as big a deal as EnableUserCreation, so that'll probably make a few good "first contribution" tickets if we don't get to them

**Comment by balasankarc** [comment]
> so that'll probably make a few good "first contribution" tickets if we fix the important ones ourselves

Indeed. :+1:

**Pull request merged**
