### PR TITLE
MM-49048: do not omit needed wsbroadcast vars

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

It seems that are omitting ContainsSanitizedData, and ContainsSensitiveData variables in WebsocketBroadcast. This created a bug in cluster mode, where we where sending duplicate events to users when normally they would have access to only one of those.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49048

#### Release Note

```release-note
Fixed an issue where duplicate `post_deleted`, and `user_updated` events would get sent to users when in cluster
```

### CODE REVIEW

**Review by oh6hay — APPROVED** [review]

**Review by agnivade — COMMENTED** [review]
Can we add a test please?

**Review by agnivade — APPROVED** [review]
Nicely done!

**Review by noxer — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
