### PR TITLE
Adds focalboard v0.6.7 as a prepackaged plugin

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
Adds focalboard as a prepackaged plugin. The name of the plugin is different because of its source code existing within the `focalboard` repository.

#### Release Note

```release-note
Added focalboard v0.6.7 as a prepackaged plugin.
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
I love the single-word plugin names. I think we'll do the same soonish when we rebrand Incident Collaboration!

**Review by jespino — APPROVED** [review]

**Comment by amyblais** [comment]
5.36 branch isn't cut yet, I'll let you know once it is.

**Comment by mgdelacroix** [comment]
We need this on the next cloud release as well, so can I directly cherry-pick to the `cloud` branch?

**Comment by mgdelacroix** [comment]
@amyblais ^

**Comment by amyblais** [comment]
@mgdelacroix ``release-5.36`` branch is cut so this can be cherry-picked. 

 > We need this on the next cloud release as well, so can I directly cherry-pick to the cloud branch?

No, we'll merge master into cloud branch next time on Monday next week.

**Comment by mgdelacroix** [comment]
Thanks @amyblais! Will cherry-pick to `5.36` then

**Pull request merged**
