### PR TITLE
Cherrypick for MM-21378

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Cherry-pick for MM-21378 on 5.19

### CODE REVIEW

**Comment by streamer45** [comment]
@saturninoabril  Adding you since you did QA for the original PR. Just want to make sure everything around post is behaving normally before merging this.

**Comment by saturninoabril** [comment]
@streamer45 I can't find somewhere where this needs to be back ported to v5.19.  Could you please comment out the reference/discussion in the ticket itself.  Feel free to merge, thanks

**Comment by streamer45** [comment]
> @streamer45 I can't find somewhere where this needs to be back ported to v5.19. Could you please comment out the reference/discussion in the ticket itself. Feel free to merge, thanks

@saturninoabril 

I believe discussion started [here](https://community-daily.mattermost.com/core/pl/5qb5nfwxyfb3fyr6eq8j1g6jxy).

**Pull request merged**
