### PR TITLE
Fix tests for guest accounts count

### PR DESCRIPTION
**Pull request by TheoVitkovskiy**
**Summary**
Fixes the test for guest accounts count.

**Ticket Link**
No ticket, but is related to the already closed [MM-23697](https://mattermost.atlassian.net/browse/MM-23697)

### CODE REVIEW

**Comment by jespino** [comment]
@TheoVitkovskiy Thank you very much, good catch.

**Comment by teresa-novoa** [comment]
@jespino is this PR ready to be merged? Thanks!

**Comment by jespino** [comment]
@teresa-novoa yes, I think so, thanks for the heads up! :)

**Pull request merged**
