### PR TITLE
MM-50746 - Edits to messages persist after cancelling

### PR DESCRIPTION
**Pull request by gitstart**
### Summary
Edits to messages persist after canceling

### Fixes https://github.com/mattermost/mattermost-server/issues/22372

Moved from https://github.com/mattermost/mattermost-webapp/pull/12253

### Demo video
https://www.loom.com/share/330e0189b6a1445a9cb7652401363280

#### Release note
```release-note
Discards edits to messages after canceling
```

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by AshishDhama** [comment]
@gitstart could you please fix the conflicts.

**Comment by hmhealey** [comment]
@gitstart Could you look into that conflict?

**Review by AshishDhama — DISMISSED** [review]

**Comment by collinewait** [comment]
@M-ZubairAhmed The test ID has been added after merging https://github.com/mattermost/mattermost-test-management/pull/83

**Review by AshishDhama — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected and [e2e](https://automation-dashboard.vercel.app/cycle/324817) passed

**Pull request merged**
