### PR TITLE
[PLT-6712/PLT-7182] /remove and /kick [username] slash command: Remove a member from the channel

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
/remove [username] slash command: Remove a member from the channel

also implement /kick slash command

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/PLT-6712 and https://mattermost.atlassian.net/browse/PLT-7182
GitHub: https://github.com/mattermost/platform/issues/6557 and https://github.com/mattermost/platform/issues/6975

#### Checklist
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by cpanato** [comment]
@jasonblais ready for your test :)

**Comment by jasonblais** [comment]
Awesome, have asked @lindalumitchell to help with testing it out.

**Comment by jasonblais** [comment]
Hey @cpanato, we were busy with the 4.1 release but will test this PR soon. Big thanks for the contribution!

**Comment by cpanato** [comment]
@jasonblais no problem :)

**Comment by lindalumitchell** [comment]
Thanks @cpanato and @jasonblais! Tested both slash commands, and I have a couple questions:

1. What is the expected behavior if I /remove or /kick a username that is on the server but not in that channel? Currently it shows the system message `[username] was removed from the channel` even though they weren't in the channel to begin with
2. Is it expected / okay that the member icon count updates immediately after user(s) removed, but the drop-down member list continues to show the removed members until after refresh?
3. It looks like trying to use the command with multiple users, both with and without the @-sign, only removes the first user listed. The tickets say it should work with multiple users; is that still the case? And I wonder what would happen with `/remove [existing-username]` followed by additional text / non-existent username or vice-versa, `/remove [non-existent username]` followed by an existing username?
4. Both commands allowed a non-admin user to remove a member from private channel, with `Policy > Enable managing of private channel members for:` set to `Team and System Admins`, but the tickets specified that an error should be displayed and the members should not be removed

**Further testing notes; the following all passed:**

Remove one user:
- Using /remove or /kick
- With and without at-sign preceding username, and using at-sign prompts user autocomplete, which worked as expected
- In public and private channels
- No issues found with similar usernames with punctuation, both when using autocomplete on the user and just typing out the username (e.g. `linda` `linda-test` `linda.test`)
- System message displayed as expected with successful removal, including the removed username
- Ephemeral error message displayed as expected in DMs and GMs, and member not removed from channel
- Ephemeral error message displayed as expected trying to remove a username not found on the server
- Removal worked as expected with attachment on the post

**Comment by jasonblais** [comment]
Thanks @lindalumitchell! This is fantastic, great work.

For your questions:
1. If they don't belong to the channel, we should post an ephemeral message `[username] is not a member of this channel.` @cpanato can you help with that?
2. The member list should update (similar to when the user is removed via **Manage Members**). @cpanato can you help with that?
3. Ah yes. We discussed with Carlos and decided it was simpler if only one user is removed at a time. (to handle cases like one user being a member of the channel but another member not). I updated the ticket. For this case though, @cpanato, propose we're consistent with `/join` and `/open` commands and display an error message `We couldn't find the user` if you try to apply the command to multiple users and/or have text that's not part of the username.
4. @cpanato Please help take a look? It should work similar to the `/purpose` and `/header` commands.

**Comment by cpanato** [comment]
@jasonblais @lindalumitchell sorry for the delay. I will update the PR with your findings! thanks!!

**Comment by jasonblais** [comment]
Thanks @cpanato! 

Just a heads up that Mattermost will be separating the `/platform` repo into two repositories on September 6th:
 - a new repository for webapp client code, hosted at github.com/mattermost/mattermost-webapp
 - existing repository (`/platform`) renamed to `/mattermost-server`, containing the server code.

Open PRs on September 6th may need to re-submit their pull request after the separation. For instance, PRs changing the UI would need to be re-submitted to the new `mattermost-webapp` repository.

More details here: https://forum.mattermost.org/t/mattermost-separating-platform-into-two-repositories-on-september-6th/3708/3

**Comment by crspeller** [comment]
Please open a new PR when changes are complete.

**Pull request closed without merging**
