### PR TITLE
[MM-51089] Fix sorting value of category in CreateSidebarCategoryForTeamForUser

### PR DESCRIPTION
**Pull request by tanmaydatta**
#### Summary

This PR is for https://github.com/mattermost/mattermost-server/issues/22445
Sorting attribute was being ignored while creating category.
This PR makes a change to start using that attribute.
Updated the unit test and added screen recording of testing API with postman

https://user-images.githubusercontent.com/5559347/223619971-8244bccf-3ed0-42b5-93f9-86c159e9a045.mov

#### Ticket Link

JIRA: https://mattermost.atlassian.net/browse/MM-51089
#### Release Note

```release-note
Fix sorting value of category in CreateSidebarCategoryForTeamForUser
```

### CODE REVIEW

**Comment by tanmaydatta** [comment]
Hi @hmhealey  @M-ZubairAhmed 
It would be great if you could help review this PR :-)
Also, who should I reach out for other PRs, I see reviewer is assigned and it has been more than a week for one of them.
https://github.com/mattermost/mattermost-server/pull/22484
https://github.com/mattermost/mattermost-webapp/pull/12371
Thanks

**Comment by hmhealey** [comment]
Sorry for the delay on reviewing these. Stuff around here has been a bit hectic lately since we're in the middle of a big migration to turn this repo into a monorepo by moving our web app into it.

As for that other PR, I'm glad to see that Amy added reviewers to that other one since I'm not sure why those weren't assigned automatically. The web app part of it will actually have to be moved over to the monorepo once that's done, but we can still review it as-is for the time being.

**Review by hmhealey — DISMISSED** [review]
This looks good to me! I tried to remember if there was a reason that we didn't let users specify the `Sorting` field when a category is first created, but I think it was just an oversight at the time

**Review by BenCookie95 — APPROVED** [review]

**Comment by tanmaydatta** [comment]
Hi @hmhealey 
I will make these changes over the weekend
Thanks

**Comment by tanmaydatta** [comment]
Actually i successfully rebased this branch
there should be no conflicts now @hmhealey

**Comment by furqanmlk** [comment]
@BenCookie95, Can please approve the workflow so that I can create the test cloud server and e2e

**Review by furqanmlk — APPROVED** [review]
Working as expected with these steps:
1. Run API's with the following URL
**GET**, `URL/api/v4/users{user id}/teams/{team id}/channel/category`
`{
  "user_id": "nsansfo7ef84pqonfn9js8spxc",
  "team_id": "xm8knofbdigrupz4o86m64t8ho",
  "display_name": "testing123",
  "type": "custom",
  "sorting": "manual"
}
`
`**POST**`, `URL/api/v4/users{user id}/teams/{team id}/channel/category`

**Before**
image

**After**
image

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks again for the PR, @tanmaydatta! This'll be included in Mattermost 8.0

**Pull request merged**
