### PR TITLE
MM-36085: Split out System/Team Schemes from license feature checks.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

* Removes the restriction on role permissions that can be patched by unlicensed instances.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-36085

#### Related Pull Requests

- https://github.com/mattermost/mattermost-webapp/pull/8211

#### Release Note

```release-note
Adds the ability for Team Edition to edit role permissions.
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]
LGTM

**Comment by marianunez** [comment]
New packaging release may be postponed past v5.37, adding `Do not merge` label to hold off merge for now. See https://github.com/mattermost/mattermost-webapp/pull/8211#issuecomment-859174074

**Review by furqanmlk — COMMENTED** [review]
TE or E0 should have access to System Schemes ✅ 

Team Scheme Permission is not visible in E10 license 🔴 

e10 TS

**Comment by mkraft** [comment]
> TE or E0 should have access to System Schemes ✅
> 
> Team Scheme Permission is not visible in E10 license 🔴
> 
> e10 TS

@furqanmlk Are you using a license for which `CustomPermissionsSchemes` is `true` or `false`?

**Review by furqanmlk — APPROVED** [review]
Verified following test cases

```
1. E0/TE -->  Should have only System Scheme Permission

1. E10  --> Should have only Team Scheme Permission, no System Scheme Permission

1. Professional  & Enterprise -> Should have both System and Team Scheme Permission

1. E20 --> Should have both System and Team Scheme Permission

```

**Pull request merged**
