### PR TITLE
MM-22340: Fixing flaky tests around Team name validation

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
There was a low chance of having a Team with an invalid name generated with
`model.NewId` without any prefix. For example a Team name starting with `api`
is going to fail.

#### Ticket Link
[MM-22340](https://mattermost.atlassian.net/browse/MM-22340)

### CODE REVIEW

**Comment by jespino** [comment]
@lindy65 I added you here because the policy, but there is a flaky tests, I don't think is anything that you can check here.

**Comment by wiggin77** [comment]
> I am wondering if it makes sense to also update other similar cases to avoid more related problems in the future.
If all those instances need to be touched, maybe a test helper for generating names would be best.  It can check against all the reserved words, etc, for all types.

**Comment by jespino** [comment]
Yes, probably makes sense, other option is to be more specific of what is a acceptable name, for example, now we are considering anything starting with `api` as a invalid name for a team, maybe it should be exclty `api` instead of "starting with" `api`.

**Comment by jespino** [comment]
@streamer45 good point, I'll check that.

**Comment by jespino** [comment]
@streamer45 changed everywhere

**Pull request merged**
