### PR TITLE
Add Focalboard to known plugin telemetry

### PR DESCRIPTION
**Pull request by chenilim**
#### Summary
Add Focalboard to the list of known plugins to enable telemetry.

```release-note
NONE
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Comment by amyblais** [comment]
@cwarnermm This one may need a telemetry doc update for v5.38.

**Comment by justinegeffen** [comment]
@amyblais, I'll take this one - but from what I understand specific plugins aren't referenced in the telemetry docs right now. @chenilim, will there be a requirement for a Focalboard section in the telemetry docs (similar to: https://docs.mattermost.com/manage/telemetry.html?highlight=telemetry#incident-collaboration-telemetry)? If so, let me know. Thanks.

**Comment by justinegeffen** [comment]
Not that I'm aware of. The Boards telemetry docs section has been addedin but afaik this PR didn't require specific documentation.

**Pull request merged**
