### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-server_master/) for mattermost-languages-shipped/mattermost-server.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by metanerd — APPROVED** [review]

**Comment by amyblais** [comment]
@metanerd Will this and the webapp PR be cherry picked to the cloud branch?

**Comment by metanerd** [comment]
@amyblais I lost track of the weeks. Is this a fast forward to the cloud branch week?

**Comment by amyblais** [comment]
@metanerd No, we have a Cloud release this Wednesday, and the v5.37 release branch will be based off that Cloud release.

**Comment by metanerd** [comment]
OK, I am going to cherry-pick then. Thank you!

**Pull request merged**
