### PR TITLE
MM-17006: An http 404 response code is returned when deleting a non existent plugin

### LINKED ISSUE #11627: API: `DELETE /plugins/{plugin_id}` responds with a 400 when the plugin doesn't exist.
#### Summary
`DELETE /plugins/{plugin_id}` responds with a 400 when the plugin doesn't exist.

#### Steps to reproduce
Issue a request against the API using either `DELETE /plugins/{plugin_id}` or by using `AdminClient.RemovePlugin(pluginId)` in which the plugin doesn't exist.

#### Expected behavior
A response code of 409 with appropriate body data to assist the application and/or developer with locating the issue. The API docs also need updated to reflect this change.

409 seems like the best match to use according to the RFC 7231 document:
```
The 409 (Conflict) status code indicates that the request could not
be completed due to a conflict with the current state of the target
resource.  This code is used in situations where the user might be
able to resolve the conflict and resubmit the request.  The server
SHOULD generate a payload that includes enough information for a user
to recognize the source of the conflict.
```

#### Observed behavior (that appears unintentional) 
A response of 400 is seen.

### PR DESCRIPTION
**Pull request by rvillablanca**
This should resolve #11627 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-17006

#### Details

The 404 response code is returned in the these cases

* Deleting a non existent plugin
* Enabling a non existent plugin
* Disabling a non existent plugin
* Getting status of a non existent plugin

### CODE REVIEW

**Comment by crspeller** [comment]
@rvillablanca I don't think that's what 409 means. It's about conflict. Here the plugin just doesn't exist, there is not conflict. Going to comment on the bug report.

**Comment by rvillablanca** [comment]
You are right @crspeller. That's what thought so I will close this PR.

**Comment by hanzei** [comment]
@rvillablanca Would you be open on making sure that _all_ plugin API endpoints return 404 for a non existing plugin?

**Comment by rvillablanca** [comment]
Sure @hanzei

**Comment by rvillablanca** [comment]
@hanzei I have verified the Plugin API and when a plugin does not exist an error with the key `app.plugin.not_installed.app_error` is returned. That key is only used in four places:

* Deleting a non existent plugin
* Enabling a non existent plugin
* Disabling a non existent plugin
* Getting status of a non existent plugin

Not sure if there is another way to look for more cases :thinking:

**Comment by hanzei** [comment]
Thanks for investigating :+1:

**Comment by hanzei** [comment]
@rvillablanca Some tests are failing (https://build.mattermost.com/blue/organizations/jenkins/mp%2Fmattermost-server-pr-new/detail/PR-11631/3/tests)  Let me know if you need help resolving them.

**Comment by rvillablanca** [comment]
I fixed the corresponding test @hanzei

**Comment by hanzei** [comment]
@rvillablanca Would you we open on updating the endpoint documentation in https://github.com/mattermost/mattermost-api-reference?

**Comment by rvillablanca** [comment]
Sure @hanzai

**Comment by hanzei** [comment]
Thanks @rvillablanca. Let me know if you have any questions.

**Comment by hanzei** [comment]
API docs are merged. Removing the label.

**Pull request merged**
