### PR TITLE
MM-38093: updates notifications copy on CRT replies

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Updates texts of push and email notifications when the user has CRT "on"
and the post is a reply to a thread.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-38093

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hanzei** [comment]
I don't think I'm the right one to review complex CRT logic. Was there a specific reason why you asked me for a review?

**Comment by koox00** [comment]
@hanzei sorry, I just followed GH suggestions, no worries

**Review by hmhealey — APPROVED** [review]

**Review by ashishbhate — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00 
Tested, looks good to merge.
- Verified texts for push, desktop and email thread reply notifications when the user has CRT "on" is updated.

**Pull request merged**
