### PR TITLE
[MM-46694] A/B Test: welcome post

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
- Adds a new post type for the welcome message
- Adds A/B Test for the welcome message that is sent only to the very first team.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46122

#### Related Pull Requests
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/11041)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
Great work @JulienTant :shipit:

**Review by julmondragon — APPROVED** [review]
LGTM!

**Comment by stevemudie** [comment]
@JulienTant I toggled the split but only ever encountered the variation. 🤔 This included new users after I'd toggled it back to off (it was off to begin with yet showed me the slash commands anyway?).

On a related note, I'm not sure who I should address this too but my impression as a user was to just click the buttons. Nothing about the design guided me to actually type out the slash command. In the design on the ticket it mention that they are slash commands you can type but not so in the Spinwick. 🤷🏻‍♂️ 

Screenshot 2022-09-29 at 9 47 54 AM

**Comment by marianunez** [comment]
@JulienTant @stevemudie can we prioritize this PR so we can cherry pick into the upcoming cloud release?

**Review by stevemudie — APPROVED** [review]
@JulienTant 
working

**Comment by JulienTant** [comment]
@amyblais can we cherry-pick this (and the webapp one) for the next cloud release?

**Pull request merged**
