### PR TITLE
[MM-46692] Channel group member count

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
Adding 2 new url params in order to get ChannelMemberCount for a group.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46692

#### Release Note

```release-note
Added 2 new urls parameters to the GET /api/v4/groups endpoint in order to get ChannelMemberCount for a group
```

### CODE REVIEW

**Review by plant99 — APPROVED** [review]

**Review by mkraft — APPROVED** [review]

**Comment by furqanmlk** [comment]
Hi @BenCookie95 can you please fix conflict

**Comment by furqanmlk** [comment]
Hi @BenCookie95, Can you please fix conflict?

**Review by furqanmlk — APPROVED** [review]
Working fine

**Pull request merged**
