### PR TITLE
MM-49870 - rename default town square channel to general

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR is intended to rename the default channel Town Square to General.
* Note that it is intended only to rename the display name and not the channel id

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49870

#### Release Note
```release-note
Rename the default channel display name from "Town Square" to "General"
```

### CODE REVIEW

**Comment by pvev** [comment]
@stevemudie we need to coordinate how are we going to merge this one to prevent any disruption or conflicts with the QA team. Who else do you think should be involve during this coordination process?

**Comment by stevemudie** [comment]
@pvev I'll reach out to the QA team to make sure we're set and ready for the change. As far as I know we are ready but I'll run it by them to be sure.

**Comment by stevemudie** [comment]
@pvev When you get a chance can you take a look at the E2E results? It looks like here were a handful of errors that had to do with the changes.

https://automation-dashboard.vercel.app/cycle/326535

On a related note, you may want to check out the recent [updates to the automation dashboard](https://community.mattermost.com/core/pl/buhfeypqc7nsbb5jhye1y84x1e) before diving into the results.

Also, here are the [master results](https://automation-dashboard.vercel.app/cycles/017b5584-346e-475f-aebf-026e20bc4c91) you can compare to that ran just prior to the E2E here last night.

**Comment by pvev** [comment]
> @pvev When you get a chance can you take a look at the E2E results? It looks like here were a handful of errors that had to do with the changes.
> 
> https://automation-dashboard.vercel.app/cycle/326535
> 
> On a related note, you may want to check out the recent [updates to the automation dashboard](https://community.mattermost.com/core/pl/buhfeypqc7nsbb5jhye1y84x1e) before diving into the results.
> 
> Also, here are the [master results](https://automation-dashboard.vercel.app/cycles/017b5584-346e-475f-aebf-026e20bc4c91) you can compare to that ran just prior to the E2E here last night.

ok @stevemudie sure! thanks!

**Review by JulienTant — APPROVED** [review]
I only skimmed through the e2e tests, but the rest looks good to me and works as expected!

**Review by stevemudie — APPROVED** [review]
The E2E tests look good and it's all set from my end. Thanks for your attention to this @pvev!

**Comment by pvev** [comment]
> @pvev I'll reach out to the QA team to make sure we're set and ready for the change. As far as I know we are ready but I'll run it by them to be sure.

@stevemudie this one is ready to be merged. Double confirm with you before moving forward that the QA team is ready to handle this in the rainforest scenario.

**Comment by esethna** [comment]
Given we won't have capacity to support or test for this moving forward we're going to close it for now.

**Pull request closed without merging**
