### PR TITLE
Fix for when the 'migrate' command drops the custom default language.…

### PR DESCRIPTION
**Pull request by haalcala**
Fix for when the 'migrate' command drops the custom default language. (Using suggested fix)

P.S. No ticket for this

### CODE REVIEW

**Review by isacikgoz — COMMENTED** [review]
Hey @haalcala, thanks for the contribution!! Could you explain why we need to call `utils.TranslationsPreInit()` before this command? I couldn't understand the reason behinds this change.

**Comment by haalcala** [comment]
> Hey @haalcala, thanks for the contribution!! Could you explain why we need to call `utils.TranslationsPreInit()` before this command? I couldn't understand the reason behinds this change.

Hi, this was the suggested fix, instead of the one I previously provided here https://github.com/mattermost/mattermost-server/pull/15617

**Review by mgdelacroix — APPROVED** [review]
Apologies for the late review @haalcala, LGTM! :+1: 

Thanks for the contribution!

**Review by isacikgoz — APPROVED** [review]
Thanks @haalcala 👍

**Pull request merged**
