### PR TITLE
Prepackage board version to 0.8.2

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update prepackaged boards version to 0.8.2

#### Ticket
https://github.com/mattermost/focalboard/issues/891

#### Release Note
```release-note
Update prepackaged boards version to 0.8.2
```

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Review by chenilim — APPROVED** [review]
LGTM!

**Comment by cpanato** [comment]
i will merge this, the upload steps failed because this PR is from a fork and the keys are not injected because it touches some blocklist files.

But the jobs are not required

**Comment by sbishel** [comment]
Thanks @cpanato

**Pull request merged**
