### PR TITLE
Fix typo in sqlstore migrations guide.

### PR DESCRIPTION
**Pull request by Potherca**
#### Summary

Fix `baord` typo in [server/boards/services/store/sqlstore/migrations/README.md](https://github.com/mattermost/mattermost-server/blob/0cb3a406da7a339cc47bb72e32106b24e13c2a9a/server/boards/services/store/sqlstore/migrations/README.md?plain=1#L10)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Neat, thanks!

**Review by mgdelacroix — APPROVED** [review]
Thanks for the fix @Potherca! :sparkles:

**Comment by mgdelacroix** [comment]
@Potherca please take a look at [this message](https://github.com/mattermost/mattermost-server/pull/23481#issuecomment-1559257462) and sign the CLA to unblock the CI :)

**Comment by Potherca** [comment]
I've filled in the form earlier. Maybe I did something wrong?

**Pull request merged**
