### PR TITLE
Added index on SidebarCategories table

### PR DESCRIPTION
**Pull request by agnivade**
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
sidebar_cat

Frankly, the load-test doesn't show any improvement, but I have a feeling it's due to the data spread. The load-test could only generate like 7k rows, and our community instance has around 21k rows. I verified that the query in MySQL does indeed use the index correctly.

Speaking strictly from a data centric view, I accept that adding this index doesn't really pass the bar, but I do note that the table doesn't have any index whatsoever other than the PK. And in community, the max time for that query is around 608ms in the past 12 hours. My load-test was only able to stress it to 41ms. So we do have a room for lot of improvement.

That said, if you feel this is not necessary, feel free to let me know.

Full dashboard here: http://3.89.26.3:3000/?orgId=1&var-server=agent-0:4000&var-server=app-0:8067&var-server=app-0:9100&var-server=app-1:8067&var-server=app-1:9100&from=1650534312560&to=1650545202883

**Review by 15279797616 — COMMENTED** [review]
52232a918b364fd80cd29ab9c515a4bbc70b1c54

**Comment by agnivade** [comment]
Gentle ping @streamer45

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by agnivade** [comment]
Going to hold on to this until 7.0 feature freeze is past. Don't want to pile up another schema change.

**Comment by agnivade** [comment]
@amyblais - Just to confirm, merging to master now will end up in 7.1 correct?

**Comment by amyblais** [comment]
> @amyblais - Just to confirm, merging to master now will end up in 7.1 correct?

Correct.

**Pull request merged**
