### PR TITLE
13102 all channel members notify props for channel cache

### PR DESCRIPTION
**Pull request by arjunagl**
#### Summary
Migrate allChannelMembersNotifyPropsForChannelCache cache from store/sqlstore/channel_store.go to the new store/localcachelayer

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/13102

#### Release Note
NONE

### CODE REVIEW

**Comment by agnivade** [comment]
Is the PR still in draft or ready to be reviewed?

**Comment by arjunagl** [comment]
> Is the PR still in draft or ready to be reviewed?

still in draft, Just want to make sure someone goes through this and verifies its heading down the correct path.

**Comment by agnivade** [comment]
Yes, that's the way to do it. Please test this out very thoroughly and carefully because caches are a very sensitive area.

**Comment by isacikgoz** [comment]
Hi @arjunagl, big thanks for your contribution! There hasn't been recent activity on this PR so I've marked it as inactive. Following our [inactive contribution process](https://developers.mattermost.com/contribute/getting-started/inactive-contributions/), the PR is now closed due to 30 days or more of inactivity.

However, if you're still interested working on the changes, let us know! Note that we [merged multiple repositories into one monorepo](https://github.com/mattermost/mattermost-server/issues/22420), which may require you to resubmit the changes. 

If you have any questions, don't hesitate to let us know, we're happy to help.

**Pull request closed without merging**
