### PR TITLE
Allow default team to be configured

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Adds a config value  "DefaultTeamName" that allows to config the name of a default team:
```
"TeamSettings": {
  "DefaultTeamName": ""
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] Added API documentation (required for all new APIs)
- [ ] All new/modified APIs include changes to the drivers
- [ ] Has enterprise changes (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
- [ ] Touches critical sections of the codebase (auth, upgrade, etc.)

CC @dmeza

### CODE REVIEW

**Comment by esethna** [comment]
@dmeza can you help me understand what this config setting does?

**Comment by esethna** [comment]
@dmeza based on my understanding from the webapp PR, the default team is used to bypass the team selection page for users who create an account but do not yet belong to any team (ie, they did not use the team invite link to create the account)? Can you help me understand:

1. Why is hiding the "Leave Team" option necessary?
2. Are there any other changes to signin and account creation flow, other than skipping the team selection page?
3. What are the use cases that make these changes necessary?

**Comment by csduarte** [comment]
Hi @esethna,

All your questions are covered by a standard use case: the enterprise. Users don't ever get invited or choose to join/leave teams. They are assigned and it's automated. And in our setup, they are mostly assigned to one team. And if they have two, there is a primary one to use. So leaving the team can't be an option, they would be stranded with no teams to select and have to go to the help desk (inefficient & costly to company). Since the teams are pre-selected, team selection doesn't make sense. With the team selection screens, there is unneeded friction and confusion for first time application users.

**Comment by dmeza** [comment]
@esethna rebased to latest from master. Also the `webapp` changes: https://github.com/mattermost/mattermost-webapp/pull/334

**Comment by esethna** [comment]
Okay thanks for the explaination @csduarte, makes sense. I will do the testing on the webapp PR, moving this one to dev review.

**Pull request merged**
