### PR TITLE
revert zoom plugin to previous release v1.1.2 for 5.20

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
The zoom plugin needs to be reverted to the previous version for this bundle.

#### Ticket Link
n/a

### CODE REVIEW

**Comment by DHaussermann** [comment]
Not sure why this won;t build but it's quite low risk. I could verify this post-merge.

@levb or possibly @lieut-data, as there won't be pre-packaged plugins anymore with 5.20, Do we have a process to roll this back from the marketplace to stop people from updating to this version until the desktop mapping issue is resolved?

**Comment by lieut-data** [comment]
The build is failing because:
```
cp: cannot stat 'tmpprepackaged/mattermost-plugin-zoom-v1.1.2-osx-amd64.tar.gz': No such file or directory
cp: cannot stat 'tmpprepackaged/mattermost-plugin-zoom-v1.1.2-osx-amd64.tar.gz.sig': No such file or directory
tar: dist/mattermost/prepackaged_plugins/mattermost-plugin-zoom-v1.1.2-osx-amd64.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Contains  in mattermost-plugin-zoom-v1.1.2-osx-amd64.tar.gz but needs dist/plugin-darwin-amd64
make: *** [build/release.mk:81: package] Error 1
```

I think this is because we don't have platform-specific signatures for v1.1.2 like we do for v1.2.0. This is another reason we should ship a v1.3.0 instead and follow the "upgrade" process.

**Comment by DHaussermann** [comment]
Right. Thanks @lieut-data. Sorry for the confusion. I supposed the question is now that plugins are not pre-installed it's not clear to me what the purpose of this code change is if it has no impact on the marketplace. 

@aaronrothschild one other point to make is that for people who already have Zoom 1.2, should there also be a change to the documentation explaining that it is not possible to map a user to a Zoom  from the desktop.

**Comment by lieut-data** [comment]
> I supposed the question is now that plugins are not pre-installed it's not clear to me what the purpose of this code change is if it has no impact on the marketplace.

*Enabled*, pre-packaged plugins will still be pre-installed as of v5.20.0. So any customer that has Zoom enabled today will get the version we ship in v5.20.0 automatically and independently of the marketplace. The only meaningful change in v5.20.0 relative to pre-packaged plugins is that we no longer forcibly install plugins you don't ever enable.

So if we want to "rollback", we definitely need to update this file to modify the version we're shipping. However, it's no longer the case that we can rollback to a previous version -- Zoom 1.2.0 is already live in the marketplace and may already be installed by customers. We need a Zoom 1.3.0 to allow them -- and anyone automatically installing via pre-packaged plugins in v5.20.0 -- to upgrade past this issue.

**Pull request closed without merging**
