### PR TITLE
Move enterprise features under Channels

### PR DESCRIPTION
**Pull request by agnivade**
We move the EE features which are Channels related.

While here, we also move some code under *Server.Start()
from NewServer.

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — COMMENTED** [review]
~~Considering features like ldap, saml would be used by other products, should we keep them the initialization part separated from the channels? I think channels should get those services while initializing the product itself.~~ I realized that I rushed into this comment. Let me re-think this again.

**Comment by agnivade** [comment]
Sure, no worries. I took a look and only separated the ones which I think fall under channels, but kept the ones (metrics, cluster, elasticsearch, licensemanager, notification and cloud) which I think are global under Server.

But you are right that ldap and saml are common login methods used by all products. So I am good with reverting them back. Are you okay with the other choices?

Also note that the initialization phase of products happen much before ldap and saml gets initialized. It happens in step 3 (after config (1) and logging (2).) So during a product initialization phase, they won't have access to ldap or saml. _However_, once the `Start` method is called, all fields should be initalized.

**Comment by isacikgoz** [comment]
Yep, others seems to be in the right place. Let's revert the saml and ldap for now and think a bit more on that. Thanks for the explanation btw, much appreciated!

**Comment by agnivade** [comment]
Done. PTAL.

**Review by isacikgoz — APPROVED** [review]
LGTM, we are getting there 👍

**Comment by amyblais** [comment]
Assigned to @agnivade to cherry-pick to ``cloud``.

**Comment by agnivade** [comment]
This is already there on the cloud branch. I suspect @nickmisasi 's branches may not be synced somehow. The cloud branch locally compiles for me.

**Pull request merged**
