### PR TITLE
[MM-28580] Add multipart support for resumable uploads API endpoint

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR adds support for resumable file uploads using the `multipart/form-data` format which, at this moment, is still the most efficient way to upload a file from a browser.

#### Ticket

https://mattermost.atlassian.net/browse/MM-28580

#### Related PRs

https://github.com/mattermost/mattermost-server/pull/15510

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
Nicely done! 🚀

**Comment by amyblais** [comment]
@streamer45 I'm pushing this from v5.28 as it will probably not make it to today's feature complete. Let me know if this is important for v5.28 and should be re-added,

**Comment by streamer45** [comment]
> @streamer45 I'm pushing this from v5.28 as it will probably not make it to today's feature complete. Let me know if this is important for v5.28 and should be re-added,

@amyblais 
I'd say it's important because it's needed by a greater feature ([MM-26812](https://mattermost.atlassian.net/browse/MM-26812)) which has already been merged. So we either post-pone everything or they really should go in together.

**Comment by amyblais** [comment]
Sounds good,

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by streamer45** [comment]
@lindalumitchell 

This is a small addition on top of https://mattermost.atlassian.net/browse/MM-26812. This as well is covered by a few tests.

**Comment by amyblais** [comment]
@lindalumitchell Kind reminder to review this for v5.28.

**Review by lindalumitchell — APPROVED** [review]

**Pull request merged**
