### PR TITLE
IS-235: Add the gomodtidy check to CI pipeline

### PR DESCRIPTION
**Pull request by agnivade**
#### Ticket Link

https://mattermost.atlassian.net/browse/IS-235

### CODE REVIEW

**Comment by agnivade** [comment]
There seems to be some issue here. CircleCI shows the state of go.mod after a go mod vendor, but Jenkins works fine. These two seem to be in conflict. I think this is why I abandoned my first PR. I will need to look into it.

**Comment by agnivade** [comment]
@metanerd @hanzei - I figured out the cause of this. The core issue is that the output of "go mod tidy" changes if you have the EE repo. And since circleCI runs the test on the TE repo, that's why Jenkins was working fine and CircleCI wasn't.

There is not straightforward way to fix this without having a separate go.mod for the EE repo. Essentially contributors and staff will see different "go mod tidy" outputs and not much can be done about it. It cannot be enforced with CI.

Let me know your thoughts. Thanks.

**Comment by metanerd** [comment]
How about moving the check to EE then?

**Comment by agnivade** [comment]
That can still work. It's fine even if it's late. But the primary problem is that a contributor will always have to manually edit their go.mod file to pass the CI. i.e. CI will validate something else than what they are using.

We need to decide what is more important - stability of go.mod, or the contributor experience. I am equally fine with either choice.

**Comment by metanerd** [comment]
I would go with more convenience for contributors tbh. What about tidying master automatically afterwards? Opinions? Too ugly?

**Comment by agnivade** [comment]
Yeah, it's definitely another layer of magic. I would love to see a clean solution here. We can discuss this more in an appropriate public channel for others to chime in.

**Comment by agnivade** [comment]
Any objections to closing this ? Doesn't look like this PR is much useful anymore.

**Pull request closed without merging**
