### PR TITLE
[MM-18277] Refactor plugin/health_check.go to use structured logging

### PR DESCRIPTION
**Pull request by sdesani**
#### Summary
Refactor "plugin/health_check.go" to use structured logging

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12725

JIRA ticket.
https://mattermost.atlassian.net/browse/MM-18277

### CODE REVIEW

**Comment by sdesani** [comment]
I have now signed the CLA. How do I re-trigger the check for same ? The [doc here](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) shows my username in it.

**Comment by jasonblais** [comment]
@sdesani Can you help with a rebase and this should be good to merge afterwards by @reflog or @mickmister? Big thanks for your contribution!

**Comment by sdesani** [comment]
@jasonblais, not a problem. Just pushed the rebased commit.
cc: @mickmister / @reflog

**Pull request merged**
