### PR TITLE
[PLT-6940] Add webrtc call at channel navbar and make it available on narrow window

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add webrtc call at channel navbar and make it available on narrow window.
'Start Video Call' is only available when user (self) is not busy (no existing call) and the other user is online.

@asaadmahmood please help fix CSS issue on channel header and webrtc. thanks! 

#### Ticket Link
Jira ticket: [PLT-6940](https://mattermost.atlassian.net/browse/PLT-6940)

#### Checklist
- [ ] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
What's needed for PM review? Is it just Asaad reviewing CSS / making tweaks as appropriate?

**Comment by saturninoabril** [comment]
@jasonblais The ticket does not specifically mention some UX items like the following and it might worth checking from PM. Here are possible UX concerns:
- order of `Start Video Call` at navbar. Right now it's on top of the list. 
- `Start Video Call` is only visible when the other user is online. No other indication is included when other user is offline or the one who wants to make a call is busy (that is when there's existing call).

**Comment by jasonblais** [comment]
@asaadmahmood Thoughts on above questions from Saturn?

1) I think in terms of ordering, we can have it as the first item. Those who have video calls enabled are more likely to start a call than edit the header or add favorites (which you might do once)
2) Any thoughts on the list item when the user is offline? I'm wondering if it would have been simpler to just add the header icon given there's enough space in mobile view.

**Comment by asaadmahmood** [comment]
@jasonblais.
1. Yup that makes sense.
2. For mobile devices, we can have it in the dropdown, but if we're talking about larger devices like tablets etc. Then we can add an icon in the DM header. That's what my comment says in the ticket. To add it in the DM header.

**Comment by jasonblais** [comment]
@asaadmahmood Thanks!

1. 👍 
2. Ah I see. I thought this comment meant we shouldn't add it: `Adding another icon in the header especially on tablet/mobile would populate the header even more leaving less space for the title.`

Note that you cannot start WebRTC calls on mobile/tablet devices -- the option will only appear on desktop mobile/tablet view. So maybe we should proceed with the icon then, since the screen will typically be wide enough for it to fit.

**Comment by asaadmahmood** [comment]
Yup @jasonblais makes sense.

**Comment by jasonblais** [comment]
@saturninoabril Is this something you'd be able to help with?

**Comment by saturninoabril** [comment]
@jasonblais Sure. I've updated the PR adding webrtc header icon for tablet.

**Comment by jasonblais** [comment]
@asaadmahmood please help review the CSS/styling?

**Comment by asaadmahmood** [comment]
@jasonblais @saturninoabril I don't see the video call button on the spinmint, and neither locally (after updating the settings, and even after the button is obviously visible on dropbox).

**Comment by saturninoabril** [comment]
Updated:
- show header icon (webrtc__button) at >480px up to 768px 
- show dropdown list (webrtc__option) at 480px and below

Thanks @asaadmahmood for the CSS tricks!

**Comment by jasonblais** [comment]
Thanks all! Just a few questions:

1) @asaadmahmood  Sorry, why this complication?

> show dropdown list (webrtc__option) at 480px and below

Why not just show the icon at all times? As a reminder, WebRTC is not available on iOS/Android devices, only on desktop (including tablet/mobile view)

**Comment by jasonblais** [comment]
Thanks all! Just a few questions:

1) @asaadmahmood  Sorry, why this complication?

> show dropdown list (webrtc__option) at 480px and below

Why not just show the icon at all times? As a reminder, WebRTC is not available on iOS/Android devices, only on desktop (including tablet/mobile view)

2) @asaadmahmood The icon looks a bit thick compared to the other header icons

image

3) @asaadmahmood @saturninoabril Is the icon visible if the person is offline? At the moment it looks like it's not, which could be confusing. On wider desktop view, there's an "active" and "inactive" state on the webrtc icon depending on if the person is offline or not.

**Comment by asaadmahmood** [comment]
1. To save header space, and I would assume that this was probably because of users who are using mattermost on desktop but have it shrunk. In that case, I think this would easily suffice that requirement.
2. Yup, that's just how the icon is on desktop, I can have a look and see if I can adjust it.
3. I don't think there's currently a different icon, probably just a different state which reduces the opacity of the icon if a user is offline, we can have the same thing here, until we upgrade and add an offline icon as well.

**Comment by asaadmahmood** [comment]
@jasonblais ^

**Comment by jasonblais** [comment]
@asaadmahmood 

1. But is this needed? I see lots of space for the video header icon in desktop mobile view. It's confusing why for some DMs you have the icon but for others you don't.
2. Maybe we can adjust it as it looks inconsistent from the others
3. Let's be consistent with the desktop view?

**Comment by jasonblais** [comment]
Given there are a few unanswered UI questions and this PR isn't critical, pushing to v4.3

**Comment by jasonblais** [comment]
@asaadmahmood Will work on a few UI tweaks.

Given our split of the platform repo, @saturninoabril you might need to resubmit this PR to the webapp repo later in the week.

**Comment by saturninoabril** [comment]
@jasonblais sure, no problem

**Comment by crspeller** [comment]
This PR needs to be re-submitted to the new separated webapp and server repositories.

**Pull request closed without merging**
