### PR TITLE
MM-41184: Remove /config/migrate API endpoint

### PR DESCRIPTION
**Pull request by agnivade**
This was introduced to let the functionality happen
via mmctl, but it does not differentiate between
sysadmins vs people having physical access to machines.

Therefore, we remove it and only keep the local endpoint
accessible from mmctl --local.

https://mattermost.atlassian.net/browse/MM-41184

```release-note
The api/v4/config/migrate API endpoint has been removed
in favor of the mmctl --local endpoint. API clients
won't be able to access this endpoint without having
physical access to the server.
```

### CODE REVIEW

**Review by srkgupta — APPROVED** [review]
Thanks @agnivade. Changes LGTM.

**Review by isacikgoz — COMMENTED** [review]
Looks good, @agnivade before merging this one shall we also create a companion PR for mmctl to remove `config migrate` command from non-local mode? I think we can just return an error that this command will be used local mode only. And also we may want to update documentation too.

**Comment by agnivade** [comment]
Sure

**Review by isacikgoz — APPROVED** [review]
LGTM 👍

**Comment by srkgupta** [comment]
Hi @amyblais 
Can this be cherry picked to 6.4 release?

**Comment by amyblais** [comment]
Seems to need a manual cherry-pick

**Pull request merged**
