### PR TITLE
[MM-32368] store/post: fix searching for phrases in postgres

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
store/post: fix searching for phrases in postgres

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32368

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @isacikgoz - this is fixed according to test steps in the ticket (spinwick has postgres database and neither elasticsearch nor bleve are enabled) 👍 

Wanted to check with you whether you saw this note on the ticket?
"Triage note: when we fix this, we should add a unit test!"

**Comment by isacikgoz** [comment]
@lindy65 thanks for pointing out :) I added a couple of unit test for this.

**Comment by lindy65** [comment]
Awesome! Thanks @isacikgoz 👍

**Pull request merged**
