### PR TITLE
[MM-28122] Fix error handling in S3FileBackend.FileExists()

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR fixes error handling in `S3FileBackend.FileExists()`.

#### Ticket

https://mattermost.atlassian.net/browse/MM-28122

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Difficult to write a test for this?

**Comment by streamer45** [comment]
> Difficult to write a test for this?

The difficulty is in having `StatObject` return something that's not a `ErrorResponse`.
The minio API states:
>  `ErrorResponse` Is the typed error returned by all API operations.

**Review by agnivade — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
less 🐛

**Comment by streamer45** [comment]
@lindalumitchell 

There's no easy way to test this. It's possibly a very rare edge case which the code change will now properly handle.

**Review by lindalumitchell — APPROVED** [review]
Thanks @streamer45, sounds good to me.

**Pull request merged**
