### PR TITLE
[MM-41993]: fixed counting thread mentions in unread root post

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
the root post got appended to the post list which led to it being counted towards mentions in the thread, which is considered a bug according to the specs.

The second change (`CreateAt` instead of `UpdateAt` in threads_store.go) was done in collaboration with @koox00 

#### Ticket Link
[MM-41993](https://mattermost.atlassian.net/browse/MM-41993)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — COMMENTED** [review]
LGTM 💪 Can you fix the tests as well?

**Comment by michelengelen** [comment]
@koox00 thanks for your time and help ... I actually had to add a new assertion to the test as we were defining a var `reply` and the test script did not like that. I took the chance to just test marking the first reply as unread as well and check if the correct value is returned, so we can be sure that this is not failing anymore. 🙇🏼

**Review by koox00 — APPROVED** [review]

**Comment by ashishbhate** [comment]
>The ThreadStore().GetPosts seems to be called only from count mentions, I don't know the reasoning behind using update_at instead of create_at, do you have any idea @ashishbhate?

I'm not sure. I looked in the git history but I couldn't find anything. 

>Using create_at seemed to me more intuitive and intentional that's why I proposed the change.
>PS: since we exclude posts having a CreateAt less than timestamp when we count mentions. keeping update_at in the query would not affect functionality.

Since it's only being called from the `countThreadMentions` method, I think it's fine to change it. You're that it wont affect functionality.

**Review by ashishbhate — APPROVED** [review]
LGTM!

**Comment by jgilliam17** [comment]
Thanks @michelengelen 
Tested, looks good to merge - pending E2E report
- Verified thread mention is not counted when marking root post with mention as unread on rhs.

**Comment by jgilliam17** [comment]
@michelengelen Can you please take a look at the failure - blocked on running e2es. Thanks 🙂

**Comment by michelengelen** [comment]
@ashishbhate or @koox00 could you have a look why that job is failing? I don't have that much experience with the server repo

**Comment by ashishbhate** [comment]
@michelengelen 

It looks like the i18n tool is trying to re-insert a translation (ent.cloud.subscription.error) that was removed in #19835 

I'm not sure why its trying to do that.

**Comment by jgilliam17** [comment]
Thanks for fixing failed checks and running E2Es @michelengelen , [report](https://automation-dashboard.vercel.app/cycles/053c6aaa-352d-4456-b008-4012548cf7c8) looks good - no PR related failures.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
