### PR TITLE
Convert Public to Private Channels

### PR DESCRIPTION
**Pull request by ruzette**
#### Summary
Converting public channels to private channels

#### Ticket Link
- https://github.com/mattermost/platform/issues/4587

#### Checklist
- [x] All new/modified APIs include changes to the drivers
- [x] Has UI changes
- [x] Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/platform/blob/master/i18n/en.json) and [.../webapp/i18n/en.json](https://github.com/mattermost/platform/tree/master/webapp/i18n/en.json)) updates

### CODE REVIEW

**Comment by jwilander** [comment]
Gave a it read through and overall it looks really good! My only suggestion would be to move as much of the shared code between the v3 and v4 handlers into the app layer as possible so that we don't have to have duplicate code and it's easier to maintain

**Comment by ruzette** [comment]
@jwilander Thanks for that feedback, and you're right -- moving the shared code to the app layers looks more maintainable. 

I'm not sure if anything is missing but this is ready for review. :)

**Comment by jasonblais** [comment]
Thanks @ruzette! Did an initial test pass and overall looks great! It's 90% there 👍 

Just a few minor nits: 

1 - Wondering if you used #4046 as a guide to build the full-screen modal? I think it's actually more like a popup dialog at the moment. We'd be happy to help in constructing the modal if needed

2 - After the modal opens, pressing Enter should perform the "yes, convert to private channel" action. Currently pressing Enter when the modal is open does no action.

3 - After converting a channel to private, it still appears as public for other users
 - Sign into the same instance with two accounts (e.g. userA on Chrome, userB on Firefox) 
 - userA: Create a public channel and add userB to the channel 
 - userA: Convert the channel to private

Observed:
 - userA: Channel converted to private. Channel icon in left-hand sidebar changes from a globe to a lock. The channel is moved under the "Private Channels" list
 - userB: No action except for a system message in the channel. "Convert to Private Channel" option appears in the channel drop-down menu. Only a page refresh properly updates the channel to private

Expected: userB should see the same as userA

4 - "@channel" doesn't trigger a mention to other users in the channel - only triggers an unread
 - Sign into the same instance with two accounts (e.g. userA on Chrome, userB on Firefox) 
 - userB: In Account Settings > Notifications > Words that trigger mentions, make sure **Channel-wide mentions "@channel", "@all"** is selected
 - userA: Create a public channel and add userB to the channel 
 - userA: Convert the channel to private

Observed:
 - userB: Channel is marked as unread, but no mention jewel shown

Expected:
 - userB: Channel is marked as unread with a mention jewel (for the `@channel` mention)

5 - Mobile view: "Convert to Private Channel" option doesn't appear

image

Propose including it below "Rename Channel" to match the desktop view.

I'm a little worried if it will fit the list given it's already quite long -- but we can try and see how it looks.

----

Notes to myself:

6 - We should think about whether we should allow admins control who can convert public channels to private, especially since you can't "undo" the action. This would probably fall into the other [Policy settings](https://docs.mattermost.com/administration/config-settings.html#policy).

^Ruzette: This would be done in a separate PR, but something for the PM team to consider before we ship the feature.

7 - Confirm UI text with Jeff, who might be able to make it more concise

(^any changes can again be done in a separate PR)

**Comment by ruzette** [comment]
Thanks for the comments, @jasonblais! They are really helpful! 

1. For the initial pass, I only used the available classes in the css templates. I can now change it accordingly. Would it be possible to send a screenshot of what #4046 looks like? It looks like an EE implementation, so I may not be able to see it from TE. 

2,3 ,4,5 -- Thanks for these! I'll update these too.

**Comment by jasonblais** [comment]
Hey @ruzette, chatted with a couple of people on 1, and the current pop-up dialog looks good so let's use that instead without a full-screen modal. 

I would just move `Convert [CHANNEL NAME] to a private channel?` into the title instead and we should be good.

image

**Comment by jasonblais** [comment]
Hey @ruzette, 

last time we chatted, it sounded like you just had a couple of things to update? Let us know if we can help with that in any way.

Really excited for this feature! We're close to queueing it for dev review 👍

**Comment by ruzette** [comment]
@jasonblais Thanks for checking up! 

I'm finishing up items 3 and 4. Items 1, 2, 5 and 8 should be completed. 👍

**Comment by jasonblais** [comment]
Awesome, thanks @ruzette! Let us know if you need any help with 3 & 4

**Comment by jasonblais** [comment]
Hey @ruzette, Carlos submitted a PR that should help resolve 3: https://github.com/mattermost/platform/pull/6677

I think the only thing left here was on 4. Let me know if you had any questions on that.

**Comment by ruzette** [comment]
Thanks @jasonblais! I saw that Carlos' PR has been merged so I will update this! :D

**Comment by jwilander** [comment]
Let me know if you need any help with implementation :)

**Comment by jasonblais** [comment]
Hey @ruzette! 

So Linda and I gave this pull request a few test passes and it looks really good. There's just a few corner cases we found. But overall really close, great work.

If any of the items below require a lot of work, just let me know. We can consider alternatives.

1 -  “@channel” that triggers a mention not highlighted in the system message.

Observed:
image

Expected: (@channel highlighted, which triggered a mention)
image

2 - Desktop notification triggered for other users after converting a public channel to private

image

Expected: Desktop notification not sent for system messages.

3 - After clicking "Convert channel to private", 
 a) update the UI text in the dialog that opens.


```
Title: Convert [CHANNEL NAME] to a private channel?

When you convert [CHANNEL NAME] to a private channel:

 - History and membership are preserved
 - Files shared via a public link remain accessible to others
 - New members need be added before they can join the conversation

The change is permanent and cannot be undone. Are you sure you want to convert [CHANNEL NAME] to a private channel?

Buttons: Cancel // Yes, convert
```

 b) left-align the body text with the title/header

image

 c) add these strings to `../en.json` file so it can be translated by our localization community.

4 - Converted channel is still listed under public channels More… list. Can click the Join button, and the modal closes (but the channel is not joined).

Expected: Converted channel does not appear in public channels More… list.

5 - Adding a diagnostic event to track how often Mattermost users use this feature.

I believe this should just be a two-line change to `../webapp/components/channel_convert_modal.jsxh`, similar to https://github.com/mattermost/platform/pull/5516/files#diff-4821c248760929f278cfda4b8c0e1fa3.

If you have questions about this one, let me know.

----

Below issues were found during testing, but I also found Jira tickets for them. So I suspect they were issues on the `master` branch a few weeks ago.

If you rebase your branch against `master`, the issues should get resolved

6 - https://mattermost.atlassian.net/browse/PLT-6948

7 - https://mattermost.atlassian.net/browse/PLT-6968

**Comment by ruzette** [comment]
Thanks! I'll update with those changes. :)

**Comment by jasonblais** [comment]
@ruzette Saw a few commits were pushed, appreciate it! :)

**Comment by jasonblais** [comment]
Hey @ruzette, how are things? Let me know if you need any help with the above changes?

**Comment by jasonblais** [comment]
@ruzette Heads up that Mattermost will be separating the `/platform` repo into two repositories on September 6th:
 - a new repository for webapp client code, hosted at github.com/mattermost/mattermost-webapp
 - existing repository (`/platform`) renamed to `/mattermost-server`, containing the server code.

Open PRs on September 6th may need to re-submit their pull request after the separation. For instance, PRs changing the UI would need to be re-submitted to the new `mattermost-webapp` repository.

**Comment by crspeller** [comment]
This PR needs to be re-submitted to the new separated webapp and server repositories.

**Pull request closed without merging**
