### PR TITLE
PLT-7870 Add some more diagnostics for plugins

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Add some more diagnostics for plugins. ~~Waiting on #7666.~~

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-7870

### CODE REVIEW

**Comment by jwilander** [comment]
@jasonblais I know we talked about sending hashes of plugin names/ids but upon some more consideration I'm thinking that might too intrusive because it'll be fairly easy to use the hash to guess what plugins are being used if they're open source. Instead I just counted the total plugins, and which are using webapp/backend portions. Thoughts?

**Comment by jasonblais** [comment]
Yep agree - if there's a way to reverse engineer which plugins are used, better not to collect it.

Does this correctly summarize the diagnostics for plugins?

1) config_plugins table:
 - enable_jira
 - enable (NEW)
 - enable_uploads (NEW)

2) plugins table (NEW): Send data once every 24 hours for each server, counting the number of plugins uploaded + how many of them use webapp and backend portions?

^can we also add a count of how many of those plugins are active vs inactive once the plugin states are added?

**Comment by jwilander** [comment]
Yes, that's accurate and yes was already planning on doing that with the plugin states implementation

**Comment by jwilander** [comment]
Need to rebase and add the states diagnostics

**Comment by jasonblais** [comment]
@jwilander Looks like this is good to merge apart from the build failure

**Comment by jwilander** [comment]
Looks like a random failure, re-running

**Pull request merged**
