### PR TITLE
Converting to structured logging the file api4/system_test.go

### PR DESCRIPTION
**Pull request by niklabh**
#### Summary

Converting to structured logging the file api4/system_test.go

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/12056

### CODE REVIEW

**Comment by lindalumitchell** [comment]
QA not needed on this PR; removing QA Review label.

**Comment by niklabh** [comment]
Here code don't seems to be doing anything useful. Just printing 1 to 20. Can we remove this loop

**Comment by gabrieljackson** [comment]
@niklabh, the code immediately following that loop gets the logs and looks for the 0-to-20 count log lines. We should probably keep this as part of the test.

**Comment by niklabh** [comment]
ok then please review the PR.

**Comment by niklabh** [comment]
If tests are expecting only 1 - 10 then i think we should not change the mlog behaviour here as per ticket. Can i close the pull request?

**Comment by niklabh** [comment]
fixed.

**Comment by niklabh** [comment]
Closing this as existing code should be the correct version. No change required in this ticket.

**Pull request closed without merging**
