### PR TITLE
[MM-30317] add manage_remote_clusters permission

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Add new `manage_remote_clusters` permission.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-30317

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by wiggin77** [comment]
Looks great @isacikgoz.  Will you be submitting the associated webapp and redux PR's?

**Comment by isacikgoz** [comment]
@wiggin77 Yes, I wanted get an approval to this one first :)

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by mkraft — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
Working as expected 
Updated with screenshots on Webapp PR
https://github.com/mattermost/mattermost-webapp/pull/7060

**Comment by amyblais** [comment]
@isacikgoz I removed v5.30 fix version from a few PRs based on https://community-release.mattermost.com/core/pl/qwq65andnibdtjwk5e1tjftiur. Concerns can be raised to me

**Pull request merged**
