### PR TITLE
[MM-37772] Idiomatic naming (URL, URI, API)

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This is a the seconds PR that changes identifies to use more idiomatic naming.

I intentional didn't change the field names of structs that are used to create DB columns like [`OAuthApp.CallbackUrls`](https://github.com/mattermost/mattermost-server/blob/fd853e74a6e81ae3ea642ec24dd2994dd3498727/model/oauth.go#L31) as `gorp` doesn't like it when you change field names.

In the future we might be able to enforce this via golangci-lint.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37772
https://mattermost.atlassian.net/browse/MM-37774
https://mattermost.atlassian.net/browse/MM-37770

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by streamer45** [comment]
@hanzei I am assuming you were able to confirm the deserialization from JSON is case insensitive?

**Comment by hanzei** [comment]
@streamer45 Yes. `encoding/json` does the deserialization case insensitive.

**Review by streamer45 — APPROVED** [review]
Nicely done :+1:

**Review by isacikgoz — APPROVED** [review]
LGTM

**Comment by amyblais** [comment]
@hanzei Is this a requirement for v6.0? If yes, can you help cherry-pick to the ``cloud`` branch? https://community.mattermost.com/core/pl/cmqefh9ue7dnxgfm1cirbcj9se

**Comment by hanzei** [comment]
@amyblais https://github.com/mattermost/mattermost-server/pull/18147 does already include this PR.

**Comment by hanzei** [comment]
@amyblais https://github.com/mattermost/mattermost-server/pull/18147 does already include this PR.

**Pull request merged**
