### PR TITLE
MM-33601: Invalidate team member cache when updating a team scheme.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Invalidates the team member cache when associating a team to an existing scheme so that the new team role is visible to the `(*App).SessionHasPermissionToTeam` authz method.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-33601

#### Release Note

```release-note
Fixed bug where team member permissions were not updated after associating a team and a permission scheme.
```

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]
LGTM

image

image

**Pull request merged**
