### PR TITLE
[MM-2307] Move plugin helpers from mattermost-server repository into mattermost-plugin-api

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary

This PR remove the plugin helpers in favor of the  [`pluginapi`](https://github.com/mattermost/mattermost-plugin-api) library.

This is a breaking change for plugin _compiling_ against v6.0.

Plugin compiled against a previous version of `mattermost-server` will work fine.

There will be a PR for adding the missing methods to https://github.com/mattermost/mattermost-plugin-api.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23077

#### Release Note
```release-note
Move plugin helpers from mattermost-server repository into mattermost-plugin-api
```

### CODE REVIEW

**Comment by lieut-data** [comment]
We've had some success hosting multiple Go modules in the same repository -- see  https://github.com/mattermost/mattermost-plugin-incident-collaboration/tree/master/client, which is versioned independently of the module at the root of the repository.

I wonder if we should consider folding the plugin-api directly into the mattermost-server repository, and just version it independently?

**Review by lieut-data — APPROVED** [review]
Deferring to @agnivade on how to handle the breaking semver change here.

**Review by agnivade — APPROVED** [review]
Looks good. There is a flaky test failure for which you need to sync with latest master.

IMO, I think it's good to let plugin-api be in its separate repo, and maintain the module per repo mental model. The server repo is already heavy as it is. There are some things (like shared) which don't belong in it.

**Comment by lieut-data** [comment]
> IMO, I think it's good to let plugin-api be in its separate repo, and maintain the module per repo mental model. The server repo is already heavy as it is. There are some things (like shared) which don't belong in it.

One pain point is that all changes to the Plugin API currently require two PRs (like the good old webapp/redux days). The alternative might be to move the Plugin API itself and have the server import that module accordingly.

**Comment by agnivade** [comment]
> The alternative might be to move the Plugin API itself and have the server import that module accordingly.

I support that idea :+1:

**Comment by hanzei** [comment]
> One pain point is that all changes to the Plugin API currently require two PRs (like the good old webapp/redux days). The alternative might be to move the Plugin API itself and have the server import that module accordingly.

Do you mean only the Plugin API interface or also the implementation? Would that approach sill require two PRs? (one "real" one for the plugin api repo and one "bump commit" one for the server)

**Comment by lieut-data** [comment]
> Do you mean only the Plugin API interface or also the implementation? Would that approach sill require two PRs? (one "real" one for the plugin api repo and one "bump commit" one for the server)

Ah, yeah, to bump it would require a second commit anyway. Good call :)

**Comment by hanzei** [comment]
@lieut-data @agnivade The discussion above seems orthogonal to this PR to me. If you don't object, I would like to merge it as it is and move the plugin API discussion to Mattermost.

**Comment by hanzei** [comment]
@DHaussermann Could you please test an existing plugin release against this PR and confirm that the plugin starts correctly?

**Comment by agnivade** [comment]
Yes, it's out of scope for this PR. This is good to go. Good stuff Ben.

**Comment by hanzei** [comment]
@agnivade Would you please merge this PR after QA is complete?

**Comment by metanerd** [comment]
Changing base branch to master, otherwise I am not able to delete release-6.0 branch

**Comment by mickmister** [comment]
@DHaussermann Probably a good idea to test the features of the demo app here

**Comment by DHaussermann** [comment]
Tested and passed 
- Installed and enabled various pre-existing plugging 
- No issues with install uninstall
- No issues with enable / disable
- No unexpected errors found in logs
- No unexpected behavior found when using the plugin form the user side

@hanzei this code change is working as expected when deployed. I'm sorry but this was only tested once your branch was re-based. Any thoughts on what the nest next steps are to get this merged?

**Comment by mickmister** [comment]
@DHaussermann Whoops I meant to say "demo plugin" not "demo app"

**Comment by DHaussermann** [comment]
@hanzei I'm seeing an issue where I can't upload plugins from the UI. The upload button is greyed-out even though I have `"EnableUploads": true`.
I see this behavior even when there is no Cloud license applied. 

Could this be related to your PRs? Strangely I see this happening on `master` as well.

Can you help me confirm this is unrelated? When you deploy this, set ``"EnableUploads": true`.` and have any non-cloud license (or no license) uploads should work is system console.

**Review by DHaussermann — APPROVED** [review]
Tested and passed again after rebase.

@hanzei  please merge.

**Comment by agnivade** [comment]
@hanzei - Sorry, I must have misunderstood this change. I am wondering if this change will break older plugins using a v6 server? If so, this will cause a lot of pain to customers trying to upgrade to v6 as they will have to rely on plugin owners to upgrade the plugin versions first.

**Comment by hanzei** [comment]
@agnivade The change only effects plugins compiled against v6. Plugin compiled against v5 will still work and have the helpers available as the code changes only touch the RPC client side, not the RPC server.

**Comment by agnivade** [comment]
Hmm .. ok I am not super familiar here. But I see that we are removing plugin/helpers_kv.go here. Will a v5 plugin making the `func (p *HelpersImpl) KVGetJSON` call still work on a v6 server? The code won't be there in the server.

**Comment by hanzei** [comment]
Yes. The plugin API must be preserved in order to provide comparability.

**Comment by agnivade** [comment]
Thanks Ben. Feel free to merge at your convenience.

**Pull request merged**
