### PR TITLE
MM-15961 Ensure postgres uses specific full text idx

### PR DESCRIPTION
**Pull request by svelle**
Created in reference to this. Credit for work and analysis to @feikesteenbergen 

https://github.com/mattermost/mattermost-server/pull/9893

### CODE REVIEW

**Comment by jasonblais** [comment]
Adding Work In Progress label.

Next step is to share a custom build with customer to see if this actually resolves the search issue for them.

**Comment by jasonblais** [comment]
@svelle Touching base if we shared the custom build with customer and if we heard any feedback from them?

PS: Looks like this is against the `master` branch, we may need to change the base branch to get a build against the release version the customer is running.

**Comment by svelle** [comment]
@jasonblais I sent out the custom build but haven't heard back from the customer yet. 
I'll update as soon as I know something. Thanks for the reminder! :)

**Comment by svelle** [comment]
@jasonblais I've got word back from the customer. The custom build fixed their issue.

Will we still be able to get this into 5.13? 
Anyways I'll update the branch to be in sync with master in the next days.

**Comment by jasonblais** [comment]
@svelle That's great news! Does the customer need the fix for 5.13, or is 5.14 sufficient? They were running on v5.2 earlier (I think), so may be fine to have the fix on 5.14.

**Comment by svelle** [comment]
@jasonblais seeing as they don't have any issues right now I think they'll be fine running the custom build till 5.14 comes out. 
Worst case they'll need another 5.13 custom build, but it's so few changes that I don't see any problem supplying that.

**Comment by jasonblais** [comment]
@svelle Great! Sounds good, will queue for 5.14. Jira ticket updated accordingly as well

**Comment by grundleborg** [comment]
@svelle looks like you need to merge master into this PR to get it working with the CI checks.

**Comment by svelle** [comment]
@grundleborg done!

**Comment by amyblais** [comment]
@svelle Can you help resolve the Jira ticket for QA https://mattermost.atlassian.net/browse/MM-15961?

**Comment by chibatpi** [comment]
Hi, @svelle,
```SQL
%s @@  to_tsquery(:Terms)
```
This does not support index, but it has good aspects that users can add their custom parser that is not supported by default, like CJK languages.
Hardcoding English excludes that option and make it difficult to search CJK texts, since they are not space delimited.

**Comment by chibatpi** [comment]
@svelle OK! I will begin with reading guideline. Thanks for the advice.

**Pull request merged**
