### PR TITLE
GH-11661 Add TLS 1.3 support

### PR DESCRIPTION
**Pull request by loganaden**
#### Summary

Add TLS 1.3 support

### CODE REVIEW

**Comment by DSchalla** [comment]
Hi @loganaden,

thanks for your PR - Since there is no ticket attached to it, what's the motivation of enable the opt-in TLS 1.3 support? I am currently hesitant to enable it, since it's still hidden behind a debug flag. If require for whatever reason, it can currently be enabled via a reverse proxy in front.

**Comment by loganaden** [comment]
@DSchalla this debug flag will be removed in the next version of golang. I don't mind waiting for the next version of golang, and then update the patch to address your concern.

**Comment by DSchalla** [comment]
Right, I'll wait for feedback of my colleagues on the matter, personally I don't have a strong feeling towards either option. Is there anything you are being blocked right now with the lacking TLSv1.3 support or is it just pushing for early adoption?

**Comment by crspeller** [comment]
Thanks for the PR! 
I am leaning towards waiting until it's not behind a flag. No need to rush support for beta cryptosystems.

**Comment by DSchalla** [comment]
@loganaden I'll close the PR then in the mean time - Once TLS 1.3 is officially released with Go a PR is more tahn welcome! Thanks.

**Pull request closed without merging**
