### PR TITLE
e2e: fix yearly subscription test

### PR DESCRIPTION
**Pull request by yasserfaraazkhan**
```release-note
NONE
```

### CODE REVIEW

**Comment by yasserfaraazkhan** [comment]
> @yasserfaraazkhan `more_channels_spec.js` is getting passed in the onprem run [e2e](https://automation-dashboard.vercel.app/cycle/324253) but its failing in the cloud run [e2e](https://automation-dashboard.vercel.app/cycle/324071)
> `yearly_subscription_spec.js` file does not exist in e2e result

@furqanmlk `yearly_subscription_spec.js ` is tagged with @cloud , will run with cloud and check.

**Review by AGMETEOR — APPROVED** [review]

**Comment by saturninoabril** [comment]
@yasserfaraazkhan I saw you ran this earlier than the image became available in DockerHub. If still happened in the future, this would be great for release team to know so we'll avoid frequent timeout when running E2E.
Screenshot 2023-04-20 at 5 21 13 PM

**Comment by yasserfaraazkhan** [comment]
> @yasserfaraazkhan I saw you ran this earlier than the image became available in DockerHub. If still happened in the future, this would be great for release team to know so we'll avoid frequent timeout when running E2E.
> Screenshot 2023-04-20 at 5 21 13 PM

Noted Saturn!

**Comment by saturninoabril** [comment]
I restarted all the failed jobs and now running on same pipeline/cycle - https://github.com/mattermost/mattermost-server/pull/22912#issuecomment-1515931437

**Pull request merged**
