### PR TITLE
[MM-48626] Move plugins environment out of Channels

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Revised version of #21697 

The problem with the previous implementation was we were initializing the plugins w/o assigning PluginService to the server. This was causing `nil` pointer dereference.

The problem can easily reproducable with starting the server plugins enabled and installed. Now we immediately assign the PluginService to the server. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48626

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by ashishbhate — APPROVED** [review]

**Comment by AshishDhama** [comment]
Removing myself I have don't have enough knowledge to review this PR

**Comment by agnivade** [comment]
@isacikgoz - Just checking on this one. Is there any urgtency on this? Asking because it is starting to accumulate some merge conflicts.

**Comment by isacikgoz** [comment]
> @isacikgoz - Just checking on this one. Is there any urgtency on this? Asking because it is starting to accumulate some merge conflicts.

@agnivade have a local updated version of this branch, needs a small fix then I'll push here.

**Comment by agnivade** [comment]
It's okay you already have 2 approvals :)

**Comment by isacikgoz** [comment]
Okay, one last e2e test after syncing with master and I think it should be okay. WDYT @metanerd? And maybe a quick cloud test server can help.

**Pull request merged**
