### PR TITLE
[MM-16330] Migrate "Channel.GetForPost" to Sync by default

### PR DESCRIPTION
**Pull request by piperRyan**
#### Summary

This pull request migrates "Channel.GetForPost" to sync and updates any impacted code caused by the change. 
#### Ticket Link

Resolves https://github.com/mattermost/mattermost-server/issues/11159

### CODE REVIEW

**Comment by lieut-data** [comment]
@piperRyan, thanks for this contribution! It looks like a few changes occurred upstream since you submitted this PR. Would you be open to merging `origin/master` and resolving those conflicts? Feel free to ping me or @jespino for help or to let us know that's done and we can get this merged.

**Comment by piperRyan** [comment]
@lieut-data Conflicts have been resolved.

**Comment by jespino** [comment]
@piperRyan Pleas, try to avoid the `push -f` when is possible (use merges and new commits) because if not, we have to review the entire thing again. Is not a big deal for this small PRs, so don't worry, but try to avoid it.

Anyway, we always "Squash and Merge" the PRs, so it will end up as 1 commit in the master branch.

**Comment by jespino** [comment]
Reviewed again and merged! Thanks @piperRyan! :confetti_ball:

**Pull request merged**
