### PR TITLE
[MM-16871] Remove bots from "Daily Active Users" and "Monthly Active Users"

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR removes bots from the Active User counts.  

One issue that took a while to figure out was how to test the status store.  There isn't a `Delete` method for the `Status Store` which means there wasn't a method to clean up the store after a test function completed.  

To solve this, I introduced a `cleanupStatusStore()` function which is called at the beginning of any test writing / accessing the `Status Store`.  It deletes all records form the status table.

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-16871

### CODE REVIEW

**Comment by levb** [comment]
@jfrerich it says that it needs to sync/merge - not sure if it's critical since there's no conflicts shown, but do you mind doing it please?

**Comment by jfrerich** [comment]
@levb Done.  Rebuild is happening now.  After a successful build, and all checks passing, would you like me to handle the merge to master and `CherryPick`?  I noticed from another ticket, we have and `AutoCherryPick` which is pretty awesome.

**Comment by aaronrothschild** [comment]
Documentation update here: https://github.com/mattermost/docs/pull/2896

**Comment by aaronrothschild** [comment]
Documentation Has been updated in 5.14 branch :  https://github.com/mattermost/docs/blob/v5.14-documentation/source/administration/statistics.rst

**Pull request merged**
