### PR TITLE
MM-23547: remove redundant JSON parsing in push notifications

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

We remove the redundant JSON serialization and de-serialization
and use a DeepCopy method to accomplish that. The gains are significant.

```
name                                 old time/op    new time/op    delta
SendPushNotificationToAllSessions-8    6.55µs ± 1%    1.60µs ± 1%  -75.59%  (p=0.000 n=9+9)

name                                 old alloc/op   new alloc/op   delta
SendPushNotificationToAllSessions-8    3.53kB ± 0%    1.78kB ± 0%  -49.67%  (p=0.000 n=10+10)

name                                 old allocs/op  new allocs/op  delta
SendPushNotificationToAllSessions-8      23.0 ± 0%       7.0 ± 0%  -69.57%  (p=0.000 n=10+10)
```

We use a custom benchmark to check this. Because the mock store is so heavy
it takes up the entire profile. And the logging spams the console.

This is the benchmark I have used to measure it.

```
// Run it with | grep -v '{"level"' to prevent spamming the console.
// To run this, we need to minimize interaction of other components.
// Otherwise the benchmarks pollute too much.
// We hardcode to some sessions, to avoid calling mock store
// -       sessions, err := a.getMobileAppSessions(userId)
// -       if err != nil {
// -               return err
// +       sessions := []*model.Session{
// +               {
// +                       Id:        "id1",
// +                       UserId:    "user1",
// +                       DeviceId:  "test1",
// +                       ExpiresAt: model.GetMillis() + 100000,
// +               },
// +               {
// +                       Id:        "id2",
// +                       UserId:    "user1",
// +                       DeviceId:  "test2",
// +                       ExpiresAt: model.GetMillis() + 100000,
// +               },
// +      }
// And we set logger.zap = zap.NewNop() in mlog.NewLogger
// And we also comment out the call to a.sendToPushProxy(tmpMessage, session).
func BenchmarkSendPushNotificationToAllSessions(b *testing.B) {
	th := SetupWithStoreMock(b)
	defer th.TearDown()

	handler := &testPushNotificationHandler{
		t:        b,
		behavior: "simple",
	}
	pushServer := httptest.NewServer(
		http.HandlerFunc(handler.handleReq),
	)
	defer pushServer.Close()

	b.ResetTimer()
	msg := &model.PushNotification{
		Type:       model.PUSH_TYPE_MESSAGE,
		PostId:     "test",
		SenderId:   "userID",
		ChannelId:  "channelID",
		Category:   model.CATEGORY_CAN_REPLY,
		Version:    model.PUSH_MESSAGE_V2,
		IsIdLoaded: true,
	}
	for i := 0; i < b.N; i++ {
		err := th.App.sendPushNotificationToAllSessions(msg, "userID", "id1")
		if err != nil {
			b.Logf("fail: %v", err)
		}
	}
}
```

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-23547

### CODE REVIEW

**Comment by agnivade** [comment]
ping @jespino

**Comment by lindy65** [comment]
Hi @agnivade - can you help with test steps please?

**Comment by agnivade** [comment]
I had marked the QA Testing Areas to be push notifications. Testing around that area should be sufficient.

**Comment by lindy65** [comment]
Ah, apologies - I missed that but just saw it on the ticket.  Is there any difference I should notice regarding push notifications or should they just work as per usual / expected?

**Comment by agnivade** [comment]
Nope, everything should work as expected. Thanks !

**Pull request merged**
