### PR TITLE
MM-29011: Add feature flag for shared channels

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-29011

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM.  Good call adding it to client config as well.  I'll add something similar to `License.Features` via another ticket.

**Comment by agnivade** [comment]
> Good call adding it to client config as well.

Yeah, otherwise the system console can't check that and gate the UI display depending on the config.

> I'll add something similar to License.Features via another ticket.

Yeah, I was thinking about that. Sounds good!

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Comment by agnivade** [comment]
Gentle ping on this @lindalumitchell. Just adds a new config setting with no visible result on the outside.

**Review by lindalumitchell — APPROVED** [review]
So sorry for the delay on this one! To not keep it any longer, I'll QA-defer it and check it after merge on a test server there (the old-style test server doesn't seem to be building, and I think that's the way I would be able to SSH in, but let's not hold this up as it's such a small change).

**Pull request merged**
