### PR TITLE
MM-42412: Skip TestStart/StopWorkers

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-42412

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@pablovelezvidal Is this related to the current CI failures in the v6.5 branch https://github.com/mattermost/mattermost-server/tree/release-6.5?

**Review by pablovelezvidal — APPROVED** [review]
thanks @agnivade

**Comment by pablovelezvidal** [comment]
yes @amyblais I think we need to get this one merged https://github.com/mattermost/enterprise/pull/1166

**Pull request merged**
