### PR TITLE
using inbucket docker image tag release-1.2.0 instead of latest

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Change the inbucket docker image to release-1.2.0 instead of latest.

#### Ticket Link
N/A

### CODE REVIEW

**Comment by jwilander** [comment]
@cpanato up to you if you want to merge as is or point to be a specific release per @ccbrown's suggestion

**Comment by cpanato** [comment]
@jwilander @ccbrown that makes a lot of sense. I will update. sorry for the delay

**Comment by cpanato** [comment]
made the changes @jwilander @ccbrown

**Comment by ccbrown** [comment]
> web/web.go:11:2: cannot find package "github.com/avct/uasurfer"

Nees a rebase I guess.

**Comment by cpanato** [comment]
@ccbrown @jwilander  PTAL 😄

**Pull request merged**
