### PR TITLE
MM-42570: Update dependencies

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-42570

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
@saturninoabril - Need a quick check please, thanks! :)

**Comment by saturninoabril** [comment]
Oh no, something failed pulling the PR branch :(. and I honestly don't have any clue why. I restarted the job and let's see how it's going - https://automation-dashboard.vercel.app/cycles/6dcd4639-1cf5-4f61-a028-1ceac3082af7

**Comment by saturninoabril** [comment]
Lots failed but I've seen others were known issues in the past. I'll run again just to make sure.

**Comment by saturninoabril** [comment]
@agnivade See test result [here](https://mattermost-cypress-report.s3.amazonaws.com/179351-2a7a163-onprem-ent-server-pr-19901-mattermost/mm-ee-test2a7a163/mochawesome.html). I haven't investigated yet but please take a look at failed test related to `/api/v4/email/test` and let me know if it's anything related to the changes here. Thanks.

**Comment by agnivade** [comment]
I think those are due to https://github.com/mattermost/mattermost-server/pull/19876. cc @isacikgoz. We need to change the tests to match with the API changes. They are more strict now.

**Comment by agnivade** [comment]
Ok found it

```
Cypress.Commands.add('apiEmailTest', () => {
    return cy.request({
        headers: {'X-Requested-With': 'XMLHttpRequest'},
        url: '/api/v4/email/test',
        method: 'POST',
    }).then((response) => {
        expect(response.status, 'SMTP not setup at sysadmin config').to.equal(200);
        return cy.wrap(response);
    });
});
```

This is actually how it's implemented in the system console for both email and s3. So we have introduced a regression. The API is designed in one way, but used in another way. I'll send a fix for this.

**Review by saturninoabril — APPROVED** [review]
Thanks @agnivade! Tested and passed. I'll go ahead and merge this then will update the referenced PR to run E2E again there.

**Pull request merged**
