### PR TITLE
remove stale bot in favor of mattermod

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Removing the Stale Bot in favor of mattermod.
I've implemented the same feature in Mattermod and with that, we can extend for more commands.
For now it is doing the same as the Stale Bot, however, it is not removing the label when someone make a comment.

we can add a command in a near future to remove the label when triggered by a person with permissions, for that we will need to implement the Owners File then we can check of the user have or not permission

When approved i will merge this and remove the permission from stale to see the repo and deploy mattermod with this change.

### CODE REVIEW

**Comment by cpanato** [comment]
@hanzei any comments?

**Comment by cpanato** [comment]
@hanzei will deploy mattermod

**Comment by hanzei** [comment]
This there a PR that I can review? Or this the code already merged?

**Comment by cpanato** [comment]
@hanzei i will open a PR to you check

**Comment by hanzei** [comment]
This can be merged after https://github.com/mattermost/mattermost-mattermod/pull/26.

**Pull request merged**
