### PR TITLE
Bumped Zoom plugin to v1.1.2

### PR DESCRIPTION
**Pull request by levb**
#### Summary
Bumped the Zoom plugin version to 1.1.2, fixing the webhook bug

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19716

### CODE REVIEW

**Comment by levb** [comment]
cc @amyblais @marianunez

**Comment by DHaussermann** [comment]
@jwilander or @cpanato I'm not sure where I'd get the logs mentioned above for why the server creation is failing. Is this something someone from cloud team would need to investigate or are they accessible somewhere?

**Comment by levb** [comment]
@DHaussermann the release is already on community, you can test there perhaps to get this PR merged?

**Comment by levb** [comment]
Manually cherry-picked into 5.17

**Pull request merged**
