### PR TITLE
[chore] Doubling the instance size used for CI

### PR DESCRIPTION
**Pull request by phoinixgrr**
#### Summary

This is to compensate for increased memory usage for DB Tests running with `-race` option. 

image

Go process consuming 24GB RSS, then system is rendered as unresponsive, (crashing) due to memory depletion.
Therefore, we are doubling the system memory, from 32GB to 64GB to compensate for the increased usage. 

#### Ticket Link

Ticket: https://mattermost.atlassian.net/browse/CLD-4014

#### Release Note

```release-note

```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
This bumps up the class for all jobs. I thought we were planning to do it only for test?

**Comment by phoinixgrr** [comment]
> This bumps up the class for all jobs. I thought we were planning to do it only for test?

This bumps up the class, for non Docker running jobs. 

The effect of the change can be witnessed here: https://app.circleci.com/pipelines/github/mattermost/mattermost-server/36411/workflows/60940ab5-f2da-4a6c-ad5f-be4008ef063d

**Comment by agnivade** [comment]
Okay, I will leave it up to you.

To actually run the race tests, let's add the `-race` flag like in: https://github.com/mattermost/mattermost-server/pull/20886/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R655 and confirm that it fixes the issue. Then we can revert it, and merge the PR if everything goes well.

**Comment by phoinixgrr** [comment]
@agnivade 
Cherry picked `a2e276240f94631496d5daa2d826268b48d8e374` to this branch, and restarted tests

**Comment by agnivade** [comment]
Umm .. no we don't want to cherry-pick :P That has the `GOMAXPROCS` restriction as well. Just the `-race` flag is what we want. Sorry for any confusion.

**Comment by phoinixgrr** [comment]
> Umm .. no we don't want to cherry-pick :P That has the `GOMAXPROCS` restriction as well. Just the `-race` flag is what we want. Sorry for any confusion.

👍  Ha! 
No problem, I've rebased and pushed https://github.com/mattermost/mattermost-server/compare/198c088f9786a7bc491e8e933aa41717d0db6467..12330eabb71d8d8a8845a19c48e4825c718288b7 

Tests re-started

**Review by pfltdv — APPROVED** [review]

**Review by agnivade — APPROVED** [review]

**Pull request merged**
