### PR TITLE
[MM-4819]  Add MinimumHashtagLength config

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary
Add `MinimumHashtagLength` config

#### Ticket Link
#9156 
https://mattermost.atlassian.net/browse/MM-4819

#### Checklist
N/A

### CODE REVIEW

**Comment by hanzei** [comment]
@jespino @mgdelacroix Can you please review when you have the time?

**Comment by mgdelacroix** [comment]
Hi @kaakaa. Thank you very much for your contribution!

We are waiting on [PR #2349](https://github.com/mattermost/mattermost-webapp/pull/2349) to be able to review both as one feature.

**Comment by kaakaa** [comment]
Thank you for heads-up @mgdelacroix 
I think that [PR #2349](https://github.com/mattermost/mattermost-webapp/pull/2349) have been ready for review. sorry.

**Comment by kaakaa** [comment]
@mgdelacroix Ah...I found my mistakes, so I made additional commit https://github.com/mattermost/mattermost-webapp/pull/2349/commits/0c4ea0baf7a37f4296258d60d78fc874c0531aed.

And mobile app doesn't seem to recognize minimumHashtagLength setting...  I would need a little more time for fixing mobile app, because I don't have enough knowledge about codebase of mattermost-mobile.
When completing to fix mobile app, I'll call you again. Thank you.

**Comment by kaakaa** [comment]
Hey @mgdelacroix. 
I've fixed [mobile](https://github.com/mattermost/mattermost-mobile/pull/2583) too. This feature is ready for reviews now, please take a look!

**Comment by hanzei** [comment]
Hey @mgdelacroix, @jespino,

Could you please review when you have the time? Thanks!

**Pull request merged**
