### PR TITLE
MM-45198: Migrate app/import and api4/import

### PR DESCRIPTION
**Pull request by agnivade**
We migrate them to use logger context.

https://mattermost.atlassian.net/browse/MM-45198

```release-note
NONE
```

### CODE REVIEW

**Review by noxer — APPROVED** [review]
Nice work

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
Failures unrelated: https://mattermost-cypress-report.s3.amazonaws.com/230386-f61d0e6-onprem-ent-server-pr-20799-mm-ee-test:f61d0e6/mochawesome.html. Merging.

**Pull request merged**
