### PR TITLE
MM-49077: fixes errors in migration job

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

`UrgentMentionCount` does not have a default values, so `COALESCE` has to be used.
`SELECT * FROM ChannelMembers` fails for the above reason. This commit `SELECT`s each and every column from `ChannelMembers` instead.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49077

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Comment by amyblais** [comment]
@stylianosrigas / @mkraft Please help prioritize this PR review.

**Review by mkraft — APPROVED** [review]

**Comment by amyblais** [comment]
@koox00 Does this need QA review?

**Comment by koox00** [comment]
no, no QA needed, I just updated the branch and I'll merge just after it builds, thanks @amyblais

**Pull request merged**
