### PR TITLE
MM-21094 Add missing diagnostics for 5.18 release

### PR DESCRIPTION
**Pull request by jasonblais**
#### Summary
@hahmadia https://github.com/mattermost/mattermost-server/pull/13018
@sbishel https://github.com/mattermost/mattermost-server/pull/12362
@ali-farooq0 https://github.com/mattermost/mattermost-server/pull/13017

This list is based on Amy's changelog summary at https://github.com/mattermost/docs/pull/3164/files#r355637942

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21094

### CODE REVIEW

**Comment by amyblais** [comment]
@ali-farooq0 Kind reminder to review this for v5.18.

**Comment by jasonblais** [comment]
I don't have permissions to merge, @ali-farooq0 / @hahmadia would one of you be open to own merging and cherry-picking to 5.18 release branch?

**Comment by hahmadia** [comment]
@jasonblais Done!

**Comment by jasonblais** [comment]
Thanks!!

**Pull request merged**
