### PR TITLE
MM-27688-OpenId Connect

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Implements OpenId Connect as part of current OAuth implemenation.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-27688

#### Related PRs
https://github.com/mattermost/mattermost-webapp/pull/7027
https://github.com/mattermost/enterprise/pull/819

#### Release Note
```release-note
added OpenId Connect as new OAuth Provider (E20)
```

### CODE REVIEW

**Review by jupenur — APPROVED** [review]
Looks reasonable. This is from the OIDC spec:

> If the ID Token is received via direct communication between the Client and the Token Endpoint (which it is in this flow), the TLS server validation MAY be used to validate the issuer in place of checking the token signature.

So it's as you suspected, Scott, we don't need to validate signatures, which makes everything a whole lot easier.

**Review by mkraft — APPROVED** [review]

**Review by hahmadia — APPROVED** [review]

**Review by furqanmlk — APPROVED** [review]

**Comment by cwarnermm** [comment]
Documentation updated via: 
- https://mattermost.atlassian.net/browse/MM-32653
- https://mattermost.atlassian.net/browse/MM-32654

**Pull request merged**
