### PR TITLE
MM-42271: Restrict support packet generation to system admin.

### PR DESCRIPTION
**Pull request by mkraft**
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-42271

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Review by sbishel — APPROVED** [review]

**Review by srkgupta — APPROVED** [review]
Thanks @mkraft. The changes LGTM. Also tested them and they were found to be working fine as expected.

**Comment by srkgupta** [comment]
Hi @mkraft 

Please note that this needs to be backported. 

cc: @amyblais

**Comment by amyblais** [comment]
Saturn had triggered e2e testing, so I added @furqanmlk to check that (Saturn will be off for the next few days).

**Review by furqanmlk — APPROVED** [review]
No issue found in E2E results

**Comment by mkraft** [comment]
> @mkraft This can also be cherry-picked to `release-6.4`, `release-6.3`, `release-6.2`, `release-5.37`, and `cloud`.

Done.

**Pull request merged**
