### PR TITLE
chore: Replaced used of O,P,D,G with constants file

### PR DESCRIPTION
**Pull request by codedsun**
#### Ticket Link

 Fixes https://github.com/mattermost/mattermost-server/issues/19150

JIRA: https://mattermost.atlassian.net/browse/MM-37132
#### Release Note

NONE

```release-note

```

### CODE REVIEW

**Comment by codedsun** [comment]
This is a work in progress PR for now

**Comment by agnivade** [comment]
@codedsun - The build is failing with several type conversion failures:

```
store/sqlstore/channel_store.go:3577: cannot use model.ChannelTypeDirect (type model.ChannelType) as type string in slice literal
store/sqlstore/channel_store.go:3577: cannot use model.ChannelTypeGroup (type model.ChannelType) as type string in slice literal
store/sqlstore/compliance_store.go:336: use of builtin append not in function call
store/sqlstore/compliance_store.go:337: cannot use query (type model.ChannelType) as type string in argument to s.SqlStore.GetReplicaX().Select
store/sqlstore/post_store.go:2457: cannot use reflect.ValueOf(model.ChannelTypeDirect) (type reflect.Value) as type string in slice literal
store/sqlstore/post_store.go:2457: cannot use reflect.ValueOf(model.ChannelTypeGroup) (type reflect.Value) as type string in slice literal
store/sqlstore/team_store.go:518: cannot use channelType (type model.ChannelType) as type *string in assignment
store/sqlstore/team_store.go:526: cannot use model.ChannelTypePrivate (type model.ChannelType) as type *string in assignment
store/sqlstore/user_store.go:1337: cannot use query (type model.ChannelType) as type string in argument to us.SqlStore.GetReplica().SelectInt
# github.com/mattermost/mattermost-server/v6/store/sqlstore [github.com/mattermost/mattermost-server/v6/utils/fileutils.test]
store/sqlstore/channel_store.go:3577: cannot use model.ChannelTypeDirect (type model.ChannelType) as type string in slice literal
store/sqlstore/channel_store.go:3577: cannot use model.ChannelTypeGroup (type model.ChannelType) as type string in slice literal
store/sqlstore/compliance_store.go:336: use of builtin append not in function call
store/sqlstore/compliance_store.go:337: cannot use query (type model.ChannelType) as type string in argument to s.SqlStore.GetReplicaX().Select
store/sqlstore/post_store.go:2457: cannot use reflect.ValueOf(model.ChannelTypeDirect) (type reflect.Value) as type string in slice literal
store/sqlstore/post_store.go:2457: cannot use reflect.ValueOf(model.ChannelTypeGroup) (type reflect.Value) as type string in slice literal
store/sqlstore/team_store.go:518: cannot use channelType (type model.ChannelType) as type *string in assignment
store/sqlstore/team_store.go:526: cannot use model.ChannelTypePrivate (type model.ChannelType) as type *string in assignment
store/sqlstore/user_store.go:1337: cannot use query (type model.ChannelType) as type string in argument to us.SqlStore.GetReplica().SelectInt
```

I am starting to think that except for places where the type is parameterized, we should leave it alone. The string concatenations make the code hard to read. Any thoughts @streamer45 ?

**Comment by streamer45** [comment]
> I am starting to think that except for places where the type is parameterized, we should leave it alone. The string concatenations make the code hard to read. Any thoughts @streamer45 ?

Agreed. Maybe, since most concatenations seem to appear in queries, we could parameterize them instead.

**Comment by agnivade** [comment]
> Agreed. Maybe, since most concatenations seem to appear in queries, we could parameterize them instead.

Yeah, I think some of them have already been done in this PR, but doing everything would be a bit out of scope for this PR.

**Comment by agnivade** [comment]
@codedsun - Just checking in to see how is this going? As discussed above, the suggestion is to remove any string concatenations and keep them as is. Only change the string for parameterized values.

**Comment by codedsun** [comment]
@agnivade Hi, I am currently contributing to dekstop contributor event, i will be back on this by 4/5 Feb. Thank you for your guidance and concern.

**Comment by agnivade** [comment]
@codedsun - I'll close this as the issue is already resolved now. Looking forward to more of your contributions!

**Pull request closed without merging**
